Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2018-12, with the labels that each got.

#60 Fixes infinite medevac stretcher duplication.
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix

#49 Update marine_shoes.dm - Adds Armor protect flags to marine shoes and PMC shoes.
  code/modules/clothing/shoes/marine_shoes.dm
Labels: Tweak

#51 Adds M42A Ice Colony back sprite variant.
  icons/mob/back.dmi
Labels: Sprites

#52 Fixes killer ice.
  code/modules/reagents/chemistry_reagents/alcohol.dm
  code/modules/reagents/chemistry_reagents/drink.dm
  code/modules/reagents/chemistry_reagents/food.dm
Labels: Fix

#57 Replaces clothing error sprites with more appropriate ones.
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#65 Allows magnetic harness to work with more armors.
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
Labels: Balance/Rebalance, Tweak

#83 Allows the underbarrel flamer to be reloaded with more things.
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Feature

#79 Adds surgical apron, white webbing, fixes cat ears.
  code/__DEFINES/mobs.dm
  code/datums/supplypacks.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/ties.dm
  code/modules/surgery/surgery.dm
  icons/mob/suit_0.dmi
  icons/mob/ties.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/ties_overlay.dmi
Labels: Fix, Sprites

#99 Adds north facing Dropship chair sprite
  icons/obj/objects.dmi
Labels: Sprites

#92 Makes orders macro-able using the issue-order "order" verb
  code/modules/cm_marines/overwatch.dm
Labels: Balance/Rebalance

#105 fixes flamethrower inhands
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
Labels: Sprites

#89 New Tank Sprites
  icons/obj/vehicles/Cannon_Animation_E-W.gif
  icons/obj/vehicles/Cannon_Animation_N-S.gif
  icons/obj/vehicles/Chaingun_Animation.gif
  icons/obj/vehicles/Chaingun_Animation_N-S.gif
  icons/obj/vehicles/armor_EW_camo.dmi
  icons/obj/vehicles/armor_NS_camo.dmi
  icons/obj/vehicles/hardpoint_modules.dmi
  icons/obj/vehicles/tank_EW.dmi
  icons/obj/vehicles/tank_EW_camo.dmi
  icons/obj/vehicles/tank_NS.dmi
  icons/obj/vehicles/tank_NS_camo.dmi
Labels: Sprites

#74 Halloss From Tackles Respects Armor
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Balance/Rebalance

#50 Makes rail attachments macro-able.
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
Labels: Feature

#67 Walls (see #1)
  icons/obj/structures/window_frames.dmi
  icons/obj/structures/windows.dmi
  icons/turf/chigusa.dmi
Labels: Sprites

#66 Better Computer Colors
  icons/obj/machines/computer.dmi
Labels: Sprites

#55 Fixes AI sprite hitbox on death.
  code/modules/mob/death.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
Labels: Fix

#59 Distress call bugfixes.
  code/__DEFINES/mode.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/pizza.dm
  code/game/gamemodes/cm_self_destruct.dm
  code/game/machinery/computer/communications.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/security levels/keycard authentication.dm
  code/modules/security levels/security levels.dm
Labels: Fix

#61 Reworks the OOC > Observe verb to be more functional
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_verbs.dm
Labels: Fix

#82 TGS Theseus
  ColonialMarinesALPHA.dme
  code/game/turfs/floor_types.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/turf/almayer.dmi
  maps/Z.03.TGS_Theseus.dmm
  maps/Z.03.USS_Almayer.dmm
Labels: Sprites

#63 Fixes zone select runtimes.
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  code/modules/mob/mob_helpers.dm
  interface/skin.dmf
Labels: Fix

#95 Adds Beretta sprite to holsters
  icons/obj/clothing/belts.dmi
Labels: Sprites

#101 Adds handholding.
  code/modules/mob/mob.dm
Labels: Feature, Priority: High

#62 Gives seed packs their proper name.
  code/modules/hydroponics/seeds.dm
Labels: Fix

#96 Smartgun powerpack and powerloader cells are now interactable.
  code/game/machinery/vending/vending.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/vehicles/powerloader.dm
Labels: Balance/Rebalance, Tweak

#71 B18 + Scout Cloak Tweaks For The Third Fucking Time
  ColonialMarinesALPHA.dme
  code/__DEFINES/mobs.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/machinery.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/suit_procs.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life/handle_organs.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/organs/limbs.dm
  code/modules/organs/pain.dm
  code/modules/surgery/bones.dm
  sound/voice/b18_activate.ogg
  sound/voice/b18_antitoxin.ogg
  sound/voice/b18_antitoxin2.ogg
  sound/voice/b18_brute.ogg
  sound/voice/b18_fracture.ogg
  sound/voice/b18_pain_suppress.ogg
  sound/voice/ib_detected.ogg
Labels: Sound, Tweak

#121 Slightly changes rank colors in-game.
  code/game/verbs/ooc.dm
  config/config.txt
Labels: Config Update

#115 Mortar restriction for synth
  code/modules/cm_marines/equipment/mortars.dm
Labels: Balance/Rebalance

#146 Fixed Rear Flip Bug for Crest Toss
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Fix

#117 Sentry sprite + build rework
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/modules/cm_marines/equipment/sentries.dm
  icons/Marine/new_sentry.dmi
  icons/Marine/new_sentry_alt.dmi
Labels: Sprites

#113 New Weeds (see #3)
  icons/Xeno/Effects.dmi
  icons/Xeno/weeds.dmi
  icons/Xeno/weeds_alt.dmi
  icons/mob/actions.dmi
Labels: Sprites

#122 Locker Conversion
  icons/obj/structures/closet.dmi
Labels: Sprites

#150 Adds adjust_bodytemperature() and fixes tactical donuts.
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/reagents.dm
  code/datums/diseases/advance/symptoms/fever.dm
  code/datums/diseases/advance/symptoms/shivering.dm
  code/datums/diseases/cold9.dm
  code/datums/diseases/fluspanish.dm
  code/game/machinery/spaceheater.dm
  code/game/objects/items/devices/suit_cooling.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/human/life/handle_environment.dm
  code/modules/mob/living/carbon/human/life/handle_fire.dm
  code/modules/mob/living/carbon/human/life/life_helpers.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/mob_status_procs.dm
  code/modules/organs/limbs.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/chemistry_reagents/alcohol.dm
  code/modules/reagents/chemistry_reagents/drink.dm
  code/modules/reagents/chemistry_reagents/food.dm
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: Fix

#116 T3 Rise of the Machines (Porting Machine Sprites)
  icons/obj/aibots.dmi
  icons/obj/kitchen.dmi
  icons/obj/machines/biogenerator.dmi
  icons/obj/machines/drone_fab.dmi
  icons/obj/machines/hydroponics.dmi
  icons/obj/machines/library.dmi
  icons/obj/machines/mining_machines.dmi
  icons/obj/machines/research.dmi
  icons/obj/machines/virology.dmi
  icons/obj/robotics.dmi
  icons/obj/stationobjs.dmi
  icons/obj/structures/misc.dmi
  icons/obj/vehicles.dmi
Labels: Sprites

#161 Updates tank ammo and fixes sentry ammo sprite
  icons/obj/items/ammo.dmi
Labels: Sprites

#160 Replacing Cargo Lift Sprites
  icons/obj/elevator_strut.dmi
Labels: Sprites

#165 Image pooling removal in prep for stonedmc
  code/__HELPERS/game.dm
  code/_onclick/hud/fullscreen.dm
  code/game/objects/items/devices/motion_detector.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/tools/shovel_tools.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/walls/walls.dm
  code/modules/animations/animation_library.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/cm_preds/yaut_items.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/power/singularity/emitter.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Refactor, Removal

#167 Removes turf deletions and replaces them with proper ChangeTurf calls.
  code/game/objects/items/explosives/plastique.dm
  code/game/turfs/walls/wall_types.dm
  code/game/turfs/walls/walls.dm
  code/modules/shuttles/shuttle.dm
Labels: Refactor, Removal

#156 New Shoes
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Sprites, Work In Progress

#158 Armor storage bugfix
  code/modules/clothing/suits/marine_armor.dm
Labels: Fix

#168 Renames var/disposed to var/gc_destroyed in prep for stonedmc
  code/ATMOSPHERICS/pipes.dm
  code/_onclick/click.dm
  code/_onclick/telekinesis.dm
  code/controllers/ProcessScheduler/stubs.dm
  code/controllers/branches/trash_collector.dm
  code/controllers/branches/trash_recycler.dm
  code/game/atoms_movable.dm
  code/game/machinery/groundmap_geothermal.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/toys/cards.dm
  code/game/objects/structures/girders.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/debug.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/cm_aliens/weeds.dm
  code/modules/cm_marines/dropship_ammo.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/economy/cash.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/organs/limbs.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/reagents/Chemistry-Holder.dm
Labels: Refactor

#169 Removes all uses of Recycle()
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/clothing/glasses/meson.dm
  code/modules/clothing/glasses/night.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/cm_preds/yaut_items.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Removal

#140 More Bioscan changes.
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/cm_process.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  config/config.txt
Labels: Config Update

#103 Ammo HUD
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/cm_marines/super_secret.dm
  code/modules/cm_preds/yaut_items.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/magazines/flamer.dm
  code/modules/projectiles/updated_projectiles/magazines/misc.dm
  icons/mob/ammoHUD.dmi
Labels: Sprites

#164 End of Round Deathmatch
  code/__DEFINES/mode.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/xeno.dm
  code/game/area/Space Station 13 areas.dm
  code/game/gamemodes/cm_process.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/game/gamemodes/game_mode.dm
  code/global.dm
  code/modules/client/preferences.dm
  maps/Z.02.Admin_Level.dmm
Labels: Feature

#151 Fixes dropships.
  code/__DEFINES/__game.dm
  code/__DEFINES/skills.dm
  code/controllers/communications.dm
  code/controllers/shuttle_controller.dm
  code/datums/fluff_emails.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/jobs/job/shipside.dm
  code/game/machinery/air_alarm.dm
  code/game/machinery/camera/presets.dm
  code/game/machinery/computer/emails.dm
  code/game/machinery/fusion_engine.dm
  code/game/objects/items/XMAS.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/structures/window_frame.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/admin/topic.dm
  code/modules/almayer/machinery.dm
  code/modules/cm_marines/codebook.dm
  code/modules/cm_marines/dropship_equipment.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/cm_marines/shuttle_backend.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/hostile/shyguy.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  code/modules/shuttles/escape_pods.dm
  code/modules/shuttles/marine_ferry.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/shuttles/shuttle_ert.dm
  interface/interface.dm
  interface/skin.dmf
Labels: Fix

#141 Adds east turnstile sprite
  icons/Marine/barricades.dmi
Labels: Sprites

#148 Distress call refactor. Better job datum equipments.
  code/datums/emergency_calls/clf.dm
  code/datums/emergency_calls/colonists.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/freelancers.dm
  code/datums/emergency_calls/pizza.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/emergency_calls/supplies.dm
  code/datums/emergency_calls/upp.dm
  code/datums/emergency_calls/upp_commando.dm
  code/datums/emergency_calls/xeno.dm
  code/datums/skills.dm
  code/game/gamemodes/cm_self_destruct.dm
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/jobs/access.dm
  code/game/jobs/job/clf.dm
  code/game/jobs/job/freelancers.dm
  code/game/jobs/job/marines.dm
  code/game/jobs/job/mercenaries.dm
  code/game/jobs/job/other.dm
  code/game/jobs/job/pmc.dm
  code/game/jobs/job/shipside.dm
  code/game/jobs/job/squads.dm
  code/game/jobs/job/upp.dm
  code/modules/admin/admin.dm
  code/modules/admin/verbs/select_equipment.dm
Labels: Refactor

#143 Engineer technician backpack fixed so it can carry stuff it should
  code/game/objects/items/storage/backpack.dm
Labels: Fix

#154 Warrior Cooldowns Fixed
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance/Rebalance

#149 Two letter grammatical fix.
  code/game/jobs/job/job.dm
Labels: Grammar and Formatting

#174 Removes files for a second time that lakiller re-added.
  code/WorkInProgress/computer3/NTOS.dm
  code/WorkInProgress/computer3/computers/welcome.dm
  code/WorkInProgress/computer3/lapvend.dm
Labels: Removal

#159 M56D improvements
  code/modules/admin/admin_verbs.dm
  code/modules/cm_marines/smartgun_mount.dm
Labels: Fix, Tweak

#175 Replaces processing_objects calls with macros in prep for stonedmc an…
  code/__HELPERS/global_lists.dm
  code/controllers/processes/_objects.dm
  code/controllers/processes/second.dm
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/door_control.dm
  code/game/machinery/fire_alarm.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items/ashtray.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/motion_detector.dm
  code/game/objects/items/devices/portable_vendor.dm
  code/game/objects/items/devices/powersink.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/devices/suit_cooling.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implantneurostim.dm
  code/game/objects/items/reagent_containers/borghydro.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/objs.dm
  code/modules/assembly/assembly.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/proximity.dm
  code/modules/assembly/signaler.dm
  code/modules/assembly/timer.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/hazresearch/haz_gas.dm
  code/modules/cm_marines/machinegun.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/cm_preds/yaut_items.dm
  code/modules/hydroponics/vines.dm
  code/modules/mining/mint.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/organs/organ_objects.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
Labels: Refactor

#142 fixes map issues
  maps/Z.03.TGS_Theseus.dmm
Labels: Map Edit

#181 Emergency armor lasgun
  code/modules/clothing/suits/marine_armor.dm
Labels: Fix

#180 Deathmatch tweaks and fixes.
  code/game/gamemodes/cm_process.dm
  code/game/gamemodes/game_mode.dm
  code/modules/client/preferences.dm
  maps/Z.02.Admin_Level.dmm
Labels: Feature, Fix

#104 Port of port of Flora code improvement
  ColonialMarinesALPHA.dme
  code/game/objects/items/XMAS.dm
  code/game/objects/structures/flora.dm
  icons/obj/flora/ausflora.dmi
  icons/obj/flora/deadtrees.dmi
  icons/obj/flora/joshuatree.dmi
  icons/obj/flora/jungleflora.dmi
  icons/obj/flora/jungletrees.dmi
  icons/obj/flora/jungletreesmall.dmi
  icons/obj/flora/largejungleflora.dmi
  icons/obj/flora/pinetrees.dmi
  maps/Z.03.TGS_Theseus_2.dmm
Labels: Sprites

#173 process() definition change in prep for stonedmc
  code/ATMOSPHERICS/datum_pipeline.dm
  code/__DEFINES/misc.dm
  code/controllers/ProcessScheduler/process.dm
  code/controllers/ProcessScheduler/processScheduler.dm
  code/controllers/lighting_controller.dm
  code/controllers/shuttle_controller.dm
  code/controllers/voting.dm
  code/datums/disease.dm
  code/datums/helper_datums/global_iterator.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gameticker.dm
  code/game/machinery/embedded_controller/embedded_program_base.dm
  code/game/machinery/kitchen/processor.dm
  code/game/objects/objs.dm
  code/game/supplyshuttle.dm
  code/modules/events/event.dm
  code/modules/nano/nanoui.dm
  code/modules/organs/limbs.dm
  code/modules/organs/organ_internal.dm
  code/modules/power/powernet.dm
  code/modules/shuttles/shuttle_ferry.dm
Labels: Refactor

#185 Fixes Scout Detector Icon Reverting
  code/game/objects/items/devices/motion_detector.dm
Labels: Fix

#186 Fixes shaking drone fabricator and centers it
  icons/obj/machines/drone_fab.dmi
Labels: Sprites

#171 Fixes windows
  icons/obj/structures/window_frames.dmi
  icons/obj/structures/windows.dmi
Labels: Sprites

#144 ammo_datums.dm wrong spacing fix
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Fix

#177 Allows the IMS to be used for necrosis surgery (again)
  code/modules/surgery/necrosis.dm
Labels: Balance/Rebalance

#172 Breathe Easy
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Sprites

#179 Remove repeated definitions, dirty code and undefined undefinition.
  code/__DEFINES/objects.dm
  code/game/gamemodes/colonialmarines/huntergames.dm
  code/modules/cm_marines/Marine_Research/Marine_Research_Console.dm
  code/modules/reagents/chemistry_reactions/other.dm
  code/modules/research/designs.dm
Labels: Fix

#184 Theseus Medical Door Sprite Edit
  icons/obj/doors/almayer/2x1medidoor.dmi
  icons/obj/doors/almayer/medidoor.dmi
Labels: Sprites

#88 Wounded Xeno Overlays
  code/modules/mob/living/carbon/xenomorph/Castes/Crusher.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Defender.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Drone.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hunter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Larva.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Predalien.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Runner.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Spitter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  icons/Xeno/wound_overlays.dmi
Labels: Sprites

#183 renames areas
  code/game/area/Space Station 13 areas.dm
Labels: Grammar and Formatting

#189 Xeno Datum Fixes + Defender Nerf
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Crusher.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Defender.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Praetorian.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance/Rebalance

#157 New Buildable: Razorwire
  ColonialMarinesALPHA.dme
  code/__DEFINES/objects.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/razorwire.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Crusher.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_verbs.dm
  icons/obj/structures/barbedwire.dmi
Labels: Sprites

#112 RoleAuthority, GameTicker code refactor. Squad assignment improvements.
  code/__DEFINES/mode.dm
  code/datums/mind.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gameticker.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/jobs/job/squads.dm
  code/game/jobs/role_authority.dm
  code/modules/admin/verbs/select_equipment.dm
  code/modules/client/preferences.dm
  code/modules/cm_marines/marines_consoles.dm
  code/modules/cm_marines/overwatch.dm
Labels: Refactor, Sprites

#91 New Sentinel Ability: Neurotoxin Sting
  code/__DEFINES/mobs.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/reagents/chemistry_reagents/other.dm
  icons/mob/actions.dmi
Labels: Sprites

#106 ColonialMarinesALPHA.dme to tgmc.dme
  .travis.yml
  tgmc.dme
  tools/travis/build_byond.sh
Labels: Tools

#193 Fixes PMC Smartgunner, tweaks UPP equipment.
  code/game/jobs/job/pmc.dm
  code/game/jobs/job/upp.dm
Labels: Fix, Tweak

#166 adds some end of round statistics
  code/__DEFINES/__game.dm
  code/datums/round_statistics.dm
  code/game/gamemodes/cm_process.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/extended/infection.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/modules/client/preferences_toggles.dm
  code/modules/cm_aliens/weeds.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Feature

#210 Minor refactor of energy gun init.
  code/modules/projectiles/updated_projectiles/guns/energy.dm
Labels: Refactor

#208 adds skub
  code/game/objects/items/misc.dm
  icons/obj/items/weapons.dmi
Labels: Feature, Sprites
