Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2019-07, with the labels that each got.

#2163 A slight photo refactor
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  code/datums/datacore.dm
  code/game/objects/items/gift_wrappaper.dm
  code/game/objects/machinery/computer/security.dm
  code/game/objects/machinery/newscaster.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/paperwork/photocopier.dm
  code/modules/paperwork/photography.dm
Labels: Map Edit, Refactor

#2169 Fixes some more mind dirtyness
  code/datums/emergency_calls/emergency_call.dm
  code/datums/jobs/squads.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/living_verbs.dm
Labels: Fix, Requires Testing

#2162 Allows the queen to override shuttle lockdown
  code/modules/shuttle/marine_dropship.dm
Labels: Balance/Rebalance

#2168 Fixes dropship interface visual issue
  code/modules/shuttle/marine_dropship.dm
Labels: Fix

#2166 Fixes the freakin' smoke runtimes for real
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
Labels: Fix

#2180 Removes var-edits from nanomeds
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/shuttles/alamo.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Map Edit, Removal, Requires Testing

#2172 Slight access code cleanup, a few admin equip panel tweaks
  code/__DEFINES/access.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/job.dm
  code/game/data_huds.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/circuitboards/circuitboard.dm
  code/game/objects/items/storage/wallets.dm
  code/game/objects/machinery/computer/card.dm
  code/game/objects/machinery/computer/marines_consoles.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/crates_lockers/secure_crates.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/topic.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  nano/templates/identification_computer.tmpl
Labels: Administration, Code Improvement

#2177 Yet another do_after runtime
  code/game/objects/structures/watercloset.dm
Labels: Fix

#2178 Hopefully fixes the reboot issues
  code/controllers/subsystem/ticker.dm
  code/game/world.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v4/api.dm
Labels: Fix

#2182 Fixes a scout cloak issue
  code/game/objects/items/storage/backpack.dm
Labels: Fix

#2179 Fixes a floor runtime
  code/game/turfs/floor.dm
Labels: Fix

#1685 Xeno armor refactor
  code/__DEFINES/conflict.dm
  code/modules/codex/entries/_codex_entry.dm
  code/modules/codex/entries/clothing_codex.dm
  code/modules/codex/entries/mobs_codex.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravenger/ravenger.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Balance/Rebalance, Requires Testing

#2185 No more tankers
  code/datums/jobs/job/shipside.dm
Labels: Balance/Rebalance

#2173 move macros
  code/__DEFINES/conflict.dm
  code/__DEFINES/objects.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/weapons/weapon.dm
  code/game/objects/structures/supplypod.dm
  code/game/objects/structures/xeno.dm
  code/modules/admin/verbs/podlauncher.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Code Improvement

#2192 Fixes a duplicate log
  code/game/world.dm
Labels: Fix

#1931 Replaces eye blur effect with real one
  code/_onclick/hud/fullscreen.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/status_procs.dm
Labels: Feature, Requires Testing

#2176 Adds argument definitions to contribution guidelines
  .github/CONTRIBUTING.md
Labels: GitHub

#2199 Fixes sprites for various hud glasses
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/glasses/meson.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Fix, Sprites

#2198 Fixes debugdalus traits
  _maps/debugdalus.json
Labels: Fix, Map Edit

#2125 Signals Episode 7 The Signals Awaken
  code/__DEFINES/components.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Requires Testing

#2204 linter
  code/controllers/subsystem/mapping.dm
  tools/travis/before_build_byond.sh
Labels: Tools

#2200 Fixes explosions not working
  code/game/objects/explosion.dm
Labels: Fix

#2202 IC information on enemy presence in Distress Signal game mode.
  code/datums/emergency_calls/emergency_call.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
Labels: Balance/Rebalance

#2207 Service pistol balance patch
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/magazines/pistols.dm
  icons/mob/belt.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/gun.dmi
Labels: Balance/Rebalance, Sprites, Test Merge Candidate, Tweak

#2174 Hopefully fixes the pref saving bad output runtime
  code/modules/client/preferences.dm
Labels: Fix, Requires Testing

#2225 Corrects some M41A1 and stock names
  code/datums/supplypacks.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Grammar and Formatting, Trivial

#2201 Fixes being unable to click on darkness
  code/__DEFINES/equipment.dm
  code/_onclick/click.dm
Labels: Fix

#2212 Adds sounds to pill bottle
  code/game/objects/items/storage/firstaid.dm
  sound/items/pillbottle.ogg
  sound/items/pills.ogg
Labels: Sound, Test Merge Candidate

#2203 Increases lasgun slowdown while wielded
  code/__DEFINES/conflict.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
Labels: Balance/Rebalance, Requires Testing

#2205 Adds sounds for pod doors
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/machinery/doors/shutters.dm
  sound/machines/blastdoor.ogg
  sound/machines/shutter.ogg
Labels: Requires Testing, Sound

#2230 Sechud jobs begone
  code/__DEFINES/atom_hud.dm
  code/datums/atom_hud.dm
  code/datums/jobs/job/job.dm
  code/game/data_huds.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/living.dm
Labels: Removal

#2211 Storage rebalance
  code/datums/gamemodes/distress.dm
  code/datums/jobs/job/shipside.dm
  code/datums/supplypacks.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/magazines/shotguns.dm
  icons/Marine/marine-pouches.dmi
Labels: Balance/Rebalance, Grammar and Formatting, Requires Testing, Sprites

#2227 Fixes teleporter attack_hand runtime
  code/game/objects/machinery/teleporter.dm
Labels: Fix

#2226 Improves admin input sanitization
  code/__HELPERS/text.dm
Labels: Administration

#2217 Fixes duplicate pipe causing warnings on ice
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Fix, Map Edit

#2216 Fixes EORD ghost runtimes
  code/datums/gamemodes/game_mode.dm
Labels: Fix

#2215 Fixes ASL radio for real
  code/datums/jobs/squads.dm
  code/game/objects/machinery/overwatch.dm
Labels: Fix

#2220 Removes unused implant code, fixes CL implanter
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/data_huds.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/implants/implantchair.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/implants/implantneurostim.dm
  code/game/objects/items/implants/implantpad.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/scanners.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/computer/prisoner.dm
  code/game/objects/machinery/teleporter.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/surgery/implant.dm
  tgmc.dme
Labels: Code Improvement, Fix, Map Edit, Removal

#2210 Converts all attack animations to the new proper type
  code/_onclick/item_attack.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/machinery/bots/bots.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/machinery/groundmap_geothermal.dm
  code/game/objects/machinery/sentries.dm
  code/game/objects/machinery/smartgun_mount.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/animations/animation_library.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_attackpaw.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/vehicles/powerloader.dm
  code/modules/vehicles/vehicle.dm
Labels: Code Improvement

#2233 .45 Ammo box
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/datums/jobs/job/shipside.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  icons/obj/items/ammo.dmi
Labels: Feature, Map Edit, Sprites

#2195 Changes Shuttle launch time lock from a define to a variable
  code/__DEFINES/mode.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/shuttle/computer.dm
Labels: Balance/Rebalance

#2228 Feedback for joining as larva.
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Test Merge Candidate

#2232 [s] Href exploit checks
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Administration

#2223 A different medkit size fix
  code/game/objects/items/storage/storage.dm
Labels: Fix

#2229 Disarming C4 with a multitool
  code/game/objects/items/explosives/plastique.dm
Labels: Feature, Fix

#2234 Adds action buttons for voting
  code/controllers/subsystem/vote.dm
  icons/mob/actions.dmi
Labels: QoL, Sprites

#2245 Removes unused rank from the repo
  config/admin_ranks.txt
Labels: Config Update, Removal

#2249 Revert "Fixes AI eye layer to be above all the things (#2110)"
  code/__DEFINES/layers.dm
  code/game/objects/machinery/computer/camera_advanced.dm
Labels: Revert

#2161 Makes the AI playable.
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/generic/Admin_Level.dmm
  code/__DEFINES/jobs.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/mapping.dm
  code/_onclick/ai.dm
  code/controllers/subsystem/job.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/computer/communications.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/admin/fun_verbs.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/ai/multicam.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/power/apc.dm
  config/config.txt
  icons/turf/areas.dmi
  nano/templates/apc.tmpl
Labels: Config Update, Feature, Map Edit, Requires Testing, Sprites

#2257 revert this change pushed to wrong branch before merge
  code/modules/admin/fun_verbs.dm
Labels: Revert

#2254 Force dropship usability changes
  code/modules/admin/fun_verbs.dm
Labels: Administration

#2197 Fire() refactor part I: Non-projectile gun attachables handled by CTRL+Click
  code/__DEFINES/components.dm
  code/_onclick/click.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  tgmc.dme
Labels: Balance/Rebalance, Refactor, Requires Testing

#2241 Limb armor datum
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/organs/limbs.dm
Labels: Performance, Requires Testing

#2261 Makes fire work properly
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Fix

#2251 Slight debug verb improvement
  code/modules/admin/debug_verbs.dm
Labels: Administration

#2247 Removes more unused configs
  code/__DEFINES/admin.dm
  code/_globalvars/admin.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration/entries/general.dm
  code/datums/world_topic.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/client/client_procs.dm
  code/modules/vehicles/multitile/hardpoints.dm
  code/modules/vehicles/multitile/tank.dm
  sound/weapons/gun_m92_attachable_joke.ogg
  sound/weapons/gun_smartgun1_joke.ogg
  sound/weapons/gun_smartgun2_joke.ogg
  sound/weapons/gun_smartgun3_joke.ogg
  sound/weapons/tank_cannon_distant1_joke.ogg
  sound/weapons/tank_cannon_distant2_joke.ogg
  sound/weapons/tank_cannon_fire1_joke.ogg
  sound/weapons/tank_cannon_fire2_joke.ogg
  sound/weapons/tank_flamethrower_joke.ogg
  sound/weapons/tank_minigun_loop_joke.ogg
  sound/weapons/tank_minigun_select_joke.ogg
  sound/weapons/tank_minigun_start_joke.ogg
  sound/weapons/tank_minigun_stop_joke.ogg
  sound/weapons/tank_smokelauncher_fire_joke.ogg
  tgmc.dme
Labels: Config Update, Removal, Sound

#2214 Life() cleanup and microoptimizations
  code/__DEFINES/mobs.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/game/objects/items/flashlight.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/autodoc.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/human/life/handle_disabilities.dm
  code/modules/mob/living/carbon/human/life/handle_fire.dm
  code/modules/mob/living/carbon/human/life/handle_grabbed.dm
  code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
  code/modules/mob/living/carbon/human/life/handle_organs.dm
  code/modules/mob/living/carbon/human/life/handle_pulse.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/human/life/handle_status_effects.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/living/status_procs.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  code/modules/surgery/eye.dm
Labels: Code Improvement

#2242 Buffs Selling Xenomorph corpses
  code/datums/supplyexports.dm
Labels: Balance/Rebalance, Fix, Requires Testing, Tweak

#2252 Fixes the release object verb
  code/modules/admin/fun_verbs.dm
Labels: Administration

#2250 Admin round-start tweaks
  code/controllers/subsystem/ticker.dm
  code/game/objects/explosion.dm
  code/modules/admin/server_verbs.dm
Labels: Administration

#2260 Fixes blood overlay issues
  code/game/blood.dm
Labels: Fix

#2266 Fixes some keybinding issues
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix

#2267 Another do_after runtimes
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/watercloset.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/turfs/walls/walls.dm
Labels: Fix

#2262 Typing indicator fixes
  code/modules/client/preferences_toggles.dm
  code/modules/mob/camera/imaginary_friend.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/typing_indicator.dm
Labels: Fix

#2282 Fixes roundstart bioscans showing location
  code/datums/gamemodes/distress.dm
Labels: Fix

#2277 Fixes a camera runtime
  code/modules/mob/living/silicon/ai/multicam.dm
Labels: Fix

#2276 Fixes the Ice Colony landing zones
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Fix, Map Edit

#2275 Fixes a world status runtime
  code/game/world.dm
Labels: Fix

#2274 Fixes a HUD runtime
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
Labels: Fix

#2273 Fixes a vote runtime
  code/controllers/subsystem/vote.dm
Labels: Fix

#2271 Fixes pocket equip issues
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#2268 Fixes mulebot wire runtime
  code/game/objects/machinery/bots/mulebot.dm
Labels: Fix

#2283 Fixes runner walking icon
  icons/Xeno/2x2_Xenos.dmi
Labels: Fix, Sprites

#2285 Fixes queen shuttle calldown quirkiness
  code/modules/shuttle/marine_dropship.dm
Labels: Fix

#2290 Fixes a space in chem dispenser
  nano/templates/chem_dispenser.tmpl
Labels: Fix

#2291 Fixes an access runtime
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Fix

#2292 Fixes AI cryo runtime
  code/game/objects/machinery/cryopod.dm
Labels: Fix

#2286 Adds aviator sunglasses for PO
  code/datums/jobs/job/shipside.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/clothing/glasses/glasses.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, Sprites

#2295 Timers out of bounds.
  code/controllers/master.dm
  code/controllers/subsystem/timer.dm
  code/game/world.dm
  code/world.dm
Labels: Fix

#2208 First part of the mob code cleanup - cooldowns
  code/__DEFINES/mobs.dm
  code/_onclick/human.dm
  code/_onclick/telekinesis.dm
  code/datums/emotes.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items.dm
  code/game/objects/items/restraints.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/recycling/disposal.dm
  tgmc.dme
Labels: Code Improvement, Requires Testing

#2296 Reboot runtime
  code/game/world.dm
Labels: Fix, Test Merge Candidate

#2248 Allows admins to set a custom tip of the round
  code/controllers/subsystem/ticker.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
Labels: Administration, Fix

#2078 Increase weeds size
  code/controllers/subsystem/weeds.dm
  code/game/objects/effects/weeds.dm
Labels: Balance/Rebalance, Fix

#1829 Flares burn weeds
  code/game/objects/effects/weeds.dm
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Balance/Rebalance

#2299 Removes removed config.txt entry
  config/config.txt
Labels: Config Update, Removal

#2302 Fixes keybinding prefs for players who played here previously
  code/modules/client/preferences_savefile.dm
Labels: Fix

#2317 Clarify xeno ruler when launching the shuttle
  code/modules/shuttle/marine_dropship.dm
Labels: Grammar and Formatting

#2315 Purge bad spacecash
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  code/game/objects/items/portable_vendor.dm
  code/game/objects/items/storage/wallets.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/modules/economy/cash.dm
Labels: Map Edit

#2303 Adds faction based roundend sounds
  code/datums/gamemodes/distress.dm
Labels: Tweak

#2309 Small hud sprite tweaks
  icons/mob/hud.dmi
Labels: Sprites

#2304 Firemode refactor
  code/__DEFINES/conflict.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/actions/item_action.dm
  code/game/objects/items.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Feature, Refactor

#2316 Fixes AI being unable to interact with dropship lockdown
  code/modules/shuttle/marine_dropship.dm
Labels: Fix

#2322 Fixes pizza
  code/game/objects/items/reagent_containers/food/snacks.dm
Labels: Fix, Priority: High

#2324 Fixes detpack timer issue
  code/game/objects/items/radio/detpack.dm
Labels: Fix

#2321 Fixes xeno basketball being enabled by default
  code/game/objects/items/toys/toys.dm
Labels: Fix

#2319 Removes the "Analyze Air" observer button
  code/modules/mob/dead/observer/observer.dm
Labels: Removal, Tweak

#2318 Fixes being unable to remove broken plating
  code/game/turfs/floor.dm
Labels: Fix

#2312 Add human / xeno count to distress beacons for admins
  code/game/objects/machinery/computer/communications.dm
Labels: Administration

#2320 Ammo datum cleanup and runtime fix
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Fix

#2307 Adds ammo counters to most spec weapons and launchers
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Tweak

#2300 Fixes HUD updating runtimes
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
Labels: Fix

#2329 Fixes plasmacutter battery removal
  code/game/objects/items/tools/mining_tools.dm
Labels: Fix

#2330 Fixes BSQL on linux
  code/modules/bsql/core/library.dm
Labels: Fix

#2326 Cleans up rav rage decay
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
Labels: Balance/Rebalance, Requires Testing

#2314 Removes Big Red cameras
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Fix, Map Edit, Removal

#2335 Allow admins to set a distress beacon when sending
  code/datums/emergency_calls/emergency_call.dm
  code/modules/admin/topic.dm
Labels: Administration, Feature

#2356 Fix counts for distress to show total number instead of shipside
  code/game/objects/machinery/computer/communications.dm
Labels: Administration

#2336 Makes some fax fields optional
  code/modules/admin/topic.dm
Labels: Administration

#2337 Fixes lobby countdown when admin sets it before startup
  code/controllers/subsystem/ticker.dm
Labels: Fix

#2338 Fixes a zone select runtime
  code/modules/mob/mob_movement.dm
Labels: Fix

#2347 Fixes ghost pulling
  code/game/objects/machinery/bots/mulebot.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/verbs/atom_verbs.dm
  code/modules/mob/living/living.dm
  code/modules/vehicles/cargo_train.dm
  tgmc.dme
Labels: Fix

#2349 Fixes elite drones and carriers
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
Labels: Fix

#2350 Fixes observer crossed mouse squeaking
  code/datums/components/squeak.dm
Labels: Fix

#2352 Fixes simple window deconstruction
  code/game/objects/structures/window.dm
Labels: Fix

#2353 Fixes some topic interaction issues
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
Labels: Fix

#2357 Fixes a gun action runtime
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
Labels: Fix

#2360 Fixes a null in player list if the player disconnects at a bad time
  code/modules/mob/login.dm
Labels: Fix

#2358 Removes emergency shutter admin message
  code/game/objects/machinery/doors/firedoor.dm
Labels: Administration, Removal

#2363 Fixes graceful shutdown pinging for real
  code/controllers/subsystem/ticker.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v4/api.dm
Labels: Fix

#2377 Fixes ahelp spelling error
  code/modules/admin/verbs/adminhelp.dm
Labels: Fix

#2366 Fixes a slight access issue
  code/datums/jobs/access.dm
Labels: Fix

#2305 death to spawn()
  code/__DEFINES/callbacks.dm
  code/__HELPERS/qdel.dm
  code/datums/marine_main_ship.dm
  code/game/area/area.dm
  code/game/area/general.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/effects/effect_system/effect_system.dm
  code/game/objects/effects/effect_system/explosions.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/effects/effect_system/particle_effects.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/effects/portals.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/megaphone.dm
  code/game/objects/items/radio/beacon.dm
  code/game/objects/items/reagent_containers/dropper.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/reagent_containers/robodropper.dm
  code/game/objects/items/reagent_containers/spray.dm
  code/game/objects/items/tools/policetape.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/transfer_valve.dm
  code/game/objects/machinery/bots/medbot.dm
  code/game/objects/machinery/bots/mulebot.dm
  code/game/objects/machinery/computer/general_air_control.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/airlock_control.dm
  code/game/objects/machinery/doors/brigdoors.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/game/objects/machinery/flasher.dm
  code/game/objects/machinery/holosign.dm
  code/game/objects/machinery/igniter.dm
  code/game/objects/machinery/smartgun_mount.dm
  code/game/objects/machinery/teleporter.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/musician.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/xeno.dm
  code/modules/assembly/signaler.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/hydroponics/vines.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/living.dm
  code/modules/organs/limbs.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/power/smes_construction.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
  code/modules/recycling/conveyor2.dm
  code/modules/recycling/disposal.dm
  code/modules/security_levels/keycard_authentication.dm
  code/modules/surgery/implant.dm
  goon/code/obj/machinery/bot/chefbot.dm
Labels: Code Improvement, Refactor

#2389 Fixes xeno spit cost
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#2196 Adds weed decay
  code/controllers/subsystem/weeds.dm
  code/controllers/subsystem/weeds_decay.dm
  code/game/objects/effects/weeds.dm
  tgmc.dme
Labels: Balance/Rebalance

#2301 Fixes vote action runtime
  code/controllers/subsystem/vote.dm
Labels: Fix

#2306 Battle rifle balance tweaks
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Balance/Rebalance, Requires Testing

#2355 Fixes cells icon updating
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/machinery/bots/mulebot.dm
  code/game/objects/machinery/cell_charger.dm
  code/game/objects/machinery/floodlight.dm
  code/game/objects/machinery/spaceheater.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/projectiles/updated_projectiles/magazines/energy.dm
Labels: Fix

#2354 Fixes overwatch eye layer issues
  code/_globalvars/misc.dm
  code/game/objects/machinery/computer/camera_advanced.dm
Labels: Fix

#2385 Converts show_messages into visible/audible_message
  code/_onclick/other_mobs.dm
  code/game/objects/items/megaphone.dm
  code/game/objects/items/reagent_containers/dropper.dm
  code/game/objects/items/reagent_containers/food/condiment.dm
  code/game/objects/items/reagent_containers/food/drinks.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/reagent_containers/robodropper.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/scanners.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/taperecorder.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/toys/toy_weapons.dm
  code/game/objects/machinery/OpTable.dm
  code/game/objects/machinery/bots/medbot.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/newscaster.dm
  code/game/objects/machinery/teleporter.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/watercloset.dm
  code/modules/admin/fun_verbs.dm
  code/modules/clothing/under/under.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/power/lighting.dm
  code/modules/power/smes.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/shuttle/supply.dm
Labels: Code Improvement, Fix

#2368 Alt+click containers
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/storage.dm
Labels: Feature

#2391 Fixes powerloader clamp issues
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/vehicles/powerloader.dm
Labels: Fix

#2378 No shrike ventcrawl
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
Labels: Balance/Rebalance

#2388 Singular to xeno plural
  code/game/mecha/mecha_wreckage.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/shards.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/bots/bots.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/machinery/groundmap_geothermal.dm
  code/game/objects/machinery/sentries.dm
  code/game/objects/machinery/smartgun_mount.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/ovipositor.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/snow.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/vehicles/powerloader.dm
  code/modules/vehicles/vehicle.dm
Labels: Fix

#2387 Fixes synthetic blind and deafness issues
  code/__DEFINES/is_helpers.dm
  code/modules/mob/living/carbon/human/human_status_procs.dm
Labels: Fix

#2390 Fixes largecrate issues
  code/game/objects/structures/crates_lockers/largecrate.dm
Labels: Fix

#2394 Bipod, and scatter rework, attachment refactor
  code/_onclick/hud/screen_objects.dm
  code/controllers/configuration/entries/combat_defines.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
Labels: Balance/Rebalance, Config Update, Refactor

#2310 Clarifies the hotkey preference name, removes obsolete SSinput things
  code/controllers/subsystem/input.dm
  code/datums/keybinding/client.dm
  code/datums/keybinding/mob.dm
  code/game/verbs/ooc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/setup.dm
Labels: Code Improvement, Removal, Requires Testing

#2415 Removes more W-Y refferences
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/shuttles/big_ert.dmm
  _maps/shuttles/distress_pmc.dmm
  code/game/objects/effects/landmarks/random_item.dm
  code/game/objects/items/marine_gear.dm
  code/modules/reagents/chemistry_reagents/alcohol.dm
  icons/mob/uniform_0.dmi
  icons/turf/ert_shuttle.dmi
Labels: Map Edit, Removal, Sprites

#2396 Fixes a queen calldown issue
  code/modules/shuttle/marine_dropship.dm
Labels: Fix

#2397 Fixes facehugger description
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#2398 Fixes some light slashing issues
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#2400 Removes hunter games
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/__DEFINES/objects.dm
  code/datums/gamemodes/huntergames.dm
  code/game/objects/effects/landmarks/random_item.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  tgmc.dme
Labels: Map Edit, Removal

#2402 Fixes AI zlevel interactions
  code/_onclick/ai.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#2403 Fixes dirty ear deafness modifications
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_status_procs.dm
  code/modules/mob/living/carbon/human/life/handle_disabilities.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/living/status_procs.dm
Labels: Fix

#2405 Another admin delay fix
  code/modules/admin/server_verbs.dm
Labels: Administration

#2406 Fixes tinglingblistered
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Fix

#2408 Fixes fuel engine interaction
  code/game/objects/machinery/fusion_engine.dm
Labels: Fix

#2411 Fixes monkey hud runtime
  code/modules/mob/living/carbon/monkey/life.dm
Labels: Fix

#2416 Adds light to the AI chamber
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit

#2419 Fixes a ton of squad issues
  code/controllers/subsystem/direction.dm
  code/controllers/subsystem/job.dm
  code/datums/jobs/squads.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Code Improvement, Fix
