Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2019-01, with the labels that each got.

#213 Fix for M56D bug
  code/modules/cm_marines/smartgun_mount.dm
Labels: Fix

#197 Boonie Hat Sprite Change
  icons/mob/head_0.dmi
Labels: Sprites

#261 Hopefully fixes issues with figuring out if the sentry turret is pointing north or south
  icons/Marine/new_sentry_alt.dmi
Labels: Sprites

#220 Un-dumbs synthetic grenade restrictions
  code/game/gamemodes/gameticker.dm
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/explosives/grenades/emgrenade.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/explosives/grenades/spawnergrenade.dm
Labels: Administration, Fix, Tweak

#279 Adds a a new scream sound for male humans
  code/game/sound.dm
  sound/voice/human_male_scream_6.ogg
Labels: Sound

#273 Less pendant and verbose descriptions for marine uniforms.
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/under.dm
Labels: Grammar and Formatting

#251 500$ sunglasses.
  code/modules/client/preferences_gear.dm
  code/modules/clothing/glasses/glasses.dm
Labels: Feature, Fix, Tweak

#248 Removes unneeded process() use from tank fab
  code/modules/vehicles/tankvendor.dm
Labels: Removal

#281 Moved north-facing wooden barricade up
  icons/Marine/barricades.dmi
Labels: Sprites

#280 New Xeno UI icons for redone resin structures
  icons/mob/actions.dmi
Labels: Sprites

#245 Replacing shotgun ammo and box sprites
  icons/obj/items/ammo.dmi
Labels: Needs Review, Sprites

#284 Minor Evolution Fixes
  code/modules/mob/living/carbon/xenomorph/Castes/Praetorian.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Spitter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
Labels: Fix

#278 Nukes the hundred charges ultime hugbox crime-stopper galore.
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
Labels: Balance/Rebalance

#287 Nanopaste stack fix
  code/game/objects/items/stacks/nanopaste.dm
Labels: Fix

#152 Some xenomorph ability PR.
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Drone.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hivelord.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Larva.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Predalien.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Xenoborg.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/mob_helpers.dm
  icons/mob/actions.dmi
Labels: Feature, Sprites, Tweak

#249 Refactors tank spawner code
  code/modules/vehicles/cm_armored.dm
  code/modules/vehicles/hardpoints.dm
  code/modules/vehicles/tank.dm
Labels: Refactor

#72 M43 Sunfury Lasgun MK1 For The Third Fucking Time
  code/__DEFINES/conflict.dm
  code/controllers/settings/combat_defines.dm
  code/datums/supplypacks.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/machinery/machinery.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/vending.dm
  code/game/objects/effects/effect_system/explosions.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/power/cell.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/magazines/energy.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  config/combat_defines.txt
  config/example/combat_defines.txt
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  icons/obj/items/projectiles.dmi
  icons/obj/machines/vending.dmi
  icons/obj/old_guns/old_guns.dmi
  tgmc.dme
Labels: Config Update, Feature, Sprites

#244 Headset Cameras Added
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/head/helmet.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/mob_grab.dm
Labels: Tweak

#275 minor refactoring/clean-up/bugfix on reagent dispensers/containers/blowtorchs
  code/game/objects/items/reagent_containers/reagent_container.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/objs.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Fix, Refactor

#234 Hotfixes Distress
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/xeno.dm
  code/game/machinery/computer/communications.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
Labels: Fix

#76 New Sniper Ability: Targeting Laser For The Third Fucking Time
  code/__DEFINES/conflict.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/objects.dm
  code/game/objects/effects/overlays.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  icons/obj/items/projectiles.dmi
Labels: Feature, Sprites, Tweak

#238 Balance Tweaks Per Recent Test Results
  code/__DEFINES/mobs.dm
  code/controllers/settings/combat_defines.dm
  code/datums/supplypacks.dm
  code/game/machinery/air_alarm.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/fire_alarm.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/machinery/vending/vending_types.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items.dm
  code/game/objects/items/circuitboards/airlock.dm
  code/game/objects/items/circuitboards/circuitboard.dm
  code/game/objects/structures/windoor_assembly.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/life/handle_stasis_bag.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/power/apc.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  config/combat_defines.txt
  tgmc.dme
Labels: Config Update, Tweak

#254 Fixes roleauthority landmark iteration
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/game/jobs/role_authority.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/modules/admin/verbs/striketeam.dm
  code/modules/admin/verbs/striketeam_syndicate.dm
Labels: Fix

#232 Adds a way to get multiple log files at once
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/getlogs.dm
Labels: Administration

#217 Fixes dropship equipment pickup.
  code/_onclick/adjacent.dm
Labels: Fix

#268 Fixes fallen sentry icon state.
  code/modules/cm_marines/equipment/sentries.dm
Labels: Fix

#192 Implements *medic *pain *scream + order icon indicators. Emote code cleanup.
  code/__DEFINES/mobs.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/say.dm
  code/modules/mob/typing_indicator.dm
  icons/mob/talk.dmi
  interface/skin.dmf
Labels: Feature, Sprites

#231 New Queen Ability: Advance Larval Growth
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  icons/mob/actions.dmi
Labels: Feature, Sprites

#209 Zombie language and christmas guns code cleanup.
  code/datums/diseases/black_goo.dm
  code/game/objects/items/XMAS.dm
  code/modules/mob/language.dm
Labels: Code Improvement

#297 LV map cleanup
  maps/Z.01.LV624.dmm
Labels: Map Edit

#255 Fixes the "Change Hivenumber" verb.
  code/datums/datumvars.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Fix

#216 Armors and suits with storage slots now properly unequip.
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix

#302 Adds the Spatial Agent debug verb.
  code/datums/skills.dm
  code/game/jobs/job/other.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/spatialagent.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/under/miscellaneous.dm
  tgmc.dme
Labels: Administration

#299 Restricts the MC panel to relevant people.
  code/modules/mob/mob.dm
Labels: Administration

#267 Adds dress whites for the marines.
  code/game/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/head_0.dmi
  icons/mob/suit_0.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#298 minor refactor of energygun new()
  code/modules/projectiles/updated_projectiles/guns/energy.dm
Labels: Refactor

#225 Expanded Hypospray Functionality
  code/__DEFINES/objects.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/reagent_containers/reagent_container.dm
  icons/obj/items/syringe.dmi
  icons/obj/reagentfillings.dmi
Labels: Sprites

#306 Fixes runtime with air alarms
  code/game/machinery/air_alarm.dm
Labels: Fix

#304 Deletes super_secret
  code/modules/cm_marines/super_secret.dm
  tgmc.dme
Labels: Removal

#307 Replaces mob/.+/New() with Initialize
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/living/carbon/hellhound/hellhound.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/bees.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/drone.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/mob.dm
Labels: Refactor

#310 Moves the MC tab to the right, fixes permission spam for mentors.
  code/modules/mob/mob.dm
Labels: Fix

#322 Lessen adjustBrainLoss() spam, applies better usage of organ damage procs on code.
  code/datums/diseases/brainrot.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/defibrillator.dm
  code/game/objects/items/storage/bible.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/chemistry_reagents/alcohol.dm
  code/modules/reagents/chemistry_reagents/drink.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  code/modules/reagents/chemistry_reagents/other.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
Labels: Code Improvement, Tweak

#311 Hotfixes Spatial Agent
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/spatialagent.dm
Labels: Fix

#312 Self Examination now reveals treatement
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/organs/limbs.dm
Labels: QoL

#314 Buffs the CHUNK box
  code/game/objects/items/reagent_containers/food/snacks.dm
Labels: Tweak

#326 [HIGH PRIORITY]Inventories: Mends what was broken.
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
Labels: Fix

#319 Fixes #316 Tank fabricator lists both fixed and broken parts to be pr…
  code/modules/vehicles/hardpoints.dm
  code/modules/vehicles/tankvendor.dm
Labels: Fix

#323 Fixes the duplicate explosive pouch on specialists' vendor.
  code/game/machinery/vending/new_marine_vendors.dm
Labels: Fix

#325 Guests can no longer join by default.
  code/global.dm
Labels: Fix

#288 Today weather's forecast: guidelines and changelogs, with a chance of mistakes.
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  code/modules/mob/mob.dm
  html/AddToChangelog.exe
  html/ban.png
  html/changelog.css
  html/changelog.html
  html/changelogs/__CHANGELOG_README.txt
  html/changelogs/example.yml
  html/chrome-wrench.png
  html/coding.png
  html/scales.png
  html/templates/footer.html
  html/templates/header.html
  tools/AddToChangelog/AddToChangelog.sln
  tools/AddToChangelog/AddToChangelog/AddToChangelog.csproj
  tools/AddToChangelog/AddToChangelog/Form1.Designer.cs
  tools/AddToChangelog/AddToChangelog/Form1.cs
  tools/AddToChangelog/AddToChangelog/Form1.resx
  tools/AddToChangelog/AddToChangelog/Program.cs
  tools/AddToChangelog/AddToChangelog/Properties/AssemblyInfo.cs
  tools/AddToChangelog/AddToChangelog/Properties/Resources.Designer.cs
  tools/AddToChangelog/AddToChangelog/Properties/Resources.resx
  tools/AddToChangelog/AddToChangelog/Properties/Settings.Designer.cs
  tools/AddToChangelog/AddToChangelog/Properties/Settings.settings
  tools/AddToChangelog/AddToChangelog/bin/Debug/AddToChangelog.vshost.exe.manifest
  tools/AddToChangelog/AddToChangelog/bugfix.png
  tools/AddToChangelog/AddToChangelog/changelog.ico
  tools/AddToChangelog/AddToChangelog/experiment.png
  tools/AddToChangelog/AddToChangelog/imageadd.png
  tools/AddToChangelog/AddToChangelog/imagedel.png
  tools/AddToChangelog/AddToChangelog/obj/x86/Debug/AddToChangelog.MainForm.resources
  tools/AddToChangelog/AddToChangelog/obj/x86/Debug/AddToChangelog.Properties.Resources.resources
  tools/AddToChangelog/AddToChangelog/obj/x86/Debug/AddToChangelog.csproj.FileListAbsolute.txt
  tools/AddToChangelog/AddToChangelog/rscadd.png
  tools/AddToChangelog/AddToChangelog/rscdel.png
  tools/AddToChangelog/AddToChangelog/soundadd.png
  tools/AddToChangelog/AddToChangelog/sounddel.png
  tools/AddToChangelog/AddToChangelog/tweak.png
  tools/AddToChangelog/AddToChangelog/wip.png
  tools/AddToChangelog/icon.png
  tools/WebhookProcessor/github_webhook_processor.php
  tools/WebhookProcessor/secret.php
  tools/makeChangelog.bat
  tools/ss13_genchangelog.py
Labels: GitHub, Tools

#329 Removes uses of processing_second
  code/__HELPERS/global_lists.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/cm_marines/equipment/gear.dm
Labels: Fix, Removal

#224 Specialist Bug Fixes + Rocket Launcher Reloads
  code/game/objects/items/storage/belt.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/magazines/specialist.dm
Labels: Fix, Tweak

#346 fixes LZ1 geothermal power
  maps/Z.01.Ice_Colony_v2.dmm
Labels: Fix

#237 Mega Minor Bug Fix Pack
  code/__DEFINES/mobs.dm
  code/datums/emergency_calls/emergency_call.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/autodoc.dm
  code/game/objects/items/devices/radio/detpack.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/window.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Fix

#277 ZX-76 Shotgun Scout Subkit Added
  code/controllers/configuration/entries/combat_defines.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/magazines/shotguns.dm
  config/config.txt
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/gun.dmi
Labels: Balance/Rebalance, Config Update, Feature, Sprites

#214 Xeno starting number and latejoin rebalance, monkey removal, survivor rework, admin xeno rolling fix.
  code/__DEFINES/mode.dm
  code/__HELPERS/game.dm
  code/controllers/configuration/entries/game_options.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/game/gamemodes/colonialmarines/huntergames.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/extended/infection.dm
  code/game/jobs/job/other.dm
  code/game/jobs/role_authority.dm
  code/game/objects/items/storage/pouch.dm
  config/config.txt
  maps/Z.01.Prison_Station_FOP.dmm
Labels: Balance/Rebalance, Config Update, Fix

#250 code/__HELPERS/pronouns.dm.
  code/__HELPERS/pronouns.dm
  code/_onclick/human.dm
  code/datums/diseases/black_goo.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/defibrillator.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/legcuffs.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/items/reagent_containers/food/drinks/bottle.dm
  code/game/objects/items/shards.dm
  code/game/objects/items/stacks/cable_coil.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/tools/surgery_tools.dm
  code/game/objects/items/toys/cards.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/energy.dm
  code/game/objects/items/weapons/misc.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/objs.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/watercloset.dm
  code/game/verbs/suicide.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/NonLethalRestraints.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/mob_grab.dm
  code/modules/organs/limb_objects.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/supermatter/supermatter.dm
  code/modules/vehicles/cm_armored.dm
  tgmc.dme
Labels: Feature, Grammar and Formatting

#308 Removes spawn() from New()
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/bio-dome_floodlights.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/computer/area_air_control.dm
  code/game/machinery/computer/hologram.dm
  code/game/machinery/computer/message.dm
  code/game/machinery/computer/pod.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/shutters.dm
  code/game/machinery/floodlight.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/machinery/lightswitch.dm
  code/game/machinery/portable_turret.dm
  code/game/machinery/vending/vending.dm
  code/game/objects/items/frames/bot_assembly.dm
  code/game/objects/items/reagent_containers/food/snacks/grown.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/wallets.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/ladders.dm
  code/game/objects/structures/safe.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  code/modules/paperwork/paper.dm
  code/modules/power/antimatter/shielding.dm
  code/modules/power/apc.dm
  code/modules/power/cell.dm
  code/modules/power/generator.dm
  code/modules/power/generator_type2.dm
  code/modules/power/gravitygenerator.dm
  code/modules/power/singularity/singularity.dm
  code/modules/power/turbine.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/shieldgen/shield_capacitor.dm
  code/modules/shieldgen/shield_gen.dm
  code/modules/shuttles/escape_pods.dm
Labels: Refactor, Removal

#349 Brig/OB room Swap, CIC Update
  maps/Z.03.TGS_Theseus.dmm
Labels: Map Edit

#283 New Xeno Caste: Defiler
  code/__DEFINES/mobs.dm
  code/datums/round_statistics.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/admin/admin.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Defiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hivelord.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/reagents/chemistry_reagents/other.dm
  icons/Xeno/2x2_Xenos.dmi
  icons/Xeno/Defiler.dmi
  icons/Xeno/wound_overlays.dmi
  icons/mob/actions.dmi
  tgmc.dme
Labels: Balance/Rebalance, Feature, Sprites

#360 Revert "Brig/OB room Swap, CIC Update (#349)"
  maps/Z.03.TGS_Theseus.dmm
Labels: Revert

#350 Fixes Shotgun belt/pouches overloading
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
Labels: Fix

#357 Updated the sprites for the Kitchen tools.
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/kitchen_tools.dmi
Labels: Sprites

#147 Webbing Now Has Quickdraw
  code/modules/clothing/under/ties.dm
Labels: Feature, QoL

#354 Sentry ammo fix
  code/modules/cm_marines/equipment/sentries.dm
Labels: Fix

#351 Proof of concept for replacing use of spawn with callbacks
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Refactor

#359 BOX HIDP and M15
  code/datums/supplypacks.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/objects/items/storage/boxes.dm
  icons/obj/items/storage/storage.dmi
Labels: Feature, Sprites

#362 Removes all organ/limb name string compares and replaces the string s…
  code/__DEFINES/mobs.dm
  code/game/machinery/autodoc.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/organs/organ_internal.dm
  code/modules/organs/pain.dm
Labels: Removal

#365 replaces all applicable mob related spawns with callbacks
  code/_onclick/hud/fullscreen.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/whisper.dm
  code/modules/mob/living/carbon/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Xenoborg.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/emote.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
Labels: Code Improvement

#372 adds lootboxes
  code/game/objects/structures/crates_lockers/largecrate.dm
Labels: Tweak

#370 EORD arena tweaks
  maps/Z.02.Admin_Level.dmm
Labels: Tweak

#392 Port's MSO's crucial security exploit fix
  code/modules/admin/debug_verbs.dm
Labels: Administration, Fix, Priority: CRITICAL

#388 Lasguns can light cigarettes now
  code/game/objects/items/tools/flame_tools.dm
Labels: Feature

#394 Fixes larva being unable to go drone after queen's death.
  code/modules/mob/living/carbon/xenomorph/Evolution.dm
Labels: Fix

#395 Quickfixes a few tarps problems.
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/cm_marines/equipment/gear.dm
Labels: Fix

#397 Fixes simple mobs being catatonic and unkillable.
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#402 Fixes Irish Cream reaction.
  code/modules/reagents/chemistry_reactions/food_drink.dm
Labels: Fix

#380 Minor refactor on supply drops code.
  code/_globalvars/lists/objects.dm
  code/game/machinery/vending/vending.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/cm_marines/overwatch.dm
Labels: Balance/Rebalance, Refactor, Test Merge Candidate

#352 fun_allowed flag
  code/controllers/configuration/entries/game_options.dm
  code/modules/mob/living/carbon/human/emote.dm
  config/config.txt
Labels: Config Update, Sprites, Tweak

#382 Admin Tweaks
  code/__DEFINES/admin.dm
  code/__HELPERS/game.dm
  code/__HELPERS/global_lists.dm
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/stonedmc/admin.dm
  code/datums/datacore.dm
  code/game/atoms.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/fax.dm
  code/game/verbs/ooc.dm
  code/game/verbs/who.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/ban_panel.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/panels/traitor_panel.dm
  code/modules/admin/server_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/admin/verbs/faxes.dm
  code/modules/admin/verbs/pray.dm
  code/modules/client/client defines.dm
  code/modules/client/client procs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Larva.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_verbs.dm
  code/modules/mob/new_player/login.dm
  code/modules/mob/new_player/new_player.dm
  code/stylesheet.dm
  interface/interface.dm
Labels: Administration, Config Update

#385 Temporary Music PR (don't close me Qustinnus)
  code/game/gamemodes/gameticker.dm
  sound/music/BloodUponTheRisers.ogg
  sound/music/DawsonChristian.ogg
  sound/music/ManOfWar.ogg
  sound/music/PraiseTheLord.ogg
  sound/music/clown.ogg
  sound/music/title1.ogg
  sound/music/title2.ogg
  sound/music/title3.ogg
Labels: Sound

#361 adds tips to the MOTD
  code/__DEFINES/admin.dm
  code/__HELPERS/global_lists.dm
  code/controllers/configuration/configuration.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/trash.dm
  code/game/world.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/pray.dm
  code/stylesheet.dm
  config/tips/joketips.txt
  config/tips/marinetips.txt
  config/tips/metatips.txt
  config/tips/xenotips.txt
  icons/obj/items/trash.dmi
Labels: Config Update, Feature, Sprites

#412 Fixes medevac stretcher "accidental" deconstructions.
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix

#420 Surgical Painkiller Bugfix.
  code/modules/surgery/surgery.dm
Labels: Fix

#421 CO Fix
  code/game/jobs/access.dm
Labels: Fix

#444 Hotfixes the ban system.
  code/modules/admin/panels/ban_panel.dm
Labels: Priority: CRITICAL

#410 APC code cleanup
  code/game/machinery/camera/camera.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/machinery.dm
  code/game/machinery/vending/vending.dm
  code/modules/power/apc.dm
Labels: Code Improvement, Fix

#369 Refactors hugger code.
  code/__DEFINES/equipment.dm
  code/game/machinery/cryopod.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/surgery/eye.dm
Labels: Balance/Rebalance, Code Improvement, Fix, Refactor, Tweak

#384 Adds a new anti-Brute medication called "Meralyne."
  code/modules/reagents/chemistry_reactions/medical.dm
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: Balance/Rebalance, Config Update

#366 Bug Fix Pack - 1-25-2019
  code/game/machinery/vending/marine_vending.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/structures/razorwire.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/living.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Fix, Tweak

#436 Fixes preferences being unchangeable
  code/modules/client/preferences.dm
Labels: Fix

#441 Fixes surgery infection chances
  code/modules/surgery/surgery.dm
Labels: Fix

#449 Fixes immortal xenos
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Fix, Priority: CRITICAL, Tweak

#219 Flare and Impact DP Grenade Types Added
  code/__DEFINES/objects.dm
  code/datums/supplypacks.dm
  code/game/gamemodes/colonialmarines/huntergames.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  icons/obj/items/grenade.dmi
  icons/obj/lighting.dmi
Labels: Balance/Rebalance, Feature, Sprites

#438 Changes the warning cone sprite
  icons/obj/janitor.dmi
Labels: Sprites

#437 Prevents synthetics from being able to rig and throw rigged power cells.
  code/modules/power/cell.dm
Labels: Fix

#435 Adds nightvision for SA.
  code/modules/clothing/glasses/glasses.dm
Labels: Fix

#434 deletes old gun sprites
  icons/obj/items/gun.dmi
Labels: Sprites

#432 Fixes window frame repairs.
  code/game/objects/structures/window_frame.dm
Labels: Fix

#419 Changes PMC rank names.
  code/game/jobs/access.dm
Labels: Tweak

#429 Adds Xeno names
  code/__HELPERS/unsorted.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/panels/traitor_panel.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Feature

#422 Minor adjustment to turret sprites.
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  icons/Marine/new_sentry.dmi
  icons/Marine/new_sentry_alt.dmi
  icons/Marine/sentry.dmi
  icons/Marine/turret.dmi
  icons/Marine/weyland.dmi
Labels: Removal, Sprites
