Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2019-12, with the labels that each got.

#3497 Revert "autobuild tgui-next (#3458)"
  .github/workflows/autobuild_tgui.yml
Labels: GitHub, Revert

#3495 Barbed wire duping fix
  code/game/objects/structures/barricade.dm
Labels: Fix

#3500 Assembly runtime fix
  code/modules/assembly/holder.dm
Labels: Fix

#3496 Main overwatch computer fix
  code/game/objects/machinery/overwatch.dm
Labels: Fix

#3501 Lever Action Rifle sprite fix
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
Labels: Fix

#3493 Buffs LMG and removes starting bipod from it
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
Labels: Balance/Rebalance, Removal, Requires Testing

#3484 Adds an admin approval proc
  code/__HELPERS/admin.dm
  code/game/objects/machinery/computer/communications.dm
  code/modules/admin/topic.dm
  tgmc.dme
Labels: Test Merge Candidate

#3442 Makes duplicate name joining a config option
  code/controllers/configuration/entries/general.dm
  code/datums/gamemodes/game_mode.dm
Labels: Code Improvement, Config Update

#3489 Changes Xeno Latespawns to be weighted depending on Human Jobs
  code/__DEFINES/jobs.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/survivor.dm
  code/game/objects/machinery/cryopod.dm
Labels: Balance/Rebalance, Config Update, Refactor, Requires Testing

#3503 Fix dumb ancient text procs
  Dockerfile
  code/__DEFINES/typeids.dm
  code/__HELPERS/text.dm
  code/__HELPERS/unsorted.dm
  code/datums/datacore.dm
  code/game/objects/items/paint.dm
  code/game/objects/machinery/computer/arcade.dm
  code/game/objects/machinery/computer/card.dm
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/machinery/computer/marines_consoles.dm
  code/game/objects/machinery/doors/brigdoors.dm
  code/game/objects/structures/barsign.dm
  code/modules/admin/verbs/varedit.dm
  code/modules/mob/mob_helpers.dm
  code/modules/paperwork/carbonpaper.dm
  code/modules/paperwork/paper.dm
  code/modules/shuttle/supply.dm
Labels: Code Improvement, Priority: High

#3506 Fixes resinwalker
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Bug, Fix

#3507 Removes a layer of wrapper for tool_act.
  code/_onclick/item_attack.dm
  code/game/atoms.dm
  code/modules/requisitions/fulton.dm
Labels: Removal

#3511 LZ shutters now require access to open
  code/game/objects/machinery/buttons.dm
Labels: Feature

#3508 Adds screwdriver sounds for opening and closing airlock panels.
  code/game/objects/machinery/doors/airlock.dm
Labels: Sound

#3510 Nerfs warrior
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Labels: Balance/Rebalance

#3485 Plasma gain while standing is nerfed; buffed when resting
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance/Rebalance

#3520 Tweaks footsteps
  code/__DEFINES/footsteps.dm
  code/datums/components/footstep.dm
  sound/effects/footstep/alien_resin_move1.ogg
  sound/effects/footstep/alien_resin_move2.ogg
Labels: Sound, Tweak

#3523 Removes /obj/item/projectile in favour of /obj/projectile
  code/__DEFINES/components.dm
  code/_onclick/adjacent.dm
  code/datums/components/full_auto_fire.dm
  code/datums/components/squeak.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/machinery/computer/HolodeckControl.dm
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/machinery/sentries.dm
  code/game/objects/machinery/smartgun_mount.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/stool_bed_chair_nest/janicart.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/simple_animal/friendly/parrot.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/misc.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/projectile.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/vehicles/multitile/hardpoints.dm
Labels: Refactor, Removal

#3513 Distress resin silos
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Feature

#3466 Stale automarking
  .github/workflows/stale.yml
Labels: GitHub

#3499 Fluff sprites
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/__DEFINES/objects.dm
  code/datums/jobs/job/shipside.dm
  code/datums/supplypacks.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/head_0.dmi
  icons/mob/suit_0.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Map Edit, Sprites

#3512 Fixes marines being able to bypass the SD shutters
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Map Edit

#3536 Add feedback for vendored items
  code/game/objects/machinery/vending/vending.dm
Labels: Trivial

#3539 Revert "Stale automarking"
  .github/workflows/stale.yml
Labels: GitHub, Revert

#3529 Xeno MouseDrop fix
  code/modules/mob/mob.dm
Labels: Fix, Priority: High

#3533 Scout cloak tweak
  code/game/objects/items/storage/backpack.dm
Labels: Tweak

#3532 Item storage runtime fix
  code/game/objects/items/storage/storage.dm
Labels: Fix

#3531 Bumps the nuke up a few layers
  code/game/objects/machinery/nuclearbomb.dm
Labels: Fix, Trivial

#3530 Deprecated shuttle proc
  code/__DEFINES/shuttles.dm
  code/controllers/subsystem/shuttle.dm
Labels: Fix, Removal

#3528 Makes trees transparent if important objects are hiding behind them.
  code/__DEFINES/components.dm
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/datums/components/largeobjecttransparency.dm
  code/game/atoms.dm
  code/game/objects/machinery/nuclearbomb.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/egg_item.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/living_defines.dm
  tgmc.dme
Labels: Fix, Requires Testing, Tweak

#3505 Shield component
  code/__DEFINES/combat.dm
  code/__DEFINES/components.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/_onclick/item_attack.dm
  code/datums/components/shield.dm
  code/game/objects/items.dm
  code/game/objects/items/cloaking.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/toys/toy_weapons.dm
  code/game/objects/items/weapons/energy.dm
  code/game/objects/items/weapons/holo_weapons.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/projectile.dm
  code/modules/requisitions/fulton.dm
  icons/effects/effects.dmi
  tgmc.dme
Labels: Feature, Sprites

#3556 Update layers.dm
  code/__DEFINES/layers.dm
Labels: Trivial

#3547 larva generation math now rounds to nearest full integer rather than flooring
  code/datums/gamemodes/game_mode.dm
Labels: Balance/Rebalance

#3552 Reduce hunter knockdown from max of 6 secs to 0.5
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Balance/Rebalance

#3541 Speed up larva growth
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
Labels: Tweak

#3544 Add Fax on bioscan
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/game_mode.dm
Labels: Feature

#3546 Buff xeno rested healing
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance/Rebalance, Requires Testing

#3549 Move the xeno hive on icy caves
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Map Edit, Trivial

#3550 Increase larvas worth points of a spec
  code/__DEFINES/jobs.dm
Labels: Balance/Rebalance, Requires Testing

#3554 Updated acid spray processing
  code/game/objects/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Test Merge Candidate

#3545 Small buff to xeno contruction
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Requires Testing, Tweak

#3567 Move the nuke to the top right of icy_caves
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/tyson_station.json
  _maps/vapor_processing.json
Labels: Map Edit, Tweak

#3569 Update power usage
  code/game/objects/machinery.dm
  code/game/objects/machinery/OpTable.dm
  code/game/objects/machinery/Sleeper.dm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/air_alarm.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/autolathe.dm
  code/game/objects/machinery/bots/bots.dm
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/cell_charger.dm
  code/game/objects/machinery/computer/camera_console.dm
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/game/objects/machinery/dropship_part_fabricator.dm
  code/game/objects/machinery/fire_alarm.dm
  code/game/objects/machinery/flasher.dm
  code/game/objects/machinery/holosign.dm
  code/game/objects/machinery/igniter.dm
  code/game/objects/machinery/kitchen/gibber.dm
  code/game/objects/machinery/kitchen/microwave.dm
  code/game/objects/machinery/kitchen/processor.dm
  code/game/objects/machinery/kitchen/smartfridge.dm
  code/game/objects/machinery/recharger.dm
  code/game/objects/machinery/scoreboard.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/electricchair.dm
  code/game/objects/structures/prop.dm
  code/modules/economy/ATM.dm
  code/modules/hydroponics/biogenerator.dm
  code/modules/power/generator.dm
  code/modules/power/lighting.dm
  code/modules/power/power_monitor.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/recycling/conveyor2.dm
  code/modules/research/rdmachines.dm
  code/modules/security_levels/keycard_authentication.dm
Labels: Tweak

#3553 Removes M4RA double damage button (burst mode) (again)
  code/modules/projectiles/guns/specialist.dm
Labels: Balance/Rebalance, Needs Balance Review, Removal

#3572 Update flame turfs for incen grenades
  code/__HELPERS/patterns.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Tweak

#3570 Autodoc balancing
  code/game/objects/machinery.dm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/fusion_engine.dm
  code/modules/power/smes.dm
Labels: Balance/Rebalance

#3577 Gun rebalance, Mostly DMR
  code/datums/gamemodes/distress.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/obj/items/ammo.dmi
Labels: Balance/Rebalance, Feature, Requires Testing, Sprites, Tweak

#3573 Meson Rebalance
  code/modules/clothing/glasses/meson.dm
Labels: Balance/Rebalance

#3586 removes ammo box magic tricks
  code/modules/projectiles/ammunition.dm
Labels: Fix

#3584 makes m4ra actually not burst & sets burst_amounts to 1
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Balance/Rebalance

#3571 Ports TG Hallucinations
  code/__DEFINES/mobs.dm
  code/__HELPERS/_string_lists.dm
  code/_onclick/ventcrawl.dm
  code/game/sound.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/living_defines.dm
  strings/hallucinations.json
  tgmc.dme
Labels: Feature

#3212 Suit Autodoc component
  code/_onclick/hud/screen_objects.dm
  code/controllers/admin.dm
  code/datums/actions/action.dm
  code/datums/actions/xeno_action.dm
  code/datums/components/suit_autodoc.dm
  code/game/atoms.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/monkey/examine.dm
  code/modules/mob/living/silicon/ai/examine.dm
  icons/mob/screen_alert.dmi
  tgmc.dme
Labels: Code Improvement, Requires Testing, Sprites

#3597 Adds a signal for a mob being revived
  code/__DEFINES/components.dm
  code/modules/mob/living/living_health_procs.dm
Labels: Code Improvement, Trivial

#3579 Readds ravage ability to ravager, tweaks damage, cooldowns and plasma costs
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
Labels: Balance/Rebalance, Needs Balance Review, Requires Testing, Tweak

#3602 Fixes distress call
  code/game/objects/machinery/computer/communications.dm
Labels: Fix

#3594 Cleans up the title of the marine vendor
  tgui-next/packages/tgui/interfaces/MarineSelector.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Fix, UI

#3588 makes DNR people become skulls on medhud
  code/game/data_huds.dm
  code/game/objects/items/defibrillator.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Feature

#3591 Fixes the DMR default ammo
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#3593 Buff surgery based on skills
  code/modules/surgery/surgery.dm
Labels: Balance/Rebalance

#3595 Ensure we have roundstart xenos on crash
  code/datums/gamemodes/crash.dm
Labels: Fix

#3601 Fixes semi-eternal deafness
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix

#3600 Unlock airlocks on hijack
  code/modules/shuttle/marine_dropship.dm
Labels: Fix

#3605 Add more space near the blue disk generator
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Map Edit, Tweak

#3606 allow lamps to be broken
  code/game/objects/items/flashlight.dm
Labels: Feature

#3604 SL Buff and PMC SG nerf
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance/Rebalance, Code Improvement, Feature, Requires Testing

#3535 Some balance changes to attachments
  code/modules/projectiles/gun_attachables.dm
Labels: Balance/Rebalance

#3613 Allows the keybinding of defenders forward charge
  code/__DEFINES/components.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Fix
