Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2019-10, with the labels that each got.

#3019 Bandannas and Goggles
  code/__DEFINES/mobs.dm
  code/_globalvars/lists/objects.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/breath.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/eyes.dmi
  icons/mob/head_0.dmi
  icons/mob/helmet_garb.dmi
  icons/mob/mask.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
Labels: Requires Testing

#3042 Revert
  code/__HELPERS/game.dm
Labels: Revert

#3025 ice lz1 unshrunk
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Fix, Map Edit

#3016 Buffs base marine glove melee protection.
  code/modules/clothing/gloves/marine_gloves.dm
Labels: Balance/Rebalance, Requires Testing

#3014 neuro*0.8
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Requires Testing

#3044 Moved medical survivor spawn
  _maps/map_files/LV624/LV624.dmm
Labels: Fix, Map Edit

#3015 gives acid AMMO_EXPLOSIVE
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Requires Testing

#3027 fix travis eol nl check
  .travis.yml
  code/game/area/tyson_station.dm
  code/game/objects/effects/countdown.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/circuitboards/mecha.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/unit_tests/component_tests.dm
  code/modules/unit_tests/subsystem_init.dm
  code/modules/unit_tests/timer_sanity.dm
  tgmc.dme
  tools/travis/check_grep.sh
Labels: GitHub

#3049 fixes a bug with the box of 45 caliber mismatch
  code/modules/projectiles/updated_projectiles/magazines/pistols.dm
Labels: Fix

#2996 Ovi removal and abilities rework
  code/__DEFINES/components.dm
  code/_onclick/click.dm
  code/_onclick/xeno.dm
  code/datums/keybinding/xeno.dm
  code/game/objects/ovipositor.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/egg_item.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  icons/Xeno/Ovipositor.dmi
  tgmc.dme
Labels: Balance/Rebalance, Feature, Removal, Sprites

#3054 Fix heart pulse issues
  code/game/objects/items/scanners.dm
  code/game/objects/machinery/OpTable.dm
  code/game/objects/machinery/Sleeper.dm
  code/game/objects/machinery/autodoc.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/life/handle_pulse.dm
Labels: Fix

#3056 cryobag scanner fix
  code/game/objects/items/bodybag.dm
Labels: Fix

#3057 Small human and defib cleanup
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/items/defibrillator.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_helpers.dm
Labels: Config Update

#3031 B18 no longer let's you have hair sticking out
  code/modules/clothing/head/helmet.dm
Labels: Test Merge Candidate

#3033 Adds belt harnesses
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/job/survivor.dm
  code/datums/supplypacks.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  icons/mob/belt.dmi
  icons/obj/clothing/belts.dmi
Labels: Balance/Rebalance, Feature, Requires Testing, Sprites

#3020 More armor and no more Squad markings on armor
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/datums/jobs/squads.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Removal, Requires Testing, Sprites

#3053 Table-ghost interaction fix.
  code/game/objects/structures/tables_racks.dm
Labels: Fix

#3038 Burrowed larva and larva now count towards xenomorph evolution tier and queen calculation
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance/Rebalance, Requires Testing, Test Merge Candidate

#3074 Boiler Gas Message Fix
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Fix

#2764 Round end after xenos defuse the nuke
  code/__DEFINES/components.dm
  code/__DEFINES/mode.dm
  code/datums/gamemodes/crash.dm
  code/game/objects/machinery/nuclearbomb.dm
Labels: Tweak

#3022 New, harder to see, resin traps
  icons/Xeno/Effects.dmi
Labels: Balance/Rebalance, Needs Review, Requires Testing, Sprites

#3048 HPR Rework
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/generic/Admin_Level.dmm
  code/datums/emergency_calls/supplies.dm
  code/datums/supplypacks.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
Labels: Balance/Rebalance, Map Edit, Requires Testing

#3080 Mob processing issues
  code/controllers/subsystem/mobs.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/living_health_procs.dm
Labels: Fix

#3075 Undoes literally EVERYTHING Kuro has done regarding Armor
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/datums/jobs/squads.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Removal, Sprites

#3061 Hyperzine rebalance mk2
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: Balance/Rebalance

#3018 Changes the shrike's abilities
  code/__DEFINES/components.dm
  code/__HELPERS/unsorted.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
Labels: Balance/Rebalance, Feature

#3047 m43 lens attachments
  code/datums/gamemodes/distress.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/codex/entries/weapons_codex.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  icons/Marine/marine-weapons.dmi
Labels: Balance/Rebalance, Feature, Sprites

#3059 Defender Armor Rebalancing
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
Labels: Balance/Rebalance, Requires Testing

#3005 Map-dependent armor and gun sprite variants
  code/__DEFINES/objects.dm
  code/datums/supplypacks.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  icons/obj/items/gun.dmi
Labels: Sprites

#3086 """""Final""""" Armor sprite overhaul
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Sprites

#3079 Explosive projectiles will try to hit a target before exploding in the turf
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Fix

#3064 Stops resin sacs and resin holes being placed on the same turf
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Balance/Rebalance, Trivial

#3070 removes fog from distress
  code/__DEFINES/mode.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
Labels: Balance/Rebalance, Removal, Requires Testing

#3089 Adds an iconstate for latejoin landmarks
  code/game/objects/effects/landmarks/landmarks.dm
  icons/mob/landmarks.dmi
Labels: Sprites

#3023 Shuttle ripple effect icon
  icons/effects/effects.dmi
Labels: Sprites

#3087 Changes to the map that no one will notice
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Map Edit

#3094 fix travis greps
  _maps/map_files/Port_Hamburg/Port_Hamburg.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  code/game/area/port_hamburg.dm
  code/game/area/vaporprocessing.dm
  code/modules/lighting/lighting_source.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  tgmc.dme
  tools/travis/check_grep.sh
Labels: Map Edit, Tools

#3090 add crash stuff to vaporprocessing
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
Labels: Map Edit

#3091 seals up outside of tyson and makes it playable for crash
  _maps/map_files/Tyson_Station/Tyson_Station.dmm
  code/game/objects/structures/window.dm
  code/game/turfs/walls/wall_types.dm
Labels: Map Edit

#3071 makes fog only protect xeno silos on crash gamemode
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/__DEFINES/mode.dm
  code/_globalvars/lists/mapping.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/game_mode.dm
  code/game/objects/effects/landmarks/mode.dm
Labels: Balance/Rebalance, Map Edit, Requires Testing

#3084 Nerfed 88 Mod 4 (VP 70)
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
Labels: Balance/Rebalance, Requires Testing

#3067 Medic chems
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Balance/Rebalance, Feature, Removal, Requires Testing

#3095 Gives Xeno Queen Call of the Burrowed
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Feature

#3097 fix errant area varedit
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
Labels: Map Edit

#3101 lints COMSIG_MOVABLE_BUMP
  code/game/atoms_movable.dm
  code/game/objects/machinery/bots/medbot.dm
Labels: Code Improvement, Tools

#3102 Adds a dreamchecker task for vscode users
  .gitignore
  .vscode/extensions.json
  .vscode/tasks.json
Labels: GitHub, Tools

#3082 Hunter Stealth Attack Nerf
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
Labels: Balance/Rebalance

#3072 tweak cant to be less xeno rush friendly
  _maps/shuttles/tgs_canterbury.dmm
Labels: Balance/Rebalance, Map Edit, Requires Testing

#3106 No dummy cameras
  code/datums/outfit.dm
Labels: Fix

#3107 AI interaction fixes
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/computer/communications.dm
  code/game/objects/machinery/overwatch.dm
Labels: Fix

#3108 Fixes respawn timer
  code/__DEFINES/mode.dm
  code/_globalvars/admin.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#3115 Limb armor on unequip fix
  code/__DEFINES/objects.dm
  code/game/objects/items/restraints.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/mob.dm
Labels: Fix

#3111 Adds "Bomber" as a lobby song
  code/controllers/subsystem/ticker.dm
  sound/music/Bomber.ogg
Labels: Sound

#3076 A few Requsitions changes
  code/datums/supplypacks.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/gun.dmi
Labels: Balance/Rebalance, Sprites

#3100 SG and M41A Reworks
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Balance/Rebalance, Feature, Removal

#3096 Pheromone Mini-Rework
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/vehicles/multitile/cm_armored.dm
Labels: Balance/Rebalance, Removal, Requires Testing

#3109 makes staggerstun args more sensible
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Code Improvement

#3105 Dropship Turret Nerf
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#3128 Xeno-damageable windoors
  code/game/objects/machinery/doors/windowdoor.dm
Labels: Fix

#3127 Signal emote fix
  code/modules/mob/living/carbon/human/emote.dm
Labels: Fix

#3126 Table bugs
  code/game/objects/structures/tables_racks.dm
Labels: Fix

#3132 Cuts back a bit on how stealthy Resin Holes are
  icons/Xeno/Effects.dmi
Labels: Balance/Rebalance, Sprites

#3138 Queen and ruler death fixes.
  code/__DEFINES/mobs.dm
  code/__DEFINES/mode.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/admin/panels/mode_panel.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Code Improvement, Feature, Fix, Tweak

#3139 Crash xeno respawn fix
  code/datums/gamemodes/crash.dm
Labels: Fix

#3140 Non-distress evolution_stored
  code/__DEFINES/mode.dm
  code/datums/gamemodes/distress.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance/Rebalance

#3141 Autodoc cleanup and fixes
  code/game/objects/machinery/autodoc.dm
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Fix

#3144 Removes msg_admin_attack
  code/__DEFINES/preferences.dm
  code/_onclick/item_attack.dm
  code/_onclick/telekinesis.dm
  code/game/objects/items/flash.dm
  code/game/objects/items/gift_wrappaper.dm
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/reagent_containers/dropper.dm
  code/game/objects/items/reagent_containers/food/condiment.dm
  code/game/objects/items/reagent_containers/food/drinks.dm
  code/game/objects/items/reagent_containers/food/drinks/bottle.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/reagent_containers/robodropper.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/tools/misc_tools.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/machinery/kitchen/gibber.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/watercloset.dm
  code/game/objects/structures/window.dm
  code/modules/admin/holder.dm
  code/modules/admin/preferences_verbs.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/organs/limb_objects.dm
  code/modules/organs/organ_objects.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Administration, Removal

#3146 Fixes the helmet sprites
  icons/mob/head_1.dmi
Labels: Fix, Sprites

#3116 513 compat
  Dockerfile
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/maths.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/plane_master.dm
  code/game/objects/machinery/autodoc.dm
  code/modules/organs/limbs.dm
  code/modules/surgery/generic.dm
Labels: Code Improvement

#3134 More xeno vision types
  code/_onclick/hud/alien.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  icons/mob/screen/alien.dmi
Labels: Feature, Sprites

#3131 Xenomorphs no longer get 1.25x or 1.5x critical hits
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Removal

#3029 Ravager is now old ravager, rage removed
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/keybinding/xeno.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
Labels: Balance/Rebalance, Requires Testing, Revert

#3043 TGMC: Return of the Pillar
  _maps/Pillar_of_Spring.json
  _maps/_basemap.dm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/shuttles/escape_shuttle.dmm
  code/datums/shuttles.dm
  code/game/area/mainship.dm
  code/game/objects/items/tools/misc_tools.dm
  code/game/objects/machinery/computer/camera_console.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/machinery/doors/multi_tile.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/machinery/flasher.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/prop.dm
  code/modules/paperwork/folders.dm
  code/modules/power/power_monitor.dm
  code/modules/shuttle/escape_pod.dm
  config/shipmaps.txt
  icons/obj/items/paper.dmi
  icons/turf/area_mainship.dmi
Labels: Config Update, Feature, Map Edit, Sprites

#3051 adds the SX-16 and removes the ZX
  code/datums/gamemodes/distress.dm
  code/datums/supplypacks.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Balance/Rebalance, Config Update, Feature, Removal, Requires Testing, Sound, Sprites

#3124 Small Energy update
  code/datums/emergency_calls/deathsquad.dm
  code/datums/jobs/job/deathsquad.dm
  code/game/objects/items/power_cells.dm
  code/modules/power/cell.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/magazines/energy.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/gun.dmi
  icons/obj/items/projectiles.dmi
Labels: Feature, Sprites, Tweak

#3160 Adds the stasis trait.
  code/__DEFINES/objects.dm
  code/__DEFINES/traits.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/machinery/Sleeper.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/living_defines.dm
  code/modules/organs/limbs.dm
  code/modules/shuttle/escape_pod.dm
Labels: Refactor, Tweak

#3174 check map jsons for fuck ups
  _maps/pillar_of_spring.json
  tools/travis/check_grep.sh
Labels: Tools

#3136 Nerfs Ravager Damage Slightly
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
Labels: Balance/Rebalance, Requires Testing

#3152 Bump Attacks, This time as a component
  code/__DEFINES/components.dm
  code/datums/actions/action.dm
  code/datums/actions/bump_attack_toggle.dm
  code/datums/components/bump_attack.dm
  code/game/atoms_movable.dm
  code/game/visual_objects.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  icons/mob/actions.dmi
  tgmc.dme
Labels: Balance/Rebalance, Feature, Requires Testing, Sprites

#3148 Xeno slashes no longer attempt to slash destroyed (delimbed) limbs
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Fix, Test Merge Candidate

#3149 Delimbs now work off of thresholds instead of rng
  code/modules/organs/limbs.dm
Labels: Balance/Rebalance, Test Merge Candidate

#3147 2 Slight Minigun Nerfs
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Balance/Rebalance, Test Merge Candidate

#3163 Swaps the MP5's accuracy for wielded and unwielded
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
Labels: Fix, Trivial

#3162 Makes rack health sensible
  code/game/objects/structures/tables_racks.dm
Labels: Balance/Rebalance

#3092 ports elements
  code/__DEFINES/components.dm
  code/controllers/subsystem/dcs.dm
  code/controllers/subsystem/garbage.dm
  code/datums/components/full_auto_fire.dm
  code/datums/elements/_element.dm
  code/datums/elements/windowshutter.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/circuitboards/circuitboard.dm
  code/game/objects/items/circuitboards/computer.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/camera/camera_assembly.dm
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/window.dm
  code/modules/atmospherics/machinery/other/meter.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/power/cable.dm
  code/modules/power/terminal.dm
  tgmc.dme
Labels: Requires Testing, Test Merge Candidate

#3088 m39 rework: Slowdown, damage, recoil
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
Labels: Balance/Rebalance, Requires Testing

#3172 Adds map json options to replace hardcoded badcode
  _maps/bigred_v2.json
  _maps/debugdalus.json
  _maps/ice_colony_v2.json
  _maps/lv624.json
  _maps/pillar_of_spring.json
  _maps/port_hamburg.json
  _maps/prison_station_fop.json
  _maps/theseus.json
  _maps/tyson_station.json
  _maps/vapor_processing.json
  code/__DEFINES/maps.dm
  code/controllers/subsystem/mapping.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/map_config.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Labels: Feature, Map Edit, Test Merge Candidate

#3164 Binocs interaction bug fix
  code/game/objects/items/binoculars.dm
Labels: Fix

#3133 Icy Caves Map
  _maps/_basemap.dm
  _maps/icy_caves.json
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/area/icy_caves.dm
  config/maps.txt
  tgmc.dme
Labels: Config Update, Feature, Map Edit

#3165 Small energy pulse rifle update
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/magazines/energy.dm
  icons/mob/ammoHUD.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Tweak

#3178 New Spec armor sprites (And sniper gets a helmet now)
  code/game/objects/items/storage/marine_boxes.dm
  code/modules/clothing/head/helmet.dm
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Feature, Sprites

#3191 Walls on shuttles fixes
  code/game/turfs/floor_types.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#3197 Queen timer fix
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#3187 Boots Change.
  code/modules/clothing/shoes/marine_shoes.dm
Labels: Balance/Rebalance, Requires Testing

#3196 Nightvision
  code/_onclick/hud/alien.dm
Labels: Fix

#3193 Map fixes
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Marine_ball/Marine_ball.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/machinery/door_display/door_display.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
Labels: Fix, Map Edit

#3194 Check-pulse fix
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#3153 M4RA changes
  _maps/map_files/icy_caves/icy_caves.dmm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/magazines/specialist.dm
Labels: Balance/Rebalance, Map Edit, Requires Testing, Test Merge Candidate

#3203 New gun sounds
  sound/weapons/guns/fire/ak47-1.ogg
  sound/weapons/guns/fire/beretta.ogg
  sound/weapons/guns/fire/colt.ogg
  sound/weapons/guns/fire/pistol_service.ogg
Labels: Removal, Sound

#3183 Removes handholding
  code/modules/mob/mob.dm
Labels: Removal, Tweak

#3201 Makes vapor less bad
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
Labels: Map Edit, Tweak
