Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2019-05, with the labels that each got.

#1417 Fixes delay round end verb
  code/modules/admin/server_verbs.dm
Labels: Administration

#1388 Makes the chat loading smoother
  code/modules/client/client_procs.dm
  code/modules/mob/login.dm
  code/modules/mob/new_player/login.dm
  goon/code/datums/browserOutput.dm
Labels: QoL

#1394 The port of NanoUI itself
  code/__DEFINES/machines.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/text.dm
  code/controllers/stonedmc/subsystem/nano.dm
  code/controllers/stonedmc/subsystem/nanoui.dm
  code/global.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/client/asset_cache.dm
  code/modules/client/client_procs.dm
  code/modules/nano/JSON_Reader.dm
  code/modules/nano/JSON_Writer.dm
  code/modules/nano/_JSON.dm
  code/modules/nano/interaction/admin.dm
  code/modules/nano/interaction/base.dm
  code/modules/nano/interaction/conscious.dm
  code/modules/nano/interaction/contained.dm
  code/modules/nano/interaction/default.dm
  code/modules/nano/interaction/interactive.dm
  code/modules/nano/interaction/inventory.dm
  code/modules/nano/interaction/inventory_deep.dm
  code/modules/nano/interaction/outside.dm
  code/modules/nano/interaction/physical.dm
  code/modules/nano/interaction/remote.dm
  code/modules/nano/interaction/self.dm
  code/modules/nano/interaction/zlevel.dm
  code/modules/nano/nanoexternal.dm
  code/modules/nano/nanomanager.dm
  code/modules/nano/nanomapgen.dm
  code/modules/nano/nanoui.dm
  nano/css/icons.css
  nano/css/shared.css
  nano/js/libraries-old.min.js
  nano/js/libraries.min.js
  nano/js/libraries/jquery-ui.js
  nano/js/libraries/jquery.js
  nano/js/libraries/jquery.timers.js
  nano/js/nano_base_callbacks.js
  nano/js/nano_base_helpers.js
  nano/js/nano_state.js
  nano/js/nano_state_manager.js
  nano/js/nano_utility.js
  nano/templates/cryo.tmpl
  nano/templates/layout_default.tmpl
  nano/templates/layout_default_header.tmpl
  tgmc.dme
Labels: Code Improvement, Performance

#1329 standardise obj health vars
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/generic/Admin_Level.dmm
  code/game/machinery/bees_apiary.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/floorbot.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/groundmap_geothermal.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/hoverpod/hoverpod.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_control_console.dm
  code/game/mecha/medical/odysseus.dm
  code/game/mecha/working/ripley.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/objs.dm
  code/game/objects/structures.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/cargo_container.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/lamarr_cage.dm
  code/game/objects/structures/plants.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_aliens/weeds.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/sculpture.dm
  code/modules/mob/living/simple_animal/hostile/shyguy.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
  code/modules/recycling/disposal.dm
Labels: Code Improvement, Map Edit, Refactor, Test Merge Candidate

#1344 Refactor mob/living/attack_alien
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/living.dm
Labels: Refactor, Test Merge Candidate

#1415 Fix Prae speed exploit
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
Labels: Fix, Test Merge Candidate

#1408 Cocking a weapon without a mag ejects a working round
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
Labels: Fix, Test Merge Candidate

#1382 Fixes wounds overlays
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  icons/Xeno/wound_overlays.dmi
Labels: Fix, Sprites, Test Merge Candidate

#1414 Fixes resin walls cannibalizing weeds
  code/game/turfs/walls/wall_types.dm
Labels: Fix

#1389 /tg/ machinery/button
  code/game/machinery/buttons.dm
  icons/obj/machines/buttons.dmi
Labels: Sprites, Test Merge Candidate

#1370 Resist time lowered, clean and refactor.
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  tgmc.dme
Labels: Balance/Rebalance, Code Improvement, Refactor

#1423 Medevac beacons can no longer be overwritten while locked
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Tweak

#1429 Fixes double message on cloak deactivation
  code/game/objects/items/storage/backpack.dm
Labels: Fix, Test Merge Candidate

#1432 sublime users dont have access to dm langserver
  code/game/jobs/squads.dm
Labels: Trivial

#1416 Fixes Xeno healing without a queen present
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance/Rebalance, Fix

#1218 Tank Tweak/Rebalance - TESTED
  code/__DEFINES/objects.dm
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/vehicles/multitile/hardpoints.dm
Labels: Balance/Rebalance, Test Merge Candidate, Tweak

#1430 Fixes camera autoname bug
  code/game/machinery/camera/presets.dm
Labels: Fix

#1431 Makes Past Scan Interface ~Fancy~
  code/game/machinery/Sleeper.dm
  code/game/machinery/autodoc.dm
  code/game/objects/items/bodybag.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Test Merge Candidate, Tweak

#1367 Tweaks on xeno sting and larval growth serum.
  code/modules/mob/living/carbon/xenomorph/powers.dm
  code/modules/reagents/chemistry_reagents/other.dm
Labels: Balance/Rebalance, Test Merge Candidate

#1435 Adjust lighttube position to sit better on walls
  code/modules/power/lighting.dm
Labels: Test Merge Candidate, Tweak

#1463 Removes purrbation
  code/modules/admin/verbs/datumvars.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Removal

#1438 Reduces job datum instance creation, fixes ERT ranks
  code/datums/emergency_calls/clf.dm
  code/datums/emergency_calls/colonists.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/emergency_calls/freelancers.dm
  code/datums/emergency_calls/imperium.dm
  code/datums/emergency_calls/pizza.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/emergency_calls/upp.dm
  code/datums/emergency_calls/upp_commando.dm
  code/game/jobs/job/other.dm
Labels: Fix

#1439 Fixes the evil squad change console
  code/modules/cm_marines/marines_consoles.dm
Labels: Fix

#1440 Fixes queen being unable to launch the shuttle
  code/modules/nano/interaction/default.dm
Labels: Fix

#1448 Fixes rejuvenate HUD graphical issues
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living_health_procs.dm
Labels: Fix

#1451 Fixes EORD shuttle windows
  code/game/objects/structures/window.dm
Labels: Fix

#1449 Fixes medibots not injecting custom chems
  code/game/machinery/bots/medbot.dm
Labels: Fix

#1450 Fixes xeno tunnels
  code/game/gamemodes/game_mode.dm
Labels: Fix

#1453 Fixes req elevator crates falling down
  code/modules/mob/mob_grab.dm
Labels: Fix

#1444 Adds sounds for cigs, lighters and matches
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/tools/flame_tools.dm
  sound/items/cig_light.ogg
  sound/items/cig_snuff.ogg
  sound/items/lighter_off.ogg
  sound/items/lighter_on.ogg
  sound/items/matchstick_hit.ogg
  sound/items/matchstick_lit.ogg
  sound/items/zippo_off.ogg
  sound/items/zippo_on.ogg
Labels: Sound, Test Merge Candidate

#1445 Adds sounds for flashlights and flares
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/flashlight.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  sound/items/flare.ogg
  sound/items/flashlight.ogg
Labels: Sound, Test Merge Candidate

#1454 moving wallframes.dmi south sprites down by 1-2 px.
  icons/obj/wallframes.dmi
Labels: Sprites, Test Merge Candidate

#1446 Adds sounds for writing on paper and using stamps
  code/modules/paperwork/paper.dm
  sound/items/stamp.ogg
  sound/items/write1.ogg
  sound/items/write2.ogg
Labels: Sound, Test Merge Candidate

#1337 Use SSdirection for queen locator
  code/__DEFINES/mobs.dm
  code/controllers/stonedmc/subsystem/direction.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living.dm
Labels: Code Improvement, Test Merge Candidate

#1201 Refactoring Xeno Ability Buttons
  code/_onclick/hud/screen_objects.dm
  code/_onclick/xeno.dm
  code/datums/action.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_defines.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  icons/mob/actions.dmi
  tgmc.dme
Labels: Refactor, Sprites, Test Merge Candidate, Tweak

#1468 Supply drops begone.
  code/datums/emergency_calls/supplies.dm
Labels: Removal

#1470 debunks snowflake wooden barricades.
  code/game/objects/structures/barricade.dm
Labels: Fix, Test Merge Candidate

#1481 Spellchecking guage to gauge.
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Grammar and Formatting, Trivial

#1471 More health vars
  code/game/objects/items.dm
  code/game/objects/items/ashtray.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/modules/clothing/head/helmet.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/organs/organ_objects.dm
  code/modules/surgery/organs_internal.dm
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/vehicles/multitile/hardpoints.dm
  code/modules/vehicles/multitile/tank.dm
  code/modules/vehicles/multitile/tankvendor.dm
  code/modules/vehicles/powerloader.dm
  code/modules/vehicles/train.dm
  code/modules/vehicles/vehicle.dm
Labels: Fix, Test Merge Candidate

#1487 remove old trash defines
  code/__DEFINES/__game.dm
  code/_onclick/hud/fullscreen.dm
  code/datums/disease.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/turfs/turf.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Test Merge Candidate

#1483 Adding more specific mapping landmarks.
  code/game/objects/effects/landmarks/itemspawner.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/effects/landmarks/marine_spawns.dm
  code/game/objects/effects/landmarks/mode.dm
  code/game/objects/effects/landmarks/random_item.dm
  code/game/objects/effects/misc.dm
  code/game/objects/effects/spawners/random.dm
  code/game/supplyshuttle.dm
  code/modules/cm_marines/shuttle_backend.dm
  icons/effects/landmarks_static.dmi
  icons/misc/mark.dmi
  icons/mob/landmarks.dmi
  icons/mob/screen1_Clockwork.dmi
  icons/mob/screen1_Midnight.dmi
  icons/mob/screen1_Operative.dmi
  icons/mob/screen1_Orange.dmi
  icons/mob/screen1_Slimecore.dmi
  icons/mob/screen1_White.dmi
  icons/mob/screen1_alien.dmi
  icons/mob/screen1_old.dmi
Labels: Sprites, Test Merge Candidate

#1484 Fixing a blindness issue.
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/living_helpers.dm
Labels: Fix, Test Merge Candidate

#1477 OB wooshing sound
  code/modules/cm_marines/orbital_cannon.dm
  code/modules/cm_marines/overwatch.dm
  sound/effects/OB_incoming.ogg
Labels: Feature, Sound, Test Merge Candidate

#1469 Fixes hardpoints repairing.
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/vehicles/multitile/hardpoints.dm
Labels: Fix

#1478 Adds more bitfields for admin use
  code/_globalvars/bitfields.dm
Labels: Administration

#1486 fixes for ability refactor
  code/datums/action.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix, Priority: CRITICAL, Test Merge Candidate

#1368 Cleaning, fixing, tweaking up chemistry_reagents.
  code/modules/mob/living/carbon/human/species.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/chemistry_reagents/alcohol.dm
  code/modules/reagents/chemistry_reagents/drink.dm
  code/modules/reagents/chemistry_reagents/food.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  code/modules/reagents/chemistry_reagents/other.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
Labels: Code Improvement, Fix, Test Merge Candidate, Tweak

#1460 Add tips
  code/controllers/configuration/configuration.dm
  code/controllers/stonedmc/subsystem/ticker.dm
  strings/tips/marine.txt
  strings/tips/meme.txt
  strings/tips/meta.txt
  strings/tips/xeno.txt
Labels: Config Update, Feature, Test Merge Candidate

#1493 New Shuttle Subsystem + escapepods
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/shuttles/escape_pod.dmm
  code/__DEFINES/__game.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/shuttles.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/unsorted.dm
  code/controllers/shuttle_controller.dm
  code/controllers/stonedmc/subsystem/evacuation.dm
  code/controllers/stonedmc/subsystem/mapping.dm
  code/controllers/stonedmc/subsystem/shuttle.dm
  code/controllers/stonedmc/subsystem/shuttleold.dm
  code/datums/map_config.dm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/turfs/baseturf_skipover.dm
  code/game/turfs/space/transit.dm
  code/game/turfs/turf.dm
  code/modules/cm_marines/shuttle_backend.dm
  code/modules/mob/mob_defines.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/docking.dm
  code/modules/shuttle/escape_pod.dm
  code/modules/shuttle/on_move.dm
  code/modules/shuttle/ripple.dm
  code/modules/shuttle/shuttle.dm
  code/modules/shuttle/shuttle_rotate.dm
  code/modules/shuttles/escape_pods.dm
  icons/obj/device.dmi
  icons/turf/escapepods.dmi
  tgmc.dme
Labels: Map Edit, Sprites

#1494 Makes Rifle Mag Names Match the Rifles
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
Labels: Grammar and Formatting, Test Merge Candidate, Trivial

#1375 Weed subsystem
  code/__DEFINES/subsystems.dm
  code/controllers/stonedmc/subsystem/weeds.dm
  code/modules/cm_aliens/weeds.dm
  tgmc.dme
Labels: Balance/Rebalance, Requires Testing

#1455 G8 pouch tweaks
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/gimmick.dm
  icons/mob/belt.dmi
  icons/obj/clothing/belts.dmi
Labels: Balance/Rebalance, Requires Testing, Sprites, Tweak

#1452 Fixes lasgun underbarrel attachments
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
Labels: Fix

#1496 Potentially fixes #1479
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Fix

#1497 Fixes drones being unable to transfer plasma
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#1498 Fixes invisible scope buttons
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Fix

#1499 Fixes RPG reloading issues
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Fix

#1500 Fixes general circuit board interactions
  code/game/objects/items/circuitboards/circuitboard.dm
Labels: Fix

#1490 removes some trade/shuttle related code
  code/_globalvars/misc.dm
  code/controllers/stonedmc/subsystem/atoms.dm
  code/game/machinery/vending/vending.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/economy/EFTPOS.dm
  code/modules/economy/TradeDestinations.dm
  code/modules/economy/economy_misc.dm
  tgmc.dme
Labels: Removal, Test Merge Candidate

#1489 remove defunct old shuttle code
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/_globalvars/lists/objects.dm
  code/controllers/shuttle_controller.dm
  code/game/area/IceColony.dm
  code/game/area/almayer.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/prisonshuttle.dm
  code/game/objects/items/circuitboards/computer.dm
  code/game/turfs/floor_types.dm
  code/global.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/shuttles/departmental.dm
  code/modules/shuttles/marine_ferry.dm
  code/modules/shuttles/shuttle.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/shuttles/shuttle_hangar.dm
  code/modules/shuttles/shuttles_multi.dm
  tgmc.dme
Labels: Map Edit

#1506 Fixes impact nades scaling
  code/game/gamemodes/distress.dm
Labels: Fix, Test Merge Candidate

#1509 Fixes monkey being untargettable by larval growth.
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Fix, Grammar and Formatting

#1501 Fixes possible observer null name due to admin transformation
  code/modules/admin/topic.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#1516 Ammo sprite tweaks
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
  code/modules/projectiles/updated_projectiles/magazines/specialist.dm
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Sprites, Test Merge Candidate

#1531 Fixes being able to melt the unmeltable.
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix, Priority: High

#1495 Ports /tg/ emote datums
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/typechache.dm
  code/datums/emotes.dm
  code/game/atoms_movable.dm
  code/modules/mob/dead/observer/say.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/brain/emote.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/emote.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/mob.dm
  code/modules/mob/say.dm
  code/modules/reagents/chemistry_reagents/food.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  sound/voice/human_female_laugh_1.ogg
  sound/voice/human_male_laugh_1.ogg
  sound/voice/human_male_laugh_2.ogg
  tgmc.dme
Labels: Code Improvement, Refactor, Sound

#1518 synth repair
  code/game/objects/items/stacks/cable_coil.dm
  code/game/objects/items/tools/maintenance_tools.dm
Labels: Sound, Tweak

#1524 Adds code to stop showing typing icon when logged out
  code/modules/mob/logout.dm
Labels: Fix

#1528 Makes the "Edit Appearance" admin verb better
  code/_globalvars/lists/flavor_misc.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/topic.dm
Labels: Administration

#1529 Fixes secure closet icon states
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
Labels: Fix

#1530 Tweaks the human inventory strip screen
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix, Tweak

#1535 Adds more in-round logging tools
  code/__HELPERS/_logging.dm
  code/_globalvars/logging.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/game_panel.dm
  code/modules/admin/panels/log_panel.dm
  code/modules/admin/topic.dm
  tgmc.dme
Labels: Administration

#1534 [s] Fixes protected lists being able to be shown and edited
  code/modules/admin/verbs/datumvars.dm
  code/modules/admin/verbs/varedit.dm
Labels: Administration, Security Exploit

#1536 Makes the change gamemode admin verb better.
  code/modules/admin/topic.dm
Labels: Administration

#1537 Fixes automute runtimes
  code/modules/admin/panels/ban_panel.dm
Labels: Administration

#1539 Halving kevlar-weave infused bulletproof windows' max integrity.
  code/game/objects/structures/window.dm
Labels: Tweak

#1559 Fixes the RPG being unable to shoot different ammo types.
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Fix

#1569 Add an editorconfig
  .editorconfig
Labels: Tools

#1571 Stops dropship sentries from processing while not deployed.
  code/modules/cm_marines/dropship_equipment.dm
  code/modules/cm_marines/equipment/sentries.dm
Labels: Fix, Test Merge Candidate

#1572 Give survivors firearms 1
  code/datums/skills.dm
Labels: Balance/Rebalance

#1557 Adds laughter, makes contraband pills not so bad.
  code/game/objects/items/reagent_containers/pill.dm
  code/modules/reagents/chemistry_reactions/other.dm
  code/modules/reagents/chemistry_reagents/drink.dm
Labels: Balance/Rebalance, Feature, Test Merge Candidate

#1567 Fixes unconscious xenos sight.
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Fix

#1582 quickfixes spectral bombastics.
  code/game/objects/items/explosives/mine.dm
Labels: Fix, Priority: High, Test Merge Candidate

#1578 Xenos now break barrels properly.
  code/game/objects/structures/crates_lockers/largecrate.dm
Labels: Fix

#1580 Gives CLF leader ammo.
  code/game/jobs/job/clf.dm
Labels: Fix

#1556 adding tox bottles to med vendors
  code/game/machinery/vending/vending_types.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
Labels: Balance/Rebalance, Feature

#1568 Fixes a race condition init runtime
  code/modules/projectiles/updated_projectiles/magazines/specialist.dm
Labels: Fix

#1561 Fixes an ancient init runtime
  code/game/objects/effects/decals/Cleanable/humans.dm
Labels: Fix

#1564 Possibly fixes another runtime
  code/_onclick/click.dm
Labels: Fix

#1594 Fixes ghastly lightstick trampling.
  code/game/objects/items/lightstick.dm
Labels: Fix

#1554 Purges maint drone code
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/unsorted.dm
  code/controllers/configuration/entries/game_options.dm
  code/game/machinery/bots/mulebot.dm
  code/game/objects/items/drone_devices.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/watercloset.dm
  code/game/verbs/suicide.dm
  code/modules/admin/debug_verbs.dm
  code/modules/codex/entries/mobs_codex.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/recycling/disposal.dm
  code/modules/surgery/implant.dm
  tgmc.dme
Labels: Config Update, Removal

#1595 Fixes a dumb sentry runtime with cameras.
  code/__DEFINES/machines.dm
  code/modules/cm_marines/dropship_equipment.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
Labels: Code Improvement, Fix, Test Merge Candidate

#1586 Fixes busy icons displaying over screen objects.
  code/__DEFINES/progress_display.dm
  code/datums/action.dm
  code/datums/progressbar.dm
Labels: Fix, Test Merge Candidate

#1563 Fixes evil emote runtime
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
Labels: Fix

#1599 Ports fit-viewport verb from /TG/
  code/game/verbs/ooc.dm
Labels: Feature

#1555 Improves the "Select Rank" admin verb
  code/game/objects/items/cards_ids.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/topic.dm
Labels: Administration

#1577 Runner balance tweaks
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance/Rebalance, Fix, Test Merge Candidate

#1616 Ports /tg/ observer customization, orbiter component.
  code/__DEFINES/components.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/matrices.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/fullscreen.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/plane_master.dm
  code/_onclick/observer.dm
  code/controllers/_DynamicAreaLighting_TG.dm
  code/datums/components/orbiter.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/logout.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/new_player/new_player.dm
  icons/mob/mob.dmi
  tgmc.dme
Labels: QoL, Sprites

#1605 Smartgun resprite
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/gun.dmi
Labels: Sprites

#1604 Fixes people not being able to respond to IRC admin PMs
  code/modules/admin/admin_verbs.dm
  code/modules/client/client_defines.dm
Labels: Administration

#1617 Fix admin cyro topic
  code/game/machinery/cryopod.dm
Labels: Fix

#1614 Fixes clicking other people to suicide
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Fix

#1610 Makes bwoinks ignore the window flashing preference.
  code/modules/admin/admin_verbs.dm
Labels: Administration

#1609 Fixes hotkey preference not saving.
  code/modules/client/preferences_savefile.dm
Labels: Fix

#1620 Fixes wire cutting issues.
  code/datums/wires/_wires.dm
  code/datums/wires/airalarm.dm
  code/datums/wires/airlock.dm
  code/datums/wires/apc.dm
  code/datums/wires/autolathe.dm
  code/datums/wires/mulebot.dm
  code/datums/wires/radio.dm
  code/datums/wires/vending.dm
Labels: Do Not TM, Fix, Invalid

#1619 Fixes *help spamming the user.
  code/datums/emotes.dm
  code/modules/mob/emote.dm
Labels: Fix, Invalid

#1521 Removes unused helper procs, slightly cleans up and sorts helper code
  code/__HELPERS/_lists.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/files.dm
  code/__HELPERS/game.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/level_traits.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/patterns.dm
  code/__HELPERS/pronouns.dm
  code/__HELPERS/qdel.dm
  code/__HELPERS/sanitize_values.dm
  code/__HELPERS/shell.dm
  code/__HELPERS/sorts/InsertSort.dm
  code/__HELPERS/sorts/MergeSort.dm
  code/__HELPERS/sorts/TimSort.dm
  code/__HELPERS/sorts/__main.dm
  code/__HELPERS/text.dm
  code/__HELPERS/time.dm
  code/__HELPERS/type2type.dm
  code/__HELPERS/unsorted.dm
  code/__HELPERS/view.dm
  code/game/machinery/computer/ai_core.dm
  code/game/mecha/combat/combat.dm
  code/game/objects/items/reagent_containers/food.dm
  code/game/world.dm
  code/modules/client/preferences.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  code/modules/mob/transform_procs.dm
Labels: Code Improvement, Removal

#1491 replace machine and door panel open vars with a flag.
  code/__DEFINES/objects.dm
  code/datums/wires/airalarm.dm
  code/datums/wires/airlock.dm
  code/datums/wires/apc.dm
  code/datums/wires/autolathe.dm
  code/datums/wires/vending.dm
  code/game/machinery/air_alarm.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/groundmap_geothermal.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/machinery.dm
  code/game/machinery/nuclearbomb.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/machinery/vending/vending.dm
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/atmospherics/machinery/components/unary_devices/thermomachine.dm
  code/modules/power/apc.dm
  code/modules/power/batteryrack.dm
  code/modules/power/smes.dm
  code/modules/recycling/conveyor2.dm
Labels: Code Improvement

#1527 increase init speed
  code/controllers/_DynamicAreaLighting_TG.dm
  code/game/area/areas.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/reagent_containers/reagent_container.dm
  code/game/objects/structures/crates_lockers/closets/fitness.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/l3closet.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/turfs/floor.dm
  code/game/turfs/space.dm
  code/game/turfs/turf.dm
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/silicon/ai/freelook/update_triggers.dm
Labels: Code Improvement, Requires Testing

#1474 adds an isnestedhost helper macro
  code/__DEFINES/is_helpers.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Code Improvement

#1633 Power runtime fixes
  code/game/machinery/computer/computer.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/vending/vending.dm
Labels: Fix

#1638 removes some of my own hackiness with lunge
  code/__DEFINES/components.dm
  code/datums/action.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/mob.dm
Labels: QoL, Refactor, Test Merge Candidate

#1643 removes duplicate emote defines
  code/__DEFINES/mobs.dm
Labels: Trivial

#1602 Implements custom hotkeys
  code/__HELPERS/_lists.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/sanitize_values.dm
  code/_globalvars/lists/client.dm
  code/datums/keybinding/_defines.dm
  code/datums/keybinding/admin.dm
  code/datums/keybinding/carbon.dm
  code/datums/keybinding/client.dm
  code/datums/keybinding/human.dm
  code/datums/keybinding/keybinding.dm
  code/datums/keybinding/living.dm
  code/datums/keybinding/mob.dm
  code/datums/keybinding/xeno.dm
  code/modules/client/client_defines.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/keybindings/bindings_carbon.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/bindings_human.dm
  code/modules/keybindings/bindings_mob.dm
  tgmc.dme
Labels: Feature, Test Merge Candidate, Tweak

#1588 Removal of OLD mech code (POWER LOADERS ARE VEHICLE CODE!)
  code/__DEFINES/is_helpers.dm
  code/_globalvars/lists/objects.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/helper_datums/teleport.dm
  code/game/machinery/doors/airlock_control.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/mass_driver.dm
  code/game/mecha/combat/combat.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/equipment/mecha_equipment.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/hoverpod/hoverpod.dm
  code/game/mecha/mech_bay.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mech_sensor.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_control_console.dm
  code/game/mecha/mecha_parts.dm
  code/game/mecha/mecha_wreckage.dm
  code/game/mecha/medical/medical.dm
  code/game/mecha/medical/odysseus.dm
  code/game/mecha/working/ripley.dm
  code/game/mecha/working/working.dm
  code/game/objects/effects/portals.dm
  code/game/objects/items/circuitboards/computer.dm
  code/game/objects/items/circuitboards/mecha.dm
  code/game/objects/items/storage/internal.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/turfs/floor_types.dm
  code/modules/admin/debug_verbs.dm
  code/modules/mob/living/brain/MMI.dm
  code/modules/mob/living/brain/brain.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/retaliate.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob_verbs.dm
  code/modules/power/power.dm
  tgmc.dme
Labels: Removal

#1651 Removes some old js
  code/js/byjax.dm
  code/js/menus.dm
  tgmc.dme
Labels: Removal

#1650 Removes some useless stuff from Life()
  code/__DEFINES/mobs.dm
  code/datums/diseases/xeno_transformation.dm
  code/datums/mob_hud.dm
  code/game/dna/dna2.dm
  code/game/dna/genes/monkey.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/defibrillator.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/life/handle_environment.dm
  code/modules/mob/living/carbon/human/life/handle_random_events.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/transform_procs.dm
  code/modules/reagents/chemistry_reagents/other.dm
  code/modules/surgery/surgery.dm
  tgmc.dme
Labels: Removal

#1641 Cleans up xenomorph gib code
  code/__DEFINES/components.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Code Improvement, Test Merge Candidate

#1597 Ports tool_act
  code/__DEFINES/components.dm
  code/__DEFINES/tools.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/game/atoms.dm
  code/game/machinery/pipe/construction.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/tools/mining_tools.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/other/meter.dm
  code/modules/power/cell.dm
  tgmc.dme
Labels: Code Improvement

#1628 Warrior lunges grab humans in their offhand
  code/datums/keybinding/xeno.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Balance/Rebalance, Tweak

#1623 Balance tweaks.
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Balance/Rebalance

#1646 Removes deprecated elevator object and var
  code/_globalvars/lists/mapping.dm
  code/game/objects/effects/landmarks/landmarks.dm
Labels: Removal

#1657 Give CMO RO and aSL access to the dropship
  code/game/jobs/job/shipside.dm
  code/game/jobs/squads.dm
  code/modules/cm_marines/overwatch.dm
Labels: Feature

#1519 convert ert shuttles to use new shuttle subsystem and ert refactoring
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/shuttles/big_ert.dmm
  _maps/shuttles/distress.dmm
  _maps/shuttles/distress_pmc.dmm
  _maps/shuttles/distress_upp.dmm
  code/controllers/shuttle_controller.dm
  code/controllers/stonedmc/subsystem/shuttle.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/emergency_calls/supplies.dm
  code/datums/emergency_calls/upp.dm
  code/datums/emergency_calls/upp_commando.dm
  code/game/machinery/doors/shutters.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/ert.dm
  code/modules/shuttle/ert_big.dm
  code/modules/shuttle/shuttle.dm
  code/modules/shuttles/shuttle_ert.dm
  tgmc.dme
Labels: Map Edit, Refactor, Test Merge Candidate

#1652 Fixes lightning and vision related issues
  code/__DEFINES/mobs.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/telekinesis.dm
  code/game/objects/items/storage/storage.dm
  code/modules/buildmode/buttons.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
  code/modules/mob/living/carbon/xenomorph/login.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/mob_grab.dm
Labels: Fix, Priority: High

#1331 Adds in the Son of Mars ERT, replacing CLF from active rotation.
  code/__DEFINES/jobs.dm
  code/__DEFINES/radio.dm
  code/datums/emergency_calls/clf.dm
  code/datums/emergency_calls/sonsofmars.dm
  code/game/communications.dm
  code/game/jobs/access.dm
  code/game/jobs/job/sonsofmars.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/radio/encryptionkey.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/Marine/marine-pouches.dmi
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head_1.dmi
  icons/mob/human.dmi
  icons/mob/mob.dmi
  icons/mob/suit_1.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/items/card.dmi
  icons/obj/items/storage/storage.dmi
  tgmc.dme
Labels: Needs Review, Sprites, Tweak

#1658 NOFLAGS to NONE
  code/__DEFINES/equipment.dm
  code/_onclick/telekinesis.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/areas.dm
  code/game/gamemodes/game_mode.dm
  code/game/jobs/job/job.dm
  code/game/machinery/buttons.dm
  code/game/machinery/machinery.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/game/objects/effects/landmarks/random_item.dm
  code/game/objects/items.dm
  code/game/objects/items/tanks/tank_types.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/structures/window.dm
  code/modules/admin/admin_ranks.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/hydroponics/seeds.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/egg_item.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/mob_grab.dm
  code/modules/organs/limbs.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/magazines/flamer.dm
  code/modules/projectiles/updated_projectiles/magazines/revolvers.dm
  code/modules/projectiles/updated_projectiles/magazines/specialist.dm
Labels: Code Improvement, Sprites

#1660 Replaces checkpass with bitfield checks
  code/game/atoms.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/spaceheater.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  code/game/supplyshuttle.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/mob/mob_movement.dm
Labels: Code Improvement

#1656 Atom/movable code cleanup
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  code/__DEFINES/components.dm
  code/__HELPERS/unsorted.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/dna/genes/monkey.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/objs.dm
  code/modules/assembly/proximity.dm
  code/modules/mob/mob.dm
Labels: Code Improvement, Map Edit

#1653 Cleans up and fixes human init
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#1281 [Tested]Third batch of /attackby( changes
  code/game/objects/items/RSF.dm
  code/game/objects/items/ashtray.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/books/book.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/circuitboards/computer.dm
  code/game/objects/items/circuitboards/machine.dm
  code/game/objects/items/coins.dm
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/flashlight.dm
  code/game/objects/items/frames/alarms.dm
  code/game/objects/items/frames/bot_assembly.dm
  code/game/objects/items/frames/camera.dm
  code/game/objects/items/frames/frame.dm
  code/game/objects/items/frames/light_fixtures.dm
  code/game/objects/items/frames/table_rack.dm
  code/game/objects/items/gift_wrappaper.dm
  code/game/objects/items/handcuffs.dm
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/lightreplacer.dm
  code/game/objects/items/megaphone.dm
  code/game/objects/items/radio/detpack.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/reagent_containers/food/sandwich.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/food/snacks/grown.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/shards.dm
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/items/stacks/cable_coil.dm
  code/game/objects/items/stacks/flags.dm
  code/game/objects/items/suit_cooling.dm
  code/game/objects/items/taperecorder.dm
  code/game/objects/items/transfer_valve.dm
  code/game/objects/items/whistle.dm
Labels: Code Improvement

#1283 [Tested]Fourth batch of /attackby( changes
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/stacks/sheets/light.dm
  code/game/objects/items/stacks/snow.dm
  code/game/objects/items/stacks/tiles/light.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/bible.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/items/tanks/tanks.dm
  code/game/objects/items/tools/cleaning_tools.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/items/tools/policetape.dm
  code/game/objects/items/toys/cards.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/barsign.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/bookcase.dm
  code/game/objects/structures/coathanger.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/extinguisher.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/ladders.dm
  code/game/objects/structures/lamarr_cage.dm
Labels: Code Improvement

#1309 [Tested]Seventh batch of /attackby( changes
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/sculpture.dm
  code/modules/mob/living/simple_animal/hostile/shyguy.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/organs/limb_objects.dm
  code/modules/paperwork/clipboard.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/paperwork/paperbin.dm
  code/modules/paperwork/photography.dm
  code/modules/power/apc.dm
  code/modules/power/batteryrack.dm
  code/modules/power/cable.dm
  code/modules/power/cell.dm
  code/modules/power/generator.dm
  code/modules/power/lighting.dm
  code/modules/power/port_gen.dm
  code/modules/power/power.dm
  code/modules/power/power_monitor.dm
  code/modules/power/smes.dm
  code/modules/power/smes_construction.dm
Labels: Code Improvement

#1311 [Tested]Eighth batch of /attackby( changes
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/recycling/conveyor2.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/research/destructive_analyzer.dm
  code/modules/research/protolathe.dm
  code/modules/research/rdconsole.dm
  code/modules/research/server.dm
  code/modules/security_levels/keycard_authentication.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/vehicles/cargo_train.dm
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/vehicles/powerloader.dm
  code/modules/vehicles/vehicle.dm
  goon/code/obj/machinery/bot/chefbot.dm
Labels: Code Improvement, Fix

#1606 Tweaks SQL error handling further.
  code/controllers/stonedmc/subsystem/blackbox.dm
  code/controllers/stonedmc/subsystem/dbcore.dm
  code/modules/admin/debug_verbs.dm
Labels: Administration

#1666 Fixes #1644
  code/__HELPERS/unsorted.dm
  code/game/supplyshuttle.dm
Labels: Priority: CRITICAL

#1673 Fixes missing carpet icon state
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  code/game/turfs/floor_types.dm
Labels: Fix, Map Edit

#1279 [Tested]Second batch of /attackby( changes
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/HolodeckControl.dm
  code/game/machinery/computer/ai_core.dm
  code/game/machinery/computer/aifixer.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/buildandrepair.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/computer/guestpass.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/skills.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/airlock_control.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/poddoor.dm
  code/game/machinery/doors/shutters.dm
  code/game/machinery/doors/unpowered.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/kitchen/gibber.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/kitchen/processor.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/pipe/construction.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/vending.dm
  code/game/mecha/mecha_wreckage.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/effects/glowshroom.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items.dm
  code/game/objects/structures.dm
Labels: Code Improvement

#1288 [Tested]Fifth batch of /attackby( changes
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/game/objects/structures/crates_lockers/secure_crates.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/musician.dm
  code/game/objects/structures/noticeboard.dm
  code/game/objects/structures/plants.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/safe.dm
  code/game/objects/structures/signs.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/janicart.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/tank_dispenser.dm
  code/game/objects/structures/watercloset.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  code/game/turfs/closed.dm
  code/game/turfs/floor.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/snow.dm
  code/game/turfs/space.dm
  code/game/turfs/turf.dm
  code/game/turfs/walls/r_wall.dm
  code/game/turfs/walls/wall_types.dm
  code/game/turfs/walls/walls.dm
  code/modules/almayer/machinery.dm
  code/modules/assembly/holder.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
Labels: Code Improvement

#1304 [Tested]Sixth batch of /attackby( changes
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/atmospherics/machinery/other/meter.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/spacesuits/breaches.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/ties.dm
  code/modules/clothing/under/under.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_aliens/weeds.dm
  code/modules/cm_marines/Marine_Research/BioPrinter.dm
  code/modules/cm_marines/Marine_Research/Organic_Analyzer.dm
  code/modules/cm_marines/codebook.dm
  code/modules/cm_marines/dropship_equipment.dm
  code/modules/cm_marines/equipment/gear.dm
  code/modules/cm_marines/equipment/mortars.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/cm_marines/marines_consoles.dm
  code/modules/cm_marines/orbital_cannon.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/economy/ATM.dm
  code/modules/economy/Accounts_DB.dm
  code/modules/economy/EFTPOS.dm
  code/modules/economy/cash.dm
  code/modules/hydroponics/biogenerator.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/seed_machines.dm
  code/modules/hydroponics/vines.dm
  code/modules/mining/money_bag.dm
  code/modules/mob/holder.dm
Labels: Code Improvement

#1278 [Tested]First batch of /attackby( changes
  code/_onclick/item_attack.dm
  code/game/dna/dna_modifier.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/air_alarm.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/bioprinter.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/floorbot.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/cell_charger.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/door_control.dm
  code/game/machinery/fax.dm
  code/game/machinery/fire_alarm.dm
  code/game/machinery/flasher.dm
  code/game/machinery/floodlight.dm
  code/game/machinery/fuelcell_recycler.dm
  code/game/machinery/fusion_engine.dm
  code/game/machinery/groundmap_geothermal.dm
  code/game/machinery/holosign.dm
  code/game/machinery/igniter.dm
  code/game/machinery/iv_drip.dm
  code/game/machinery/machinery.dm
  code/game/machinery/newscaster.dm
  code/game/machinery/nuclearbomb.dm
  code/game/machinery/recharger.dm
  code/game/machinery/seed_extractor.dm
  code/game/machinery/spaceheater.dm
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/teleporter.dm
  code/game/machinery/washing_machine.dm
Labels: Code Improvement

#1654 Cleans up /atom procs and defines
  code/game/atoms.dm
  code/game/objects/structures/inflatable.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_defines.dm
Labels: Code Improvement

#1659 Implements skeleton crew access
  code/controllers/configuration/entries/game_options.dm
  code/controllers/stonedmc/subsystem/job.dm
  code/game/jobs/job/marines.dm
  code/game/jobs/job/shipside.dm
Labels: Config Update

#1674 Fixes zero timeofdeath
  code/modules/shuttle/shuttle.dm
Labels: Fix

#1683 Fixes admin transformation
  code/modules/mob/mob_transformation_simple.dm
Labels: Fix

#1681 Removes unused js file
  code/modules/html_interface/jquery.min.js
Labels: Removal

#1680 Removes genetic side effects
  code/game/objects/items/dna_injector.dm
  code/modules/genetics/side_effects.dm
  tgmc.dme
Labels: Removal

#1642 Removes HANDLE_STEALTH_CODE_CANCEL
  code/__DEFINES/components.dm
  code/__DEFINES/mobs.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/vehicles/multitile/cm_armored.dm
Labels: Code Improvement, Removal, Requires Testing

#1508 cleaning up screen hud icons & co.
  code/__DEFINES/preferences.dm
  code/__HELPERS/type2type.dm
  code/_onclick/click.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/alien.dm
  code/_onclick/hud/alien_larva.dm
  code/_onclick/hud/fullscreen.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/monkey.dm
  code/_onclick/hud/other_mobs.dm
  code/_onclick/hud/screen_objects.dm
  code/game/machinery/OpTable.dm
  code/game/objects/effects/bump_teleporter.dm
  code/game/objects/effects/manifest.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/effects/spawners/bombspawner.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life/handle_disabilities.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  icons/mob/screen/alien.dmi
  icons/mob/screen/clockwork.dmi
  icons/mob/screen/cyborg.dmi
  icons/mob/screen/full.dmi
  icons/mob/screen/generic.dmi
  icons/mob/screen/generic_old.dmi
  icons/mob/screen/health.dmi
  icons/mob/screen/midnight.dmi
  icons/mob/screen/operative.dmi
  icons/mob/screen/plasmafire.dmi
  icons/mob/screen/retro.dmi
  icons/mob/screen/slimecore.dmi
  icons/mob/screen/white.dmi
  icons/mob/screen/zone_sel.dmi
  icons/mob/screen1.dmi
  icons/mob/screen1_Clockwork.dmi
  icons/mob/screen1_Midnight.dmi
  icons/mob/screen1_Operative.dmi
  icons/mob/screen1_Orange.dmi
  icons/mob/screen1_Slimecore.dmi
  icons/mob/screen1_White.dmi
  icons/mob/screen1_alien.dmi
  icons/mob/screen1_old.dmi
  icons/mob/screen1_robot.dmi
  icons/mob/screen_gen.dmi
  icons/mob/zone_sel.dmi
Labels: Sprites, Test Merge Candidate

#1551 Fixing smoke nades and buffing phosphorus smoke.
  code/__DEFINES/conflict.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/cm_aliens/weeds.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/carbon_status_procs.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_defines.dm
Labels: Balance/Rebalance, Fix, Requires Testing, Tweak
