Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2019-09, with the labels that each got.

#2816 Fixes beret in marine custom loadout and adds a real green beret
  code/modules/client/preferences_gear.dm
  code/modules/clothing/head/head.dm
  icons/mob/head_1.dmi
  icons/obj/clothing/cm_hats.dmi
Labels: Grammar and Formatting, Sprites

#2736 Movespeed mod and datum charge/crushing
  code/__DEFINES/components.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/_onclick/xeno.dm
  code/game/atoms_movable.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/mob_movespeed.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/vehicles/multitile/cm_armored.dm
  tgmc.dme
Labels: Balance/Rebalance, Requires Testing

#2797 Reduces the roundstart notransform lock time
  code/datums/gamemodes/game_mode.dm
Labels: Requires Testing, Tweak

#2821 Fixes a sound runtime
  code/datums/gamemodes/distress.dm
Labels: Fix

#2848 Pyro REEtexture
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Sprites

#2819 New PFC armor sprites and new squad color armor markings
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Sprites

#2830 Ports TG Sofa
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  icons/obj/objects.dmi
Labels: Sprites

#2834 SMG ammunition naming change
  code/modules/projectiles/updated_projectiles/magazines/smgs.dm
Labels: Tweak

#2829 Fix xeno minor conditions
  code/datums/gamemodes/crash.dm
Labels: Fix

#2695 YeeHaw cowboy time, it's a lever action rifle
  code/__DEFINES/mode.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/magazines/pistols.dm
  code/modules/projectiles/updated_projectiles/magazines/revolvers.dm
  code/modules/projectiles/updated_projectiles/magazines/shotguns.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/gun.dmi
Labels: Feature, Sprites

#2823 Fixes powerloader clamp runtimes
  code/modules/vehicles/powerloader.dm
Labels: Fix

#2825 Incoming mentorhelps now have a different sound
  code/modules/admin/verbs/adminhelp.dm
Labels: Administration

#2832 Fixes hunter stealth attack issues
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
Labels: Fix

#2836 Fixes ship map reference name replace
  code/datums/map_config.dm
Labels: Fix

#2837 Fixes aSL not having orders available
  code/datums/jobs/squads.dm
Labels: Fix

#2838 Fixes being able to take over aghosted xenos
  code/__DEFINES/is_helpers.dm
Labels: Fix

#2841 Fixes fortune cookie interactions
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/trash.dm
Labels: Fix

#2842 Fixes unclosed HTML tags
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#2843 Fixes fax machine eating IDs
  code/game/objects/machinery/fax.dm
Labels: Fix

#2846 Fixes xeno beacon
  code/datums/emergency_calls/emergency_call.dm
Labels: Fix

#2851 Admins can now cancel playing a cinematic
  code/modules/admin/fun_verbs.dm
Labels: Administration

#2855 Fixes powerloader attack animation
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#2856 Fixes xeno fog cheesing
  code/modules/mob/mob_grab.dm
Labels: Fix

#2857 Fixes roundstart delay set during early init
  code/controllers/subsystem/ticker.dm
Labels: Fix

#2859 Fixes bad eyesight preference
  code/modules/mob/new_player/preferences_setup.dm
Labels: Fix

#2861 Fixes pyro marine shoes icon
  code/modules/clothing/shoes/marine_shoes.dm
  icons/obj/clothing/shoes.dmi
Labels: Fix, Sprites

#2863 Improves randomize name log
  code/modules/admin/topic.dm
Labels: Administration

#2865 Fixes warrior runtime
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Fix

#2867 Fixes storage window weirdness
  code/game/objects/items/storage/storage.dm
Labels: Fix

#2868 Cleans up headset code
  code/game/objects/items/radio/headset.dm
Labels: Code Improvement

#2833 Removes MP skill and tank access from PMC
  code/__DEFINES/access.dm
  code/datums/jobs/job/pmc.dm
  code/datums/skills.dm
Labels: Removal, Tweak

#2852 Small M39 Mags
  code/modules/projectiles/updated_projectiles/magazines/smgs.dm
Labels: Balance/Rebalance, Test Merge Candidate

#2853 4 Helmet Storage Slots
  code/modules/clothing/head/helmet.dm
Labels: Balance/Rebalance, Test Merge Candidate

#2869 Removed Queen screech's screen shake for xenomorphs
  code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
Labels: Balance/Rebalance, Test Merge Candidate

#2870 Fixes adminwho without mentors
  code/modules/admin/verbs/adminhelp.dm
Labels: Fix

#2871 Fixes flares not burning weeds
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Fix

#2880 Fixes even more fog cheesing
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#2881 Fixes invisible shoes
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Fix

#2873 Youtubedl tweaks
  code/modules/admin/fun_verbs.dm
Labels: Administration

#2882 Fixes more sound runtimes
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
Labels: Fix

#2872 Rage no longer ticks down or gives damage resist
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
Labels: Balance/Rebalance, Test Merge Candidate

#2888 Update CODEOWNERS
  .github/CODEOWNERS
Labels: GitHub

#2885 Fixes goonchat line height for IE8
  goon/browserassets/js/browserOutput.js
Labels: Fix

#2886 Cleans up workaround for fixed compiler bug
  code/modules/admin/SDQL2/SDQL_2_parser.dm
Labels: Tweak

#2884 Cleans up combat defines
  code/__DEFINES/conflict.dm
  code/controllers/configuration/entries/combat_defines.dm
  code/modules/codex/entries/guns_codex.dm
  code/modules/codex/entries/weapons_codex.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/magazines/specialist.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  tgmc.dme
Labels: Config Update, Tweak

#2904 Better Paladin Inhands
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
Labels: Fix, Sprites

#2890 Revert "New PFC armor sprites and new squad color armor markings"
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Revert, Sprites

#2902 Fixes the burger name from -burger and removes 1 bit of whitespace
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
Labels: Grammar and Formatting

#2892 Fixes codex runtime for xeno abilities
  code/modules/codex/entries/mobs_codex.dm
Labels: Fix

#2903 Fixes damage after deletion runtimes
  code/game/objects/explosion.dm
Labels: Fix

#2909 [s] Input sanity
  code/modules/keybindings/bindings_client.dm
Labels: Priority: High, Security Exploit

#2908 Fixes harm intent table interactions
  code/game/objects/structures/tables_racks.dm
Labels: Fix

#2891 Fixes radio destroy runtimes
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/radio/radio.dm
Labels: Fix

#2894 Fixes the mysterious storage runtime for good
  code/game/objects/items/flashlight.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Fix

#2907 Unshitcodes ammoboxes even further
  code/datums/gamemodes/distress.dm
  code/datums/supplypacks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
Labels: Fix

#2919 Fixes a menu runtime
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix

#2877 Improved ERT Spawn Messages
  code/datums/emergency_calls/colonists.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/emergency_calls/freelancers.dm
  code/datums/emergency_calls/pizza.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/emergency_calls/upp.dm
  code/datums/emergency_calls/upp_commando.dm
Labels: Tweak

#2905 Viable Non-standard weapons
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/generic/Admin_Level.dmm
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/upp_commando.dm
  code/datums/supplypacks.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  sound/weapons/guns/fire/M16-1.ogg
  sound/weapons/guns/fire/ak47-1.ogg
  sound/weapons/guns/interact/ak47_cocked.ogg
  sound/weapons/guns/interact/ak47_reload.ogg
  sound/weapons/guns/interact/ak47_unload.ogg
Labels: Map Edit, Sound, Sprites

#2854 Changes the Integrated Storage to hold a gun.
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance/Rebalance, Test Merge Candidate

#2924 Armor and embedding reworks
  code/__DEFINES/combat.dm
  code/datums/embedding_behavior.dm
  code/game/objects/items.dm
  code/game/objects/items/embedding.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implantneurostim.dm
  code/game/objects/items/reagent_containers/food/drinks/bottle.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/shards.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/human/life/handle_status_effects.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/organs/limbs.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/surgery/brainrepair.dm
  code/modules/surgery/eye.dm
  code/modules/surgery/face.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/headreattach.dm
  code/modules/surgery/robolimbs.dm
  tgmc.dme
Labels: Balance/Rebalance, Refactor

#2934 ignore visualstudio compile cache files from midi2piano
  .gitignore
Labels: GitHub

#2913 Changes the way xeno abilities are and buffs defender at ancient
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Balance/Rebalance, Refactor, Requires Testing, Test Merge Candidate

#2883 M3 pattern Harness
  code/game/objects/items/defibrillator.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/suits/marine_armor.dm
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Feature, Sprites, Test Merge Candidate

#2937 copy spacemaniac's travis script improvements
  .dockerignore
  .gitattributes
  .travis.yml
  Dockerfile
  code/__HELPERS/_logging.dm
  code/_compile_options.dm
  code/game/world.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/component_tests.dm
  code/modules/unit_tests/spawn_humans.dm
  code/modules/unit_tests/subsystem_init.dm
  code/modules/unit_tests/timer_sanity.dm
  code/modules/unit_tests/unit_test.dm
  dependencies.sh
  tgmc.dme
  tools/deploy.sh
  tools/travis/before_build_byond.sh
  tools/travis/build_bsql.sh
  tools/travis/build_byond.sh
  tools/travis/check_changelogs.sh
  tools/travis/check_grep.sh
  tools/travis/install_build_tools.sh
  tools/travis/install_byond.sh
  tools/travis/install_libmariadb.sh
  tools/travis/install_rust_g.sh
  tools/travis/install_spaceman_dmm.sh
  tools/travis/run_server.sh
  tools/travis/template_dm_generator.py
  tools/travis/travis_config.txt
Labels: GitHub

#2936 Mrcalzon02maps
  .dockerignore
  _maps/WIP/Z.01.Desert-Dam.dmm
  _maps/_basemap.dm
  _maps/map_files/Port_Hamburg/Port_Hamburg.dmm
  _maps/map_files/Tyson_Station/Tyson_Station.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/port_hamburg.json
  _maps/tyson_station.json
  _maps/vapor_processing.json
  code/game/area/port_hamburg.dm
  code/game/area/tyson_station.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  config/maps.txt
  html/changelog.html
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_suits.dmi
  tgmc.dme
  tools/travis/travis_config.txt
Labels: Test Merge Candidate

#2932 Refits ERT Loadouts
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
Labels: Requires Testing

#2943 Adds prescription glasses to marine loadout
  code/modules/client/preferences_gear.dm
Labels: Trivial

#2948 Removes findeclaration references and cleans up code
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/implants/implantfreedom.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/machinery/bots/mulebot.dm
  code/game/objects/machinery/computer/atmos_alert.dm
  code/game/objects/machinery/computer/buildandrepair.dm
  code/game/objects/machinery/computer/card.dm
  code/game/objects/machinery/computer/medical.dm
  code/game/objects/machinery/computer/pod.dm
  code/game/objects/machinery/computer/security.dm
  code/game/objects/machinery/computer/skills.dm
  code/game/objects/machinery/constructable_frame.dm
  code/game/objects/machinery/doors/brigdoors.dm
  code/game/objects/machinery/recharger.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/mob/living/brain/brain.dm
  code/modules/research/designs.dm
  code/modules/research/rd-readme.dm
  tgmc.dme
Labels: Code Improvement, Removal

#2946 HTML folder cleanup
  code/modules/admin/panels/ban_panel.dm
  code/modules/admin/panels/game_panel.dm
  code/modules/client/asset_cache.dm
  code/modules/client/client_procs.dm
  html/80x15.png
  html/browser/banpanel.css
  html/browser/changelog.css
  html/browser/create_object.html
  html/browser/cryo.css
  html/browser/panels.css
  html/browser/scannernew.css
  html/browser/search.js
  html/browser/sleeper.css
  html/browser/unbanpanel.css
  html/changelog.js
  html/changelogs/changelog2015.html
  html/changelogs/changelog2016.html
  html/changelogs/changelog2017.html
  html/changelogs/changelog20181.html
  html/changelogs/changelog20182.html
  html/images/88x31.png
  html/images/ban.png
  html/images/bug-minus.png
  html/images/burn-exclamation.png
  html/images/chevron-expand.png
  html/images/chevron.png
  html/images/chrome-wrench.png
  html/images/coding.png
  html/images/cross-circle.png
  html/images/hard-hat-exclamation.png
  html/images/high_button.png
  html/images/image-minus.png
  html/images/image-plus.png
  html/images/medium_button.png
  html/images/minor_button.png
  html/images/music-minus.png
  html/images/music-plus.png
  html/images/none_button.png
  html/images/ntlogo.png
  html/images/padlock.png
  html/images/scales.png
  html/images/spell-check.png
  html/images/tg-notif.png
  html/images/tgmclogo.png
  html/images/tick-circle.png
  html/images/wrench-screwdriver.png
  html/old_add-to-changelog.html
  html/postcardsmall.jpg
  html/somerights20.png
Labels: GitHub, Tools

#2945 Goonchat
  code/modules/client/asset_cache.dm
  code/modules/goonchat/browserOutput.css
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserOutput.html
  code/modules/goonchat/browserOutput.js
  code/modules/goonchat/browserOutput_colorblindv1.css
  code/modules/goonchat/font-awesome.css
  code/modules/goonchat/fonts/fontawesome-webfont.eot
  code/modules/goonchat/fonts/fontawesome-webfont.svg
  code/modules/goonchat/fonts/fontawesome-webfont.ttf
  code/modules/goonchat/fonts/fontawesome-webfont.woff
  code/modules/goonchat/fonts/fontawesome-webfont.woff2
  code/modules/goonchat/jquery.min.js
  code/modules/goonchat/json2.min.js
  code/modules/mob/new_player/poll.dm
  goon/LICENSE.md
  goon/README.md
  goon/icons/obj/aibots.dmi
  goon/icons/vehicles.dmi
  goon/sound/effects/dramatic.ogg
  tgmc.dme
Labels: Code Improvement

#2954 Revert suits oof
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Fix

#2938 ballistic armour change
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance/Rebalance, Requires Testing

#2922 Fixes the Lever Action Sprites
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
Labels: Test Merge Candidate

#2914 IFF bullets for M4RA
  code/datums/supplypacks.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/magazines/specialist.dm
  icons/mob/ammoHUD.dmi
  icons/obj/items/ammo.dmi
Labels: Feature, Sprites, Test Merge Candidate

#2939 Adds a heavy-duty harness to the minigun
  code/datums/supplypacks.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  icons/mob/belt.dmi
  icons/obj/clothing/belts.dmi
Labels: Balance/Rebalance, Feature, Requires Testing, Test Merge Candidate

#2956 Small rework on bullet burst
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Fix

#2963 Adds a worm to LV624
  _maps/map_files/LV624/LV624.dmm
  code/game/objects/items/reagent_containers/food/snacks.dm
  icons/obj/items/items.dmi
Labels: Feature

#2950 add more unit tests
  code/modules/mob/living/carbon/xenomorph/castes/ravenger/ravenger.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/spawn_xenos.dm
Labels: Code Improvement, GitHub

#2952 Crash xeno numbers patch
  code/datums/gamemodes/crash.dm
Labels: Balance/Rebalance, Requires Testing

#2955 Runtime fixes.
  code/__DEFINES/misc.dm
  code/datums/actions/xeno_action.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/embedding.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/bots/medbot.dm
  code/game/objects/machinery/smartgun_mount.dm
  code/modules/client/client_procs.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: Fix

#2941 Xeno bull
  code/__DEFINES/components.dm
  code/__DEFINES/is_helpers.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/datums/supplyexports.dm
  code/game/sound.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  icons/Xeno/wound_overlays.dmi
  icons/mob/actions.dmi
  sound/voice/human_female_gored_1.ogg
  sound/voice/human_female_gored_2.ogg
  sound/voice/human_male_gored_1.ogg
  sound/voice/human_male_gored_2.ogg
  tgmc.dme
Labels: Balance/Rebalance

#2960 Nerfs the Queen's screech ability
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Balance/Rebalance

#2940 Armor resprite 2: Electric Boogaloo
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Sprites

#2971 Removes two variables and substitutes them with the cooldown list
  code/__DEFINES/mobs.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/taste.dm
Labels: Code Improvement

#2953 Marine ball
  _maps/_basemap.dm
  _maps/map_files/Marine_ball/Marine_ball.dmm
Labels: Map Edit

#2893 Wo refitting
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  code/game/turfs/closed.dm
  icons/turf/dropship3.dmi
Labels: Feature, Map Edit, Sprites

#2986 Wall armor: resistant walls
  code/game/turfs/turf.dm
  code/game/turfs/walls/wall_types.dm
  code/game/turfs/walls/walls.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Balance/Rebalance

#2985 Makes more examines use atom/examine
  code/game/objects/items/motion_detector.dm
  code/game/objects/items/stacks/cable_coil.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/toys/toy_weapons.dm
  code/game/objects/structures/stool_bed_chair_nest/janicart.dm
  code/game/objects/structures/xeno.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/paperwork/paperbin.dm
  code/modules/power/cell.dm
Labels: Code Improvement

#2984 Rogue shots fixes
  code/_onclick/observer.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/sentries.dm
  code/game/objects/machinery/smartgun_mount.dm
  code/modules/admin/holder.dm
Labels: Code Improvement, Fix

#2981 Xeno ability destroy fix
  code/datums/actions/xeno_action.dm
Labels: Fix

#2980 Revolver runtime fix
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
Labels: Fix

#2970 Fixes init issues
  code/game/objects/items/cards_ids.dm
  code/modules/buildmode/buttons.dm
Labels: Fix

#2987 Undamageable atmospheric stuff
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/machinery/components/binary_devices/pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/valve.dm
  code/modules/atmospherics/machinery/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/machinery/components/trinary_devices/filter.dm
  code/modules/atmospherics/machinery/components/trinary_devices/mixer.dm
  code/modules/atmospherics/machinery/components/unary_devices/heat_exchanger.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/portables_connector.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
Labels: Balance/Rebalance, Fix

#2988 Fixes another hallucination runtime
  code/modules/flufftext/Hallucination.dm
Labels: Fix

#2989 Removes the Melee malus on revolver stock
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Balance/Rebalance

#2998 VARIANCE BEGONE
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/obj_defense.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/codex/entries/mobs_codex.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravenger/ravenger.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/friendly/farm_animals.dm
  code/modules/mob/living/simple_animal/friendly/lizard.dm
  code/modules/mob/living/simple_animal/friendly/parrot.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/bear.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/constructs.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/shade.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/vehicles/multitile/cm_armored.dm
Labels: Balance/Rebalance

#2923 Improved Orders
  code/game/objects/machinery/overwatch.dm
Labels: Needs Review

#3011 Poddoor, airlock, detpack and c4 bugfixes
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/radio/detpack.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/poddoor.dm
Labels: Fix

#3012 Fixes not being able to pick up lighters.
  code/game/objects/items/tools/flame_tools.dm
Labels: Fix

#2990 Crash xeno evolution
  code/__DEFINES/components.dm
  code/datums/gamemodes/crash.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Balance/Rebalance

#2999 Deletion and bad client runtimes fixes
  code/datums/browser.dm
  code/game/objects/items/radio/headset.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/recycling/disposal.dm
Labels: Fix

#2569 Ports radial menus with the power of the copypasting.
  code/_onclick/hud/radial.dm
  code/_onclick/hud/radial_persistent.dm
  icons/mob/radial.dmi
  tgmc.dme
Labels: Sprites

#3026 Fixes a crate runtime
  code/game/objects/structures/crates_lockers/largecrate.dm
Labels: Fix
