Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2019-06, with the labels that each got.

#1700 Cleans up preference code
  code/__DEFINES/jobs.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/preferences.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/_logging.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/bitfields.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/stonedmc/subsystem/job.dm
  code/game/jobs/job/clf.dm
  code/game/jobs/job/deathsquad.dm
  code/game/jobs/job/freelancers.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/marines.dm
  code/game/jobs/job/mercenaries.dm
  code/game/jobs/job/other.dm
  code/game/jobs/job/pmc.dm
  code/game/jobs/job/shipside.dm
  code/game/jobs/job/sonsofmars.dm
  code/game/jobs/job/survivor.dm
  code/game/jobs/job/upp.dm
  code/game/jobs/job/upp_commando.dm
  code/game/machinery/cryopod.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/living/living.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Code Improvement, Config Update, QoL

#1726 Start now will always work
  code/modules/admin/server_verbs.dm
Labels: Administration

#1626 Add new defender forward charge
  code/__DEFINES/mobs.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
Labels: Balance/Rebalance, Feature, Requires Testing

#1690 Build mode disables ghost click to teleport
  code/_onclick/observer.dm
Labels: QoL

#1688 Fixes monkey speech issues
  code/modules/mob/living/carbon/monkey/monkey.dm
Labels: Fix

#1695 Further Silicon and AI code cleanup
  .github/CODEOWNERS
  code/__HELPERS/announce.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/click.dm
  code/controllers/stonedmc/subsystem/evacuation.dm
  code/datums/emergency_calls/clf.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/freelancers.dm
  code/datums/emergency_calls/imperium.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/emergency_calls/upp.dm
  code/datums/emergency_calls/upp_commando.dm
  code/datums/mind.dm
  code/defines/procs/announce.dm
  code/defines/procs/hud.dm
  code/game/gamemodes/distress.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/tracking.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/self_destruct.dm
  code/game/machinery/status_display.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  code/modules/mob/living/silicon/say.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/power/power.dm
  code/modules/security_levels/keycard_authentication.dm
  code/modules/security_levels/security_levels.dm
  code/modules/shuttles/marine_ferry.dm
  code/modules/shuttles/shuttle_console.dm
  sound/AI/aireport.ogg
  sound/AI/aliens.ogg
  sound/AI/intercept.ogg
  sound/AI/ionstorm.ogg
  sound/AI/outbreak5.ogg
  sound/AI/outbreak7.ogg
  sound/AI/radiation.ogg
  sound/AI/shuttlecalled.ogg
  sound/AI/shuttlerecalled.ogg
  sound/AI/welcome.ogg
  tgmc.dme
Labels: Code Improvement, GitHub, Sound

#1655 Cleans up client procs and defines, ports some /tg/ goods
  code/__DEFINES/logging.dm
  code/_globalvars/lists/client.dm
  code/_onclick/click.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/stonedmc/subsystem/server_maint.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/verbs/ooc.dm
  code/game/world.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement.dm
  tgmc.dme
Labels: Code Improvement, Config Update

#1669 Cleans up unused or shitty mob defines
  code/_onclick/ventcrawl.dm
  code/datums/outfit.dm
  code/game/area/areas.dm
  code/game/objects/items/megaphone.dm
  code/game/turfs/turf.dm
  code/modules/admin/fun_verbs.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life/life_helpers.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/mob/living/simple_animal/friendly/mouse.dm
  code/modules/mob/living/simple_animal/friendly/spiderbot.dm
  code/modules/mob/living/simple_animal/parrot.dm
  code/modules/mob/living/simple_animal/shade.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/living/simple_animal/worm.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
Labels: Code Improvement

#1702 Ports supply pods from /tg/
  code/__HELPERS/icons.dm
  code/_onclick/drag_drop.dm
  code/datums/supplypacks.dm
  code/game/area/Space_Station_13_areas.dm
  code/game/area/centcom.dm
  code/game/objects/effects/misc.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/game/objects/structures/supplypod.dm
  code/modules/admin/holder.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/podlauncher.dm
  code/modules/client/client_defines.dm
  code/modules/mob/mob.dm
  code/modules/nano/interaction/admin.dm
  code/modules/nano/interaction/default.dm
  html/create_object.html
  icons/effects/supplypod_down_target.dmi
  icons/effects/supplypod_target.dmi
  icons/mob/actions.dmi
  icons/obj/supplypods.dmi
  nano/templates/podlauncher.tmpl
  sound/weapons/mortar_long_whistle.ogg
  sound/weapons/mortar_whistle.ogg
  tgmc.dme
Labels: Administration, Sound, Sprites

#1727 Adds a topic for joining ERT
  code/datums/emergency_calls/emergency_call.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Merge Conflict

#1696 Sleeper window fix
  code/game/machinery/Sleeper.dm
Labels: Tweak

#1736 [s]Stack href exploit fix
  code/game/objects/items/stacks/stack.dm
Labels: In Game Exploit, Security Exploit

#1670 Adds spec scaling
  code/controllers/configuration/entries/game_options.dm
  code/game/gamemodes/distress.dm
Labels: Balance/Rebalance, Config Update

#1731 Improves launch pod error handling
  code/modules/admin/verbs/podlauncher.dm
Labels: Administration

#1734 Sleeper Condense
  code/game/machinery/Sleeper.dm
Labels: Tweak

#1730 A few more silicon fixes and camera interaction changes
  code/_onclick/click.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/mind.dm
  code/game/machinery/autolathe_datums.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/camera/camera_assembly.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/turfs/walls/walls.dm
  code/game/verbs/suicide.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
  code/modules/mob/living/silicon/ai/examine.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/ai/say.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/nano/interaction/default.dm
  code/modules/power/apc.dm
  icons/obj/machines/monitors.dmi
  tgmc.dme
Labels: Sprites, Tweak

#1693 Changes keybinds to use signals
  code/__DEFINES/components.dm
  code/_onclick/hud/human.dm
  code/datums/action.dm
  code/datums/keybinding/human.dm
  code/datums/keybinding/keybinding.dm
  code/datums/keybinding/xeno.dm
  code/game/atoms_movable.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Fix

#1740 Fixes Alt walking and Ctrl facing
  code/datums/keybinding/mob.dm
  code/modules/client/preferences.dm
  code/modules/keybindings/bindings_client.dm
Labels: Fix

#1751 AI playability tweaks
  code/__HELPERS/announce.dm
  code/_onclick/ai.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/computer/dropship_weapons.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/machinery.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/ai/multicam.dm
  code/modules/mob/living/silicon/ai/say.dm
  code/modules/power/apc.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/vehicles/vehicle.dm
  sound/machines/boltsdown.ogg
  sound/machines/boltsup.ogg
Labels: Sound, Tweak

#1737 Gets rid of the last legacy proc definitions
  code/__HELPERS/astar.dm
  code/controllers/stonedmc/subsystem/pathfinder.dm
  code/datums/datacore.dm
  code/defines/procs/AStar.dm
  code/defines/procs/records.dm
  code/defines/procs/sd_Alert.dm
  code/game/skincmd.dm
  interface/stylesheet.dm
  tgmc.dme
Labels: Code Improvement

#1744 Fixes a camera init runtime
  code/game/machinery/camera/camera.dm
Labels: Fix

#1746 Fixes being unable to C4 tunnels
  code/game/objects/items/explosives/plastique.dm
Labels: Fix

#1749 Fixes M56D do_after runtime
  code/modules/cm_marines/smartgun_mount.dm
Labels: Fix

#1752 Observers now show their name on examine.
  code/modules/mob/dead/observer/observer.dm
Labels: Trivial, Tweak

#1738 Slight area code cleanup.
  code/__DEFINES/layers.dm
  code/game/area/HauntedHouse.dm
  code/game/area/Prison_Station_FOP.dm
  code/game/area/Sulaco.dm
  code/game/area/Z_Holder.dm
  code/game/area/almayer.dm
  code/game/area/area.dm
  code/game/area/general.dm
  code/game/area/misc.dm
  code/game/area/prison.dm
  code/game/machinery/recharger.dm
  code/modules/client/client_defines.dm
  code/modules/power/gravitygenerator.dm
  tgmc.dme
Labels: Code Improvement

#1753 Fixes brain emote runtime.
  code/modules/mob/living/brain/emote.dm
Labels: Fix, Trivial

#1735 Create a new locator hud for SL -> FC
  code/controllers/stonedmc/subsystem/direction.dm
  code/game/jobs/job/shipside.dm
  code/game/jobs/squads.dm
  code/game/objects/items/radio/headset.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Feature

#1755 Fix small spelling mistake
  code/game/jobs/job/shipside.dm
Labels: Grammar and Formatting

#1754 Fix up keybindings
  code/datums/keybinding/client.dm
  code/datums/keybinding/human.dm
  code/datums/keybinding/xeno.dm
Labels: Fix

#1760 Fixing zone selection UI icon issues.
  code/_onclick/hud/screen_objects.dm
Labels: Fix

#1763 Removes unused config entry values.
  config/config.txt
Labels: Config Update, Removal

#1762 Slight machinery code cleanup
  code/controllers/stonedmc/subsystem/evacuation.dm
  code/controllers/stonedmc/subsystem/machines.dm
  code/datums/wires/airlock.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/bots/bots.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/floorbot.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/computer/arcade.dm
  code/game/machinery/deployable.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/machinery/machinery.dm
  code/game/machinery/telecomms/computers/logbrowser.dm
  code/game/machinery/vending/vending.dm
  code/game/objects/items/circuitboards/computer.dm
  code/game/objects/items/debugger.dm
  code/game/objects/items/lightreplacer.dm
  code/game/objects/items/megaphone.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/taperecorder.dm
  code/game/objects/items/whistle.dm
  code/modules/atmospherics/machinery/components/unary_devices/unary_devices.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/Marine_Research/Marine_Research_Console.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/detectivework/scanning_console.dm
  code/modules/economy/ATM.dm
  code/modules/hydroponics/seed_machines.dm
  code/modules/power/apc.dm
  code/modules/power/port_gen.dm
  code/modules/power/smes.dm
  code/modules/power/smes_construction.dm
  code/modules/power/terminal.dm
  code/modules/research/rdconsole.dm
  code/modules/research/server.dm
  code/modules/vehicles/vehicle.dm
  goon/code/obj/machinery/bot/chefbot.dm
Labels: Code Improvement

#1761 CMO now has a command headset
  code/game/jobs/job/shipside.dm
  code/game/objects/items/radio/encryptionkey.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Labels: Balance/Rebalance, Removal, Tweak

#1765 Fixes more vision related issues.
  code/__DEFINES/__game.dm
  code/game/objects/items/scanners.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/glasses/meson.dm
  code/modules/clothing/glasses/night.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/mob/living/brain/brain.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
Labels: Fix

#1764 Slight item code cleanup
  code/__DEFINES/components.dm
  code/__HELPERS/unsorted.dm
  code/_onclick/human.dm
  code/game/objects/items.dm
  code/game/objects/items/ashtray.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/flashlight.dm
  code/game/objects/items/modkit.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/items/weapons/energy.dm
  code/game/turfs/walls/walls.dm
  code/modules/assembly/igniter.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/hydroponics/vines.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_bundle.dm
  icons/obj/clothing/species/skrell/hats.dmi
  icons/obj/clothing/species/skrell/suits.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/unathi/hats.dmi
  icons/obj/clothing/species/unathi/suits.dmi
  tgmc.dme
Labels: Code Improvement, Sprites

#1767 Refactor gamemode code
  code/_globalvars/lists/mobs.dm
  code/controllers/stonedmc/subsystem/ticker.dm
  code/controllers/stonedmc/subsystem/timer.dm
  code/game/gamemodes/distress.dm
  code/game/gamemodes/extended.dm
  code/game/gamemodes/game_mode.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
Labels: Refactor

#1775 Removes another unused file.
  code/modules/flufftext/TextFilters.dm
  tgmc.dme
Labels: Removal

#1773 Makes dropship-placeable structures destructible by xenos
  code/modules/cm_marines/dropship_ammo.dm
  code/modules/cm_marines/dropship_equipment.dm
  code/modules/vehicles/powerloader.dm
Labels: Fix

#1772 Fixes attachment visual issues
  code/datums/action.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Fix

#1785 Fixes a tiny typo that would break jobs.
  code/game/gamemodes/game_mode.dm
Labels: Fix, Priority: High

#1768 A greater mob define cleanup.
  code/_onclick/click.dm
  code/_onclick/hud/plane_master.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/computer/HolodeckControl.dm
  code/game/machinery/computer/camera_console.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/flasher.dm
  code/game/objects/effects/effect_system/explosions.dm
  code/game/objects/explosion.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/radio/electropack.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/tools/surgery_tools.dm
  code/game/objects/items/toys/toy_weapons.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/sound.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/legacy.dm
  code/modules/cm_marines/NonLethalRestraints.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/mob_verbs.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
  code/modules/recycling/disposal.dm
  code/modules/shuttles/shuttle.dm
  code/modules/vehicles/multitile/tank.dm
  tgmc.dme
Labels: Code Improvement

#1788 Fixes a fingerprint runtime.
  code/game/objects/items.dm
Labels: Fix, Trivial

#1792 Fixes more bad do_afters
  code/game/objects/structures/barricade.dm
Labels: Fix

#1786 Fixes camera orientation
  code/game/machinery/camera/camera.dm
  icons/obj/machines/monitors.dmi
Labels: Fix, Sprites, Trivial

#1793 Fixes monkey mask overlay issues
  code/modules/mob/living/carbon/monkey/update_icons.dm
Labels: Fix

#1795 Small fix for smartgun inhand icons
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
Labels: Fix, Sprites

#1790 Fixes latejoining
  code/game/gamemodes/distress.dm
  code/game/gamemodes/game_mode.dm
  code/modules/mob/new_player/new_player.dm
Labels: Fix

#1791 Fixes being unable to interact with camera computers
  code/game/machinery/computer/camera_console.dm
  code/modules/mob/mob_defines.dm
Labels: Fix

#1796 Following the AI will now follow the eye as an observer
  code/modules/mob/dead/observer/say.dm
Labels: Fix

#1797 Fixes AI death state
  code/modules/mob/living/silicon/ai/death.dm
Labels: Fix

#1798 Fixes ghost forms not saving properly
  code/__HELPERS/sanitize_values.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix

#1770 Adds imaginary friends for the mentors.
  code/datums/action.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/mob/camera/imaginary_friend.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_defines.dm
  icons/mob/actions.dmi
  tgmc.dme
Labels: Administration, Sprites

#1800 Fix new player references
  code/game/gamemodes/game_mode.dm
Labels: Fix, Priority: High

#1799 Makes admins able to fully rename any mobs via VV, not just /living
  code/modules/admin/verbs/datumvars.dm
Labels: Administration

#1694 m39 on back
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  icons/mob/back.dmi
Labels: Balance/Rebalance, Sprites, Test Merge Candidate

#1809 Another missed do_after
  code/game/objects/structures/girders.dm
Labels: Fix

#1811 Ensure we save keybindings after all changes
  code/modules/client/preferences.dm
Labels: Fix

#1813 Set the ghost notification for detpack the user
  code/game/objects/items/radio/detpack.dm
Labels: Tweak

#1821 Fixes autodoc's radio ejecting itself.
  code/game/machinery/autodoc.dm
Labels: Fix

#1826 Cleanup wording for bioscan in admin log
  code/game/gamemodes/distress.dm
Labels: Trivial

#1782 Ports /tg/ telekinesis
  code/__DEFINES/combat.dm
  code/__DEFINES/living_flags.dm
  code/_onclick/telekinesis.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/effect.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/living_defines.dm
  icons/effects/effects.dmi
  sound/weapons/tap.ogg
  tgmc.dme
Labels: Requires Testing, Sound, Sprites

#1838 Fuel sprite lack of name fixed.
  icons/effects/effects.dmi
Labels: Sprites

#1812 Fixes airlock welding
  code/game/machinery/doors/airlock.dm
Labels: Fix

#1814 Makes AI report verbs more modular.
  code/modules/admin/fun_verbs.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
Labels: Tweak

#1808 Combines the rank/equipment/squad admin verbs, slight PP tweaks
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
Labels: Administration

#1807 Adds a varset_callback to reduce the proc amount
  code/__DEFINES/callbacks.dm
  code/datums/callback.dm
  code/game/machinery/fax.dm
  code/modules/codex/codex_client.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Code Improvement

#1801 Adds round IDs to the note panel.
  code/modules/admin/panels/note_panel.dm
Labels: Administration

#1805 Adds a slight delay to watchlists for clarity
  code/modules/admin/panels/note_panel.dm
Labels: Administration

#1803 Makes the AI unable to interact with dropship doors.
  code/game/machinery/doors/airlock_types.dm
Labels: Fix

#1830 Fixes frustrating repairs of generators.
  code/game/machinery/groundmap_geothermal.dm
Labels: Fix

#1818 Fixes a to_chat runtime.
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#1820 Fixes a sleeper runtime
  code/game/machinery/Sleeper.dm
Labels: Fix

#1816 Fixes blood overlay for boots, adds different icon for pyro boots
  code/modules/clothing/shoes/marine_shoes.dm
  icons/effects/blood.dmi
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Fix, Sprites

#1831 Fixes launching humans into nullscape on nesting if the nest is deleted
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
Labels: Fix

#1832 Fixes a race condition xeno action runtime
  code/datums/action.dm
Labels: Fix

#1804 Cleans up some dirty perspective modifications
  code/_onclick/hud/alien.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/monkey.dm
  code/_onclick/ventcrawl.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/computer/camera_console.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/structures/ladders.dm
  code/modules/admin/fun_verbs.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_verbs.dm
Labels: Code Improvement, Do Not Merge

#1817 Gives B18 tacticool gloves
  code/modules/clothing/gloves/marine_gloves.dm
  icons/obj/clothing/gloves.dmi
Labels: Sprites

#1789 Fixes layers of items related to actions
  code/datums/action.dm
Labels: Fix

#1834 Xenos do not keep the skills of previous lives anymore.
  code/datums/mind.dm
Labels: Fix

#1837 Fixes AI interaction with certain machines
  code/game/machinery/computer/communications.dm
  code/modules/cm_marines/overwatch.dm
Labels: Fix

#1843 Fixes explosion passthrough.
  code/__HELPERS/unsorted.dm
  code/game/atoms.dm
  code/game/objects/explosion.dm
  code/game/objects/structures/supplypod.dm
Labels: Fix

#1848 Hopefully fixes a lot of binding_client errors.
  code/modules/client/preferences.dm
Labels: Fix, Priority: High

#1841 Pain hud
  code/__DEFINES/atom_hud.dm
  code/datums/atom_hud.dm
  code/game/data_huds.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/living_health_procs.dm
Labels: Tweak

#1758 Adds more explosion sounds
  code/game/objects/explosion.dm
  code/game/sound.dm
  code/modules/flufftext/Hallucination.dm
  sound/effects/explosion1.ogg
  sound/effects/explosion2.ogg
  sound/effects/explosion3.ogg
  sound/effects/explosion4.ogg
  sound/effects/explosion5.ogg
  sound/effects/explosion6.ogg
  sound/effects/explosion_small1.ogg
  sound/effects/explosion_small2.ogg
  sound/effects/explosion_small3.ogg
  sound/effects/explosionsmallfar.ogg
Labels: Requires Testing, Sound

#1757 Adds new firing sounds for some weapons
  code/game/sound.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  sound/weapons/gun_auto9.ogg
  sound/weapons/gun_beretta.ogg
  sound/weapons/gun_colt.ogg
  sound/weapons/gun_deagle.ogg
  sound/weapons/gun_flamethrower1.ogg
  sound/weapons/gun_flamethrower_empty.ogg
  sound/weapons/gun_flamethrower_off.ogg
  sound/weapons/gun_flamethrower_on.ogg
  sound/weapons/gun_hmg.ogg
  sound/weapons/gun_hp.ogg
  sound/weapons/gun_launcher.ogg
  sound/weapons/gun_launcher_empty.ogg
  sound/weapons/gun_launcher_reload.ogg
  sound/weapons/gun_m16.ogg
  sound/weapons/gun_m41a_empty.ogg
  sound/weapons/gun_mosin.ogg
  sound/weapons/gun_mp5.ogg
  sound/weapons/gun_mp7.ogg
  sound/weapons/gun_ny.ogg
  sound/weapons/gun_p90.ogg
  sound/weapons/gun_pistol.ogg
  sound/weapons/gun_pistol_service.ogg
  sound/weapons/gun_ppsh.ogg
  sound/weapons/gun_revolver.ogg
  sound/weapons/gun_revolver_small.ogg
  sound/weapons/gun_shotgun_cmb.ogg
  sound/weapons/gun_shotgun_empty.ogg
  sound/weapons/gun_shotgun_light.ogg
  sound/weapons/gun_shotgun_open.ogg
  sound/weapons/gun_skorpion.ogg
  sound/weapons/gun_svd.ogg
  sound/weapons/gun_type71.ogg
  sound/weapons/working_the_bolt.ogg
Labels: Requires Testing, Sound

#1538 Mends a not-so-little race condition smoke runtime on rockets & co.
  code/modules/mob/living/damage_procs.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Fix

#1839 Fixes admin ghosts not being properly deleted allowing for duplication
  code/modules/mob/dead/observer/logout.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#1853 Fixes xeno acid being overriden by weaker one
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#1854 Fixes boiler acid type being inversed
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Fix

#1856 Fixes hunter stealth
  code/_onclick/ventcrawl.dm
Labels: Fix

#1859 My attempt at fixing the smoke runtime
  code/game/objects/effects/effect_system/smoke.dm
Labels: Fix

#1862 Fixes xeno acid not hitting mobs on direct hit
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Fix

#1861 You can no longer rest in vents.
  code/modules/mob/living/living_verbs.dm
Labels: Fix

#1857 Fixes being able to cheese with tank weapon switching.
  code/modules/vehicles/multitile/hardpoints.dm
Labels: Fix

#1858 Fixes prae acid being able to spray through walls
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#1863 Fixes an issue with storage insertion
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix

#1855 Allows boiler left click to bombard again.
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Fix, QoL

#1885 Fix runtime when swapping a squad for a SL
  code/game/jobs/squads.dm
Labels: Fix

#1865 Adds species into the edit appearance menu
  code/modules/admin/fun_verbs.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Administration

#1864 Makes the admin equipment menu take one less click
  code/modules/admin/topic.dm
Labels: Administration, QoL

#1784 Sulaco refit
  _maps/WIP/Sulaco_bottom.dmm
  _maps/WIP/Sulaco_top.dmm
  _maps/_basemap.dm
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/area/Sulaco.dm
Labels: Map Edit

#1872 Cameras now start anchored
  code/game/machinery/camera/camera.dm
Labels: Fix

#1873 Fixes a supply computer deconstruction runtime
  code/modules/shuttle/supply.dm
Labels: Fix

#1874 Fixes xeno tunnel destroy runtime.
  code/modules/cm_aliens/XenoStructures.dm
Labels: Fix

#1875 Fixes a timer not being stoppable but being qdeleted
  code/game/objects/items/radio/detpack.dm
Labels: Fix

#1878 Fixes a garbage collection runtime
  code/modules/reagents/Chemistry-Holder.dm
Labels: Fix

#1880 Fixes xeno mind name not getting updated on evolution
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#1881 Fixes lasgun visual issue
  code/modules/projectiles/updated_projectiles/guns/energy.dm
Labels: Fix

#1882 Fixes spec rocked fire runtime
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Fix

#1883 Makes zipcuff behavior less quirky
  code/game/objects/items/handcuffs.dm
Labels: Tweak

#1884 Makes binary :n so it won't conflict with bravo
  code/__DEFINES/say.dm
Labels: Fix

#1887 Fixes a few more deltimer issues
  code/datums/emergency_calls/emergency_call.dm
Labels: Fix

#1889 Fixes not being able to screw back autolathe
  code/game/machinery/autolathe.dm
Labels: Fix

#1890 Fixes not being able to manipulate with shocked doors
  code/game/machinery/doors/airlock.dm
Labels: Fix

#1891 Fixes another positional argument issue
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix

#1893 Fixes the autodoc issue
  code/game/machinery/autodoc.dm
Labels: Fix

#1867 Siege tweaks.
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
Labels: Balance/Rebalance

#1895 Fixes proximity garbage collection issues
  code/game/atoms_movable.dm
Labels: Fix

#1897 Fixes a few more pespective issues
  code/game/machinery/kitchen/microwave.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_movement.dm
  tgmc.dme
Labels: Fix

#1896 shuttle engine sprites port.
  icons/turf/shuttle.dmi
Labels: Sprites

#1810 Fixes an admin runtime.
  code/modules/admin/admin_verbs.dm
Labels: Fix

#1815 Makes the pod launcher logging better.
  code/modules/admin/verbs/podlauncher.dm
Labels: Administration

#1825 Standarizing pills init.
  code/__HELPERS/global_lists.dm
  code/game/objects/items/reagent_containers/pill.dm
Labels: Fix

#1869 Slight unused or bad object code cleanup
  code/__DEFINES/objects.dm
  code/game/machinery/bots/mulebot.dm
  code/game/objects/items/debugger.dm
  code/game/objects/items/scanners.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/recycling/disposal.dm
Labels: Code Improvement

#1886 Purges the rest of the targetting system
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/targeting.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  tgmc.dme
Labels: Code Improvement

#1888 Fixes a transit turf issue
  code/game/turfs/space/transit.dm
Labels: Fix

#1903 Observers now get bold messages from people speaking in view
  code/modules/mob/dead/observer/say.dm
Labels: QoL

#1532 Shuttles Episode IV: A New Hope NOT WIP, READY FOR TESTING
  _maps/WIP/Z.01.Desert-Dam.dmm
  _maps/_basemap.dm
  _maps/low_orbit.json
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Low_Orbit/Low_Orbit.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/shuttles/alamo.dmm
  code/__DEFINES/__game.dm
  code/__DEFINES/maps.dm
  code/__HELPERS/level_traits.dm
  code/controllers/shuttle_controller.dm
  code/controllers/stonedmc/subsystem/evacuation.dm
  code/controllers/stonedmc/subsystem/mapping.dm
  code/controllers/stonedmc/subsystem/shuttle.dm
  code/controllers/stonedmc/subsystem/shuttleold.dm
  code/game/gamemodes/distress.dm
  code/game/gamemodes/game_mode.dm
  code/game/machinery/computer/crew.dm
  code/game/machinery/computer/dropship_weapons.dm
  code/game/machinery/door_control.dm
  code/game/machinery/doors/airlock_types.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/objects/items/gift_wrappaper.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/turfs/space.dm
  code/game/world.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/cm_marines/dropship_equipment.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/cm_marines/shuttle_backend.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/mob.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/docking.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/shuttle/shuttle.dm
  code/modules/shuttles/marine_ferry.dm
  code/modules/shuttles/shuttle.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/shuttles/shuttle_ferry.dm
  icons/obj/structures/dropship_structures.dmi
  tgmc.dme
Labels: Map Edit, Refactor, Removal, Sprites

#1565 Adds survivor radios, headsets, intercomms
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/radio/intercom.dm
  code/game/objects/items/radio/radio.dm
Labels: Map Edit, Tweak

#1919 Fixes some belts onmob icons
  code/game/objects/items/storage/belt.dm
  icons/mob/belt.dmi
Labels: Fix, Sprites, Tweak

#1923 Fixes mine box storage space, correts numbers on flare pack icon
  code/game/objects/items/storage/boxes.dm
  icons/obj/items/storage/storage.dmi
Labels: Fix, Sprites

#1912 Fixes being able to escape through prison shutters.
  code/game/objects/structures/window.dm
Labels: Fix

#1913 Fixes tank magazine reloading weirdness.
  code/modules/vehicles/multitile/cm_armored.dm
Labels: Fix

#1911 Fixes burstfire HUD icon
  code/_onclick/hud/screen_objects.dm
Labels: Fix

#1672 Sorts cm_aliens, cm_marines, removes the last almayer reference
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/machinery/computer/marines_consoles.dm
  code/game/machinery/dropship_part_fabricator.dm
  code/game/machinery/overwatch.dm
  code/game/machinery/sentries.dm
  code/game/machinery/smartgun_mount.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/books/book.dm
  code/game/objects/items/maps.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/items/tools/surgery_tools.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/ovipositor.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/mortar.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/prop.dm
  code/game/objects/structures/xeno.dm
  code/modules/cm_marines/Marine_Research/BioPrinter.dm
  code/modules/cm_marines/Marine_Research/Marine_Designs.dm
  code/modules/cm_marines/Marine_Research/Marine_Research.dm
  code/modules/cm_marines/Marine_Research/Marine_Research_Console.dm
  code/modules/cm_marines/Marine_Research/Marine_Research_Items.dm
  code/modules/cm_marines/Marine_Research/Organic_Analyzer.dm
  code/modules/cm_marines/NonLethalRestraints.dm
  code/modules/cm_marines/codebook.dm
  tgmc.dme
Labels: Code Improvement, Map Edit, Removal

#1836 Optimizes pheromone's emitting
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Refactor

#1902 Fixes explosions deleting worn items
  code/__DEFINES/components.dm
  code/game/atoms.dm
  code/game/objects/explosion.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/vehicles/multitile/cm_armored.dm
Labels: Fix

#1918 Fixes Theseus map issues
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/machinery/doors/airlock_types.dm
  code/game/machinery/doors/brigdoors.dm
Labels: Fix, Map Edit

#1866 Ports cinematics from /tg/
  code/__DEFINES/__game.dm
  code/__DEFINES/layers.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/stonedmc/subsystem/evacuation.dm
  code/datums/cinematic.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  icons/effects/station_explosion.dmi
  tgmc.dme
Labels: Code Improvement, Sprites

#1922 Fixes ice colony visual issues
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  code/game/objects/effects/landmarks/corpsespawner.dm
Labels: Fix, Map Edit

#1900 Xeno devour refactor
  code/__DEFINES/components.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/mob_grab.dm
Labels: Fix

#1901 Small hud tweaks
  code/__DEFINES/atom_hud.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Tweak

#1924 Fixes LV visual map issues
  _maps/map_files/LV624/LV624.dmm
Labels: Fix, Map Edit

#1921 Fixes Prison Station visual issues
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Fix, Map Edit

#1928 Admin level tweaks
  _maps/map_files/generic/Admin_Level.dmm
  code/_globalvars/lists/mapping.dm
  code/game/area/centcom.dm
  code/game/objects/effects/landmarks/landmarks.dm
  icons/turf/areas.dmi
Labels: Map Edit, Sprites

#1934 Changes the PO slots to 2
  code/game/jobs/job/shipside.dm
Labels: Fix

#1935 Fixes another attackby runtime
  code/game/turfs/floor.dm
  code/game/turfs/snow.dm
Labels: Fix

#1936 Fixes another timer issue
  code/game/machinery/door_control.dm
Labels: Fix

#1932 Removes the clown survivor.
  code/game/jobs/job/survivor.dm
Labels: Removal

#1929 Fixes a few view visual issues
  code/__HELPERS/game.dm
  code/datums/mind.dm
  code/game/gamemodes/huntergames.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/brain/brain_item.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/login.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/mob/mob_verbs.dm
Labels: Fix
