Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2019-02, with the labels that each got.

#443 changes the first-aid pouch to have a green cross
  icons/Marine/marine-pouches.dmi
Labels: Sprites

#462 Prevents event roles from showing up in the crew manifest
  code/datums/datacore.dm
Labels: Fix

#461 Fixes hub round time display.
  code/game/world.dm
  config/config.txt
Labels: Config Update, Fix

#463 Survivor tweaks.
  code/game/gamemodes/cm_initialize.dm
  code/game/jobs/job/other.dm
Labels: Balance/Rebalance, Fix

#418 Queen Death Timer Countdown Tweaks
  code/__DEFINES/mode.dm
  code/game/area/LV624.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/cm_process.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/mob.dm
Labels: Balance/Rebalance

#466 Corrects misspelling of 'the'
  code/game/jobs/job/shipside.dm
Labels: Grammar and Formatting

#459 Zoom fixes
  code/game/objects/items.dm
  code/modules/client/client procs.dm
  code/modules/mob/mob_verbs.dm
Labels: Fix

#465 Fixes changelog hash display.
  code/global.dm
  code/modules/client/client procs.dm
  code/modules/mob/mob.dm
Labels: Fix

#478 Deletes changerock
  code/game/objects/items/artifacts.dm
  icons/obj/items/misc.dmi
  tgmc.dme
Labels: Sprites

#448 Reworks emit pheromones into action buttons instead of drop down list
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Drone.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hivelord.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Praetorian.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  icons/mob/actions.dmi
Labels: Feature, Sprites

#447 Toggle rail attachment now only toggles the gun in the active hand.
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
Labels: Fix, QoL

#464 Possibly fixes xeno HUD issues.
  code/datums/mob_hud.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Fix

#468 Say should now show up properly.
  code/modules/mob/say.dm
Labels: Fix

#474 Fixing supply drops
  code/__HELPERS/lists.dm
  code/modules/cm_marines/overwatch.dm
Labels: Fix

#479 Fixes Vendor Background Colors
  nano/css/layout_basic.css
  nano/css/layout_default.css
Labels: Fix

#485 Removes a couple nazi references from the code
  code/game/machinery/computer/arcade.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/obj/clothing/suits.dmi
Labels: Grammar and Formatting, Removal, Sprites

#488 Fix for Lasgun Charger Not Being Available
  code/datums/supplypacks.dm
Labels: Fix

#499 You Now Decloak on Death
  code/game/objects/items/storage/backpack.dm
Labels: Fix

#510 God is good and changestone doesn't exist.
  maps/Z.01.BigRed_v2.dmm
  maps/Z.01.Ice_Colony_v2.dmm
Labels: Map Edit, Priority: High

#505 Fixes frenzy pheromone not working
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
Labels: Fix

#527 One liner about closets' layer
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#515 Everyone can now attach, survivor fixes.
  code/game/gamemodes/cm_initialize.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
Labels: Fix

#453 Fixes xeno inability at dropship barrel rolls
  code/game/machinery/machinery.dm
Labels: Fix, Test Merge Candidate

#467 [Experimental Testmerge Balance] Make's alien's disarm tackle damage no longer RNG
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Balance/Rebalance

#489 changes allowed armor storage items for marine armor
  code/modules/clothing/suits/marine_armor.dm
Labels: QoL

#506 new marine and xeno sounds
  code/game/sound.dm
  sound/voice/alien_growl4.ogg
  sound/voice/alien_roar10.ogg
  sound/voice/alien_roar11.ogg
  sound/voice/alien_roar12.ogg
  sound/voice/alien_roar7.ogg
  sound/voice/alien_roar8.ogg
  sound/voice/alien_roar9.ogg
  sound/voice/alien_roar_larva3.ogg
  sound/voice/alien_roar_larva4.ogg
  sound/voice/human_male_pain_4.ogg
  sound/voice/human_male_pain_5.ogg
  sound/voice/human_male_pain_6.ogg
  sound/voice/human_male_pain_7.ogg
  sound/voice/human_male_pain_8.ogg
  sound/voice/human_male_pain_joke1.ogg
  sound/voice/human_male_pain_joke2.ogg
  sound/voice/human_male_scream_5.ogg
  sound/voice/human_male_scream_6.ogg
  sound/voice/human_male_scream_joke1.ogg
  sound/voice/human_male_scream_joke2.ogg
  sound/voice/human_male_scream_joke3.ogg
  sound/voice/human_male_scream_joke4.ogg
Labels: Sound, Test Merge Candidate, Tweak

#543 Minor motion detector code improvements.
  code/game/objects/items/devices/motion_detector.dm
Labels: Fix

#544 Typing indicator cleanup.
  code/__DEFINES/__game.dm
  code/modules/mob/typing_indicator.dm
Labels: Fix

#542 Cleans up OB message.
  code/modules/cm_marines/overwatch.dm
Labels: Fix

#545 Briefing chairs can now only be deconstructed by welding.
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  maps/Z.03.TGS_Theseus.dmm
Labels: Tweak

#549 Medical machinery now properly checks if the occupant is present.
  code/game/machinery/Sleeper.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/cryo.dm
Labels: Fix

#547 Pyro spec in full gear can no longer get set on fire.
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Tweak

#548 Fixes neurogas going on cooldown prematurely.
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Fix

#367 Re-ports Xeno Sprites + General Cleanup
  icons/Xeno/1x1_Xenos.dmi
  icons/Xeno/2x2_Xenos.dmi
  icons/Xeno/Defiler.dmi
  icons/Xeno/Effects.dmi
  icons/Xeno/wound_overlays.dmi
Labels: Removal, Sprites

#551 Fixes TimSort (for real this time)
  code/__HELPERS/sorts/InsertSort.dm
  code/__HELPERS/sorts/__main.dm
Labels: Fix

#546 Added Automag Attachments
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
Labels: Balance/Rebalance

#556 is to is a
  code/game/verbs/who.dm
Labels: Grammar and Formatting

#559 Regurgitate ability now deals an one tick knock down
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
Labels: Balance/Rebalance

#553 Renames Marshall to Marshal
  code/datums/skills.dm
  code/game/area/BigRed.dm
  code/game/jobs/job/other.dm
  code/modules/clothing/under/marine_uniform.dm
  maps/Z.01.BigRed_v2.dmm
Labels: Grammar and Formatting

#425 [Ready]Boiler sprays & flames bug fixes.
  code/__HELPERS/unsorted.dm
  code/_onclick/adjacent.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/game/objects/structures/window.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Code Improvement, Fix, Needs Review

#495 New Sub-Spec: B18 Minigunner
  code/controllers/configuration/entries/combat_defines.dm
  code/datums/supplypacks.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/magazines/misc.dm
  code/modules/projectiles/updated_projectiles/magazines/specialist.dm
  config/config.txt
Labels: Config Update, Test Merge Candidate

#555 Fixes destructibility of certain important things.
  code/game/machinery/doors/airlock_types.dm
  code/game/machinery/doors/multi_tile.dm
  code/modules/cm_marines/dropship_equipment.dm
Labels: Fix

#518 Another Admin Tweaks PR
  code/__DEFINES/__game.dm
  code/__DEFINES/admin.dm
  code/__DEFINES/tgs.config.dm
  code/__HELPERS/_logging.dm
  code/__HELPERS/text.dm
  code/__HELPERS/time.dm
  code/_globalvars/configuration.dm
  code/_globalvars/lists/objects.dm
  code/_globalvars/logging.dm
  code/game/gamemodes/cm_process.dm
  code/game/gamemodes/gameticker.dm
  code/game/jobs/job/squads.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/fax.dm
  code/game/objects/explosion.dm
  code/game/objects/items/devices/transfer_valve.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/verbs/ooc.dm
  code/game/world.dm
  code/global.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/game_panel.dm
  code/modules/admin/panels/mode_panel.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/server_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/faxes.dm
  code/modules/events/event_dynamic.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_verbs.dm
  code/modules/mob/say.dm
  code/modules/power/cell.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  goon/browserassets/css/browserOutput.css
  tgmc.dme
Labels: Administration

#579 Mapping fixes
  code/ATMOSPHERICS/atmospherics.dm
  code/ATMOSPHERICS/pipes.dm
  code/_onclick/observer.dm
  code/game/area/areas.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/machinery/machinery.dm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/tables_racks.dm
  code/game/world.dm
  code/global.dm
  code/modules/awaymissions/bluespaceartillery.dm
  code/modules/awaymissions/exile.dm
  code/modules/awaymissions/gateway.dm
  code/modules/awaymissions/loot.dm
  code/modules/awaymissions/pamphlet.dm
  code/modules/awaymissions/trigger.dm
  code/modules/awaymissions/zlevel.dm
  code/modules/maps/dmm_suite.dm
  code/modules/maps/fromdmp.dm
  code/modules/maps/reader.dm
  code/modules/maps/swapmaps.dm
  code/modules/maps/writer.dm
  code/modules/vehicles/train.dm
  maps/WIP/Z.01.Desert-Dam.dmm
  maps/Z.01.Ice_Colony_v2.dmm
  maps/Z.01.Prison_Station_FOP.dmm
  maps/Z.03.TGS_Theseus.dmm
  tgmc.dme
Labels: Fix

#567 Removes unused and old IRC bot code.
  bot/CORE_DATA.py
  bot/C_eightball.py
  bot/C_heaortai.py
  bot/C_makequote.py
  bot/C_maths.py
  bot/C_rot13.py
  bot/C_rtd.py
  bot/C_sarcasticball.py
  bot/C_srtd.py
  bot/D_help.py
  bot/FMLformatter.py
  bot/Marakov/Marakov.Cache
  bot/Marakov_Chain.py
  bot/Namecheck.py
  bot/NanoTrasenBot.py
  bot/Shortname.py
  bot/Timeconverter.py
  bot/Weather.py
  bot/YTCv3.py
  bot/YTCv4.py
  bot/_____Readme.txt
  bot/gen_fml.py
  bot/htmltagremove.py
  bot/irchat.py
  bot/linereader.py
  bot/nudge.py
  bot/save_load.py
  bot/some_but_not_all_2.py
  bot/xkcdparser.py
Labels: Removal

#569 Ravager's second wind now goes onto cooldown properly.
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Fix

#575 Should fix holocards
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#576 Marshall to Marshal
  maps/WIP/Z.01.Desert-Dam.dmm
  maps/Z.01.BigRed_v2.dmm
Labels: Grammar and Formatting

#577 MAC-15 Suppressor Fix
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
Labels: Fix

#563 Gives the ship a Mast
  code/game/objects/structures/misc.dm
  icons/obj/structures/structures.dmi
  maps/Z.03.TGS_Theseus.dmm
Labels: Feature, Sprites

#578 Cleanup
  code/game/objects/items/cosmetics.dm
  code/game/objects/items/misc.dm
  icons/obj/items/items.dmi
  icons/obj/items/weapons.dmi
Labels: Sprites

#561 Defiler Gas Change
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Balance/Rebalance, Test Merge Candidate, Tweak

#590 Update Z.01.BigRed_v2.dmm
  maps/Z.01.BigRed_v2.dmm
Labels: Map Edit, Priority: High

#580 Removing duplicated definitions
  code/__DEFINES/logging.dm
  code/__DEFINES/misc.dm
  code/__HELPERS/unsorted.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Fix

#593 Fixing lumberjack dilemmas and synth whipping.
  code/game/objects/items/stacks/cable_coil.dm
  code/game/objects/structures/flora.dm
Labels: Fix

#528 E to equip, now with being able to set your preferred slots!
  code/__DEFINES/equipment.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/storage.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/clothing/under/ties.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/mob.dm
Labels: QoL

#599 Fixes instructions unclear for barrel crates.
  code/game/objects/structures/crates_lockers/largecrate.dm
Labels: Fix

#589 ups grey medical belt size
  code/game/objects/items/storage/belt.dm
Labels: Tweak

#601 Fixes crusher/defender jolly co-op.
  code/game/objects/structures/razorwire.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_status_procs.dm
Labels: Fix

#611 Fixes runtimes in crew monitor sorting procedures
  code/game/machinery/computer/crew.dm
Labels: Fix

#606 Dumb xeno vs chad shuttle door.
  code/game/machinery/doors/unpowered.dm
  code/modules/shuttles/shuttle.dm
  code/modules/shuttles/shuttle_ert.dm
  icons/turf/shuttle.dmi
  maps/Z.01.Ice_Colony_v2.dmm
  maps/Z.01.Prison_Station_FOP.dmm
Labels: Fix, Sprites

#570 Minor embryo code cleanup.
  code/datums/mob_hud.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
  icons/mob/hud.dmi
Labels: Code Improvement, Fix, Sprites

#565 Pyro spec now takes slight damage from walking over fire.
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Balance/Rebalance

#588 Makes a new coffee vending item
  code/game/machinery/vending/vending_types.dm
  code/game/objects/items/reagent_containers/food/drinks.dm
Labels: Tweak

#620 Supplypacks.dm cleanup and fix
  code/datums/supplypacks.dm
Labels: Fix, Priority: High

#621 Runtime fixes
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
Labels: Fix

#631 Fixes more bodybag/tarp related issues.
  code/game/objects/items/bodybag.dm
  code/modules/cm_marines/equipment/gear.dm
Labels: Fix

#623 Update Z.01.Desert-Dam.dmm
  maps/WIP/Z.01.Desert-Dam.dmm
Labels: Map Edit

#612 Set-transfer-amount automatically selects the active hand.
  code/game/objects/items/reagent_containers/food/cans.dm
  code/game/objects/items/reagent_containers/food/drinks.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/game/objects/items/reagent_containers/reagent_container.dm
  code/game/objects/items/reagent_containers/spray.dm
Labels: Fix

#619 Warrior Balance Tweak
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Test Merge Candidate, Tweak

#622 Major Prison Station change/fix
  code/game/area/Prison_Station_FOP.dm
  maps/Z.01.Prison_Station_FOP.dmm
Labels: Fix, Map Edit, Priority: High

#632 > beno transferring plasma to itself.
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Fix

#571 MOD88 pistol stock and holster combo
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  icons/Marine/marine-weapons.dmi
Labels: Feature, Sprites

#660 [s] testing something with MSO
  config/admin_ranks.txt
  config/admins.txt
Labels: Config Update

#587 Yet Another Admin Tweaks PR
  code/__HELPERS/text.dm
  code/_globalvars/bitfields.dm
  code/defines/procs/announce.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/fax.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/server_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/admin/verbs/faxes.dm
  code/modules/admin/verbs/player_notes.dm
  code/modules/admin/verbs/pray.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/mob/mob_verbs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/vehicles/hardpoints.dm
  goon/browserassets/css/browserOutput.css
  interface/interface.dm
Labels: Administration

#627 Ship Hull HP Reduced to Reasonable Amount
  code/game/turfs/walls/wall_types.dm
Labels: Balance/Rebalance, Test Merge Candidate, Tweak

#645 Fuel tank shenanigeans fix.
  code/game/objects/structures/reagent_dispensers.dm
Labels: Fix

#635 Adds a Discord button to the interface.
  interface/interface.dm
  interface/skin.dmf
Labels: Feature

#640 Aliens now get picked from the oldest
  code/__HELPERS/game.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
Labels: Tweak

#656 Softens up Warrior's teamkilling bully punch.
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Fix

#637 More starting ammo for sniper spec
  code/modules/cm_marines/equipment/weapons.dm
Labels: Balance/Rebalance, Test Merge Candidate

#638 Actually fixes the explosion screen.
  code/game/gamemodes/cm_self_destruct.dm
Labels: Fix

#562 Ongoing facehugger fixes.
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
Labels: Fix

#625 Adds LOOC
  code/controllers/configuration/entries/general.dm
  code/game/verbs/ooc.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/server_verbs.dm
  config/config.txt
  interface/skin.dmf
Labels: Config Update, Feature

#634 LV Cleanup and Improvment
  code/game/objects/structures/flora.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/walls/wall_types.dm
  icons/obj/flora/ground_map64.dmi
  icons/turf/floors.dmi
  maps/Z.01.LV624.dmm
Labels: Removal, Sprites, Tweak

#491 Adds a bolt action rifle
  code/game/gamemodes/cm_initialize.dm
  code/game/machinery/vending/marine_vending.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/magazines/shotguns.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  sound/weapons/working_the_bolt.ogg
Labels: Feature, Sound, Sprites

#661 Removes wy and aliens reference from cigs
  code/game/objects/items/storage/fancy.dm
  icons/obj/items/cigarettes.dmi
Labels: Removal, Sprites

#636 Hand Labeler rework
  code/game/objects/items/storage/storage.dm
  code/game/objects/items/tools/misc_tools.dm
Labels: Fix

#658 Prevents melee weaponary from applying stuns to already horizontal humans.
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix

#657 Distress members now get their zoom reset.
  code/datums/emergency_calls/clf.dm
  code/datums/emergency_calls/colonists.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/freelancers.dm
  code/datums/emergency_calls/pizza.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/emergency_calls/upp.dm
  code/datums/emergency_calls/upp_commando.dm
  code/datums/emergency_calls/xeno.dm
Labels: Fix

#663 Admin Fixes
  code/game/machinery/fax.dm
  code/game/objects/items/devices/radio/detpack.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/structures/reagent_dispensers.dm
Labels: Administration

#626 Cleaned generators and floodlights code
  code/game/machinery/fusion_engine.dm
  code/game/machinery/groundmap_geothermal.dm
  code/modules/power/smes.dm
  maps/Z.03.TGS_Theseus.dmm
Labels: Refactor, Requires Testing

#667 ZX-76 Assault Shotgun Supplypack Added
  code/datums/supplypacks.dm
Labels: Balance/Rebalance, Tweak

#596 Fixes the unilateral muhrin armor lamp overlay.
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Fix

#607 Observer, prefs, and new_player code cleanup
  code/__DEFINES/mob_hud.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/misc.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/mob_hud.dm
  code/game/atoms_movable.dm
  code/modules/admin/verbs/faxes.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/logout.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/new_player/login.dm
  code/modules/mob/new_player/logout.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/poll.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/mob/new_player/skill.dm
  code/modules/mob/new_player/sprite_accessories.dm
  tgmc.dme
Labels: Code Improvement, Requires Testing

#605 New lower medbay layout
  maps/Z.03.TGS_Theseus.dmm
Labels: Removal, Sprites, Tweak

#689 Fixes LOOC
  .gitignore
  code/game/verbs/ooc.dm
  tmp/iconCache.sav
Labels: Fix

#685 Actually fixes faxes.
  code/game/machinery/fax.dm
  code/modules/admin/verbs/faxes.dm
Labels: Fix

#681 Some weapons no longer try to fire when trying to equip them.
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Fix

#671 Cleans up configs, makes the defaults friendlier for downstreams, fixes a few fuckups.
  code/__DEFINES/logging.dm
  code/__HELPERS/_logging.dm
  code/controllers/configuration/entries/combat_defines.dm
  code/controllers/configuration/entries/comms.dm
  code/controllers/configuration/entries/dbconfig.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration/entries/general.dm
  code/game/atoms.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/verbs/ooc.dm
  code/modules/client/client procs.dm
  code/modules/ext_scripts/github.dm
  code/modules/ext_scripts/irc.dm
  code/modules/ext_scripts/python.dm
  config/config.txt
  config/motd.txt
  interface/skin.dmf
  tgmc.dme
Labels: Config Update

#680 Suits now properly unequip.
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix

#679 You can no longer draw/equip under all circumstances.
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix

#676 Requisitions Elevator Sounds an Alarm When Decending
  code/modules/shuttles/shuttle_supply.dm
Labels: Feature

#639 refactors gun default attachment code
  code/__DEFINES/conflict.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/screen_objects.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Refactor

#674 Ports /tg/'s goonchat
  code/_globalvars/misc.dm
  code/modules/client/asset_cache.dm
  code/stylesheet.dm
  goon/browserassets/css/browserOutput.css
  goon/browserassets/css/font-awesome.css
  goon/browserassets/css/fonts/fontawesome-webfont.eot
  goon/browserassets/css/fonts/fontawesome-webfont.svg
  goon/browserassets/css/fonts/fontawesome-webfont.ttf
  goon/browserassets/css/fonts/fontawesome-webfont.woff
  goon/browserassets/css/fonts/fontawesome-webfont.woff2
  goon/browserassets/html/browserOutput.html
  goon/browserassets/js/browserOutput.js
  goon/browserassets/js/errorHandler.js
  goon/browserassets/js/jquery.min.js
  goon/code/datums/browserOutput.dm
  goon/code/datums/jsErrorHandler.dm
  interface/skin.dmf
  tgmc.dme
Labels: Code Improvement, Requires Testing

#618 Pain Rebalance
  code/modules/mob/living/carbon/shock.dm
Labels: Test Merge Candidate, Tweak

#693 Fixes for Hunter not Unstealthing on Non-Mob Attacks
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/vehicles/cm_armored.dm
Labels: Fix, Requires Testing

#550 click relay equipment and firearm patches.
  code/_onclick/handle_click.dm
  code/_onclick/human.dm
  code/_onclick/other_mobs.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/binoculars.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/vehicles/cm_armored.dm
  tgmc.dme
Labels: Code Improvement, Fix

#669 Corp Mercs Style SL Pointer/Locator
  code/__DEFINES/mobs.dm
  code/__DEFINES/subsystems.dm
  code/__HELPERS/lists.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects.dm
  code/controllers/stonedmc/subsystem/direction.dm
  code/game/jobs/job/squads.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  icons/Marine/marine-items.dmi
  tgmc.dme
Labels: Feature, Refactor, Requires Testing, Sprites

#700 Renames RoleAuthority to SSjob
  code/datums/mind.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/gameticker.dm
  code/game/jobs/job/marines.dm
  code/game/jobs/role_authority.dm
  code/game/machinery/bots/cleanbot.dm
  code/game/machinery/bots/medbot.dm
  code/game/machinery/bots/mulebot.dm
  code/game/machinery/cryopod.dm
  code/game/world.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/panels/ban_panel.dm
  code/modules/admin/server_verbs.dm
  code/modules/admin/topic.dm
  code/modules/client/preferences.dm
  code/modules/cm_marines/marines_consoles.dm
  code/modules/cm_marines/overwatch.dm
  code/modules/mob/new_player/new_player.dm
Labels: Code Improvement

#707 Fixes guns Initialize() runtimes.
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Fix

#696 Purges a lot of traitor/syndicate shitcode.
  code/_globalvars/lists/objects.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/stonedmc/subsystem/atoms.dm
  code/datums/mind.dm
  code/datums/spells/area_teleport.dm
  code/datums/spells/conjure.dm
  code/datums/spells/dumbfire.dm
  code/datums/spells/emplosion.dm
  code/datums/spells/ethereal_jaunt.dm
  code/datums/spells/explosion.dm
  code/datums/spells/genetic.dm
  code/datums/spells/horsemask.dm
  code/datums/spells/inflict_handler.dm
  code/datums/spells/knock.dm
  code/datums/spells/mind_transfer.dm
  code/datums/spells/projectile.dm
  code/datums/spells/trigger.dm
  code/datums/spells/turf_teleport.dm
  code/datums/spells/wizard.dm
  code/game/gamemodes/events.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/extended/infection.dm
  code/game/gamemodes/factions.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/gameticker.dm
  code/game/gamemodes/intercept_report.dm
  code/game/gamemodes/newobjective.dm
  code/game/gamemodes/objective.dm
  code/game/gamemodes/sandbox/h_sandbox.dm
  code/game/gamemodes/sandbox/sandbox.dm
  code/game/gamemodes/setupgame.dm
  code/game/gamemodes/traitor/traitor.dm
  code/game/machinery/camera/tracking.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/wishgranter.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/pinpointer.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/traitordevices.dm
  code/game/objects/items/devices/uplinks.dm
  code/game/objects/items/implants/implantuplink.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/structures/crates_lockers/closets/syndicate.dm
  code/global.dm
  code/modules/admin/topic.dm
  code/modules/events/event_dynamic.dm
  code/modules/events/ion_storm.dm
  code/modules/mob/living/silicon/robot/laws.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/simple_animal/constructs.dm
  code/modules/nano/nanoui.dm
  code/modules/shuttles/antagonist.dm
  nano/templates/uplink.tmpl
  tgmc.dme
Labels: Code Improvement, Config Update, Removal, Requires Testing

#721 Moves inflatable deflation code to... inflatable code.
  code/game/machinery/vending/vending.dm
  code/game/objects/structures/inflatable.dm
Labels: Code Improvement

#720 Fixes some pronouns
  code/game/objects/items/toys/cards.dm
  code/game/objects/objs.dm
Labels: Fix

#574 CMO letters of Commendation
  code/datums/medal_awards.dm
  code/modules/clothing/under/ties.dm
  code/modules/paperwork/paper.dm
  icons/mob/ties.dmi
  icons/obj/clothing/ties_overlay.dmi
  icons/obj/items/paper.dmi
Labels: Feature, Sprites, Work In Progress

#698 Warrior Punch Rework
  code/modules/mob/living/carbon/xenomorph/Powers.dm
Labels: Tweak

#712 Fixes a goonchat runtime
  goon/code/datums/browserOutput.dm
Labels: Fix

#646 New Runner Passive: Hit and Run
  code/modules/mob/living/carbon/xenomorph/Castes/Runner.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance/Rebalance, Feature

#701 You can now field strip weapons without skills.
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
Labels: Fix

#710 Some ghosts related fixes
  code/game/atoms_movable.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#727 Updates the pull request template.
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub

#718 Defibs now show the correct charge~
  code/game/objects/items/devices/defibrillator.dm
Labels: Fix

#726 Energy guns description fix.
  code/modules/projectiles/updated_projectiles/guns/energy.dm
Labels: Fix

#722 Fixes SL tracking after squad transfer
  code/game/jobs/job/squads.dm
Labels: Fix

#724 Stops people from teleporting to CC via televac.
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix

#383 [Ready](?) Tankcode sanitization.
  code/_onclick/handle_click.dm
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items/storage/internal.dm
  code/game/objects/items/storage/storage.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
  code/modules/mob/mob_verbs.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/shuttles/escape_pods.dm
  code/modules/vehicles/cm_armored.dm
  code/modules/vehicles/multitile.dm
  code/modules/vehicles/tank.dm
Labels: Needs Review, Requires Testing

#723 Implements the CMO's Letter of recommendation
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Labels: Feature

#728 Map merge formats map files
  maps/Z.01.BigRed_v2.dmm
  maps/Z.01.Ice_Colony_v2.dmm
  maps/Z.01.LV624.dmm
  maps/Z.01.Prison_Station_FOP.dmm
  maps/Z.01.Whiskey_Outpost_v2.dmm
  maps/Z.02.Admin_Level.dmm
  maps/Z.03.TGS_Theseus.dmm
  maps/Z.04.Low_Orbit.dmm
  tools/mapmerge/1prepare_map.bat
  tools/mapmerge/2clean_map.bat
  tools/mapmerge/MapPatcher.jar
  tools/mapmerge/clean_map_git.sh
  tools/mapmerge/install.txt
  tools/mapmerge/mapmerge.sh
  tools/mapmerge2/Prepare Maps.bat
  tools/mapmerge2/README.md
  tools/mapmerge2/convert.py
  tools/mapmerge2/dmi.py
  tools/mapmerge2/dmm.py
  tools/mapmerge2/dmm2tgm.bat
  tools/mapmerge2/frontend.py
  tools/mapmerge2/map_scripts/cornersfix.txt
  tools/mapmerge2/map_scripts/turfs2decals.txt
  tools/mapmerge2/mapmerge.bat
  tools/mapmerge2/mapmerge.py
  tools/mapmerge2/merge_driver_dmi.py
  tools/mapmerge2/precommit.py
  tools/mapmerge2/requirements-install.bat
  tools/mapmerge2/requirements.txt
  tools/mapmerge2/tgm2dmm.bat
  tools/mapmerge2/update_paths.py
Labels: Code Improvement, Tools

#743 Fix areas powerstate not properly updating for discrete power use
  code/game/area/areas.dm
  code/game/machinery/vending/vending.dm
  code/game/machinery/vending/vending_types.dm
Labels: Fix

#757 Rounds the tactical stock amounts scale.
  code/game/gamemodes/cm_initialize.dm
Labels: Fix

#758 Mends broken powerpacks.
  code/modules/cm_marines/equipment/weapons.dm
Labels: Fix

#552 [Ready]Refactors breath and health threshold code a bit.
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/unsorted.dm
  code/controllers/configuration/entries/game_options.dm
  code/datums/diseases/advance/symptoms/fever.dm
  code/datums/diseases/advance/symptoms/shivering.dm
  code/game/dna/dna_misc.dm
  code/game/dna/dna_modifier.dm
  code/game/dna/genes/monkey.dm
  code/game/objects/items/devices/defibrillator.dm
  code/game/objects/items/tanks/tanks.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/mob/living/carbon/carbon_status_procs.dm
  code/modules/mob/living/carbon/hellhound/hellhound.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_status_procs.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/human/life/handle_grabbed.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/organs/organ_internal.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/reagents/chemistry_reagents/food.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  code/modules/reagents/chemistry_reagents/other.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
  code/modules/surgery/face.dm
  config/config.txt
  tgmc.dme
Labels: Code Improvement, Config Update, Needs Review, Refactor

#633 Chairs no longer rotate at the speed of light.
  code/_onclick/observer.dm
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Config Update

#735 Makes the scout shotgun hold 10 rounds total counting the one shell in the chamber
  code/modules/projectiles/updated_projectiles/magazines/shotguns.dm
Labels: Balance/Rebalance

#731 Crew console interface upgrade
  code/__HELPERS/cmp.dm
  code/__HELPERS/lists.dm
  code/__HELPERS/sorts/InsertSort.dm
  code/__HELPERS/sorts/MergeSort.dm
  code/__HELPERS/sorts/TimSort.dm
  code/__HELPERS/sorts/__main.dm
  code/game/machinery/computer/crew.dm
  nano/templates/crew_monitor.tmpl
Labels: Tweak

#765 Autodoc bugfix and pulse counting spellchecking
  code/game/machinery/autodoc.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix, Grammar and Formatting

#755 fixing xeno FF staggerstun
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Fix

#737 Medevac stretcher no bucklee removal
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Removal

#522 Hyperzine Made Great Again
  code/__DEFINES/mobs.dm
  code/game/objects/items/devices/scanners.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/chemistry_reactions/other.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  code/modules/reagents/chemistry_reagents/other.dm
Labels: Balance/Rebalance, Tweak

#668 New CL Suit
  code/game/objects/items/devices/portable_vendor.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/uniform_0.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#730 Mateba and M44 belt fix
  code/game/objects/items/storage/belt.dm
Labels: Balance/Rebalance

#767 Adds diffrent name/desc for adv hypo
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Tweak

#615 autoinjectors for the pill machine.
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/reagents/Chemistry-Machinery.dm
  icons/obj/items/chemistry.dmi
  icons/obj/items/syringe.dmi
Labels: Feature, Refactor, Requires Testing, Sprites

#742 Fixing the not fixed energy guns description
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/misc.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Test Merge Candidate

#761 MinigunUnderBarrelRemoval
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Test Merge Candidate, Tweak

#762 Warrior, Neurotox, Flechette and Lasgun Nerfs
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/reagents/chemistry_reagents/other.dm
Labels: Balance/Rebalance

#766 Sniper gains an integrated laze in its gun.
  code/_onclick/handle_click.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Feature

#785 Hunters Must Be on Same Z Level As Queen to Regen Plasma Off Weeds
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance/Rebalance

#783 adds missing qdel when wrenching pipes
  code/modules/atmospherics/machinery/atmosmachinery.dm
Labels: Fix

#784 Fixes grass tiles being black.
  icons/turf/almayer.dmi
Labels: Fix, Sprites
