Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2019-11, with the labels that each got.

#3210 Fixes my armor sprites positioning
  icons/mob/suit_1.dmi
Labels: Sprites

#3205 Some fixes for Icy Caves Map
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Map Edit

#3192 Redesigned Player Setup
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/mob/new_player/new_player.dm
Labels: Tweak

#3207 Make tackle damage respect 80% of armor value
  code/__DEFINES/mobs.dm
Labels: Balance/Rebalance, Requires Testing, Test Merge Candidate

#3173 Some damage de-escalation stuff.
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#3176 Nerfs B18 Armor A Bit
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance/Rebalance, Requires Testing

#3229 Xeno Rebalance
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Labels: Balance/Rebalance, Requires Testing

#3218 Damage deescalation for marine side
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Balance/Rebalance, Requires Testing

#3228 Shrike Gets Larva Growth Acceleration Sting
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
Labels: Balance/Rebalance, Requires Testing

#3238 deletes two apostrophes
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Grammar and Formatting

#3217 More End of Round Deathmatch roles
  code/datums/gamemodes/game_mode.dm
Labels: Feature, Test Merge Candidate

#3235 removes antidepressants, makes reagents do more things as multiples of defines
  code/__DEFINES/mobs.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/reagents/chemistry_reactions/medical.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  code/modules/reagents/chemistry_reagents/other.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
Labels: Removal

#3213 Makes Helmets Smaller
  code/modules/clothing/head/helmet.dm
Labels: Tweak

#3232 Removes antihug properties of map-spawned masks
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/modules/clothing/masks/gasmask.dm
Labels: Map Edit, Removal

#3236 Removes stored larva loss on queen death
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance/Rebalance, Removal

#3254 xeno keybind name changes changes
  code/datums/keybinding/xeno.dm
Labels: Grammar and Formatting

#3255 makes explosions not explode things 4 times
  code/game/objects/explosion.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
Labels: Balance/Rebalance, Fix

#3262 Minigun Buff
  code/__HELPERS/mobs.dm
  code/datums/components/full_auto_fire.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Balance/Rebalance, Requires Testing

#3245 Xeno firefighters
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Balance/Rebalance

#3246 Fixes ventcrawling when resting
  code/_onclick/ventcrawl.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
Labels: Fix

#3243 Respawn and no repeated names
  code/__DEFINES/jobs.dm
  code/__DEFINES/mode.dm
  code/__HELPERS/game.dm
  code/_globalvars/admin.dm
  code/_globalvars/lists/mobs.dm
  code/datums/emergency_calls/clf.dm
  code/datums/emergency_calls/colonists.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/freelancers.dm
  code/datums/emergency_calls/imperium.dm
  code/datums/emergency_calls/pizza.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/emergency_calls/upp.dm
  code/datums/emergency_calls/upp_commando.dm
  code/datums/emergency_calls/xeno.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/machinery/cryopod.dm
  code/modules/admin/holder.dm
  code/modules/admin/server_verbs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_verbs.dm
  code/modules/mob/new_player/new_player.dm
Labels: Feature, Fix

#3266 Shuttle fixes
  _maps/shuttles/alamo.dmm
  code/__DEFINES/components.dm
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/crash.dm
  code/game/objects/machinery/sentries.dm
  code/modules/admin/fun_verbs.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/ert.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/shuttle/shuttle.dm
  tgui-next/packages/tgui/interfaces/MarineDropship.js
  tgui-next/packages/tgui/public/tgui.bundle.js
Labels: Balance/Rebalance, Fix, Map Edit, UI

#3263 Shrike Unrelenting Force now uses plasma
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Fix

#3270 Rebalance of marine armor
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance/Rebalance

#3271 Remove edginess/ballistic eletric bogaloo 2
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Removal

#3260 Resin Traps, Goo, and Eggs are destroyed if the resin tile below them is also destroyed.
  code/game/objects/effects/weeds.dm
  code/game/objects/structures/xeno.dm
Labels: Balance/Rebalance, Requires Testing

#3227 Reworks Queen (Including removing acid spit)
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Requires Testing

#3273 Buffs machete,nerfs weed nodes
  code/game/objects/effects/weeds.dm
  code/game/objects/items/weapons/blades.dm
Labels: Balance/Rebalance

#3272 remove br memes
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Tweak

#3275 Marine Snow Slowdown reduced from +75% move speed penalty to +50% move speed penalty
  code/game/turfs/snow.dm
Labels: Balance/Rebalance, Requires Testing

#3283 New spacemandmm release
  code/controllers/globals.dm
  code/datums/datum.dm
  code/datums/elements/_element.dm
  code/datums/emergency_calls/emergency_call.dm
  code/game/atoms_movable.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/fence.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  dependencies.sh
Labels: Tools

#3291 you are no longer shot by specifically a military laser bolt
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Grammar and Formatting

#3293 Custom Built Shotgun Nerf
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
Labels: Balance/Rebalance

#3261 SpecialClick Framework added, Vaulting and holecrawling changed to fit into it
  code/datums/keybinding/carbon.dm
  code/datums/keybinding/keybinding.dm
  code/datums/keybinding/mob.dm
  code/game/atoms.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/structures.dm
  code/game/objects/structures/barricade.dm
  strings/tips/marine.txt
  strings/tips/xeno.txt
Labels: Config Update, Requires Testing, Sprites, Tweak, UI

#3280 Reverts IS to old storage
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance/Rebalance, Requires Testing, Revert

#3274 T64 DMR
  code/datums/gamemodes/distress.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  sound/weapons/guns/fire/T64.ogg
  sound/weapons/guns/fire/desktop.ini
Labels: Balance/Rebalance, Feature, Requires Testing, Sound, Sprites

#3295 Nerfs permastun memes
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Balance/Rebalance

#3320 Removes Ice Cave Memes
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Balance/Rebalance, Map Edit, Removal, Requires Testing

#3314 Louder DropShip Takeoff Sound
  sound/effects/engine_startup.ogg
Labels: Fix, Requires Testing, Sound

#3302 Move delay from wearing B18 armor increased from +100% to +115%
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance/Rebalance, Test Merge Candidate

#3299 Lowers runners speed by 0.1.
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
Labels: Balance/Rebalance

#3308 Removes hit and run from runner
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance/Rebalance, Removal, Requires Testing

#3300 Crash coefficient
  code/controllers/configuration/entries/game_options.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/game_mode.dm
Labels: Config Update

#3307 Supply shuttle runtime fixes
  code/game/objects/machinery/doors/railing.dm
  code/modules/shuttle/supply.dm
Labels: Fix

#3310 Fixes xenos not on the main ground being deleted on hijacks
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#3312 Fire bugfix
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Fix

#3313 Xeno action runtime fix
  code/datums/actions/xeno_action.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#3315 Headset camera runtime fix
  code/game/objects/items/radio/headset.dm
Labels: Fix

#3311 Fixes bad signals
  code/game/objects/items/storage/backpack.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#3321 Fixes a health scanner do_after runtime
  code/game/objects/items/scanners.dm
Labels: Fix

#3323 Squad tracker runtime fix
  code/game/objects/items/radio/headset.dm
Labels: Fix

#3325 Pillar pipe fix
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#3326 Carrier Plasma Tweaks
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
Labels: Balance/Rebalance, Requires Testing

#3332 Increases Queen heal cooldown
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Balance/Rebalance, Requires Testing

#3317 Powerpack reload fix
  code/game/objects/items/storage/marine_boxes.dm
Labels: Fix

#3289 Gun repaths
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/shuttles/big_ert.dmm
  code/datums/emergency_calls/supplies.dm
  code/datums/gamemodes/distress.dm
  code/datums/jobs/job/deathsquad.dm
  code/datums/jobs/job/pmc.dm
  code/datums/supplypacks.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
  code/modules/projectiles/updated_projectiles/magazines/smgs.dm
Labels: Map Edit

#3303 removes shift spits from queen
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Removal

#3339 Multi Carrier trap fix
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Fix

#3340 fixes m39 belt sprite issue
  icons/obj/clothing/belts.dmi
Labels: Fix, Sprites

#3301 Spitting anything (acid spit, slowdown spit, boiler spit) as a Xeno slows you down for a short time.
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance/Rebalance, Test Merge Candidate

#3338 Changes DMR a bit
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
Labels: Balance/Rebalance, Requires Testing

#3342 Nerfs Meme guns
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
Labels: Balance/Rebalance, Requires Testing

#3322 Larval toxin changes
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
Labels: Balance/Rebalance

#3353 fixes boiler lights going out after an aheal
  code/modules/mob/living/living_defense.dm
Labels: Do Not TM, Fix

#3354 Adds T-42 LMG to PFCs 2.0
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  code/datums/emergency_calls/supplies.dm
  code/datums/gamemodes/distress.dm
  code/datums/supplypacks.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  sound/weapons/guns/interact/t42_reload.ogg
  sound/weapons/guns/interact/t42_unload.ogg
Labels: Feature, Map Edit, Sound, Sprites

#3364 Fixes M92 missing empty sprite
  icons/obj/items/gun.dmi
Labels: Fix, Sprites

#3202 Heavy helmet
  code/__DEFINES/equipment.dm
  code/__DEFINES/is_helpers.dm
  code/game/objects/effects/misc.dm
  code/game/objects/items.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/xeno.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/codex/entries/clothing_codex.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/life/handle_disabilities.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/mob_grab.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  icons/mob/head_1.dmi
  icons/mob/screen/full.dmi
  icons/obj/clothing/cm_hats.dmi
Labels: Feature, Requires Testing, Sprites

#3352 Rocket (And Demo) buff
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#3362 gives hyposprays and its subtypes melee range
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Fix

#3343 Legacy chat support re-enabled
  code/__DEFINES/misc.dm
  code/controllers/subsystem/chat.dm
  code/controllers/subsystem/vote.dm
  code/game/verbs/ooc.dm
  code/modules/goonchat/browserOutput.dm
Labels: Feature

#3355 Remove IMDPs
  code/datums/supplypacks.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Balance/Rebalance

#3363 m81 grenade launcher fix
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Fix

#3365 Headless reviving fix
  code/__DEFINES/mobs.dm
  code/game/objects/items/defibrillator.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/organs/limbs.dm
Labels: Fix

#3372 Xenos armor fixes
  code/game/objects/effects/aliens.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/organs/limbs.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Balance/Rebalance, Fix

#3374 Detpack runtime fix
  code/game/objects/items/radio/detpack.dm
Labels: Fix

#3375 Buckle runtime fix
  code/game/objects/objs.dm
Labels: Fix

#3371 Events-based Cryosleep machines
  code/__DEFINES/components.dm
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/machinery/cryopod.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/logout.dm
  code/modules/mob/living/carbon/xenomorph/logout.dm
Labels: Tweak

#3358 New attack animations
  code/__DEFINES/combat.dm
  code/_onclick/item_attack.dm
  code/_onclick/telekinesis.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_attackpaw.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  code/modules/vehicles/multitile/cm_armored.dm
  icons/effects/attacks.dmi
  icons/effects/effects.dmi
Labels: Feature, Sprites

#3331 Shotgun spread tweaks
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#3379 Nerfs queen speed
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Balance/Rebalance, Requires Testing

#3305 Converts marine gloves to greyscale
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/datums/jobs/squads.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Feature, Requires Testing, Sprites

#3294 Prison variants and SG/SL resprites
  _maps/prison_station_fop.json
  code/__DEFINES/maps.dm
  code/__DEFINES/objects.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/items/storage/storage.dmi
Labels: Feature, Map Edit, Sprites

#3367 Adds the T-18 and T-12 for PFCs
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/datums/emergency_calls/supplies.dm
  code/datums/gamemodes/distress.dm
  code/datums/supplypacks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  sound/weapons/guns/fire/t18.ogg
  sound/weapons/guns/interact/t18_reload.ogg
  sound/weapons/guns/interact/t18_unload.ogg
Labels: Balance/Rebalance, Feature, Map Edit, Requires Testing, Sound, Sprites

#3377 Removed intentional "cooldowns" for interacting with storage and items
  code/_onclick/human.dm
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
Labels: Balance/Rebalance, Fix, Requires Testing

#3366 Properly Buffs/Nerfs the LMG
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
Labels: Balance/Rebalance, Needs Balance Review

#3350 Better disk spawns
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/area/icy_caves.dm
Labels: Balance/Rebalance, Map Edit

#3380 Rocket Buff, I guess
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Requires Testing, Tweak

#3397 fixes the megaphone as a xeno translation device.
  code/game/objects/items/megaphone.dm
Labels: Fix

#3256 (Re)Adds a new shotgun scout specialization role.
  code/datums/components/dripping.dm
  code/datums/supplypacks.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/magazines/shotguns.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  tgmc.dme
Labels: Feature, Requires Testing, Sprites

#3357 Adds a New Map: Desert Outpost AKA "Dessert"
  _maps/_basemap.dm
  _maps/desert.json
  _maps/map_files/desert/desert.dmm
  code/game/area/desert.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/machinery/sentries.dm
  code/game/turfs/walls/wall_types.dm
  config/maps.txt
  icons/obj/structures/windows.dmi
  tgmc.dme
Labels: Config Update, Feature, Map Edit, Requires Testing, Sprites

#3398 fixes spent flares activating.
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Fix

#3394 Mortar changes
  code/datums/supplypacks.dm
  code/game/objects/structures/mortar.dm
Labels: Balance/Rebalance, Requires Testing

#3396 Fixes the spare vendor dispensing wrong camo helmet
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#3387 Adds B17
  code/__DEFINES/equipment.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  icons/mob/head_1.dmi
  icons/obj/clothing/cm_hats.dmi
Labels: Feature, Requires Testing, Sprites

#3400 fixes cocking the gun producing the wrong bullet.
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Fix

#3401 Fixes Lightsticks
  code/game/turfs/snow.dm
Labels: Fix

#3392 New muzzleflashes
  code/game/visual_objects.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  icons/obj/items/projectiles.dmi
Labels: Feature, Sprites, Test Merge Candidate, Tweak

#3406 small bugfixes
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/open.dm
Labels: Fix

#3335 Fixes Carrier being able to drop 10 huggers in a group of marines in about a second
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Balance/Rebalance, Fix, Requires Testing

#3404 moves 2 crash/ert shuttle locations on the pillar
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#3405 Fix powerpacks not using their sprite
  icons/mob/back.dmi
Labels: Feature, Fix, Sprites

#3407 Fixes invisible prison pyro helmet
  icons/mob/head_1.dmi
Labels: Fix, Sprites

#3409 Pillar Of Spring Poddoor Change/Fix
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#3399 Xeno armor/health rebalance
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Labels: Balance/Rebalance, Requires Testing

#3410 Pyro Backpack Change
  code/game/objects/items/storage/backpack.dm
Labels: Needs Balance Review, Tweak

#3408 Adds the T-19 SMG
  _maps/map_files/Sulaco/Sulaco.dmm
  code/datums/emergency_calls/supplies.dm
  code/datums/gamemodes/distress.dm
  code/datums/supplypacks.dm
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/projectiles/updated_projectiles/ammunition.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/magazines/smgs.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Feature, Map Edit, Requires Testing, Sprites

#3419 Fixes Lasgun Charger double stocking.
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#3386 bodyscanners, autodocs and sleepers now eject their occupants properly when destroyed
  code/game/objects/machinery/Sleeper.dm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/autodoc.dm
Labels: Fix, Test Merge Candidate

#3420 Make jumpsuit less weird
  icons/mob/uniform_0.dmi
Labels: Sprites, Tweak

#3425 Xeno elusive break sound bug fix
  code/game/objects/structures/xeno.dm
  code/game/sound.dm
  sound/effects/alien_resin_break1.ogg
  sound/effects/alien_resin_break2.ogg
  sound/effects/alien_resin_break3.ogg
Labels: Fix, Sound

#3391 clothing_tint component
  code/__DEFINES/components.dm
  code/_onclick/telekinesis.dm
  code/datums/components/clothing_tint.dm
  code/game/objects/items.dm
  code/game/objects/items/cloaking.dm
  code/game/objects/items/marine_gear.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/codex/entries/clothing_codex.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
  tgmc.dme
Labels: Refactor

#3290 Rambo Survivors
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/job/survivor.dm
  code/datums/skills.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
Labels: Balance/Rebalance, Requires Testing

#3451 fixes tgui-next icons
  code/modules/client/asset_cache.dm
  code/modules/goonchat/browserOutput.html
Labels: Fix

#3439 Removes sneak attack bonus damage from hunter
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance/Rebalance, Duplicate, Removal, Test Merge Candidate

#3422 No More Beanbags
  code/game/objects/structures/crates_lockers/largecrate.dm
Labels: Tweak

#3445 Removes that one table
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Fix, Map Edit, Removal

#3435 M240-T to use spec skill
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
Labels: Tweak

#3437 Makes Desert More "Mortar Friendly"
  _maps/map_files/desert/desert.dmm
  code/game/area/desert.dm
Labels: Balance/Rebalance, Fix, Map Edit

#3444 fixes synth being able to view the shadowrealm
  code/game/objects/items/defibrillator.dm
Labels: Fix

#3416 Shrike slowdown
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
Labels: Balance/Rebalance

#3429 Removes the broken Defender Lunge
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
Labels: Removal

#3413 Grenade launcher and similar shoot through MMB or shift+click, instead of ctrl+click
  code/__DEFINES/components.dm
  code/_onclick/click.dm
  code/_onclick/observer.dm
  code/_onclick/xeno.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/gun_helpers.dm
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Tweak

#3430 Fire and Snow interactions
  code/game/objects/effects/effect_system/particle_effects.dm
  code/game/turfs/snow.dm
  code/modules/mob/living/living_defense.dm
Labels: Feature, Needs Balance Review

#3462 Fixes invisible FC powerpacks
  icons/mob/back.dmi
  icons/obj/items/storage/storage.dmi
Labels: Sprites

#3464 Pillar vendor fix
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#3465 Fixes T19 Mag name on vendors
  code/modules/projectiles/updated_projectiles/magazines/smgs.dm
Labels: Fix

#3470 Fix shrike jobban
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#3478 Re-adds squad colors
  code/datums/jobs/squads.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
Labels: Requires Testing, Sprites

#3481 Makes Ice Caves use ice variants
  _maps/icy_caves.json
Labels: Map Edit

#3474 Adds ACCESS_CIVILIAN_ENGINEERING to Ship Techs and changes circuit weights to TINY.
  code/datums/jobs/job/shipside.dm
  code/game/objects/items/circuitboards/circuitboard.dm
Labels: Test Merge Candidate, Tweak

#3467 Welderpacks can be opened while worn
  code/game/objects/items/storage/backpack.dm
Labels: Balance/Rebalance, Test Merge Candidate

#3461 Reworks all armor sets to be like marines ones
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance/Rebalance, Fix, Requires Testing

#3459 Lower wield delay, higher fire delay for spec grenade launcher
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Balance/Rebalance, Requires Testing

#3479 Makes beaker transfer amounts not bad
  code/game/objects/items/reagent_containers/glass.dm
Labels: Tweak

#3457 Crash T1s start at Mature instead of Elder now.
  code/datums/gamemodes/crash.dm
Labels: Balance/Rebalance

#3455 DMR minor nerf
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
Labels: Balance/Rebalance, Needs Balance Review

#3448 Custom squad amounts
  _maps/pillar_of_spring.json
  _maps/shuttles/tgs_canterbury.dmm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/ticker.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/squads.dm
  code/datums/map_config.dm
  code/game/objects/machinery/computer/marines_consoles.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/new_player/new_player.dm
Labels: Config Update, Map Edit

#3458 autobuild tgui-next
  .github/workflows/autobuild_tgui.yml
Labels: GitHub, Tools

#3216 Adds more gun type codexes and description changes
  code/modules/codex/entries/guns_codex.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/energy.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/smgs.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/magazines/flamer.dm
  code/modules/projectiles/updated_projectiles/magazines/rifles.dm
  code/modules/projectiles/updated_projectiles/magazines/shotguns.dm
  icons/obj/items/ammo.dmi
Labels: Feature, Sprites, Test Merge Candidate, Tweak

#3482 Allows the heavy armor to have variant sprite
  code/modules/clothing/suits/marine_armor.dm
Labels: Tweak

#3476 Adds the T-35 Pump shotgun to marines
  code/datums/gamemodes/distress.dm
  code/datums/supplypacks.dm
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/gun.dmi
  icons/obj/items/storage/storage.dmi
Labels: Requires Testing, Sprites

#3450 Fix crusher exiting turfs
  code/__DEFINES/components.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Fix, Requires Testing

#3483 Nerfs all non-helmet marine headgear
  code/modules/clothing/head/head.dm
Labels: Balance/Rebalance, Requires Testing

#3487 Some helmet changes
  code/modules/clothing/head/helmet.dm
Labels: Balance/Rebalance, Requires Testing, Tweak
