Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2019-04, with the labels that each got.

#1147 Changes storage lists to typepaths
  code/datums/diseases/black_goo.dm
  code/game/machinery/cloning.dm
  code/game/mecha/mecha_control_console.dm
  code/game/objects/items.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/bible.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/items/storage/misc.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/items/storage/surgical_tray.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/items/storage/wallets.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/ties.dm
  code/modules/cm_marines/equipment/gear.dm
  code/modules/cm_marines/equipment/sentries.dm
  code/modules/cm_marines/equipment/weapons.dm
  code/modules/cm_marines/smartgun_mount.dm
  code/modules/codex/entries/clothing_codex.dm
  code/modules/codex/entries/misc_codex.dm
  code/modules/detectivework/evidence.dm
  code/modules/hydroponics/seed_machines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/paperwork/photography.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
  code/modules/projectiles/updated_projectiles/guns/revolvers.dm
  code/modules/projectiles/updated_projectiles/guns/shotguns.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Code Improvement, Requires Testing

#1168 Gamemode code cleanup.
  _maps/bigred_v2.json
  _maps/ice_colony_v2.json
  _maps/lv624.json
  _maps/prison_station_fop.json
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mode.dm
  code/__DEFINES/preferences.dm
  code/controllers/stonedmc/subsystem/ticker.dm
  code/datums/map_config.dm
  code/datums/mind.dm
  code/game/gamemodes/cm_initialize.dm
  code/game/gamemodes/cm_process.dm
  code/game/gamemodes/colonialmarines/colonialmarines.dm
  code/game/gamemodes/colonialmarines/halloween2016.dm
  code/game/gamemodes/colonialmarines/whiskey_outpost.dm
  code/game/gamemodes/distress.dm
  code/game/gamemodes/events/power_failure.dm
  code/game/gamemodes/extended.dm
  code/game/gamemodes/extended/extended.dm
  code/game/gamemodes/extended/infection.dm
  code/game/gamemodes/game_mode.dm
  code/game/gamemodes/huntergames.dm
  code/game/machinery/cryopod.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/effects/landmarks/mode.dm
  code/game/objects/effects/misc.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/admin/panels/mode_panel.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Larva.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Predalien.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/login.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/power/power.dm
  code/modules/shuttles/marine_ferry.dm
  config/maps.txt
  tgmc.dme
Labels: Code Improvement, Config Update, Map Edit, Requires Testing

#1172 A/B testing for machine subsystem changes.
  code/controllers/stonedmc/subsystem/machines.dm
Labels: Refactor

#1165 Fixes warnings from dm-langserver
  code/game/machinery/machinery.dm
  code/game/machinery/nuclearbomb.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/machinery/telecomms/traffic_control.dm
  code/game/objects/items/reagent_containers/food/sandwich.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/admin/holder.dm
  code/modules/flufftext/TextFilters.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/nano/JSON_Reader.dm
  code/modules/paperwork/paper.dm
  code/modules/power/power.dm
  code/modules/projectiles/targeting.dm
  code/modules/research/rdmachines.dm
  code/modules/scripting/AST/AST_Nodes.dm
  code/modules/scripting/AST/Blocks.dm
  code/modules/scripting/AST/Operators/Binary_Operators.dm
  code/modules/scripting/AST/Operators/Unary_Operators.dm
  code/modules/scripting/AST/Statements.dm
  code/modules/scripting/Errors.dm
  code/modules/scripting/IDE.dm
  code/modules/scripting/Implementations/Telecomms.dm
  code/modules/scripting/Implementations/_Logic.dm
  code/modules/scripting/Interpreter/Evaluation.dm
  code/modules/scripting/Interpreter/Interaction.dm
  code/modules/scripting/Interpreter/Interpreter.dm
  code/modules/scripting/Interpreter/Scope.dm
  code/modules/scripting/Options.dm
  code/modules/scripting/Parser/Expressions.dm
  code/modules/scripting/Parser/Keywords.dm
  code/modules/scripting/Parser/Parser.dm
  code/modules/scripting/Scanner/Scanner.dm
  code/modules/scripting/Scanner/Tokens.dm
  code/modules/scripting/stack.dm
  tgmc.dme
Labels: Code Improvement

#1175 fixes revolver sprite
  icons/obj/items/gun.dmi
Labels: Sprites

#1104 Smartgun Tweaks
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Balance/Rebalance, Tweak

#1046 Fix: Scales ERT Reinforcements Property
  code/datums/emergency_calls/emergency_call.dm
Labels: Balance/Rebalance

#1184 Makes the master compile.
  code/datums/emergency_calls/emergency_call.dm
Labels: Fix, Priority: CRITICAL

#1155 Knife Attachments
  code/modules/projectiles/updated_projectiles/guns/pistols.dm
Labels: Feature, Test Merge Candidate

#1182 Fixes SD walls
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Fix, Map Edit

#1183 Fixes Oxycodone OD
  code/modules/reagents/chemistry_reagents/medical.dm
Labels: Fix, Test Merge Candidate

#431 Adds Imperium clothing
  code/controllers/communications.dm
  code/datums/emergency_calls/imperium.dm
  code/datums/skills.dm
  code/game/jobs/job/imperium.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/presets.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/mob/language.dm
  code/stylesheet.dm
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/uniforms.dmi
  tgmc.dme
Labels: Feature, Sprites

#982 Refactors Hive Status
  .github/CODEOWNERS
  code/__DEFINES/mobs.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/mobs.dm
  code/datums/mob_hud.dm
  code/game/gamemodes/distress.dm
  code/game/gamemodes/game_mode.dm
  code/game/objects/structures/plants.dm
  code/game/verbs/who.dm
  code/modules/admin/fun_verbs.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/codex/entries/mobs_codex.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/logout.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/Abilities.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Boiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Carrier.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Crusher.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Defender.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Defiler.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Drone.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hivelord.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Hunter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Larva.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Praetorian.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Queen.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Ravager.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Runner.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Sentinel.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Spitter.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Warrior.dm
  code/modules/mob/living/carbon/xenomorph/Castes/Xenoborg.dm
  code/modules/mob/living/carbon/xenomorph/Embryo.dm
  code/modules/mob/living/carbon/xenomorph/Evolution.dm
  code/modules/mob/living/carbon/xenomorph/Facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/Powers.dm
  code/modules/mob/living/carbon/xenomorph/XenoAttacks.dm
  code/modules/mob/living/carbon/xenomorph/XenoProcs.dm
  code/modules/mob/living/carbon/xenomorph/XenoUpgrade.dm
  code/modules/mob/living/carbon/xenomorph/Xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  tgmc.dme
Labels: GitHub, Refactor, Requires Testing

#1163 Doctor medical buff
  code/__DEFINES/objects.dm
  code/__DEFINES/skills.dm
  code/datums/skills.dm
  code/game/atoms.dm
  code/game/objects/items/devices/defibrillator.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/objs.dm
Labels: Balance/Rebalance

#1141 Sl Armor Buff
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance/Rebalance

#1149 Slowstack Related Balance Tweaks - TESTED
  code/__DEFINES/conflict.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance/Rebalance, Requires Testing, Tweak

#1196 Minor changes to xeno critical hits
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Fix, Requires Testing

#1189 Fixes pointblank doing double damage
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Fix

#1135 Snowflake Beret for the FC + admeme headband
  code/game/jobs/job/shipside.dm
  code/modules/clothing/head/head.dm
  icons/mob/head_0.dmi
  icons/mob/head_1.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, Sprites

#272 [Ready] more directional sprites for wall mounted stuff.
  _maps/WIP/Sulaco_bottom.dmm
  _maps/WIP/Sulaco_top.dmm
  _maps/WIP/Z.01.Desert-Dam.dmm
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/generic/Admin_Level.dmm
  code/__DEFINES/machines.dm
  code/_globalvars/bitfields.dm
  code/game/atoms_movable.dm
  code/game/machinery/air_alarm.dm
  code/game/machinery/fire_alarm.dm
  code/game/objects/closets/walllocker.dm
  code/game/objects/items/frames/alarms.dm
  code/game/objects/items/frames/frame.dm
  code/game/objects/items/tools/extinguisher.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/extinguisher.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/modules/power/apc.dm
  code/modules/security_levels/security_levels.dm
  icons/obj/objects.dmi
  icons/obj/wallframes.dmi
Labels: Map Edit, Needs Review, Sprites

#1193 Removes Autopsy, cleans up limb damage.
  code/_onclick/human.dm
  code/game/mecha/combat/combat.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/autopsy_scanner.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/shards.dm
  code/game/objects/structures.dm
  code/modules/assembly/mousetrap.dm
  code/modules/genetics/side_effects.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/hydroponics/vines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
  code/modules/mob/living/carbon/human/life/handle_organs.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/organs/limbs.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
  code/modules/surgery/internal_bleeding.dm
Labels: Removal

#1151 Hivelord Improvements - TESTED
  code/__DEFINES/mobs.dm
  code/game/turfs/turf.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/hivelord.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Tweak

#1109 Slight Projectile Speed Increase
  code/controllers/configuration/entries/combat_defines.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
Labels: Balance/Rebalance, Config Update, Tweak

#1204 Purges xenoborgs
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/_globalvars/bitfields.dm
  code/modules/mob/living/carbon/xenomorph/castes/xenoborg/abilities_xenoborg.dm
  code/modules/mob/living/carbon/xenomorph/castes/xenoborg/castedatum_xenoborg.dm
  code/modules/mob/living/carbon/xenomorph/castes/xenoborg/xenoborg.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/mob_helpers.dm
  icons/Xeno/1x1_Xenos.dmi
  icons/Xeno/2x2_Xenos.dmi
  tgmc.dme
Labels: Sprites

#1199 fixes two xeno bugs
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#1211 Less infinite survivors.
  code/game/gamemodes/distress.dm
Labels: HOTFIX

#1217 fix for unacidable errors
  _maps/WIP/Sulaco_bottom.dmm
  _maps/WIP/Sulaco_top.dmm
  _maps/_basemap.dm
  _maps/map_files/Low_Orbit/Low_Orbit.dmm
  code/modules/cm_marines/equipment/sentries.dm
Labels: Map Edit

#1207 Fixes even more runtimes.
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#1215 Adds item_state to a couple firstaid kits and fixes.
  code/game/objects/items/storage/firstaid.dm
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
Labels: Fix, Removal, Sprites

#1212 Fixes null icon_states for nade_box types.
  code/game/objects/items/storage/boxes.dm
Labels: Fix

#1213 Fixes chemical grenades not initializing properly.
  code/game/objects/items/explosives/grenades/chem_grenade.dm
Labels: Fix

#1225 Fixes unacidable and indestructible flags checks
  code/__DEFINES/flags.dm
  code/game/machinery/machinery.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/devices/radio/detpack.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/structures.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/girders.dm
  code/modules/cm_marines/Marine_Research/Marine_Research_Items.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
Labels: Fix, HOTFIX

#1222 TYPO HOTFIX FOR HIVELORD TUNNELS
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: HOTFIX

#1206 Minigun Burst Value Redefine
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Bug, Config Update

#1209 Cleaning of code related to door displays
  code/game/machinery/door_display/door_display.dm
  icons/obj/status_display.dmi
Labels: Fix, Sprites

#1210 (un)Atomized admin PR
  code/__DEFINES/__game.dm
  code/__DEFINES/atmospherics.dm
  code/__DEFINES/jobs.dm
  code/__HELPERS/files.dm
  code/_globalvars/admin.dm
  code/_globalvars/configuration.dm
  code/_globalvars/lists/mobs.dm
  code/_globalvars/misc.dm
  code/controllers/configuration/configuration.dm
  code/controllers/stonedmc/subsystem/blackbox.dm
  code/controllers/stonedmc/subsystem/ticker.dm
  code/controllers/stonedmc/subsystem/vote.dm
  code/game/atoms.dm
  code/game/gamemodes/distress.dm
  code/game/gamemodes/game_mode.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/job_exp.dm
  code/game/jobs/squads.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/mecha/mecha.dm
  code/game/objects/explosion.dm
  code/game/objects/structures/window.dm
  code/game/verbs/ooc.dm
  code/game/world.dm
  code/global.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/ban_panel.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/server_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/faxes.dm
  code/modules/client/client_procs.dm
  code/modules/cm_aliens/weeds.dm
  code/modules/economy/Accounts.dm
  code/modules/economy/economy_misc.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/mob/mob_verbs.dm
  code/modules/mob/new_player/login.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/power/apc.dm
  tgmc.dme
Labels: Administration

#1228 Fixes EORD for new_players
  code/game/gamemodes/game_mode.dm
Labels: Fix, Trivial

#1229 Fixes being able to activate SD without power
  code/game/machinery/self_destruct.dm
Labels: Fix, Trivial

#1230 Fixes chat logs displaying 1 less round
  code/modules/projectiles/updated_projectiles/gun_system.dm
Labels: Fix, Trivial

#1231 Hardening bits checks against unexpected uses
  code/__DEFINES/flags.dm
Labels: Trivial

#1227 Fixes signal emote.
  code/modules/mob/living/carbon/human/emote.dm
Labels: Fix, Trivial

#1234 Moves wound_type to castes
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/spitter.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Trivial

#1235 Shifts unweedable area checks into is_weedable
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
Labels: Trivial

#1236 Moves check_alien_construction to a turf proc
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/egg_item.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Trivial

#1233 Shifts charge mob vars to defines
  code/__DEFINES/mobs.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/razorwire.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/vehicles/cm_armored.dm
Labels: Trivial

#1192 Buffs Guardsmen
  code/datums/emergency_calls/imperium.dm
  code/datums/skills.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
Labels: Sprites, Tweak

#1244 Fixes money bag not being able to be picked up.
  code/modules/mining/money_bag.dm
Labels: Fix, Trivial

#1242 Fixes humans being able to attack xenos from the inside.
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/mob_grab.dm
Labels: Fix

#1240 Devour timer reduced
  code/modules/mob/mob_grab.dm
Labels: Balance/Rebalance

#1232 Reduces xeno icon code duplication
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Trivial

#1247 Fixes a very small runtime
  code/modules/mob/login.dm
Labels: Fix

#1219 Removes processing machinery (profiling edition)
  code/game/machinery/air_alarm.dm
  code/game/machinery/doors/airlock_control.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/fire_alarm.dm
  code/game/machinery/status_display.dm
Labels: Code Improvement, Performance, Removal

#1246 Smartgun Sight Change
  code/modules/clothing/glasses/night.dm
Labels: Balance/Rebalance

#1153 Hotfix for Hold Orders Recovery Benefits - PRIORITY
  code/modules/mob/living/carbon/human/life/handle_status_effects.dm
Labels: Merge Conflict

#1243 Admin PR, this time atomized for real.
  code/__HELPERS/unsorted.dm
  code/_globalvars/bitfields.dm
  code/controllers/stonedmc/subsystem/job.dm
  code/datums/emergency_calls/emergency_call.dm
  code/game/gamemodes/distress.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/job_exp.dm
  code/game/jobs/job/marines.dm
  code/game/jobs/job/shipside.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/panels/mode_panel.dm
  code/modules/admin/panels/note_panel.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/server_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/chat_commands.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/admin/verbs/faxes.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/login.dm
  code/modules/mob/living/living.dm
  code/modules/mob/new_player/new_player.dm
  goon/code/datums/browserOutput.dm
Labels: Administration

#1265 [s] Fix paper
  code/modules/paperwork/paper.dm
Labels: Priority: CRITICAL

#1256 Refactors hivelord thiccening
  code/game/turfs/walls/wall_types.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
Labels: Trivial

#1267 fix clik
  code/_onclick/click.dm
Labels: Fix, Priority: High

#1255 Shifts upgrade bonuses to macros
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
Labels: Trivial

#1269 Removing the most unfinished map in our repository.
  _maps/WIP/ChigusaShipyard.dmm
  _maps/WIP/ChigusaShipyardV.2.dmm
  code/game/area/ChigusaShipyard.dm
  tgmc.dme
Labels: Map Edit

#1273 Minor paperwork QoL changes
  code/__DEFINES/__game.dm
  code/modules/client/asset_cache.dm
  code/modules/paperwork/paper.dm
  html/images/wylogo.png
  html/ntlogo.png
Labels: Fix, Tweak

#1284 Fixes #1250
  code/game/machinery/doors/poddoor.dm
Labels: Priority: High

#1277 Makes handcuffs work properly
  code/_onclick/click.dm
Labels: Fix

#1270 Replaced txt-based door code with DEFINE_FOR_X
  code/game/machinery/doors/airlock_types.dm
Labels: Code Improvement

#1282 Fixes click code passing parameters
  code/_onclick/click.dm
Labels: Fix

#989 [Ready] Cleaning up hypersleepers a little.
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/__DEFINES/jobs.dm
  code/_globalvars/lists/mobs.dm
  code/_globalvars/lists/objects.dm
  code/game/machinery/cryopod.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/shuttles/escape_pods.dm
Labels: Fix, Map Edit, Test Merge Candidate

#1241 Ports forensics component.
  code/datums/components/forensics.dm
  code/game/atoms.dm
  code/game/objects/effects/effect_system/chemsmoke.dm
  code/game/objects/items/frames/light_fixtures.dm
  code/game/objects/items/stacks/cable_coil.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/transfer_valve.dm
  code/modules/clothing/clothing.dm
  code/modules/detectivework/forensics.dm
  code/modules/detectivework/scanner.dm
  code/modules/detectivework/scanning_console.dm
  code/modules/organs/organ_objects.dm
  code/modules/power/lighting.dm
  tgmc.dme
Labels: Administration, Feature

#1290 Fixes Prison Issues
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/game/turfs/walls/r_wall.dm
Labels: Fix, Map Edit

#1259 Minor cleanup of overwatch code
  code/game/jobs/squads.dm
  code/modules/cm_marines/overwatch.dm
Labels: Code Improvement

#1258 Moves squad color overlays to GLOBs
  code/datums/mob_hud.dm
  code/game/jobs/job/marines.dm
  code/game/jobs/squads.dm
  code/game/world.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Code Improvement

#1262 Fixes initial damage not being applied on flamer_fire instanciation
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/cm_marines/dropship_ammo.dm
  code/modules/mob/living/living_defines.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/gun_attachables.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/reagents/chemistry_reactions/other.dm
Labels: Fix, Requires Testing

#1260 adds HUD buttons for orders and button to show/hide the new buttons
  code/modules/cm_marines/overwatch.dm
  icons/mob/order_icons.dmi
Labels: Feature, Requires Testing

#1272 new tool vendors
  code/game/machinery/vending/marine_vending.dm
  icons/obj/machines/vending.dmi
Labels: Sprites

#1301 Tweaks tool closets
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
Labels: Tweak

#1271 Thin Sticky Rebalance
  code/modules/cm_aliens/XenoStructures.dm
Labels: Balance/Rebalance, Test Merge Candidate

#1300 Changes wallframes.dmi size to 64x64.
  code/game/machinery/air_alarm.dm
  code/game/machinery/fire_alarm.dm
  code/game/objects/closets/walllocker.dm
  code/game/objects/structures/extinguisher.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/modules/power/apc.dm
  icons/obj/apc_repair.dmi
  icons/obj/machines/monitors.dmi
  icons/obj/monitors.dmi
  icons/obj/power.dmi
  icons/obj/structures/walllocker.dmi
  icons/obj/wallframes.dmi
Labels: Test Merge Candidate

#1203 /tg/ stacks
  code/datums/supplypacks.dm
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/dna/dna_modifier.dm
  code/game/machinery/Sleeper.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/rechargestation.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/items/stacks/cable_coil.dm
  code/game/objects/items/stacks/catwalk.dm
  code/game/objects/items/stacks/flags.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/stacks/sheets/light.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/snow.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/structures/girders.dm
  code/game/supplyshuttle.dm
  code/game/turfs/turf.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/under/ties.dm
  code/modules/economy/cash.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  icons/Marine/marine-items.dmi
  icons/obj/items/items.dmi
  icons/obj/stack_objects.dmi
Labels: Feature, Sprites

#1308 Prevent hive lists from readding a *living* xeno when revived
  code/modules/mob/living/living_health_procs.dm
Labels: Fix, Priority: High

#1291 Cleaning up the minefield. Fixing #1289.
  code/game/objects/items/explosives/mine.dm
Labels: Test Merge Candidate

#1263 Band-aiding this heap of sadness that's facehuggers.
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix, Test Merge Candidate, Tweak

#1297 Make life live less
  code/controllers/stonedmc/subsystem/mobs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
Labels: Test Merge Candidate

#1140 Explosion Tweaks
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/mob_helpers.dm
Labels: Fix, Test Merge Candidate, Tweak

#814 [Ready]Refactoring smoke clouds
  code/__DEFINES/conflict.dm
  code/__HELPERS/game.dm
  code/datums/components/forensics.dm
  code/datums/spell.dm
  code/game/atoms.dm
  code/game/mecha/combat/marauder.dm
  code/game/objects/effects/effect_system/chemsmoke.dm
  code/game/objects/effects/effect_system/explosions.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/scrolls.dm
  code/game/objects/objs.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/razorwire.dm
  code/game/turfs/turf.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/cm_marines/dropship_ammo.dm
  code/modules/cm_marines/equipment/mortars.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/carbon_status_procs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/life/handle_random_events.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/mob_defines.dm
  code/modules/power/apc.dm
  code/modules/power/smes.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/projectiles/updated_projectiles/projectile.dm
  code/modules/reagents/Chemistry-Colours.dm
  code/modules/reagents/chemistry_reactions/other.dm
  code/modules/reagents/chemistry_reagents/food.dm
  code/modules/vehicles/cm_armored.dm
  tgmc.dme
Labels: Fix, Needs Review, Refactor

#1313 Door fixes
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/machinery/doors/airlock_types.dm
Labels: Fix

#773 [Ready] Tank-eful galore II
  code/__DEFINES/machines.dm
  code/modules/cm_aliens/XenoStructures.dm
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/vehicles/multitile/hardpoints.dm
  code/modules/vehicles/multitile/multitile.dm
  code/modules/vehicles/multitile/tank.dm
  code/modules/vehicles/multitile/tankvendor.dm
  code/modules/vehicles/tankvendor.dm
  tgmc.dme
Labels: Fix, Needs Review

#1305 Purges zombie code
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mode.dm
  code/_globalvars/lists/objects.dm
  code/datums/diseases/black_goo.dm
  code/defines/procs/announce.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/firedoor.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/morgue.dm
  code/game/verbs/who.dm
  code/modules/mob/language.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/reagents/chemistry_reagents/medical.dm
  code/modules/reagents/chemistry_reagents/other.dm
  tgmc.dme
Labels: Code Improvement, Removal, Test Merge Candidate

#1302 Admin changes ad nauseam
  code/game/atoms_movable.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/job_exp.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/ban_panel.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
Labels: Administration

#1268 Spitter plasma rebalance
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Test Merge Candidate

#1332 Adds sound for throwing stuff
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  sound/effects/throw.ogg
Labels: Test Merge Candidate

#1333 Adds a medic webbing, adjusts the white webbing
  code/game/machinery/vending/marine_vending.dm
  code/game/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/under/ties.dm
Labels: Feature, Test Merge Candidate

#1342 Cuter help intents
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
Labels: Feature, Trivial, Tweak

#1335 Prison Fix/Edit
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Balance/Rebalance, Fix, Map Edit

#1348 Fixes icons for holsters in suit slot
  icons/mob/suit_slot.dmi
Labels: Sprites

#1338 updated order talk sprites, changed focus to be a crosshair instead of !
  icons/mob/hud.dmi
  icons/mob/order_icons.dmi
  icons/mob/talk.dmi
Labels: Sprites, Tweak

#1315 Fixes possible runtimes for people loading in too fast
  code/modules/mob/mob.dm
Labels: Fix

#1351 Add more stats for start of round observers
  code/modules/mob/dead/observer/observer.dm
Labels: Tweak

#1352 Fixes powerpack inhand icon
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
Labels: Fix, Sprites

#1355 Adds sprites for different nade boxes
  code/game/objects/items/storage/boxes.dm
  icons/obj/items/storage/storage.dmi
Labels: Sprites

#1306 Fixes synths being affected by defiler stings.
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/powers.dm
Labels: Fix

#1336 Fixes #1318 Hanger Access
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/machinery/doors/airlock_types.dm
Labels: Fix, Map Edit

#1146 Hunter and Warrior Balance Tweak
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
Labels: Test Merge Candidate, Tweak

#1334 Removes neuro for queen, replaces by sticky.
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Balance/Rebalance, Removal

#1307 Fixing some older procs not respecting resistance flags.
  code/game/machinery/doors/airlock_types.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/machinery/doors/shutters.dm
  code/game/machinery/machinery.dm
  code/game/machinery/telecomms/machine_interactions.dm
  code/game/objects/structures.dm
  code/game/objects/structures/platforms.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window_frame.dm
  code/modules/cm_marines/dropship_equipment.dm
  code/modules/codex/entries/machinery_codex.dm
Labels: Fix

#1343 Moves boiler smoke set up away from New()
  code/game/mecha/combat/marauder.dm
  code/game/objects/effects/effect_system/effect_system.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/scrolls.dm
  code/modules/cm_marines/equipment/mortars.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/defiler.dm
  code/modules/power/apc.dm
  code/modules/power/smes.dm
  code/modules/projectiles/updated_projectiles/ammo_datums.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
  code/modules/reagents/chemistry_reactions/other.dm
Labels: Fix, Requires Testing

#1357 Fixes webbings being unable to hold medical stacks.
  code/modules/clothing/under/ties.dm
Labels: Fix

#1366 Removes the SMOKE_OPAQUE flag.
  code/__DEFINES/conflict.dm
  code/game/objects/effects/effect_system/smoke.dm
Labels: Balance/Rebalance, Removal, Test Merge Candidate

#1356 Ground turfs
  _maps/WIP/Z.01.Desert-Dam.dmm
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/items/tools/shovel_tools.dm
  code/game/turfs/closed.dm
  code/game/turfs/floor.dm
  code/game/turfs/floor_ground.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/open.dm
  code/game/turfs/open_ground.dm
  code/game/turfs/plating.dm
  code/game/turfs/snow.dm
  code/game/turfs/turf.dm
  code/game/turfs/walls/wall_types.dm
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/projectiles/updated_projectiles/guns/flamer.dm
  code/modules/shuttles/shuttle.dm
  code/modules/vehicles/multitile/tank.dm
  tgmc.dme
Labels: Balance/Rebalance, Map Edit, Test Merge Candidate

#1369 Updating and cleaning up reagents outside of chemistry_reagents.
  code/__DEFINES/mobs.dm
  code/__DEFINES/reagents.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/bitfields.dm
  code/datums/diseases/advance/advance.dm
  code/game/atoms.dm
  code/game/dna/genes/monkey.dm
  code/game/machinery/autodoc.dm
  code/game/machinery/kitchen/microwave.dm
  code/game/machinery/kitchen/smartfridge.dm
  code/game/mecha/equipment/tools/medical_tools.dm
  code/game/objects/items/paint.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/blood_pack.dm
  code/game/objects/items/reagent_containers/borghydro.dm
  code/game/objects/items/reagent_containers/dropper.dm
  code/game/objects/items/reagent_containers/food.dm
  code/game/objects/items/reagent_containers/food/cans.dm
  code/game/objects/items/reagent_containers/food/condiment.dm
  code/game/objects/items/reagent_containers/food/drinks.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/reagent_containers/reagent_container.dm
  code/game/objects/items/reagent_containers/spray.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/items/scanners.dm
  code/game/objects/items/tools/extinguisher.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/tools/misc_tools.dm
  code/game/objects/objs.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/stool_bed_chair_nest/janicart.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/cm_marines/Marine_Research/BioPrinter.dm
  code/modules/codex/categories/category_reagents.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/life/handle_organs.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/carbon/monkey/monkey.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/mob_helpers.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/Chemistry-Reactions.dm
  code/modules/reagents/Chemistry-Readme.dm
  code/modules/research/circuitprinter.dm
  code/modules/research/protolathe.dm
Labels: Code Improvement, Requires Testing

#1373 Moves game preference verb to preferences
  code/game/verbs/ooc.dm
  code/modules/client/preferences_toggles.dm
Labels: Test Merge Candidate, Tweak

#1365 Adds more directions to the ghost sprite.
  icons/mob/mob.dmi
Labels: Sprites

#1364 Fixes APC's examine() and update_icon().
  code/modules/power/apc.dm
  icons/obj/wallframes.dmi
Labels: Fix, Sprites, Test Merge Candidate

#1328 Refactor screech into screech_act
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
  code/modules/mob/living/living_defense.dm
Labels: Requires Testing

#1380 purges another reference to predaliens.
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/organs/limbs.dm
Labels: Code Improvement

#1374 Two new admin verbs: "Check Contents" and "Randomize Name"
  code/modules/admin/debug_verbs.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
Labels: Administration

#1376 updates older beret sprites, gives the CSE superior welding googles.
  code/game/jobs/job/mercenaries.dm
  code/game/jobs/job/shipside.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/head/misc_special.dm
  icons/mob/head_0.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, Sprites, Test Merge Candidate, Tweak

#1377 Buffing neuro smoke again just a very little.
  code/modules/mob/living/carbon/carbon_defense.dm
Labels: Balance/Rebalance, Test Merge Candidate

#1379 Adds more SDQL2 admin wrappers
  code/modules/admin/SDQL2/SDQL_2_wrappers.dm
Labels: Administration, Trivial

#1384 Fixes the fully_replace_character_name proc
  code/__HELPERS/unsorted.dm
Labels: Fix

#1312 Add automatic takeover for SSD xenos
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/game.dm
  code/modules/client/client_procs.dm
  code/modules/mob/dead/observer/logout.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/login.dm
  code/modules/mob/mob_helpers.dm
Labels: Feature

#1402 Fixes big red visual issues
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Map Edit

#1400 Updates the selector arrays to latest /tg/ version
  code/modules/admin/SDQL2/SDQL_2.dm
  code/modules/admin/SDQL2/SDQL_2_parser.dm
Labels: Administration

#1405 Adds /tg/ git hook tools, updates the mapmerge2 slightly
  .gitattributes
  tools/hooks/README.md
  tools/hooks/dmi.merge
  tools/hooks/install.bat
  tools/hooks/install.sh
  tools/hooks/pre-commit.hook
  tools/hooks/python.sh
  tools/mapmerge2/dmm.py
  tools/mapmerge2/update_paths.py
Labels: Tools

#1398 Adds job playtime restrictions.
  code/__DEFINES/jobs.dm
  code/game/gamemodes/distress.dm
  code/game/jobs/job/job_exp.dm
  code/game/jobs/job/marines.dm
  code/game/jobs/job/shipside.dm
  config/config.txt
Labels: Config Update, Tweak

#1395 Fixes xeno interaction with closets and crates.
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/crates_lockers/secure_crates.dm
Labels: Fix, Test Merge Candidate

#1372 Refactor queen follow topics
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
Labels: Refactor

#1407 Adds different satchel sprites for corpsman and engineer
  icons/obj/items/storage/storage.dmi
Labels: Sprites, Test Merge Candidate

#1381 Auto-9 Magazine Fix
  code/modules/projectiles/updated_projectiles/magazines/pistols.dm
Labels: Fix, Test Merge Candidate

#1383 Fixes the take over admin verb
  code/modules/admin/admin_verbs.dm
Labels: Administration

#1385 VV improvements: rotate, varedit updates, link to VV'd object
  code/modules/admin/verbs/datumvars.dm
  code/modules/admin/verbs/varedit.dm
Labels: Administration

#1386 Makes purrbation slightly less evil.
  code/modules/admin/verbs/datumvars.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Administration

#1406 Kills rogue pixel on hold order
  icons/mob/talk.dmi
Labels: Fix, Sprites

#1397 Fixes the rocket launcher backblast smoke being located on the user's turf.
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/projectiles/updated_projectiles/guns/specialist.dm
Labels: Fix, Test Merge Candidate

#1399 Fixes latejoin squad numbers
  code/game/jobs/squads.dm
Labels: Fix

#1401 Adds preference for window flashing
  code/__HELPERS/game.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
Labels: QoL

#1404 Add a few more stats
  code/modules/mob/mob.dm
Labels: Test Merge Candidate, Tweak

#1413 Fixes IV Drip
  code/game/machinery/iv_drip.dm
  code/modules/mob/living/blood.dm
Labels: Fix

#1424 Such is life
  config/config.txt
Labels: Config Update

#1410 Cleans up controller code that likely won't be used
  code/controllers/configuration/configuration.dm
  code/controllers/stonedmc/subsystem/mapping.dm
  code/game/world.dm
  code/modules/admin/holder.dm
  code/modules/admin/server_verbs.dm
Labels: Code Improvement

#1411 Adds the /tg/ runtime viewer
  code/__HELPERS/unsorted.dm
  code/controllers/configuration/entries/general.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/topic.dm
  code/modules/error_handler/error_handler.dm
  code/modules/error_handler/error_viewer.dm
  tgmc.dme
Labels: Config Update

#1412 Reverts HPR firing sound
  code/modules/projectiles/updated_projectiles/guns/rifles.dm
Labels: Revert, Sound
