Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2020-09, with the labels that each got.

#4754 storage creep be gone
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/modular_armor/storage.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Removal

#4755 baldur is no longer free, costs more in req
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#4752 Magmoor miners and guns
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Balance/Rebalance, Feature, Map Edit

#4756 Fixes autolathe material amount for metal and rods
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Fix

#4593 Windoor Recode + Req Windoors
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/MarineHQ/MarineHQ.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/desert/desert.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/shuttles/alamo.dmm
  _maps/shuttles/big_ert.dmm
  _maps/shuttles/distress.dmm
  _maps/shuttles/distress_pmc.dmm
  _maps/shuttles/distress_upp.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/machinery/doors/brigdoors.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/structures/windoor_assembly.dm
Labels: Code Improvement, Feature, Map Edit

#4620 Resin Structures on Ship Tiles & Catwalks + Girder Check
  code/__DEFINES/layers.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/structures/girders.dm
  code/game/turfs/plating.dm
  code/game/turfs/turf.dm
  code/modules/atmospherics/machinery/components/unary_devices/outlet_injector.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
Labels: Code Improvement

#4760 Nerf's ravager charge CD and raises the plasma cost
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Tweak

#4750 LZ Shutter Layout Rework + Big Red Cave Area Rename
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/area/bigred.dm
Labels: Feature, Map Edit, Tweak

#4751 New Ambience & Footsteps
  code/__DEFINES/footsteps.dm
  code/game/area/area.dm
  code/game/area/bigred.dm
  code/game/area/magmoor_digsite.dm
  code/game/objects/structures/lattice.dm
  code/game/turfs/floor_ground.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/open.dm
  code/game/turfs/open_ground.dm
  code/game/turfs/plating.dm
  code/game/turfs/snow.dm
  sound/ambience/ambiatmos.ogg
  sound/ambience/ambiatmos2.ogg
  sound/ambience/ambicave.ogg
  sound/ambience/ambilava1.ogg
  sound/ambience/ambilava2.ogg
  sound/ambience/ambilava3.ogg
  sound/ambience/ambitech.ogg
  sound/ambience/ambitech2.ogg
  sound/credits.txt
  sound/effects/footstep/concrete1.ogg
  sound/effects/footstep/concrete2.ogg
  sound/effects/footstep/concrete3.ogg
  sound/effects/footstep/concrete4.ogg
  sound/effects/footstep/concrete5.ogg
  sound/effects/footstep/ice1.ogg
  sound/effects/footstep/ice2.ogg
  sound/effects/footstep/ice3.ogg
  sound/effects/footstep/ice4.ogg
  sound/effects/footstep/ice5.ogg
  sound/effects/footstep/snow1.ogg
  sound/effects/footstep/snow2.ogg
  sound/effects/footstep/snow3.ogg
  sound/effects/footstep/snow4.ogg
  sound/effects/footstep/snow5.ogg
  sound/weapons/guns/fire/desktop.ini
Labels: Sound

#4745 Sulaco Pipes/Wires Rework + Area Layout Tweaks + Aesthetic Changes
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/turfs/floor_types.dm
  icons/turf/prison.dmi
Labels: Feature, Fix, Map Edit, Sprites, Tweak

#4748 Pillar of Spring Layout Changes
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Removal, Tweak

#4663 Use unrelenting force via keybind instead of just selecting
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Requires Testing, Test Merge Candidate, Tweak

#4773 PoS Surplus Vendor
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#4776 Actual PoS Fixes
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#4774 Fixes Ob exploit
  code/game/objects/structures/orbital_cannon.dm
Labels: Fix

#4775 fixes crawling through holes with shutters
  code/game/objects/effects/acid_hole.dm
Labels: Fix

#4742 Fixes aqua helms
  icons/mob/modular/modular_armor.dmi
Labels: Fix, Sprites

#4778 Buffs Incendiary OB fire into the same as X Fuel (Blue Fire) (This time not commited to master)
  code/game/objects/structures/orbital_cannon.dm
Labels: Balance/Rebalance

#4780 PoS Stuff (Again)
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Tweak

#4700 Synth Rebalance
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/datums/jobs/job/shipside.dm
  code/datums/skills.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/gimmick.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/modular_armor/storage.dm
  code/modules/reagents/reagents/other.dm
Labels: Balance/Rebalance, Feature, Requires Testing

#4735 Add savefile entry for missing keybindings
  code/modules/client/preferences_savefile.dm
Labels: Do Not TM

#4781 Prison APC/Area Fix
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Fix, Map Edit

#4792 Make precommit hooks more robust
  tools/hooks/dmi.merge
  tools/hooks/pre-commit.hook
  tools/hooks/python.sh
Labels: Tools

#4789 Sulaco 2 Electric Boogaloo
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  code/game/turfs/closed.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/walls/wall_types.dm
  icons/obj/structures/window_frames.dmi
  icons/obj/structures/windows.dmi
  icons/turf/mainship.dmi
  icons/turf/mainshipwalls.dmi
  icons/turf/shuttle.dmi
Labels: Feature, Fix, Map Edit, Removal, Sprites, Tweak

#4767 Bumpattacks no longer target mobs laying down
  code/datums/components/bump_attack.dm
Labels: Balance/Rebalance

#4740 PSG Auto Sniper
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Feature, Grammar and Formatting, Removal, Sprites

#4779 Soul clarification
  code/modules/mob/living/carbon/human/examine.dm
Labels: Tweak

#4712 Supply consoles are now locked properly
  code/modules/reqs/supply.dm
Labels: Balance/Rebalance, Fix

#4729 Modular Mapping
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/modularmaps/prison/civresbeach.dmm
  _maps/modularmaps/prison/civresgym.dmm
  code/controllers/subsystem/mapping.dm
  code/game/objects/effects/spawners/modularmappingspawner.dm
  code/modules/mapping/modular_mapping.dm
  tgmc.dme
Labels: Feature, Map Edit

#4807 Adds Gun fire and pump/bolt animations
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
  icons/Marine/gun64.dmi
  icons/obj/items/gun.dmi
Labels: Code Improvement, Feature, Sprites

#4806 Razorwire HP nerf
  code/__DEFINES/objects.dm
Labels: Balance/Rebalance, Test Merge Candidate

#4805 fixes combat carriers instantly hugging in melee
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  icons/Xeno/Effects.dmi
Labels: Fix, Sprites, Test Merge Candidate

#4800 Flamer changes
  code/game/objects/items/tools/maintenance_tools.dm
  code/modules/projectiles/guns/flamer.dm
Labels: Balance/Rebalance, Test Merge Candidate

#4795 (un)Borked jaeger and PAS armor values
  code/modules/clothing/suits/marine_armor.dm
  code/modules/modular_armor/armor_pieces.dm
  code/modules/modular_armor/modular.dm
Labels: Balance/Rebalance, Test Merge Candidate, Tweak

#4777 Removes magic armor
  code/datums/armor.dm
Labels: Code Improvement, Removal, Test Merge Candidate

#4783 Makes regenning walls slightly less bad
  code/controllers/subsystem/processing/slowprocess.dm
  code/game/turfs/walls/resin.dm
  tgmc.dme
Labels: Code Improvement, Test Merge Candidate

#4811 Sulaco Shutter Fix +Minor Changes
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit, Tweak

#4770 Bigbury follow-up
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/desert/desert.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/shuttles/tgs_bigbury.dmm
  code/modules/shuttle/gamemodes/crash.dm
Labels: Map Edit, Tweak

#4634 Tesla gun thing
  code/__DEFINES/conflict.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/datums/beam.dm
  code/datums/status_effects/debuffs.dm
  code/modules/codex/entries/ammunition_codex.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/projectile.dm
  code/modules/reqs/supplypacks.dm
  icons/effects/beam.dmi
  icons/obj/items/projectiles.dmi
  sound/weapons/guns/fire/tesla.ogg
  tgmc.dme
Labels: Feature, Sound, Sprites

#4734 Updates Requisitions Pricing
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplyexports.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature, Removal, Test Merge Candidate, Tweak

#4814 Pillar of Spring - Alcohol
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Feature, Map Edit

#4815 Nerfs crusher stomp by half damage but gives it a 2sec stun
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Balance/Rebalance

#4820 DMDoc will use typepaths
  SpacemanDMM.toml
Labels: Code Improvement

#4817 Table pixel offset
  code/game/objects/structures/tables_racks.dm
Labels: Feature, Test Merge Candidate

#4816 Gives first-aid injector pouch an unique sprite and makes first-aid pouch descriptions more accurate
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  icons/Marine/marine-pouches.dmi
Labels: Sprites, Tweak

#4812 Xeno scalping
  code/datums/elements/scalping.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/projectiles/gun_attachables.dm
  tgmc.dme
Labels: Feature

#4793 Buffs T-12's wield slowdown and adds angle grip to it's attachments
  code/modules/projectiles/guns/rifles.dm
Labels: Test Merge Candidate, Tweak

#4743 Removes ssping
  code/controllers/subsystem/ping.dm
  code/modules/admin/SDQL2/SDQL_2.dm
  tgmc.dme
Labels: Code Improvement, Removal, Test Merge Candidate

#4764 Gives a new sprite to most attachments and nerfs bc and buffs suppressor
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/Marine/marine-weapons.dmi
Labels: Balance/Rebalance, Sprites, Test Merge Candidate

#4668 Buff captain skills
  code/datums/skills.dm
Labels: Balance/Rebalance

#3909 Revised cloning
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/__DEFINES/jobs.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/objects.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/marines.dm
  code/datums/skills.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/cloning/cloning.dm
  code/game/objects/machinery/data_disks.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/reagents/reactions/medical.dm
  code/modules/reagents/reagents/cloning.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/machines/cloning.dmi
  tgmc.dme
Labels: Map Edit, Sprites

#4819 Adds a Memorial to the Sulaco
  _maps/map_files/Sulaco/Sulaco.dmm
  strings/tips/marine.txt
Labels: Feature, Map Edit, Removal, Test Merge Candidate

#4832 Sawn off no longer has a damage mult bonus
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance/Rebalance

#4829 Fixes Xeno Larva evolving to Tier 2+ castes by abusing regression. The reboot part IV.
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix, Test Merge Candidate

#4786 Burger's Attempt at a Xeno Regeneration Nerf
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance/Rebalance, Needs Balance Review, Requires Testing, Test Merge Candidate

#4844 Makes linter shut up by fixing it
  code/datums/emergency_calls/emergency_call.dm
Labels: Fix

#4851 Updates asset cache/CDN asset port
  code/__DEFINES/admin.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/_logging.dm
  code/__HELPERS/files.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/type2type.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/resources.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/assets.dm
  code/controllers/subsystem/mapping.dm
  code/datums/browser.dm
  code/game/objects/machinery/hologram.dm
  code/game/world.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/note_panel.dm
  code/modules/admin/panels/permission_panel.dm
  code/modules/admin/verbs/chat_commands.dm
  code/modules/admin/verbs/whitelist.dm
  code/modules/asset_cache/asset_cache_client.dm
  code/modules/asset_cache/asset_cache_item.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/asset_cache/readme.md
  code/modules/asset_cache/transports/asset_transport.dm
  code/modules/asset_cache/transports/webroot_transport.dm
  code/modules/asset_cache/validate_assets.html
  code/modules/client/asset_cache.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/emoji/emoji_parse.dm
  code/modules/language/language.dm
  code/modules/mob/mob.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/ert.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/tgui/external.dm
  code/modules/tgui/tgui.dm
  config/config.txt
  config/resources.txt
  tgmc.dme
  tools/localhost-asset-webroot-server.py
Labels: Config Update, Refactor, Tools

#4838 Buffs ERT helms/headpieces
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
Labels: Balance/Rebalance

#4859 Animated Muzzleflashes
  icons/obj/items/projectiles.dmi
Labels: Feature, Sprites

#4854 Text Emphasis (CitMain Port)
  code/datums/chatmessage.dm
  code/game/say.dm
  code/modules/mob/say.dm
Labels: Feature

#4823 More PoS Changes
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Tweak

#4830 Variety Update
  code/__DEFINES/__game.dm
  code/__DEFINES/radio.dm
  code/datums/emergency_calls/clf.dm
  code/datums/emergency_calls/colonists.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/emergency_calls/freelancers.dm
  code/datums/emergency_calls/imperium.dm
  code/datums/emergency_calls/pizza.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/emergency_calls/sectoid.dm
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/emergency_calls/upp.dm
  code/datums/emergency_calls/upp_commando.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/survivor.dm
  code/datums/jobs/job/xenomorph.dm
  code/game/communications.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/telecomms/machines/bus.dm
  code/game/objects/machinery/telecomms/machines/receiver.dm
  code/game/objects/machinery/telecomms/machines/server.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/flufftext/Dreaming.dm
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Feature, Fix, Grammar and Formatting, Removal, Tweak

#4875 Fixes Magmoor Crash
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Fix, Map Edit

#4809 Deployable Cams
  code/game/objects/machinery/camera/deployable_camera.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/machines/monitors.dmi
  tgmc.dme
Labels: Feature, Sprites, Test Merge Candidate

#4821 Dellog
  code/modules/admin/debug_verbs.dm
  code/modules/admin/holder.dm
Labels: Feature

#4842 Fixes weather damaging
  code/datums/weather/weather.dm
Labels: Fix

#4768 Adds a recoilless rifle, bag to carry the ammo and normal rockets
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/mob/ammoHUD.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
Labels: Feature, Sprites

#4845 Scalping fix
  code/datums/elements/scalping.dm
Labels: Fix

#4846 Fixes some invalid comments
  code/datums/skills.dm
  code/game/objects/effects/spawners/modularmappingspawner.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
Labels: Fix

#4848 STs can use req consoles again
  code/modules/reqs/supply.dm
Labels: Fix

#4849 dropship table will layer consistently and will relay clicks by powerloaders
  code/game/objects/structures/dropship_equipment.dm
Labels: Tweak

#4853 Field commanders can no longer use the smartgun effecitvely
  code/datums/skills.dm
Labels: Balance/Rebalance

#4862 Buckets can now be slashed
  code/game/objects/structures/misc.dm
Labels: Tweak

#4865 Captain, corpsmen, smartgunners, engineers and squadleads now have playtime based paygrades
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
Labels: Feature

#4866 Fixes defenders having bad names and spelling
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Fix

#4881 fixes pillar having destructible walls
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#4882 Replaces one of the ointments in the fire medkit with a leporazine packet
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pill_packets.dm
Labels: Feature, Test Merge Candidate

#4880 Removes legacy asset glob
  code/_globalvars/lists/client.dm
  code/modules/client/client_procs.dm
Labels: Fix, Removal, Test Merge Candidate

#4872 Adds Xeno Jelly and Jelly node hivelord abilities
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/_globalvars/bitfields.dm
  code/datums/keybinding/xeno.dm
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/projectiles/guns/flamer.dm
  icons/Xeno/resinpod.dmi
Labels: Feature, Fix, Sprites, Test Merge Candidate

#4864 Fixes space amazon denying your request across the mortal barrier
  code/controllers/subsystem/points.dm
Labels: Fix, Test Merge Candidate

#4863 Removes the last traces of rads
  code/__DEFINES/mobs.dm
  code/game/objects/items/scanners.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/life/handle_mutations_and_radiation.dm
  code/modules/mob/living/carbon/monkey/life.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/organs/organ_internal.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/reagents/reagents/alcohol.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/toxin.dm
  tgmc.dme
Labels: Removal, Test Merge Candidate

#4860 rolling buffer improvements
  code/__DEFINES/admin.dm
  code/controllers/subsystem/input.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/setup.dm
Labels: Feature, Fix, Test Merge Candidate, Tweak

#4877 Sulaco Dirt + SD
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Map Edit

#4899 Fixes screenwide red xenos
  code/game/objects/structures/xeno.dm
Labels: Fix

#4906 fixes officer cloaks not spawning in officer lockers
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
Labels: Fix

#4904 fixes offduty gamemode process
  code/datums/gamemodes/offduty.dm
Labels: Fix

#4901 Fixes linter throwing an error in a commented code block
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Fix

#4898 Adds an an to unrecognizable mess
  code/modules/organs/limbs.dm
Labels: Grammar and Formatting

#4894 Distress Victory Conditions
  code/datums/gamemodes/distress.dm
Labels: Balance/Rebalance

#4885 Icy Caves+
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/area/icy_caves.dm
Labels: Map Edit, Tweak

#4895 adds an autolathe to crash ships
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
Labels: Feature, Map Edit

#4902 fixes acting squad leaders not getting order abilities
  code/datums/jobs/squads.dm
Labels: Fix, Test Merge Candidate

#4891 Tweaks Xeno Leaders Hivemind messages to give them more size and authority
  code/modules/goonchat/browserOutput.css
  code/modules/goonchat/browserOutput_white.css
  code/modules/mob/living/carbon/xenomorph/say.dm
Labels: Test Merge Candidate, Tweak

#4909 adds generic marine radios, fixes uniform vendors not having marine radios and fixes squad huds not being removed on drop
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/masks/breath.dm
  icons/obj/items/radio.dmi
Labels: Fix, Sprites

#4884 Removes unnecessary pouches, adds medkit pouch and changes it.
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-pouches.dmi
Labels: Feature, Removal, Sprites, Tweak

#4888 Fixes orbiters glide_size not syncing with the orbit target, and fix breaking on xeno evo
  code/datums/components/orbiter.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix, Test Merge Candidate

#4908 asrs pad also includes embryos now
  code/game/objects/machinery/sellingpad.dm
Labels: Fix

#4903 Experimental maptick optimization
  code/game/atoms.dm
Labels: Code Improvement, Performance, Requires Testing

#4917 adds a new version of debugdalus
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
Labels: Feature, Map Edit

#4912 adds black vest to marine vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Tweak

#4918 Synth Armor Flag Fix
  code/modules/modular_armor/modular.dm
Labels: Fix

#4905 Fixes the big red "You are either AFK.." message showing when you are in fact not AFK and/or disconnected
  code/controllers/subsystem/ping.dm
  tgmc.dme
Labels: Fix

#4915 you can now switch binocular mode with altclick
  code/game/objects/items/binoculars.dm
Labels: Tweak

#4914 underbarrel attachments now dont deactivate on pb
  code/modules/projectiles/gun_system.dm
Labels: Tweak

#4922 Icy Caves++
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/area/icy_caves.dm
Labels: Map Edit, Tweak

#4896 improves the id console a lot, rebalances logistics access and makes access nicer
  code/__DEFINES/access.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/machinery/computer/marines_consoles.dm
  code/modules/recycling/conveyor2.dm
Labels: Balance/Rebalance, Fix, Tweak

#4916 Changes boiler zoom offset to be the same as the railscope.
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Tweak
