Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2020-11, with the labels that each got.

#5130 Nerfs dead marine headset cameras by allowing xenos to disable them like lights
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5128 Gives survivor a knife and hard hat
  code/datums/jobs/job/survivor.dm
  code/modules/clothing/head/hardhat.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5117 Makes Telsa gun Zaps stagger for 2 seconds and slow for 0.5 seconds
  code/datums/beam.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5137 Remove docker image generation
  .github/workflows/docker_publish.yml
Labels: GitHub

#4979 Adds a UI to the Mortar to decrease sanity loss in engineers
  code/game/objects/structures/mortar.dm
  tgui/packages/tgui/interfaces/Mortar.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, UI

#5008 Medvendor update
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Feature, Removal

#5132 Fix atom init issues
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/spawners/modularmappingspawner.dm
Labels: Code Improvement

#5129 Adds flechettes and mr-25s/m412s to the armories in lv and big red
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/LV624/LV624.dmm
Labels: Balance/Rebalance, Map Edit

#5139 Make xeno abilities easier to target
  code/__DEFINES/actions.dm
  code/_onclick/click.dm
  code/datums/actions/xeno_action.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Code Improvement, Feature

#5138 removes melee hard armor from shields, give them 50% soft melee
  code/game/objects/items/weapons/shields.dm
Labels: Balance/Rebalance, Removal

#5141 reduces shield durablity to 300
  code/game/objects/items/weapons/shields.dm
Labels: Balance/Rebalance

#5134 Gives pilots modern jumpsuit/flak/helmet sprites by j*ff
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Feature, Removal, Sprites

#5145 Removes RNG from light stick trampling for big mobs only (queen, crusher, etc..)
  code/game/objects/items/lightstick.dm
Labels: Removal, Tweak

#5135 replaces whatever the fp2000 masquarades as with a FAMAS
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  code/datums/jobs/job/freelancers.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/smgs.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Feature, Map Edit, Removal, Sprites

#5083 Metal barricades can now be upgraded
  code/game/objects/structures/barricade.dm
Labels: Feature, Test Merge Candidate

#4954 Cas Airplane
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/shuttles/casplane.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/dropship_equipment.dm
  code/_globalvars/bitfields.dm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/game/atoms.dm
  code/game/objects/machinery/computer/dropship_weapons.dm
  code/game/objects/machinery/telecomms/machines/relay.dm
  code/game/objects/structures/cas_plane_parts.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/turfs/closed.dm
  code/modules/shuttle/cas_plane.dm
  code/modules/shuttle/ert.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/shuttle/shuttle.dm
  icons/Marine/cas_plane_cockpit.dmi
  icons/Marine/cas_plane_engines.dmi
  icons/Marine/casship.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/MarineCasship.js
  tgui/packages/tgui/interfaces/Orbit.js
  tgui/packages/tgui/interfaces/PortableVendor.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Code Improvement, Feature, Map Edit, Sprites, UI

#5143 Allow xeno attack code to bypass shields
  code/__DEFINES/dcs/signals.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Code Improvement, Feature, Refactor

#5152 Hydrocodone changes, makes it actually work
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/modules/reagents/reagents/medical.dm
Labels: Balance/Rebalance, Fix

#5171 New Intel Computer Sprite + Minor Fixes/Tweaks
  code/__DEFINES/combat.dm
  code/game/objects/machinery/computer/intel_computer.dm
  icons/Xeno/2x2_Xenos.dmi
  icons/Xeno/resinpod.dmi
  icons/effects/effects.dmi
  icons/obj/machines/computer.dmi
Labels: Sprites

#5176 Adds new backpack sprites, replaces the old marine backpack sprites
  code/game/objects/items/storage/backpack.dm
  icons/mob/back.dmi
  icons/obj/items/storage/storage.dmi
Labels: Feature, Removal, Sprites

#5158 Replaces most pouch sprites
  icons/Marine/marine-pouches.dmi
Labels: Feature, Removal, Sprites, Test Merge Candidate

#5058 adds a req only way to make advanced chemicals, lemoline
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/modules/reagents/reactions/medical.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/chemistry.dmi
Labels: Balance/Rebalance, Feature, Sprites, Test Merge Candidate

#5089 Reworks armor modules minorly, adds lesser versions of baldur/mimir/tyr for free access
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/modular_armor/attachables.dm
  code/modules/modular_armor/helmets.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Feature, Test Merge Candidate

#5111 Minor lasgun rework, removes redundant fire mode and adds a new one
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
  icons/mob/ammoHUD.dmi
Labels: Balance/Rebalance, Feature, Removal, Sprites

#5142 makes the minimum age of marines 18
  code/__DEFINES/preferences.dm
Labels: Tweak

#5144 adds paracematol packets to all the ships
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Feature, Map Edit

#5178 Codex fluff move-about
  code/controllers/subsystem/codex.dm
  code/modules/codex/entries/guns_codex.dm
Labels: Tweak

#5186 tx-15/marine Autoshotgun can't be fired one handed anymore.
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#5191 Rank times standardisation, field commander max rank time fix (now actually functional)
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
Labels: Fix, Tweak

#5164 shields check runtime fix
  code/game/objects/items/coins.dm
  code/game/objects/items/misc.dm
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/stacks/snow.dm
  code/game/objects/items/tools/cleaning_tools.dm
  code/game/objects/items/tools/misc_tools.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/weapons/holo_weapons.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/objs.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/paperwork/clipboard.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/paper_bundle.dm
  code/modules/power/cable.dm
  code/modules/power/pipecleaners.dm
Labels: Fix

#5170 Adds T-19 ammo to supply pack
  code/modules/projectiles/ammunition.dm
  code/modules/reqs/supplypacks.dm
Labels: Fix

#5166 binoculars can no longer target things the user cannot see.
  code/game/objects/items/binoculars.dm
Labels: Fix

#5163 Synthetics can now get their blood back via nanopaste
  code/game/objects/items/stacks/nanopaste.dm
Labels: Fix

#5161 Makes the General Storage Module actually General
  code/modules/modular_armor/storage.dm
Labels: Fix

#5168 moves a viro closet over two tiles on Theseus
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Fix, Map Edit

#5167 powercells must be recharged before restocking them
  code/game/objects/machinery/vending/vending.dm
Labels: Balance/Rebalance

#5107 The Pickup Macro is made null for guns.
  code/modules/projectiles/gun_system.dm
Labels: Tweak

#5156 Breaking the legs of a massive broken monster from hell(bull) quickly.
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Balance/Rebalance

#5173 Sulaco Rework (Again)
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#5162 deletes pulse rifle firing sounds, changes it with a new firing sound
  code/game/sound.dm
  code/modules/projectiles/guns/rifles.dm
  sound/weapons/guns/fire/M412.ogg
  sound/weapons/guns/fire/m41a_1.ogg
  sound/weapons/guns/fire/m41a_2.ogg
  sound/weapons/guns/fire/m41a_3.ogg
  sound/weapons/guns/fire/m41a_4.ogg
  sound/weapons/guns/fire/m41a_5.ogg
  sound/weapons/guns/fire/m41a_6.ogg
Labels: Removal, Sound, Test Merge Candidate

#5032 Capture Rework
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/keybinding/xeno.dm
  code/datums/round_statistics.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items/defibrillator.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/examine.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/mob_grab.dm
  code/modules/mob/update_icons.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/Xeno/Effects.dmi
  icons/mob/actions.dmi
  icons/mob/alien.dmi
Labels: Do Not TM, Feature, Sprites

#5180 Resin Silo Corpse Fix
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix

#5084 Bodydragging is now a 2 Second timer on nonburst humans for xenos
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/mob.dm
Labels: Balance/Rebalance

#5199 Typepath fix for Hyronalin
  code/modules/reagents/reagents/medical.dm
Labels: Fix

#5174 Minor refactor of acid spray crossed
  code/game/objects/effects/aliens.dm
Labels: Refactor

#5207 Fixes Shrike fling bullying of nested infected hosts
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Fix

#5213 Removes light in wall on prison
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Fix, Map Edit

#5200 Intel comp fix
  icons/obj/machines/computer.dmi
Labels: Sprites

#5208 Fixes Bull losing headbite and headbutt abilities from aging
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
Labels: Fix

#5203 Prison Area Fix
  code/game/area/prison.dm
Labels: Fix

#5179 increases hivelord's heal range by 1, improves(?) acidic salve/psychic cure range code
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Test Merge Candidate, Tweak

#5193 Less Bright Lava
  code/game/turfs/open.dm
Labels: Balance/Rebalance

#5212 Removes the LZ 2 Phoron Miner on Prison
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Map Edit, Removal, Test Merge Candidate

#5169 Makes Carrier stunnable
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5172 Lowers shutter automatic opening to 30 minutes
  code/datums/gamemodes/game_mode.dm
Labels: Test Merge Candidate, Tweak

#5218 adds the cl briefcase to the sulaco/pos
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit, Test Merge Candidate

#5209 Refactor hivemind movement
  code/__DEFINES/dcs/signals.dm
  code/game/objects/effects/weeds.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Labels: Fix, Refactor, Test Merge Candidate, Tweak

#4943 Should allow People to make orders regardless of point cost
  tgui/packages/tgui/interfaces/Cargo.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Test Merge Candidate, Tweak, UI

#5236 Xenomorph caste documentation
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Fix

#5239 Re-Adds the Harness to the game, via surplus equipment vendor.
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/suits/marine_armor.dm
Labels: Feature

#5192 Neuraline cost increased by 1
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5202 More Sulaco Fixes
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#5216 Nerfs sentry turrets damage/health, buffs sunder
  code/game/objects/machinery/sentries.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5229 Implements a hardcap towards spawning AI
  code/_globalvars/lists/ai_nodes.dm
  code/datums/components/ai.dm
Labels: Tweak

#5098 ERT can no longer metarush SD
  code/__DEFINES/is_helpers.dm
  code/game/objects/machinery/self_destruct.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5234 Spilts pmcs from nt lorewise, and gives pmc gunner the modern smartgun
  code/datums/emergency_calls/pmc.dm
  code/datums/jobs/job/pmc.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance, Tweak

#5185 Fixes broken miniflamer and nerfs it too
  code/modules/projectiles/gun_attachables.dm
Labels: Balance/Rebalance, Fix, Test Merge Candidate

#5154 updates the sprites of some of the berets, adds a red and snow beret
  code/modules/client/preferences_gear.dm
  code/modules/clothing/head/head.dm
  icons/mob/head_1.dmi
  icons/obj/clothing/cm_hats.dmi
Labels: Do Not TM, Feature, Sprites, Tweak

#5270 *warcry
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/human_female_warcry_1.ogg
  sound/voice/human_female_warcry_2.ogg
  sound/voice/human_female_warcry_3.ogg
  sound/voice/human_female_warcry_4.ogg
  sound/voice/human_female_warcry_5.ogg
  sound/voice/human_female_warcry_6.ogg
  sound/voice/human_female_warcry_7.ogg
  sound/voice/human_female_warcry_8.ogg
  sound/voice/human_male_warcry_1.ogg
  sound/voice/human_male_warcry_10.ogg
  sound/voice/human_male_warcry_11.ogg
  sound/voice/human_male_warcry_12.ogg
  sound/voice/human_male_warcry_13.ogg
  sound/voice/human_male_warcry_14.ogg
  sound/voice/human_male_warcry_15.ogg
  sound/voice/human_male_warcry_16.ogg
  sound/voice/human_male_warcry_17.ogg
  sound/voice/human_male_warcry_18.ogg
  sound/voice/human_male_warcry_19.ogg
  sound/voice/human_male_warcry_2.ogg
  sound/voice/human_male_warcry_20.ogg
  sound/voice/human_male_warcry_21.ogg
  sound/voice/human_male_warcry_22.ogg
  sound/voice/human_male_warcry_3.ogg
  sound/voice/human_male_warcry_4.ogg
  sound/voice/human_male_warcry_5.ogg
  sound/voice/human_male_warcry_6.ogg
  sound/voice/human_male_warcry_7.ogg
  sound/voice/human_male_warcry_8.ogg
  sound/voice/human_male_warcry_9.ogg
Labels: Feature, Sound, Test Merge Candidate

#5153 Seperates the surplus equipment vendor into a clothing/armor vendor
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature, Map Edit, Test Merge Candidate

#5274 deletes gamer gear from cl briefcase
  code/game/objects/items/portable_vendor.dm
Labels: Fix

#5266 Hivemind Return to Core fix
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
Labels: Fix

#5259 adds a straw hat to tgmc, and gives it to clf
  code/datums/jobs/job/clf.dm
  code/modules/clothing/head/head.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/head_1.dmi
  icons/obj/clothing/cm_hats.dmi
Labels: Feature, Sprites

#5277 Removes Command Headsets from Lockers
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
Labels: Removal

#5231 Silo Point Adjustments
  code/modules/xenomorph/xeno_structures.dm
Labels: Test Merge Candidate, Tweak

#5268 RUSH B! to the new modular EORG arena.
  _maps/map_files/generic/Admin_Level.dmm
  _maps/modularmaps/EORG/de_dust2.dmm
  _maps/modularmaps/EORG/original.dmm
  code/game/objects/effects/spawners/modularmappingspawner.dm
  code/game/turfs/closed.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/mapping/modular_mapping.dm
Labels: Feature, Map Edit

#5256 Stun changes part 4 - warrior
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Balance/Rebalance

#5262 Even MORE Sulaco Changes
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Feature, Fix, Map Edit, Tweak

#5289 deletes cat ears
  _maps/map_files/desert/desert.dmm
  code/game/objects/effects/landmarks/itemspawner.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/misc_special.dm
  icons/mob/head_0.dmi
Labels: Map Edit, Removal, Sprites

#5198 Replaces Defiler's Neurotoxin sting with Reagent Slash, adds associated toxins, adds 2 new gasses, adds hud for xenos based on new toxins V2
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/conflict.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/datums/atom_hud.dm
  code/datums/keybinding/xeno.dm
  code/game/data_huds.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living.dm
  code/modules/reagents/reagents/toxin.dm
  icons/mob/actions.dmi
  icons/mob/hud.dmi
Labels: Feature, Removal, Sprites

#5280 Acid Wells No Longer Spawn Gas When Crushed by Dropship
  code/game/objects/structures/xeno.dm
Labels: Fix

#5273 deletes unused gun sprites
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/specialist.dm
  icons/obj/items/gun.dmi
Labels: Removal, Sprites

#5275 replaces the old belt sprites with new ones
  icons/obj/clothing/belts.dmi
Labels: Feature, Removal, Sprites

#5276 Improves *warcry
  code/game/sound.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/talk.dmi
  sound/voice/skeleton_warcry.ogg
Labels: Feature, Sound, Sprites, Tweak

#5233 30 minute Respawn (Again)
  code/_globalvars/admin.dm
Labels: Balance/Rebalance, Test Merge Candidate

#4707 Orbital drop pods
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/objects.dm
  code/_globalvars/lists/objects.dm
  code/game/area/mainship.dm
  code/game/area/sulaco.dm
  code/game/objects/machinery/computer/droppod_control.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/structures/droppod.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/shuttle/shuttle.dm
  icons/obj/structures/droppod.dmi
  sound/effects/droppod_impact.ogg
  sound/effects/droppod_launch.ogg
  tgmc.dme
  tgui/packages/tgui/interfaces/Droppod.js
  tgui/packages/tgui/interfaces/DroppodControl.js
  tgui/packages/tgui/interfaces/HiveEvolveScreen.js
  tgui/packages/tgui/interfaces/Sentry.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Map Edit, Sound, Sprites, Test Merge Candidate, UI

#5150 Make Camo Tarps Great Again
  code/__DEFINES/dcs/signals.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/marine_gear.dm
Labels: Refactor, Test Merge Candidate, Tweak

#5187 gives sentinel the ability to swap to light acid spit
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5288 fixes bigbury and sulaco not having an armor vendor
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/shuttles/tgs_bigbury.dmm
Labels: Fix, Map Edit

#5283 T71 now can take T12 attachments (excluding QF)
  code/modules/projectiles/guns/rifles.dm
Labels: Tweak

#5287 Fixes a surgery callback
  code/modules/surgery/surgery.dm
Labels: Fix

#5238 Headbite Changes
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance/Rebalance

#5292 make acid use process
  code/game/objects/effects/aliens.dm
Labels: Test Merge Candidate

#5194 Removes RNG and adds proper values and fixes abilities not checking armor accidentally.
  code/__DEFINES/mobs.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/structures/razorwire.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_health_procs.dm
Labels: Balance/Rebalance, Fix, Removal, Test Merge Candidate

#5302 Fixes Replacement Character bug
  code/__HELPERS/text.dm
Labels: Fix, Priority: CRITICAL

#5278 Add mobile_power component
  code/__DEFINES/dcs/signals.dm
  code/datums/components/mobile_power.dm
  code/game/objects/machinery.dm
  code/modules/power/port_gen.dm
  code/modules/power/power.dm
  dependencies.sh
  tgmc.dme
Labels: Feature, Test Merge Candidate

#5269 Making Stagger Great Again
  code/__DEFINES/conflict.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
Labels: Test Merge Candidate, Tweak

#5296 removes most of the garbage warcry emotes
  code/game/sound.dm
  sound/voice/human_female_warcry_2.ogg
  sound/voice/human_female_warcry_3.ogg
  sound/voice/human_female_warcry_4.ogg
  sound/voice/human_female_warcry_5.ogg
  sound/voice/human_female_warcry_6.ogg
  sound/voice/human_female_warcry_7.ogg
  sound/voice/human_female_warcry_8.ogg
  sound/voice/human_male_warcry_10.ogg
  sound/voice/human_male_warcry_11.ogg
  sound/voice/human_male_warcry_12.ogg
  sound/voice/human_male_warcry_13.ogg
  sound/voice/human_male_warcry_14.ogg
  sound/voice/human_male_warcry_15.ogg
  sound/voice/human_male_warcry_16.ogg
  sound/voice/human_male_warcry_17.ogg
  sound/voice/human_male_warcry_18.ogg
  sound/voice/human_male_warcry_19.ogg
  sound/voice/human_male_warcry_20.ogg
  sound/voice/human_male_warcry_21.ogg
  sound/voice/human_male_warcry_22.ogg
  sound/voice/human_male_warcry_3.ogg
  sound/voice/human_male_warcry_4.ogg
  sound/voice/human_male_warcry_5.ogg
  sound/voice/human_male_warcry_6.ogg
  sound/voice/human_male_warcry_7.ogg
  sound/voice/human_male_warcry_8.ogg
  sound/voice/human_male_warcry_9.ogg
Labels: Removal, Sound, Test Merge Candidate

#5281 Resin Structures Not Blocked by Non-Nest Beds/Obstacles Easier to Clear
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/turf.dm
Labels: Fix, Test Merge Candidate, Tweak

#5290 Improved Hive Information
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Feature

#5279 Quick Cades, Barricade Anchoring and Barbed Wire Respect No Construction
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/items/quickdeploy_cade.dm
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/structures/barricade.dm
Labels: Fix

#5291 update timer subsystem and fixes a bug
  code/__DEFINES/_subsystems.dm
  code/__HELPERS/_lists.dm
  code/controllers/subsystem/runechat.dm
  code/controllers/subsystem/timer.dm
  code/game/world.dm
Labels: Fix, Priority: CRITICAL

#5248 Shield Fix
  code/datums/components/shield.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/shields.dm
Labels: Tweak

#5305 Fixes new lints detected by the spacemandmm update
  code/__DEFINES/objects.dm
  code/game/objects/items/bodybag.dm
Labels: Fix, Priority: High

#5252 Stun changes part 1- shrike
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5258 Stun changes part 6- queen
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5299 nerfs tanglefoot/drain gas avaliablity substansiaually and ups the detonation time
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5314 Linting annotation
  .github/workflows/test.yml
Labels: Code Improvement, Git-hub, Git.hUb, GitHub

#5316 Should not sleep initialize and destroy and should call parent initialize
  code/datums/datum.dm
  code/game/atoms.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/space.dm
  code/game/turfs/turf.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/mob.dm
Labels: Code Improvement

#5307 Invisimins can no longer be orbited
  code/__HELPERS/unsorted.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder.dm
Labels: Administration, Fix

#5284 0 length timer linting
  code/controllers/configuration/configuration.dm
  code/modules/power/cable.dm
  tools/ci/check_grep.sh
Labels: Code Improvement, Tools

#5272 sends panther to the shadowrealm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/_globalvars/lists/mobs.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/round_statistics.dm
  code/game/objects/structures/misc.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/reqs/supplyexports.dm
  icons/Xeno/2x2_Xenos.dmi
  tgmc.dme
Labels: Removal, Sprites, Test Merge Candidate

#5265 Removes warriors default ctrlclick override
  code/__DEFINES/dcs/signals.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Removal, Test Merge Candidate, Tweak

#5264 Fixes xeno health overlays layering strange
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Fix, Test Merge Candidate

#5308 deletes marine vest sprite
  icons/mob/suit_1.dmi
Labels: Removal, Sprites

#5297 nerfs lz2 on big red
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Balance/Rebalance, Map Edit, Test Merge Candidate

#3434 Spaceship Orbits
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/mode.dm
  code/datums/gamemodes/distress.dm
  code/datums/wires/spaceship.dm
  code/game/objects/structures/orbital_cannon.dm
  code/modules/orbits/spaceship.dm
  code/modules/shuttle/marine_dropship.dm
  icons/obj/machines/computer.dmi
  tgmc.dme
Labels: Feature, Map Edit, Sprites, Test Merge Candidate

#5326 Init sanity unit test
  code/controllers/subsystem/atoms.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/initialize_sanity.dm
Labels: Code Improvement

#5332 fixes if can put stronger acid check that was reversed due to #5292 changes.
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#5322 Tweak new Hive Status health color to be less red all the time
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Tweak

#5300 Replaces the M37A2 with the V10 (sprite only)
  code/game/objects/items/storage/large_holster.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/gun.dmi
Labels: Removal, Sprites, Tweak

#5295 Changes the pistol sprite of the 88mod/M1911 and replaces the M4A3
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/clothing/under/ties.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/pistols.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Feature, Map Edit, Removal, Sprites, Tweak

#5350 Fixes acid going too fast and some check
  code/game/objects/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix, Priority: High

#5341 Fixes cades being unable to be secured with wrench
  code/game/objects/structures/barricade.dm
Labels: Fix

#5337 Fixes Infinite Metal From Crowbarring Anchored Metal Barricades
  code/game/objects/structures/barricade.dm
Labels: Fix, In Game Exploit

#5244 Updates the database
  .dockerignore
  .github/workflows/test.yml
  BSQL.dll
  Dockerfile
  SQL/database_changelog.txt
  SQL/tgmc-schema.sql
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/bsql.config.dm
  code/__DEFINES/bsql.dm
  code/__HELPERS/text.dm
  code/_globalvars/lists/mobs.dm
  code/_globalvars/misc.dm
  code/controllers/configuration/entries/dbconfig.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/dbcore.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/stickyban.dm
  code/datums/atom_hud.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/job/job_exp.dm
  code/game/world.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/ban_panel.dm
  code/modules/admin/panels/note_panel.dm
  code/modules/admin/panels/permission_panel.dm
  code/modules/admin/panels/poll_panel.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/create_poll.dm
  code/modules/admin/verbs/poll_managment.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/bsql/LICENSE
  code/modules/bsql/core/connection.dm
  code/modules/bsql/core/library.dm
  code/modules/bsql/core/operation.dm
  code/modules/bsql/core/query.dm
  code/modules/bsql/includes.dm
  code/modules/client/client_procs.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/poll.dm
  config/config.txt
  config/dbconfig.txt
  dependencies.sh
  html/IRV/jquery-ui.custom-core-widgit-mouse-sortable-min.js
  html/browser/admin_panels.css
  html/browser/admin_panels_css3.css
  tgmc.dme
  tools/ci/build_bsql.sh
  tools/ci/run_server.sh
Labels: Administration, Config Update, Do Not TM, Fix, GitHub, Refactor, SQL, Tools

#5351 tx-15 one hnaded fix
  code/modules/projectiles/guns/rifles.dm
Labels: Fix

#5334 Barefoot step runtime fix
  code/game/turfs/open.dm
  code/game/turfs/plating.dm
Labels: Fix

#5257 Stun changes part 5 - Ravager
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5254 Stun changes part 3- Runner
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5267 nerfs ballistic/acid barricade armor upgrade and nerfs plasteel hp by 100
  code/game/objects/structures/barricade.dm
Labels: Balance/Rebalance, Test Merge Candidate, Tweak

#5315 Improves sound procs
  code/__HELPERS/ai.dm
  code/_globalvars/lists/mobs.dm
  code/controllers/subsystem/server_maint.dm
  code/game/sound.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Code Improvement, Test Merge Candidate

#5235 Capture Removal
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Removal, Tweak

#5223 Ports advanced shuttle landing from tg and adds a dropship using this feature to the Sulaco and Pillar
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/shuttles/minidropship.dmm
  code/__DEFINES/layers.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/game/objects/structures/dropship_equipment.dm
  code/modules/shuttle/gamemodes/crash.dm
  code/modules/shuttle/mini_dropship.dm
  code/modules/shuttle/navigation_computer.dm
  code/modules/shuttle/shuttle.dm
  icons/mecha/actions_mecha.dmi
  tgmc.dme
Labels: Feature, Map Edit, Sprites

#5367 Fixes player polls runtime
  code/modules/mob/new_player/new_player.dm
Labels: Fix, Priority: High

#5368 Fixes undeleted query
  code/datums/gamemodes/game_mode.dm
Labels: Fix

#5237 gun_attachables documentation
  code/modules/projectiles/gun_attachables.dm
Labels: Fix, Stale

#5344 Fixes xeno_action's add_cooldown() sanity check to prevent 0 length timers
  code/datums/actions/xeno_action.dm
Labels: Fix

#5345 removes unused/pointless guns part 1
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/desert/desert.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/__DEFINES/mode.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/shotguns.dm
  code/modules/projectiles/magazines/smgs.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/gun.dmi
Labels: Map Edit, Removal, Sprites

#5383 Fixes Bug With Bodybag Improves Serial Number Gen
  code/game/objects/items/bodybag.dm
Labels: Fix, Refactor, Tweak

#5331 Add filter helpers
  code/__HELPERS/cmp.dm
  code/__HELPERS/icons.dm
  code/game/atoms.dm
  code/game/objects/structures/xeno.dm
Labels: Code Improvement

#5352 Fixes Defiler gas prompts wording, Improves Select Reagent description
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Labels: Feature, Tweak

#5388 Ports TG timer thing
  code/controllers/subsystem/timer.dm
Labels: Code Improvement

#5385 Fixes bad code in tarps
  code/game/objects/items/bodybag.dm
Labels: Code Improvement

#5159 QoL Improvements for Hivelord Tunnels
  code/__DEFINES/atom_hud.dm
  code/datums/atom_hud.dm
  code/game/atoms.dm
  code/game/data_huds.dm
  code/game/objects/objs.dm
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
Labels: Fix, Refactor, Tweak

#5217 Drone's Salvage Plasma Reworked into Salvage Biomass
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/keybinding/xeno.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Feature, Test Merge Candidate

#5319 Tweaks for Spits That Drop Residual Effects
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Fix

#5375 Acid spray Duration fix.
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Code Improvement, Fix

#5323 Activating flare automatically puts you in throw mode
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/flashlight.dm
Labels: Tweak

#5311 Minor ice edits
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Map Edit, Removal
