Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2020-01, with the labels that each got.

#3618 Small gun description fixes
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Grammar and Formatting

#3617 puts ciggies on the cant
  _maps/shuttles/tgs_canterbury.dmm
Labels: Feature, Map Edit

#3612 Tweak for pump action shotgun ammo hud
  code/modules/projectiles/guns/shotguns.dm
Labels: Tweak

#3608 Drone salving
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Feature

#3614 Small gun rebalance v2
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance, Test Merge Candidate

#3621 Updated Ammo hud for the lasgun
  code/modules/projectiles/ammo_datums.dm
  icons/mob/ammoHUD.dmi
Labels: Feature, Sprites

#3623 Changes Description
  code/modules/projectiles/magazines/rifles.dm
Labels: Grammar and Formatting, Trivial

#3576 Add balance tracking
  code/__DEFINES/components.dm
  code/__DEFINES/is_helpers.dm
  code/datums/balance.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  tgmc.dme
Labels: Feature

#3611 Removes acid blood from all Xenos except boilers
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Balance/Rebalance, Removal

#3622 Delete unused/broken maps
  _maps/WIP/Z.01.Desert-Dam.dmm
  _maps/_basemap.dm
  _maps/map_files/Marine_ball/Marine_ball.dmm
  _maps/map_files/Port_Hamburg/Port_Hamburg.dmm
  _maps/port_hamburg.json
  config/maps.txt
Labels: Config Update, Map Edit

#3566 adds remote FOB construction
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/components.dm
  code/datums/jobs/job/marines.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/barricade.dm
  code/modules/mining/remote_fob/remote_fob_actions_misc.dm
  code/modules/mining/remote_fob/remote_fob_computer.dm
  code/modules/mining/remote_fob/remote_fob_fobdrone.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/shuttle/shuttle.dm
  icons/Marine/remotefob.dmi
  sound/machines/terminal_insert_disc.ogg
  tgmc.dme
Labels: Feature, Map Edit, Sound, Sprites

#3616 Adds the Heat lens to the M43 lasgun
  code/datums/gamemodes/distress.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/energy.dm
  icons/Marine/marine-weapons.dmi
Labels: Balance/Rebalance, Feature, Requires Testing, Sprites

#3619 New Crash landing spots
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/desert/desert.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Feature, Map Edit, Removal, Requires Testing, Test Merge Candidate, Tweak

#3620 Crusher Armor nerf
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Labels: Balance/Rebalance, Requires Testing

#3596 Adds in QuikDeploy:tm: barricades
  code/game/objects/items/quickdeploy_cade.dm
  icons/obj/items/quikdeploy_cade.dmi
  tgmc.dme
Labels: Feature, Requires Testing, Sprites

#3635 Minorly changes the description on lasgun lenses.
  code/modules/projectiles/gun_attachables.dm
Labels: Grammar and Formatting

#3637 Removes custom CSS
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserOutput.js
Labels: Removal

#3634 Fixes the attack animation with weapons against living
  code/_onclick/item_attack.dm
Labels: Fix

#3641 New Player Panel: Current Character
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/mob/new_player/new_player.dm
Labels: Tweak

#3649 Removes the Spatial Agent glasses tint
  code/modules/clothing/glasses/glasses.dm
Labels: Removal, Tweak

#3642 Adds a Admin-Only Commissar job and equipment
  code/datums/jobs/job/imperium.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/hands.dmi
  icons/mob/head_1.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/mob/suit_1.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/items/weapons.dmi
Labels: Feature, Sprites

#3592 New mob: Xeno Hivemind
  code/__DEFINES/components.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/patterns.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/xeno/hivemind.dm
  code/_onclick/hud/xeno/larva.dm
  code/_onclick/hud/xeno/xeno.dm
  code/_onclick/xeno.dm
  code/datums/actions/xeno_action.dm
  code/datums/keybinding/xeno.dm
  code/game/data_huds.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/shards.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/machinery/sentries.dm
  code/game/objects/structures/ladders.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/mob/living/silicon/ai/freelook/chunk.dm
  icons/Xeno/weeds.dmi
  icons/mob/actions.dmi
  icons/mob/cameramob.dmi
  tgmc.dme
Labels: Feature, Requires Testing, Sprites

#3639 Adds the T series pistol/revolver/shotgun/autoshotgun and some stuff
  code/datums/gamemodes/distress.dm
  code/datums/supplypacks.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  sound/weapons/guns/fire/t35.ogg
  sound/weapons/guns/fire/tp14.ogg
  sound/weapons/guns/interact/tp14_reload.ogg
Labels: Balance/Rebalance, Feature, Requires Testing, Sound, Sprites, Tweak

#3628 Observe Typo Fix
  code/modules/mob/new_player/new_player.dm
Labels: Fix

#3631 Carbine Tweaks + Aim Slowdown Changes.
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance/Rebalance, Test Merge Candidate, Tweak

#3645 Ports Emotes for OOC and Dsay
  code/game/verbs/ooc.dm
  code/modules/client/asset_cache.dm
  code/modules/emoji/emoji_parse.dm
  code/modules/mob/say.dm
  icons/misc/emoji.dmi
  tgmc.dme
Labels: Feature, Sprites

#3654 Upgrade pygit2 dependency to v1.0.1
  tools/mapmerge2/requirements.txt
Labels: Tools

#3656 Some changes suggested by lummox
  code/modules/client/message.dm
  code/modules/keybindings/bindings_client.dm
Labels: Priority: CRITICAL

#3650 TGS refs refactor
  code/__DEFINES/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/ban_panel.dm
  code/modules/admin/panels/note_panel.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/admin/verbs/chat_commands.dm
  code/modules/client/client_defines.dm
Labels: Refactor

#3661 Ports map popups and movement tracker
  code/__DEFINES/components.dm
  code/__HELPERS/matrices.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/map_popups.dm
  code/datums/components/orbiter.dm
  code/datums/movement_detector.dm
  code/game/objects/effects/proximity.dm
  code/game/objects/items/devices/spyglasses.dm
  code/game/objects/items/storage/storage.dm
  code/modules/client/client_defines.dm
  icons/mob/map_backgrounds.dmi
  icons/obj/clothing/accessories.dmi
  interface/skin.dmf
  tgmc.dme
Labels: Sprites

#3329 Boiler rework
  code/__DEFINES/components.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  icons/Xeno/actions_boiler_glob.dmi
Labels: Sprites, Tweak

#3555 TGB - "Rising Star" Ultra Low Pop Map
  _maps/_basemap.dm
  _maps/map_files/MarineHQ/MarineHQ.dmm
  _maps/risingstar.json
  code/datums/gamemodes/offduty.dm
  code/game/objects/machinery/floodlight.dm
  code/game/turfs/open.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/magazines/energy.dm
  config/shipmaps.txt
Labels: Administration, Config Update, Feature, Fix, Map Edit

#3664 Ports the character policy and IC word filter
  code/__DEFINES/__game.dm
  code/__DEFINES/admin.dm
  code/__HELPERS/config.dm
  code/__HELPERS/text.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/ping.dm
  code/game/verbs/ooc.dm
  code/modules/goonchat/browserOutput.dm
  code/modules/goonchat/browserOutput.js
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  config/in_character_filter.txt
  config/policy.json
  tgmc.dme
Labels: Config Update

#3651 Icon and gun fixes.
  code/game/objects/items.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  icons/mob/items_righthand_0.dmi
Labels: Priority: High, Sprites

#3660 remove unreachable code
  code/controllers/subsystem/timer.dm
  code/datums/components/squeak.dm
  code/datums/datum.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/gamemodes/crash.dm
  code/datums/wires/_wires.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/computer/camera_console.dm
  code/modules/admin/verbs/centcom_podlauncher.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/datum_pipeline.dm
  code/modules/mob/inventory.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/reagents/Chemistry-Holder.dm
  code/modules/reagents/chemistry_reagents/toxin.dm
  code/modules/shuttle/escape_pod.dm
Labels: Code Improvement

#3142 Radial Menu Bandages
  code/__DEFINES/mobs.dm
  code/__DEFINES/preferences.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/radial/radial_body_select.dm
  code/modules/surgery/surgery.dm
  icons/mob/radial.dmi
  tgmc.dme
Labels: Feature, Requires Testing, Sprites, Test Merge Candidate
