Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2020-12, with the labels that each got.

#5394 Fixes a typo
  code/modules/reagents/reagents/alcohol.dm
Labels: Grammar and Formatting

#5353 Fixes T2 and T3 Hive Status Limit Calcs
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#5400 Makes retreating a xeno minor
  code/datums/gamemodes/distress.dm
Labels: Tweak

#5370 reduces cas cost for ammo overall and ds surgery table cost
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
Labels: Balance/Rebalance

#5306 Shield Slowdown Now Works
  code/datums/components/shield.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5398 Slight buff to the T-18 carbine by giving it 4 more bullets
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance/Rebalance

#5401 Snow Clear Time Improved for Xenos
  code/game/turfs/snow.dm
Labels: Tweak

#5403 Fixes Lying Angles for Buckled/Unbuckled Living Mobs
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Fix

#5339 Making Sticky Resin Great Again
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Tweak

#5391 Larva now get to see what is outside the silo before spawning
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Feature

#5321 Gun Cabinet tweak
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
Labels: Tweak

#5312 makes the OB inbound sound prettier and more obvious
  code/game/objects/machinery/overwatch.dm
  code/game/objects/structures/orbital_cannon.dm
  sound/effects/OB_warning_announce.ogg
  sound/effects/OB_warning_announce_novoiceover.ogg
  sound/effects/obfire.ogg
Labels: Balance/Rebalance, Feature, Sound

#5420 Fixes hijack bugs with giving xeno burrowed on hijacking to achieve xeno/marine ratio, also makes silos not break on launching hijacked ship.
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix, Tweak

#5425 airburst() runtime fix. fixes #5362
  code/modules/projectiles/projectile.dm
Labels: Fix

#5415 changes to the orbits mechanic
  code/modules/orbits/spaceship.dm
Labels: Feature, Tweak

#5390 Improves Crusher Crest Toss backwards tossibility checks
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Fix

#5393 Removes 4s lock on Defiler's Transvitox reagent's effect
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Balance/Rebalance

#5392 Shrapnel and bonebreaks actually do damage now.
  code/game/objects/items/embedding.dm
  code/modules/mob/living/carbon/human/life/handle_organs.dm
Labels: Balance/Rebalance

#5412 Adds more bandannas to Surplus / Adds squad headsets to Ops Vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#5396 Allow the designation of "non-repeatable" weather types (perpetual acid rain fix)
  code/controllers/subsystem/weather.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/sand_storm.dm
Labels: Code Improvement

#5241 Adds mining well upgrades(Ready)
  code/game/objects/items/misc.dm
  code/game/objects/machinery/autolathe_datums.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/machinery/sellingpad.dm
  code/modules/reqs/supplyexports.dm
  code/modules/requisitions/_supply_export.dm
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/items.dmi
  icons/obj/mining.dmi
  icons/obj/mining_drill.dmi
Labels: Feature, Sprites

#5242 Reworks IFF code, Gives Aim Mode to select rifles
  code/__DEFINES/conflict.dm
  code/__DEFINES/movespeed_modification.dm
  code/_globalvars/bitfields.dm
  code/datums/actions/item_action.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/machinery/sentries.dm
  code/game/objects/machinery/smartgun_mount.dm
  code/modules/codex/entries/ammunition_codex.dm
  code/modules/codex/entries/guns_codex.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/multitile/hardpoints.dm
  icons/mob/hud.dmi
Labels: Feature, Refactor, Sprites

#5221 New Runner Ability: Evasion
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/datums/round_statistics.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  icons/mob/actions.dmi
Labels: Feature, Sprites, Test Merge Candidate

#5366 Making Lasrifle Overcharge Great Again
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5372 Changes Hivemind Collapse timer to be longer in cases where more time is needed, not less
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance/Rebalance, Test Merge Candidate, Tweak

#5409 Tadpole Map Rework
  _maps/shuttles/minidropship.dmm
  code/game/turfs/open.dm
Labels: Balance/Rebalance, Map Edit

#5419 droppods have coolsprites
  icons/obj/structures/droppod.dmi
Labels: Feature, Sprites

#5395 Tox heal chems diversified
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pill_packets.dm
  code/modules/reagents/reagents/medical.dm
Labels: Balance/Rebalance, Grammar and Formatting

#5397 Shield Intercept Ratio Fixed
  code/datums/components/shield.dm
Labels: Fix, Test Merge Candidate, Tweak

#5446 Fix CI failure
  .github/workflows/test.yml
  tools/ci/check_grep.sh
Labels: GitHub, Tools

#5429 Removes the limit on Resin Silo construction, and lowers the cooldown
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance/Rebalance, Removal

#5225 Add requirement to autodoc new procs and vars to Contributing.md
  .github/CONTRIBUTING.md
Labels: Git-hub, Git.hUb, GitHub

#5389 Zoom optimizing.
  code/__DEFINES/dcs/signals.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/mob.dm
  code/modules/modular_armor/helmets.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
Labels: Refactor

#5435 Keyloop microopt
  code/modules/keybindings/bindings_atom.dm
Labels: Code Improvement, Performance

#5436 Optimimization pass on get_hearers_in_view
  code/game/say.dm
Labels: Code Improvement, Performance

#5437 Optimized get_hear()
  code/__HELPERS/game.dm
Labels: Code Improvement, Performance

#5438 Optimizes getviewsize()
  code/__HELPERS/view.dm
Labels: Code Improvement, Performance

#5443 Bug Fix for Sentries
  code/__DEFINES/objects.dm
  code/game/objects/machinery/sentries.dm
Labels: Code Improvement, Fix

#5440 Nerfs lasgun overcharge
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#5451 fixes problem of reverse giving larva on hijack.
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#5444 Adds Evasion Keybinds and Fixes Minor Evasion Bug
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Fix

#5452 Prevents a single pill from crippling both your arms.
  code/modules/organs/limbs.dm
Labels: Fix

#5430 Adds the Salvage Biomass ability to Hivelord
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
Labels: Feature, Test Merge Candidate

#5431 Removes dead huds
  code/__DEFINES/atom_hud.dm
  code/datums/atom_hud.dm
  code/game/data_huds.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/silicon/ai/multicam.dm
Labels: Code Improvement, Removal

#5456 Fixes Crusher Crest Toss buckle issue and visual feedback oversight
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Fix

#5455 Autoburst no longer more accurate than burst
  code/modules/projectiles/gun_system.dm
Labels: Fix

#5461 makes acid use Slow process instead of standard process
  code/game/objects/effects/aliens.dm
Labels: Code Improvement

#5484 Auto-punctuation.
  code/datums/emotes.dm
  code/modules/mob/living/say.dm
Labels: Feature

#5481 Gives scope a few fixes.
  code/game/objects/items.dm
  code/modules/modular_armor/helmets.dm
  code/modules/projectiles/gun_attachables.dm
Labels: Fix

#5478 Makes all xenos use movable light, fixes fire and acid glob glow not showing.
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/living_defense.dm
Labels: Code Improvement, Fix

#5482 Acid Wells and Hugger Traps Are Properly Deleted by Shuttle Crushing
  code/game/objects/structures/xeno.dm
Labels: Fix

#5488 Minor cleanup of beds and chairs
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
Labels: Code Improvement

#5489 Cleans up Move() and Signal defines slightly
  code/__DEFINES/dcs/signals.dm
  code/game/objects/effects/effect_system/particle_effects.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/machinery/pipe/construction.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/window.dm
  code/modules/vehicles/cargo_train.dm
Labels: Code Improvement

#5490 Refactors item actions to a lazylist, documentation and deprecation pass
  code/__DEFINES/objects.dm
  code/__HELPERS/unsorted.dm
  code/datums/actions/item_action.dm
  code/game/objects/items.dm
  code/game/objects/items/shards.dm
  code/game/objects/items/weapons/weaponry.dm
  code/game/objects/structures/xeno.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/modular_armor/modular.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Code Improvement, Refactor

#5470 Turns Ice Caves into their own areas on Ice colony , Gives them the deep underground flag.
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  code/game/area/icecolony.dm
  icons/turf/areas.dmi
Labels: Balance/Rebalance, Fix, Map Edit, Sprites, Test Merge Candidate

#5471 Fixes tadpole being able to land in bigred caves
  code/game/area/bigred.dm
Labels: Balance/Rebalance, Fix, Test Merge Candidate

#5472 Fixes tadpole being able to land in underground buildings on magmoor
  code/game/area/magmoor_digsite.dm
Labels: Fix, Test Merge Candidate

#5486 Transfer Plasma Doesn't X-Fer More Than Target Needs + Cool SFX
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  icons/effects/effects.dmi
Labels: Sprites, Test Merge Candidate, Tweak

#5433 Fixes T3 Limit Displays for the Hive Status
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix, Refactor

#5497 Makes hostile AI ever so slightly faster.
  code/modules/mob/living/simple_animal/hostile/hostile.dm
Labels: Code Improvement

#5498 Fix server votes probably
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
Labels: Fix, Priority: High

#5499 fixes deadchat not muting properly locally
  code/__HELPERS/mobs.dm
Labels: Fix

#5493 Fixes Xeno overwatch of numbers and space containing names, and delayed hud update
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#5483 Conveyor refactor attempt 2
  code/game/objects/machinery/autolathe_datums.dm
  code/modules/recycling/conveyor2.dm
  icons/obj/recycling.dmi
Labels: Refactor, Sprites, Test Merge Candidate

#5492 Refactors various overlays to use the correct proc and fixes turret overlays performing like trash
  code/game/objects/items/binoculars.dm
  code/game/objects/items/portable_vendor.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/tools/shovel_tools.dm
  code/game/objects/machinery/fire_alarm.dm
  code/game/objects/machinery/kitchen/gibber.dm
  code/game/objects/machinery/sentries.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/game/objects/structures/janicart.dm
  code/modules/power/smes.dm
Labels: Code Improvement, Fix, Performance, Refactor, Test Merge Candidate

#4669 Powerfist
  code/game/objects/items/weapons/misc.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/weapons.dmi
  sound/weapons/energy_blast.ogg
  sound/weapons/fistclamp.ogg
  sound/weapons/fistunclamp.ogg
Labels: Feature, Sound, Sprites, Test Merge Candidate

#5421 Warrior Rework and Bug Fix
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/game/objects/machinery/autolathe.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/power/apc.dm
  icons/mob/actions.dmi
Labels: Feature, Fix, Refactor, Sprites

#5504 fixes xenos ctrl click starting to grab humans on distance.
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#5503 Optimizes getallcontents and splits it into 2 procs
  code/__HELPERS/unsorted.dm
Labels: Code Improvement, Performance

#5511 Minor Bug Fix; Removes Unused Vars
  code/game/objects/structures/barricade.dm
Labels: Fix, Removal

#5522 Fixes Minor Bug With Barbed Barricades
  code/game/objects/structures/barricade.dm
Labels: Fix

#5533 deletes skirts
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/game/objects/effects/landmarks/itemspawner.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform_0.dmi
Labels: Map Edit, Removal, Sprites

#5513 Fixes some logged issues
  code/_onclick/hud/radial.dm
  code/datums/chatmessage.dm
  code/game/turfs/walls/resin.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/say.dm
Labels: Fix

#5462 Fixes Phantom/Disappearing Mini-Sentry Cells and Reformats Deactivation
  code/game/objects/machinery/sentries.dm
Labels: Code Improvement, Fix

#5523 Fixes PMC sniper IFF
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#5538 [s] Fixes dbrank exploit
  code/modules/admin/panels/permission_panel.dm
Labels: Fix, Priority: High

#5539 Update garbage
  code/controllers/subsystem/garbage.dm
Labels: Code Improvement, Performance

#5325 Areas with FOB shutters can no longer be weeded with closed shutters
  code/__DEFINES/__game.dm
  code/__DEFINES/area.dm
  code/game/area/area.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/turfs/turf.dm
  tgmc.dme
Labels: Balance/Rebalance

#5507 Stamina projectiles no longer trigger FF limit
  code/modules/projectiles/projectile.dm
Labels: Tweak

#5517 Un-hardcodes and refactors icon drawing for update_inv(), removes hardcoded icon files
  code/__DEFINES/equipment.dm
  code/__HELPERS/_lists.dm
  code/game/objects/items.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/under.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/modular_armor/armor_pieces.dm
  code/modules/modular_armor/attachables.dm
  code/modules/modular_armor/modular.dm
  code/modules/modular_armor/storage.dm
  code/modules/projectiles/gun_system.dm
  icons/mob/modular/modular_armor.dmi
  icons/mob/modular/modular_armor_modules.dmi
  icons/mob/modular/modular_arms.dmi
  icons/mob/modular/modular_helmet.dmi
  icons/mob/modular/modular_helmet_icon.dmi
  icons/mob/modular/modular_legs.dmi
Labels: Code Improvement, Refactor, Sprites

#5532 fist sprite change
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/weapons.dmi
Labels: Sprites, Tweak

#5544 Fixes Aim Mode fire rate debuff bypass.
  code/modules/projectiles/gun_system.dm
Labels: Fix

#5540 Fixes Req-orderable Watertanks + M16 Surplus Ammo + Fultons
  code/modules/reqs/supplypacks.dm
Labels: Fix

#5527 Fixes Serial Number Not Properly Setting for Deployed Camo Tarps
  code/game/objects/items/bodybag.dm
Labels: Fix

#5534 Fixes Phantom Cells for Powerloaders
  code/modules/vehicles/powerloader.dm
Labels: Fix

#5479 CanPass Refactor Imported From TG
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/misc.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/machinery/OpTable.dm
  code/game/objects/machinery/computer/HolodeckControl.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/game/objects/machinery/doors/railing.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/machinery/line_nexter.dm
  code/game/objects/machinery/spaceheater.dm
  code/game/objects/objs.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/platforms.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  code/game/turfs/turf.dm
  code/game/turfs/walls/resin.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/mob_movement.dm
  code/modules/recycling/disposal.dm
Labels: Refactor, Test Merge Candidate

#5506 Added Grapple Toss Keybind; Improved Grapple Toss Implementation
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Code Improvement, Tweak

#5558 ERT Shuttles now have a 'proper' windup and depart
  code/modules/shuttle/ert.dm
Labels: Fix

#5561 Makes head reattach surgery work properly
  code/modules/surgery/headreattach.dm
Labels: Fix

#5562 makes the corner CL bookcase accessible on Sulaco
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#5551 Fixes runtime's associated with Dropship Operating Tables
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#5554 Fixes the FC vendor
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Fix

#5567 flamer fire refactor
  code/modules/projectiles/guns/flamer.dm
Labels: Refactor

#5550 Changes all typepaths of russianRed into russian_red
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reagents/reagents/medical.dm
Labels: Fix

#5526 Canterbury Update With New Layout, Extra Vendors, and Removed Obsolete Section.
  _maps/shuttles/tgs_canterbury.dmm
Labels: Map Edit, Tweak

#5553 Adds the Lagcheck command
  code/modules/admin/server_verbs.dm
  code/modules/admin/verbs/chat_commands.dm
Labels: Code Improvement, Feature

#5577 Fixes canterbury spaces
  _maps/shuttles/tgs_canterbury.dmm
Labels: Map Edit, Priority: High

#5571 moved the Toggle_Middle/Shift Clicking from IC verb to GamePref
  code/__DEFINES/preferences.dm
  code/_onclick/click.dm
  code/datums/actions/xeno_action.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Do Not TM, Tweak

#5502 Saved recipes persist through rounds
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Do Not TM, Tweak

#5581 Allthehypo
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Feature

#5560 Only external physical damage should damage objects
  code/game/objects/obj_defense.dm
Labels: Fix

#5557 Xenos can no long buckle humans into OpTables
  code/game/objects/machinery/OpTable.dm
Labels: Fix

#5589 Windoor Collision Fix
  code/game/objects/machinery/doors/windowdoor.dm
Labels: Fix

#5594 makes orbit menu not close when choosing something to follow.
  code/modules/mob/dead/observer/orbit.dm
Labels: Tweak

#5586 Ai node expansion finish
  code/__DEFINES/nodes.dm
  code/__HELPERS/ai.dm
  code/controllers/subsystem/nodes.dm
  code/datums/elements/pathfinder.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/carbon/xeno/xeno.dm
  code/modules/ai/effect_node.dm
Labels: Refactor

#5611 Revert "Only external physical damage should damage objects"
  code/game/objects/obj_defense.dm
Labels: Fix, Priority: CRITICAL, Requires Testing, Revert, Test Merge Candidate

#5588 PFC cas flare
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Tweak

#5518 Fire Now Melts Snow Stacks
  code/game/turfs/snow.dm
Labels: Feature

#5601 Fix Xeno Silo Fog and Tunnels blocking passage of headbit/headless marines
  code/game/objects/effects/misc.dm
  code/game/objects/structures/xeno.dm
Labels: Fix

#5552 ERT Fix
  _maps/shuttles/distress.dmm
  _maps/shuttles/distress_pmc.dmm
  _maps/shuttles/distress_ufo.dmm
  _maps/shuttles/distress_upp.dmm
  code/game/objects/machinery/doors/airlock_types.dm
  code/modules/shuttle/ert.dm
Labels: Fix, Map Edit
