Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2020-08, with the labels that each got.

#4471 Jerrycan
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/__DEFINES/dcs/signals.dm
  code/_onclick/item_attack.dm
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/game/objects/items/reagent_containers/jerrycan.dm
  tgmc.dme
Labels: Feature, Map Edit

#4573 FCVendor
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  code/__DEFINES/access.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Feature, Map Edit

#4585 Fixes small issues on pillar
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#4582 Ports runechat subsystem from TG
  code/__DEFINES/_subsystems.dm
  code/__HELPERS/_lists.dm
  code/controllers/subsystem/runechat.dm
  code/controllers/subsystem/timer.dm
  code/datums/chatmessage.dm
  tgmc.dme
Labels: Feature

#4629 Prison Map Fix
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Fix, Map Edit

#4602 Field commander changes.
  code/datums/jobs/job/shipside.dm
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/items/weapons/blades.dm
  icons/mob/belt.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/storage/storage.dmi
  icons/obj/items/weapons.dmi
Labels: Balance/Rebalance, Feature, Sprites

#4632 Updates g8 desc
  code/game/objects/items/storage/belt.dm
Labels: Fix

#4633 Hunters can no longer give hallucinations to dead bodies
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Fix

#4604 Allows synths to use the hydro cannon
  code/modules/projectiles/gun_attachables.dm
Labels: Tweak

#4349 Modular helmet binocs
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items.dm
  code/modules/modular_armor/helmets.dm
Labels: Feature

#4636 Wow more fixes Prison Edition
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Fix, Map Edit

#4644 Lv shutter fix
  _maps/map_files/LV624/LV624.dmm
Labels: Fix, Map Edit

#4597 Fixes wording when toggle looc
  code/modules/admin/server_verbs.dm
Labels: Fix

#4583 Adds 50 more health to every beno but runner, adds 10 slash damage to ravager
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Labels: Balance/Rebalance, Not a code change

#4580 A number of fixes related to huggers
  code/game/atoms.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#4344 Adds the mirage grenade
  code/game/objects/items/devices/mirage.dm
  code/game/objects/machinery/vending/marine_vending.dm
  tgmc.dme
Labels: Feature

#4649 Add buckled signal to the medievac bed
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix

#4586 Readd xeno playtime
  code/datums/jobs/job/job.dm
Labels: Fix

#4657 Hotfix for the thing
  code/game/objects/items.dm
Labels: Bug, In Game Exploit

#4607 Plantable Flags
  code/game/objects/items/plantable_flags.dm
  icons/obj/items/plantable_flag.dmi
  tgmc.dme
Labels: Feature, Sprites

#4654 Jerry cans will pour on resin better
  code/game/objects/items/reagent_containers/jerrycan.dm
Labels: Fix

#4646 Spatial agent tweaks
  code/datums/jobs/job/other.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  icons/mob/head_0.dmi
  icons/mob/suit_0.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites, Tweak

#4369 Adds Events and the Intel collection random event
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/events.dm
  code/__HELPERS/admin.dm
  code/__HELPERS/game.dm
  code/_globalvars/lists/objects.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/events.dm
  code/game/objects/machinery/computer/intel_computer.dm
  code/modules/admin/holder.dm
  code/modules/admin/topic.dm
  code/modules/events/_events.dm
  code/modules/events/intel_computer.dm
  code/modules/security_levels/keycard_authentication.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/IntelComputer.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Config Update, Feature, Map Edit, UI

#4642 Cleans up some refs
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/organs/limbs.dm
  code/modules/organs/organ_internal.dm
Labels: Fix

#4648 Fix defib sprites
  icons/obj/items/items.dmi
Labels: Fix, Sprites

#4655 Fix crash nuke
  code/datums/gamemodes/crash.dm
Labels: Fix

#4640 Adds overlay for modular helmet
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/modular_armor/helmets.dm
  code/modules/modular_armor/modular.dm
  icons/mob/modular/modular_helmet_attachment.dmi
Labels: Feature, Sprites

#4616 Adds in a new crash shuttle for 25+ pop
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Tyson_Station/Tyson_Station.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/desert/desert.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/shuttles/tgs_bigbury.dmm
  code/datums/gamemodes/crash.dm
  code/datums/shuttles.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/modules/shuttle/gamemodes/crash.dm
Labels: Feature, Map Edit, Tweak

#4675 Heavy Helmet
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/head/helmet.dm
Labels: Feature

#4660 Ports deadchat_broadcast
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/preferences.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/bitfields.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggles.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/say.dm
Labels: Refactor

#4672 Remove the unbuckle signal after you medevac
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix

#4677 Qdel macro fixes
  code/__HELPERS/qdel.dm
Labels: Fix

#4656 Better cooldown macros
  code/__DEFINES/cooldowns.dm
  code/_onclick/human.dm
  code/_onclick/telekinesis.dm
  code/datums/components/bump_attack.dm
  code/datums/components/suit_autodoc.dm
  code/datums/datum.dm
  code/datums/emotes.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items.dm
  code/game/objects/items/restraints.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/iv_drip.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/taste.dm
  code/modules/modular_armor/modular.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/recycling/disposal.dm
Labels: Code Improvement

#4615 NV scopes
  code/modules/projectiles/gun_attachables.dm
  icons/Marine/marine-weapons.dmi
Labels: Feature, Sprites

#4670 Tools can be held in engi jaegers
  code/modules/modular_armor/storage.dm
Labels: Balance/Rebalance

#4592 Nerf plasma regen
  code/__DEFINES/mobs.dm
  code/_globalvars/bitfields.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance/Rebalance

#4664 Correctly set ground trait on maps
  code/datums/map_config.dm
  code/modules/mapping/space_management/traits.dm
Labels: Fix

#4650 Fixes runtimes related to atom proccalls and null wounds
  code/modules/admin/debug_verbs.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#4601 Nerfs the pacman
  code/modules/power/port_gen.dm
Labels: Balance/Rebalance, Not a code change

#4687 Revolver Rail light pixel fix
  code/modules/projectiles/guns/revolvers.dm
Labels: Fix

#4667 Add outfit buildmode
  code/__HELPERS/unsorted.dm
  code/_globalvars/misc.dm
  code/datums/outfit.dm
  code/modules/buildmode/submodes/delete.dm
  code/modules/buildmode/submodes/outfit.dm
  icons/misc/buildmode.dmi
  tgmc.dme
Labels: Administration, Sprites

#4704 Sulaco Pipenet Fix
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#4665 Removes FC SG (again(again)) and adds tazers to POS
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Balance/Rebalance, Map Edit, Removal

#4617 Escape pod tgui
  code/modules/shuttle/escape_pod.dm
  tgui/packages/tgui/interfaces/EscapePod.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, UI

#4641 New helmet module, makes helmet modules available, add descriptions
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/modular_armor/helmets.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature, Fix

#4643 Removes a duplicate proc
  code/__HELPERS/game.dm
  code/game/objects/items/explosives/grenades/flashbang.dm
Labels: Code Improvement, Removal

#4709 Nukes Tyson from orbit
  _maps/_basemap.dm
  _maps/map_files/Tyson_Station/Tyson_Station.dmm
  _maps/tyson_station.json
  code/game/area/tyson_station.dm
  config/maps.txt
  tgmc.dme
Labels: Config Update, Map Edit, Removal

#4645 Weather
  _maps/bigred_v2.json
  _maps/ice_colony_v2.json
  _maps/icy_caves.json
  _maps/lv624.json
  code/__DEFINES/maps.dm
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/weather.dm
  code/datums/looping_sounds/weather_sounds.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/datums/weather/weather_types/sand_storm.dm
  code/datums/weather/weather_types/snow_storm.dm
  code/game/area/area.dm
  code/game/area/areas/shuttles.dm
  code/game/area/bigred.dm
  code/game/area/general.dm
  code/game/area/icecolony.dm
  code/game/area/icy_caves.dm
  code/game/area/lava_outpost.dm
  code/game/area/lv624.dm
  code/game/area/port_hamburg.dm
  code/game/area/research_outpost.dm
  code/game/area/vaporprocessing.dm
  code/game/area/whiskeyoutpost.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/items/scanners.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_movement.dm
  icons/effects/weather_effects.dmi
  sound/weather/acidrain/acidrain_end.ogg
  sound/weather/acidrain/acidrain_mid.ogg
  sound/weather/acidrain/acidrain_start.ogg
  sound/weather/ashstorm/inside/active_end.ogg
  sound/weather/ashstorm/inside/active_mid1.ogg
  sound/weather/ashstorm/inside/active_mid2.ogg
  sound/weather/ashstorm/inside/active_mid3.ogg
  sound/weather/ashstorm/inside/active_start.ogg
  sound/weather/ashstorm/inside/weak_end.ogg
  sound/weather/ashstorm/inside/weak_mid1.ogg
  sound/weather/ashstorm/inside/weak_mid2.ogg
  sound/weather/ashstorm/inside/weak_mid3.ogg
  sound/weather/ashstorm/inside/weak_start.ogg
  sound/weather/ashstorm/outside/active_end.ogg
  sound/weather/ashstorm/outside/active_mid1.ogg
  sound/weather/ashstorm/outside/active_mid2.ogg
  sound/weather/ashstorm/outside/active_mid3.ogg
  sound/weather/ashstorm/outside/active_start.ogg
  sound/weather/ashstorm/outside/weak_end.ogg
  sound/weather/ashstorm/outside/weak_mid1.ogg
  sound/weather/ashstorm/outside/weak_mid2.ogg
  sound/weather/ashstorm/outside/weak_mid3.ogg
  sound/weather/ashstorm/outside/weak_start.ogg
  tgmc.dme
Labels: Code Improvement, Feature, Map Edit, Sound, Sprites

#4692 Revert "Nerfs the DMR/BR/SNIPER damage. Nerfs BR/Bolt action rifle damage"
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Revert

#4696 Adds paladin to req weapons vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#4666 Makes fireman carry easier
  code/datums/skills.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Tweak

#4685 Add a new floor (industrial
  code/game/turfs/floor_types.dm
  icons/turf/industrial.dmi
Labels: Feature, Sprites

#4738 Mimir helmet fix
  code/modules/reqs/supplypacks.dm
Labels: Fix

#4710 Fixes paygrade texts
  code/game/say.dm
Labels: Fix

#4714 Fixes weather gibbing and other handy tweaks
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/datums/weather/weather_types/sand_storm.dm
Labels: Balance/Rebalance, Fix

#4718 Assorted modular helmet fixes
  code/modules/modular_armor/helmets.dm
Labels: Fix

#4730 Ports various runechat stuff
  code/__DEFINES/layers.dm
  code/datums/chatmessage.dm
  code/modules/mob/mob.dm
  code/modules/mob/say.dm
Labels: Feature, Fix

#4658 Xeno IC names
  code/modules/admin/panels/mode_panel.dm
  code/modules/admin/topic.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/login.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Administration, Feature

#4721 Area cleanup
  code/game/area/area.dm
  code/game/area/bigred.dm
  code/game/area/centcom.dm
  code/game/area/general.dm
  code/game/objects/machinery/doors/firedoor.dm
Labels: Code Improvement

#4719 Fixes conveyors
  code/modules/recycling/conveyor2.dm
Labels: Fix

#4562 Ship Supplies Rebalance
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Balance/Rebalance, Feature, Map Edit, Removal

#4569 SG nvgs no longer have effective night vision.
  code/modules/clothing/glasses/night.dm
Labels: Balance/Rebalance

#4587 PFC paygrades based on playtime
  code/datums/jobs/job/job_exp.dm
  code/datums/jobs/job/marines.dm
Labels: Feature, Test Merge Candidate

#4731 Razorwire can no longer be healed when it is at full/cleanup
  code/game/objects/structures/razorwire.dm
Labels: Code Improvement, Fix

#4711 Ports agressive changelog
  code/controllers/configuration/entries/game_options.dm
  code/modules/client/client_procs.dm
  config/config.txt
Labels: Config Update, Feature

#4722 Adds more cover to lv
  _maps/map_files/LV624/LV624.dmm
  code/game/area/lv624.dm
Labels: Balance/Rebalance, Map Edit, Test Merge Candidate

#4741 Fixes paygrades on comms
  code/game/say.dm
Labels: Fix

#4689 Adds a bluespace selling pad for requisitions
  code/game/objects/machinery/sellingpad.dm
  code/modules/reqs/supplypacks.dm
  code/modules/requisitions/_supply_export.dm
  tgmc.dme
Labels: Feature, Sprites

#4697 Xeno tackle normalizing
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Labels: Balance/Rebalance, Needs Balance Review, Requires Testing
