Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2020-03, with the labels that each got.

#3675 Dress Hat
  icons/mob/head_0.dmi
  icons/obj/clothing/hats.dmi
Labels: Feature, Removal, Sprites

#3674 Changed icons and ID's
  icons/mob/order_icons.dmi
  icons/obj/items/card.dmi
Labels: Feature, Removal, Sprites

#3676 Redid the target sprite
  icons/mob/actions.dmi
Labels: Feature, Removal, Sprites

#3683 harness buff
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance/Rebalance, Tweak

#3682 MP Uniforms, Dress Uniform Fix, and Order Sprite fix.
  icons/mob/actions.dmi
  icons/mob/order_icons.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/machines/library.dmi
  icons/obj/machines/vending.dmi
Labels: Sprites

#3681 Adds the ability for the M43 to use railscopes
  code/modules/projectiles/guns/energy.dm
Labels: Balance/Rebalance, Tweak

#3680 Adds a miniscope to the armament vendor.
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Balance/Rebalance

#3677 smg now does 5 round burst
  code/modules/projectiles/guns/smgs.dm
Labels: Balance/Rebalance, Needs Balance Review

#3673 Some Pillar things.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Feature, Map Edit

#3658 Whitelist, stickybans and db and admin stuff
  code/__DEFINES/admin.dm
  code/_globalvars/lists/admin.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/dbcore.dm
  code/controllers/subsystem/stickyban.dm
  code/game/world.dm
  code/modules/admin/IsBanned.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/ban_panel.dm
  code/modules/admin/stickyban.dm
  code/modules/admin/verbs/whitelist.dm
  code/modules/client/client_procs.dm
  tgmc.dme
Labels: Config Update

#3684 Nerfs Boiler to no longer be an insane glob machine
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Needs Balance Review

#3685 Neuroclaws
  code/__DEFINES/components.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance/Rebalance

#3687 Fix UI color when sanitizing hexcolors
  code/modules/client/preferences_savefile.dm
Labels: Fix

#3688 Synths don't scream
  code/game/objects/effects/aliens.dm
Labels: Fix

#3699 Armor and Fatigues update
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/head_1.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_1.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Balance/Rebalance, Fix, Sprites

#3700 Revert "Armor and Fatigues update"
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/head_1.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_1.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Revert, Sprites

#3692 Fix xenos throwing people into disposals
  code/modules/recycling/disposal.dm
Labels: Fix

#3678 Fleccheteman
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Needs Balance Review

#3694 Theseus Map Changes v2
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit
