Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2020-06, with the labels that each got.

#4137 Plasma transfer and salvaging buffs
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance/Rebalance

#4164 [Map Edit Fix] Fixing Sulaco's Medbay Exit
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#4155 Allow Ripley to lift vendors, closets, and tanks
  code/modules/vehicles/powerloader.dm
Labels: Fix, Tweak

#4138 fixes razorwire not working and nerfs it
  code/game/objects/structures/razorwire.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Balance/Rebalance, Fix

#4165 [Map Edit Fix] Fixing WO Vendors
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
Labels: Fix, Map Edit

#4088 Big supply rework; Self serve req, refillable ammo boxes, better miners
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Tyson_Station/Tyson_Station.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/desert/desert.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/datums/gamemodes/distress.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/tools/misc_tools.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammunition.dm
  icons/obj/items/storage/storage.dmi
Labels: Balance/Rebalance, Feature, Fix, Map Edit, Sprites, Tweak

#4123 Makes carrier trap more visible
  icons/Xeno/Effects.dmi
Labels: Sprites

#4170 Adds the TP-23
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/pistols.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/gun.dmi
  sound/weapons/guns/fire/tp23.ogg
Labels: Balance/Rebalance, Feature, Sound, Sprites

#3928 Removes MPs
  _maps/map_files/MarineHQ/MarineHQ.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/jobs.dm
  code/datums/datacore.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/extended.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/shipside.dm
  code/datums/skills.dm
  code/game/objects/effects/landmarks/gamemode/crash_spawns.dm
  code/game/objects/effects/landmarks/marine_spawns.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/fax.dm
  code/modules/admin/topic.dm
Labels: Map Edit, Removal

#4177 Moves a crash marker on Sulaco so it isn't in space
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#4180 Fixes snake bandana sprite
  icons/mob/head_1.dmi
Labels: Fix, Sprites

#4169 Mimir no longer gives you effecive acid and bio immunity, slows down a bit less.
  code/modules/modular_armor/attachables.dm
Labels: Balance/Rebalance

#4168 Wall Armor Reduction
  code/game/turfs/walls/walls.dm
Labels: Tweak

#4152 Nerfs Shotgun Slugs
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#4153 Slight Rav speed and health nerf
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
Labels: Balance/Rebalance, Fix, Test Merge Candidate

#4150 Drone to Queen
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
Labels: Tweak

#4134 Xenomorph Acid Well
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  icons/Xeno/acid_pool.dmi
Labels: Feature, Removal, Sprites

#4144 Prae is faster, has better pheros early
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
Labels: Balance/Rebalance

#4133 Frenzy Reduction
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance/Rebalance

#3912 [DO NOT REMOVE THIS FROM TEST MERGES] Add some debugging info for shuttles
  code/__HELPERS/_logging.dm
  code/_globalvars/logging.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/shuttle.dm
  code/game/world.dm
  code/modules/shuttle/shuttle.dm
Labels: Priority: CRITICAL, Requires Testing

#4182 Adds the TP-17 pocket pistol for marines. And changes light pistol bullet and adds an AP version.
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/pistols.dm
  icons/mob/ammoHUD.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Balance/Rebalance, Feature, Sprites

#4185 [Map Fix] WO Signs and Windoor
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
Labels: Fix, Map Edit

#4172 Rifle family has been re-statted, carbine and lmg have been reworked.
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#4162 Fixes xeno powered door check
  code/game/objects/machinery/doors/airlock.dm
Labels: Fix

#4160 Ricochet ammo for the 357
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/projectiles/projectile.dm
Labels: Feature

#4157 Panther Buff
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/abilities_panther.dm
  code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
Labels: Feature, Test Merge Candidate, Tweak

#4117 Queen Fixes And Buffs
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Balance/Rebalance, Feature, Test Merge Candidate

#4188 TP-23 now has a belt sprite for being in your holster belt.
  icons/obj/clothing/belts.dmi
Labels: Fix, Sprites

#4198 Adds modular helmets to req vendors and helmets.
  code/datums/supplypacks.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#4189 DMR no longer has weird aimslowdown values.
  code/modules/projectiles/guns/rifles.dm
Labels: Fix

#4184 heavy armor modular chest piece slowdown nerfed from .4 to .6
  code/modules/modular_armor/armor_pieces.dm
Labels: Balance/Rebalance

#4190 Adds new T-39 combat shotgun and balances some other other shotguns
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/Marine/gun64.dmi
  icons/Marine/lasrifle.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
Labels: Balance/Rebalance, Sprites

#4131 Some lasgun changes, mostly upping heat lens fire delay and nerfing the damage on the main projectile by 5.
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
Labels: Balance/Rebalance

#4212 Removes legcuff code
  code/__DEFINES/conflict.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/equipment.dm
  code/__DEFINES/mobs.dm
  code/datums/components/shield.dm
  code/game/objects/items.dm
  code/game/objects/items/implants/implantfreedom.dm
  code/game/objects/items/legcuffs.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/monkey/inventory.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/update_icons.dm
  code/modules/organs/limbs.dm
  tgmc.dme
Labels: Code Improvement, Removal

#4206 Xenos can increase the chances generators fail
  code/modules/power/groundmap_geothermal.dm
Labels: Feature

#4204 Adds modular colors
  code/game/objects/items/cosmetics.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/modular_armor/armor_pieces.dm
  code/modules/modular_armor/modular.dm
  icons/mob/modular/modular_armor.dmi
Labels: Feature, Sprites

#4167 Adds some spawn content to whiskey and fixes some ai nodes
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  code/game/objects/structures/supports.dm
  config/maps.txt
  tgmc.dme
Labels: Config Update, Map Edit

#4215 Adds a new DMR sprite, changes some stats on it. Remakes old DMR into a BR.
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  sound/weapons/guns/fire/BR.ogg
Labels: Balance/Rebalance, Feature, Removal, Sound, Sprites

#4024 should fix shuttle explosions
  code/controllers/subsystem/explosions.dm
  code/modules/shuttle/on_move.dm
Labels: Fix, Test Merge Candidate

#4213 Deletes ravenger
  code/modules/mob/living/carbon/xenomorph/castes/ravenger/ravenger.dm
  tgmc.dme
Labels: Removal

#4216 Adds a keybind for the rest verb.
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/carbon.dm
Labels: Feature

#4192 Tweaks facehugger stun
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Balance/Rebalance

#4101 Refactors supply exports
  code/controllers/subsystem/points.dm
  code/modules/reqs/supply.dm
  code/modules/reqs/supplyexports.dm
  code/modules/reqs/supplypacks.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/Cargo.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Code Improvement, Refactor, UI

#4214 Makes the tp-44 and tp-19 no longer clip while in pistol belts
  icons/obj/clothing/belts.dmi
Labels: Fix, Sprites

#4229 Makes bioscan code hugely faster
  code/_globalvars/lists/mobs.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/living_health_procs.dm
Labels: Code Improvement, Performance, Refactor

#4227 Fix non hull pillar windows
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#4230 Load shuttles in transit level
  code/__HELPERS/unsorted.dm
  code/controllers/subsystem/shuttle.dm
Labels: Code Improvement

#4183 [Practice] Surgery
  _maps/map_files/MarineHQ/MarineHQ.dmm
  code/game/area/centcom.dm
  code/game/objects/machinery/practice/medical.dm
  tgmc.dme
Labels: Feature, Map Edit

#4210 Fixes dropship attachment acid removal exploit and an error message
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#4142 [Map] Lava Outpost
  _maps/_basemap.dm
  _maps/lava_outpost.json
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  code/__DEFINES/is_helpers.dm
  code/game/area/lava_outpost.dm
  code/game/turfs/closed.dm
  code/game/turfs/open.dm
  config/maps.txt
  icons/turf/areas.dmi
  icons/turf/lava.dmi
  tgmc.dme
Labels: Config Update, Feature, Map Edit, Sprites

#4217 Remove spec skill requirements from guns
  code/__DEFINES/skills.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#4202 [Map Edit] Sulaco Walls/Hulls Change
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/turfs/walls/wall_types.dm
Labels: Fix, Map Edit, Test Merge Candidate

#4222 Updates reagents to /tg/ standard
  code/__HELPERS/cmp.dm
  code/game/objects/empulse.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/Chemistry-Reactions.dm
  code/modules/reagents/colors.dm
  code/modules/reagents/holder.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/machinery/pandemic.dm
  code/modules/reagents/machinery/reagentgrinder.dm
  code/modules/reagents/reactions.dm
  code/modules/reagents/reactions/food_drink.dm
  code/modules/reagents/reactions/medical.dm
  code/modules/reagents/reactions/other.dm
  code/modules/reagents/readme.md
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/alcohol.dm
  code/modules/reagents/reagents/drink.dm
  code/modules/reagents/reagents/food.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/toxin.dm
  tgmc.dme
Labels: Code Improvement

#4233 Ports ghost orbit TGUI from tg
  code/_onclick/hud/ghost.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/orbit.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/Orbit.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, UI

#4239 switch some GLOBs to zlevel lists
  code/__HELPERS/ai.dm
  code/__HELPERS/game.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/shuttle/shuttle.dm
Labels: Code Improvement

#4238 [Fix] LO Catwalk, Basalt Barricades. Buttons
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/machinery/door_control.dm
Labels: Fix, Map Edit

#4228 Standardizes cases (on letters) and changes some descriptions
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/modular_armor/armor_pieces.dm
  code/modules/modular_armor/modular.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/flamer.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/shotguns.dm
  code/modules/projectiles/magazines/smgs.dm
  code/modules/projectiles/magazines/specialist.dm
Labels: Tweak

#4220 Adds the T-60 GPMG.
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  sound/weapons/guns/fire/GPMG.ogg
Labels: Balance/Rebalance, Feature, Sound, Sprites

#4243 Fixes panther caste_descs typos
  code/modules/mob/living/carbon/xenomorph/castes/panther/castedatum_panther.dm
Labels: Grammar and Formatting

#4248 Add missing reactions
  tgmc.dme
Labels: Fix, Priority: High

#4236 Buffs sunder recovery while resting
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance/Rebalance

#4231 Better admin controls over FF
  code/__DEFINES/cooldowns.dm
  code/_onclick/item_attack.dm
  code/controllers/configuration/entries/general.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/projectile.dm
Labels: Administration, Config Update

#4234 Fix APC in hanger security on ice colony
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Map Edit

#4264 fixes the IS module to be like a satchel
  code/modules/modular_armor/storage.dm
Labels: Tweak

#4265 Fix razorwire entangle bug
  code/game/objects/structures/razorwire.dm
Labels: Fix

#4203 Sentry Health Buff
  code/game/objects/machinery/sentries.dm
Labels: Balance/Rebalance

#4241 Remove some orbit debugging
  tgui/packages/tgui/interfaces/Orbit.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: UI

#4247 Fix xeno emotes
  code/modules/mob/living/carbon/xenomorph/emote.dm
Labels: Fix

#4249 Fixes exploding evac shuttles
  _maps/shuttles/escape_shuttle.dmm
  code/modules/shuttle/escape_pod.dm
Labels: Fix, Map Edit

#4251 AI can no longer near mobs on turfs they can't see
  code/modules/mob/living/say.dm
Labels: Fix

#4252 Fixes some autodoc issues
  code/game/objects/machinery/autodoc.dm
Labels: Fix

#4253 Fixes admin away messages
  tgmc.dme
Labels: Fix

#4254 Fix id card computer
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Tyson_Station/Tyson_Station.dmm
  _maps/shuttles/big_ert.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/items/circuitboards/computer.dm
  code/game/objects/machinery/computer/card.dm
  code/game/objects/machinery/computer/marines_consoles.dm
  tgmc.dme
Labels: Fix, Map Edit

#4261 Add a clock
  code/game/objects/items/misc.dm
  icons/obj/items/items.dmi
Labels: Feature, Sprites

#4245 Fixes Defiler stats
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
Labels: Balance/Rebalance

#4285 Fix pixel_x = 0 warning on Sulaco
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Map Edit

#4257 Fix orbit offsets
  code/datums/components/orbiter.dm
Labels: Fix

#4272 New camera console
  code/__DEFINES/skills.dm
  code/__HELPERS/game.dm
  code/_onclick/hud/screen_objects.dm
  code/_onclick/map_popups.dm
  code/game/area/bigred.dm
  code/game/area/centcom.dm
  code/game/area/desert.dm
  code/game/area/desertdam.dm
  code/game/area/general.dm
  code/game/area/icecolony.dm
  code/game/area/icy_caves.dm
  code/game/area/lava_outpost.dm
  code/game/area/lv624.dm
  code/game/area/mainship.dm
  code/game/area/port_hamburg.dm
  code/game/area/prison.dm
  code/game/area/sulaco.dm
  code/game/area/vaporprocessing.dm
  code/game/area/whiskeyoutpost.dm
  code/game/objects/items/devices/spyglasses.dm
  code/game/objects/items/devices/tablets.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/computer/camera.dm
  code/game/objects/machinery/computer/camera_console.dm
  code/game/sound.dm
  code/modules/client/client_defines.dm
  sound/machines/terminal_button01.ogg
  sound/machines/terminal_button02.ogg
  sound/machines/terminal_button03.ogg
  sound/machines/terminal_button04.ogg
  sound/machines/terminal_button05.ogg
  sound/machines/terminal_button06.ogg
  sound/machines/terminal_button07.ogg
  sound/machines/terminal_button08.ogg
  sound/machines/terminal_on.ogg
  tgmc.dme
  tgui/packages/tgui/interfaces/CameraConsole.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Sound, UI

#4255 Stop xenos vent dragging marines past fog
  code/modules/atmospherics/machinery/atmosmachinery.dm
Labels: Fix

#4260 Adds the T-70 grenade launcher
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/specialist.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
Labels: Balance/Rebalance, Feature, Sprites

#4246 Reduce amount of extra SG slots
  code/datums/gamemodes/infestation.dm
Labels: Balance/Rebalance

#4235 Machine pistol now pistol sized, less ammo in mags, better accuracy
  code/game/objects/items/storage/pouch.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/smgs.dm
Labels: Balance/Rebalance

#4262 gives combat engineers proper engineering access
  code/datums/jobs/job/marines.dm
Labels: Feature

#4287 Fixes ERT loading issues
  _maps/map_files/generic/Admin_Level.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/__DEFINES/shuttles.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/xeno.dm
  code/datums/gamemodes/crash.dm
  code/modules/mapping/map_template.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/ert.dm
  code/modules/shuttle/ert_big.dm
  code/modules/shuttle/gamemodes/crash.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/shuttle/shuttle.dm
Labels: Code Improvement, Fix, Map Edit

#4211 Buffs barricades
  code/game/objects/structures/barricade.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance/Rebalance

#4289 [Map Edits] LZ Shutters
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Fix, Map Edit

#4282 rebalances and uncomments a very important yet missing piece of fire code for idling
  code/modules/projectiles/guns/flamer.dm
Labels: Balance/Rebalance, Tweak

#4288 Fixes gaurdsmen icons
  code/modules/clothing/suits/marine_armor.dm
Labels: Fix

#4294 Fixes Engineering Storage Module
  code/modules/modular_armor/storage.dm
Labels: Fix

#4278 Fixes two engineers getting 2 kinds of gloves
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Fix

#4318 Throwable points
  code/modules/mob/living/living.dm
Labels: Feature

#4298 Fix mobs surviving being crushed by shuttles
  code/__DEFINES/dcs/signals.dm
  code/game/objects/machinery/Sleeper.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/shuttle/on_move.dm
Labels: Fix

#4279 Adds (admin only) other hive Xeno ERTs and allows individual other hive xenos to spawn
  code/datums/emergency_calls/xeno.dm
  code/datums/emergency_calls/xenoalpha.dm
  code/datums/emergency_calls/xenobeta.dm
  code/datums/emergency_calls/xenocorrupted.dm
  code/datums/emergency_calls/xenozeta.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  tgmc.dme
Labels: Feature

#4218 Map fixes for Sulaco and Pillar
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/watercloset.dm
Labels: Fix, Map Edit

#4290 brings the construction skill in line with other time reducing skills
  code/game/objects/items/stacks/stack.dm
Labels: Tweak

#4319 Some more emotes
  code/modules/mob/living/carbon/human/emote.dm
Labels: Feature

#4316 Defender Bugfix
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Fix

#4311 fixes super sayan speed modular armor
  code/modules/modular_armor/modular.dm
Labels: Fix

#4321 Fix mini sentry starting with less health
  code/game/objects/machinery/sentries.dm
Labels: Fix

#4325 Fixes the DMR gun sprite having white pixels and pistol inhands.
  icons/Marine/gun64.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
Labels: Fix

#4301 Adds pill packets, and tricordazine pill packets to the first aid kit pouch.
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/items/storage/pouch.dm
  icons/obj/items/chemistry.dmi
  tgmc.dme
Labels: Balance/Rebalance, Feature, Sprites

#4276 Removes quick fire assembly from the pulse rifles
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance, Removal

#4302 Announce to affected players when mass-bussing happens who did it
  code/modules/admin/topic.dm
Labels: Administration

#4327 Nerf T1 Xenos on crash
  code/datums/gamemodes/crash.dm
Labels: Balance/Rebalance

#4324 Fix spaces areas in sulaco
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Map Edit

#4339 Burrowed nerf
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance/Rebalance

#4343 Buffs mortar
  code/game/objects/structures/mortar.dm
Labels: Balance/Rebalance

#4341 Actually Fixes the goddamn engi gloves bug
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Fix

#4366 Removes krihelmeter from the readme
  README.md
Labels: Removal

#4352 Fixes Pill Packets
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/items/storage/pouch.dm
Labels: Feature

#4342 Gives HuD tablets to SLs, POs, FCs, and the captain
  code/datums/jobs/job/shipside.dm
  code/game/objects/items/devices/tablets.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Feature

#4348 Fixes modular helmets
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/modular_armor/helmets.dm
  code/modules/modular_armor/modular.dm
Labels: Fix, Grammar and Formatting

#4330 Tarp Uncovering
  code/game/objects/items/marine_gear.dm
Labels: Feature

#4309 Add gesture based callouts for humans
  code/datums/elements/gestures.dm
  code/modules/mob/living/living.dm
  tgmc.dme
Labels: Feature

#4353 Tips Galore! Adds tips and removes defunct ones.
  strings/tips/marine.txt
  strings/tips/meme.txt
  strings/tips/meta.txt
  strings/tips/xeno.txt
Labels: Feature, Removal, Tweak

#4283 Fix random weapon spawn tiers
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  code/game/objects/effects/landmarks/landmarks.dm
Labels: Fix, Map Edit

#4306 Minigun Change
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Balance/Rebalance, Test Merge Candidate, Tweak

#4307 Enables kicking of excessive friendly fire [part 2]
  code/modules/mob/living/living_helpers.dm
Labels: Administration, Test Merge Candidate

#4323 reduces point to cooldown by 50%
  code/modules/mob/living/living.dm
Labels: Requires Testing

#4345 adds Jaeger mimir helmet module
  code/modules/modular_armor/attachables.dm
  code/modules/modular_armor/helmet_module.dm
  icons/mob/modular/modular_helmet_attachment.dmi
Labels: Feature, Sprites

#4350 FOB Drone Construction Speed
  code/modules/mining/remote_fob/remote_fob_actions_misc.dm
Labels: Balance/Rebalance

#4358 Readds code for setting playercount limits on map voting
  code/controllers/subsystem/vote.dm
  config/maps.txt
Labels: Config Update

#4360 Standardizes Firing Modes
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Tweak

#4361 Fixes Modular Armor II
  code/modules/modular_armor/attachables.dm
Labels: Fix

#4364 Correctly fixes turfs being deleted
  code/game/objects/effects/overlays.dm
  code/game/objects/items/binoculars.dm
Labels: Fix

#4375 gives hunter more hp
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Balance/Rebalance, Fix
