Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2021-05, with the labels that each got.

#6682 Orders icons are now red when on cooldown
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/overwatch.dm
  code/datums/actions/order_action.dm
Labels: Quality of Life

#6447 Fix larva queue
  code/datums/jobs/job/job.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Do Not Merge, Fix

#6725 Fixes xeno zone selection QOL regression bug
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#6727 Fix bump attack message
  code/datums/components/bump_attack.dm
Labels: Fix

#6728 Fix fortified defenders laying down
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
Labels: Fix

#6729 Fix small silo being placeable on high pop
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#6683 Add linters for pixel z / pixel w and for centcomm with two m
  _maps/map_files/MarineHQ/MarineHQ.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  code/datums/emergency_calls/xenoalpha.dm
  code/datums/emergency_calls/xenobeta.dm
  code/datums/emergency_calls/xenocorrupted.dm
  code/datums/emergency_calls/xenozeta.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items/tools/misc_tools.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/armor.dm
  code/modules/paperwork/paper.dm
  code/modules/shuttle/ert_big.dm
  tools/ci/check_grep.sh
Labels: Code Improvement, Map Edit, Tools

#6677 Tracker cleanup
  code/controllers/subsystem/direction.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/squads.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/nuclearbomb.dm
Labels: Code Improvement

#6731 Fixes thrown item damage application delay
  code/modules/mob/living/living_defense.dm
Labels: Fix

#6734 Fix open helmets
  code/modules/modular_armor/modular.dm
Labels: Fix

#6736 No longer invisible when dead in cloak smoke
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
Labels: Fix

#6732 Updating the Shoulder Holster to fit the T19
  code/modules/clothing/under/ties.dm
Labels: Fix

#6743 Attachment code improvements
  code/__DEFINES/attachments.dm
  code/modules/codex/entries/weapons_codex.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  tgmc.dme
Labels: Code Improvement

#6741 Ui button updates
  code/__DEFINES/dcs/signals.dm
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/modules/client/preferences_ui.dm
  icons/UI_Icons/lobby_button.dmi
  interface/skin.dmf
Labels: Fix, Quality of Life, Sprites

#6739 Emissive apcs
  code/modules/power/apc.dm
Labels: Quality of Life

#6735 Sulaco fix
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#6733 Can no longer vote for crash in high pop
  code/__DEFINES/configuration.dm
  code/controllers/configuration/configuration.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/vote.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/gamemodes/hunt.dm
  config/modes.txt
Labels: Config Update, Fix

#6744 Larva queue QOL
  code/datums/actions/observer_action.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  icons/mob/actions.dmi
Labels: Quality of Life, Sprites

#6746 Fix incorrect icon update procs
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/items/radio/detpack.dm
  code/game/objects/items/reagent_containers/blood_pack.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/items/storage/surgical_tray.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/items/toys/cards.dm
  code/game/objects/items/toys/toy_weapons.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/autolathe.dm
  code/game/objects/machinery/bioprinter.dm
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/cloning/cloning.dm
  code/game/objects/machinery/computer/camera_console.dm
  code/game/objects/machinery/computer/crew.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/airlock_control.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/machinery/doors/railing.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/machinery/dropship_part_fabricator.dm
  code/game/objects/machinery/flasher.dm
  code/game/objects/machinery/hologram.dm
  code/game/objects/machinery/holosign.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/ladders.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/safe.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/windoor_assembly.dm
  code/modules/assembly/mousetrap.dm
  code/modules/power/generator.dm
  code/modules/power/port_gen.dm
  code/modules/projectiles/ammunition.dm
Labels: Code Improvement

#6754 Adds TGUI compability mode as a byond verb
  code/modules/client/preferences_toggles.dm
Labels: Fix, Quality of Life

#6740 Code improve return ahelp I guess
  code/modules/admin/verbs/adminhelp.dm
Labels: Administration, Fix

#6760 Incredible change to attempt to resurrect git
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
Labels: Map Edit

#6360 Tadpole small rework
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/shuttles/minidropship.dmm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/obj_flags.dm
  code/__DEFINES/shuttles.dm
  code/_globalvars/lists/mapping.dm
  code/controllers/subsystem/shuttle.dm
  code/controllers/subsystem/silo.dm
  code/datums/elements/windowshutter.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/window_frame.dm
  code/game/turfs/space/transit.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/shuttle/docking.dm
  code/modules/shuttle/mini_dropship.dm
  code/modules/shuttle/navigation_computer.dm
  code/modules/shuttle/shuttle.dm
  code/modules/tgui/states/dropship.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/mecha/actions_mecha.dmi
  icons/turf/space.dmi
  sound/machines/shuttle_still_flight.ogg
  tgmc.dme
  tgui/packages/tgui/interfaces/Minidropship.js
  tgui/public/tgui.bundle.js
Labels: Map Edit, Sound, Sprites, Test Merge Candidate, UI

#6722 Deletes desert outpost
  _maps/_basemap.dm
  _maps/desert.json
  _maps/map_files/desert/desert.dmm
  code/game/area/desert.dm
  config/maps.txt
  tgmc.dme
Labels: Config Update, Map Edit, Removal

#6750 Adds the word 'menu' to the right click toggle notice
  code/modules/client/preferences_toggles.dm
Labels: Grammar and Formatting

#6758 Makes silos unable to be placed near walls as much
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance/Rebalance

#6756 Ports Glass UI style
  code/__DEFINES/preferences.dm
  code/__HELPERS/type2type.dm
  icons/mob/screen/glass.dmi
Labels: Sprites

#6755 removes tracer rounds from suppressors
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance, Removal

#6726 Fix showers
  code/game/objects/structures/watercloset.dm
Labels: Fix

#6464 LV Rework V3
  _maps/map_files/LV624/LV624.dmm
Labels: Balance/Rebalance, Feature, Map Edit, Test Merge Candidate

#6768 Fixes Sulaco Engineer Prep, other tweaks.
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Map Edit, Quality of Life

#6771 Fix xeno structures resistance_flags, update VV bitfields
  code/_globalvars/bitfields.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix, Quality of Life

#6765 Fix name not appearing in lobby ui properly
  code/_onclick/hud/screen_objects/menu_text_objects.dm
Labels: Fix

#6764 Update HvH vendor to be tabbed one
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
Labels: Code Improvement

#6769 Tac Reload Buff
  code/modules/projectiles/gun_helpers.dm
Labels: Balance/Rebalance

#6772 PPSh now fits on back slot.
  code/modules/projectiles/guns/smgs.dm
Labels: Balance/Rebalance

#6712 tgui shuttle control with new dropship
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/shuttles/normandy.dmm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/shuttles.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/power/lighting.dm
  code/modules/shuttle/cas_plane.dm
  code/modules/shuttle/docking.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/shuttle/shuttle.dm
  code/modules/tgui/states/access.dm
  code/modules/tgui/states/human_adjacent.dm
  icons/Marine/shuttle-parts.dmi
  icons/obj/doors/mainship/dropship2_side.dmi
  icons/obj/structures/dropship_structures.dmi
  icons/turf/dropship2.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/ShuttleControl.js
  tgui/public/tgui.bundle.js
Labels: Code Improvement, Feature, Map Edit, Quality of Life, Sprites, UI

#6776 Remove fulton beacon from req
  code/modules/reqs/supplypacks.dm
Labels: Removal

#6757 Adds emissive jaeger visors that glow in the dark
  code/__DEFINES/dcs/signals.dm
  code/datums/components/clothing_tint.dm
  code/datums/elements/special_clothing_overlay.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/modular_visor_emissive.json
  code/datums/greyscale/json_configs/modular_visor_emissive_skull.json
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/modular_armor/modular.dm
  tgmc.dme
Labels: Quality of Life

#6781 Foam razorwire doesn't exist anymore.
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/structures/razorwire.dm
Labels: Balance/Rebalance

#6782 In which two ways to get large quantities of metal for no cost are described fully and completely.
  code/game/objects/items/stacks/sheets/glass.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#6788 Wraiths Can't Banish While Incorporeal
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Balance/Rebalance

#6794 Include a notice with sand storm damage like acid rain does
  code/datums/weather/weather_types/sand_storm.dm
Labels: Quality of Life

#6785 Fix psy drained trait being applied too often
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#6783 Holo and Minimalist UI
  code/__DEFINES/preferences.dm
  code/__HELPERS/type2type.dm
  icons/mob/screen/holo.dmi
  icons/mob/screen/minimalist.dmi
Labels: Feature, Sprites

#6767 Nerf xeno sting
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance/Rebalance

#6792 Phase Shift Revisions
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  icons/mob/actions.dmi
Labels: Balance/Rebalance, Quality of Life, Sprites

#6751 Context Menu on Shift Right Click
  code/modules/client/client_defines.dm
  code/modules/client/preferences_toggles.dm
  interface/skin.dmf
Labels: Quality of Life, Test Merge Candidate

#6409 Resin door rebalance
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/projectiles/guns/flamer.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6793 Banished Targets Now Disgorge Living Contents
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Code Improvement

#6805 Revert parts not working of #6746
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/machinery/doors/railing.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/machinery/doors/windowdoor.dm
Labels: Fix, Revert

#6798 Xeno Chem HUD Improved
  code/game/data_huds.dm
  icons/mob/hud.dmi
Labels: Quality of Life, Sprites

#6802 Fix synth name and mute xeno health alerts not working on tgui game pref
  code/modules/client/preferences_ui.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/Types.tsx
  tgui/public/tgui.bundle.js
Labels: Fix, UI

#6801 Fix hijack state not being registered
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/hunt.dm
Labels: Fix

#6807 Excess Cooldown Notice Removal for Phase Shift
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Quality of Life

#6812 Fix headbite xeno hud update that I broke.
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#6814 Make accidentally opening the admin dsay dialog less annoying
  code/modules/admin/admin_verbs.dm
Labels: Administration

#6813 Fix xeno turrets broken by the alamo spewing acid smoke
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix

#6799 Should fix double minimap when changing squad
  code/datums/jobs/squads.dm
Labels: Fix, Test Merge Candidate

#6753 Emote keybinds
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/preferences.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/sanitize_values.dm
  code/_globalvars/lists/keybinding.dm
  code/datums/custom_emotes.dm
  code/datums/emotes.dm
  code/datums/keybinding/_defines.dm
  code/datums/keybinding/custom_emote.dm
  code/datums/keybinding/emote.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/emote.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/TextInputModal.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/Types.tsx
  tgui/public/tgui.bundle.js
Labels: Feature, UI

#6790 New Ammo Box and Grenade Boxes
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/smartgun_mount.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/flamer.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/shotguns.dm
  code/modules/projectiles/magazines/smgs.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/items_mini.dmi
  icons/obj/items/storage/storage_boxes.dmi
Labels: Feature, Map Edit, Quality of Life, Removal, Sprites, Test Merge Candidate

#6818 Mk1 Jaeger modules in armor vendor
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#6674 Port CBT
  .dockerignore
  .github/workflows/ci_suite.yml
  .gitignore
  .tgs4.yml
  .vscode/launch.json
  .vscode/tasks.json
  BUILD.bat
  code/controllers/subsystem/vote.dm
  html/changelogs/example.yml
  tgstation.mdme
  tgui/.gitignore
  tgui/bin/tgui
  tgui/bin/tgui_.ps1
  tgui/public/tgui-common.bundle.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
  tools/bootstrap/node_.ps1
  tools/build/.editorconfig
  tools/build/README.md
  tools/build/build
  tools/build/build.bat
  tools/build/build.js
  tools/build/cbt/fs.js
  tools/build/cbt/glob.js
  tools/build/cbt/process.js
  tools/build/cbt/task.js
  tools/build/cbt/winreg.js
  tools/ci/build.ps1
  tools/ci/build_spaceman_dmm.sh
  tools/ci/build_tgui.sh
  tools/ci/check_changelogs.sh
  tools/ci/check_filedirs.sh
  tools/ci/dm.sh
  tools/ci/install_build_tools.sh
  tools/ci/install_node.sh
  tools/ci/install_rust_g.sh
  tools/ci/install_spaceman_dmm.sh
  tools/ci/run_server.sh
  tools/deploy.sh
  tools/tgs4_scripts/PreCompile.bat
  tools/tgs4_scripts/PreCompile.sh
Labels: Do Not Merge, GitHub, Tools, UI

#6830 Automatically show testmerges on login if there are any
  code/modules/mob/new_player/login.dm
Labels: Quality of Life

#6828 Fix vsc warning when building
  .gitignore
  .vscode/tasks.json
Labels: Fix, Tools

#6826 Add Bull's charge modes descriptions to the codex
  code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
Labels: Quality of Life

#6820 Automated miners require an open side to sell ore
  code/game/objects/machinery/miner.dm
Labels: Balance/Rebalance

#6819 Fixes Vali not disabling if unequipped soon after turned on
  code/datums/components/chem_booster.dm
Labels: Fix

#6823 Replace nightfall with a 5 second version
  sound/magic/nightfall.ogg
Labels: Sound

#6766 Allow rclick to immediately draw from storage
  code/game/objects/items/storage/storage.dm
Labels: Quality of Life

#6791 modularizes attachments code.
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/game/objects/items/tools/flame_tools.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Refactor

#6719 Terra Expermental Energy weapons series
  code/__DEFINES/colors.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/magazines/energy.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/projectiles.dmi
  sound/weapons/guns/fire/Laser Carbine Scatter.ogg
  sound/weapons/guns/fire/Laser Pistol Standard.ogg
  sound/weapons/guns/fire/Laser Rifle Standard.ogg
  sound/weapons/guns/fire/Laser Sniper Standard.ogg
  sound/weapons/guns/fire/Laser overcharge standard.ogg
  sound/weapons/guns/interact/standard_laser_pistol_reload.ogg
  sound/weapons/guns/interact/standard_laser_rifle_reload.ogg
  sound/weapons/guns/interact/standard_laser_sniper_reload.ogg
  sound/weapons/guns/interact/standard_machine_laser_reload.ogg
  tgmc.dme
Labels: Balance/Rebalance, Feature, Removal, Sound, Sprites, Test Merge Candidate

#6838 fixes Whisky Outpost Sandbags (and map linters?)
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
Labels: Map Edit

#6834 Reorder end of round automatic votes, groundmap last
  code/controllers/subsystem/vote.dm
Labels: Quality of Life

#6845 Fix xeno spit and scatter spit aiming
  code/modules/mob/living/living.dm
Labels: Fix

#6844 Minor TE description changes
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/magazines/energy.dm
Labels: Fix

#6835 Fix wraith blink keybind not showing
  code/datums/keybinding/xeno.dm
Labels: Fix

#6752 Rebalances standard issue pistol sunder (TP14 to 1.65, TP23 to 2.15)
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#6829 Fix xeno tracker not updating for crash nuke activation
  code/datums/gamemodes/crash.dm
  code/game/objects/machinery/nuclearbomb.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#6763 Faction support for requisition
  code/__DEFINES/factions.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/monitor.dm
  code/controllers/subsystem/points.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/gamemodes/infestation.dm
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/imperium.dm
  code/datums/jobs/job/mercenaries.dm
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/sectoid.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
  code/game/objects/machinery/computer/intel_computer.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/machinery/sellingpad.dm
  code/modules/reqs/supply.dm
  code/modules/reqs/supplyexports.dm
  code/modules/requisitions/_supply_export.dm
  code/modules/requisitions/fulton.dm
  code/modules/requisitions/supply_export.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/Cargo.js
Labels: Code Improvement, UI

#6855 webbing is bulky
  code/modules/clothing/under/ties.dm
Labels: Balance/Rebalance

#6849 Fix hair choice on new character
  code/modules/mob/new_player/preferences_setup.dm
Labels: Fix

#6847 Rclick now lets you change the reagent transfer on ANY reagent container
  code/game/objects/items/reagent_containers/reagent_container.dm
Labels: Quality of Life

#6762 Clean landmarks + weeds are gamemode dependant + corpse spawners are gamemode dependant + remove resin from maps
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/__DEFINES/mode.dm
  code/_globalvars/lists/mapping.dm
  code/_globalvars/lists/objects.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/gamemodes/hunt.dm
  code/datums/gamemodes/infestation.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/effects/landmarks/mode.dm
  code/game/objects/items/cocoon.dm
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  tools/ci/check_grep.sh
Labels: Feature, Map Edit, Tools

#6850 No more runtime on prae acid spit and xeno turrets
  code/game/objects/effects/aliens.dm
Labels: Fix

#6706 Adds the Martini Henry Infantry Rifle
  code/__DEFINES/calibers.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/magazines/shotguns.dm
  sound/weapons/guns/fire/martini.ogg
  sound/weapons/guns/interact/martini_cocked.ogg
  sound/weapons/guns/interact/martini_open.ogg
  sound/weapons/guns/interact/martini_reload.ogg
Labels: Code Improvement, Feature, Sound, Sprites

#6841 Pillar of Spring Prep/Medical Optimization
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Feature, Map Edit

#6832 Banish Now Toggles On/Off; Recall Removed v2
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  icons/mob/actions.dmi
Labels: Quality of Life, Sprites

#6852 Runtime new perm
  code/__DEFINES/admin.dm
  code/__HELPERS/type2type.dm
  code/_globalvars/bitfields.dm
  code/modules/admin/admin_ranks.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/holder.dm
Labels: Administration

#6839 Fix me
  code/__DEFINES/emote.dm
  code/__DEFINES/keybind.dm
  code/_globalvars/lists/keybinding.dm
  code/datums/emotes.dm
  code/modules/mob/emote.dm
  tgmc.dme
Labels: Fix

#6866 Fix supply not working
  code/modules/reqs/supply.dm
Labels: Fix

#6873 Fix req
  code/controllers/subsystem/points.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/reqs/supply.dm
Labels: Fix

#6874 Export history fix
  code/game/objects/machinery/sellingpad.dm
  code/modules/reqs/supply.dm
  code/modules/requisitions/fulton.dm
Labels: Fix

#6869 Fix invicible resin walls
  code/datums/gamemodes/infestation.dm
Labels: Fix

#6825 Vendors improvement: more shared one, infinite supplies
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
  tgui/packages/tgui/interfaces/Vending.tsx
Labels: Balance/Rebalance, UI

#6854 Fix xeno psy hud not updating for non-processing mobs
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#6871 Fixes Distance Stacking for Hugger Trap Alerts
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#6843 Ammo box 2: The prefillening
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/items_mini.dmi
  icons/obj/items/storage/storage_boxes.dmi
Labels: Feature, Map Edit, Quality of Life, Removal, Sprites

#6816 Hunt get psy points too, but only from generators
  code/__DEFINES/mode.dm
  code/controllers/subsystem/job.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/hunt.dm
Labels: Feature

#6555 Jetpack buff
  code/game/objects/items/jetpack.dm
  code/game/objects/structures/razorwire.dm
  code/modules/mob/living/living.dm
Labels: Balance/Rebalance, Stale

#6887 Allows xeno tracker target selection while resting
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Quality of Life

#6882 Prevent restocking of infinite supplies
  code/game/objects/machinery/vending/vending.dm
Labels: Fix

#6851 Larvas are on minimap
  code/datums/jobs/job/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#6895 Automatic approve workflows
  .github/workflows/run_approval.yml
Labels: Git-hub, Git.hUb, GitHub

#6876 Pin conflict labeler commit and increase timeout
  .github/workflows/conflicts.yml
Labels: Git-hub, Git.hUb, GitHub

#6894 Fix hunt/distress MODE_PSY_POINTS flag collision
  code/controllers/subsystem/silo.dm
  code/datums/jobs/job/job.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#6884 Improved Xeno Structure Placement
  code/_globalvars/lists/objects.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/projectiles/projectile.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Code Improvement, Fix, Quality of Life

#6888 Improve small silo active player count and notice
  code/__HELPERS/game.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix, Grammar and Formatting

#6893 Charging xenos now plow snow when at full steam
  code/game/turfs/snow.dm
Labels: Feature

#6889 Adds a marine attachment that makes your bullets faster
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/gun_attachables.dm
Labels: Balance/Rebalance

#6875 Changed price of CAS flares from 10 to 5
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#6804 Maybe make warrior lunge better[DNM]
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Fix, Test Merge Candidate

#6914 Dont run approval on prs
  .github/workflows/run_approval.yml
Labels: Git-hub, Git.hUb, GitHub

#6908 Fixes the Martini Henry Sprites
  icons/Marine/gun64.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
Labels: Fix, Sprites

#6777 Setting to remove some supply packs in HVH
  code/__DEFINES/mode.dm
  code/controllers/subsystem/points.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/reqs/supplypacks.dm
Labels: Code Improvement

#6910 Sandbag barricade icons now update when repaired
  code/game/objects/structures/barricade.dm
Labels: Fix

#6900 Recall Reinstated
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Labels: Quality of Life

#6906 Pref rand char fix
  code/__HELPERS/mobs.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Fix

#6905 Fix restocking
  code/game/objects/machinery/vending/vending.dm
Labels: Fix

#6897 Fix Synths being able to pull Xenos
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Administration, Fix

#6904 More round flags, fix psy points on hunt
  code/__DEFINES/mode.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/silo.dm
  code/datums/gamemodes/distress.dm
  code/datums/jobs/job/job.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/power/groundmap_geothermal.dm
Labels: Fix

#6867 Supply shuttle are now faction based
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/generic/Admin_Level.dmm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/points.dm
  code/controllers/subsystem/shuttle.dm
  code/modules/reqs/supply.dm
  code/modules/shuttle/shuttle.dm
Labels: Code Improvement, Map Edit, Test Merge Candidate

#6836 Hvh faction
  code/__DEFINES/access.dm
  code/__DEFINES/factions.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/radio.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/other.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/squads.dm
  code/game/communications.dm
  code/game/objects/effects/landmarks/marine_spawns.dm
  code/game/objects/items/radio/encryptionkey.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/machinery/doors/multi_tile.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  config/shipmaps.txt
Labels: Config Update, Feature

#6831 Theseus Remodel/Rework
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/theseus.json
  code/game/area/mainship.dm
  code/game/objects/machinery/doors/multi_tile.dm
Labels: Feature, Map Edit

#6924 Ports easy to extend SVG custom font from TG and some small things.
  code/__DEFINES/tgui.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui_panel/tgui_panel.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/tgui_create_message.dm
  tgui/packages/tgfont/.gitignore
  tgui/packages/tgfont/config.cjs
  tgui/packages/tgfont/icons/anonymous_logo.svg
  tgui/packages/tgfont/icons/nanotrasen_logo.svg
  tgui/packages/tgfont/icons/syndicate_logo.svg
  tgui/packages/tgfont/icons/tgmc_logo.svg
  tgui/packages/tgfont/mkdist.cjs
  tgui/packages/tgfont/package.json
  tgui/packages/tgui/components/Icon.js
  tgui/yarn.lock
  tools/build/build.js
Labels: Tools, UI

#6917 Keybind for vent
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
Labels: Feature

#6860 Laser gun rebalance and edits
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Not a code change, Sprites

#6931 Fix ert shuttles and canterbury
  code/modules/shuttle/shuttle.dm
Labels: Fix

#6912 Resin Nodes no Longer Block Buildings
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Balance/Rebalance, Quality of Life

#6935 Revert "Ports easy to extend SVG custom font from TG and some small things."
  code/__DEFINES/tgui.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui_panel/tgui_panel.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/tgui_create_message.dm
  tgui/packages/tgfont/.gitignore
  tgui/packages/tgfont/config.cjs
  tgui/packages/tgfont/icons/anonymous_logo.svg
  tgui/packages/tgfont/icons/nanotrasen_logo.svg
  tgui/packages/tgfont/icons/syndicate_logo.svg
  tgui/packages/tgfont/icons/tgmc_logo.svg
  tgui/packages/tgfont/mkdist.cjs
  tgui/packages/tgfont/package.json
  tgui/packages/tgui/components/Icon.js
  tgui/yarn.lock
  tools/build/build.js
Labels: Revert, Tools, UI

#6936 Reverts revert of Easy to extend SVG
  code/__DEFINES/tgui.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui_panel/tgui_panel.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/tgui_create_message.dm
  tgui/packages/tgfont/.gitignore
  tgui/packages/tgfont/config.cjs
  tgui/packages/tgfont/icons/anonymous_logo.svg
  tgui/packages/tgfont/icons/nanotrasen_logo.svg
  tgui/packages/tgfont/icons/syndicate_logo.svg
  tgui/packages/tgfont/icons/tgmc_logo.svg
  tgui/packages/tgfont/mkdist.cjs
  tgui/packages/tgfont/package.json
  tgui/packages/tgui/components/Icon.js
  tgui/yarn.lock
  tools/build/build.js
  tools/tgs4_scripts/PreCompile.bat
Labels: Revert, Tools, UI

#6932 Port Popper Tooltips
  tgui/docs/component-reference.md
  tgui/packages/tgui-panel/Panel.js
  tgui/packages/tgui/components/Button.js
  tgui/packages/tgui/components/Popper.tsx
  tgui/packages/tgui/components/Tooltip.js
  tgui/packages/tgui/components/Tooltip.tsx
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/Orbit.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/TextInputModal.tsx
  tgui/packages/tgui/layouts/NtosWindow.js
  tgui/packages/tgui/package.json
  tgui/packages/tgui/stories/Popper.stories.js
  tgui/packages/tgui/stories/Tooltip.stories.js
  tgui/packages/tgui/styles/components/Tooltip.scss
  tgui/public/tgui.html
  tgui/yarn.lock
Labels: Refactor, UI

#6933 Converts changelog to tgui
  .gitattributes
  .github/workflows/compile_changelogs.yml
  code/_globalvars/changelog.dm
  code/_globalvars/tgui.dm
  code/game/world.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/mob.dm
  html/browser/changelog.css
  html/images/88x31.png
  html/images/ban.png
  html/images/bug-minus.png
  html/images/burn-exclamation.png
  html/images/chrome-wrench.png
  html/images/coding.png
  html/images/cross-circle.png
  html/images/hard-hat-exclamation.png
  html/images/image-minus.png
  html/images/image-plus.png
  html/images/music-minus.png
  html/images/music-plus.png
  html/images/scales.png
  html/images/spell-check.png
  html/images/tick-circle.png
  html/images/wrench-screwdriver.png
  html/templates/footer.html
  html/templates/header.html
  tgmc.dme
  tgui/packages/tgfont/icons/image-minus.svg
  tgui/packages/tgfont/icons/image-plus.svg
  tgui/packages/tgfont/icons/sound-minus.svg
  tgui/packages/tgfont/icons/sound-plus.svg
  tgui/packages/tgui-polyfill/index.js
  tgui/packages/tgui-polyfill/package.json
  tgui/packages/tgui/interfaces/Changelog.js
  tgui/packages/tgui/package.json
  tgui/packages/tgui/styles/atomic/links.scss
  tgui/packages/tgui/styles/interfaces/Changelog.scss
  tgui/packages/tgui/styles/main.scss
  tgui/yarn.lock
  tools/WebhookProcessor/github_webhook_processor.php
  tools/ci/check_changelogs.sh
  tools/makeChangelog.bat
  tools/ss13_genchangelog.py
  tools/tgs4_scripts/PreSynchronize.ps1
  tools/tgs4_scripts/PreSynchronize.sh
Labels: GitHub, Refactor, Tools, UI

#6918 Medbay expansion + Pipenet and Disposal Improvement for PoS
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#6922 Fix non-xeno construction zone near lzs for barrenquilla
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
Labels: Fix, Map Edit

#6937 Fixed Movement Bug With Evasion
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Fix

#6929 Fix AI not being able to give orders ground side
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#6903 Tail Sweep SFX and QoL Improvements
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
Labels: Code Improvement, Quality of Life

#6858 jaeger storage modules no longer slow you down
  code/modules/modular_armor/storage.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6916 Friendly fire damage is reduced
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6824 Add jatum
  code/__HELPERS/jatum.dm
  tgmc.dme
Labels: Code Improvement

#6927 T19 buff
  code/modules/projectiles/guns/smgs.dm
Labels: Balance/Rebalance

#6941 Puts changelogs file on correct location
  code/datums/changelog/changelog.dm
  tgmc.dme
Labels: Fix

#6939 Theseus Day 1 Patch
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Fix, Map Edit

#6780 Chem rework mk 6 revenge of the chems
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Balance/Rebalance, Feature, Map Edit, Removal, Test Merge Candidate

#6915 Nerf psydrain, nerf generators psy points output, rebalance cocoon
  code/controllers/subsystem/points.dm
  code/game/objects/items/cocoon.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance/Rebalance

#6945 Removes lrp dolls
  code/game/objects/items/toys/toys.dm
  code/game/objects/machinery/computer/arcade.dm
  icons/obj/items/toy.dmi
Labels: Removal, Sprites

#6865 HvH mode prework: squad hud, minimap and orders
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/minimap.dm
  code/__DEFINES/mobs.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/minimaps.dm
  code/datums/actions/order_action.dm
  code/datums/atom_hud.dm
  code/datums/gamemodes/civil_war.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/squads.dm
  code/game/data_huds.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/computer/marines_consoles.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/squad_supply/supply_pads.dm
  code/modules/admin/topic.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/silicon.dm
  tgmc.dme
Labels: Code Improvement, Config Update

#6923 Ports SSpersistence, adds time-based seasons tracking system, adds rotating marine supplies
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/time.dm
  code/controllers/subsystem/persistence.dm
  code/datums/gamemodes/game_mode.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
  tgmc.dme
Labels: Code Improvement, Config Update, Do Not TM

#6948 Airlock changes
  code/game/objects/machinery/doors/airlock.dm
Labels: Balance/Rebalance
