Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2021-04, with the labels that each got.

#6462 Update dependencies installed for TGSv4 precompile scripts
  tools/tgs4_scripts/PreCompile.sh
Labels: Tools

#6306 Cloak grenades only stealth marines, supplies cut in half
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
Labels: Balance frozen, Balance/Rebalance

#6419 reduces revolver screenshake a bit.
  code/modules/projectiles/ammo_datums.dm
Labels: Balance frozen, Balance/Rebalance

#6404 QoL Synth
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Balance frozen, Balance/Rebalance, Quality of Life

#6423 Razor Burn nade boxes
  code/game/objects/items/storage/boxes.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/storage/storage.dmi
Labels: Balance frozen, Feature, Sprites

#6369 Minor buff to armored labcoat
  code/modules/clothing/suits/labcoat.dm
Labels: Balance frozen, Balance/Rebalance

#6371 makes some power weapons (m4ra, railgun, anti material rifle) cheaper
  code/modules/reqs/supplypacks.dm
Labels: Balance frozen, Balance/Rebalance

#6115 Ai can send CIC orders
  code/__DEFINES/dcs/signals.dm
  code/_onclick/ai.dm
  code/datums/actions/order_action.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/living/silicon/ai/ai.dm
  tgmc.dme
Labels: Balance frozen, Feature

#6411 drone speed up from weeds massively reduced
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
Labels: Balance frozen, Balance/Rebalance

#6452 One less button, merge spits button
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
Labels: Quality of Life

#6445 Wraith get psy drain
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Labels: Fix

#6408 Xenos have the choice to build smaller and cheaper silos
  code/controllers/subsystem/silo.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Feature

#6443 Asleep examine message
  code/modules/mob/living/carbon/human/examine.dm
Labels: Quality of Life

#6413 Combat Engi Rework; Electric Boogaloo Edition
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Balance/Rebalance, Do Not Merge, Freeze Pass, Test Merge Candidate

#6392 Power fist balance (another PR, yes)
  code/game/objects/items/weapons/misc.dm
Labels: Balance frozen, Balance/Rebalance

#6415 Eggs can be done only by defiler
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Balance/Rebalance

#6358 Typescripts orbit menu and adds dead section to it
  tgui/packages/tgui/components/LabeledList.tsx
  tgui/packages/tgui/interfaces/Orbit.tsx
  tgui/public/tgui.bundle.js
  tgui/yarn.lock
Labels: Quality of Life, UI

#6453 Remove tank crewman job
  _maps/map_files/MarineHQ/MarineHQ.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/shipside.dm
  code/datums/skills.dm
  code/game/objects/effects/landmarks/gamemode/crash_spawns.dm
  code/game/objects/effects/landmarks/marine_spawns.dm
Labels: Map Edit, Removal

#6428 Praetorian cone sprays rework + acid spray exploit fix
  code/__DEFINES/cooldowns.dm
  code/game/objects/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Code Improvement, Feature, Fix, Refactor

#6469 Fix silo price
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#5422 Carrier Rework - 4 New Hugger Types
  code/__DEFINES/conflict.dm
  code/__DEFINES/mobs.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/effects/effects.dmi
  icons/mob/actions.dmi
Labels: Feature, Refactor, Sprites, Test Merge Candidate

#6451 You can corrupt generators by clicking on it
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/power/groundmap_geothermal.dm
Labels: Quality of Life

#6467 276 Belt Storage
  code/game/objects/items/storage/belt.dm
Labels: Balance/Rebalance

#6418 Lasergun radial mode menu
  code/datums/components/full_auto_fire.dm
  code/modules/projectiles/guns/energy.dm
  icons/mob/radial.dmi
Labels: Balance/Rebalance, Quality of Life, Sprites

#6441 More Sulaco QOL and tweaks
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/area/sulaco.dm
Labels: Feature, Fix, Map Edit, Quality of Life, Removal

#6475 Defiler can actually plant eggs
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
Labels: Fix

#6479 Hivemind collapse will now ALWAYS be 5 minutes
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance/Rebalance

#6422 Turret Price Change
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6482 Fixes Tadpole on Prison issue
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Fix, Map Edit

#6450 Slugs have slowdown again
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#6481 Razorwire now buildable from metal menu
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Quality of Life

#6490 Prae spray behaviour fix
  code/game/objects/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
Labels: Balance/Rebalance, Fix

#6488 AT Sniper nerf
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#6487 Queen Screech Update PR.
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance/Rebalance, Fix

#6313 Halves slowdown from wounds
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6468 Basketball Arena End of Round Deathmatch map
  _maps/modularmaps/EORG/basketball.dmm
  code/modules/mapping/modular_mapping.dm
Labels: Feature, Map Edit

#6284 New way of getting psy points, cocooning
  code/__DEFINES/dcs/signals.dm
  code/game/objects/items/cocoon.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/projectiles/gun_attachables.dm
  icons/obj/cocoon.dmi
  sound/effects/cutting_cocoon.ogg
  sound/vore/escape.ogg
  sound/vore/licence.txt
  sound/vore/struggle.ogg
  tgmc.dme
Labels: Feature, Sound, Sprites

#6164 Autofire refactor
  code/__DEFINES/autofire.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/_onclick/drag_drop.dm
  code/datums/components/autofire.dm
  code/datums/components/full_auto_fire.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/misc.dm
  code/modules/projectiles/guns/specialist.dm
  tgmc.dme
Labels: Refactor

#6483 Power Armor made useful again
  code/__DEFINES/supply.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Feature

#6353 Harvester effects small rework
  code/game/objects/items/weapons/blades.dm
Labels: Balance/Rebalance

#6273 Humans now take low oxy damage when critdragged
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Balance/Rebalance, Fix, Test Merge Candidate

#6500 Remove SS_NO_TICK_CHECK
  code/__DEFINES/MC.dm
  code/controllers/master.dm
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/points.dm
  code/controllers/subsystem/shuttle.dm
  code/controllers/subsystem/time_track.dm
Labels: Code Improvement

#6493 Larva output of super pool was wrong
  code/controllers/subsystem/silo.dm
Labels: Fix

#6474 restats/balances/names/sprites the T-45/M4RA
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/portable_vendor.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/glasses/night.dm
  code/modules/codex/entries/guns_codex.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Balance/Rebalance, Sprites

#6502 fixes recently introduced Sulaco Pipenet issues
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Map Edit

#6478 Marine Vending Cleanup and Organization
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Removal

#6494 Removes Engineer skill requirement for Mortar
  code/game/objects/structures/mortar.dm
Labels: Balance/Rebalance, Removal

#6495 Nerfs arm aiming.
  code/modules/organs/limbs.dm
Labels: Balance/Rebalance

#6376 Hive Status and Tunnel List Info Now Includes Distance
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix, Quality of Life, Stale

#6510 HVH ERT Fix
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/emergency_calls/upp.dm
Labels: Fix

#6480 Add rally order to SL, FC, SO and captain
  code/__DEFINES/overwatch.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/actions/order_action.dm
  code/datums/jobs/squads.dm
  code/datums/skills.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/Marine/marine-items.dmi
  icons/mob/actions.dmi
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Sprites, UI

#6513 Fix lasgun autofire mode not being on at init
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#6512 Fix ai order runtiming + give feedback when launching orders
  code/datums/actions/order_action.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix, Quality of Life

#6515 Carrier can lay eggs
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
Labels: Balance/Rebalance

#6509 Robo limbs proper malfunction and slight damage reduction buff.
  code/modules/organs/limbs.dm
Labels: Balance/Rebalance

#6521 Port TGUI vote
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/vote.dm
  tgui/packages/tgui/interfaces/Vote.js
  tgui/public/tgui.bundle.js
Labels: Config Update, Refactor, UI

#6524 Fixes FOB drone on ice colony LZ2
  code/modules/mining/remote_fob/remote_fob_fobdrone.dm
Labels: Fix

#6534 Fix voting machine
  code/controllers/subsystem/vote.dm
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui.bundle.js
Labels: Fix, UI

#6529 Barricade QOL
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Quality of Life

#6518 Taser
  code/modules/projectiles/ammo_datums.dm
Labels: Administration, Fix

#6410 Hivemind open resin doors with alt click
  code/__DEFINES/cooldowns.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Labels: Balance/Rebalance

#6514 Silo less from 10 minutes to 5
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance/Rebalance

#6533 Cas laser layer change
  code/game/objects/effects/overlays.dm
Labels: Balance/Rebalance

#6531 Fixes even more prison droppod edge cases
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Balance/Rebalance, Map Edit

#6497 Simplifies Vali
  code/datums/components/chem_booster.dm
Labels: Balance/Rebalance

#6499 You can aim at black tiles while shooting
  code/_onclick/click.dm
  code/modules/projectiles/gun_system.dm
Labels: Quality of Life

#6519 Allows reloading from pistol belt.
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/modules/clothing/suits/armor.dm
Labels: Feature

#6526 Allows entrenching tool to be sharpened.
  code/game/objects/items/tools/shovel_tools.dm
  icons/Marine/marine-items.dmi
Labels: Feature, Sprites

#6298 Adds a tactical explosive vest.
  code/game/objects/items/explosives/bombvest.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_suits.dmi
  tgmc.dme
Labels: Feature, Sprites, Test Merge Candidate

#6406 Protection against temporary visuals hard del
  code/datums/atom_hud.dm
Labels: Code Improvement

#6523 Gives light to miners if repaired.
  code/game/objects/machinery/miner.dm
Labels: Balance/Rebalance, Feature

#6528 Extinguisher QOL
  code/game/objects/items/tools/extinguisher.dm
Labels: Quality of Life

#6548 Ice LZ2 QOL fence removal
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Map Edit, Quality of Life

#6547 Hold Order Buff
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance

#6504 Xeno abilities easier to land on targets
  code/__DEFINES/actions.dm
  code/_onclick/click.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Balance/Rebalance

#6558 Fix a gap in ice colony containment shutters that wraith could phase through
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Fix, Map Edit

#6527 mortar kit and shells are bulky rather than huge, engineer bag is able to hold them
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/mortar.dm
Labels: Balance/Rebalance

#6557 Xeno get a message when silos/turrets are built. It is also registered in the game log
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Administration, Quality of Life

#6559 No more inbetween space areas on prison
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Balance/Rebalance, Fix, Map Edit

#6560 Can correctly vote for ground maps. Also non admins can start vote
  code/controllers/subsystem/vote.dm
  tgui/packages/tgui/interfaces/Vote.js
  tgui/public/tgui.bundle.js
Labels: Fix, Test Merge Candidate, UI

#6308 2.5 supply points are given everytime a marine spawn
  code/__DEFINES/mode.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/points.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6563 Handholding
  code/modules/mob/living/carbon/human/species.dm
Labels: Feature

#6573 Spear Buff.
  code/game/objects/items/weapons/twohanded.dm
Labels: Balance/Rebalance

#6564 Synths can no longer operate suicide vests
  code/game/objects/items/explosives/bombvest.dm
Labels: Fix

#6566 Halves lay egg cost
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance/Rebalance

#6561 Stop arrow from runtiming
  code/_onclick/hud/screen_objects/screen_objects.dm
Labels: Fix

#6498 ERT call are dependant on monitor state
  code/__DEFINES/monitor.dm
  code/controllers/subsystem/monitor.dm
  code/datums/emergency_calls/clf.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/emergency_calls/freelancers.dm
  code/datums/emergency_calls/imperium.dm
  code/datums/emergency_calls/pizza.dm
  code/datums/emergency_calls/pmc.dm
  code/datums/emergency_calls/sectoid.dm
  code/datums/emergency_calls/skeleton.dm
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/emergency_calls/supplies.dm
  code/datums/emergency_calls/upp.dm
  code/datums/emergency_calls/upp_commando.dm
  code/datums/emergency_calls/xeno.dm
  code/datums/emergency_calls/xenoalpha.dm
  code/datums/emergency_calls/xenobeta.dm
  code/datums/emergency_calls/xenocorrupted.dm
  code/datums/emergency_calls/xenozeta.dm
  code/game/objects/machinery/computer/communications.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/topic.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6582 Revert "disables smartgunner, makes smart machinegun useable by anyone"
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/extended.dm
  code/datums/gamemodes/infestation.dm
  code/datums/jobs/job/marines.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/reqs/supplypacks.dm
Labels: Revert

#6511 Tips update
  strings/tips/marine.txt
  strings/tips/meme.txt
  strings/tips/meta.txt
  strings/tips/xeno.txt
Labels: Fix

#6579 Automatic votes at the end of each round
  code/controllers/subsystem/vote.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
Labels: Administration

#6565 Nerfs Pistol Belt Reloading
  code/game/objects/items/storage/belt.dm
  code/modules/projectiles/gun_helpers.dm
Labels: Balance/Rebalance

#6562 hunter nerf, speed and slash nerf
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Balance/Rebalance

#6539 bbuffs dmr and br
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance/Rebalance

#6575 Tesla Is now 0.1 shell speed, lowers total drain time, and slowdown up.
  code/datums/beam.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#6577 Lemoline is too expensive, make it cheaper.
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#6477 You can use non combat abilities when resting as a xeno
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6571 Mass replace admin verb
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder.dm
Labels: Administration

#6589 fixes tactical reloading
  code/modules/projectiles/gun_helpers.dm
Labels: Fix, Test Merge Candidate

#6588 Fixes the biggest sin on prison
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Map Edit

#6377 Adds bump attack component to humans, adds bump attack compatibility to harvester and unarmed
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/datums/components/bump_attack.dm
  code/datums/round_statistics.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Feature, Test Merge Candidate

#6584 Buffs Claymore
  code/game/objects/items/weapons/blades.dm
Labels: Balance/Rebalance

#6595 Ports alot of tgui TG PRs from tg
  .gitattributes
  .vscode/settings.json
  tgui/.eslintrc-harder.yml
  tgui/.eslintrc.yml
  tgui/.prettierrc.yml
  tgui/bin/tgui
  tgui/bin/tgui_.ps1
  tgui/jest.config.js
  tgui/package.json
  tgui/packages/tgui-dev-server/package.json
  tgui/packages/tgui-panel/package.json
  tgui/packages/tgui-polyfill/package.json
  tgui/packages/tgui/components/LabeledList.tsx
  tgui/packages/tgui/format.js
  tgui/packages/tgui/interfaces/ListInput.js
  tgui/packages/tgui/package.json
  tgui/packages/tgui/routes.js
  tgui/public/tgui-common.bundle.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
  tgui/webpack.config.js
  tgui/yarn.lock
Labels: Quality of Life, UI

#6576 Adds Vali buff complexity
  code/__DEFINES/movespeed_modification.dm
  code/datums/components/chem_booster.dm
  icons/mob/radial.dmi
Labels: Feature, Quality of Life, Sprites

#6550 Allows Mortar to be aimed using tactical binocs
  code/game/objects/items/binoculars.dm
  code/game/objects/structures/mortar.dm
Labels: Feature

#6598 Flower pin.
  code/modules/client/preferences_gear.dm
Labels: Feature

#6600 Ammo Box Pickup QoL
  code/game/objects/items/storage/boxes.dm
Labels: Quality of Life

#6594 leader xenos now lose queen pheros when queen dies.
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance/Rebalance

#6535 New Pistol, TX7 Plasma Pistol
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/pistols.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Feature, Sprites, Test Merge Candidate

#6516 Ravage and Shrike Screech can be selected with a keybind
  code/__DEFINES/dcs/signals.dm
  code/datums/actions/xeno_action.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Quality of Life, Stale

#6606 Psy drain and cocoon couldn't be used on stacked bodies. It's the fix
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#6612 Vali movement buff fix
  code/datums/components/chem_booster.dm
Labels: Balance/Rebalance

#6618 Tweak vote timer
  code/controllers/subsystem/vote.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
Labels: Administration

#6587 Flamer must be fully wielded before firing
  code/__DEFINES/conflict.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/flamer.dm
Labels: Balance/Rebalance

#6586 Duel wielding nerf
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Balance/Rebalance, Code Improvement

#6622 Fixes Xeno Queen overwatch using hivemind chat
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
Labels: Fix

#6614 Prison Station minor refactor and balance patch
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/game/turfs/open.dm
  code/game/turfs/space.dm
Labels: Balance/Rebalance, Map Edit, Refactor

#6179 Adds minimaps for xenos and marines
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/minimap.dm
  code/controllers/subsystem/minimaps.dm
  code/datums/elements/hud_maps.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/squads.dm
  code/game/area/area.dm
  code/game/area/bigred.dm
  code/game/area/icecolony.dm
  code/game/area/lava_outpost.dm
  code/game/area/lv624.dm
  code/game/area/magmoor_digsite.dm
  code/game/area/research_outpost.dm
  code/game/atoms.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/structures/fence.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/requisitions/fulton.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/UI_Icons/map_blips.dmi
  icons/UI_Icons/minimap.dmi
  icons/mob/actions.dmi
  tgmc.dme
Labels: Config Update, Feature, Sprites, UI

#6626 OB Req QoL V2
  code/modules/reqs/supplypacks.dm
Labels: Quality of Life

#6638 Fixes Bull's gore free attack using the wrong intent
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Fix

#6611 Prae spit extinguishes fire
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#6640 Vali instructions page update
  code/modules/paperwork/paper.dm
Labels: Quality of Life

#6530 Drop pods can no longer land on death tiles (water, lava...)
  code/__DEFINES/area.dm
  code/game/area/general.dm
  code/game/area/lv624.dm
  code/game/area/magmoor_digsite.dm
  code/game/objects/structures/droppod.dm
Labels: Fix

#6641 Fixes the biggest problem in TGMC history: Uncentered TGMC Logo
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#6643 adds milk dispenser and breaks FC balance forever
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/objects/structures/reagent_dispensers.dm
  icons/obj/wallframes.dmi
Labels: Feature, Map Edit, Sprites

#6639 Spray fix
  code/game/objects/effects/aliens.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
Labels: Fix

#6607 Log admin respawns
  code/datums/gamemodes/game_mode.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/mob_verbs.dm
Labels: Administration

#6652 Fix SSoverlays holding too many icons
  code/controllers/subsystem/overlays.dm
Labels: Fix, Priority: High

#6647 Fixes milk dispenser bugs and unintended placements
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Map Edit

#6633 Among us Crewmate emojis
  icons/misc/emoji.dmi
Labels: Sprites

#6659 Revert "Among us Crewmate emojis"
  icons/misc/emoji.dmi
Labels: Revert, Sprites

#6642 Revert "Prae spit extinguishes fire"
  code/modules/projectiles/ammo_datums.dm
Labels: Revert

#6666 Fix SDMM
  code/modules/mob/dead/observer/observer.dm
Labels: Fix, Priority: High

#6661 update byond ver reccomedations
  code/_compile_options.dm
  code/modules/client/client_procs.dm
Labels: Code Improvement

#6648 Orders now use area
  code/datums/actions/order_action.dm
Labels: Fix

#6644 Fixes Combat Huggers not Attacking Infected Humans
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#6653 Fixes still spawning as a marine after closing the "game is unbalanced" dialog
  code/modules/mob/new_player/new_player.dm
Labels: Fix

#6656 Fix some turret proc acting on silo as well
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix

#6654 Fixes being able to remove items from storage while dead
  code/game/objects/items/storage/storage.dm
Labels: Fix

#6657 Removed white pixel in green arrow
  icons/Marine/marine-items.dmi
Labels: Fix, Sprites

#6668 Port GAGS and make screwdrivers greyscale
  code/__DEFINES/_subsystems.dm
  code/__HELPERS/icons.dm
  code/controllers/subsystem/greyscale.dm
  code/datums/greyscale/README.md
  code/datums/greyscale/_greyscale_config.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/screwdriver.json
  code/datums/greyscale/json_configs/screwdriver_inhand_left.json
  code/datums/greyscale/json_configs/screwdriver_inhand_right.json
  code/datums/greyscale/layer.dm
  code/game/atoms.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/admin/view_variables/greyscale_modify_menu.dm
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/items.dmi
  icons/obj/items/screwdriver.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/GreyscaleModifyMenu.tsx
  tgui/public/tgui.bundle.js
Labels: Refactor, Sprites, UI

#6667 Delete coordinate datums and shitty helpers
  code/__HELPERS/unsorted.dm
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/vehicles/multitile/multitile.dm
  code/modules/vehicles/multitile/tank.dm
Labels: Code Improvement

#6660 Monkey cubes will now tell you how to use them + cleanup
  code/game/objects/items/reagent_containers/food/snacks.dm
Labels: Code Improvement, Quality of Life

#6655 Fixes infinite metal from reinforced floors exploit
  code/game/turfs/floor_types.dm
Labels: Fix

#6646 DMR now has sniper range
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#6671 Fixes ghosts fumbling with the OB cannon console
  code/game/objects/structures/orbital_cannon.dm
Labels: Fix

#6651 Refactor minimap creation + new CIC map table
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  code/__DEFINES/minimap.dm
  code/controllers/subsystem/minimaps.dm
  code/datums/elements/hud_maps.dm
  code/game/objects/machinery/cic_maptable.dm
  code/game/objects/structures/prop.dm
  tgmc.dme
Labels: Feature, Map Edit, Refactor

#6678 Port TG emissives
  code/__DEFINES/layers.dm
  code/__DEFINES/lighting.dm
  code/__HELPERS/lighting.dm
  code/_onclick/hud/plane_master.dm
  code/datums/mutable_appearance.dm
  code/game/atoms_movable.dm
  code/game/objects/items.dm
  code/game/objects/machinery/lightswitch.dm
  code/modules/lighting/emissive_blocker.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/mob_defines.dm
  icons/obj/power.dmi
  tgmc.dme
Labels: Feature, Sprites

#6663 Medevac beds can be instantly activated with rclick
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Quality of Life

#6676 Shows the Hiveminds nickname in its radio chat.
  code/modules/mob/living/carbon/xenomorph/say.dm
Labels: Quality of Life

#6507 Tabbed vendors
  _maps/map_files/MarineHQ/MarineHQ.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/_globalvars/lists/objects.dm
  code/_globalvars/lists/vending.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/Vending.js
  tgui/packages/tgui/interfaces/Vending.tsx
  tgui/public/tgui.bundle.js
Labels: Feature, Map Edit, Refactor, UI
