Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2021-07, with the labels that each got.

#7228 Mateba Fix
  icons/obj/items/gun.dmi
Labels: Fix, Sprites

#7147 Fix OB beacons being activatable on dropships like Alamo
  code/game/objects/machinery/squad_supply/supply_beacon.dm
Labels: Fix, Stale

#7222 Hivelord can apply jelly via throw
  code/game/objects/structures/xeno.dm
Labels: Content Expansion

#7215 You can now wear warning cones on your head.
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  code/game/objects/items/tools/cleaning_tools.dm
  icons/mob/head_0.dmi
Labels: Map Edit, Sprites

#7183 Prevent joining a faction with too many players in HvH gamemode
  code/__DEFINES/factions.dm
  code/__DEFINES/mode.dm
  code/_globalvars/lists/mobs.dm
  code/datums/gamemodes/civil_war.dm
  code/datums/gamemodes/extended.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/gamemodes/infestation.dm
  code/datums/jobs/job/job.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/new_player/new_player.dm
Labels: Balance/Rebalance

#7225 Fix bicardine cigarette sprite dissapear when lit
  code/game/objects/items/tools/flame_tools.dm
Labels: Fix

#7165 Improves fences
  code/game/objects/structures/fence.dm
Labels: Balance/Rebalance, Fix

#7236 Anti roomba league
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/game/objects/machinery/roomba.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix

#7206 Deathsquad equippment and role refresh
  code/__DEFINES/access.dm
  code/datums/emergency_calls/deathsquad.dm
  code/datums/jobs/job/deathsquad.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/guns/rifles.dm
  icons/Marine/marine-pouches.dmi
Labels: Balance/Rebalance, Mechanic, Sprites

#7232 Synths don't get guns.
  code/modules/projectiles/gun_system.dm
Labels: Fix

#7088 Wraith Buffs
  code/__DEFINES/mobs.dm
  code/datums/actions/xeno_action.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Balance/Rebalance, Test Merge Candidate

#7235 Spelling
  code/__DEFINES/combat.dm
  code/game/objects/items/embedding.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/shards.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/living.dm
Labels: Grammar and Formatting

#7233 Improved self examine
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Content Expansion

#7079 Acid Well Improvements
  code/__DEFINES/mobs.dm
  code/datums/round_statistics.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Balance/Rebalance, Code Improvement, Quality of Life, Test Merge Candidate

#7196 Defiler Control QoL
  code/__DEFINES/dcs/signals.dm
  code/_globalvars/lists/abilities.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  tgmc.dme
Labels: Quality of Life

#7230 Improved Anti-Shuffle Hug so Carrier Allies Don't Reset Jump Timers
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Code Improvement

#7039 Automatic balance system + admin verb
  code/__DEFINES/monitor.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/monitor.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/unit_tests/spawn_xenos.dm
  config/config.txt
Labels: Config Update, Mechanic

#6748 Datumized view refactor and new view settings
  code/__DEFINES/preferences.dm
  code/__HELPERS/sanitize_values.dm
  code/__HELPERS/view.dm
  code/datums/components/riding.dm
  code/datums/view.dm
  code/game/objects/items.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/smartgun_mount.dm
  code/modules/admin/fun_verbs.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/login.dm
  code/modules/shuttle/navigation_computer.dm
  code/modules/vehicles/multitile/hardpoints.dm
  config/config.txt
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/FieldPreferences.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/Types.tsx
Labels: Config Update, Quality of Life, RED LABEL, Refactor, UI

#7252 Update bug_report.yml description
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: Git-hub, Git.hUb, GitHub

#7246 Hard del protection on gun user
  code/modules/projectiles/gun_system.dm
Labels: Code Improvement, Fix

#7243 Add a suite of notices and information to the AI
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/camera/deployable_camera.dm
  code/game/objects/structures/orbital_cannon.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Mechanic, Quality of Life

#7240 Allow the AI to turn fusion reactors on and off.
  code/modules/power/fusion_engine.dm
Labels: Quality of Life

#7245 Randomly break groundmap fence lines at round start
  code/game/objects/structures/fence.dm
Labels: Quality of Life

#7238 Azerty support for keybinds + better perfs on game prefs ui
  code/__DEFINES/preferences.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_ui.dm
  tgui/packages/tgui/components/Button.js
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/PlayerPreferences/BackgroundInformation.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/FieldPreferences.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/GearCustomisation.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/ProfilePicture.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/TextInputModal.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/Types.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/index.tsx
Labels: Code Improvement, Mechanic, UI

#7244 Make Miner minimap icons show if they are active
  code/game/objects/machinery/miner.dm
  icons/UI_Icons/map_blips.dmi
Labels: Content Expansion, Sprites

#7237 Theseus 2.2
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit, Mechanic

#7227 Hydro Cannon Fix
  code/datums/actions/item_action.dm
  code/modules/projectiles/gun_attachables.dm
Labels: Fix, Refactor

#7262 Condor Minigun Fix
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#7255 Makes Pizza Sliceable
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/modules/projectiles/gun_attachables.dm
Labels: Fix, Mechanic

#7256 Cigarette Chem Fix.
  code/game/objects/items/tools/flame_tools.dm
Labels: Fix

#7135 Minimap icons change when marines die
  code/__DEFINES/dcs/signals.dm
  code/game/objects/items/radio/headset.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/life.dm
  icons/UI_Icons/map_blips.dmi
Labels: Content Expansion, Sprites

#7264 Improves the orbital canon AI notifications.
  code/game/objects/items/binoculars.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/objects/structures/orbital_cannon.dm
Labels: Fix, Quality of Life

#7271 Fixes PoS research doors
  code/game/objects/machinery/doors/airlock_types.dm
Labels: Fix

#7266 The AI now has points on a hot tab.
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Quality of Life

#7265 Fix observers being locked out of pre-shutter larva on Distress rounds
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Quality of Life

#7254 Fix some areas looking weird on the POS
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#7197 Reduces the prices of some req guns
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#7276 Fix undefibbable icons on minimap
  code/game/objects/items/radio/headset.dm
Labels: Fix

#7248 Fix HvH req
  code/__HELPERS/_lists.dm
  code/controllers/subsystem/points.dm
  code/modules/reqs/supply.dm
Labels: Fix

#7229 Fix window weeds not updating after the frame is gone [UTMOST PRIORITY]
  code/game/objects/structures/window_frame.dm
Labels: Fix

#7275 Hivemind respawn fix
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Labels: Fix

#7182 Allow to remove keybinds + clean up keybinds + king keybinds added
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/human.dm
  code/datums/keybinding/xeno.dm
  code/modules/client/preferences_savefile.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Code Improvement, Quality of Life

#7234 Simplifies surgical shrapnel removal on head/chest
  code/modules/surgery/implant.dm
Labels: Quality of Life

#7208 Prevent from buying scopes and ballistic module in HvH
  code/_globalvars/lists/typechache.dm
  code/game/objects/machinery/vending/vending.dm
Labels: Balance/Rebalance

#7231 Medical Huds in Req
  code/modules/reqs/supplypacks.dm
Labels: Mechanic

#7242 Ravager plasma is now fury
  code/datums/elements/plasma_on_attack.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  icons/mob/hud.dmi
  tgmc.dme
Labels: Balance/Rebalance, Content Expansion, Sprites, Test Merge Candidate

#7174 Add strong windows and a camera to the POS AI core.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/objects/structures/window.dm
Labels: Map Edit, Mechanic

#7200 Cannot silo bodies in crash + silos no longer have alert proximity in modes other than distress
  code/__DEFINES/mode.dm
  code/datums/gamemodes/hunt.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Balance/Rebalance, Fix

#7278 Fullscreen setting
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Quality of Life, UI

#7290 Fix keybinds not being saved[CRITICAL]
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
Labels: Fix

#7284 Fix be special settings (EORD, etc) not showing on tgui
  code/modules/client/preferences_ui.dm
Labels: Fix

#7286 Fix perspective bug with tadpole
  code/modules/shuttle/mini_dropship.dm
Labels: Fix

#7142 combat shotgun can be fired one handed
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance/Rebalance, Stale, Test Merge Candidate

#7292 Fix for welding helmet module
  code/modules/modular_armor/helmets.dm
Labels: Fix

#7224 T-25 smartrifle
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
Labels: Content Expansion, Sprites

#7066 Replace outfit build mode by loadouts build mode
  code/__DEFINES/loadout.dm
  code/_globalvars/admin.dm
  code/controllers/subsystem/persistence.dm
  code/datums/loadout/loadout.dm
  code/game/objects/items/storage/storage.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/buildmode/submodes/loadout.dm
  code/modules/buildmode/submodes/outfit.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/misc/buildmode.dmi
  tgmc.dme
Labels: Mechanic, Sprites, UI

#7281 Fix Eviscerating Charge Keybind
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Fix

#7293 Add the hivemind to the player panel menu.
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
Labels: Administration

#7289 Widescreen on local
  config/config.txt
Labels: Config Update

#7299 makes Windoors not cause SAN damage everytime I map
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/MarineHQ/MarineHQ.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/modularmaps/EORG/basketball.dmm
  _maps/shuttles/big_ert.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/machinery/doors/windowdoor.dm
Labels: Map Edit

#7298 Better keybind registering system
  tgui/packages/tgui/components/Button.js
Labels: Quality of Life

#7319 Acid blood bugfix
  code/__DEFINES/mobs.dm
Labels: Fix

#7307 Mesons no longer reveal a lighting plane.
  code/modules/clothing/glasses/meson.dm
Labels: Balance/Rebalance

#7322 Adds Missing Return to Acid Well Dismantling
  code/game/objects/structures/xeno.dm
Labels: Fix

#7329 Ports tg forced Fit Viewport on connect fix
  code/modules/client/client_procs.dm
Labels: Fix, Upstream port

#7300 Fix tadpole eye going to null space
  code/game/objects/machinery/computer/camera_advanced.dm
  code/modules/shuttle/navigation_computer.dm
Labels: Fix

#7315 Add a missing light to one of POS hallway.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#7297 warrior fling distance on grapple toss reduced to 3 from 5
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Balance/Rebalance

#7295 Closet based ghost bullying fix
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#7285 Fix tarp shooting
  code/__DEFINES/traits.dm
  code/modules/projectiles/gun_system.dm
Labels: Fix

#7304 railgun rebalance- less damage/stagger, mag-h instead of scope, more wield delay
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Balance/Rebalance

#7134 TL-102 HSG and Mortar refactor
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/modularmaps/big_red/operation.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/__DEFINES/conflict.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/equipment.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/elements/deployable_item.dm
  code/game/data_huds.dm
  code/game/objects/items.dm
  code/game/objects/items/binoculars.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/machinery/deployable.dm
  code/game/objects/machinery/mortar.dm
  code/game/objects/machinery/smartgun_mount.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/game/objects/structures/dropship_equipment.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/projectiles/mounted.dm
  code/modules/projectiles/projectile.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-hmg.dmi
  icons/Marine/mortar.dmi
  tgmc.dme
Labels: Balance/Rebalance, Code Improvement, Map Edit, Mechanic, Refactor, Sprites

#7341 Fixes Double Barrels and Martini
  code/modules/projectiles/guns/shotguns.dm
Labels: Fix

#7318 Fixes unreloadable EORD Thermobaric
  code/game/objects/effects/landmarks/landmarks.dm
Labels: Fix

#7352 Tesla projectile fix.
  icons/obj/items/projectiles.dmi
Labels: Fix, Sprites

#7108 Ravager Rage Ability
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/traits.dm
  code/_onclick/xeno.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/keybinding/xeno.dm
  code/datums/round_statistics.dm
  code/datums/status_effects/xeno_buffs.dm
  code/game/objects/items/explosives/mine.dm
  code/modules/ai/ai_behaviors/carbon/xeno/xeno.dm
  code/modules/codex/entries/mobs_codex.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  icons/mob/actions.dmi
Labels: Mechanic, Sprites

#7354 Fixes ahealing dead xenos
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Fix

#7359 Fix wraith banish targeting
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#7270 Fix é keybind[DNM]
  code/modules/keybindings/bindings_client.dm
Labels: Quality of Life, Test Merge Candidate

#7320 makes packets under one parent and adds a tx-11 ammo packet box, general pouch can now hold packets
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/__DEFINES/mode.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/ammo.dmi
Labels: Balance/Rebalance, Content Expansion, Map Edit, Sprites

#7357 Plasma transfer rav removed
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
Labels: Fix

#7358 Fix missing Ai display icons, and port a couple from TG station
  code/game/objects/machinery/status_display.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
  icons/obj/status_display.dmi
Labels: Fix, Mechanic, Sprites

#7356 Deathstats
  code/datums/gamemodes/game_mode.dm
  code/datums/round_statistics.dm
  code/game/objects/items/defibrillator.dm
Labels: Content Expansion

#7361 Disable the antena module beeping to cull spam.
  code/modules/modular_armor/helmets.dm
Labels: Quality of Life

#7164 Pepperball MK2
  code/__DEFINES/calibers.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  icons/Marine/gun64.dmi
  icons/mob/belt.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
Labels: Mechanic, Sprites

#7365 Add a map table to the sulaco CIC.
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Map Edit, Mechanic

#7368 Add some fire alarms to the firing range of POS.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#7367 Add a couple water tanks to the POS. There is only one in the ship at the moment.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Mechanic

#7369 Switch around the POS hangar areas so the fire alarms don't abruptly stop in the middle of an hallway.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Content Expansion, Map Edit, Mechanic

#7360 Fix being able to queue multiple item draws from backpacks
  code/game/objects/items/storage/storage.dm
Labels: Fix

#7364 T-25 ammo packet and adds the gun to req
  code/modules/projectiles/magazines/misc.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/ammo.dmi
Labels: Content Expansion, Fix, Sprites

#7374 buffs the automag and deagle by giving them their own bullet
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/pistols.dm
Labels: Balance/Rebalance

#7366 Switch things around in the OB room to not be CBT.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit, Quality of Life

#7388 Make the holopad layer above catwalks.
  code/__DEFINES/layers.dm
  code/game/objects/machinery/hologram.dm
Labels: Fix

#7221 Xeno tunnel upgrades: minimap icons, plus fixing tunnel list and a couple bugs
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  icons/UI_Icons/map_blips.dmi
Labels: Config Update, Fix, Mechanic, Sprites, Test Merge Candidate, UI

#7394 Fix admin respan logging
  code/modules/mob/mob_verbs.dm
Labels: Administration, Fix

#7387 T-81 impact grenade fix
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#7376 Lets you name pill bottles
  code/modules/reagents/machinery/chem_master.dm
Labels: Mechanic

#7393 nerfs jelly to 20 seconds from 5
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Balance/Rebalance, Test Merge Candidate

#7389 Fixes the AI lack of hologram. Also remove some broken links.
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
  icons/mob/AI.dmi
Labels: Fix, Sprites

#7384 impact grenades are back
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/items/grenade.dmi
Labels: Mechanic, Sprites

#7378 New fed icon.
  icons/mob/screen/generic.dmi
Labels: Sprites

#7395 Change stale autoclose from 7 days to 3
  .github/workflows/stale.yml
Labels: Git-hub, Git.hUb, GitHub

#7426 Ports parallax
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/preferences.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/parallax.dm
  code/_onclick/observer.dm
  code/controllers/subsystem/parallax.dm
  code/controllers/subsystem/shuttle.dm
  code/game/area/area.dm
  code/game/atoms_movable.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/mob.dm
  code/modules/shuttle/on_move.dm
  code/modules/shuttle/shuttle.dm
  icons/effects/parallax.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/Types.tsx
Labels: Mechanic, Sprites, UI, Upstream port

#7428 Fix quick equip not respecting storage delay
  code/game/objects/items/storage/boxes.dm
  code/modules/mob/mob.dm
Labels: Fix

#7399 Fix larva spawn in silo PRs
  code/controllers/subsystem/job.dm
  code/datums/jobs/job/xenomorph.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#7373 Fixes Corrosive Acid Melt Times and Process Time Adjustment Math
  code/game/objects/effects/aliens.dm
Labels: Balance/Rebalance, Fix

#7414 you can't refill qc+ and peri+ at marine med
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance/Rebalance

#7425 Fix SL medhud
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Fix

#7351 adds an iff-less heavy machinegun
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  icons/Marine/marine-hmg.dmi
  sound/weapons/guns/fire/mg08.ogg
Labels: Content Expansion, Sound, Sprites

#7311 Readds thermobaric and reworks it entirely, new sprite too
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/gun.dmi
Labels: Balance/Rebalance, Sprites

#7418 replaces some old cm sprites, cmb revolver, uzi, and ak47
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Sprites

#7441 smartrifle pack fix
  code/modules/reqs/supplypacks.dm
Labels: Fix

#7427 Fix shuttle windows not rotating
  code/modules/shuttle/shuttle_rotate.dm
Labels: Fix

#7405 LV624 cave tweaks and engineering expansion.
  _maps/map_files/LV624/LV624.dmm
Labels: Balance/Rebalance, Map Edit

#7312 Imager Goggles
  code/modules/clothing/glasses/night.dm
  code/modules/reqs/supplypacks.dm
Labels: Content Expansion

#7437 Proper Impact Grenade Box Name
  code/game/objects/items/storage/boxes.dm
Labels: Fix

#7423 adds a marine spear
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/weapons.dmi
Labels: Content Expansion, Sprites

#6957 IFF refactor
  code/__DEFINES/access.dm
  code/__DEFINES/conflict.dm
  code/__DEFINES/factions.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/deathsquad.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/other.dm
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/machinery/sentries.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/projectile.dm
  code/modules/reqs/supply.dm
  code/modules/vehicles/multitile/hardpoints.dm
Labels: Refactor

#7377 Removes double healing from most xeno sources
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance/Rebalance, Fix, Removal, Test Merge Candidate

#7194 Prevent too many xeno at start
  code/__DEFINES/jobs.dm
  code/__DEFINES/mode.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/hunt.dm
  code/datums/jobs/job/xenomorph.dm
Labels: Balance/Rebalance, Test Merge Candidate

#7413 full health resin walls now die to devastating explosions
  code/game/turfs/walls/resin.dm
Labels: Balance/Rebalance, Fix

#7349 Ravager gains fury when damaged and passive regen reduced.
  code/datums/elements/plasma_on_attack.dm
  code/datums/elements/plasma_on_attacked.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  tgmc.dme
Labels: Balance/Rebalance, Content Expansion

#7272 Fix hvh comms
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  code/__DEFINES/radio.dm
  code/game/communications.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/telecomms/machines/broadcaster.dm
  code/game/objects/machinery/telecomms/machines/bus.dm
  code/game/objects/machinery/telecomms/machines/hub.dm
  code/game/objects/machinery/telecomms/machines/processor.dm
  code/game/objects/machinery/telecomms/machines/receiver.dm
  code/game/objects/machinery/telecomms/machines/server.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
Labels: Fix, Map Edit

#7257 Clawed Huggers no longer suck
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Balance/Rebalance

#7099 Hemodile Buff
  code/modules/reagents/reagents/toxin.dm
Labels: Balance/Rebalance, Test Merge Candidate

#7434 Adds a button to become an Imaginary Friend to the ticket panel, and log their creation to active tickets
  code/__DEFINES/admin.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminhelp.dm
Labels: Administration, Quality of Life

#7433 Larvas cannot become king anymore
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
Labels: Fix

#7446 Fix impact grenades being in HvH vendor only
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#7327 Siloless collaspe is at 45 mintues into a round rather than an hour
  code/__DEFINES/mode.dm
Labels: Balance/Rebalance

#7424 Killing specialist code
  _maps/map_files/MarineHQ/MarineHQ.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/loadout.dm
  code/__DEFINES/objects.dm
  code/__DEFINES/skills.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/datums/skills.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/items/portable_vendor.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Map Edit, Removal

#7396 Fix userdanger messages
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Fix, UI

#7277 Improve unique action and unload gun keybind
  code/__DEFINES/dcs/signals.dm
  code/datums/elements/deployable_item.dm
  code/game/objects/items.dm
  code/game/objects/items/binoculars.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/mob_helpers.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Quality of Life, UI

#7449 Fixes pos pipenet
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#7439 adds a new bucket with an uzi and cmb revolver, and buffs and restats them
  code/controllers/subsystem/persistence.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Balance/Rebalance, Content Expansion

#7214 adds a lolipop pouch to marine venders
  code/__DEFINES/loadout.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/items/storage/storage.dmi
Labels: Mechanic, Sprites, Stale

#7458 Fix premade sentries IFF
  code/game/objects/machinery/sentries.dm
Labels: Fix

#7408 Fix projectile double tap
  code/modules/projectiles/projectile.dm
Labels: Fix

#7474 fix t-25 not having iff
  code/modules/projectiles/guns/rifles.dm
Labels: Fix

#7476 Minor Text Fix For Place Warp Shadow
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#7151 Fixes Right Click Mode for Xenos
  code/_onclick/click.dm
  code/_onclick/xeno.dm
Labels: Fix, Test Merge Candidate

#7383 Fixes destroyed limbs also being broken
  code/modules/organs/limbs.dm
Labels: Fix, Test Merge Candidate

#7212 Moves per-item storage limits up in inheritance
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/storage.dm
  code/modules/projectiles/gun_system.dm
Labels: Code Improvement

#7440 Adds seasonal system roundstart announcement
  code/controllers/subsystem/persistence.dm
  code/controllers/subsystem/ticker.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Quality of Life, UI

#7431 minigun rework makes it work off powerpacks, also deletes old sg
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/codex/entries/guns_codex.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Map Edit, Removal

#7462 Remplace some weird bits of outerhull in the POS
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#7465 Add a missing floodlight switch to LV engineering
  _maps/map_files/LV624/LV624.dmm
Labels: Fix, Map Edit

#7466 Make it so cameras check for power before notifying the AI
  code/game/objects/machinery/camera/camera.dm
Labels: Fix

#7454 Runner has higher melee armor
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
Labels: Balance/Rebalance

#7463 Add more paths to quick create for admins.
  code/modules/admin/panels/game_panel.dm
Labels: Administration
