Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2021-02, with the labels that each got.

#5846 Sulaco medbay fixes
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#5837 grenade new sprite
  icons/obj/items/grenade.dmi
Labels: Sprites

#5854 Licensing Changes
  README.md
  sound/credits.txt
Labels: Git-hub, Git.hUb, GitHub, Sound

#5851 Cas can't refuel mid flight
  code/modules/shuttle/cas_plane.dm
Labels: Fix

#5847 Fixes M42A laser feature
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#5844 Bio/synthetic printers are stocked
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/machinery/bioprinter.dm
Labels: Fix, Map Edit

#5823 Drops PMC SG probability to 30
  code/datums/emergency_calls/pmc.dm
Labels: Tweak

#5857 Fixes SL Paygrade only working on late join
  code/datums/jobs/job/marines.dm
Labels: Fix

#5863 Hypo fix
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Fix

#5815 Winning condition hijack
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
Labels: Fix

#5618 fixes a few bugs/typos and map bugs part2 (now with 3 incantations and a goat sacrifice for git)
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/controllers/subsystem/explosions.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/machinery/doors/airlock.dm
  code/modules/admin/debug_verbs.dm
  code/modules/organs/organ_alien.dm
  code/modules/reagents/reagents/food.dm
Labels: Fix, Map Edit

#5835 Darkmode CSS Update.
  code/__DEFINES/colors.dm
  code/modules/goonchat/browserOutput.css
Labels: Tweak

#5777 Both Marines and Xenos now die almost instantly in area/space
  code/game/area/general.dm
  code/game/turfs/open.dm
  code/game/turfs/space.dm
  strings/tips/meta.txt
Labels: Tweak

#5866 Adds the AOE-generator to the ships , adds it as a req purchaseable
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  code/modules/reqs/supplypacks.dm
Labels: Feature, Map Edit

#5877 fix cas flare
  icons/obj/items/grenade.dmi
Labels: Fix, Sprites

#5884 Fix game end
  code/datums/gamemodes/game_mode.dm
Labels: Fix, Priority: High

#5679 Monitor
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/area.dm
  code/__DEFINES/monitor.dm
  code/__DEFINES/supply.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/direction.dm
  code/controllers/subsystem/monitor.dm
  code/game/objects/items.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/structures/orbital_cannon.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/reqs/supplypacks.dm
  code/modules/shuttle/marine_dropship.dm
  tgmc.dme
Labels: Administration, Config Update

#5874 makes the hk11 not total garbage
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#5767 ballistic armor module
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/modular_armor/attachables.dm
  icons/mob/modular/modular_armor_modules.dmi
Labels: Feature, Needs Balance Review, Sprites

#5796 Hunter Stealth Stun removal
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Balance/Rebalance

#5886 Removes various bad sleeps
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/security_levels/keycard_authentication.dm
  code/modules/shuttle/cas_plane.dm
Labels: Code Improvement, Removal

#5852 The fusion generators no longer break down.
  code/modules/power/fusion_engine.dm
Labels: Tweak

#5901 fixes hk11 offsets
  code/modules/projectiles/guns/rifles.dm
Labels: Fix

#5891 Another Energy Gun Update
  code/__DEFINES/colors.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  icons/mob/ammoHUD.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/projectiles.dmi
Labels: Feature, Sprites, Tweak

#5890 fixes v10 not having map variant
  code/modules/projectiles/guns/shotguns.dm
Labels: Fix

#5860 Add new supply drop console
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/objects/machinery/squad_supply/supply_console.dm
  code/game/objects/machinery/squad_supply/supply_pads.dm
  icons/obj/machines/computer.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/SupplyDropConsole.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Feature, Map Edit, Sprites, UI

#5880 Remove Sight Check from Tac Binos
  code/game/objects/items/binoculars.dm
Labels: Removal

#5876 removes barrel charger from req vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal

#5894 Fixes carbine offsets.
  code/modules/projectiles/guns/rifles.dm
Labels: Fix

#5873 pocket pistol hsa no aim slowdown
  code/modules/projectiles/guns/pistols.dm
Labels: Balance/Rebalance

#5861 Changes Vote Sound
  README.md
  code/controllers/subsystem/vote.dm
  sound/ambience/votestart.ogg
Labels: Sound

#5678 Roundstart species (Vatborn sprites II)
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/_globalvars/lists/mobs.dm
  code/datums/jobs/job/terragov.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/preferences_setup.dm
  icons/mob/human_races/r_vatborn.dmi
  icons/mob/human_races/r_vatgrown.dmi
Labels: Feature, Sprites

#5826 police comms to CAS and MORTAR
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/__DEFINES/radio.dm
  code/game/communications.dm
  code/game/objects/items/radio/encryptionkey.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/telecomms/machines/bus.dm
  code/game/objects/machinery/telecomms/machines/hub.dm
  code/game/objects/machinery/telecomms/machines/receiver.dm
  code/game/objects/machinery/telecomms/machines/server.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/mortar.dm
  code/game/say.dm
  code/modules/goonchat/browserOutput.css
  code/modules/goonchat/browserOutput_colorblindv1.css
  code/modules/goonchat/browserOutput_white.css
  code/modules/mob/living/say.dm
  code/modules/mob/living/simple_animal/friendly/parrot.dm
  interface/stylesheet.dm
Labels: Fix, Map Edit, Tweak

#5803 Xenos can chose a xenomorph or a silo to track
  code/__DEFINES/is_helpers.dm
  code/controllers/subsystem/direction.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Code Improvement, Feature, Test Merge Candidate

#5879 Death to Upgrade Shitcode
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Code Improvement

#5875 replaces the m9 with a glocc thing, replaces the pk9 with a new sprite and deletes variants
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/desert/desert.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/upp.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/storage/belt.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Feature, Map Edit, Removal, Sprites

#5710 right click menu has been disabled, right click has been freed
  code/_onclick/click.dm
  code/modules/client/client_defines.dm
  code/modules/client/preferences_toggles.dm
  code/modules/projectiles/gun_helpers.dm
Labels: Removal, Tweak

#5888 Flamed grenades will respect detonation timers
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Balance/Rebalance

#5761 medical attention REQuired
  code/modules/reqs/supplypacks.dm
Labels: Feature

#5911 Xenos can now rightclick to use abilities + Rclick signal framework
  code/__DEFINES/dcs/signals.dm
  code/_onclick/click.dm
Labels: Code Improvement, Feature

#5899 new jaeger light set and open helmet
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/modular_armor/armor_pieces.dm
  code/modules/modular_armor/modular.dm
  icons/mob/modular/modular_armor.dmi
  icons/mob/modular/modular_arms.dmi
  icons/mob/modular/modular_helmet.dmi
  icons/mob/modular/modular_helmet_icon.dmi
  icons/mob/modular/modular_legs.dmi
Labels: Feature, Sprites

#5915 Revert "deletes cat ears"
  _maps/map_files/desert/desert.dmm
  code/game/objects/effects/landmarks/itemspawner.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/misc_special.dm
  icons/mob/head_0.dmi
Labels: Map Edit, Revert, Sprites

#5916 Revert "Revert "deletes cat ears""
  _maps/map_files/desert/desert.dmm
  code/game/objects/effects/landmarks/itemspawner.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/misc_special.dm
  icons/mob/head_0.dmi
Labels: Map Edit, Revert, Sprites

#5917 Revert "Revert "Revert "deletes cat ears"""
  _maps/map_files/desert/desert.dmm
  code/game/objects/effects/landmarks/itemspawner.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/misc_special.dm
  icons/mob/head_0.dmi
Labels: Map Edit, Revert, Sprites

#5918 Revert "Revert "Revert "Revert "deletes cat ears""""
  _maps/map_files/desert/desert.dmm
  code/game/objects/effects/landmarks/itemspawner.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/misc_special.dm
  icons/mob/head_0.dmi
Labels: Map Edit, Revert, Sprites

#5921 fixes jaeger helmet
  icons/mob/modular/modular_helmet_icon.dmi
Labels: Sprites

#5920 Adds a right click hud toggle
  code/datums/actions/rightclick_toggle.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/logout.dm
  tgmc.dme
Labels: Feature

#5922 Clients will default to rclick menu on
  code/modules/client/client_defines.dm
Labels: Tweak

#5923 Fixes missing rclick icon
  code/datums/actions/rightclick_toggle.dm
  icons/mob/actions.dmi
Labels: Fix, Sprites

#5829 CAS Ammo Loading Mismatch Bug Fix
  code/__DEFINES/dropship_equipment.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#5895 nerf tl-127 aim mode fire speed
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#5927 Fix map lint fail
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit, Priority: High

#5933 Fix rogue comma
  tools/ci/check_grep.sh
Labels: Fix, Tools

#5883 Fixes blackbox query
  code/controllers/subsystem/blackbox.dm
Labels: Fix

#5882 Likely fix various client caused bugs by cleaning client deletion
  code/__DEFINES/dcs/signals.dm
  code/modules/client/client_procs.dm
Labels: Administration, Refactor

#5889 Ports MC stack overflow protection
  code/controllers/failsafe.dm
  code/controllers/master.dm
  code/datums/helper_datums/stack_end_detector.dm
  tgmc.dme
Labels: Code Improvement

#5906 Enables automute logging and admin messages
  code/modules/client/client_procs.dm
Labels: Administration

#5926 Bump tools versions
  .github/workflows/test.yml
  dependencies.sh
  tools/WebhookProcessor/github_webhook_processor.php
  tools/bootstrap/node
  tools/bootstrap/node.bat
  tools/bootstrap/node_.ps1
  tools/bootstrap/python
  tools/bootstrap/python.bat
  tools/bootstrap/python36._pth
  tools/bootstrap/python_.ps1
  tools/dmi/Resolve Icon Conflicts.bat
  tools/dmi/__init__.py
  tools/dmi/__pycache__/__init__.cpython-36.pyc
  tools/dmi/__pycache__/merge_driver.cpython-36.pyc
  tools/dmi/merge_driver.py
  tools/dmi/test.py
  tools/hooks/README.md
  tools/hooks/Uninstall.bat
  tools/hooks/__pycache__/merge_frontend.cpython-36.pyc
  tools/hooks/dmi.merge
  tools/hooks/dmm.merge
  tools/hooks/install.bat
  tools/hooks/install.py
  tools/hooks/install.sh
  tools/hooks/merge_frontend.py
  tools/hooks/pre-commit.hook
  tools/hooks/python.sh
  tools/mapmerge2/I Forgot To Map Merge.bat
  tools/mapmerge2/README.md
  tools/mapmerge2/Resolve Map Conflicts.bat
  tools/mapmerge2/Run Before Committing.bat
  tools/mapmerge2/convert.py
  tools/mapmerge2/dmm.py
  tools/mapmerge2/dmm_test.py
  tools/mapmerge2/fixup.py
  tools/mapmerge2/mapmerge.py
  tools/mapmerge2/merge_driver.py
  tools/mapmerge2/precommit.py
  tools/midi2piano/README.txt
  tools/midi2piano/easygui/__init__.py
  tools/midi2piano/midi/__init__.py
  tools/midi2piano/midi/midi.py
  tools/midi2piano/midi2piano.py
  tools/midi2piano/pyperclip/__init__.py
  tools/midi2piano/pyperclip/clipboards.py
  tools/midi2piano/pyperclip/exceptions.py
  tools/midi2piano/pyperclip/windows.py
  tools/requirements.txt
Labels: Code Improvement, GitHub, Tools

#5924 Reagent Mixing QoL
  code/game/objects/items/reagent_containers/food/drinks.dm
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Tweak

#5925 Trampops
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  icons/obj/items/storage/storage.dmi
Labels: Feature, Sprites

#5864 moves mbx to imports, adds 12 gauge tracker shells
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/magazines/shotguns.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/ammo.dmi
Labels: Balance/Rebalance, Sprites

#5856 boiler gets acid spit i guess
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
Labels: Balance/Rebalance

#5929 Adds unit test for bespoke ids
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/bespoke_id.dm
Labels: Code Improvement

#5930 Adds unit test for weeding
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/weed_ability.dm
Labels: Code Improvement

#5939 fixes helmet
  icons/mob/modular/modular_helmet_icon.dmi
Labels: Sprites

#5931 Updates unit tests + unit test extension
  .vscode/extensions.json
  code/__HELPERS/_logging.dm
  code/modules/unit_tests/README.md
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/unit_test.dm
Labels: Code Improvement

#5765 Fixes Bug With Fire and Acid Not Properly Updating Snow Stack Visuals
  code/__DEFINES/dcs/signals.dm
  code/game/atoms.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items/bodybag.dm
  code/game/turfs/snow.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix, Refactor

#5612 Flamer changes
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/equipment.dm
  code/_onclick/hud/screen_objects.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/magazines/flamer.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/ammoHUD.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  tools/hooks/__pycache__/install.cpython-36.pyc
Labels: Feature, Fix, Removal, Sprites, Tweak

#5912 Gun attachments can now be fired with rclick
  code/__DEFINES/dcs/signals.dm
  code/_onclick/click.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
Labels: Feature

#5940 Fix linter if(true) detections
  code/__DEFINES/_subsystems.dm
Labels: Fix

#5941 Likely fix for ghost hard dels
  code/modules/mob/dead/observer/logout.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#5943 Misc. xeno code cleanup
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/egg_item.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
Labels: Code Improvement

#5953 Revert "boiler gets acid spit i guess"
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
Labels: Revert

#5951 Minor dreaming refactor
  code/modules/flufftext/Dreaming.dm
Labels: Refactor

#5954 Compensator/masterkey description changes
  code/modules/projectiles/gun_attachables.dm
Labels: Fix, Grammar and Formatting

#5798 Nerfs mine boxes back down to small, and makes the normal box hold 5 again, adds a mine box that holds 10 mines
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#5934 Medical overhaul
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/under/ties.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature, Removal, Tweak

#5955 Fixes Healing Infusion Timer Bug
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Fix

#5457 Evasion Thwarted By Debuffs and Stagger/Slow Partial Refactor
  code/__DEFINES/conflict.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/carbon_status_procs.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/status_procs.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance, Refactor, Tweak

#5948 adds the t-26, and reprices the autosniper
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/portable_vendor.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/modules/codex/entries/guns_codex.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
Labels: Balance/Rebalance, Feature, Sprites

#5957 Prescription medhud
  code/modules/clothing/glasses/hud.dm
Labels: Fix

#5662 Revert "auxtools debugger (#5530)"
  SpacemanDMM.toml
  code/__DEFINES/spaceman_dmm.dm
  code/game/world.dm
Labels: Requires Testing, Revert, Test Merge Candidate

#5725 CIC orders
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/overwatch.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/squads.dm
  code/game/data_huds.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/clothing/outfits/vv_outfit.dm
  code/modules/goonchat/browserOutput.css
  code/modules/goonchat/browserOutput_white.css
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/Marine/marine-items.dmi
  icons/mob/actions.dmi
  sound/effects/CIC_order.ogg
  tgmc.dme
Labels: Feature, Refactor, Sound, Sprites, Tweak

#5972 builds tgui bundle
  tgui/public/tgui.bundle.js
Labels: Priority: High, UI

#5962 deletes unused guns, removes useless gun variants, replaces some gun sprites and reorganizes gun.dmi a bit
  code/datums/jobs/job/clf.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/modules/projectiles/guns/smgs.dm
  icons/obj/items/gun.dmi
Labels: Feature, Removal, Sprites

#5967 Bump extools ver
  byond-extools.dll
Labels: Fix

#5982 removes evil guy psrites
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/gun.dmi
Labels: Removal, Sprites

#5979 upgrade marked to 2.0.0 and other dependencies.
  tgui/package.json
  tgui/packages/tgui/package.json
  tgui/yarn.lock
Labels: Fix, Priority: High, Security Exploit, Test Merge Candidate, UI

#5960 Adds filteriffic
  code/__DEFINES/colors.dm
  code/__HELPERS/filters.dm
  code/_onclick/hud/plane_master.dm
  code/game/atoms.dm
  code/game/objects/structures/xeno.dm
  code/modules/admin/holder.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/admin/view_variables/filterrific.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/Filteriffic.js
  tgui/public/tgui-common.bundle.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: Code Improvement, Refactor, UI

#5786 Xenos can capture the Alamo instead of hijacking, ending the round
  code/datums/gamemodes/distress.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Feature, Test Merge Candidate

#5944 Generic code cleanup pass and documentation
  code/controllers/subsystem/direction.dm
  code/controllers/subsystem/weeds_decay.dm
  code/game/objects/machinery/autodoc.dm
  code/modules/organs/limb_objects.dm
  code/modules/organs/limbs.dm
  code/modules/requisitions/fulton.dm
  code/modules/surgery/bones.dm
Labels: Code Improvement

#5942 Fix spawn() returns and clean up /obj/item/storage/internal/proc/handle_mousedrop
  code/game/objects/items/storage/internal.dm
Labels: Code Improvement

#5945 Adds a chem implant and updates some implant code
  code/__DEFINES/implants.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implant_chem.dm
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/implants/implantneurostim.dm
  tgmc.dme
Labels: Code Improvement, Feature

#5990 Nukes window resizable, Improves drag code, improves tabs and upgrades some small dependencies.
  tgui/docs/component-reference.md
  tgui/packages/tgui-dev-server/package.json
  tgui/packages/tgui-panel/Panel.js
  tgui/packages/tgui-panel/styles/themes/light.scss
  tgui/packages/tgui-polyfill/package.json
  tgui/packages/tgui/components/Section.js
  tgui/packages/tgui/components/Tabs.js
  tgui/packages/tgui/debug/KitchenSink.js
  tgui/packages/tgui/drag.js
  tgui/packages/tgui/interfaces/AlertModal.js
  tgui/packages/tgui/interfaces/Apc.js
  tgui/packages/tgui/interfaces/CameraConsole.js
  tgui/packages/tgui/interfaces/Cargo.js
  tgui/packages/tgui/interfaces/ChemDispenser.js
  tgui/packages/tgui/interfaces/ChemMaster.js
  tgui/packages/tgui/interfaces/Cryo.js
  tgui/packages/tgui/interfaces/EscapePod.js
  tgui/packages/tgui/interfaces/Filteriffic.js
  tgui/packages/tgui/interfaces/HiveEvolveScreen.js
  tgui/packages/tgui/interfaces/IntelComputer.js
  tgui/packages/tgui/interfaces/ListInput.js
  tgui/packages/tgui/interfaces/Mortar.js
  tgui/packages/tgui/interfaces/PortableGenerator.js
  tgui/packages/tgui/interfaces/ShuttleManipulator.js
  tgui/packages/tgui/interfaces/SmartVend.js
  tgui/packages/tgui/interfaces/manually-routed/KitchenSink.js
  tgui/packages/tgui/layouts/NtosWindow.js
  tgui/packages/tgui/layouts/Window.js
  tgui/packages/tgui/routes.js
  tgui/packages/tgui/stories/Storage.stories.js
  tgui/packages/tgui/stories/Tabs.stories.js
  tgui/packages/tgui/styles/components/Section.scss
  tgui/packages/tgui/styles/components/Tabs.scss
  tgui/packages/tgui/styles/themes/paper.scss
  tgui/public/tgui-common.bundle.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
  tgui/yarn.lock
Labels: Fix, Test Merge Candidate, Tweak, UI

#5991 fixes missing users from tgui alert and input list and untrust byond var assigning
  code/datums/gamemodes/game_mode.dm
  code/game/objects/items/books/book.dm
  code/game/objects/items/circuitboards/circuitboard.dm
  code/game/objects/items/cosmetics.dm
  code/game/objects/items/toys/cards.dm
  code/game/objects/machinery/autolathe.dm
  code/game/objects/machinery/bioprinter.dm
  code/game/objects/machinery/computer/camera_console.dm
  code/game/objects/machinery/computer/marines_consoles.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/practice/medical.dm
  code/game/objects/structures/barsign.dm
  code/game/objects/structures/bookcase.dm
  code/game/objects/structures/ladders.dm
  code/modules/admin/fun_verbs.dm
  code/modules/assembly/holder.dm
  code/modules/client/preferences.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/give.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/surgery/organs_internal.dm
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/vehicles/multitile/tank.dm
Labels: Fix, Test Merge Candidate

#5653 tie your laces
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  icons/Marine/marine-weapons.dmi
Labels: Feature, Needs Balance Review, Sprites

#5825 Small arms REJOICE!!!!
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/pistols.dm
Labels: Balance/Rebalance

#5802 lowers sandbag health
  code/game/objects/structures/barricade.dm
Labels: Balance/Rebalance

#5986 Removes Psychic choke code
  code/__DEFINES/dcs/signals.dm
  code/_onclick/telekinesis.dm
  code/datums/keybinding/xeno.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Code Improvement, Removal

#5988 Unarmedattack no longer converts params twice
  code/_onclick/ai.dm
  code/_onclick/click.dm
  code/_onclick/other_mobs.dm
  code/_onclick/xeno.dm
Labels: Code Improvement

#5987 Add Weed spread unit test
  code/controllers/subsystem/weeds.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/unit_test.dm
  code/modules/unit_tests/weed_spread.dm
Labels: Code Improvement, Tools

#6004 Fix xeno unarmed attack bad index runtime
  code/_onclick/xeno.dm
Labels: Fix, Priority: High

#6011 Replaces Nanotrasen Background logo on TGUI with TGMC background logo
  tgui/packages/tgui/assets/bg-tgmc.svg
  tgui/packages/tgui/styles/interfaces/NuclearBomb.scss
  tgui/packages/tgui/styles/main.scss
  tgui/public/tgui.bundle.css
Labels: Sprites, UI

#6016 Fix svg resizing
  tgui/packages/tgui/assets/bg-tgmc.svg
  tgui/public/tgui.bundle.css
Labels: Fix, UI

#5974 pill bottle 30 from 15
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Balance/Rebalance

#5897 Fixes weird unicode rendering in command announcements
  code/__HELPERS/announce.dm
Labels: Fix

#6008 Clearout particularily shitty old sprites
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  code/modules/power/turbine.dm
  icons/obj/device.dmi
  icons/obj/objects.dmi
  icons/obj/pipeturbine.dmi
  icons/obj/power.dmi
  tgmc.dme
Labels: Map Edit, Sprites

#6014 Adds Aim Mode keybinding
  code/__DEFINES/dcs/signals.dm
  code/datums/actions/item_action.dm
  code/datums/keybinding/human.dm
Labels: Code Improvement, Do Not TM

#6018 Sentry voucher fix
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Grammar and Formatting

#5980 Removes boiler's bombard's random offset
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Balance/Rebalance, Removal

#5978 adds tx-11 and pays gun tax by deleting ak variant
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Feature, Map Edit, Sprites

#6009 Adds a cloak implant and fixes implants not activating
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals.dm
  code/game/objects/items/cloaking.dm
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/game/objects/items/flash.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implant_cloak.dm
  code/game/objects/items/implants/implant_neurostim.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/storage/backpack.dm
  sound/effects/seedling_chargeup.ogg
  tgmc.dme
Labels: Code Improvement, Feature, Fix, Sound

#6010 Adds armblade implant and support for item implants
  README.md
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implant_items.dm
  code/game/objects/items/implants/implanter.dm
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/weapons.dmi
  tgmc.dme
Labels: Code Improvement, Feature, Sprites

#6023 Removes weed removal unit test
  code/modules/unit_tests/weed_spread.dm
Labels: Fix, Removal

#6029 Fixes divide by 0 runtime
  code/modules/mob/living/carbon/human/human_damage.dm
Labels: Fix

#6028 Fix DBquery second edition
  code/controllers/subsystem/blackbox.dm
Labels: Fix

#5770 New HealthMate Eyewear
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/head/helmet.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, Sprites

#6038 Heedhelp to Needhelp
  code/modules/mob/living/carbon/xenomorph/emote.dm
Labels: Fix

#6040 Fixes missing helmet icons
  icons/mob/modular/modular_helmet_icon.dmi
Labels: Fix, Sprites

#6030 Fix spammed runner runtime
  code/__DEFINES/dcs/signals.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
Labels: Fix

#6032 Removes illegal src edits and adds a lint for them
  code/game/objects/effects/manifest.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/machinery/adv_med.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/reagents/reagents.dm
  code/modules/tooltip/tooltip.dm
  tools/ci/check_grep.sh
Labels: Code Improvement, Tools

#6015 514 compat
  SpacemanDMM.toml
  code/__DEFINES/_tick.dm
  code/__DEFINES/spaceman_dmm.dm
  code/_compile_options.dm
  code/game/world.dm
Labels: Code Improvement

#6024 Beam refactor to use signals
  code/datums/beam.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Refactor

#5885 Fixes a bit over half of the sleeping signal handlers
  code/datums/actions/xeno_action.dm
  code/datums/components/suit_autodoc.dm
  code/datums/elements/scalping.dm
  code/datums/marine_main_ship.dm
  code/datums/wires/airlock.dm
  code/game/area/area.dm
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/airlock_control.dm
  code/game/objects/machinery/doors/brigdoors.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/machinery/telecomms/machines/allinone.dm
  code/modules/ai/ai_behaviors/carbon/carbon.dm
  code/modules/ai/ai_behaviors/carbon/xeno/xeno.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/shuttle/on_move.dm
Labels: Refactor

#5970 Pinpointer for pools
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature, Map Edit, Test Merge Candidate

#5997 Multiple map changes related to larva PR
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Feature, Map Edit, Removal, Test Merge Candidate, Tweak

#6034 anti material rile has iff
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#5949 Unbalanced join detector
  code/__DEFINES/is_helpers.dm
  code/controllers/subsystem/monitor.dm
  code/modules/mob/new_player/new_player.dm
Labels: Feature

#6003 Makes the entire area of HE OB a devastating explosion
  code/game/objects/structures/orbital_cannon.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6033 general purpose storage module bypasses ammo
  code/modules/modular_armor/storage.dm
Labels: Balance/Rebalance

#6042 Grab Slowdown Capped at 3
  code/__DEFINES/mobs.dm
  code/modules/mob/mob.dm
Labels: Fix

#6037 Minor cloak formatting changes
  code/game/objects/items/implants/implant_cloak.dm
Labels: Fix

#5959 Replace the lobby HTML window with a new lobby menu
  code/_onclick/hud/new_player.dm
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/_onclick/hud/screen_objects/text_objects.dm
  code/controllers/subsystem/ticker.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/admin/topic.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/new_player/login.dm
  code/modules/mob/new_player/new_player.dm
  icons/UI_Icons/lobby_button.dmi
  interface/skin.dmf
  sound/effects/menu_click.ogg
  sound/effects/menu_select.ogg
  tgmc.dme
Labels: Code Improvement, Feature, Sound, Sprites, Test Merge Candidate

#5855 Defiler Reagent Slash Rework
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Balance/Rebalance, Code Improvement, Test Merge Candidate, Tweak

#5811 Jetpack
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/equipment.dm
  code/__DEFINES/movespeed_modification.dm
  code/_onclick/click.dm
  code/datums/components/footstep.dm
  code/datums/components/shield.dm
  code/datums/components/squeak.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/jetpack.dm
  code/game/objects/items/shards.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/machinery/doors/railing.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/utility.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_movespeed.dm
  code/modules/modular_armor/modular.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/back.dmi
  icons/obj/items/jetpack.dmi
  sound/items/jetpack_sound.ogg
  tgmc.dme
Labels: Feature, Fix, Sound, Sprites, Tweak

#6053 Ice colony instant death fix
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Fix, Map Edit

#6054 Add ic filtering for announcements
  code/game/objects/machinery/computer/communications.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Administration, Fix

#5946 Remote control vehicles/component
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/vehicles.dm
  code/datums/components/remote_control.dm
  code/modules/vehicles/unmanned/unmanned_turrets.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
  code/modules/vehicles/unmanned/unmanned_vehicle_remote.dm
  icons/obj/unmanned_vehicles.dmi
  tgmc.dme
Labels: Feature, Sprites

#6056 Sulaco dropship-crash fix
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#6036 Fixes blade sound only playing for owner
  code/game/objects/items/implants/implant_items.dm
Labels: Fix

#6057 the normal marine vest uses pas vest stats, and normalizes non pas vest stats to pas vest for shipside armor
  code/modules/clothing/suits/marine_armor.dm
Labels: Fix

#6073 Adds droids
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals.dm
  code/datums/components/remote_control.dm
  code/modules/vehicles/unmanned/unmanned_droid.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
  code/modules/vehicles/unmanned/unmanned_vehicle_remote.dm
  icons/obj/unmanned_vehicles.dmi
  sound/machines/drone/droneoff.ogg
  sound/machines/drone/weapons_engaged.ogg
  sound/runtime/drone/drone1.ogg
  sound/runtime/drone/drone10.ogg
  sound/runtime/drone/drone11.ogg
  sound/runtime/drone/drone12.ogg
  sound/runtime/drone/drone2.ogg
  sound/runtime/drone/drone3.ogg
  sound/runtime/drone/drone4.ogg
  sound/runtime/drone/drone5.ogg
  sound/runtime/drone/drone6.ogg
  sound/runtime/drone/drone7.ogg
  sound/runtime/drone/drone8.ogg
  sound/runtime/drone/drone9.ogg
  tgmc.dme
Labels: Feature, Sound, Sprites

#6058 Monitor v2
  code/__DEFINES/monitor.dm
  code/controllers/subsystem/monitor.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Refactor

#6074 Adds Droid screen overlay
  code/__DEFINES/layers.dm
  code/_onclick/hud/fullscreen.dm
  code/modules/vehicles/unmanned/unmanned_droid.dm
  icons/mob/screen/full.dmi
Labels: Sprites

#5907 Adds playtime tracking to notes
  SQL/database_changelog.txt
  SQL/tgmc-schema.sql
  code/__DEFINES/_subsystems.dm
  code/modules/admin/panels/note_panel.dm
Labels: Administration, SQL

#6047 Ice Cream (Color Gradients)
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/flavor_misc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/hair_gradients.dmi
Labels: Feature, Sprites

#5695 Neurospit Tweak: Stamina Damage Nerfed, Weak Neurogas Spawn and Neurotoxin Reagent Transfer Added
  code/__DEFINES/conflict.dm
  code/__DEFINES/mobs.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Balance/Rebalance, Refactor, Test Merge Candidate, Tweak

#6050 Prison Station LZ 1 & 2 adjustments
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Balance/Rebalance, Map Edit, Test Merge Candidate

#5983 CAS Balance Tweaks
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/objects/effects/overlays.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/orbital_cannon.dm
Labels: Balance/Rebalance, Map Edit, Test Merge Candidate

#5965 revolver has a real fire speed now, mateba has higher aim mode delay
  code/modules/projectiles/guns/revolvers.dm
Labels: Balance/Rebalance, Test Merge Candidate
