Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2021-09, with the labels that each got.

#8127 Split new account config
  code/controllers/configuration/entries/general.dm
  code/modules/client/client_procs.dm
  config/config.txt
Labels: Config Update

#7974 Attachment Refactor!
  _maps/map_files/LV624/LV624.dmm
  code/__DEFINES/attachments.dm
  code/__DEFINES/conflict.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/loadout.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/actions/item_action.dm
  code/datums/components/attachment_handler.dm
  code/datums/elements/attachment.dm
  code/datums/elements/deployable_item.dm
  code/datums/emergency_calls/supplies.dm
  code/datums/loadout/item_representation/gun_representation.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/codex/entries/weapons_codex.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/flamer.dm
  code/modules/projectiles/magazines/shotguns.dm
  code/modules/projectiles/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  tgmc.dme
Labels: Sprites, Code Improvement, Refactor, Map Edit, Quality of Life, Mechanic

#8119 Flashlights are now not useless
  code/game/objects/items/marine_gear.dm
Labels: Balance/Rebalance

#8139 Revert "Flashlights are now not useless"
  code/game/objects/items/marine_gear.dm
Labels: Revert

#8053 Smoke affects you when you step into it
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/living_defines.dm
Labels: Balance/Rebalance

#8137 Puts default config viewsize to 15x15 again
  config/config.txt
Labels: Config Update

#8135 Add a couple in game notes referring to binary radio.
  code/datums/jobs/job/shipside.dm
  strings/tips/marine.txt
Labels: Mechanic

#8107 makes captain have level 1 surgery
  code/datums/skills.dm
Labels: Mechanic

#8140 New gun, the derringer.
  code/__DEFINES/calibers.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/magazines/shotguns.dm
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Sprites, Mechanic

#8146 Admin respawn bypass message_admins()
  code/modules/mob/mob_verbs.dm
Labels: Administration

#8020 Jetpack are now free
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance/Rebalance

#8079 Xeno turret projectiles go faster
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Test Merge Candidate

#8151 Change log fetching to r_admin instead of r_asay
  code/modules/admin/admin_verbs.dm
Labels: Administration

#8152 Fix door shooting/hitting logging excessively
  code/game/objects/machinery/doors/airlock.dm
Labels: Administration

#8150 Add a boxing ring to Pillar
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Mechanic

#8149 Limits max magazines in med belts
  code/game/objects/items/storage/belt.dm
Labels: Balance/Rebalance

#8148 Mimir Buff
  code/modules/modular_armor/attachables.dm
  code/modules/modular_armor/helmets.dm
Labels: Balance/Rebalance

#8133 Sentry Tweaks
  code/game/objects/machinery/deployable.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/mounted.dm
  code/modules/projectiles/sentries.dm
Labels: Code Improvement, Balance/Rebalance, Fix, Test Merge Candidate

#8164 Fix xeno turrets not checking z level of droids
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix

#8173 Fixes unmapped area in Big Red
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Fix, Map Edit

#8163 Fixes the issue with Unloaded Derringer bullets not being able to be loaded back into the Derringer.
  code/modules/projectiles/guns/shotguns.dm
Labels: Fix

#8125 Chigusa Hydroelectric Dam - A damn big port.
  _maps/_basemap.dm
  _maps/desertdam.json
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/desertdam/desertdam.dmm
  code/game/area/desertdam.dm
  code/game/objects/structures/desertdam.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/platforms.dm
  code/game/objects/structures/prop.dm
  code/game/turfs/floor_ground.dm
  code/game/turfs/open_ground.dm
  config/maps.txt
  icons/desertdam_map.dmi
  icons/obj/structures/railstairs.dmi
  icons/turf/asphalt.dmi
  icons/turf/catwalks.dmi
  icons/turf/dam_areas.dmi
  icons/turf/desertdam_map.dmi
  icons/turf/geothermal.dmi
Labels: Sprites, Config Update, Code Improvement, Map Edit, Mechanic

#8136 pulse rifle has it's old sounds
  code/game/sound.dm
  code/modules/projectiles/guns/rifles.dm
  sound/weapons/guns/fire/m41a_1.ogg
  sound/weapons/guns/fire/m41a_2.ogg
  sound/weapons/guns/fire/m41a_3.ogg
  sound/weapons/guns/fire/m41a_4.ogg
  sound/weapons/guns/fire/m41a_5.ogg
  sound/weapons/guns/fire/m41a_6.ogg
Labels: Sound

#8162 Miner module buff for reinforcement
  code/game/objects/machinery/miner.dm
Labels: Balance/Rebalance

#8158 Lets you clear a single recipe from dispensers
  code/modules/reagents/machinery/chem_dispenser.dm
  tgui/packages/tgui/interfaces/ChemDispenser.js
Labels: UI, Mechanic

#8180 Rage Power is Now Maximized While at Negative HP
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Balance/Rebalance

#7868 Chambering Refactor and Single Action Revolvers
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Code Improvement, Refactor

#8121 Refactor eggs
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/egg.dm
  code/modules/mob/living/carbon/xenomorph/egg_item.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  icons/Xeno/Effects.dmi
  tgmc.dme
Labels: Sprites, Refactor

#8184 Removes Baldur Mk2 and Mk1 slowdown.
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/modular_armor/attachables.dm
  code/modules/reqs/supplypacks.dm
Labels: Removal, Balance/Rebalance

#8185 Fixes some issues with attachment weapons firing when they shouldnt.
  code/modules/projectiles/gun_system.dm
Labels: Fix

#7815 Adds movement and direction switch for scopes with ctrl+Wasd
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/movespeed_modification.dm
  code/datums/view.dm
  code/game/objects/items.dm
  code/game/objects/items/binoculars.dm
  code/modules/mob/mob.dm
  code/modules/modular_armor/helmets.dm
  code/modules/projectiles/gun_attachables.dm
Labels: Balance/Rebalance, Test Merge Candidate, Quality of Life

#7618 King of the hill Civil War
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/modularmaps/EORG/basketball.dmm
  code/__DEFINES/minimap.dm
  code/__DEFINES/mode.dm
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/minimaps.dm
  code/datums/gamemodes/civil_war.dm
  code/datums/gamemodes/game_mode.dm
  code/game/area/area.dm
  code/game/area/general.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/game/objects/structures/sensor_tower.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/sentries.dm
  icons/UI_Icons/map_blips.dmi
  icons/obj/structures/sensor.dmi
  icons/turf/areas.dmi
  tgmc.dme
Labels: Sprites, Map Edit, Content Expansion

#8196 Fix lighter in cigarette packet
  code/game/objects/items/storage/fancy.dm
Labels: Fix

#8197 Moves PPSH to seasonals from marine vendor, adds a new gun for seasonals, MKH98
  code/controllers/subsystem/persistence.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/Marine/gun64.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Mechanic

#8210 You can sprint while shooting again
  code/modules/projectiles/gun_system.dm
Labels: Priority: High, Fix

#8201 Fix ai xeno runtime
  code/controllers/subsystem/spawning.dm
Labels: Fix

#8190 Fix being able to send two people with one medevac
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix

#8199 Repath grenade frag to grenade
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/MarineHQ/MarineHQ.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/modularmaps/lv624/cargo_bay.dmm
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/clf.dm
  code/datums/jobs/job/deathsquad.dm
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/imperium.dm
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/sectoid.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Code Improvement, Map Edit

#8208 Hunter Mark Improvements
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Balance/Rebalance

#8220 Update to spacemandmm 1.7.1
  .github/workflows/generate_documentation.yml
  dependencies.sh
Labels: GitHub, Git-hub, Git.hUb

#8211 Fixes Ice Colony's LZ2 resin wall before shutters exploit
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Fix, Map Edit

#8126 Roomba roulette
  code/game/objects/machinery/roomba.dm
Labels: Mechanic

#8110 You can vote for civil war now
  code/controllers/subsystem/vote.dm
  config/modes.txt
Labels: Config Update, Do Not Merge, Stale

#8215 Fix flaregun shooting nades
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#8187 Toning down infections
  code/modules/organs/limbs.dm
  code/modules/organs/wound.dm
Labels: Balance/Rebalance, Fix, Test Merge Candidate, Quality of Life

#8216 Misc hugger/egg fixes
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/egg.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  icons/Xeno/Effects.dmi
Labels: Sprites, Fix, Test Merge Candidate

#8217 TP-14 Standard Pistol Nerf
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/pistols.dm
Labels: Balance/Rebalance

#8218 AI crusher will no longer have the speed of a runner
  code/datums/elements/pathfinder.dm
Labels: Fix

#8223 Add ai nodes to EORD
  _maps/modularmaps/EORG/de_dust2.dmm
  _maps/modularmaps/EORG/original.dmm
Labels: Map Edit, Content Expansion

#8104 Map contrib guidelines added
  .github/CONTRIBUTING.md
Labels: GitHub

#8231 Update inventory.dm, get_active_held_item() returning every 3 world.time ticks now reduced to 1.
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Code Improvement, Test Merge Candidate, Quality of Life

#8188 Repaths medkit stacks
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/map_files/generic/Admin_Level.dmm
  code/datums/jobs/job/deathsquad.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/sectoid.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/jobs/job/upp.dm
  code/game/objects/items/reagent_containers/food/snacks/grown.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/surgical_tray.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/clothing/under/ties.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/reqs/supplypacks.dm
  code/modules/surgery/necrosis.dm
  code/modules/surgery/organs_internal.dm
Labels: Refactor, Map Edit, Quality of Life

#8156 Increases ammo belt storage slots.
  code/game/objects/items/storage/belt.dm
Labels: Balance/Rebalance

#8219 You can take full control of the ai
  code/datums/components/ai.dm
  code/datums/elements/pathfinder.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
Labels: Quality of Life

#8233 Prevent flares from exploding and refactor grenades a little
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/special_forces.dm
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Refactor, Fix

#8240 Scanner and defib wording changes
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/scanners.dm
Labels: Fix

#8145 Space agent no longer reset timeofdeath, support for ghostroles, players cannot steal aghosted xenos, ghost can take afk marines
  code/__DEFINES/mode.dm
  code/__HELPERS/game.dm
  code/_globalvars/misc.dm
  code/controllers/subsystem/monitor.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/login.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/login.dm
  code/modules/mob/living/carbon/xenomorph/logout.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/logout.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/shuttle/shuttle.dm
  tgmc.dme
Labels: Sprites, Fix, Mechanic

#8120 Adds marine motorbikes
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/__DEFINES/buckling.dm
  code/__DEFINES/cooldowns.dm
  code/_globalvars/bitfields.dm
  code/datums/components/riding/riding_vehicle.dm
  code/datums/elements/riding.dm
  code/datums/elements/slow_on_cross.dm
  code/game/buckling.dm
  code/game/objects/items/storage/internal.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/mob_grab.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/motorbike.dm
  code/modules/vehicles/ridden.dm
  icons/obj/vehicles.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/Cargo.js
Labels: Sprites, Map Edit, UI, Mechanic

#8244 Admin spawned xeno can use abilities in civil war
  code/datums/gamemodes/civil_war.dm
Labels: Mechanic

#8195 Build-A-Sentry
  code/__DEFINES/conflict.dm
  code/__DEFINES/loadout.dm
  code/_globalvars/bitfields.dm
  code/datums/elements/deployable_item.dm
  code/game/objects/machinery/deployable.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/mounted.dm
  code/modules/projectiles/sentries.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/Marine/sentry.dmi
Labels: Sprites, Test Merge Candidate, Mechanic, Content Expansion

#8241 Update ooc.dm. Adds two new OOC verbs for team-based OOC.
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/client.dm
  code/game/verbs/ooc.dm
Labels: Code Improvement, Administration, Test Merge Candidate, Mechanic

#8246 https://github.com/tgstation/tgstation/pull/61341/files port
  code/_onclick/hud/parallax.dm
Labels: Fix

#8247 port https://github.com/tgstation/tgstation/pull/61324/files
  tgui/packages/common/color.js
Labels: Fix, UI

#8248 https://github.com/tgstation/tgstation/pull/61078/files port
  code/__HELPERS/qdel.dm
Labels: Fix

#8255 TGUI tooltip optimization
  tgui/packages/tgui/components/Tooltip.tsx
Labels: Code Improvement, UI

#8253 Fix radial menu flags
  code/_onclick/hud/radial.dm
Labels: Fix

#8252 Ballon alerts flags fix
  code/modules/balloon_alert/balloon_alert.dm
Labels: Fix

#8249 Add missing varedit bitfield byond flags
  code/_globalvars/bitfields.dm
Labels: Administration

#8243 Add back sentry ammo hud
  code/__DEFINES/atom_hud.dm
  code/game/data_huds.dm
  code/modules/projectiles/mounted.dm
  code/modules/projectiles/sentries.dm
Labels: Fix

#8254 Emissive code improvement port
  code/__DEFINES/lighting.dm
  code/__HELPERS/lighting.dm
  code/game/atoms_movable.dm
  code/modules/lighting/emissive_blocker.dm
Labels: Code Improvement

#8238 Sleeping changes
  code/datums/status_effects/debuffs.dm
Labels: Content Expansion

#8230 reduces machinecarbine scatter by 8
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#8232 T-90/19 semi buff/aim mode adding
  code/modules/projectiles/guns/smgs.dm
Labels: Balance/Rebalance

#8245 Fix droid repair
  code/modules/vehicles/unmanned/unmanned_droid.dm
Labels: Fix

#8257 Bump Max reccomended byond versions
  code/_compile_options.dm
  code/modules/client/client_procs.dm
Labels: Code Improvement

#8256 Add clothing whitelist support
  code/__HELPERS/string_lists.dm
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/species.dm
  tgmc.dme
Labels: Code Improvement

#7976 Hivemind rework v1
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/obj_flags.dm
  code/_onclick/hud/xeno/hivemind.dm
  code/datums/components/bump_attack.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/game/objects/structures/razorwire.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/unit_tests/weed_ability.dm
  icons/Xeno/48x48_Xenos.dmi
  icons/Xeno/wound_overlays.dmi
  icons/mob/actions.dmi
  icons/mob/cameramob.dmi
  tgmc.dme
Labels: Sprites, Mechanic

#8266 Fixes buckling to beds and carrying mobs
  code/game/buckling.dm
  code/modules/mob/mob_movement.dm
  code/modules/vehicles/ridden.dm
Labels: Fix, Test Merge Candidate

#8242 Add minimap blips for nuke disk generator and nuke
  code/datums/gamemodes/infestation.dm
  code/game/objects/machinery/computer/nuke_disk_generator.dm
  code/game/objects/machinery/nuclearbomb.dm
  icons/UI_Icons/map_blips.dmi
Labels: Sprites, Quality of Life

#8263 tp44 description changes
  code/modules/projectiles/guns/revolvers.dm
Labels: Grammar and Formatting

#8264 makes the M-44 into a proper single action+minor stat changes
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/controllers/subsystem/persistence.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/gun.dmi
Labels: Sprites, Balance/Rebalance, Map Edit

#8274 Mini incinerator tank now small item
  code/modules/projectiles/magazines/flamer.dm
Labels: Balance/Rebalance

#8258 vehicle multitile adjecency support and minor cleanup
  code/_onclick/adjacent.dm
Labels: Code Improvement

#8267 Infinite gauze, finite brute kits
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
Labels: Balance/Rebalance

#8269 Chigusa LZ revamp and bugfix update
  _maps/map_files/desertdam/desertdam.dmm
  code/game/area/desertdam.dm
  code/game/objects/structures/desertdam.dm
  icons/desertdam_map.dmi
  icons/turf/desertdam_map.dmi
Labels: Sprites, Removal, Balance/Rebalance, Fix, Map Edit, Mechanic, Content Expansion

#8237 Revert "fixes not being able to shoot on adjacent tiles. (#8066)"
  code/modules/projectiles/gun_system.dm
Labels: Revert, Quality of Life

#8270 MK221 to vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Mechanic

#8273 Buff Praetorian acid spit
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#8262 ak relore/name
  code/modules/projectiles/guns/rifles.dm
Labels: Grammar and Formatting

#8280 Team OOC logging and stealthmode checks.
  code/__DEFINES/logging.dm
  code/__HELPERS/_logging.dm
  code/controllers/configuration/entries/general.dm
  code/game/atoms.dm
  code/game/verbs/ooc.dm
  config/config.txt
Labels: Config Update, Administration

#8054 Incin chems rebalance
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/modules/reagents/reactions/other.dm
Labels: Fix, Mechanic

#8290 mosin/svd have aim mode once again
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Balance/Rebalance

#8222 Jaeger and M10 helmet storage.
  code/game/objects/items/storage/storage.dm
  code/modules/modular_armor/helmets.dm
  code/modules/modular_armor/modular.dm
  code/modules/modular_armor/storage.dm
  icons/mob/modular/modular_helmet_storage.dmi
Labels: Sprites, Mechanic, Content Expansion

#8295 Fix infinite respawn, randomise name on ssd take, add admin loging
  code/modules/mob/dead/observer/observer.dm
Labels: Fix, Administration

#8227 Replaces ryetalin in combat injectors with dylovene
  code/game/objects/items/reagent_containers/autoinjectors.dm
Labels: Fix

#8314 Revert "Fix infinite respawn, randomise name on ssd take, add admin loging"
  code/modules/mob/dead/observer/observer.dm
Labels: Revert

#8292 Synth can use loadout vendor
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Content Expansion

#8281 All ghosts have actions, kill the pref
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Removal

#8276 Fix not being able to fire at dark zones with attachment
  code/modules/projectiles/gun_system.dm
Labels: Fix

#8236 You cannot use enemy medevacs
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/mob_defines.dm
Labels: Balance/Rebalance

#8141 Priority change in shuffling
  code/modules/mob/living/living.dm
Labels: Test Merge Candidate, Quality of Life

#8147 Reqtorio V1
  code/__DEFINES/factory.dm
  code/__DEFINES/is_helpers.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/round_statistics.dm
  code/modules/factory/howtopaper.dm
  code/modules/factory/machines.dm
  code/modules/factory/outputter.dm
  code/modules/factory/parts.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/factory/factory_machines.dmi
  icons/obj/factory/factoryparts.dmi
  icons/obj/factory_refill.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/Cargo.js
Labels: Sprites, UI, Mechanic

#8309 AK and Storm Rifle have mag harness, AK gets auto eject
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#8310 M16 changes- Faster burst reset, no BFA, less base scatter, better aim speed. No autoburst
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#8300 Adds Judge shotgun revolver, adds seasonal with it and nagant revolver
  code/__DEFINES/calibers.dm
  code/controllers/subsystem/persistence.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/revolvers.dm
  icons/obj/items/gun.dmi
Labels: Sprites, Mechanic, Content Expansion

#8259 Hunter is SUS SUS AMOGUS
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Config Update, Balance/Rebalance, Mechanic

#8311 Prae buff/nerf- Cone acid upped to 400, cone slowdown halved, bomb resist 1
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
Labels: Balance/Rebalance

#8323 Fixes medvacs not working
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix, Test Merge Candidate

#8285 Xenos have slower respawn in crash
  code/datums/gamemodes/crash.dm
Labels: Balance/Rebalance

#8325 Fixes new ticket admin/mentor help message double sanitizing
  code/modules/admin/verbs/adminhelp.dm
Labels: Fix, Administration, Upstream port

#8327 Adds T-27 MMG, and deployed scatter reduction
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-mmg.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  sound/weapons/guns/fire/t27.ogg
Labels: Sprites, Sound, Code Improvement, Mechanic

#8283 Fix motion detector working in pockets
  code/game/objects/items/motion_detector.dm
Labels: Fix

#8153 Explosion logs will now only send to chat shipside
  code/controllers/subsystem/explosions.dm
Labels: Administration

#8313 PPsh buff
  code/modules/projectiles/guns/smgs.dm
Labels: Balance/Rebalance

#8138 Fixes zoom values.
  code/game/objects/items.dm
  code/modules/projectiles/gun_attachables.dm
Labels: Fix, Test Merge Candidate

#8322 Chem rework 7.0
  code/datums/jobs/job/shipside.dm
  code/modules/reagents/reactions/medical.dm
  code/modules/reagents/reagents/medical.dm
Labels: Test Merge Candidate, Content Expansion

#8326 seasonal guns are cheaper in imports, adds some seasonals to req
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Quality of Life

#8346 t27 inhand flip or whatever
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
Labels: Sprites, Fix

#8235 You can no longer switch sides in HvH
  code/datums/gamemodes/civil_war.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob_verbs.dm
  code/modules/mob/new_player/new_player.dm
Labels: Balance/Rebalance

#8337 Radio Backpack
  code/__DEFINES/loadout.dm
  code/modules/reqs/supply.dm
  icons/mob/back.dmi
  icons/obj/items/storage/storage.dmi
Labels: Sprites, Sound, Mechanic

#8294 Gun flag system refactor
  code/__DEFINES/conflict.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/modules/codex/entries/guns_codex.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/mounted.dm
  code/modules/projectiles/sentries.dm
Labels: Refactor

#8347 Center small explosions
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
Labels: Quality of Life

#8348 Change weed name
  code/game/objects/effects/weeds.dm
Labels: Quality of Life

#8332 Add percentage based plasma loss for plasmaloss gas and pepperball gun.
  code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Code Improvement, Balance/Rebalance

#8343 Lighting fix batch
  code/game/turfs/turf.dm
  code/modules/lighting/lighting_static/static_lighting_turf.dm
Labels: Fix

#8341 ravager melee damage buff and standardization
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
Labels: Balance/Rebalance

#8306 Adds the Leicester Repeater
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/magazines/shotguns.dm
  icons/Marine/gun64.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
Labels: Sprites

#8354 Lazy click drag fix
  code/_onclick/drag_drop.dm
Labels: Code Improvement

#8353 Fixes synths applying racial resistances twice to limb damage
  code/modules/organs/limbs.dm
Labels: Fix

#8377 Revert "Space agent no longer reset timeofdeath, support for ghostroles, players cannot steal aghosted xenos, ghost can take afk marines"
  code/__DEFINES/mode.dm
  code/__HELPERS/game.dm
  code/_globalvars/misc.dm
  code/controllers/subsystem/monitor.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/gamemodes/game_mode.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/login.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/login.dm
  code/modules/mob/living/carbon/xenomorph/logout.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/logout.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/shuttle/shuttle.dm
  tgmc.dme
Labels: Revert

#8355 Fix shuttle lighting & turfs
  code/game/turfs/turf.dm
Labels: Fix, Test Merge Candidate

#8330 Lower praetorian acid spray cost from 400 to 300
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
Labels: Balance/Rebalance

#8359 Radio Backpack Right-click Fix
  code/modules/reqs/supply.dm
Labels: Fix

#8361 Fix energy guns not auto ejecting
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#8366 Fix loging into ai not giving you full control
  code/modules/ai/ai_behaviors/ai_behavior.dm
Labels: Fix

#8362 You can have multiple ammo huds
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/mounted.dm
Labels: Quality of Life

#8369 Fix hivemind slowdown issues
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/mob_movement.dm
Labels: Fix

#8371 Fix corpsespawner looking psydrainable
  code/game/objects/effects/landmarks/corpsespawner.dm
Labels: Fix

#8370 Self splinting timer delay is 3x instead of 4x
  code/modules/organs/limbs.dm
Labels: Balance/Rebalance

#8368 Fix xeno instant evolving
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Fix, Test Merge Candidate

#8389 Fix shotgun pump lock
  code/modules/projectiles/guns/shotguns.dm
Labels: Fix

#8374 Fixes Repeater Inhands
  icons/mob/items_lefthand_1.dmi
Labels: Sprites, Fix

#8372 Whiskey Outpost QOL update
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
Labels: Map Edit, Mechanic

#8384 Fix weed decaying
  code/controllers/subsystem/weeds.dm
  code/controllers/subsystem/weeds_decay.dm
  code/game/objects/effects/weeds.dm
Labels: Fix, Test Merge Candidate

#8400 Hotfix weed
  code/__DEFINES/xeno.dm
  code/game/objects/effects/weeds.dm
  icons/mob/actions.dmi
Labels: Sprites, Fix

#8399 Enable neuter gender in prefs
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx
Labels: UI

#8385 Adds a resin turret
  code/__DEFINES/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/Xeno/acidturret.dmi
Labels: Sprites, Test Merge Candidate, Mechanic

#8406 Add asset log config
  code/__HELPERS/_logging.dm
  code/controllers/configuration/entries/general.dm
  config/config.txt
Labels: Config Update

#8394 Improves first aid pouches
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/items/storage/pouch.dm
Labels: Balance/Rebalance

#8364 t27 wielded inhand change
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
Labels: Sprites
