Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2021-08, with the labels that each got.

#7703 Fix crusher charging
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Fix

#7688 modular armor storage module update
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites

#7677 Make Shrike stronk
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
Labels: Balance/Rebalance

#7640 Fixes regress/evolve for xenos that use plasma_regen_limit
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#7695 adds tyr helmet attachment
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/modular_armor/helmets.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/modular/modular_helmet_attachment.dmi
Labels: Mechanic, Sprites

#7709 adds a marine flaregun and makes it fit in flare pouches
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/misc.dm
  icons/obj/items/gun.dmi
Labels: Balance/Rebalance, Mechanic, Quality of Life, Sprites

#7716 Make it so there is a welding sound when you weld a firelock
  code/game/objects/machinery/doors/firedoor.dm
Labels: Quality of Life

#7714 Fix typo with the snapping emote and hugging emote
  code/modules/mob/living/carbon/human/emote.dm
Labels: Fix

#7708 Fixes a bug with lolipop pouches
  code/__DEFINES/loadout.dm
Labels: Fix

#7727 fix flaregun vendor amounts
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#7732 tyr helmet attachie spawns in places now
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#7686 Nerfs King
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  sound/effects/bomb_fall.ogg
Labels: Sound

#7679 Update monitor balance calculation
  code/__DEFINES/monitor.dm
  code/controllers/subsystem/monitor.dm
  code/game/objects/structures/orbital_cannon.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Code Improvement

#7733 new gloves/boot sprites
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/shoes.dmi
Labels: Sprites

#7728 jaeger storage modules have better positions on the armor
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites

#7723 Fix doube clicking items in backpack dropping them
  code/game/objects/items.dm
Labels: Fix

#7702 Checkexit & Uncross now respects dir
  code/game/atoms.dm
  code/game/atoms_movable.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/game/objects/machinery/doors/railing.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/machinery/line_nexter.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/platforms.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix, Refactor, Test Merge Candidate

#7736 Fix minigun
  code/modules/projectiles/gun_system.dm
Labels: Fix

#7731 Relores the 357, new sprite
  code/controllers/subsystem/persistence.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/revolvers.dm
  icons/obj/items/gun.dmi
Labels: Grammar and Formatting, Sprites

#7742 gloves and shoe resprite numero dos
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/shoes.dmi
Labels: Sprites

#7734 Fixes hive status xeno health color when negative
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#7210 Autodocs can now start on their own
  code/game/objects/machinery/autodoc.dm
Labels: Mechanic, Test Merge Candidate

#7739 Removing King Announcement Overrides
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Fix

#7720 Fix slashing dead human lights
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Fix

#7698 Shitcode the boiler into having a faster ROF depending on the amount of ammo stored
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance/Rebalance

#7743 Converts Some Span Classes to Span Macros That Were Missed
  code/modules/projectiles/gun_helpers.dm
Labels: Code Improvement

#7641 Convert a number of tochats to balloon messages
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/_onclick/telekinesis.dm
  code/_onclick/ventcrawl.dm
  code/datums/components/bump_attack.dm
  code/datums/components/chem_booster.dm
  code/datums/components/remote_control.dm
  code/datums/components/rotation.dm
  code/datums/components/suit_autodoc.dm
  code/datums/components/udder.dm
  code/datums/custom_emotes.dm
  code/datums/elements/deployable_item.dm
  code/datums/elements/shrapnel_removal.dm
  code/datums/emotes.dm
  code/datums/loadout/loadout.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/xeno_buffs.dm
  code/datums/wires/_wires.dm
Labels: Quality of Life, Test Merge Candidate

#7741 changes machete holster sprite
  icons/obj/items/storage/storage.dmi
Labels: Sprites

#7699 Clicking a resin floor as xeno won't trigger attack delay
  code/_onclick/xeno.dm
Labels: Fix

#7744 Adds In-Game Notification on How To Replace Sentry Batteries
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/guns/sentries.dm
Labels: Mechanic

#7737 Make the AI lose control over the dropship doors when the beans hijackk it.
  code/_onclick/ai.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Balance/Rebalance

#7715 Shoves the AI into a different corner of theseus
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Content Expansion, Map Edit, Mechanic

#7572 Fixes damage not taking hunters out of stealth
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Fix

#7633 Sanitise item paths in loadouts
  code/datums/loadout/item_representation/_item_representation.dm
Labels: Code Improvement

#7632 Fix loadout deletion
  code/datums/loadout/loadout_manager.dm
  code/modules/client/preferences_savefile.dm
Labels: Fix, Stale

#7288 Add TS-34 Scopes
  code/modules/projectiles/guns/shotguns.dm
Labels: Content Expansion

#7644 AI notifications tweaks
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/shuttle/computer.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Content Expansion

#7757 Give the AI a noise notification whenever it gets a call on the holopad.
  code/game/objects/machinery/hologram.dm
  sound/machines/two_tones_beep.ogg
Labels: Quality of Life, Sound

#7775 Fix loadouts
  code/datums/loadout/item_representation/_item_representation.dm
Labels: Fix, Priority: High

#7756 new tp-17 sprites
  code/modules/projectiles/guns/pistols.dm
  icons/Marine/gun64.dmi
  icons/obj/items/gun.dmi
  sound/weapons/guns/fire/tp17.ogg
Labels: Sound, Sprites

#7776 automag has belt sprite
  icons/obj/clothing/belts.dmi
Labels: Fix, Sprites

#7745 Smol defiler buff
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
Labels: Balance/Rebalance

#7754 Make the outside of ice colony LZ2 actually count as outside.
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  code/game/area/icecolony.dm
  icons/turf/areas.dmi
Labels: Fix, Map Edit, Sprites

#7747 Fixes the UGL not having a fire delay by giving it a fire delay of 1 second
  code/modules/projectiles/gun_attachables.dm
Labels: Balance/Rebalance, Fix, Grammar and Formatting

#7751 /Mounted tweaks
  code/datums/elements/deployable_item.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/mounted.dm
Labels: Code Improvement

#7730 Give the AI some BETTER notificaitons for shuttle moving
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/shuttle.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Content Expansion

#7687 Allow the AI to turn on groundside generators like shipside ones, provided that they are intact.
  code/modules/power/groundmap_geothermal.dm
Labels: Quality of Life

#7759 fixes supply beacons not working in every LZ's
  code/game/area/sulaco.dm
Labels: Fix

#7753 Add big floor numbers to barrenquilla mining facility
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
Labels: Map Edit, Quality of Life

#7765 Make the supply beacon from the antenna last 4 minutes instead of 1
  code/modules/modular_armor/helmets.dm
Labels: Quality of Life

#7758 Add a wrenching noise to fueltanks, and another when spilling fuel
  code/game/objects/structures/reagent_dispensers.dm
  sound/effects/glob.ogg
Labels: Mechanic, Sound

#7766 Make the light replacer small. Because it is too big for its usefulness.
  code/game/objects/items/lightreplacer.dm
Labels: Quality of Life

#7755 Fix the special force leader incorrectly spawning with a Med hud
  code/datums/jobs/job/special_forces.dm
Labels: Fix

#7772 Defiler lore change
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
Labels: Fix

#7778 Leadered Xenos Receive Special Blue Crown Icon on the Minimap
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  icons/UI_Icons/map_blips.dmi
Labels: Sprites, Mechanic

#7777 Changes Dark Mode colors to more eye-friendly options
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
Labels: UI, Quality of Life

#7770 Prevents defibbing headless synths
  code/game/objects/items/defibrillator.dm
Labels: Fix

#7787 Mild bonus projectile fix
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#7783 Removes Queen Slashing Permissions
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Removal

#7782 HMG/HSG undeploy in 3 seconds, HMG deploys ~500ms faster.
  code/modules/projectiles/guns/mounted.dm
Labels: Balance/Rebalance

#7681 Sentinel movement animation
  icons/Xeno/48x48_Xenos.dmi
Labels: Sprites, Test Merge Candidate

#7654 Add a handheld cell charger for engineers
  Handheld charger.dmi
  code/__DEFINES/loadout.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  icons/obj/items/items.dmi
Labels: Sprites, Mechanic

#7771 Removes annoying Message on selecting an ability
  code/datums/actions/xeno_action.dm
Labels: Quality of Life

#7475 Makes red dot sight reduce aim mode fire delay by 50%
  code/modules/projectiles/gun_attachables.dm
Labels: Balance/Rebalance, Test Merge Candidate

#7789 Fix some of destroy code not abiding to contrib guidelines
  code/_onclick/hud/alerts.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/components/udder.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/effects/bump_teleporter.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/binoculars.dm
  code/game/objects/items/devices/spyglasses.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/flashlight.dm
  code/game/objects/items/radio/intercom.dm
  code/game/objects/items/reagent_containers/borghydro.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/machinery/floodlight.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/ladders.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/windoor_assembly.dm
  code/modules/admin/verbs/centcom_podlauncher.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/hardhat.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/ties.dm
  code/modules/clothing/under/under.dm
  code/modules/hydroponics/vines.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/organs/organ_objects.dm
  code/modules/power/apc.dm
  code/modules/power/lighting.dm
  code/modules/power/power.dm
  code/modules/power/powernet.dm
  code/modules/power/smes.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/reagents/holder.dm
  code/modules/recycling/disposal.dm
  code/modules/shuttle/navigation_computer.dm
Labels: Code Improvement, Fix

#7769 Fixes cpr'ing undefibbable bodies
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/projectiles/gun_system.dm
Labels: Fix

#7794 Removes Last Remaining References To Xeno Respawn Timers
  code/__HELPERS/game.dm
  code/_globalvars/admin.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/ticker.dm
  code/modules/admin/holder.dm
  code/modules/admin/server_verbs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/new_player/new_player.dm
Labels: Config Update, Removal

#7823 Fix larva spawning
  code/game/objects/items/cocoon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#7824 Fixes new light fixtures being destroyed upon creation
  code/game/objects/items/frames/light_fixtures.dm
Labels: Fix

#7804 Automag Nerf
  code/modules/projectiles/guns/pistols.dm
Labels: Balance/Rebalance, Test Merge Candidate

#7615 Warrior Punch Can Target But Doesn't Damage Unacidable; Other Fixes
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Stale, Fix

#7818 10 minutes is long in hvh, respawn is set to 5 minutes
  code/datums/gamemodes/civil_war.dm
Labels: Balance/Rebalance

#7819 Add mortars, sentries, and drop pods to civil war
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance/Rebalance, Map Edit

#7807 Grav crush does less damage to mobs
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Balance/Rebalance

#7792 evasion now actually has a real plasma cost, runner plasma reserves at lower tiers increased, and regen increased
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
Labels: Balance/Rebalance

#7726 Ports the TG smite system and several smites
  code/__DEFINES/mobs.dm
  code/_globalvars/lists/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder.dm
  code/modules/admin/smites/bloodless.dm
  code/modules/admin/smites/boneless.dm
  code/modules/admin/smites/brain_damage.dm
  code/modules/admin/smites/bsa.dm
  code/modules/admin/smites/fake_bwoink.dm
  code/modules/admin/smites/fat.dm
  code/modules/admin/smites/gib.dm
  code/modules/admin/smites/lightning.dm
  code/modules/admin/smites/nugget.dm
  code/modules/admin/smites/puzzle.dm
  code/modules/admin/smites/smite.dm
  code/modules/admin/topic.dm
  icons/obj/artefacts.dmi
  icons/obj/puzzle.dmi
  sound/effects/lightningbolt.ogg
  tgmc.dme
Labels: Sprites, Sound, Code Improvement, Administration, Upstream port, Mechanic

#7793 Sticky resin slows down vehicles
  code/game/objects/structures/xeno.dm
  code/modules/vehicles/vehicle.dm
Labels: Balance/Rebalance

#7844 Fix wrong headset being given to rebels from loadout vendor
  code/datums/loadout/loadout_helper.dm
  code/datums/loadout/loadout_seller.dm
Labels: Fix

#7831 Make the martini do a nice little animation when it ejects empty shots
  code/modules/projectiles/guns/shotguns.dm
  icons/Marine/gun64.dmi
Labels: Sprites, Mechanic

#7812 What if we made LV LZ1 bigger? This makes it bigger.
  _maps/map_files/LV624/LV624.dmm
Labels: Map Edit, Content Expansion

#7839 Fixes the little space view south of prep in sulaco killing beans during crash, by making it into a little room
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#7830 Fixes limb infection index error
  code/modules/organs/limbs.dm
Labels: Fix

#7796 Relocates Psy Points Cost to Xeno Action
  code/datums/actions/xeno_action.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Refactor

#7820 Trying to equip an enemy radio will make an explosion
  code/__DEFINES/_radio.dm
  code/__DEFINES/factions.dm
  code/game/objects/items/radio/headset.dm
  tgmc.dme
Labels: Content Expansion

#7790 Unmanned vehicles take some damage in acid boiler smoke
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Balance/Rebalance

#7780 Give a little breath noise whenever you put on a gas mask.
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/preferences.dm
  code/_globalvars/bitfields.dm
  code/game/sound.dm
  code/modules/client/preferences_toggles.dm
  code/modules/clothing/masks/gasmask.dm
  sound/effects/gasmaskbreath.ogg
  sound/effects/gasmaskbreath2.ogg
Labels: Sound

#7750 Buffs the TX-11 by 10 pen and 0.25 sunder
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#7846 Fix squad preferences for rebels
  code/controllers/subsystem/job.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/squads.dm
Labels: Fix

#7852 Updates alot of tgui stuff
  code/__HELPERS/mobs.dm
  code/game/verbs/ooc.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob.dm
  code/modules/tgchat/to_chat.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui/tgui_alert.dm
  code/modules/tgui/tgui_input_list.dm
  tgui/.gitignore
  tgui/docs/component-reference.md
  tgui/package.json
  tgui/packages/common/collections.spec.ts
  tgui/packages/common/collections.ts
  tgui/packages/common/math.ts
  tgui/packages/tgfont/package.json
  tgui/packages/tgui-dev-server/reloader.js
  tgui/packages/tgui-panel/chat/middleware.js
  tgui/packages/tgui-panel/chat/renderer.js
  tgui/packages/tgui-panel/index.js
  tgui/packages/tgui-panel/settings/SettingsPanel.js
  tgui/packages/tgui-panel/settings/constants.js
  tgui/packages/tgui-panel/settings/middleware.js
  tgui/packages/tgui-panel/settings/reducer.js
  tgui/packages/tgui-panel/styles/components/Chat.scss
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/components/AnimatedNumber.js
  tgui/packages/tgui/components/Box.tsx
  tgui/packages/tgui/components/InfinitePlane.js
  tgui/packages/tgui/components/LabeledList.tsx
  tgui/packages/tgui/components/Popper.tsx
  tgui/packages/tgui/components/RoundGauge.js
  tgui/packages/tgui/components/TimeDisplay.js
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/format.js
  tgui/packages/tgui/interfaces/AlertModal.js
  tgui/packages/tgui/interfaces/ListInput.js
  tgui/packages/tgui/interfaces/PortableGenerator.js
  tgui/packages/tgui/interfaces/common/BeakerContents.js
  tgui/packages/tgui/interfaces/common/InterfaceLockNoticeBox.js
  tgui/packages/tgui/interfaces/common/PortableAtmos.js
  tgui/packages/tgui/layouts/Window.js
  tgui/packages/tgui/styles/atomic/links.scss
  tgui/packages/tgui/styles/components/Button.scss
  tgui/packages/tgui/styles/components/Dropdown.scss
  tgui/packages/tgui/styles/components/Knob.scss
  tgui/packages/tgui/styles/components/ProgressBar.scss
  tgui/packages/tgui/styles/components/RoundGauge.scss
  tgui/packages/tgui/styles/components/Tabs.scss
  tgui/packages/tgui/styles/components/Tooltip.scss
  tgui/packages/tgui/styles/interfaces/AlertModal.scss
  tgui/packages/tgui/styles/interfaces/Changelog.scss
  tgui/packages/tgui/styles/interfaces/ListInput.scss
  tgui/packages/tgui/styles/layouts/TitleBar.scss
  tgui/public/tgui.html
  tgui/yarn.lock
Labels: Code Improvement, Fix, UI, Quality of Life, Upstream port

#7849 [CRITICAL] fix gun jamming
  code/modules/projectiles/gun_system.dm
Labels: Fix, Test Merge Candidate

#7851 Headsets will no longer blow up in your face for no reason
  code/__DEFINES/factions.dm
  code/game/objects/items/radio/headset.dm
Labels: Fix

#7843 Fix able to buy forbidden items in civil war
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Fix

#7858 Fixes cocoons opening instantly
  code/game/objects/items/cocoon.dm
Labels: Fix

#7811 Fixes the mortar flare shell not working
  code/game/objects/machinery/mortar.dm
Labels: Fix, Content Expansion

#7838 Stops the hivemind from getting caugh ton razorwires
  code/game/objects/structures/razorwire.dm
Labels: Fix

#7821 Chemistry access changes
  code/datums/jobs/job/marines.dm
  code/game/objects/machinery/kitchen/smartfridge.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
Labels: Balance/Rebalance, Quality of Life

#7768 Defiler reagentslash change
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Labels: Removal, Balance/Rebalance, Test Merge Candidate

#7761 uniforms are bulky
  code/modules/clothing/under/under.dm
Labels: Fix

#7676 Delete clown paraphernalia from maps
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/datums/skills.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
Labels: Removal, Map Edit

#7853 Number of oversight fixes for LZ1
  _maps/map_files/LV624/LV624.dmm
Labels: Fix, Map Edit, Quality of Life

#7855 Gives the alamo an AI holopad.
  _maps/shuttles/alamo.dmm
Labels: Map Edit, Quality of Life

#7445 You can now color jaeger any color you want
  code/modules/modular_armor/armor_pieces.dm
  code/modules/modular_armor/modular.dm
Labels: Test Merge Candidate, Content Expansion

#7876 Fix jaeger coloring in hvh
  code/modules/modular_armor/armor_pieces.dm
  code/modules/modular_armor/modular.dm
Labels: Fix

#7861 water buff
  code/modules/reagents/reagents/other.dm
Labels: Balance/Rebalance

#7763 Fixes King Minimap Icon
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
Labels: Fix

#7666 Wraith Ability Refactor/Fixes
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/wraith.dm
Labels: Balance/Rebalance, Refactor, Fix

#7841 Few changes to Sulaco
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/area/sulaco.dm
  icons/turf/areas.dmi
Labels: Sprites, Map Edit, Mechanic, Content Expansion

#7784 Relocates Xeno Evolution Panel Backend From Hive_Status To New Datum Evolution_Panel
  code/_globalvars/tgui.dm
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  tgmc.dme
Labels: Code Improvement, Refactor

#7882 Fixes t-ray scanners not showing wires
  code/game/objects/items/scanners.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/recycling/disposal.dm
Labels: Fix

#7602 Fultons are now limited use and more expensive, decreases price of ASRS, and adds fultons to SL vendor and operational vendor
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
  code/modules/requisitions/fulton.dm
Labels: Balance/Rebalance, Test Merge Candidate, Content Expansion

#7550 Allow the AI to turn on red alert (without ctrl click now)
  code/modules/security_levels/keycard_authentication.dm
Labels: Content Expansion

#7652 Remove monkey cubes from shipside
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Removal, Map Edit

#7865 More minimap icons
  code/datums/jobs/job/shipside.dm
  icons/UI_Icons/map_blips.dmi
Labels: Sprites, Content Expansion

#7889 laser pistol and magazines fit in your belt
  code/game/objects/items/storage/belt.dm
  icons/obj/clothing/belts.dmi
Labels: Sprites, Balance/Rebalance

#7875 adds bayonet knife to marine vending, moves knives to utility, combat knife buff
  code/game/objects/items/weapons/blades.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/items/weapons.dmi
Labels: Sprites, Balance/Rebalance, Fix, Quality of Life

#7890 tyr head is now inifnite
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#7907 Remove top level dmi
  Handheld charger.dmi
Labels: Fix

#7878 Buffs chem dispenser recharging
  code/modules/reagents/machinery/chem_dispenser.dm
  icons/obj/machines/chemical_machines.dmi
  icons/obj/machines/vending.dmi
Labels: Sprites, Balance/Rebalance, Fix, Mechanic

#7869 Flare gun improvements
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/misc.dm
  code/modules/projectiles/guns/specialist.dm
  icons/obj/items/gun.dmi
Labels: Sprites, Content Expansion

#7845 Fix rebel huds
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/marines.dm
  code/game/data_huds.dm
  icons/mob/hud.dmi
Labels: Sprites, Fix

#7854 Bunch of changes on debug ship
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
Labels: Map Edit, Administration

#7905 Fixes flamer ammo hud disappearing
  code/modules/projectiles/guns/flamer.dm
Labels: Fix

#7894 Crusher has less weed speed
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Labels: Balance/Rebalance

#7859 you can fire the sawnoff one handed
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance/Rebalance

#7806 king takes 90 minutes to enter the round
  code/__DEFINES/mode.dm
Labels: Balance/Rebalance, Test Merge Candidate

#7773 Reduces ravager slash damage
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
Labels: Balance/Rebalance

#7692 Adds a new rifle type to marines-Skirmish Rifle
  code/__DEFINES/calibers.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/Marine/gun64.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  sound/weapons/guns/fire/t21.ogg
  sound/weapons/guns/fire/t21_empty.ogg
  sound/weapons/guns/interact/t21_reload.ogg
  sound/weapons/guns/interact/t21_unload.ogg
Labels: Sprites, Sound, Test Merge Candidate, Mechanic

#7919 hypervene autoinjectors have a new sprite to differentiate them
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/modules/reagents/machinery/chem_master.dm
  icons/obj/items/syringe.dmi
Labels: Sprites, Quality of Life

#7910 Makes it clearer when you are denied access to a vendor
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Quality of Life

#7908 Adds plasma cutter order to requisitions
  code/modules/reqs/supplypacks.dm
Labels: Mechanic

#7901 Display round id and playtime in notes panel
  code/modules/admin/panels/note_panel.dm
Labels: Administration

#7922 Clarify silo and larva generation
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Quality of Life

#7924 Updates github close timer message
  .github/workflows/stale.yml
Labels: GitHub

#7921 Reduces Observe / Ghost at Post-Round Start Text
  code/modules/mob/new_player/new_player.dm
Labels: Fix

#7870 Makes the bolt action rifle act closer like a bolt action codewise.
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Code Improvement

#7923 Fix sg having infinite sg goggles with loadout vendor
  code/datums/loadout/loadout_helper.dm
Labels: Fix

#7527 Motion detector is now a rail attachment for guns
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/loadout.dm
  code/__DEFINES/objects.dm
  code/__HELPERS/view.dm
  code/datums/actions/item_action.dm
  code/datums/jobs/job/marines.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-items.dmi
  icons/Marine/marine-weapons.dmi
Labels: Sprites, Balance/Rebalance, Map Edit, Test Merge Candidate

#7534 Transvitox Bonus Damage Now Applies to Converted Burn Damage Too
  code/modules/reagents/reagents/toxin.dm
Labels: Balance/Rebalance, Stale, Test Merge Candidate

#7933 Makes FOB Drone Console Indestructable
  code/modules/mining/remote_fob/remote_fob_computer.dm
Labels: Fix

#7928 Fixes infinite antibiotics
  code/__DEFINES/mobs.dm
Labels: Fix

#7915 Changes shard sound effects
  code/game/objects/items/shards.dm
  sound/effects/shard1.ogg
  sound/effects/shard2.ogg
  sound/effects/shard3.ogg
  sound/effects/shard4.ogg
  sound/effects/shard5.ogg
Labels: Sound

#7936 Removes Unintended Buildstate Check For Gen Decorruption
  code/modules/power/groundmap_geothermal.dm
Labels: Removal, Fix

#7942 Larvas sources are shown at the end of the game
  code/controllers/subsystem/silo.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/xenomorph.dm
  code/datums/round_statistics.dm
  code/game/objects/items/cocoon.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Quality of Life

#7925 Fix Blue Crown Leadership Being Deleted On Evo
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#7941 On the right! A few missing mobs have been added to the player panel menu
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
Labels: Administration

#7938 minigun has a fire animation
  code/modules/projectiles/guns/specialist.dm
  icons/Marine/gun64.dmi
Labels: Sprites

#7863 Mortar and minigun can be bought in civil war
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Stale

#7953 Ai node refactor
  code/__DEFINES/_math.dm
  code/__DEFINES/ai.dm
  code/__HELPERS/ai.dm
  code/modules/ai/ai_node.dm
  tgmc.dme
Labels: Refactor

#7973 Fix rock layer on magmoor
  code/game/objects/structures/flora.dm
Labels: Fix

#7948 Adds telecoms to the list of no go places for wraith
  code/modules/mob/living/carbon/xenomorph/castes/wraith/wraith.dm
Labels: Fix
