Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2021-03, with the labels that each got.

#6192 Fix appearance bans on xenos
  code/modules/mob/living/carbon/xenomorph/login.dm
Labels: Administration, Fix

#6167 Two Handed Update
  code/game/objects/items/weapons/twohanded.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/modular_armor/modular.dm
Labels: Balance/Rebalance

#6182 Icons for TL84
  code/__DEFINES/dcs/signals.dm
  code/datums/actions/item_action.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/flamer.dm
  icons/mob/actions.dmi
Labels: Quality of Life, Sprites

#6200 Fixes magic revives (again)
  code/game/objects/items/defibrillator.dm
Labels: Fix

#6197 Fixes the AI not having access to APC's
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/power/apc.dm
Labels: Fix

#6218 Crates no longer sell for req points (This kills the stonks)
  code/modules/requisitions/_supply_export.dm
Labels: Fix

#6208 Adds description to TL-102 telling how to repair it.
  code/game/objects/machinery/smartgun_mount.dm
Labels: Quality of Life

#6204 Boiler Neurogas Now Extinguishes Fire Properly
  code/modules/projectiles/guns/flamer.dm
Labels: Fix

#6064 Bucketed autofire system
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/autofire.dm
  code/game/world.dm
  tgmc.dme
Labels: Code Improvement

#6209 Siloless collapse takes 20 minutes instead of 10
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance/Rebalance

#6059 adds railgun deletes m92
  code/game/objects/effects/landmarks/landmarks.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/projectiles.dmi
  sound/weapons/guns/fire/railgun.ogg
Labels: Feature, Removal, Sound, Sprites, Test Merge Candidate

#6169 you can restock hypo clicking on pill bottles
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Quality of Life

#6185 Added Sprite For trampop
  icons/obj/items/storage/storage.dmi
Labels: Fix, Quality of Life, Sprites

#6174 Allows pre-loading reagents into the Vali system
  code/datums/components/chem_booster.dm
  code/modules/paperwork/paper.dm
  icons/mob/radial.dmi
Labels: Feature, Sprites

#6128 Silo base spawn rate nerf
  code/controllers/subsystem/silo.dm
Labels: Balance/Rebalance, Freeze Pass, Test Merge Candidate

#6217 Cleans some TGUI interfaces code, adds typescript settings for tgui on vscode and fixes ESLint
  .gitignore
  .vscode/settings.json
  tgui/.yarn/sdks/eslint/lib/api.js
  tgui/.yarn/sdks/eslint/package.json
  tgui/.yarn/sdks/typescript/bin/tsc
  tgui/.yarn/sdks/typescript/bin/tsserver
  tgui/.yarn/sdks/typescript/lib/tsc.js
  tgui/.yarn/sdks/typescript/lib/tsserver.js
  tgui/.yarn/sdks/typescript/lib/typescript.js
  tgui/packages/tgui/interfaces/Cargo.js
  tgui/packages/tgui/interfaces/Droppod.js
  tgui/packages/tgui/interfaces/MarineSelector.js
  tgui/packages/tgui/interfaces/ShuttleManipulator.js
  tgui/packages/tgui/interfaces/SupplyDropConsole.js
  tgui/packages/tgui/interfaces/Vending.js
  tgui/public/tgui.bundle.js
Labels: Fix, UI

#6215 Xenos can correctly see the siloless collapse timer
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#6213 Nerfs Miner Overclock Upgrade
  code/game/objects/machinery/miner.dm
Labels: Balance/Rebalance

#6221 Silo were not maturing if placed after shutters
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix

#6220 Lowers the cost for tesla cells to be 10 instead of 30
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#6168 Allows IFF Bullets to pass over the TL-102 HSG
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance

#6225 Gives the 102 a hud like the sentries
  code/game/data_huds.dm
  code/game/objects/machinery/smartgun_mount.dm
Labels: Feature

#5839 New Scatterspit Ability for Spitter Caste
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/round_statistics.dm
  code/game/objects/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/projectiles/ammo_datums.dm
  icons/mob/actions.dmi
Labels: Balance/Rebalance, Feature, Sprites

#6236 Fixes vali actions/overlay removal runtime
  code/datums/components/chem_booster.dm
Labels: Fix

#6231 hypervene no longer is purged by /medicine purges
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/scanners.dm
  code/modules/reagents/reactions/medical.dm
  code/modules/reagents/reagents/medical.dm
Labels: Balance/Rebalance

#6212 Fixes FS key giving command channel
  code/game/objects/items/radio/encryptionkey.dm
Labels: Fix

#6096 Guns Rattle When Low Ammo
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
Labels: Feature, Quality of Life, Test Merge Candidate

#6237 Changes type 71 to 3 burst
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance/Rebalance

#6194 Psych balance tweak
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/silo.dm
  code/datums/gamemodes/distress.dm
  code/datums/jobs/job/job.dm
Labels: Balance/Rebalance

#6190 Jetpack nerf
  code/game/objects/items/jetpack.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6251 HOTFIX - Removed Headbites and Regurgitate From Wraith
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Labels: Fix

#6253 Hotfix for wraith signal issues
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix, Priority: CRITICAL

#6211 Miner Holds More
  code/game/objects/machinery/miner.dm
Labels: Quality of Life

#6240 Unbalance message fix
  code/modules/mob/new_player/new_player.dm
Labels: Fix

#6245 Adds armored labcoat
  code/datums/jobs/job/shipside.dm
  code/modules/clothing/suits/labcoat.dm
  icons/mob/suit_0.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#6223 Marine respawn from 45 minutes to 30 minutes
  code/_globalvars/admin.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6234 Psy drain, another way of getting psych points and larva
  code/__DEFINES/traits.dm
  code/game/data_huds.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items/defibrillator.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/living_health_procs.dm
  icons/mob/hud.dmi
  sound/magic/end_of_psy_drain.ogg
Labels: Balance/Rebalance, Feature, Sound, Sprites, Test Merge Candidate

#5961 Chestburst Is No Longer Permadeath
  code/game/objects/items/defibrillator.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
Labels: Atomic, Balance/Rebalance, Test Merge Candidate

#6244 Refactor looping sounds into a subsystem
  code/__DEFINES/_subsystems.dm
  code/controllers/subsystem/loopingsound.dm
  code/datums/looping_sounds/_looping_sound.dm
  tgmc.dme
Labels: Refactor

#6241 disables smartgunner, makes smart machinegun useable by anyone
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/extended.dm
  code/datums/gamemodes/infestation.dm
  code/datums/jobs/job/marines.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Removal

#6243 Mass replace flags_armor_protection = 0
  code/game/objects/items/tools/flame_tools.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/wiz_robe.dm
Labels: Code Improvement

#6260 Add scripts for running with tgsv4 + fix linux compatibility issue with extools
  .tgs4.yml
  code/game/world.dm
  tools/tgs4_scripts/PreCompile.sh
  tools/tgs4_scripts/PreSynchronize.bat
  tools/tgs4_scripts/PreSynchronize.ps1
  tools/tgs4_scripts/PreSynchronize.sh
Labels: Fix, Tools

#6214 No siloless collapse until 13:00
  code/__DEFINES/mode.dm
  code/datums/gamemodes/distress.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6113 AI can use fob drone, no more mats limit for it
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  code/__DEFINES/objects.dm
  code/modules/mining/remote_fob/remote_fob_actions_misc.dm
  code/modules/mining/remote_fob/remote_fob_computer.dm
Labels: Balance/Rebalance, Map Edit, Test Merge Candidate

#6255 Make Larva proper nouns
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
Labels: Fix, Grammar and Formatting

#6254 Increase Hypervene Metabolism Rate
  code/modules/reagents/reagents/medical.dm
Labels: Fix

#6261 Fix vending machine UI overlaying itself
  tgui/packages/tgui/interfaces/MarineSelector.js
  tgui/packages/tgui/interfaces/Vending.js
  tgui/public/tgui.bundle.js
Labels: Fix, UI

#6262 Fix spurious test fail
  code/modules/unit_tests/spawn_humans.dm
Labels: Fix, Unit Tests

#6246 Port ambience subsystem
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/sound.dm
  code/controllers/subsystem/ambience.dm
  code/game/area/area.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences_toggles.dm
  tgmc.dme
Labels: Refactor

#6250 orbit menu QOL's and fixes
  code/__HELPERS/unsorted.dm
  code/_onclick/hud/hud.dm
  code/datums/components/orbiter.dm
  code/game/atoms.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/dead/observer/orbit.dm
  html/images/ghost.png
  tgui/packages/tgui/interfaces/Orbit.js
  tgui/public/tgui.bundle.js
Labels: Code Improvement, Fix, Quality of Life, UI

#6229 Gens psych points outpute scale with server pop
  code/controllers/subsystem/points.dm
  code/controllers/subsystem/silo.dm
  code/modules/power/groundmap_geothermal.dm
Labels: Balance/Rebalance, Test Merge Candidate

#5963 Xeno Health Alert Improvements
  code/__DEFINES/mobs.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Code Improvement, Do Not TM

#6267 CAS Balance Pass (orbit effect reduction, rocket buff)
  code/controllers/subsystem/points.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
Labels: Balance/Rebalance

#6268 flush queue in preloading part of tgui_panel
  code/modules/tgui_panel/tgui_panel.dm
Labels: Fix

#6270 Fix TGUI Reloading
  tgui/packages/tgui-dev-server/reloader.js
Labels: UI

#6256 Add banish logging
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Administration

#6060 Xeno turrets
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/objects.dm
  code/_onclick/click.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/controllers/subsystem/autofire.dm
  code/datums/components/full_auto_fire.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/Marine/marine-items.dmi
  icons/Xeno/acidturret.dmi
  icons/mob/actions.dmi
Labels: Feature, Map Edit, Sprites

#6271 Actually make it so the engineering shutters have their own buttons.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/shutters.dm
Labels: Fix, Map Edit

#6224 new chem cigs
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/machinery/vending/vending_types.dm
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/items/cigarettes.dmi
Labels: Feature, Sprites

#6280 Fix voter fraud
  code/modules/mob/new_player/poll.dm
Labels: Fix, In Game Exploit

#6282 Binary insert test
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/binary_insert.dm
Labels: Unit Tests

#6281 Drop pods are now animated
  code/game/objects/structures/droppod.dm
Labels: Quality of Life

#6279 Removes soul
  code/__HELPERS/type2type.dm
  code/game/objects/items/circuitboards/computer.dm
  code/modules/detectivework/scanning_console.dm
Labels: Code Improvement

#6296 Fix a cause of screen hard dels
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
Labels: Fix, Priority: High

#6289 ROF Compensation Buffs to the GPMG and LMG
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#6235 PoS prep overhaul
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit

#6069 Add support for right click human actions
  code/__DEFINES/dcs/signals.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
Labels: Code Improvement

#6294 Reduce sentry costs
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#6297 Fixes potential hard deletes for destroyed tunnels
  code/game/objects/structures/xeno.dm
Labels: Code Improvement

#6299 Megaphone Respects IC filter
  code/game/objects/items/megaphone.dm
Labels: Administration, Fix

#6302 Small Aim Order Buff
  code/modules/projectiles/gun_helpers.dm
Labels: Balance/Rebalance

#6305 Turrets shoot on random part of body
  code/modules/xenomorph/xeno_structures.dm
Labels: Balance/Rebalance

#6295 Turrets are destroyed on hijack
  code/__DEFINES/mode.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Balance/Rebalance

#6300 Gun rattle update
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist.dm
  sound/weapons/guns/fire/DMR_low.ogg
  sound/weapons/guns/fire/GPMG_low.ogg
  sound/weapons/guns/fire/T64_low.ogg
  sound/weapons/guns/fire/tl127_low.ogg
Labels: Feature, Removal, Sound

#6276 You can't get psy points in crash
  code/__DEFINES/mode.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/points.dm
  code/datums/gamemodes/distress.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/power/groundmap_geothermal.dm
Labels: Balance/Rebalance

#6307 Agrip now has an actual negative
  code/modules/projectiles/gun_attachables.dm
Labels: Balance/Rebalance

#6303 Xeno turrets lose IFF
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#6309 Add two missing wires to Sulaco surgery
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Atomic, Fix, Map Edit

#6310 Add some cameras and lights to the sulaco. Again.
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Atomic, Fix, Map Edit

#6257 Adding Missing Incorporeal Checks
  code/_onclick/item_attack.dm
  code/_onclick/other_mobs.dm
  code/controllers/subsystem/explosions.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/misc.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#6263 Make it so requisition can spend some of their money into vouchers for dropships.
  code/game/objects/items/misc.dm
  code/game/objects/machinery/dropship_part_fabricator.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature

#6301 Cooldown Fix for Fling and Grapple Toss
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Balance/Rebalance

#6199 Making a pool create a tunnel next to it
  code/modules/xenomorph/xeno_structures.dm
Labels: Feature

#6312 Add some fire alarms to the sulaco. Along with ONE camera because i can't be bothered to make another PR just for that one.
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Atomic, Fix, Map Edit

#6317 fix icon for chempacket
  icons/obj/items/cigarettes.dmi
Labels: Fix, Sprites

#6316 Adds a lot of missing fire shutters to the sulaco. Sister commit to the fire alarms.
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Atomic, Fix, Map Edit

#6321 Nerfs GPMG's aim mode rate of fire.
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#6324 Fix gun attachments descriptions
  code/modules/projectiles/gun_attachables.dm
Labels: Fix

#6320 Adds "Broken Man" facial hair.
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Feature, Sprites

#6323 Fixes wording in modules
  code/modules/modular_armor/storage.dm
Labels: Fix

#6325 Xeno turrets more expensive
  code/__DEFINES/mode.dm
Labels: Balance/Rebalance

#6326 Delete Obsolete Compactor Upgrade
  code/game/objects/items/misc.dm
Labels: Code Improvement

#6318 Engies build faster
  code/game/objects/items/stacks/stack.dm
Labels: Balance/Rebalance

#6228 Xenos upgrade points are kept when evolving
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Balance/Rebalance, Test Merge Candidate

#6350 Scatterspit Hotkey
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
Labels: Quality of Life

#6346 Bunga. Removes a ugli wall from POS garbage & make the disposals work
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit, Removal

#6344 Silo have the same output whole game
  code/controllers/subsystem/silo.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Balance/Rebalance

#6348 Oogga - Fix some cameras orientation on Sulaco
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#6341 Changes pools timer from 20 to 10m
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance/Rebalance

#6354 Revert Flush queue in preloading of tgui_panel and fixes typescript interfaces
  code/modules/tgui_panel/tgui_panel.dm
  tgui/packages/tgui/components/Flex.tsx
  tgui/packages/tgui/components/LabeledList.tsx
  tgui/packages/tgui/routes.js
  tgui/public/tgui.bundle.js
Labels: Fix, Revert, UI

#6339 Fixes hivemind collapse shipside win condition
  code/datums/gamemodes/distress.dm
Labels: Fix

#6337 New sound when xeno turret dies
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/xenomorph/xeno_structures.dm
  sound/effects/xeno_turret_death.ogg
Labels: Fix, Sound

#6355 Puts WP smoke on Incendiary OB
  code/game/objects/structures/orbital_cannon.dm
Labels: Balance/Rebalance

#6340 Changes win conditions
  code/datums/gamemodes/distress.dm
Labels: Balance/Rebalance

#6334 Small Remap of Sulaco synth room to prevent instant kill zone on alamo crash
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#6345 Silo price up
  code/__DEFINES/mode.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance/Rebalance, Quality of Life

#6315 buff medics fireman carry ((in the code. medics would take MORE time than marines))
  code/modules/mob/living/carbon/human/human.dm
Labels: Balance/Rebalance, Fix

#6219 [READY]Automatic Miner Upgrade
  code/game/objects/items/misc.dm
  code/game/objects/machinery/autolathe_datums.dm
  code/game/objects/machinery/miner.dm
  icons/obj/mining_drill.dmi
Labels: Feature, Sprites

#6367 TGUI Preferences to char setup
  code/modules/client/preferences.dm
Labels: Quality of Life

#6362 Venting out lights for PoS
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit

#6328 Booga Booga the FOB drone has a light now so you can see things.
  code/modules/mining/remote_fob/remote_fob_fobdrone.dm
Labels: Fix

#6364 neurospit now injects non purging neurotoxin
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Balance/Rebalance

#6331 You can see how much ammo the condor minigun has now. Also typo fix.
  code/game/objects/structures/cas_plane_parts.dm
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#6336 Sandbags are no longer bulky, can hold in construction pouch and be build faster by engies
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/storage/pouch.dm
Labels: Balance/Rebalance

#6274 Banish Tweaks and Fixes
  code/game/turfs/closed.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Balance/Rebalance, Fix

#6383 Fix certain nades always harddelling
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Fix

#6385 Fix uniqueaction
  code/_onclick/click.dm
  code/game/objects/items.dm
Labels: Fix

#6370 nerfs healing infusion cd
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Balance/Rebalance

#6293 Droids can now use guns
  code/__DEFINES/vehicles.dm
  code/datums/components/remote_control.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/vehicles/unmanned/unmanned_droid.dm
  code/modules/vehicles/unmanned/unmanned_turrets.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
  icons/obj/unmanned_vehicles.dmi
Labels: Feature, Fix, Sprites

#6335 Queue system to spawn as larva
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/distress.dm
  code/datums/jobs/job/xenomorph.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Quality of Life, Test Merge Candidate

#6366 Salvage dead xenos is gone
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
Labels: Removal

#6352 Adds 1 Synths job slot every 40 pop
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
Labels: Balance/Rebalance

#6384 Fix rightclick safety thing
  code/modules/projectiles/gun_helpers.dm
Labels: Fix

#6388 Fixed Bug With Scatterspit Projectiles Going Too Far
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Fix

#6391 Corpsmen Storage QoL V2
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Feature

#6292 Transit shutters has had its ID changed
  code/game/objects/machinery/doors/shutters.dm
Labels: Fix, Stale

#6399 Missing wire in hangar
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#6400 Adds more cameras to the POS
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#6393 Psy draining is quicker
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance/Rebalance

#6386 Cuts fuel blocks price in half, Lowers most OB's by half
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#6398 Queue larva system hard del protection
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Do Not Merge, Fix, Test Merge Candidate

#6416 Nests are no longer buildable
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Removal

#6407 Adds a shortcut for the AI to turn on & off fire alarms using shift & Ctrl click.
  code/_onclick/ai.dm
Labels: Quality of Life

#6389 QoL Ammo Box
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Quality of Life

#6338 Origin of xeno job point recorded
  code/__DEFINES/jobs.dm
  code/controllers/subsystem/silo.dm
  code/datums/jobs/job/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Code Improvement

#6424 Queen time lock (10 hours)
  code/datums/jobs/job/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Administration

#6356 QOL Sulaco tweaks and fixes.
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Map Edit, Quality of Life

#6426 minor droid grammar fixes
  code/modules/vehicles/unmanned/unmanned_droid.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
  code/modules/vehicles/unmanned/unmanned_vehicle_remote.dm
Labels: Grammar and Formatting

#6434 Xeno queue QOL
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Quality of Life

#6429 Fixes FC Vendor.
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Fix, Removal

#6430 Marine Boots QoL
  code/datums/jobs/job/shipside.dm
Labels: Quality of Life

#6435 Fixes SSA belt sprite
  icons/obj/clothing/belts.dmi
Labels: Fix, Sprites

#6433 Arith Replacement
  code/game/objects/items/reagent_containers/autoinjectors.dm
Labels: Quality of Life

#6436 Adds Loaded states for Dropship weapons
  code/game/objects/structures/dropship_ammo.dm
  icons/Marine/mainship_props.dmi
  icons/Marine/mainship_props64.dmi
Labels: Fix, Sprites

#6439 Fixes/Changes Powernet/ Disposalnet and Atmosnets on most maps (and some cameras)
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/MarineHQ/MarineHQ.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/modularmaps/big_red/operation.dmm
  _maps/modularmaps/lv624/atmospherics.dmm
  _maps/modularmaps/lv624/cargo_bay.dmm
  _maps/modularmaps/lv624/internal_affairs.dmm
  _maps/modularmaps/lv624/robotics.dmm
  code/modules/power/cable.dm
Labels: Fix, Map Edit
