Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2021-01, with the labels that each got.

#5608 Tactical reload ammo HUD fix
  code/modules/projectiles/gun_system.dm
Labels: Fix

#5619 Fixes the POS' hull.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#5631 Rail attachment keybind
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/human.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob_helpers.dm
Labels: Feature

#5624 Renames Aim Mode button to "Take Aim", changes some wording, Adds better icon for Aim Mode
  code/datums/actions/item_action.dm
  code/modules/codex/entries/guns_codex.dm
  code/modules/projectiles/gun_helpers.dm
  icons/mob/actions.dmi
Labels: Code Improvement, Sprites, Tweak

#5541 Unskilled marines can now apply Miner Modules
  code/game/objects/machinery/miner.dm
Labels: Balance/Rebalance, Tweak

#5617 Brings pilot helms in line with other helmets
  code/modules/clothing/head/helmet.dm
Labels: Balance/Rebalance

#5623 Makes gyroscopic stabilizer reduce aim mode movement speed reduction by 50%
  code/modules/codex/entries/weapons_codex.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance

#5514 Larva may now cancel out of spawning
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#5286 Hive Alerts for Hive Leaders and Damaged Low HP Xenos/Resin Silos
  code/__DEFINES/admin.dm
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/preferences.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/atom_hud.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/keybinding/xeno.dm
  code/datums/round_statistics.dm
  code/game/data_huds.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/game/objects/structures/xeno.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/mob/actions.dmi
Labels: Feature, Sprites

#5628 Anti early fob camp tweak
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Tweak

#5644 Fix boiler globule lock
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Fix

#5643 Ai is now a master engineer
  code/datums/jobs/job/shipside.dm
  code/datums/skills.dm
Labels: Fix

#5616 Removes requirement to stand still when activating aim mode
  code/modules/projectiles/gun_helpers.dm
Labels: Balance/Rebalance, Removal, Requires Testing

#5655 Updates ST Uniform
  icons/mob/uniform_0.dmi
Labels: Feature, Sprites

#5638 add ammoboxes to vendors
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Tweak

#5602 Unfucks LZ1 ice.
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Balance/Rebalance, Map Edit, Tweak

#5641 Lava Outpost Upgrade/Overhaul
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
  code/game/area/lava_outpost.dm
  code/game/objects/machinery/door_control.dm
  icons/turf/areas.dmi
Labels: Feature, Map Edit, Sprites, Tweak

#5342 Adds a roomba
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/machinery/bots/bots.dm
  code/game/objects/machinery/roomba.dm
  icons/obj/aibots.dmi
  icons/obj/items/grenade.dmi
  tgmc.dme
Labels: Code Improvement, Feature, Map Edit, Requires Testing, Sprites, Test Merge Candidate

#5604 CAS Ammo updates and cleanup
  README.md
  code/__HELPERS/movable.dm
  code/__HELPERS/unsorted.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/game/objects/machinery/camera/camera_assembly.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/turfs/open.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/shuttle/cas_plane.dm
  code/modules/vehicles/cargo_train.dm
  code/modules/vehicles/train.dm
  icons/Marine/mainship_props.dmi
  icons/effects/heavyimpact.dmi
  sound/effects/casplane_flyby.ogg
  tgmc.dme
  tgui/packages/tgui/interfaces/MarineCasship.js
  tgui/packages/tgui/public/tgui.bundle.js
Labels: Code Improvement, Feature, Fix, Refactor, Sound, Sprites, UI

#5648 Fix of #5629
  code/modules/reagents/reactions/food_drink.dm
Labels: Fix, Tweak

#5651 Hyposprays fits into medical jaeger storage
  code/modules/modular_armor/storage.dm
Labels: Tweak

#5649 Fix of two recipes for virus food
  code/modules/reagents/reactions/other.dm
Labels: Fix, Tweak

#5674 fixes acid spray not passing damage correctly
  code/game/objects/effects/aliens.dm
Labels: Fix, Trivial

#5673 Observers Can Now Properly Move to Rally Hive and Resin Silo Death Alerts
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix

#5667 New Hairs
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Feature, Sprites

#5658 Made a var for xeno movement speed on weeds
  code/game/objects/effects/weeds.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Code Improvement

#5642 Tactical binoculars changes
  code/game/objects/effects/overlays.dm
  code/game/objects/items/binoculars.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/structures/orbital_cannon.dm
  code/modules/shuttle/cas_plane.dm
  icons/obj/items/projectiles.dmi
Labels: Sprites, Tweak

#5495 Disable game mode voting over a certain cap
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/vote.dm
  config/config.txt
Labels: Administration, Config Update

#5665 Xenos can now scout their tunnel's surroundings before coming out
  code/game/objects/structures/xeno.dm
Labels: Feature

#5668 this fixes #5621 without changing stuff to much
  code/modules/reagents/reagents/medical.dm
Labels: Fix

#5652 Big boy hypospray(120u)
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Tweak

#5684 Vending Machine Language
  code/game/objects/machinery/vending/vending.dm
Labels: Fix

#5683 Corrects Powerfist Spelling Error
  code/game/objects/items/weapons/misc.dm
Labels: Fix

#5661 Fixes Shuttle Crushed Huggers
  code/game/objects/effects/weeds.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/xeno.dm
Labels: Fix, In Game Exploit

#5657 Converts REM to a reagent var
  code/__DEFINES/reagents.dm
  code/game/objects/machinery/autodoc.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/drink.dm
  code/modules/reagents/reagents/food.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Tweak

#5682 2415 > 2416
  code/__DEFINES/__game.dm
  code/modules/mob/new_player/new_player.dm
Labels: Tweak

#5677 fixes some gloves not showing and handcuffs
  code/modules/clothing/clothing.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/mob/living/carbon/monkey/update_icons.dm
  icons/mob/mob.dmi
  icons/mob/monkey.dmi
Labels: Fix, Sprites

#5670 changes PAS to use another armor icon.
  code/modules/clothing/suits/marine_armor.dm
Labels: Sprites

#5646 Mines
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Tweak

#5349 New Hivelord Ability: Healing Infusion (Replaces Acidic Salve)
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/keybinding/xeno.dm
  code/datums/round_statistics.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  icons/mob/actions.dmi
Labels: Feature, Refactor, Sprites, Tweak

#5570 Hijack on ground fix
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
  code/modules/shuttle/marine_dropship.dm
  sound/AI/hijack.ogg
Labels: Fix, In Game Exploit, Sound, Test Merge Candidate

#5690 C4 explosion sound
  code/game/objects/items/explosives/plastique.dm
Labels: Fix

#5691 missing hair hotfix
  icons/mob/human_face.dmi
Labels: Fix, Sprites

#5685 More and cheaper smartgun drums
  code/game/objects/items/storage/marine_boxes.dm
  code/modules/reqs/supplypacks.dm
Labels: Tweak

#5686 GPMG aim mode speed slow increased to 6 aim fire delay made 0.1
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#5671 HvH armor and vendors
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/emergency_calls/upp.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/jobs/job/upp.dm
  code/game/objects/machinery/floodlight.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/suits/marine_armor.dm
  icons/obj/machines/computer.dmi
Labels: Balance/Rebalance, Feature, Sprites, Tweak

#5654 Removes Thermobaric from Requisitions
  code/modules/reqs/supplypacks.dm
Labels: Removal, Tweak

#5705 Adds an eye patch to preference gear.
  code/modules/client/preferences_gear.dm
Labels: Feature

#5572 Computers Can Be Smashed So They Don't Block Movement
  code/__DEFINES/objects.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/computer/arcade.dm
  code/game/objects/machinery/computer/atmos_alert.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/computer/camera_console.dm
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/machinery/computer/crew.dm
  code/game/objects/machinery/computer/station_alert.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Balance/Rebalance

#5701 KBs for Healing Infusion + Rally Hive. Healing Infusion code improvement
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Code Improvement, Feature, Fix

#5707 Fixes Observer Hive Status Runtimes for Resin Silos
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#5699 Combat pack tweak
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#5615 Nerfs machinepistol fire rate to 0.2 from 0.15
  code/modules/projectiles/guns/smgs.dm
Labels: Balance/Rebalance, Needs Balance Review, Requires Testing

#5583 Mortar cleanup + logging
  code/game/objects/structures/mortar.dm
Labels: Administration, Code Improvement

#5700 Reverts 5682s general change to hyposprays and medic vendor, adds 120 unit hypospray
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Balance/Rebalance, Feature, Revert

#5717 Fixes HvH attachment vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#5711 Adressing lava outpost feedback & fixing a few mistakes
  _maps/map_files/Lava_Outpost/LavaOutpost.dmm
Labels: Feature, Fix, Map Edit, Removal, Tweak

#5732 Fix hivemind abilities
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Labels: Fix

#5735 combover fix
  code/modules/mob/new_player/sprite_accessories.dm
Labels: Fix

#5733 Negative fuel condor fixed
  code/modules/shuttle/cas_plane.dm
Labels: Fix

#5722 Fixes Bug With Rally Hive Not Being Removed From Demoted Ex-Leader Xenos
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
Labels: Fix

#5728 Needed (removed two names)
  strings/names/last_name.txt
Labels: Removal

#5712 Give distress vessels their thrusters
  _maps/shuttles/distress.dmm
  _maps/shuttles/distress_pmc.dmm
  _maps/shuttles/distress_upp.dmm
Labels: Map Edit, Tweak

#5740 Adds Supply Tablet to RO Locker
  code/datums/jobs/job/shipside.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
Labels: Tweak

#5715 pistols get aim mode now
  code/modules/projectiles/guns/pistols.dm
Labels: Balance/Rebalance

#5373 Add combat floodlights
  code/__DEFINES/misc.dm
  code/game/objects/items/lightreplacer.dm
  code/game/objects/machinery/floodlight.dm
  code/modules/power/lighting.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/machines/floodlight.dmi
Labels: Feature, Sprites

#5676 Refactors/rewrites most of implant code
  code/__DEFINES/implants.dm
  code/game/objects/items.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/implants/implantfreedom.dm
  code/game/objects/items/implants/implantneurostim.dm
  code/modules/codex/codex_mob.dm
  code/modules/surgery/implant.dm
  tgmc.dme
Labels: Refactor

#5716 revolvers get aim mode
  code/modules/projectiles/guns/revolvers.dm
Labels: Balance/Rebalance

#5745 gives the mosin, paladin 12, and ppsh new sprites
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/smgs.dm
  icons/Marine/128.dmi
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Feature, Removal, Sprites

#5749 Fixes Fog Wall Being Permeable to Humans/Bullets/Grenades
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/effects/misc.dm
Labels: Config Update, Fix

#5584 Adds tweeezers and changes known_implants to a global var
  code/datums/elements/shrapnel_removal.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/items/devices/spyglasses.dm
  code/game/objects/items/devices/tweezers.dm
  code/game/objects/items/flashlight.dm
  code/game/objects/items/scanners.dm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  icons/obj/items/items.dmi
  tgmc.dme
Labels: Code Improvement, Feature, Sprites

#5742 evac that marine already. hes a mummy!!!
  code/__DEFINES/objects.dm
Labels: Balance/Rebalance

#5744 adds ammo packets for several calibers and adds them to the marine ammo cargo vendor
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/obj/items/ammo.dmi
Labels: Feature, Sprites

#5689 New time locks
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/job_exp.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
Labels: Administration, Tweak

#5764 Medical Officer Rank Progression
  code/datums/jobs/job/shipside.dm
Labels: Feature

#5585 Removes retreat
  code/__DEFINES/mode.dm
  code/datums/gamemodes/distress.dm
  code/modules/orbits/spaceship.dm
Labels: Removal, Test Merge Candidate

#5720 Bug Fixes for Xeno Tunnels
  code/game/objects/structures/xeno.dm
Labels: Code Improvement, Fix

#5760 Improves the readability of xenoupgrade.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Refactor

#5750 Should Fix Healing Infusion Aura Issues For Good
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Fix

#5772 Sentries Gain IFF Prot, Integrity / Ammo Indicators /w HUD Components.
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/objects.dm
  code/game/data_huds.dm
  code/game/objects/machinery/sentries.dm
  code/modules/projectiles/projectile.dm
Labels: Code Improvement, Feature, Fix

#5797 fix ammo box bug
  icons/obj/items/ammo.dmi
Labels: Fix, Sprites

#5793 Fixes B18 Autodoc not stabilizing head
  code/modules/clothing/suits/marine_armor.dm
Labels: Fix

#5790 smg buff, 0.15 fire rate and aim mode, and mags fit in black webbing, t19 scatter changes
  code/modules/clothing/under/ties.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Balance/Rebalance

#5788 M3 Harness Resprite
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Sprites, Tweak

#5776 Alamo reset hijack fix
  code/modules/shuttle/marine_dropship.dm
Labels: Fix, Tweak

#5800 Fixes attachments for M412L1 and M412 Elite
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Fix

#5587 Adds the spawn controller
  code/__DEFINES/_subsystems.dm
  code/controllers/subsystem/spawning.dm
  code/modules/ai/spawners/human.dm
  code/modules/ai/spawners/spawner.dm
  code/modules/ai/spawners/xeno.dm
  tgmc.dme
Labels: Refactor

#5816 Revert "Automatic TGS DMAPI Update"
  code/__DEFINES/tgs.dm
  code/modules/tgs/core/core.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v5/_defines.dm
  code/modules/tgs/v5/api.dm
  code/modules/tgs/v5/interop_version.dm
  code/modules/tgs/v5/undefs.dm
Labels: Revert

#5773 Hivelord healing infusion nerf
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Balance/Rebalance

#5809 Sulaco Medbay Renovation
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#5778 Synthetic Rank Progression
  code/datums/jobs/access.dm
  code/datums/jobs/job/shipside.dm
Labels: Feature

#5820 [MIRROR] Fix CI failure with i386 caused by latest Ubuntu version. Pin Ubuntu version to allow us to upgrade in the future.
  .github/workflows/compile_changelogs.yml
  .github/workflows/conflicts.yml
  .github/workflows/generate_documentation.yml
  .github/workflows/round_id_linker.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .github/workflows/update_tgs_dmapi.yml
Labels: Fix, GitHub, Priority: High

#5804 Damage Delay Eliminated For Most Relevant Things
  code/game/objects/effects/aliens.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/watercloset.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_attackpaw.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#5817 sulaco medidoor
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#5822 Fix Synth ranks
  code/datums/jobs/job/shipside.dm
Labels: Fix

#5746 adds one use rpgs
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/gun.dmi
Labels: Feature, Sprites

#5726 Roony
  code/controllers/configuration/entries/game_options.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  icons/Xeno/2x2_Xenos.dmi
Labels: Config Update, Sprites

#5831 reaplces the type-71, tp,23, tp17 and m16a4 sprites with new ones, deletes type 23 subvariants
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Sprites

#5834 Fix roony stun sprite
  code/game/objects/structures/misc.dm
  icons/Xeno/2x2_Xenos.dmi
Labels: Fix, Sprites

#5849 adds ocelots m41a, deletes a few unused sprites
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Balance/Rebalance, Removal, Sprites, Tweak
