Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2022-03, with the labels that each got.

#9686 Punch and Forward charge no longer knock down sentries
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Balance/Rebalance

#9714 Synths can speak in xenocommon
  code/modules/language/language_holder.dm
Labels: Mechanic

#9695 Anti-Mat sniper buff.
  code/__DEFINES/conflict.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#9716 Entrenching Tools can now be saved in loadouts and will not pick up snow piles while folded.
  code/game/objects/items/stacks/snow.dm
  code/game/objects/items/tools/shovel_tools.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#9717 Actually fixes my pr that's only a one line change for the 2nd time (Plasma pistol only shoots while fully wielded bugfix)
  code/modules/projectiles/guns/pistols.dm
Labels: Fix

#9692 Barrenquilla Mining Facility 2.0
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
Labels: Balance/Rebalance, Stale, Fix, Map Edit, Mechanic

#9718 Removes ship cameras from Big Red underground complex
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Removal, Balance/Rebalance, Map Edit

#9715 Fixes recall not working if banishing oneself
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#9725 Fixes footsteps
  code/datums/components/footstep.dm
Labels: Fix

#9645 sentry rework
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/sentries.dm
Labels: Balance/Rebalance, Test Merge Candidate

#9691 Shutters now has an alarm played when opening early (and a 18,5~ second delay between button-press and opening)
  code/game/objects/machinery/buttons.dm
  sound/effects/shutters_alarm.ogg
Labels: Sound, Test Merge Candidate, Mechanic

#9719 Better snow digging
  code/game/objects/items/stacks/snow.dm
  code/game/objects/items/tools/shovel_tools.dm
  code/game/objects/structures/barricade.dm
Labels: Sprites, Balance/Rebalance, Quality of Life

#9731 Fixes the SL Xenonauten helmet using the Jaeger sprite
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Fix

#9650 Adds the TAT-36 AT Gun
  code/__DEFINES/calibers.dm
  code/__DEFINES/conflict.dm
  code/_globalvars/bitfields.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-atgun.dmi
  icons/mob/ammoHUD.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/projectiles.dmi
  sound/weapons/guns/fire/tat36.ogg
  sound/weapons/guns/interact/tat36_reload.ogg
Labels: Sprites, Sound, Mechanic

#9730 Shovels for everyone!
  code/__DEFINES/loadout.dm
  code/game/objects/items/radio/detpack.dm
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance/Rebalance, Quality of Life

#9729 Gives the SL the compass
  code/__DEFINES/loadout.dm
Labels: Balance/Rebalance

#9707 Modularizes LV-624 lake area, makes a number of mapping QOL changes, fixes some issues.
  _maps/map_files/LV624/LV624.dmm
  _maps/modularmaps/lv624/hydro_jungle.dmm
  _maps/modularmaps/lv624/hydro_path.dmm
  _maps/modularmaps/lv624/lakebase.dmm
  _maps/modularmaps/lv624/medbayone.dmm
  _maps/modularmaps/lv624/medbaytwo.dmm
  _maps/modularmaps/lv624/newcavevar1.dmm
  _maps/modularmaps/lv624/newcavevar10.dmm
  _maps/modularmaps/lv624/newcavevar11.dmm
  _maps/modularmaps/lv624/newcavevar12.dmm
  _maps/modularmaps/lv624/newcavevar2.dmm
  _maps/modularmaps/lv624/newcavevar3.dmm
  _maps/modularmaps/lv624/newcavevar4.dmm
  _maps/modularmaps/lv624/newcavevar5.dmm
  _maps/modularmaps/lv624/newcavevar6.dmm
  _maps/modularmaps/lv624/newcavevar7.dmm
  _maps/modularmaps/lv624/newcavevar8.dmm
  _maps/modularmaps/lv624/newcavevar9.dmm
  code/game/area/lv624.dm
  code/game/objects/effects/decals/misc.dm
  code/game/objects/effects/decals/warning_stripes.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/effects/spawners/modularmappingspawner.dm
  code/game/objects/effects/spawners/random.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/structures/curtains.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/turfs/floor_types.dm
  code/modules/mapping/modular_mapping.dm
  code/modules/shuttle/gamemodes/crash.dm
  icons/effects/blood.dmi
  icons/effects/landmarks_static.dmi
  icons/effects/warning_stripes.dmi
  icons/obj/items/casings.dmi
  icons/obj/items/shards.dmi
  icons/obj/machines/monitors.dmi
  icons/obj/mining_drill.dmi
  icons/obj/objects.dmi
  icons/obj/structures/curtain.dmi
  icons/obj/structures/structures.dmi
  icons/turf/areas.dmi
  icons/turf/floors.dmi
  icons/turf/ground_map.dmi
Labels: Sprites, Fix, Map Edit, Test Merge Candidate, Mechanic, Content Expansion

#9684 Updating Squad Leader Vendor
  code/__DEFINES/loadout.dm
Labels: Removal, Balance/Rebalance, Mechanic

#9744 Poster time Part 1: Add new posters
  code/game/objects/effects/decals/posters/bs12.dm
  icons/obj/contraband.dmi
Labels: Sprites, Mechanic

#9724 Powerpack resprites (and minor fix)
  icons/mob/back.dmi
  icons/obj/items/storage/storage.dmi
Labels: Sprites, Fix, Mechanic

#9671 Chem Lab QoL and Standardization
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Balance/Rebalance, Stale, Map Edit, Quality of Life

#9732 FF module update and description modernization.
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Balance/Rebalance, Mechanic

#9743 Remove acid gas and plasma cutters in Barrenquilla
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
Labels: Removal, Map Edit

#9748 Corporate Liaison Playtime Ranks (Approved by Tivi)
  code/datums/jobs/access.dm
  code/datums/jobs/job/shipside.dm
Labels: Mechanic

#9568 Make the T-64 Great Again
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance, Stale, Test Merge Candidate, Mechanic

#9752 Fix sniper ammo with inherited pen/sunder
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#9754 Minor previous PR essentials fix
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Fix

#9759 Fixed ALF autoburst delay
  code/modules/projectiles/guns/rifles.dm
Labels: Fix

#9762 Remove all free plasma cutters in all planetsides
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Removal, Map Edit

#9770 Barrenquilla has fire extinguishers around lava
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
Labels: Map Edit, Mechanic

#9765 Forward Charge Now Uses A Danger Icon
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Quality of Life

#9777 New Field Commander Minimap Icon
  icons/UI_Icons/map_blips.dmi
Labels: Sprites

#9782 Big Red bugfix and QOL update
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/modularmaps/big_red/bigredatmosvar1.dmm
  _maps/modularmaps/big_red/bigredatmosvar2.dmm
  _maps/modularmaps/big_red/bigredatmosvar3.dmm
  _maps/modularmaps/big_red/bigredatmosvar4.dmm
  _maps/modularmaps/big_red/bigredcargoareavar4.dmm
  _maps/modularmaps/big_red/bigredcargoareavar5.dmm
  _maps/modularmaps/big_red/bigredcargoareavar6.dmm
  _maps/modularmaps/big_red/bigredcheckpointsouthvar3.dmm
  _maps/modularmaps/big_red/bigredengineeringvar2.dmm
  _maps/modularmaps/big_red/bigredengineeringvar4.dmm
  _maps/modularmaps/big_red/bigredetavar3.dmm
  _maps/modularmaps/big_red/bigredlambdacave2.dmm
  _maps/modularmaps/big_red/bigredlzvar3.dmm
  _maps/modularmaps/big_red/bigredlzvar5.dmm
  _maps/modularmaps/big_red/bigredlzvar6.dmm
  _maps/modularmaps/big_red/bigredmedbayvar4.dmm
  _maps/modularmaps/big_red/bigredmedbayvar5.dmm
  _maps/modularmaps/big_red/bigredmedbayvar6.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
  _maps/modularmaps/big_red/bigredsecornervar2.dmm
  _maps/modularmaps/big_red/bigredsecornervar3.dmm
  _maps/modularmaps/big_red/bigredsecornervar6.dmm
  _maps/modularmaps/big_red/bigredsouthwestetavar1.dmm
  _maps/modularmaps/big_red/bigredsouthwestetavar2.dmm
  _maps/modularmaps/big_red/bigredsouthwestetavar3.dmm
  _maps/modularmaps/big_red/bigredsouthwestetavar5.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar3.dmm
  code/game/area/bigred.dm
  code/game/objects/structures/prop.dm
  icons/Marine/mainship_props.dmi
Labels: Sprites, Balance/Rebalance, Fix, Map Edit

#9733 Resizes and removes empty space around ice colony
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Removal, Balance/Rebalance, Map Edit

#9767 Poster Part 2 Redo: Putting Posters in Shipside
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/decals/posters/bs12.dm
  code/game/objects/structures/signs.dm
  icons/obj/contraband.dmi
  icons/obj/decals.dmi
Labels: Sprites, Removal, Code Improvement, Map Edit, Mechanic

#9785 at gun changes
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#9795 AT gun nerf and removes IFF on it
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/mounted.dm
Labels: Balance/Rebalance

#9791 Helmet QOL, specifically leader helmets.
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Removal, Fix, Quality of Life

#9790 Updates leader essentials kits, FC has specific Jaeger kit.
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Removal, Code Improvement, Mechanic

#9789 Give a button outside of Tadpole when someone lockdowns tadpole from inside
  _maps/shuttles/minidropship.dmm
Labels: Map Edit, Mechanic

#9755 Essentials kit Quality of life
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Removal, Quality of Life, Mechanic

#9792 Tadpole Part 2: Bring Back Medbus
  code/game/objects/machinery/vending/vending_types.dm
Labels: Balance/Rebalance, Mechanic

#9806 Nuke can no longer be teleported
  code/game/objects/structures/teleporter.dm
Labels: Balance/Rebalance, Test Merge Candidate

#9807 Updates Valhalla, adds missing items/features
  _maps/map_files/generic/Admin_Level.dmm
  code/_globalvars/lists/mobs.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix, Map Edit, Quality of Life

#9781 Modernizes Freelancers
  code/datums/components/suit_autodoc.dm
  code/datums/jobs/job/freelancers.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/storage.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/under.dm
  code/modules/codex/entries/clothing_codex.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Code Improvement, Balance/Rebalance, Fix

#9812 Abbreviation fix
  code/datums/jobs/access.dm
Labels: Grammar and Formatting

#9805 New gamemode, nuclear war (or discrash or crashtess)
  _maps/map_files/desertdam/desertdam.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/__DEFINES/loadout.dm
  code/__DEFINES/mode.dm
  code/__DEFINES/xeno.dm
  code/_globalvars/lists/objects.dm
  code/controllers/subsystem/monitor.dm
  code/controllers/subsystem/silo.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/gamemodes/infestation.dm
  code/datums/gamemodes/nuclear_war.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/reqs/supplypacks.dm
  code/modules/xenomorph/xeno_structures.dm
  config/modes.txt
  tgmc.dme
Labels: Config Update, Map Edit, Mechanic

#9798 Banishes Barrenquilla to the shadowrealm
  _maps/_basemap.dm
  _maps/barrenquilla_mining.json
  _maps/map_files/Barrenquilla_Mining/Barrenquilla_Mining_Facility.dmm
  code/__DEFINES/__game.dm
  code/datums/jobs/job/survivor.dm
  code/game/area/barrenquilla_mining.dm
  config/maps.txt
  tgmc.dme
Labels: Config Update, Removal, Map Edit

#9756 Allows engineers access to superior welding protection and gives the Xenonauten a new welding helmet sprite.
  code/__DEFINES/loadout.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites, Code Improvement, Balance/Rebalance, Mechanic

#9753 Surt light debuff removal
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Balance/Rebalance

#9757 Teleporter has max_integrity of 250, half of its health
  code/game/objects/structures/teleporter.dm
Labels: Balance/Rebalance, Waiting for PL approval

#9816 Fixes monkey cube exploit
  code/game/objects/items/reagent_containers/food/snacks.dm
Labels: Fix

#9814 Fixes an unpowered area in Chigusa
  code/game/area/desertdam.dm
Labels: Fix

#9821 Fixes Big Red virology being unbuildable before shutter drop, plus some minor changes
  _maps/modularmaps/big_red/bigredetavar2.dmm
  _maps/modularmaps/big_red/bigredlz2var2.dmm
  _maps/modularmaps/big_red/bigredlzvar6.dmm
  _maps/modularmaps/big_red/bigredmedbayvar6.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
Labels: Balance/Rebalance, Fix, Map Edit

#9822 Fixes a varedit, resolves an issue on LV624
  _maps/map_files/LV624/LV624.dmm
  code/game/turfs/floor_ground.dm
Labels: Fix, Map Edit

#9801 Keybinds supported for all actions
  code/__DEFINES/dcs/signals.dm
  code/datums/actions/action.dm
  code/datums/actions/xeno_action.dm
  code/datums/components/chem_booster.dm
  code/datums/components/suit_autodoc.dm
  code/datums/keybinding/human.dm
  icons/mob/actions.dmi
  icons/mob/radial.dmi
Labels: Sprites, Code Improvement

#9751 Runner savage damage bonus max, 1/4th
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Balance/Rebalance

#9817 Fixes invisible balloon alerts
  code/__DEFINES/layers.dm
  code/_onclick/hud/rendering/plane_master.dm
Labels: Fix

#9834 Fix recursive storage exploit
  code/modules/clothing/modular_armor/attachments/storage.dm
Labels: Fix

#9831 Patches an area of incorrect weather on Big Red, plus minor tweaks
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/modularmaps/big_red/bigredatmosvar3.dmm
  _maps/modularmaps/big_red/bigredcheckpointsouthvar1.dmm
  _maps/modularmaps/big_red/bigredcheckpointsouthvar3.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
  code/game/objects/effects/landmarks/corpsespawner.dm
Labels: Balance/Rebalance, Fix, Map Edit, Mechanic

#9813 Refactors target_stake and targets, fixes an issue.
  code/game/objects/items/shooting_range.dm
  code/game/objects/structures/target_stake.dm
  icons/obj/objects.dmi
  tgmc.dme
Labels: Sprites, Refactor, Fix

#9828 Add fire extinguishers in Alamo
  _maps/shuttles/alamo.dmm
Labels: Map Edit, Mechanic

#9794 Make coverage code actually work
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/items/shooting_range.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/OpTable.dm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/autolathe.dm
  code/game/objects/machinery/bioprinter.dm
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/machinery/deployable.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/floodlight.dm
  code/game/objects/machinery/kitchen/gibber.dm
  code/game/objects/machinery/kitchen/microwave.dm
  code/game/objects/machinery/kitchen/processor.dm
  code/game/objects/machinery/kitchen/smartfridge.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/machinery/mortar.dm
  code/game/objects/machinery/nuclearbomb.dm
  code/game/objects/machinery/pipe/pipe_dispenser.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/objs.dm
  code/game/objects/structures.dm
  code/game/objects/structures/bookcase.dm
  code/game/objects/structures/cargo_container.dm
  code/game/objects/structures/cas_plane_parts.dm
  code/game/objects/structures/coathanger.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/desertdam.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/objects/structures/landing_signs.dm
  code/game/objects/structures/memorial.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/musician.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/platforms.dm
  code/game/objects/structures/prop.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/safe.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/tank_dispenser.dm
  code/game/objects/structures/toolboxtrophy.dm
  code/game/objects/structures/window_frame.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/projectiles/projectile.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Balance/Rebalance, Fix

#9701 Burst fire balance 2.0
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance, Stale, Waiting for PL approval

#9720 The AI wants YOU to get revived
  code/game/objects/items/defibrillator.dm
  sound/effects/gladosmarinerevive.ogg
Labels: Sound, Test Merge Candidate

#9696 Boiler cloud radius no longer scales past Ancient
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#9840 Fixes magazines deleting themselves when emptied by hand.
  code/modules/projectiles/ammunition.dm
Labels: Fix

#9837 Icy Caves fixes plus minor tweaks
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/area/icy_caves.dm
  code/game/objects/machinery/doors/multi_tile.dm
  icons/obj/doors/mainship/2x1personaldoor.dmi
  icons/obj/doors/mainship/2x1personaldoor_glass.dmi
Labels: Sprites, Balance/Rebalance, Fix, Map Edit, Quality of Life

#9738 Adds the TX-54 Grenade launcher
  code/__DEFINES/calibers.dm
  code/__DEFINES/conflict.dm
  code/_globalvars/bitfields.dm
  code/datums/components/attachment_handler.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/projectile.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/ammoHUD.dmi
  icons/mob/back.dmi
  icons/mob/human_races/r_human.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  icons/obj/items/projectiles.dmi
Labels: Sprites, Sound, Code Improvement, Fix, Mechanic

#9797 Larval hugger rebalance
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Balance/Rebalance, Stale

#9847 Fixes gens sometimes just not working and needing to be recorrupted.
  code/modules/power/groundmap_geothermal.dm
Labels: Fix

#9825 Fixes razorwire duplication exploit, adds ability to blacklist medical chems
  code/game/objects/machinery/sleeper.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/reagents/holder.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Balance/Rebalance, Mechanic

#9843 Fixes AT gun APHE chain explosions
  code/modules/projectiles/projectile.dm
Labels: Fix

#9832 Tweak Minerva and PoS for FCDR to have loadout vendor and change poster's positions
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit, Mechanic

#9826 Xeno ex act refactor
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Balance/Rebalance, Refactor

#9852 Fix crusher primo advance
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Fix

#9841 Standardization of Round Start CAS ammo
  .github/CONTRIBUTING.md
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Balance/Rebalance, Map Edit, GitHub

#9838 Harversting drone primo flowers doesn't destroy them
  code/modules/xenomorph/xeno_structures.dm
Labels: Balance/Rebalance

#9844 Outfit variant support and Freelancer variants
  code/datums/emergency_calls/freelancers.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/job.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/under.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Code Improvement, Mechanic

#9870 Fixes outfit variants
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/job.dm
Labels: Fix
