Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2022-09, with the labels that each got.

#10865 Add a camera to the tadpole
  _maps/shuttles/minidropship.dmm
Labels: Map Edit, Quality of Life

#10826 CLF ERT refresh
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/modularmaps/EORG/basketball.dmm
  _maps/modularmaps/big_red/bigredsecornervar2.dmm
  code/datums/jobs/job/clf.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  icons/mob/belt.dmi
  icons/mob/feet.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/shoes.dmi
Labels: Sprites, Map Edit, Feature, Balance

#10867 MG-27 actually uses 10x27mm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
Labels: Fix

#10861 Increases the survivability of certain objects and structures
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/mining/satchel_ore_boxdm.dm
  code/modules/paperwork/filingcabinet.dm
Labels: Balance

#10804 Fix piercing projectile hitting the same atom multiple times
  code/modules/projectiles/projectile.dm
Labels: Fix

#10872 Remove girder in Big Red LZ1 and move crate in LV624
  _maps/map_files/LV624/LV624.dmm
  _maps/modularmaps/big_red/bigredlzvar2.dmm
  _maps/modularmaps/big_red/bigredlzvar3.dmm
  _maps/modularmaps/big_red/bigredlzvar8.dmm
Labels: Map Edit, Quality of Life

#10879 Update webhook to tg
  tools/WebhookProcessor/github_webhook_processor.php
Labels: Tools

#10877 Simplify Orbits
  code/modules/orbits/spaceship.dm
Labels: Balance

#10869 Combat Patrol tips of the round
  strings/tips/HvH.txt
Labels: Feature

#10860 Marine and SOM armour rebalancing
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/shoes/marine_shoes.dm
Labels: Balance

#10886 AI can now build the FOB again
  code/modules/mining/remote_fob/remote_fob_computer.dm
Labels: Fix

#10882 Defender crest-defense now provides stagger immunity
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Balance

#10858 You are now your character when spawned into vallhalla
  code/modules/mob/dead/observer/observer.dm
Labels: Quality of Life

#10899 Fixes the valhalla loadout vendor not working
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#10897 Grenade bandolier armor module
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites, Feature

#10896 Fixes POS disposals and shutters
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#10892 AI vox reaches all Z levels & all humans
  code/modules/mob/living/silicon/ai/say.dm
Labels: Fix

#10887 You can now respawn into EORD no matter your pref for it
  code/datums/gamemodes/game_mode.dm
Labels: Quality of Life

#10851 Improves the wide flamer nozzle and related refactor
  code/__HELPERS/unsorted.dm
  code/game/atoms.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/flamer.dm
Labels: Balance, Refactor, Fix

#10905 Condensing seasonals
  code/controllers/subsystem/persistence.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature, Quality of Life

#10875 V-31 tweaks
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#10874 V-21 tweak
  code/modules/projectiles/guns/smgs.dm
Labels: Balance

#10876 GL-54 tweaks
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#10902 Reduce plasma cutter to be closer to other melee
  code/game/objects/items/tools/mining_tools.dm
Labels: Balance

#10903 Wraith can't banish weeds
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#10849 Adds a buffer between a limb's max damage and the brute required to sever
  code/modules/organs/limbs.dm
Labels: Fix

#10900 RR changes (4 new ammo types, and Vendor changes for it)
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/ammoHUD.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Balance, Feature

#10909 Fixes a small typo with the mint protein bar
  code/game/objects/items/marine_gear.dm
Labels: Grammar and Formatting

#10904 Improve UV ammo logic & descriptions
  code/modules/projectiles/magazines/unmanned_vehicle.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Quality of Life

#10847 Make Tac/Rangefinder binoculars able to link to multiple mortars
  code/game/objects/items/binoculars.dm
Labels: Feature, Test Merge Candidate

#10901 Kuro2.0 gun sprites
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_back_64.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/items_righthand_64.dmi
  icons/mob/items_suit_slot_64.dmi
  icons/mob/suit_slot.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/items_mini.dmi
Labels: Sprites

#10918 Swap the AI and Synth rooms on POS
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Quality of Life

#10914 Removes two unused config vars
  code/controllers/configuration/entries/game_options.dm
  code/modules/organs/limbs.dm
Labels: Config Update, Removal

#10917 Add mining to round end stats
  code/datums/gamemodes/game_mode.dm
  code/datums/round_statistics.dm
  code/game/objects/machinery/miner.dm
Labels: Feature

#10910 Add Carrier ability: Drop all facehugger panic button
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  icons/mob/actions.dmi
Labels: Sprites, Fix, Feature

#10922 Beheading fixes
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/organs/limb_objects.dm
  code/modules/organs/limbs.dm
Labels: Fix

#10930 Remove unused and extra APC in synth room
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Removal, Map Edit

#10929 Shields can be bashed with any weapon instead of just batons
  code/game/objects/items/weapons/shields.dm
Labels: Feature

#10926 Add an update_icon() to the UV's
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Fix

#10921 X fuel exploit fix
  code/modules/projectiles/magazines/flamer.dm
Labels: Fix

#10943 Wrenching noise for wrenching req factory machines
  code/modules/factory/machines.dm
Labels: Quality of Life

#10920 Combat Patrol: Loadouts part 6 (probably)
  code/datums/quick_load_outfits.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/smgs.dm
  icons/mob/back.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/mob/modular/modular_armor_modules.dmi
  icons/obj/items/weapons.dmi
Labels: Sprites, Balance, Fix, Feature

#10925 Fixes some minor issues with chigusa
  _maps/map_files/desertdam/desertdam.dmm
Labels: Balance, Fix, Map Edit

#10938 Fixes supply drop console delay message
  code/game/objects/machinery/squad_supply/supply_console.dm
Labels: Fix

#10870 New sprites for brute kit, burn kit, and surgery membrane
  icons/obj/items/surgery_tools.dmi
  icons/obj/stack_objects.dmi
Labels: Sprites

#10937 Moves Thermal Dampening Tarp to Specialized Tab
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Quality of Life

#10944 Replace POS AI Door with an opaque one
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Quality of Life

#10942 Clarify the minigun names
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
Labels: Quality of Life

#10934 Sentry fixes
  code/modules/projectiles/sentries.dm
Labels: Fix

#10928 Making looping sounds use timer SS def
  code/controllers/subsystem/loopingsound.dm
  code/datums/looping_sounds/_looping_sound.dm
Labels: Refactor

#10946 Fix some weird ai movements
  code/controllers/subsystem/pathfinder.dm
  code/datums/components/ai.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/mob/living/living.dm
Labels: Fix

#10923 Add name and area to planted supply beacon
  code/game/objects/machinery/squad_supply/supply_beacon.dm
Labels: Quality of Life

#10793 New Map: Gelida IV [MDB ignore]
  _maps/_basemap.dm
  _maps/gelida_iv.json
  _maps/map_files/gelida_iv/gelida_iv.dmm
  code/game/area/gelida_iv.dm
  code/game/objects/effects/decals/misc.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/platforms.dm
  code/game/objects/structures/prop.dm
  code/game/turfs/closed.dm
  code/game/turfs/floor_ground.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/open.dm
  config/maps.txt
  icons/Marine/mainship_props.dmi
  icons/Marine/mainship_props96.dmi
  icons/effects/96x96.dmi
  icons/obj/stationobjs.dmi
  icons/obj/structures/crates.dmi
  icons/turf/floors.dmi
  icons/turf/prison.dmi
  icons/turf/walls/snowwall.dmi
  tgmc.dme
Labels: Sprites, Config Update, Map Edit, Feature

#10967 Fixes a bug with the trauma kit sprite
  icons/obj/stack_objects.dmi
Labels: Sprites, Fix

#10954 looping_sounds maxloops fix
  code/datums/looping_sounds/_looping_sound.dm
Labels: Code Improvement

#10935 Removes randomized starting nutrition for Marines/SOM
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/sonsofmars.dm
Labels: Removal, Quality of Life

#10932 Adds More HUD-Goggles
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/meson.dm
  code/modules/clothing/glasses/night.dm
  code/modules/clothing/head/helmet.dm
  icons/mob/eyes.dmi
  icons/mob/modular/modular_helmet_storage.dmi
  icons/mob/species/robot/glasses.dmi
  icons/obj/clothing/glasses.dmi
Labels: Sprites, Feature

#10956 why does ths thing have opacity in the first place remove opacity from explosion
  code/game/objects/effects/effect_system/effects_explosion.dm
Labels: Removal

#10981 (Re) adds MP
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/skills.dm
  code/datums/gamemodes/extended.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/shipside.dm
  code/datums/skills.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/vehicles/multitile/tank.dm
  icons/UI_Icons/map_blips.dmi
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/uniforms.dmi
  tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
Labels: Sprites, Feature, UI

#10864 Make it so droids be used as supply beacon
  code/__DEFINES/dcs/signals.dm
  code/modules/vehicles/unmanned/unmanned_droid.dm
  icons/mob/actions.dmi
Labels: Sprites, Feature

#10974 Fixes the icon states for attachments
  code/datums/components/attachment_handler.dm
Labels: Fix

#10962 Anti-personnel landmines no longer trigger on dead mobs
  code/game/objects/items/explosives/mine.dm
Labels: Balance

#10936 Give the POS a fireaxe locker
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Feature

#10913 item storage tweaks
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
Labels: Balance

#10931 Reduces the flash range of rockets and RR rockets.
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#10958 Fix a bug that popped up on newer byond vers
  code/_onclick/hud/rendering/plane_master.dm
Labels: Fix

#10959 Space load optimisations
  code/__DEFINES/misc.dm
  code/game/turfs/space.dm
Labels: Code Improvement

#10968 Add pods to the list of notifications the AI get
  code/game/objects/structures/droppod.dm
Labels: Quality of Life

#10978 Enables special forces ERT
  tgmc.dme
Labels: Fix

#10964 Ais now user timer like ss
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/pathfinder.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
Labels: Code Improvement, Balance

#10983 Reverts the addition of SoM guns to seasonals
  code/controllers/subsystem/persistence.dm
Labels: Removal, Revert

#10834 Add an item which allows the AI to remote target for artillery pieces.
  code/__DEFINES/loadout.dm
  code/_onclick/ai.dm
  code/game/objects/items/misc.dm
  code/game/objects/machinery/mortar.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature

#10979 Akimbo bug fixes
  code/__DEFINES/dcs/signals.dm
  code/datums/components/autofire.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
Labels: Fix

#10987 Adds Gorger tab to Admin Player Panel
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
Labels: Administration

#10989 Adds Combat Robot to admin panel
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
Labels: Administration

#10955 Mech p2, greyscale mechs
  code/__DEFINES/mecha.dm
  code/__DEFINES/modular_armor.dm
  code/__HELPERS/mech.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/mech_arm.json
  code/datums/greyscale/json_configs/mech_head.json
  code/datums/greyscale/json_configs/mech_legs.json
  code/datums/greyscale/json_configs/mech_torso.json
  code/datums/greyscale/json_configs/mech_visor.json
  code/game/objects/items/power_cells.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/clothing/modular_armor/attachments/cape.dm
  code/modules/clothing/modular_armor/attachments/visors.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
  code/modules/vehicles/mecha/mecha_helpers.dm
  icons/mecha/mech_assault.dmi
  icons/mecha/mech_recon.dmi
  icons/mecha/mech_vanguard.dmi
  icons/obj/machines/computer.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/MechVendor.tsx
Labels: Sprites, UI

#11005 Fix ai not stopping when controlled by a player
  code/datums/components/ai.dm
Labels: Fix

#10997 Fix Set-Xeno-Buffs Logging
  code/modules/admin/admin_verbs.dm
Labels: Administration

#10980 Micronade fixes
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#11006 Fix letter overlay on medical items bug out in storage slots
  code/game/objects/items/storage/firstaid.dm
Labels: Fix

#10969 AI knows dropship points & nb of live marines
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Feature

#10993 Gelida balance changes
  _maps/map_files/gelida_iv/gelida_iv.dmm
  code/game/objects/structures/platforms.dm
  code/game/objects/structures/prop.dm
Labels: Balance, Fix, Map Edit

#10977 Add mounted gun rotation info
  code/game/objects/items/storage/boxes.dm
  code/modules/projectiles/gun_system.dm
Labels: Quality of Life

#10957 (Re?)adds move_force
  code/game/atoms_movable.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living.dm
  code/modules/shuttle/on_move.dm
  code/modules/vehicles/mecha/_mecha.dm
Labels: Code Improvement

#10891 tadpole swagger buff [MDB ignore]
  _maps/shuttles/minidropship.dmm
  _maps/shuttles/normandy.dmm
  code/game/objects/structures/dropship_equipment.dm
  code/game/turfs/closed.dm
  code/modules/shuttle/marine_dropship.dm
  icons/obj/structures/dropship_structures.dmi
  icons/turf/dropship2.dmi
Labels: Sprites, Balance, Map Edit, Feature, Test Merge Candidate

#10986 Resin door build time and plasma costs reduced
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance

#10990 buff the som shotgun
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance

#11000 Correct dropship ammo description
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#10992 V-51 sound update
  code/game/sound.dm
  code/modules/projectiles/guns/shotguns.dm
  sound/weapons/guns/fire/v51_1.ogg
  sound/weapons/guns/fire/v51_2.ogg
  sound/weapons/guns/fire/v51_3.ogg
  sound/weapons/guns/fire/v51_4.ogg
  sound/weapons/guns/fire/v51_empty.ogg
  sound/weapons/guns/interact/v51_load.ogg
Labels: Sound

#10999 Resprites nuke, ports a number of other legacy sprite replacements from CM.
  icons/mob/screen/generic.dmi
  icons/obj/assemblies/new_assemblies.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/items/books.dmi
  icons/obj/items/items.dmi
  icons/obj/items/weapons.dmi
  icons/obj/stationobjs.dmi
Labels: Sprites, Removal

#11008 Revert "buff the som shotgun"
  code/modules/projectiles/guns/shotguns.dm
Labels: Revert

#11017 Instruments in suit storage
  code/modules/clothing/modular_armor/modular.dm
  code/modules/instruments/items.dm
  icons/mob/instruments_back.dmi
Labels: Sprites, Feature

#11012 Autoburst akimbo fixes round 2
  code/datums/components/autofire.dm
  code/modules/projectiles/gun_system.dm
Labels: Balance, Fix

#11010 Fix some items map text overflowing on the right
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending.dm
Labels: Fix

#11016 CLF SL skills
  code/__DEFINES/skills.dm
  code/datums/jobs/job/clf.dm
  code/datums/skills.dm
Labels: Balance

#11019 you can build in tadpole again
  _maps/shuttles/minidropship.dmm
Labels: Fix, Map Edit

#11020 Shield rebalance
  code/game/objects/items/weapons/shields.dm
Labels: Balance

#11028 Carrier panic drop change
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Balance

#11021 Evolution towers now count for T3 and T2 xeno slot calculations
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Balance

#11026 Fix warrior punch exploit
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Fix

#11003 Projectile hit proc fixes
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
Labels: Refactor

#11027 fire stack proc fix and cleanup
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
Labels: Refactor, Fix

#10991 Fix MP suit icon
  code/modules/clothing/suits/marine_armor.dm
  tgmc.dme
Labels: Fix

#11042 Prevents xenos from buckling dead people to things
  code/game/buckling.dm
Labels: Balance

#11040 Grenade and bag mob sprites
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/reqs/supply.dm
  icons/Marine/sentry.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_0.dmi
  icons/mob/items_righthand_1.dmi
Labels: Sprites

#11029 Riot shield mob sprite improvements
  icons/mob/back.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/weapons.dmi
Labels: Sprites

#11002 Rewrites remote AI eye movement code , general FOB Drone QOL
  code/__DEFINES/construction.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/modules/mining/remote_fob/remote_fob_actions_misc.dm
  code/modules/mining/remote_fob/remote_fob_computer.dm
  code/modules/mining/remote_fob/remote_fob_fobdrone.dm
Labels: Code Improvement, Quality of Life

#11046 Medical item maptext fix: 5real edition
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/storage/firstaid.dm
  icons/misc/12x12.dmi
Labels: Sprites, Fix

#11041 Adds the Pheromone Tower (VSC edition)
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/UI_Icons/buyable_icons.dmi
  icons/Xeno/1x1building.dmi
Labels: Sprites, Feature

#11013 MP-19 akimbo tweak
  code/modules/projectiles/guns/smgs.dm
Labels: Balance

#10953 Hyperscale Guns
  code/__DEFINES/greyscale_guns.dm
  code/controllers/subsystem/greyscale.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/gun.json
  code/datums/greyscale/json_configs/gun_attachment.json
  code/datums/greyscale/json_configs/gun_held.json
  code/datums/greyscale/json_configs/gun_with_belt.json
  code/datums/greyscale/json_configs/gun_worn.json
  code/datums/loadout/item_representation/_item_representation.dm
  code/datums/loadout/item_representation/armor_representation.dm
  code/datums/loadout/item_representation/helmet_representation.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/belt.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  icons/Marine/gun_attachments_greyscale/t35_stock.dmi
  icons/Marine/gun_greyscale/t12/back.dmi
  icons/Marine/gun_greyscale/t12/left_hand.dmi
  icons/Marine/gun_greyscale/t12/right_hand.dmi
  icons/Marine/gun_greyscale/t12/suit.dmi
  icons/Marine/gun_greyscale/t12/t12.dmi
  icons/Marine/gun_greyscale/t14/left_hand.dmi
  icons/Marine/gun_greyscale/t14/right_hand.dmi
  icons/Marine/gun_greyscale/t14/t14.dmi
  icons/Marine/gun_greyscale/t18/back.dmi
  icons/Marine/gun_greyscale/t18/left_hand.dmi
  icons/Marine/gun_greyscale/t18/right_hand.dmi
  icons/Marine/gun_greyscale/t18/suit.dmi
  icons/Marine/gun_greyscale/t18/t18.dmi
  icons/Marine/gun_greyscale/t35/back.dmi
  icons/Marine/gun_greyscale/t35/left_hand.dmi
  icons/Marine/gun_greyscale/t35/right_hand.dmi
  icons/Marine/gun_greyscale/t35/suit.dmi
  icons/Marine/gun_greyscale/t35/t35.dmi
  icons/Marine/gun_greyscale/t42/back.dmi
  icons/Marine/gun_greyscale/t42/left_hand.dmi
  icons/Marine/gun_greyscale/t42/right_hand.dmi
  icons/Marine/gun_greyscale/t42/suit.dmi
  icons/Marine/gun_greyscale/t42/t42.dmi
  icons/Marine/gun_greyscale/t90/back.dmi
  icons/Marine/gun_greyscale/t90/left_hand.dmi
  icons/Marine/gun_greyscale/t90/right_hand.dmi
  icons/Marine/gun_greyscale/t90/suit.dmi
  icons/Marine/gun_greyscale/t90/t90.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/items_back_64.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_64.dmi
  icons/mob/items_suit_slot_64.dmi
  icons/obj/clothing/belts.dmi
  tgmc.dme
  tools/hyperscale_converter/converter.py
Labels: Sprites, Tools, Feature

#11064 Resprites nuke again, reverts vests
  icons/obj/clothing/ties.dmi
  icons/obj/stationobjs.dmi
Labels: Sprites, Removal, Revert

#11065 Changes oxycodone bottle capacity to 60u
  code/game/objects/items/reagent_containers/glass/bottle.dm
Labels: Quality of Life

#10988 Howie Shell cost increased
  code/modules/reqs/supplypacks.dm
Labels: Balance

#10998 Lets primordial hunters have stealth as well as disguise (again) but they cant be active at the same time
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Feature, Test Merge Candidate

#11081 Hyperscales 2 more guns and 2 more attachments
  code/__DEFINES/attachments.dm
  code/datums/components/attachment_handler.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/gun_attachment.json
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  icons/Marine/gun_attachments_greyscale/angled_grip.dmi
  icons/Marine/gun_attachments_greyscale/t35_stock.dmi
  icons/Marine/gun_attachments_greyscale/vertical_grip.dmi
  icons/Marine/gun_greyscale/t21/back.dmi
  icons/Marine/gun_greyscale/t21/left_hand.dmi
  icons/Marine/gun_greyscale/t21/right_hand.dmi
  icons/Marine/gun_greyscale/t21/suit.dmi
  icons/Marine/gun_greyscale/t21/t21.dmi
  icons/Marine/gun_greyscale/t29/back.dmi
  icons/Marine/gun_greyscale/t29/left_hand.dmi
  icons/Marine/gun_greyscale/t29/right_hand.dmi
  icons/Marine/gun_greyscale/t29/suit.dmi
  icons/Marine/gun_greyscale/t29/t29.dmi
  icons/mob/back.dmi
  icons/mob/suit_slot.dmi
Labels: Sprites, Feature

#11084 MPs rank and spawn in blurb changes.
  code/datums/jobs/job/shipside.dm
Labels: Grammar and Formatting

#11087 Makes engineering storage module fit filled sandbags
  code/modules/clothing/modular_armor/attachments/storage.dm
Labels: Balance

#11080 Refactors SSauras to be more consistant and to respect MC_CHECK_TICK
  code/controllers/subsystem/aura.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/living/carbon/human/life/handle_status_effects.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/living.dm
Labels: Fix, Test Merge Candidate

#11090 Mp holster in clothing vensor, smg25 holster in seasonal
  code/controllers/subsystem/persistence.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#11098 Flashbangs no longer spawn naturally
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/modularmaps/big_red/bigredsecornervar3.dmm
  _maps/modularmaps/big_red/bigredsecornervar6.dmm
  _maps/modularmaps/lv624/cargo_bay.dmm
  code/game/objects/machinery/vending/vending_types.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Removal, Map Edit

#11097 Cleans up some map spawned gear
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/objects/effects/spawners/random.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance, Map Edit

#11100 Flashbang sound fix
  code/game/objects/items/explosives/grenades/flashbang.dm
Labels: Fix

#11068 Change the snowstorm sprite
  icons/effects/weather_effects.dmi
Labels: Sprites

#11044 tadpole 3 tile cade all sides
  _maps/shuttles/minidropship.dmm
Labels: Balance, Map Edit, Test Merge Candidate
