Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2022-07, with the labels that each got.

#10546 Cryo fixes
  code/_onclick/ventcrawl.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/organs/organ_internal.dm
Labels: Balance/Rebalance, Fix

#10562 Defiler fix MKII
  code/__DEFINES/xeno.dm
Labels: Fix

#10560 Adds reagent grinders to Canterbury and Bigbury
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
Labels: Balance/Rebalance, Map Edit

#10553 Remove 15 req point autominer from req
  code/modules/reqs/supplypacks.dm
Labels: Removal

#10551 Adds code to enable preventing reagent container refills
  code/game/objects/items/reagent_containers/reagent_container.dm
  code/game/objects/machinery/vending/vending.dm
Labels: Code Improvement

#10443 Quick equip vendor - take 2
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
  _maps/shuttles/big_ert.dmm
  _maps/shuttles/distress.dmm
  _maps/shuttles/distress_pmc.dmm
  _maps/shuttles/distress_upp.dmm
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/clf.dm
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/imperium.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
  icons/Marine/marine-pouches.dmi
  icons/mob/back.dmi
  icons/obj/items/storage/storage.dmi
  tgmc.dme
  tgui/packages/tgui/assets/bg-som.svg
  tgui/packages/tgui/index.js
  tgui/packages/tgui/interfaces/Quickload/Types.tsx
  tgui/packages/tgui/interfaces/Quickload/index.tsx
  tgui/packages/tgui/styles/themes/som.scss
Labels: Sprites, Map Edit, Feature, UI

#10575 Kidneys catch microdoses, confuse fix
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/status_procs.dm
  code/modules/organs/organ_internal.dm
Labels: Fix

#10573 Compasses can get target coordinates
  code/game/objects/items/marine_gear.dm
Labels: Feature

#10583 Adds splint break sound
  code/modules/organs/limbs.dm
  sound/items/splint_break.ogg
Labels: Sound, Feature

#10571 Win fix
  code/datums/gamemodes/distress.dm
Labels: Balance/Rebalance

#10588 Fix some wraith portal issues
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#10585 Hunter stealth plasma fixes
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Fix

#10582 Scream on delimb
  code/modules/organs/limbs.dm
Labels: Feature

#10597 Fixes attachment overlays getting stuck on your mob
  code/datums/components/attachment_handler.dm
Labels: Fix

#10572 Combat shotgun akimbo tweak - again
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance/Rebalance

#10577 COPE sentry
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/sentries.dm
  icons/Marine/sentry.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Feature

#10593 Staggerstun bug fix and cleanup
  code/modules/projectiles/ammo_datums.dm
Labels: Refactor, Fix

#10598 Some gun mob sprite fixes
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
Labels: Sprites, Fix

#10596 You can no longer give orders to other factions
  code/modules/mob/living/carbon/human/life/handle_status_effects.dm
Labels: Fix

#10601 Volkite powerpack fix
  code/modules/projectiles/magazines/energy.dm
Labels: Fix, Feature

#10603 Splint break sound range limit
  code/modules/organs/limbs.dm
Labels: Fix

#10602 Add wraith time shift keybind
  code/datums/keybinding/xeno.dm
Labels: Quality of Life

#10594 C4 smoke reduction
  code/game/objects/items/explosives/plastique.dm
Labels: Balance/Rebalance

#10570 Orion Changes
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  code/game/objects/structures/prop.dm
  code/game/turfs/floor_ground.dm
Labels: Balance/Rebalance, Fix, Map Edit

#10549 Updates Hypospray belt and chem colours.
  code/datums/quick_load_outfits.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/reagents/reagents/medical.dm
Labels: Removal, Balance/Rebalance, Fix, Quality of Life

#10608 refactor of welding overlay code
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/machinery/doors/multi_tile.dm
Labels: Refactor

#10612 Allow multiple choice voting
  code/controllers/subsystem/vote.dm
  tgui/packages/tgui/interfaces/Vote.js
Labels: Feature, UI

#10619 Fix: Missing sprites for revolvers on the belt
  icons/obj/clothing/belts.dmi
Labels: Sprites

#10625 Remove untangle's 10 slowdown
  code/__DEFINES/objects.dm
  code/game/objects/structures/razorwire.dm
Labels: Balance

#10618 Fixes bino module desyncing
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Fix

#10620 Remove a unused part of jobspawning system
  code/_globalvars/lists/mapping.dm
  code/controllers/subsystem/job.dm
  code/datums/gamemodes/crash.dm
  code/game/objects/effects/landmarks/landmarks.dm
Labels: Code Improvement

#10624 Arrowhead Rebalance
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Removal, Balance

#10613 Removes the TerraGov Tech Vendor and Reorganizes Automated Weapons Vendors
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/machines/vending.dmi
Labels: Sprites, Removal, Balance/Rebalance, Stale, Map Edit, Quality of Life

#10614 Vending restock changes
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/vending.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/Vending.tsx
Labels: Fix, UI, Quality of Life

#10554 Fixes Arithrazine
  code/modules/reagents/reagents/medical.dm
Labels: Fix

#10633 New T2 Spitter sprites
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/spitter.dm
  icons/Xeno/2x2_Xenos.dmi
  icons/Xeno/48x48_Xenos.dmi
  icons/Xeno/wound_overlays.dmi
Labels: Sprites

#10644 Fix off-set of spitter sprites
  code/modules/mob/living/carbon/xenomorph/castes/spitter/spitter.dm
Labels: Fix

#10643 Fix vote fixing
  code/controllers/subsystem/vote.dm
Labels: Fix

#10642 SOM ERT update
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/under.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Feature

#10651 More volkite tweaks
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/magazines/energy.dm
Labels: Balance

#10647 Keybind for Move, Focus, Hold, Send, and Rally Order
  code/__DEFINES/dcs/signals.dm
  code/datums/actions/order_action.dm
  code/datums/keybinding/human.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/screen_alert/command_alert.dm
Labels: Quality of Life

#10650 Fix mid round gamemode vote bug
  code/controllers/subsystem/vote.dm
Labels: Fix

#10656 Fix plural gender not able to chose gear
  code/modules/client/preferences_ui.dm
Labels: Fix
