Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2022-01, with the labels that each got.

#9124 Big Red LZ 2 Fix
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Fix, Map Edit

#9113 PMC SG spawns with mag harness on T-29
  code/datums/jobs/job/pmc.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Quality of Life

#9114 Queen gets Neurotoxin sting
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Mechanic

#9071 New Sent Order Icon
  icons/mob/actions.dmi
Labels: Sprites

#9128 fixes blue fire stages sprite
  icons/effects/fire.dmi
Labels: Sprites, Fix

#9129 Carrier wound overlay fix
  icons/Xeno/wound_overlays.dmi
Labels: Sprites, Fix

#9056 Merry Christmas from Ocelot!
  code/modules/projectiles/guns/revolvers.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Sprites, Stale

#9049 Banishes old computer sprites to the shadow realm
  icons/obj/machines/computer.dmi
  icons/obj/machines/computer3.dmi
Labels: Sprites, Removal

#9127 removes Bracket colorizing extension(integrated on vsc)
  .vscode/extensions.json
Labels: Removal

#9134 Soft armor, including Jaegar storage and helmet modules, don't give 100 bio armor
  code/game/objects/objs.dm
  code/modules/clothing/modular_armor/attachments.dm
Labels: Fix

#9108 New Sprites for Surplus Vendors
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/machines/vending.dmi
Labels: Sprites, Sound, Quality of Life

#9110 T-25 has Point Blank
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance, Mechanic

#9064 New synthetic minimap_icon sprites
  icons/UI_Icons/map_blips.dmi
Labels: Sprites, Removal, Quality of Life

#9061 Valhallastation: Christmas Edition
  _maps/map_files/generic/Admin_Level.dmm
  code/__DEFINES/maps.dm
  code/game/area/valhallastation.dm
  code/game/objects/effects/decals/misc.dm
  code/game/objects/effects/decals/warning_stripes.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/kitchen/gibber.dm
  code/game/objects/machinery/kitchen/microwave.dm
  code/game/objects/machinery/kitchen/processor.dm
  code/game/objects/machinery/kitchen/smartfridge.dm
  code/game/objects/machinery/recharger.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/game/objects/structures/prop.dm
  code/game/objects/structures/signs.dm
  code/game/turfs/floor_types.dm
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/machinery/reagentgrinder.dm
  icons/Marine/mainship_props.dmi
  icons/Marine/mainship_props64.dmi
  icons/effects/landmarks_static.dmi
  icons/effects/warning_stripes.dmi
  icons/turf/floors.dmi
  sound/effects/supermatter.ogg
  tgmc.dme
Labels: Sprites, Sound, Map Edit, Mechanic, Content Expansion

#9116 Fix marine shoes sprite
  code/modules/clothing/shoes/marine_shoes.dm
  icons/mob/feet.dmi
Labels: Sprites, Fix

#9133 Catslug for research's pet
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/modules/mob/living/simple_animal/friendly/catslug.dm
  icons/mob/pets.dmi
  tgmc.dme
Labels: Sprites, Map Edit, Mechanic

#9158 Delete some hazard signs in Big Red
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Removal, Map Edit

#9154 Decrease reagent_transfer_amount in light of marines losing 200+ bio
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Test Merge Candidate

#9151 Common Supply Channel
  code/game/objects/items/radio/encryptionkey.dm
  code/game/objects/items/radio/headset.dm
Labels: Mechanic

#9153 T-25 now cannot take keymaster, mini flamethrower, and UGL
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#9111 SADAR spawns with miniscope
  code/modules/projectiles/guns/specialist.dm
Labels: Balance/Rebalance, Mechanic

#9006 Makes psychic link usable while moving
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/traits.dm
  code/datums/status_effects/xeno_buffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Balance/Rebalance, Fix, Test Merge Candidate

#9160 Queen announcement filter now checks for ascii
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Fix

#9161 Adds 19 more sentences for roomba to pick from & increases chance of it saying something to 10%
  code/game/objects/machinery/roomba.dm
Labels: Fix, Mechanic

#9067 Give king all abilities when young
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
Labels: Balance/Rebalance

#9141 Fix BaS Dupe
  code/datums/elements/deployable_item.dm
Labels: Fix

#9142 Resprites wall-mounted newscasters
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/modularmaps/lv624/internal_affairs.dmm
  icons/obj/terminals.dmi
Labels: Sprites, Map Edit

#9163 Overmind Sprites
  icons/Xeno/2x2_Xenos.dmi
  icons/Xeno/wound_overlays.dmi
Labels: Sprites

#9186 Cache Greyscale Palettes at Round Init
  code/controllers/subsystem/greyscale.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/clothing/modular_armor/attachments/badges.dm
  code/modules/clothing/modular_armor/attachments/visors.dm
  code/modules/clothing/modular_armor/modular.dm
Labels: Code Improvement

#9185 fixes mk221
  code/modules/projectiles/gun_system.dm
Labels: Fix

#9182 UGL fix
  code/modules/projectiles/guns/grenade_launchers.dm
Labels: Fix

#9048 Added Rocket Sledge
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/back.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/weapons.dmi
  sound/weapons/rocket_sledge.ogg
Labels: Sprites, Sound, Code Improvement, Mechanic

#9033 Ports fancy conveyor sprites from TG and CEV Eris
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/modules/recycling/conveyor2.dm
  icons/obj/recycling.dmi
Labels: Sprites, Map Edit

#9187 Fixes for auto spit
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix, Test Merge Candidate

#9167 Prevent stocking in vendors that are broken/unpowered
  code/game/objects/machinery/vending/vending.dm
Labels: Fix

#9175 Fix runtime with hive call
  code/_onclick/hud/screen_objects/screen_objects.dm
Labels: Fix

#9173 No more sound when a ghost open a storage
  code/game/objects/items/storage/storage.dm
Labels: Fix

#9152 Fix ugl being reloadable in storage
  code/modules/projectiles/gun_helpers.dm
Labels: Fix

#9183 Lasgun fixes
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#9156 Fix hivemind abilities being useable while unmanifested
  code/datums/actions/xeno_action.dm
Labels: Fix

#9094 Fix cocoon psy point output
  code/game/objects/items/cocoon.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Stale, Fix

#9157 Polishing up xenomorphs' roundend statistics
  code/datums/gamemodes/game_mode.dm
  code/datums/round_statistics.dm
Labels: Fix

#9180 Removes bumpattack from vali related tools
  code/game/objects/items/weapons/twohanded.dm
Labels: Removal, Balance/Rebalance

#9039 Pill bottles show how many pills they have in overlays
  code/game/objects/items.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/projectiles/gun_system.dm
Labels: Quality of Life

#9178 Protect ai nodes and pipe from tadpole crushing
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/__DEFINES/equipment.dm
  code/modules/ai/ai_node.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/shuttle/mini_dropship.dm
  code/modules/shuttle/on_move.dm
Labels: Fix, Map Edit

#9193 Change plasma_cost of Psychic Summon so that young King can use Psychic Summon
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Balance/Rebalance, Fix

#9150 Adds hypersleep consoles to POS
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#9166 Sentry radial mode balance
  code/__DEFINES/objects.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/sentries.dm
  tgui/packages/tgui/interfaces/Sentry.js
Labels: Balance/Rebalance, Test Merge Candidate, UI

#9194 copege added
  icons/misc/emoji.dmi
Labels: Sprites

#9169 Ghosts can no longer steal aghosted bodies
  code/__DEFINES/mobs.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/logout.dm
Labels: Fix

#9172 Prevent using the suicide vest when cloaked
  code/game/objects/items/explosives/bombvest.dm
Labels: Balance/Rebalance

#9171 Research outpost Crash silo fixes.
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
Labels: Balance/Rebalance, Map Edit

#9126 Sleeves
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/under.dm
  icons/mob/uniform_0.dmi
Labels: Sprites, Mechanic

#9038 Rebalance minions
  code/__DEFINES/monitor.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/xeno/xeno.dm
  code/modules/ai/ai_behaviors/xeno/zombie.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/abilities_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/mantis/abilities_mantis.dm
  code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
  code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#9200 Plasma pistol buff
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/pistols.dm
Labels: Balance/Rebalance, Quality of Life

#9201 Miniflamer nerf.
  code/modules/projectiles/guns/flamer.dm
Labels: Balance/Rebalance, Fix

#9214 New Jaeger set: Helljumper
  code/__DEFINES/loadout.dm
  code/datums/greyscale/greyscale_configs.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/clothing/modular_armor/attachments/arm_plates.dm
  code/modules/clothing/modular_armor/attachments/chestplates.dm
  code/modules/clothing/modular_armor/attachments/leg_plates.dm
  code/modules/clothing/modular_armor/attachments/visors.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/helljumper.dmi
Labels: Sprites

#9202 New Jaeger Colors
  code/__DEFINES/modular_armor.dm
  code/controllers/subsystem/greyscale.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/clothing/modular_armor/modular.dm
Labels: Mechanic

#9217 Scorpions can spit again
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#9184 Sprite fixes
  code/datums/jobs/job/imperium.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/specialist.dm
  icons/mob/back.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Sprites, Fix

#8742 Diagonal move refactor electric boogaloo
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/movement.dm
  code/game/atoms_movable.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/pipe/construction.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/game/turfs/turf.dm
  code/modules/admin/smites/puzzle.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/vehicles/_vehicle.dm
  code/modules/vehicles/motorbike.dm
Labels: Balance/Rebalance, Refactor, RED LABEL

#8967 Rebalance savage
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Balance/Rebalance, Test Merge Candidate, RED LABEL

#9168 Remove vendor malfunction
  code/game/objects/items/portable_vendor.dm
  code/game/objects/machinery/vending/vending.dm
Labels: Removal

#9197 Give queen command minions
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Balance/Rebalance

#9199 Charge and similar xeno abilities will no longer be used by ai xenos when they can't see the target
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Fix

#9204 Acid splatter no longer damage dead marines
  code/game/objects/effects/aliens.dm
Labels: Fix

#9205 Xeno can evolve while resting again
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#9219 Miniflamer Fix
  code/__DEFINES/dcs/signals.dm
  code/datums/components/attachment_handler.dm
  code/datums/loadout/item_representation/gun_representation.dm
Labels: Fix

#9225 Fix lasgun and railgun cycling issue
  code/__DEFINES/conflict.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#9226 Allow lasgun to tactictal reload and prevent tactical reload exploit
  code/modules/projectiles/gun_helpers.dm
Labels: Fix, Quality of Life

#9218 OOC Color rights fix
  code/game/verbs/ooc.dm
  code/modules/admin/holder.dm
  code/modules/admin/preferences_verbs.dm
Labels: Administration

#9229 Fixes harvester Bicardine attack
  code/datums/components/harvester.dm
Labels: Fix

#9257 RO, AI, and CIC get req channel back again
  code/game/objects/items/radio/encryptionkey.dm
Labels: Fix

#9240 Xeno health hud buff 2.0
  code/game/data_huds.dm
Labels: Balance/Rebalance

#9131 Soldering iron for Squad Engineer
  code/__DEFINES/loadout.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/tools/soldering_tool.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  tgmc.dme
Labels: Mechanic

#9243 Gun attachment are activated by default when you attach them
  code/modules/projectiles/gun_attachables.dm
Labels: Quality of Life

#9224 Prevent ais from nocliping through shutters
  code/modules/ai/ai_behaviors/xeno/xeno.dm
Labels: Fix

#9221 Researcher Minimap 2.0
  code/datums/jobs/job/shipside.dm
  icons/UI_Icons/map_blips.dmi
Labels: Sprites, Mechanic

#9253 Nerfs A19 Impact Ammo 2.0
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#9245 Rocket hammer balance pass (nerf)
  code/game/objects/items/weapons/twohanded.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#9267 Removes M40-T box from reqs vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal, Balance/Rebalance

#9270 Reduces screenshake from explosions
  code/controllers/subsystem/explosions.dm
Labels: Balance/Rebalance

#9268 Increases cost of Tanglefoot CAS rockets
  code/game/objects/structures/dropship_ammo.dm
Labels: Removal, Balance/Rebalance

#9269 Removes all instances of screenshake on projectiles
  code/modules/projectiles/ammo_datums.dm
Labels: Removal

#9273 fixes autofire getting scatter debuff from burst
  code/modules/projectiles/gun_system.dm
Labels: Fix

#9101 New dress and service uniform!
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/head_0.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#9208 Up the maximum recommend version
  code/_compile_options.dm
Labels: Stale

#9282 Makes window frames slashable
  code/game/objects/structures/window_frame.dm
Labels: Balance/Rebalance

#9179 Neurotoxin rebalance, new chemical Ozemolyn, purges chemical and does minor toxin damage to capped amount.
  code/__DEFINES/conflict.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/xeno.dm
  code/datums/keybinding/xeno.dm
  code/datums/round_statistics.dm
  code/game/data_huds.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/reagents/reagents/toxin.dm
  icons/mob/actions.dmi
  icons/mob/hud.dmi
Labels: Sprites, Balance/Rebalance, Mechanic

#9275 Wall Nanomed Contraband Removal
  code/game/objects/machinery/vending/vending_types.dm
Labels: Removal

#9287 Factory pamphlet spelling errors
  code/modules/factory/howtopaper.dm
Labels: Fix

#9251 add milk in soda dispenser
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Quality of Life, Mechanic

#9250 Colorable Flak Jacket!
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/suits/armor.dm
  icons/mob/modular/modular_armor.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Sprites, Mechanic

#9195 Add support for piercing projectiles
  code/__DEFINES/conflict.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance, Test Merge Candidate

#9288 Fix: port SStimer fixes
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/timer.dm
Labels: Config Update, Fix

#9302 Icy caves v2.0
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Balance/Rebalance, Map Edit, Mechanic

#9298 Revert Minion Spawn Rate Nerf
  code/__DEFINES/monitor.dm
Labels: Balance/Rebalance, Revert

#9276 Cowboy leather jacket suit slot fix
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/suits/marine_armor.dm
Labels: Fix, Map Edit

#9300 remove Sentry gun voucher
  code/__DEFINES/loadout.dm
  code/modules/mining/remote_fob/remote_fob_actions_misc.dm
  code/modules/mining/remote_fob/remote_fob_computer.dm
Labels: Removal

#9310 Autolathe Contraband Removal
  code/game/objects/machinery/autolathe_datums.dm
Labels: Removal

#9305 now we can see angry tanya in title screen
  code/game/turfs/walls/wall_types.dm
Labels: Fix

#9304 Overlay on Suit Toggle Button when Turning On and Off Suit light
  code/datums/actions/item_action.dm
  code/modules/clothing/modular_armor/modular.dm
Labels: Quality of Life, Mechanic

#9292 New Shotgun Seasonal
  code/controllers/subsystem/persistence.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal, Mechanic

#9278 TX-11 and T-18 no longer have extra delay on burst fire.
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#9244 You can tactical reload gun attachments
  code/modules/projectiles/gun_helpers.dm
Labels: Quality of Life

#9294 Grenade boxes don't chain grenade
  code/game/objects/items/storage/boxes.dm
Labels: Balance/Rebalance

#9264 Minerva Hangar Retrofit
  _maps/map_files/Minerva/TGS_Minerva.dmm
Labels: Fix, Map Edit, Test Merge Candidate

#9277 Fix: sanitize and fix SQL requests
  code/controllers/subsystem/blackbox.dm
  code/controllers/subsystem/dbcore.dm
  code/modules/admin/panels/note_panel.dm
Labels: Fix

#9299 Reqtorio cost balance
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#9331 Fixes quick equip exploit for the revolver toss trick
  code/modules/projectiles/guns/revolvers.dm
Labels: Fix

#9315 new ammo hub for energy weapons
  icons/mob/ammoHUD.dmi
Labels: Sprites

#9324 Combat Robot Insulation
  code/__DEFINES/mobs.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items/shards.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance/Rebalance

#9320 All unmanned vehicles can now be fixed with a welder
  code/modules/vehicles/unmanned/unmanned_droid.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Fix

#9321 Sentry kit box can only hold ammo and sentries
  code/modules/projectiles/guns/sentries.dm
Labels: Fix

#9342 Resin walls take more explosion damage, and die instantly to heavy explosions.
  code/game/turfs/walls/resin.dm
Labels: Balance/Rebalance

#9115 Ghosts can assume control of minions
  code/__DEFINES/mobs.dm
  code/__DEFINES/mode.dm
  code/__DEFINES/xeno.dm
  code/__HELPERS/game.dm
  code/_globalvars/misc.dm
  code/controllers/subsystem/monitor.dm
  code/datums/actions/observer_action.dm
  code/datums/components/ai.dm
  code/datums/emergency_calls/emergency_call.dm
  code/game/objects/machinery/cryopod.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/xeno/xeno.dm
  code/modules/ai/ai_behaviors/xeno/xeno_illusion.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/shuttle/shuttle.dm
  icons/UI_Icons/buyable_icons.dmi
  icons/mob/actions.dmi
Labels: Sprites, Test Merge Candidate, Mechanic

#9144 TE-X X-Ray Laser Rifle
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
Labels: Sprites, Mechanic

#9170 Cryoing no longer delete the marine
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/_globalvars/lists/objects.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/roomba.dm
  code/modules/shuttle/escape_pod.dm
Labels: Balance/Rebalance, Map Edit

#9326 Defiler Hemodile and Transvitox gas is no longer transparent.
  code/game/objects/effects/effect_system/smoke.dm
Labels: Balance/Rebalance

#9337 Fix: Avoid timer scheduling too far events into short queue
  code/controllers/subsystem/timer.dm
Labels: Fix

#9323 T-27 ammo box
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes.dm
  icons/obj/items/storage/storage_boxes.dmi
Labels: Sprites, Balance/Rebalance, Mechanic

#9327 Increases the cost of the IFF sniper
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#9339 hazard signs to help FOB engineers
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Map Edit, Mechanic

#9338 Give free conveyor belts in shipside maps due to free reqtorio
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit, Mechanic

#9255 Sulaco Medbay's Break room
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Balance/Rebalance, Stale, Map Edit, Mechanic

#9340 give 4 roller beds in Theseus
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit, Mechanic

#9343 revolver changes- non akimbo firerate buff, and knockback readded
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/revolvers.dm
Labels: Balance/Rebalance

#9347 Combat Robots no longer have organs
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/scanners.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#9370 Fixes Chigusa's lack of excavation sites
  _maps/map_files/desertdam/desertdam.dmm
Labels: Fix, Map Edit

#9362 Adds a confirmation to hijacking the alamo, adds a line when you lock the alamo as xeno by clicking the console
  code/modules/shuttle/marine_dropship.dm
Labels: Mechanic

#9329 New Synthetic vendor sprites!
  code/game/objects/machinery/vending/new_marine_vendors.dm
  icons/obj/machines/vending.dmi
Labels: Sprites

#9363 Fix plasma pistol ammoHUD
  code/modules/projectiles/ammo_datums.dm
  icons/mob/ammoHUD.dmi
Labels: Sprites, Fix, Mechanic

#9233 Fix one crash runtime + add logging to jobs and larva
  code/controllers/subsystem/monitor.dm
  code/datums/jobs/job/job.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Code Improvement

#9371 Add valhalla specific ban
  code/__DEFINES/jobs.dm
  code/modules/admin/panels/ban_panel.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Mechanic

#9358 Remove right click setting action
  code/datums/actions/rightclick_toggle.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/logout.dm
  tgmc.dme
Labels: Removal

#9333 Fix some move issues
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
Labels: Fix

#9379 makes rebreathers/bandanas block gas attacks
  code/modules/clothing/masks/breath.dm
Labels: Mechanic

#9328 Miner Upgrades in Operational Supply And Supply Order, Not Autolathe
  code/game/objects/machinery/autolathe_datums.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
Labels: Removal, Quality of Life, Mechanic

#9322 Adds population dependent modular map support
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/persistence.dm
  code/modules/mapping/modular_mapping.dm
Labels: Code Improvement

#9400 Repeater Attempt Take #3
  icons/mob/items_lefthand_1.dmi
Labels: Sprites, Fix

#9295 Carrier primo
  code/__DEFINES/objects.dm
  code/__DEFINES/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/Xeno/acidturret.dmi
  icons/Xeno/resinpod.dmi
  icons/mob/actions.dmi
  icons/obj/items/projectiles.dmi
Labels: Sprites

#9262 Fix buckled bag not moving with roller bed
  code/game/atoms_movable.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix

#9203 Xenos can force marine to go out from cryo, sleeper, autodoc
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/sleeper.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/shuttle/cas_plane.dm
  tgmc.dme
Labels: Balance/Rebalance

#9031 Praetorian primordial
  code/__DEFINES/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Test Merge Candidate, RED LABEL

#9396 Fixes rail scopes zooming in when detached
  code/modules/projectiles/gun_attachables.dm
Labels: Fix

#9397 Fix laser pistol having automatic fire mode
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#9390 Adjust combat robot armor values
  code/modules/clothing/suits/marine_armor.dm
Labels: Fix

#9373 Fix zombie players resurecting in xeno faction
  code/modules/mob/living/living_health_procs.dm
Labels: Fix

#9393 Fixes some small issues with Theseus CL office
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Fix, Map Edit

#9392 Thrown items respect mob armor
  code/game/objects/items/weapons/blades.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
Labels: Code Improvement
