Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2022-08, with the labels that each got.

#10567 Dead marines do not reduce number of xenos for crash
  code/datums/gamemodes/crash.dm
Labels: Balance/Rebalance, Stale

#10654 Squish shitcode and a future bug
  code/modules/projectiles/projectile.dm
Labels: Fix

#10648 Give attack, defend, and retreat order to FC, SL, and aSL (also CO, SO, CSE, RO, and CMO)
  code/datums/actions/order_action.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Feature, Balance

#10660 Combat Patrol - Bioscan and pop balance tweaks
  code/__DEFINES/mode.dm
  code/datums/gamemodes/combat_patrol.dm
Labels: Balance

#10634 Adds normal smoke grenades
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature, Test Merge Candidate

#10662 Turns lengthy else-if chain in /mob/dead/observer/Topic(href, href_list) into a switch
  code/modules/mob/dead/observer/observer.dm
Labels: Code Improvement

#10679 Fix large object transparency opacity issue
  code/datums/components/largeobjecttransparency.dm
Labels: Fix

#10678 Fix motion detector shutting down impromptly
  code/game/objects/items/motion_detector.dm
Labels: Fix

#10675 Fix ai controlling doors groundside
  code/game/objects/machinery/doors/airlock_types.dm
Labels: Fix

#10681 Set Xeno buffs admin verb is now in percentage
  code/modules/admin/admin_verbs.dm
Labels: Fix

#10687 Fix direction on pipe changing when tadpole is landing
  code/modules/shuttle/on_move.dm
Labels: Fix

#10692 Fix inconsistent hugger activation on hit
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Fix

#10699 Fix being able to vent out in dense object
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/projectiles/gun_helpers.dm
Labels: Fix

#10701 Fixes nonfunctional CAS doors on Minerva
  _maps/map_files/Minerva/TGS_Minerva.dmm
Labels: Map Edit

#10704 Prevent from spamming launch in tadpole
  code/modules/shuttle/mini_dropship.dm
Labels: Fix

#10709 Fix corpse spawner being counted in statistic
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/modules/mob/living/carbon/human/death.dm
Labels: Fix

#10696 Fix fob drone placing cade diagonally
  code/__HELPERS/unsorted.dm
  code/modules/mining/remote_fob/remote_fob_fobdrone.dm
Labels: Fix

#10691 Should fix burst breaking gun due to lag
  code/datums/components/autofire.dm
Labels: Fix

#10683 Add random name for synth
  code/datums/namepool.dm
  strings/names/female_synth.tx
  strings/names/male_synth.txt
Labels: Fix

#10677 Fix wraith unable to time shift self again after entering and existing crit whilst under the effect of time shift
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#10680 Add location check for building silos and such
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Balance

#10706 Drop pod ejects marine if the marine dies
  code/game/objects/structures/droppod.dm
Labels: Quality of Life

#10705 Fix alamo being stuck shipside if you touched the console too late
  code/modules/shuttle/marine_dropship.dm
Labels: Fix

#10698 Fix stagger not being applied with deployed gun
  code/modules/projectiles/projectile.dm
Labels: Fix

#10690 Cannot deploy via alt click menu
  code/datums/elements/deployable_item.dm
Labels: Fix

#10682 Prevent corpse lunging
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Fix

#10665 Add auto climbing
  code/game/objects/structures.dm
Labels: Quality of Life

#10558 Vendors improve
  code/__DEFINES/jobs.dm
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/marines.dm
  code/datums/loadout/loadout_helper.dm
  code/datums/loadout/loadout_seller.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/game/objects/machinery/vending/vending_types.dm
  tgui/packages/tgui/interfaces/MarineSelector.js
Labels: Removal, Code Improvement, Balance/Rebalance, Stale, Feature, Test Merge Candidate, UI

#10695 Fix disguised hunter still having wound overlay
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Fix

#10684 Fix synth's getting human limbs after aheal
  code/modules/organs/limbs.dm
Labels: Fix

#10629 Remove permutated from projectile code
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/projectiles/projectile.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Code Improvement

#10707 Fix spawned shotgun not able to shoot
  code/modules/projectiles/gun_system.dm
Labels: Fix

#10595 Converts auras to a subsystem
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/xeno.dm
  code/controllers/subsystem/aura.dm
  code/game/data_huds.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life/handle_status_effects.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  tgmc.dme
Labels: Refactor, Test Merge Candidate

#10655 Combat Patrol QOL and adjust respawn timer
  code/datums/gamemodes/combat_patrol.dm
  code/datums/gamemodes/game_mode.dm
  code/game/objects/structures/patrol_points.dm
  code/modules/mob/dead/observer/observer.dm
  icons/Marine/mainship_props.dmi
  icons/effects/effects.dmi
  sound/effects/rappel.ogg
  sound/effects/tadpolehovering.ogg
Labels: Sprites, Sound, Feature, Quality of Life, Balance

#10721 More egg cleanup
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/egg.dm
Labels: Fix

#10710 Fixes the (garbage) lever action gun
  code/modules/projectiles/guns/shotguns.dm
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
Labels: Sprites, Fix

#10715 Fix climbing
  code/game/objects/structures.dm
Labels: Fix

#10702 Fix bonus projectile not having IFF
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#10673 Fix tadpole able to crush shutters
  code/game/objects/machinery/doors/poddoor.dm
Labels: Fix

#10664 Add overlay short description on hypospray and pill bottles
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/storage/firstaid.dm
Labels: Feature

#10674 Fix being able to shoot in a tarp
  code/modules/projectiles/gun_system.dm
Labels: Fix

#10676 Fix sadar turret not shooting
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/sentries.dm
Labels: Fix

#10671 Attachment icon no longer update every icon change
  code/datums/components/attachment_handler.dm
Labels: Code Improvement

#10645 Lemoline Crate Buff
  code/modules/reqs/supplypacks.dm
Labels: Balance

#10672 End of round stat update
  code/datums/gamemodes/combat_patrol.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/jobs/job/job.dm
  code/datums/round_statistics.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items/defibrillator.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/projectile.dm
Labels: Code Improvement, Feature

#10725 Increasing sunder recovery during Gorger drain ability
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
Labels: Balance

#10730 Fix getting out of the Condor in Reserved Z
  code/modules/shuttle/cas_plane.dm
Labels: Fix

#10734 No hair no longer has TWO brackets on early synth.
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#10731 Fix wave respawns for combat patrol
  code/datums/gamemodes/combat_patrol.dm
Labels: Fix

#10726 Vali Tweaks
  code/datums/components/chem_booster.dm
Labels: Removal, Fix, Grammar and Formatting

#10728 Kuro Gun Resprite pt1
  code/game/objects/items/weapons/twohanded.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_back_64.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/items_righthand_64.dmi
  icons/mob/items_suit_slot_64.dmi
  icons/mob/suit_slot.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  icons/obj/items/items_mini.dmi
Labels: Sprites, Removal, Code Improvement

#10743 Fix ghost bullets
  code/modules/projectiles/projectile.dm
Labels: Fix

#10738 Synthetics can have hair again
  code/modules/mob/living/carbon/human/species.dm
Labels: Feature

#10732 Self Harm Toggle
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/mob.dm
  code/game/objects/items/weapons/weapon.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/mob_defines.dm
Labels: Feature

#10686 Fix wrong flag on shouldermount, causing gun to cycle too much
  code/modules/projectiles/gun_attachables.dm
Labels: Fix

#10749 Revert "Turns lengthy else-if chain in /mob/dead/observer/Topic(href, href_list) into a switch"
  code/modules/mob/dead/observer/observer.dm
Labels: Revert

#10747 Aura cleanup
  code/controllers/subsystem/aura.dm
  code/game/data_huds.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
Labels: Code Improvement

#10753 Guns part1 redux
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/items_mini.dmi
Labels: Sprites

#10751 Wide screen on local
  config/config.txt
Labels: Config Update

#10708 Fix xeno fire overlay not changing dir when the xeno is turning
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#10689 Improve do_surgery code
  code/__DEFINES/mobs.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/surgery.dm
Labels: Fix

#10757 End of round stat fix for Combat Patrol
  code/datums/gamemodes/combat_patrol.dm
Labels: Fix

#10760 Combat Patrol loadout updates
  code/datums/quick_load_outfits.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Feature, Balance

#10766 Stop pheromones on death
  code/modules/mob/living/carbon/xenomorph/death.dm
Labels: Fix

#10769 Assemblies now pulse wires they're attached to again
  code/datums/wires/_wires.dm
Labels: Fix, Balance

#10770 Updates Pillar of Spring map to fix some issues with misplaced or missing cameras, firelocks, lights & APC's.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#10767 Fixes detpacks
  code/game/objects/items/radio/detpack.dm
Labels: Fix

#10774 SOM ballistic tweaks
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  icons/Marine/marine-weapons.dmi
Labels: Sprites, Balance

#10756 Motorbikes will not act as free armor
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/motorbike.dm
Labels: Fix, Balance

#10768 CIC markers now work as they used to (fix)
  code/datums/actions/order_action.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#10772 Add CAS radio key to the tactical binocs crate.
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#10778 SOM shoe fix
  code/modules/clothing/shoes/marine_shoes.dm
Labels: Fix

#10763 Other surgery fixes
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/organs/limbs.dm
  code/modules/organs/organ_internal.dm
  code/modules/surgery/amputation.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/brainrepair.dm
  code/modules/surgery/encased.dm
  code/modules/surgery/face.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/headreattach.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/internal_bleeding.dm
  code/modules/surgery/necrosis.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/robolimbs.dm
  code/modules/surgery/surgery.dm
Labels: Fix, Test Merge Candidate, Cookie

#10785 Clarifies description on Hunter's disguise
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Feature

#10789 Surgery single limb selection
  code/modules/surgery/surgery.dm
Labels: Fix

#10779 Correct bit of wrong text with supply drop console
  code/game/objects/machinery/squad_supply/supply_console.dm
Labels: Fix

#10776 Shield hard armor works, bullet pen applies
  code/datums/components/shield.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/projectile.dm
Labels: Fix, Feature

#10790 Teleporter kit's description tells you how to remove the power cell
  code/game/objects/structures/teleporter.dm
Labels: Fix

#10797 remove r windows in prep to free roomba
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Removal, Map Edit

#10792 Add yet another set of railing to the ASRS Elevator to prevent crate spacing
  _maps/shuttles/supply.dmm
Labels: Map Edit, Feature

#10646 Combat Patrol Base Remap and Fluff
  _maps/map_files/combat_patrol_base/combat_patrol_base.dmm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/machinery/cic_maptable.dm
  code/game/objects/structures/landing_signs.dm
  code/game/objects/structures/platforms.dm
  code/game/objects/structures/prop.dm
  code/game/objects/structures/som_cas_parts.dm
  code/game/objects/structures/window.dm
  code/game/turfs/floor_types.dm
  icons/Marine/mainship_props.dmi
  icons/Marine/mech_prop.dmi
  icons/Marine/somshipprop.dmi
  icons/obj/landing_signs.dmi
  icons/obj/objects.dmi
  icons/obj/structures/platforms.dmi
  icons/turf/mainship.dmi
  sound/effects/radio_chatter/radio1.ogg
  sound/effects/radio_chatter/radio2.ogg
  sound/effects/radio_chatter/radio3.ogg
  sound/effects/radio_chatter/radio4.ogg
  sound/effects/radio_chatter/radio5.ogg
  sound/effects/radio_chatter/radio6.ogg
  sound/effects/radio_chatter/radio7.ogg
  sound/effects/radio_chatter/radio8.ogg
  tgmc.dme
Labels: Sprites, Sound, Map Edit, Feature, Test Merge Candidate

#10782 Yet more Combat patrol loadouts
  code/datums/quick_load_outfits.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
  icons/Marine/marine-weapons.dmi
Labels: Sprites, Feature

#10773 Add mortar & howitzer shots to end game stats
  code/datums/gamemodes/game_mode.dm
  code/datums/round_statistics.dm
  code/game/objects/machinery/mortar.dm
Labels: Feature

#10801 Combat patrol: Loadout description improvements
  code/datums/quick_load_outfits.dm
Labels: Quality of Life

#10798 Mob sprites for wearing floppa on head
  code/modules/mob/living/simple_animal/friendly/cat.dm
  icons/mob/head_0.dmi
Labels: Sprites

#10750 Projectile performance improvement
  code/__DEFINES/obj_flags.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/elements/riding.dm
  code/game/atoms.dm
  code/game/objects/effects/effect.dm
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/projectile.dm
Labels: Code Improvement, Test Merge Candidate

#10794 Shield integrity fixes and tweaks
  code/game/objects/items/weapons/shields.dm
Labels: Fix, Grammar and Formatting, Balance

#10813 Revert "Add auto climbing"
  code/game/objects/structures.dm
Labels: Revert

#10809 Lighting and bugfix
  code/controllers/subsystem/modularmapping.dm
  code/datums/gamemodes/combat_patrol.dm
Labels: Balance

#10817 Fix SO belts being double loaded
  code/game/objects/items/storage/belt.dm
Labels: Fix

#10812 Keybinds for Attack, Defend, and Retreat orders
  code/__DEFINES/dcs/signals.dm
  code/datums/actions/order_action.dm
  code/datums/keybinding/human.dm
Labels: Feature, Quality of Life

#10808 Fix Combat Patrol groundmap votes
  code/controllers/subsystem/vote.dm
Labels: Fix

#10815 Fix some guns spawning with a missing round
  code/modules/projectiles/gun_system.dm
Labels: Fix

#10821 More sulaco fixes & patches.
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#10816 VA-61 fix
  code/modules/projectiles/guns/shotguns.dm
Labels: Fix

#10814 Combat Patrol sound tweaks
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/structures/patrol_points.dm
Labels: Quality of Life

#10819 Fix some more markings, lights, cameras and areas on POS
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#10827 Fixes unremovable attachments
  code/datums/components/attachment_handler.dm
Labels: Fix

#10822 Slightly reduce vox cooldown for the AI
  code/modules/mob/living/silicon/ai/say.dm
Labels: Balance

#10820 Give the AI a recap of vox messages
  code/modules/mob/living/silicon/ai/say.dm
Labels: Quality of Life

#10835 Remove an useless argument in a mortar/binocs proc
  code/game/objects/items/binoculars.dm
  code/game/objects/machinery/mortar.dm
Labels: Code Improvement

#10810 SOM seasonals
  code/controllers/subsystem/persistence.dm
Labels: Feature

#10832 Various minerva fixes
  _maps/map_files/Minerva/TGS_Minerva.dmm
Labels: Fix, Map Edit

#10837 Adds a tool for converting greyscale sprites into hyperscale sprites.
  .gitignore
  tools/hyperscale_converter/ReadMe.txt
  tools/hyperscale_converter/converter.py
Labels: Tools

#10836 Fixes deployed gun layer
  code/modules/projectiles/mounted.dm
  code/modules/projectiles/sentries.dm
Labels: Fix

#10842 Fix projectiles being able to bypass fog
  code/game/objects/effects/misc.dm
Labels: Fix

#10838 Fixes the stagger immunity trait
  code/modules/mob/living/status_procs.dm
Labels: Fix

#10841 Vote fix: For real edition
  code/controllers/subsystem/vote.dm
Labels: Fix

#10840 Mass spectrometer/reagent scanner cleanup
  code/game/objects/items/scanners.dm
Labels: Code Improvement

#10800 Hunter Swap control simplification
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Test Merge Candidate, Quality of Life

#10846 SOM squad preferences actually work
  code/datums/jobs/squads.dm
Labels: Fix

#10788 SOM boots actually fixed edition
  icons/mob/feet.dmi
Labels: Sprites, Fix

#10829 MPI_KM mob sprite fixes
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
Labels: Sprites

#10831 Command Orders Bugfix and Minimap
  code/datums/actions/order_action.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/ai/ai.dm
  icons/Marine/marine-items.dmi
  icons/UI_Icons/map_blips.dmi
Labels: Sprites, Fix, Quality of Life

#10845 It just works - fixes non-binary and object robots not being able to scream or warcry
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#10833 Allows the AI to grab coordinates with ctrl click
  code/_onclick/ai.dm
Labels: Feature

#10823 Leg breaks adjustment
  code/modules/mob/living/carbon/human/life/handle_organs.dm
Labels: Balance

#10852 Two Handing added to SH39
  code/modules/projectiles/guns/shotguns.dm
Labels: Feature

#10855 Combat Patrol: The loadouts just keep coming
  code/datums/quick_load_outfits.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Feature, Quality of Life, Balance

#10859 Hands are harder to hit
  code/modules/mob/mob_helpers.dm
Labels: Balance

#10862 Accuracy system tweaks
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
Labels: Code Improvement

#10863 Makes most signs have directional arrows for mapper convenience
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  code/game/objects/structures/signs.dm
  icons/obj/decals_arrow.dmi
  icons/obj/safety_signs_arrow.dmi
Labels: Sprites, Fix, Map Edit, Quality of Life

#10830 New RR shell for Combat Patrol
  code/datums/quick_load_outfits.dm
  code/game/objects/items/storage/holsters.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
Labels: Balance
