Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2022-06, with the labels that each got.

#10294 Larvae get two evo points per tick if on weed, again
  code/modules/mob/living/carbon/xenomorph/castes/larva/larva.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance/Rebalance

#10259 Underbarrel weapon rebalance
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Balance/Rebalance

#10331 Operating tables apply a trait instead of using internals
  code/game/objects/machinery/OpTable.dm
Labels: Code Improvement

#10361 Revert "Laser sniper changes (IFF mode)"
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
Labels: Balance/Rebalance, Revert

#10357 Nerfs SG minigun sunder
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#10351 Allow many non-combat essential objects to be slashed at all or faster by xenos
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/mining/satchel_ore_boxdm.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/vehicles/train.dm
Labels: Balance/Rebalance, Fix

#10353 Clothing Vendor Change: Bandanna Edition
  code/_globalvars/lists/objects.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/client/preferences_gear.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/misc.dm
  icons/mob/head_0.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites, Removal, Feature

#10380 Adds explanatory comments to ammo flags
  code/__DEFINES/conflict.dm
Labels: Code Improvement

#10363 Attachments reorder
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Quality of Life

#10371 Add missing accurate min range and sniper flag to laser sniper ammo
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#10313 Mobs no longer breathe
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/game/atoms_movable.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/mob/living/carbon/human/life/handle_breath.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  tgmc.dme
Labels: Code Improvement, Test Merge Candidate

#10287 Ice Colony Changes: Nuclear War Edition
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Balance/Rebalance, Map Edit, Test Merge Candidate

#10377 Nerfs smartgunner minigun ammo count and magazine boxes
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/specialist.dm
Labels: Balance/Rebalance

#10356 Disables SADAR from firing until wielded
  code/modules/projectiles/guns/specialist.dm
Labels: Balance/Rebalance

#10378 Makes undeployed teleporters meltable
  code/game/objects/structures/teleporter.dm
Labels: Fix

#10376 Injector Jaeger Module
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites, Feature

#10388 Mob health updates on suturing
  code/modules/surgery/generic.dm
Labels: Fix

#10383 Fixes self-examine kit messages
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Fix

#10387 lets researchers unlock GROUNDSIDE apcs
  code/datums/jobs/job/shipside.dm
Labels: Balance/Rebalance

#10392 The importance of hydration
  code/game/objects/items/reagent_containers/food/drinks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  icons/mob/modular/modular_helmet_storage.dmi
Labels: Sprites, Removal, Balance/Rebalance, Feature

#10372 LV-624 changes: Remove chokepoint in cave, add crowbars in LZ, and make Sand Temple underground
  _maps/map_files/LV624/LV624.dmm
  code/game/area/lv624.dm
Labels: Removal, Map Edit, Feature

#10398 Fixes carriers not carrying huggers
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#10366 Shifts projectile flamer to deal damage on hit
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#10374 Relocate APC's location in Big Red's barrack and operation
  _maps/modularmaps/big_red/barracks.dmm
  _maps/modularmaps/big_red/operation.dmm
Labels: Map Edit, Feature

#10410 Injector sprite fix
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites

#10400 Grenade additions and fixes
  code/__DEFINES/conflict.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/living.dm
  code/modules/reagents/reagents/toxin.dm
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_0.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/grenade.dmi
Labels: Sprites, Refactor, Fix, Feature

#10406 Fixes moving not canceling evolution
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#10394 Removes germs from internal organs
  code/game/objects/machinery.dm
  code/game/objects/machinery/autodoc.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/organs/limbs.dm
  code/modules/organs/organ_internal.dm
Labels: Removal

#10403 Remove heavy reinforced wall in Ice Colony's red nuke disk
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Removal, Map Edit

#10402 UAVs can open doors
  code/game/objects/machinery/doors/door.dm
Labels: Quality of Life

#10401 Fixes projectile speed modifiers
  code/modules/projectiles/gun_system.dm
Labels: Fix

#10391 TGUI Hive Status Revived feat. Compact (Classic) Mode
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/mode.dm
  code/__HELPERS/global_lists.dm
  code/_globalvars/lists/mobs.dm
  code/datums/actions/observer_action.dm
  code/datums/components/orbiter.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/game_mode.dm
  code/game/atoms.dm
  code/game/objects/machinery/computer/communications.dm
  code/game/objects/structures/plants.dm
  code/modules/admin/panels/mode_panel.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/codex/entries/mobs_codex.dm
  code/modules/mob/dead/observer/orbit.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/tgui/states/xeno.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/UI_Icons/hive_status_icons.dmi
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Sprites, Removal, Refactor, Fix, Feature, Test Merge Candidate, UI, Quality of Life

#10379 Makes plasma cutters cut plasma
  code/game/objects/items/tools/mining_tools.dm
Labels: Feature

#10404 Fixes failing legs code
  code/modules/mob/living/carbon/human/life/handle_organs.dm
  code/modules/organs/limbs.dm
Labels: Fix

#10422 Empowered jab tweak
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Balance/Rebalance

#10415 ravager plasmadrain immunity
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
Labels: Feature

#10417 Xenos keep health percent through balance buff
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#10316 Heart and lung damage affect stamina, health and speed
  code/__DEFINES/mobs.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/glass.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/flasher.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/organs/limbs.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/reactions/medical.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Test Merge Candidate

#10426 Changing MG42 Sprites with new gun sound
  code/modules/projectiles/guns/rifles.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
  icons/obj/items/items_mini.dmi
  sound/weapons/guns/fire/t42.ogg
Labels: Sprites, Sound

#10432 Turns long line of parse_zone else-if's into a switch
  code/__HELPERS/unsorted.dm
Labels: Code Improvement

#10254 Readds combat droids and pre-vended protein bars to Sulaco
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#10437 Fix teleporter being mountable
  code/datums/elements/deployable_item.dm
  code/game/objects/machinery/minelayer.dm
  code/game/objects/machinery/mortar.dm
  code/game/objects/structures/teleporter.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/sentries.dm
Labels: Fix

#10434 Buff wraith portal
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Balance/Rebalance

#10436 Reduce plasma cost of all wraith abilities
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Balance/Rebalance

#10439 Some fixes to equip procs
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix

#10441 Fix missing hivemind can_flags
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
Labels: Fix

#10444 Fixes unintended Praetorian Neurotoxin nerf at Young to Mature.
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#10445 Fix flak jacket accepting modules
  code/modules/clothing/modular_armor/modular.dm
Labels: Fix

#10449 Fix organ damage not being treated by surgery
  code/modules/surgery/organs_internal.dm
Labels: Fix

#10450 Adjusts breach points on LV624 and Big Red, adds APC to LV sand temple
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/modularmaps/big_red/bigredcargoareavar1.dmm
  _maps/modularmaps/big_red/bigredcargoareavar2.dmm
  _maps/modularmaps/big_red/bigredcargoareavar3.dmm
  _maps/modularmaps/big_red/bigredcargoareavar4.dmm
  _maps/modularmaps/big_red/bigredcargoareavar5.dmm
  _maps/modularmaps/big_red/bigredcargoareavar6.dmm
  _maps/modularmaps/big_red/bigredcargoareavar7.dmm
  _maps/modularmaps/big_red/bigredcargoareavar8.dmm
  _maps/modularmaps/big_red/bigredlzvar1.dmm
  _maps/modularmaps/big_red/bigredlzvar2.dmm
  _maps/modularmaps/big_red/bigredlzvar3.dmm
  _maps/modularmaps/big_red/bigredlzvar4.dmm
  _maps/modularmaps/big_red/bigredlzvar5.dmm
  _maps/modularmaps/big_red/bigredlzvar6.dmm
  _maps/modularmaps/big_red/bigredlzvar7.dmm
  _maps/modularmaps/big_red/bigredlzvar8.dmm
  code/game/area/lv624.dm
Labels: Balance/Rebalance, Map Edit

#10435 Add back portal fancy graphic
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  icons/effects/effects.dmi
Labels: Sprites, Feature, Test Merge Candidate

#10408 Remove miners near LZ
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/modularmaps/big_red/bigredcargoareavar1.dmm
  _maps/modularmaps/big_red/bigredcargoareavar2.dmm
  _maps/modularmaps/big_red/bigredcargoareavar3.dmm
  _maps/modularmaps/big_red/bigredcargoareavar4.dmm
  _maps/modularmaps/big_red/bigredcargoareavar5.dmm
  _maps/modularmaps/big_red/bigredcargoareavar6.dmm
  _maps/modularmaps/big_red/bigredcargoareavar7.dmm
  _maps/modularmaps/big_red/bigredcargoareavar8.dmm
Labels: Removal, Map Edit, Test Merge Candidate

#10451 RL-72 has proper gunflags on spawn
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#10342 Radial menu for metal recipes + small cleanup of mats code
  code/__DEFINES/preferences.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/preferences_ui.dm
  icons/Marine/barricades.dmi
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Sprites, Removal, Refactor, Test Merge Candidate, UI, Quality of Life

#10326 Internal organs damage are visible on the health analyzer
  code/game/objects/items/scanners.dm
  tgui/packages/tgui/interfaces/MedScanner.js
Labels: Balance/Rebalance, UI

#10321 Medical Storage Changes
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
  _maps/shuttles/big_ert.dmm
  _maps/shuttles/distress.dmm
  _maps/shuttles/distress_pmc.dmm
  _maps/shuttles/distress_upp.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/__DEFINES/loadout.dm
  code/_globalvars/lists/objects.dm
  code/datums/jobs/job/clf.dm
  code/datums/jobs/job/deathsquad.dm
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/imperium.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/jobs/job/special_forces.dm
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/surgical_tray.dm
  code/game/objects/items/tools/soldering_tool.dm
  code/game/objects/items/tools/surgery_tools.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/under.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reqs/supplypacks.dm
  code/modules/surgery/necrosis.dm
  code/modules/surgery/organs_internal.dm
  icons/Marine/marine-pouches.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/chemistry.dmi
  icons/obj/items/storage/storage.dmi
  icons/obj/items/surgery_tools.dmi
Labels: Sprites, Map Edit, Feature

#10463 Fixes lungs not updating slowdown
  code/modules/organs/organ_internal.dm
Labels: Fix

#10414 Roundstart map announce_text fixed & icarus military port announce_text changed
  _maps/bigred_v2.json
  _maps/desertdam.json
  _maps/icarus_military_port.json
  _maps/ice_colony_v2.json
  _maps/icy_caves.json
  _maps/lv624.json
  _maps/magmoor_digsite_iv.json
  _maps/prison_station_fop.json
  _maps/research_outpost.json
  _maps/vapor_processing.json
  _maps/whiskey_outpost_v2.json
  code/datums/map_config.dm
Labels: Fix, Map Edit, Feature

#10413 Akimbo nerfs
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Balance/Rebalance

#10424 Moves some items away from reqs
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
Labels: Removal, Balance/Rebalance

#10469 Changes the eva skull sprite
  icons/mob/modular/eva.dmi
Labels: Sprites

#10470 Nerfs fire strength against resin walls
  code/game/turfs/walls/resin.dm
Labels: Balance/Rebalance

#10471 Xenos are no longer cucked by a knee high railing
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/platforms.dm
Labels: Fix

#10486 Remove project leader role from contributing.md, move that file to root folder
  CONTRIBUTING.md
Labels: GitHub

#10485 Runners can't graverob
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Fix

#10482 gives the BR-64 one (1) extra round per magazine
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance/Rebalance

#10466 Removes the TerraGovTech Corpsmen Vendor
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/machines/vending.dmi
Labels: Sprites, Removal, Map Edit, Quality of Life

#10433 Add a new wraith ability: woosh swoosh
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  icons/mob/actions.dmi
  sound/effects/woosh_swoosh.ogg
Labels: Sprites, Sound, Feature

#10493 Revert "Changes the eva skull sprite"
  icons/mob/modular/eva.dmi
Labels: Sprites, Revert

#10496 Valhalla fixes, again
  code/game/objects/machinery/vending/vending_types.dm
Labels: Fix

#10499 Mpi-KM attachment changes and slowdown reduction
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#10502 Combat Robot Optical Meson Scanner Sprite Fix
  icons/mob/species/robot/glasses.dmi
Labels: Sprites, Fix

#10503 Remove using wrench to undeploy mortar
  code/game/objects/machinery/mortar.dm
Labels: Quality of Life

#10440 Fix jetpack flying while buckled
  code/game/objects/items/jetpack.dm
Labels: Fix

#10472 Necrotic limbs applies organ damage over time
  code/game/objects/items/scanners.dm
  code/modules/organs/limbs.dm
Labels: Feature

#10505 Removes damage falloff from boiler projectiles
  code/modules/projectiles/ammo_datums.dm
Labels: Removal, Balance/Rebalance

#10461 Adds new effects to kidneys, cleans up liver
  code/__DEFINES/dcs/signals.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/status_procs.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/holder.dm
  code/modules/reagents/reagents/drink.dm
Labels: Balance/Rebalance, Feature

#10517 Tgstation Test explorer for VScode now work properly
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/unit_test.dm
Labels: Code Improvement

#10506 Breathing/losebreath cleanup
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/reagents/medical.dm
  icons/mob/screen/generic.dmi
Labels: Sprites, Fix, Feature

#10500 NTmed pill bottles revert
  code/game/objects/machinery/vending/vending_types.dm
Labels: Balance/Rebalance, Revert

#10497 Marine ballistic goggles are now tiny, letting you fit goggles and another object
  code/modules/clothing/glasses/glasses.dm
Labels: Balance/Rebalance

#10429 Support for bigger worn and inhand icons and change some images to mutable appearances
  code/__HELPERS/icons.dm
  code/datums/components/attachment_handler.dm
  code/game/objects/items.dm
  code/game/objects/items/jetpack.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/human/update_icons.dm
Labels: Code Improvement, Test Merge Candidate

#10507 Blood over maximum leaks out
  code/modules/mob/living/blood.dm
Labels: Fix, Feature

#10393 Win fix
  code/datums/gamemodes/infestation.dm
  code/datums/gamemodes/nuclear_war.dm
Labels: Fix

#10509 Fixes Ice Colony LZ1, adds APC to LZ2
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  code/game/area/icecolony.dm
Labels: Balance/Rebalance, Fix, Map Edit

#10530 Adds a pinpointer to op vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance/Rebalance

#10527 Swap surgery prio for necrosis and organ repair
  code/modules/surgery/necrosis.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/surgery.dm
Labels: Fix

#10526 Adds routing for robot heals in two human procs
  code/datums/components/harvester.dm
  code/game/objects/machinery/autodoc.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/reagents/reagents/medical.dm
Labels: Code Improvement, Fix

#10531 Resprites/ports firedoor sprites, removes more flat icons
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/effects/misc.dm
  code/game/objects/items/frames/table_rack.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/clothing/clothing.dm
  icons/Marine/mainship_props.dmi
  icons/effects/effects.dmi
  icons/obj/doors/DoorHazard.dmi
  icons/obj/doors/Doorext.dmi
  icons/obj/items/items.dmi
  icons/obj/stationobjs.dmi
  icons/obj/structures/tables.dmi
Labels: Sprites, Removal, Code Improvement, Fix, Map Edit

#10520 Big Red modular map fix
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar1.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar2.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar3.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar4.dmm
  _maps/modularmaps/big_red/bigredtoolshedvar5.dmm
Labels: Fix, Map Edit

#10504 Ports TG's/Tau Ceti's welding effect
  code/__DEFINES/layers.dm
  code/game/objects/items.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/machinery/deployable.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/floor.dm
  code/game/turfs/walls/walls.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/power/fusion_engine.dm
  code/modules/power/groundmap_geothermal.dm
  icons/effects/welding_effect.dmi
  icons/effects/welding_effect_multitile_door.dmi
  icons/turf/floors.dmi
Labels: Sprites, Feature

#10533 Fixes wraith portals being unaffected by most explosions
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#10541 Peri+ clone loss scales with organ damage healed
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/reagents/reagents/medical.dm
Labels: Balance/Rebalance

#10538 Dylovene reduces stamina regen with any volume
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/reagents/medical.dm
Labels: Balance/Rebalance

#10543 Pills and hypos call reaction_mob properly
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/pill.dm
Labels: Code Improvement

#10519 Mosin Clips
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/magazines/shotguns.dm
  icons/obj/items/ammo.dmi
Labels: Sprites, Feature

#10523 Defiler fixes
  code/__DEFINES/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Refactor, Fix

#10511 Smart pistol
  code/datums/jobs/job/shipside.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Balance/Rebalance, Feature

#10539 LV modular maps
  _maps/map_files/LV624/LV624.dmm
  _maps/modularmaps/lv624/lvhydrobridge1.dmm
  _maps/modularmaps/lv624/lvhydrobridge2.dmm
  _maps/modularmaps/lv624/lvhydrobridge3.dmm
  _maps/modularmaps/lv624/lvhydrobridge4.dmm
  _maps/modularmaps/lv624/southsandtemple1.dmm
  _maps/modularmaps/lv624/southsandtemple2.dmm
  _maps/modularmaps/lv624/southsandtemple3.dmm
  _maps/modularmaps/lv624/southsandtemple4.dmm
  code/game/objects/effects/spawners/modularmappingspawner.dm
  code/modules/mapping/modular_mapping.dm
Labels: Map Edit
