Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2022-02, with the labels that each got.

#9465 Fix Vahalla's TerraGovTech Requisition Vendor sprites
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#9464 Prep signs for marine role in shipside
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit, Quality of Life

#9454 Fix gib animation
  code/game/objects/effects/overlays.dm
  code/game/objects/items/binoculars.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/death.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Fix

#9455 Fix bull primo
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Fix

#9460 Marine can no longer shuffle xenos
  code/modules/mob/living/living.dm
Labels: Fix

#9237 The Hypospray Belt
  code/__DEFINES/loadout.dm
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/firstaid.dm
  icons/obj/clothing/belts.dmi
  icons/obj/items/storage/storage.dmi
Labels: Sprites, Mechanic

#9461 fixes xeno larva spawn menu sound
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#9462 Putting Tricord pill bottles in med belts
  code/__DEFINES/loadout.dm
  code/game/objects/items/storage/belt.dm
Labels: Removal, Balance/Rebalance, Quality of Life, Mechanic

#9473 Infinite packets and ammo boxes
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance/Rebalance, Quality of Life

#9439 Gives Tx11 autoburst mode
  code/modules/projectiles/guns/rifles.dm
Labels: Quality of Life

#9450 new 1911 sprites by Dongwaiver
  code/modules/projectiles/guns/pistols.dm
  icons/obj/items/gun.dmi
Labels: Sprites

#9477 Necrosis removal surgery clears germs
  code/modules/surgery/necrosis.dm
Labels: Balance/Rebalance

#9485 Fix projectiles hitting allies in aim mode
  code/modules/projectiles/projectile.dm
Labels: Fix

#9435 Drone primordial
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/xeno.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/Xeno/plants.dmi
  icons/mob/actions.dmi
Labels: Sprites, Test Merge Candidate, Mechanic

#9492 Fixes for the Minerva
  _maps/map_files/Minerva/TGS_Minerva.dmm
Labels: Fix, Map Edit

#9475 Moves Optical Meson Scanner to Engineer Clothing Vendor
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Removal, Balance/Rebalance

#9508 Removed duplicate code from energy weapons
  code/modules/projectiles/guns/energy.dm
Labels: Code Improvement

#9507 T-26 can actually use its alt ammo types
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#9506 overwatch notification typo
  code/game/objects/machinery/overwatch.dm
Labels: Grammar and Formatting

#9488 Xeno resin door fixes
  code/game/objects/structures/xeno.dm
Labels: Fix

#9486 Warrior lunge range qol
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Quality of Life

#9493 Fix T-29 Smart Machinegun Unwelded Mob Sprites; it was reversed and had no back sprite
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
Labels: Sprites, Fix

#9495 Reduce big sentry scatter
  code/modules/projectiles/guns/sentries.dm
Labels: Balance/Rebalance

#9476 Vote qol
  code/controllers/subsystem/vote.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/login.dm
Labels: Test Merge Candidate, Quality of Life

#9497 Fix movable light colors
  code/_onclick/hud/rendering/plane_master.dm
Labels: Fix

#9498 Maybe fix shuttle lights
  code/game/turfs/turf.dm
Labels: Fix

#9429 DNRs no longer show up as defibbable on the minimap
  code/game/data_huds.dm
Labels: Fix, Test Merge Candidate

#9519 Fix hypospray belt not accepting five specific autoinjectors
  code/game/objects/items/storage/belt.dm
Labels: Fix

#9525 Moving YouTool code to marine_vending.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Code Improvement, Fix

#9518 Hypospray has 30u & 20u mode and QoL with amount per transfer menu
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Quality of Life, Mechanic

#9527 Fixes mortar flares
  code/game/objects/machinery/mortar.dm
Labels: Fix

#9528 Fixes HUD layering
  code/_onclick/hud/hud.dm
  code/_onclick/hud/rendering/plane_master.dm
Labels: Fix

#9526 Adds the heat absorbent coifs crates to ice colony.
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Map Edit, Mechanic

#9474 Scatter balance pass
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Balance/Rebalance

#9504 Significantly reduces snow storm opacity
  icons/effects/weather_effects.dmi
Labels: Sprites, Quality of Life

#9500 Robots no longer have chem in their body
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Test Merge Candidate, Quality of Life

#9530 Primo drone fixes
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/xeno_buffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix

#9531 Revert "Bring back grenade chain explosion (#8972)"
  code/game/objects/items/explosives/grenades/grenade.dm
Labels: Balance/Rebalance, Revert

#9534 No more weird shuffle when moving diagonaly
  code/modules/mob/living/living.dm
Labels: Fix

#9536 PREVENT_CONTENTS_EXPLOSION in item
  code/game/objects/items.dm
  code/game/objects/items/storage/boxes.dm
Labels: Fix

#9538 Engineers get a free teleporter in their kit. You can put one teleporter on your back
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/teleporter.dm
  icons/Marine/teleporter.dmi
  icons/mob/back.dmi
Labels: Sprites, Balance/Rebalance, Mechanic

#9480 Refactors some plasmacutter behavior, squashes a number of plasmacutter bugs
  code/__DEFINES/is_helpers.dm
  code/game/objects/structures/cas_plane_parts.dm
  code/game/turfs/closed.dm
  code/game/turfs/walls/wall_types.dm
  code/game/turfs/walls/walls.dm
Labels: Refactor, Fix, Test Merge Candidate

#9533 Sharable NanotrasenMed Plus & rebalancing the NanotrasenMed Plus
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Balance/Rebalance, Map Edit, Mechanic

#9408 Xeno upgrade changes
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/crash.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/unit_tests/xeno_logical_scaling.dm
Labels: Balance/Rebalance, Test Merge Candidate, Quality of Life

#9542 Unnerf primo runner
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Balance/Rebalance

#9547 Remove synth vendor medhud
  code/__DEFINES/loadout.dm
Labels: Fix

#9472 Fix some centrifugal force bugs
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Fix

#9509 Makes autoburst extra (extra) delay a var
  code/datums/components/autofire.dm
  code/modules/projectiles/gun_system.dm
Labels: Mechanic

#9557 Fix misspelling on primo crusher's rapid advance
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Grammar and Formatting

#9540 Allow TL127 and Mosin to take bipod attachment
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance/Rebalance

#9529 Adds M21 APRDS "Minelayer"
  code/__DEFINES/loadout.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/machinery/minelayer.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-items.dmi
  tgmc.dme
Labels: Sprites, Mechanic

#8633 Motorbike sidecar
  code/datums/components/riding/riding_vehicle.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/motorbike.dm
  icons/obj/motorbike_sidecar.dmi
  icons/obj/vehicles.dmi
Labels: Sprites, Test Merge Candidate, Mechanic

#9535 Remove stored egg from carrier's game panel
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Removal

#9546 xenonauten essentials has descs now
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Fix

#9239 Adds the 6E Chameleon Cape
  code/__DEFINES/attachments.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/modular_armor.dm
  code/datums/components/attachment_handler.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/cape.json
  code/datums/greyscale/json_configs/cape_highlight.json
  code/datums/greyscale/json_configs/cape_highlight_no_hood.json
  code/datums/greyscale/json_configs/cape_no_hood.json
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/clothing/modular_armor/attachments/cape.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/attachments/visors.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/under/under.dm
  icons/mob/modular/assault.dmi
  icons/mob/modular/capes/full.dmi
  icons/mob/modular/capes/half.dmi
  icons/mob/modular/capes/scarf.dmi
  icons/mob/modular/capes/short.dmi
  icons/mob/modular/eod.dmi
  icons/mob/modular/eva.dmi
  icons/mob/modular/infantry.dmi
  icons/mob/modular/scout.dmi
  icons/mob/modular/skirmisher.dmi
  tgmc.dme
Labels: Sprites, Code Improvement, Fix, Mechanic

#9548 Feat: add 5 new EORG maps
  _maps/modularmaps/EORG/cs_mansion.dmm
  _maps/modularmaps/EORG/cs_militia.dmm
  _maps/modularmaps/EORG/cs_office.dmm
  _maps/modularmaps/EORG/de_inferno.dmm
  _maps/modularmaps/EORG/de_nuke.dmm
  code/modules/mapping/modular_mapping.dm
Labels: Map Edit, Mechanic

#9550 Fix webbings fitting in bags
  code/__DEFINES/is_helpers.dm
  code/datums/jobs/job/special_forces.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
Labels: Fix

#9227 Evacuation can prevent xeno major
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mode.dm
  code/controllers/subsystem/evacuation.dm
  code/controllers/subsystem/monitor.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/gamemodes/infestation.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/airlock_control.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/machinery/doors/door.dm
  code/modules/shuttle/escape_pod.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Map Edit, Test Merge Candidate, Mechanic

#9556 resprite MarineMed and remap corpsman prep
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/machines/vending.dmi
Labels: Sprites, Fix, Map Edit

#9573 You can deploy all deployable items by cntrl clicking the ground
  code/datums/elements/deployable_item.dm
  code/game/objects/machinery/minelayer.dm
  code/modules/projectiles/gun_system.dm
Labels: Quality of Life

#9578 Primordial drone buff
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Balance/Rebalance

#9590 robot visors now rewind properly
  icons/mob/human_races/r_robot.dmi
  icons/mob/species/robot/glasses.dmi
Labels: Sprites, Fix

#9574 Fix Tx73
  _maps/map_files/generic/Admin_Level.dmm
  code/datums/jobs/job/imperium.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/magazines/energy.dm
Labels: Fix, Map Edit

#9566 Remove ob beacons from game
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/marines.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/reqs/supplypacks.dm
Labels: Removal

#9567 Fix neurotoxin sting being on queen and shrike primos
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
Labels: Fix

#9579 Wraith's Time Stop Action Icon is now actually in game and in codebase
  icons/mob/actions.dmi
Labels: Sprites, Fix

#9577 Remove any mention of /obj/item/cell/lasgun/tesla
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/reqs/supplypacks.dm
Labels: Removal, Fix

#9223 You can send supply drop in caves
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/objects/machinery/squad_supply/supply_console.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/reqs/supply.dm
Labels: Balance/Rebalance

#9580 Neurospit buff
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#9565 Akimbo delay applies to autofire
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Fix

#9572 Handheld charger rightclick action
  code/game/objects/items/tools/maintenance_tools.dm
Labels: Mechanic

#9601 Teleporter comes with a high-capacity cell installed
  code/game/objects/structures/teleporter.dm
Labels: Balance/Rebalance

#9605 Fix wraith and runno primo
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#9609 Fix being able to diagonally walk through platforms
  code/game/objects/structures/platforms.dm
Labels: Fix

#9611 Fixes some incorrect sentry behavior
  code/modules/projectiles/sentries.dm
Labels: Fix

#9381 Refactor: make SSrunechat to be subsystem of SStimer
  code/controllers/subsystem/runechat.dm
  code/datums/chatmessage.dm
Labels: Refactor, RED LABEL

#9293 Primos can be bought by tiers
  code/__DEFINES/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  icons/mob/actions.dmi
Labels: Sprites, Mechanic

#9604 Fix larva regress exploit
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#9594 T-26 AMR price reduced from 75 to 65
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#9615 Shrike's gravity nade fix.
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Fix

#9607 Fix a visual bug with lasers and wraith primo
  code/modules/projectiles/projectile.dm
Labels: Fix

#9595 Reqtorio cost balance (again)
  code/modules/factory/outputter.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance

#9617 lunge fix
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Fix

#9618 Razorwire fix
  code/game/objects/structures/razorwire.dm
Labels: Fix

#9610 Buffs primordial boiler's lance glob accuracy and speed
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance

#9629 Deployables can no longer be deployed into nullspace
  code/datums/elements/deployable_item.dm
Labels: Fix

#9628 Fixes cryo icon not updating
  code/modules/atmospherics/machinery/components/components_base.dm
Labels: Fix

#9649 Bluespace teleporters can be damaged by xenos
  code/game/objects/structures/teleporter.dm
Labels: Balance/Rebalance

#9647 fix render effect cutting
  code/_onclick/hud/rendering/plane_master.dm
Labels: Fix

#9561 Tadpole balance: medbus edition
  _maps/shuttles/minidropship.dmm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Balance/Rebalance, Map Edit

#9569 Xenomorphs cannot use most abilities nor attack while on a solid turf (e.g. a resin wall)
  code/__DEFINES/actions.dm
  code/_globalvars/bitfields.dm
  code/_onclick/xeno.dm
  code/datums/actions/xeno_action.dm
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Balance/Rebalance, Fix, Test Merge Candidate

#9636 Fixes deployables on dropship equipment
  code/datums/elements/deployable_item.dm
Labels: Fix, Test Merge Candidate

#9619 T-26 Alt ammo buff and available from req
  code/modules/projectiles/ammo_datums.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance/Rebalance, Mechanic

#9652 MG-08/495 ammo box
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/items/storage/storage_boxes.dmi
  tgmc.dme
Labels: Sprites, Balance/Rebalance, Mechanic

#9640 Logistic Access Change For Corporate Liaison
  code/datums/jobs/job/shipside.dm
Labels: Content Expansion

#9614 Miner upgrades in engineer point vendor
  code/__DEFINES/loadout.dm
Labels: Balance/Rebalance

#9672 Fix TGMC big letters
  icons/Marine/mainship_props64.dmi
Labels: Sprites, Fix

#9654 Xeno's turret deploy time reduced to 10s.
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Quality of Life

#9663 Fixes zero stacks of handfuls
  code/modules/projectiles/ammunition.dm
Labels: Fix

#9670 Makes announcement hearable even if deaf
  code/__HELPERS/announce.dm
Labels: Balance/Rebalance

#9657 No decap on headbands; Same Armor as berets
  code/modules/clothing/head/head.dm
Labels: Balance/Rebalance

#9666 Makes plasma pistol attachment shoot only while wielded
  code/modules/projectiles/guns/pistols.dm
Labels: Balance/Rebalance

#9661 Reduces Acid well Cost.
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Balance/Rebalance

#9676 laser pistol can be held in shoulder holster, and pistol belts can hold 6 lasgun mags
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
Labels: Balance/Rebalance, Fix

#9644 Left click takes cells out of handheld chargers again
  code/game/objects/items/tools/maintenance_tools.dm
Labels: Fix, Quality of Life

#9675 Acid rain is now colored, and changed rain code a bit to reflect that
  code/datums/weather/weather_types/acid_rain.dm
  icons/effects/weather_effects.dmi
Labels: Sprites, Code Improvement, Content Expansion

#9668 Fixes playing cards
  code/game/objects/items/toys/cards.dm
  icons/obj/items/playing_cards.dmi
Labels: Sprites, Fix

#9669 Detpack fixes
  code/game/objects/items/radio/detpack.dm
Labels: Balance/Rebalance, Fix

#9625 DS is actually OP now
  code/datums/jobs/job/deathsquad.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/weapons/energy.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance/Rebalance, Administration, Mechanic

#9681 Fixing my own pr (Plasma pistol can only fire while wielded)
  code/modules/projectiles/guns/pistols.dm
Labels: Fix

#9697 Northwestern Icy caves APC's fixes
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Fix, Map Edit

#9704 Fixes the bouncy revolver
  code/modules/projectiles/ammo_datums.dm
Labels: Fix
