Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2022-11, with the labels that each got.

#11252 Rain now cleans blood and grime off marines and puts out burning mobs
  code/datums/weather/weather_types/acid_rain.dm
Labels: Feature

#11386 Nerfs Warrior Lunge bonus modifier for Punch from x2.0 to x1.5
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Balance

#11388 Drowsiness sleep chance changed to only activate after a certain stack threshold
  code/modules/mob/living/carbon/life.dm
Labels: Balance

#11394 auto-reload for mech
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Quality of Life

#11395 Arty range fix
  code/game/objects/machinery/mortar.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance, Fix

#11397 Adds keybinds to mecha
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/keybind.dm
  code/datums/keybinding/mecha.dm
  code/modules/vehicles/mecha/combat/marauder.dm
  code/modules/vehicles/mecha/combat/savannah_ivanov.dm
  code/modules/vehicles/mecha/mecha_actions.dm
  tgmc.dme
Labels: Quality of Life

#11330 Removes chemisty grenade crafting recipe
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Removal

#11392 Mech no longer gets control loss
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Labels: Balance

#11399 Adds MP bay to Minerva
  _maps/map_files/Minerva/TGS_Minerva.dmm
Labels: Priority: High, Map Edit, Feature

#11389 Resprites yet more objects
  _maps/map_files/Icarus_Military_Port/icarus_military_port.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/modularmaps/EORG/old.dmm
  _maps/modularmaps/lv624/lvhydrobridge2.dmm
  _maps/modularmaps/lv624/lvhydrobridge3.dmm
  _maps/modularmaps/lv624/lvhydrobridge4.dmm
  _maps/modularmaps/lv624/southsandtemple1.dmm
  _maps/modularmaps/lv624/southsandtemple3.dmm
  _maps/shuttles/escape_shuttle.dmm
  code/__DEFINES/smoothing.dm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed.dm
  icons/misc/buildmode.dmi
  icons/obj/items/chemistry.dmi
  icons/obj/items/items.dmi
  icons/obj/items/storage/storage.dmi
  icons/obj/items/trash.dmi
  icons/obj/machines/computer3.dmi
  icons/obj/machines/drone_fab.dmi
  icons/obj/reagentfillings.dmi
  icons/obj/structures/structures.dmi
  icons/turf/shuttle.dmi
Labels: Sprites, Removal, Map Edit

#11402 Theseus polish and fix
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/objects/machinery/door_control.dm
Labels: Fix, Map Edit, Feature

#11405 Adds radial menu support to medical tweezers, chain-tweezing.
  code/datums/elements/shrapnel_removal.dm
Labels: Quality of Life

#11400 Fixes being able to pod into BR containment tanks
  _maps/modularmaps/big_red/bigredatmosvar1.dmm
  _maps/modularmaps/big_red/bigredatmosvar3.dmm
  _maps/modularmaps/big_red/bigredatmosvar4.dmm
  _maps/modularmaps/big_red/bigredatmosvar6.dmm
Labels: Fix, Map Edit

#11412 MP Armor Fix
  code/modules/clothing/suits/marine_armor.dm
Labels: Fix

#11417 Buffs the ammount of ammo mecha ammo boxes have
  code/modules/vehicles/mecha/equipment/weapons/mecha_ammo.dm
Labels: Quality of Life

#11418 Nerfs mecha efficiency module from 75% energy reduction to 50%
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Labels: Balance

#11416 Fixes rain giving xenos wet messages
  code/datums/weather/weather_types/acid_rain.dm
Labels: Fix

#11415 Nerfs laser sword energy usage and increase cooldown between uses
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
Labels: Balance

#11409 Gives mech pilot quarters more protection.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/multi_tile.dm
  code/game/objects/machinery/doors/poddoor.dm
Labels: Balance, Map Edit

#11413 Mech health nerfed
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Labels: Balance

#11411 Prison Station East LZ heavy reinforced walls removed
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Fix, Map Edit

#11404 Lets requisitions vend mech ammo
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Quality of Life

#11422 Nerf Mech healing
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Balance

#11429 Various minor HvH tweaks and fixes
  code/datums/quick_load_outfits.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/specialist.dm
  icons/obj/items/ammo.dmi
Labels: Sprites, Balance, Fix

#11433 Railgun now has Scope (and offset fix)
  code/modules/projectiles/guns/specialist.dm
Labels: Balance, Fix

#11419 Mech Repair Now Fumbles
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Balance

#11398 Fixes hivemind breaking hive status and chat and fixes hivemind core getting killed upon hijack
  code/__DEFINES/mobs.dm
  code/__DEFINES/xeno.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#11363 Pepperball magazine, aim mode buff, infinite magazines, added to req and rail light addition
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance

#11379 Fixes smoothing when mining turfs
  code/game/turfs/turf.dm
Labels: Fix

#11434 Ally export prevention
  code/modules/requisitions/supply_export.dm
Labels: Fix

#11435 Pillar of Spring's Winter Edition part 1: fix CIC APC and help MP
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Removal, Fix, Map Edit, Feature

#11438 Add phoron stack and another mech console in Minerva
  _maps/map_files/Minerva/TGS_Minerva.dmm
Labels: Map Edit, Feature

#11441 Defiler's Tentacle ability will no longer go on cooldown if it fails
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Labels: Fix

#11443 Xenomorph pheromones update when maturing
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Fix

#11387 Nerfs Warrior Lunge range from 6 to 4 tiles
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Balance

#11439 Lowers the inventory size of thermal dampening tarps
  code/game/objects/items/bodybag.dm
Labels: Balance

#11445 Defiler now consumes plasma after noxius gas has channeled
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Labels: Balance

#11450 BR-8 scout rifle magazine assembly refill Cost Fix
  code/modules/reqs/supplypacks.dm
Labels: Fix

#11359 Hod head module
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites, Feature

#11454 facehuggers no longer disable lights and headset
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Removal, Balance

#11396 Adds a limiter for CAS hotkeys
  tgui/packages/tgui/interfaces/MarineCasship.tsx
Labels: Fix, Feature, UI

#11453 remove semi fire mode from guns with autofire [MDB Ignore]
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Removal

#11458 Turf smoothing runtime fix
  code/game/turfs/turf.dm
Labels: Fix

#11456 Gun icon update refactor
  code/modules/projectiles/gun_system.dm
Labels: Refactor

#11420 Artillery impact tablet
  code/game/objects/items/devices/tablets.dm
  code/game/objects/machinery/mortar.dm
Labels: Feature, UI

#11367 Adds the TA-40L Rocket Artillery system and some ammo datum fixes for artillery rounds.
  code/game/objects/machinery/mortar.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/mortar.dmi
Labels: Sprites, Feature, Test Merge Candidate

#11448 dispenser fixes
  code/game/objects/items/storage/dispenser.dm
Labels: Fix

#11446 Raises Queen Leader Slots
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Balance

#11436 Facehugger Impregnates Faster
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Balance

#11410 Valhalla Mech Pilot
  _maps/map_files/generic/Admin_Level.dmm
  code/datums/jobs/job/fallen.dm
Labels: Map Edit, Feature, Test Merge Candidate

#11393 MPs available on distress/nuclear war
  code/datums/gamemodes/distress.dm
  code/datums/jobs/job/shipside.dm
Labels: Fix, Feature

#11421 Mech Pilot Job Slots
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
Labels: Feature

#11469 Git actions changes
  .github/workflows/auto_changelog.yml
  .github/workflows/compile_changelogs.yml
  .github/workflows/generate_documentation.yml
  .github/workflows/remove_guide_comments.yml
  .github/workflows/update_tgs_dmapi.yml
Labels: GitHub

#11474 [s] test pr
  config/config.txt
Labels: Config Update

#11467 mlrs impact tablet and explosion animation
  code/game/objects/machinery/mortar.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Feature

#11461 Nuke Disk Gen minimap icon fix
  code/game/objects/machinery/computer/nuke_disk_generator.dm
Labels: Fix

#11465 Mech Pilot Crew Manifest Tag Added
  code/__DEFINES/jobs.dm
Labels: Fix

#11466 Balloon alerts barricades and some gun stuff
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/barricade.dm
  code/modules/projectiles/gun_helpers.dm
Labels: Quality of Life

#11463 Flamer particle colors
  code/modules/projectiles/guns/flamer.dm
Labels: Quality of Life

#11468 Mech pilot's hud icon addition + Captain's hud icon fix + loadout beret fix
  code/modules/client/preferences_gear.dm
  icons/mob/hud.dmi
Labels: Sprites, Fix

#11477 Updated walls and resin/weed sprites
  code/controllers/subsystem/weeds.dm
  code/game/objects/effects/weeds.dm
  code/game/turfs/turf.dm
  icons/Xeno/Effects.dmi
  icons/Xeno/structures.dmi
  icons/Xeno/weeds.dmi
  icons/mob/actions.dmi
  icons/turf/walls.dmi
Labels: Sprites, Feature

#11444 Drones can now cancel essence links properly, essence link automatically removed on death.
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
Labels: Fix

#11492 Revert "Adds Cat Ears (back)"
  code/game/objects/effects/landmarks/itemspawner.dm
  code/game/objects/effects/spawners/random.dm
  code/modules/clothing/head/collectable.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/head_0.dmi
  icons/mob/uniform_0.dmi
Labels: Sprites, Revert

#11483 remove the 3 extra sentries and hsg marines get in crash
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
Labels: Balance, Map Edit

#11486 No mechs in lowpop
  code/controllers/subsystem/job.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/extended.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/shipside.dm
Labels: Balance

#11484 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub

#11460 Adds the melee core
  code/__DEFINES/traits.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  icons/mecha/mecha_equipment.dmi
Labels: Sprites, Feature

#11423 Paracetamol no longer purges Tricordrazine
  code/modules/reagents/reagents/medical.dm
Labels: Balance

#11464 Misc bombvest code improvements
  code/game/objects/items/explosives/bombvest.dm
Labels: Administration, Quality of Life

#11337 Hive threat - new event for xenos
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/traits.dm
  code/game/data_huds.dm
  code/modules/events/hive_threat.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  icons/mob/hud.dmi
  tgmc.dme
Labels: Sprites, Feature

#11381 Adds TGMC pack boxes
  code/game/objects/items/loot_box.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature

#11424 oxycodone now gives 100 pain resistance over 50.
  code/__DEFINES/mobs.dm
  code/modules/reagents/reagents/medical.dm
Labels: Balance

#11498 Fix MP having lead skill
  code/datums/skills.dm
Labels: Fix

#11493 Woyer can punch vehicles properly
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Fix

#11501 Autoinjectors can't absorb pills, grammar
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Fix, Grammar and Formatting

#11499 Make bookcases slashable by xenos
  code/game/objects/structures/bookcase.dm
Labels: Quality of Life

#11497 Fix extra space in minion names
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#11495 Mechs take the same damage from crusher charge as anchored objects
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Balance

#11502 Mech actually has bio armor now
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Labels: Balance

#11494 Mech extinguisher not selectable
  code/modules/vehicles/mecha/equipment/tools/work_tools.dm
Labels: Fix

#11488 Changes MG42 gun sound back to old T42 gun sound.
  code/modules/projectiles/guns/rifles.dm
Labels: Sound

#11189 makes mounted guns easy to use
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/mounted.dm
  code/modules/projectiles/projectile.dm
Labels: Balance, Quality of Life

#11336 Increase Synth Nade Permissions
  code/game/objects/items/devices/mirage.dm
Labels: Balance

#11506 Fixes mech component damage and weapon integrity
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Fix

#11507 Fix actuator exploit
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/gygax.dm
Labels: Fix, In Game Exploit

#11510 Xenos keep numeric age on evolve/upgrade
  code/__DEFINES/mobs.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Code Improvement, Quality of Life

#11512 APC prop QOL change
  code/game/objects/structures/prop.dm
Labels: Quality of Life

#11514 change name of marine platoon
  code/modules/shuttle/marine_dropship.dm
Labels: Feature

#11519 Nerfs mech armor and HP
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Labels: Balance

#11447 Marine masks no longer protect against ash/sandstorms
  code/datums/weather/weather_types/ash_storm.dm
Labels: Balance, Test Merge Candidate

#11516 Fixes drone enhancement
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
Labels: Fix

#11511 Supply drop event
  code/datums/gamemodes/civil_war.dm
  code/datums/gamemodes/combat_patrol.dm
  code/datums/gamemodes/game_mode.dm
  code/game/objects/items/loot_box.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/events/supply_drop.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
  icons/Marine/gun64.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  tgmc.dme
Labels: Sprites, Feature

#11523 Some mech weapon balance changes
  code/modules/projectiles/ammo_datums.dm
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
Labels: Balance

#11522 Mech engine rebalance
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Labels: Balance

#11532 Carrier can switch huggers while resting
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Quality of Life

#11530 Fixes weed landmark icon
  code/game/objects/effects/landmarks/landmarks.dm
Labels: Fix

#11525 Makes mechs take damage from lava
  code/game/turfs/open.dm
Labels: Balance

#11534 Rollerbed fix
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Fix

#11535 quick equip storage order tweaks
  code/__DEFINES/equipment.dm
Labels: Quality of Life

#11543 Makes rejuvenate and feast work even if staggered
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
Labels: Balance

#11548 Spawned in xenos have correct age
  code/modules/events/hive_threat.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Fix

#11540 Dispenser nerfed to 48 max storage size from 63.
  code/game/objects/items/storage/dispenser.dm
Labels: Balance

#11513 Wall and window sprites
  icons/obj/structures/window_frames.dmi
  icons/obj/structures/windows.dmi
  icons/turf/walls.dmi
Labels: Sprites

#11520 Hull wall update
  icons/turf/mainshipwalls.dmi
Labels: Sprites

#11518 Improved resin door visibility
  icons/Xeno/Effects.dmi
  icons/mob/actions.dmi
Labels: Sprites

#11539 Mateba changes, removes snubnose, and some minor scatter buffs.
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/revolvers.dm
Labels: Removal, Balance

#11550 Adds fat removal surgery, kills a dead var
  code/__DEFINES/mobs.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/life/handle_organs.dm
  code/modules/reagents/reagents/other.dm
  code/modules/surgery/encased.dm
  code/modules/surgery/surgery.dm
Labels: Feature

#11517 Rocket Storage Box QoL
  code/game/objects/machinery/mortar.dm
  code/modules/reqs/supplypacks.dm
Labels: Quality of Life

#11556 Minimap improvements
  code/__DEFINES/minimap.dm
  code/controllers/subsystem/minimaps.dm
  code/game/area/area.dm
  code/game/area/bigred.dm
  code/game/area/desertdam.dm
  code/game/area/gelida_iv.dm
  code/game/area/general.dm
  code/game/area/icecolony.dm
  code/game/area/icy_caves.dm
  code/game/area/lv624.dm
  code/game/area/orion_outpost.dm
  code/game/area/prison.dm
  code/game/area/research_outpost.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/turfs/floor_ground.dm
  code/game/turfs/open.dm
  code/game/turfs/open_ground.dm
  code/game/turfs/snow.dm
  code/game/turfs/turf.dm
Labels: Quality of Life

#11566 Tad weaponpoint fix
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#11568 Reqtorio Expansion V 1.0
  code/modules/factory/howtopaper.dm
  code/modules/factory/parts.dm
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature

#11553 Exploding barrels
  _maps/map_files/Icarus_Military_Port/icarus_military_port.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/combat_patrol_base/combat_patrol_base.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/modularmaps/EORG/cs_mansion.dmm
  _maps/modularmaps/EORG/de_inferno.dmm
  _maps/modularmaps/big_red/bigredcargoareavar3.dmm
  _maps/modularmaps/big_red/bigredcargoareavar4.dmm
  _maps/modularmaps/big_red/bigredcargoareavar5.dmm
  _maps/modularmaps/big_red/bigredcargoareavar6.dmm
  _maps/modularmaps/big_red/bigredsecornervar6.dmm
  _maps/modularmaps/lv624/cargo_bay2.dmm
  _maps/shuttles/big_ert.dmm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/reagent_dispensers.dm
Labels: Balance, Map Edit, Test Merge Candidate

#11527 Mech UI minor rework
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
  tgui/packages/tgui/interfaces/MechVendor/MechAssembly.tsx
  tgui/packages/tgui/interfaces/MechVendor/MechWeapons.tsx
  tgui/packages/tgui/interfaces/MechVendor/data.ts
  tgui/packages/tgui/interfaces/MechVendor/index.tsx
Labels: Fix, UI, Quality of Life

#11554 Adds a hotkey for place acid well
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Feature

#11571 Hull window update
  icons/obj/structures/window_frames.dmi
  icons/obj/structures/windows.dmi
  icons/turf/mainshipwalls.dmi
  icons/turf/walls.dmi
Labels: Sprites

#11588 Minor PoS renovation
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Removal, Map Edit, Feature

#11589 Change Widow's minimap sprite
  icons/UI_Icons/map_blips.dmi
Labels: Sprites

#11587 increase widow leash ball hp
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
Labels: Balance

#11583 Spiderlings ain't no bitches
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
Labels: Feature

#11546 Fatty Rework 2.0 (Cluster strikes back!)
  code/game/objects/structures/dropship_ammo.dm
Labels: Balance, Test Merge Candidate

#11584 Fix hardpoint issue
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#11582 Adds Labellers to weapons vendor
  code/game/objects/items/tools/misc_tools.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#11569 Reqtorio Expansion V 1.1
  code/__DEFINES/factory.dm
  code/modules/factory/machines.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/factory/factory_machines.dmi
  tgmc.dme
Labels: Sprites, Feature

#11597 Miner layer fix
  code/game/objects/machinery/miner.dm
Labels: Fix

#11586 Particle editor port
  code/__DEFINES/generators.dm
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/generators.dm
  code/_compile_options.dm
  code/datums/status_effects/xeno_buffs.dm
  code/game/atoms_movable.dm
  code/modules/admin/holder.dm
  code/modules/admin/verbs/datumvars.dm
  code/modules/admin/view_variables/particle_editor.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  dependencies.sh
  icons/UI_Icons/particle_editor/box_gen.png
  icons/UI_Icons/particle_editor/circle_gen.png
  icons/UI_Icons/particle_editor/cube_gen.png
  icons/UI_Icons/particle_editor/linear_rand.png
  icons/UI_Icons/particle_editor/motion.png
  icons/UI_Icons/particle_editor/normal_rand.png
  icons/UI_Icons/particle_editor/num_gen.png
  icons/UI_Icons/particle_editor/sphere_gen.png
  icons/UI_Icons/particle_editor/square_gen.png
  icons/UI_Icons/particle_editor/square_rand.png
  icons/UI_Icons/particle_editor/uniform_rand.png
  icons/UI_Icons/particle_editor/vector_gen.png
  tgmc.dme
  tgui/packages/tgui/interfaces/ParticleEdit/EntriesBasic.tsx
  tgui/packages/tgui/interfaces/ParticleEdit/EntriesGenerators.tsx
  tgui/packages/tgui/interfaces/ParticleEdit/Generators.tsx
  tgui/packages/tgui/interfaces/ParticleEdit/Tutorial.tsx
  tgui/packages/tgui/interfaces/ParticleEdit/data.ts
  tgui/packages/tgui/interfaces/ParticleEdit/helpers.ts
  tgui/packages/tgui/interfaces/ParticleEdit/index.tsx
Labels: Sprites, Administration, UI

#11599 Revolver changes
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#11611 Weyland Yutani Removal
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/modularmaps/big_red/operation.dmm
  code/modules/economy/ATM.dm
Labels: Fix, Map Edit

#11612 Make Queen time lock actually work
  code/datums/jobs/job/xenomorph.dm
Labels: Fix

#11596 Resin Doors have custom ex_acts now
  code/game/objects/structures/xeno.dm
Labels: Balance

#11529 Carrier new ability: Call of younger
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/xeno.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  icons/mob/actions.dmi
  icons/mob/hud.dmi
Labels: Sprites, Feature

#11600 Fix packet of .45-70's sprite
  code/modules/projectiles/magazines/misc.dm
  icons/obj/items/ammo.dmi
Labels: Sprites, Fix

#11614 Hivemind now passes through all mobs.
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
Labels: Balance

#11620 Removes Icarus Military Port
  _maps/icarus_military_port.json
  _maps/map_files/Icarus_Military_Port/icarus_military_port.dmm
  code/game/area/icarus.dm
  config/maps.txt
  tgmc.dme
Labels: Config Update, Map Edit

#11558 Slugcat sentience
  code/__DEFINES/dcs/signals.dm
  code/datums/components/companion.dm
  code/game/objects/items/tools/research_tools.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/friendly/catslug.dm
  tgmc.dme
Labels: Feature

#11628 Queen timer fix 2.0
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/job.dm
Labels: Fix

#11617 Turf smoothing for shuttles
  code/game/smoothwall.dm
  code/game/turfs/closed.dm
  code/modules/shuttle/shuttle_rotate.dm
Labels: Fix

#11615 Railing smoothing removal
  code/game/objects/machinery/doors/railing.dm
Labels: Fix

#11593 SADAR Changes, added 'Unguided' HE/WP rocket types, Reworked AP-2
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance, Test Merge Candidate

#11629 port tg smartpipes for mapping
  code/modules/atmospherics/machinery/pipes/mapping.dm
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
Labels: Sprites, Feature

#11619 Removes dupe TGMC uniform from Clothing vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal

#11549 Vali visuals
  code/__DEFINES/dcs/signals.dm
  code/datums/components/chem_booster.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites, Balance

#11475 Magmoor Digsite IV Rework | Justice for the Lavaplanet™
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  code/game/area/magmoor_digsite.dm
  code/game/objects/machinery/doors/multi_tile.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/platforms.dm
  code/game/turfs/closed.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
Labels: Removal, Map Edit, Feature

#11592 Spiderling death anim
  icons/Xeno/Effects.dmi
Labels: Sprites

#11635 Hot Foods and Drink vendors now have an infinite supply of foods and drinks.
  code/game/objects/machinery/vending/vending_types.dm
Labels: Balance

#11621 Implements aghosts new sprites
  icons/Xeno/1x1building.dmi
  icons/Xeno/Effects.dmi
  icons/Xeno/resin_silo.dmi
  icons/obj/doors/1x4blast_hor.dmi
  icons/obj/doors/1x4blast_hor_secure.dmi
  icons/obj/doors/icecolony.dmi
  icons/obj/structures/windows.dmi
Labels: Sprites

#11622 MMG sprites
  code/modules/projectiles/guns/mounted.dm
  icons/Marine/marine-mmg.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
Labels: Sprites

#11638 Vali bugfix
  code/datums/components/chem_booster.dm
Labels: Fix

#11580 Widow Spiderling QoL + Old Signal Cleanup
  code/__DEFINES/dcs/signals.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
  code/modules/projectiles/sentries.dm
  code/modules/vehicles/multitile/cm_armored.dm
Labels: Balance, Fix, Quality of Life

#11627 Rownin Skeleton and removal of chosing M3 harness
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/modular_armor.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Sprites, Feature

#11641 fix: maptable for observers
  code/game/objects/machinery/cic_maptable.dm
Labels: Fix
