Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2022-04, with the labels that each got.

#9874 Fix outfit variants 2: electric boogaloo
  code/datums/jobs/job/job.dm
Labels: Fix

#9865 fix tx-11 mob sprite
  icons/mob/items_righthand_1.dmi
Labels: Sprites, Fix

#9860 Greyscale support for projectiles and bullets - greyscale for TX-54 ammo
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/ammo.json
  code/datums/greyscale/json_configs/projectiles.json
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/projectile.dm
  icons/obj/items/ammo.dmi
  icons/obj/items/projectiles.dmi
  tgmc.dme
Labels: Sprites, Code Improvement, Mechanic

#9819 Jones Gets Sturdy
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Mechanic, Waiting for PL approval

#9863 Nerf conveyor belt from 500 integrity to 50
  code/modules/recycling/conveyor2.dm
Labels: Balance/Rebalance, Fix

#9788 Removes the false illusion that the FC has a special headband
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Removal

#9862 Crusher unique explosion handler removal
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
Labels: Code Improvement, Balance/Rebalance

#9829 Riot gear and stuff
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/head_1.dmi
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Sprites, Balance/Rebalance, Mechanic

#9878 Fix xeno ex_act severity math hack
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Fix

#9873 Defenders can now parry thrown attacks with tail-abilities
  code/__DEFINES/dcs/signals.dm
  code/datums/components/throw_parry.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/living_helpers.dm
  tgmc.dme
Labels: Mechanic

#9871 Fix crusher rapid advance forcing 8 directions
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Fix

#9890 Add xeno overheal amount to the status panel
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Mechanic

#9893 Bugfix - adds CIC and CAS eye icons, like AI's
  icons/mob/cameramob.dmi
Labels: Sprites, Fix

#9888 Undo Crusher bomb immunity removal with numbers
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Labels: Balance/Rebalance

#9851 Cas tsx and new hotkeys
  code/modules/shuttle/cas_plane.dm
  tgui/packages/tgui/interfaces/MarineCasship.tsx
Labels: Refactor, UI, Quality of Life

#9776 update atomns init
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/atoms.dm
  code/game/atoms.dm
  code/game/objects/effects/spawners/modularmappingspawner.dm
  tools/read_init_times.py
Labels: Tools, Test Merge Candidate

#9882 Icy caves crash fixes & adjustments
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Balance/Rebalance, Map Edit

#9884 Plasma pistol is no longer an attachment, slight buff to compensate
  code/datums/components/attachment_handler.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance/Rebalance

#9894 Scope vision + offset now resets properly when ghosting/on death
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/living.dm
Labels: Fix

#9918 Remove plasma pistol from T25
  code/modules/projectiles/guns/rifles.dm
Labels: Balance/Rebalance

#9910 APCR changes, and AT Gun anchorablity
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/mounted.dm
Labels: Balance/Rebalance, Quality of Life

#9907 Removes blink debuff when wraith is in phase shift
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Removal, Balance/Rebalance

#9904 Removes Eyeblur from Blink
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Balance/Rebalance

#9906 Resolves some Defender action issues
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
Labels: Fix

#9942 Triples damage from guns/acid spit and xeno melee
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance

#9943 Revert "Triples damage from guns/acid spit and xeno melee"
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/projectiles/projectile.dm
Labels: Revert

#9913 tsx sentries
  tgui/packages/tgui/interfaces/Sentry.tsx
Labels: UI

#9935 Add clarification on ctrl-click desc by telling players to ctrl-click on tile
  code/modules/projectiles/gun_system.dm
Labels: Quality of Life

#9925 Makes missing limbs bleed
  code/modules/mob/living/blood.dm
Labels: Fix

#9931 Fixes an old Synthetic name system.
  code/modules/client/preferences.dm
Labels: Fix

#9933 Fires hiveminds being unable to return to core if in a wall
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
Labels: Fix

#9927 mini pepperball magazines should fit in pistol pouches the second
  code/game/objects/items/storage/pouch.dm
Labels: Balance/Rebalance

#9824 Tesla gun rebalance
  code/datums/beam.dm
  code/datums/status_effects/debuffs.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
Labels: Balance/Rebalance, Test Merge Candidate

#9929 Buff: Reduce required sheet to upgrade metal barricade from 2 to 1
  code/game/objects/structures/barricade.dm
Labels: Balance/Rebalance

#9930 Add xeno crit health hud
  code/game/data_huds.dm
  icons/mob/hud.dmi
Labels: Sprites, Quality of Life

#9761 Porting CM 2x1 & glass door sprites and del some posters
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/game/objects/machinery/doors/airlock_types.dm
  code/game/objects/machinery/doors/multi_tile.dm
  icons/obj/doors/mainship/2x1almayerdoor.dmi
  icons/obj/doors/mainship/2x1almayerdoor_glass.dmi
  icons/obj/doors/mainship/2x1engidoor.dmi
  icons/obj/doors/mainship/2x1engidoor_glass.dmi
  icons/obj/doors/mainship/2x1prepdoor.dmi
  icons/obj/doors/mainship/2x1prepdoor_alpha.dmi
  icons/obj/doors/mainship/2x1prepdoor_bravo.dmi
  icons/obj/doors/mainship/2x1prepdoor_charlie.dmi
  icons/obj/doors/mainship/2x1prepdoor_delta.dmi
  icons/obj/doors/mainship/2x1secdoor.dmi
  icons/obj/doors/mainship/2x1secdoor_glass.dmi
  icons/obj/doors/mainship/engidoor_glass.dmi
  icons/obj/doors/mainship/personaldoor_glass.dmi
Labels: Sprites, Map Edit, Test Merge Candidate

#9914 tsx droppod control
  tgui/packages/tgui/interfaces/DroppodControl.tsx
Labels: UI

#9915 TSX droppods
  tgui/packages/tgui/interfaces/Droppod.tsx
Labels: UI

#9917 Alternate quick equip hotkey
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/equipment.dm
  code/datums/keybinding/human.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: UI, Quality of Life

#9833 Adds the M40 Adhesive grenade
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  icons/obj/items/grenade.dmi
Labels: Sprites, Test Merge Candidate, Mechanic

#9936 Some deployable weapon updates
  code/datums/elements/deployable_item.dm
  code/game/objects/items.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/mounted.dm
Labels: Fix, Quality of Life

#9947 Preweeds Chigusa + minor changes and fixes
  _maps/map_files/desertdam/desertdam.dmm
Labels: Balance/Rebalance, Fix, Map Edit

#9924 Modular holsters - Allows rocket bag to visually hold the RR
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/large_holster.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/gimmick.dm
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/species/robot/backpack.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/storage/storage.dmi
  tgmc.dme
Labels: Sprites, Balance/Rebalance, Refactor, Fix, Mechanic

#8932 Icarus Shipyard. (New map)
  _maps/icarus_military_port.json
  _maps/map_files/Icarus_Military_Port/icarus_military_port.dmm
  config/maps.txt
Labels: Config Update, Stale, Map Edit, Mechanic

#9964 Tesla IFF mode
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/reqs/supplypacks.dm
Labels: Code Improvement, Mechanic

#9967 Hot fix quick draw being inversed with alternate
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Test Merge Candidate

#9940 Teleporter buff cooldown
  code/game/objects/structures/teleporter.dm
Labels: Balance/Rebalance

#9923 Remove some posters as ordered by Tivi
  code/game/objects/effects/decals/posters/bs12.dm
  icons/obj/contraband.dmi
Labels: Sprites, Removal

#9928 Ports TG's drop and pickup animations
  code/game/objects/items.dm
  code/modules/mob/inventory.dm
Labels: Mechanic

#9962 Fix TE power cell drain bug
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#9954 Make mounted gun integrity consistent
  code/modules/projectiles/guns/mounted.dm
Labels: Balance/Rebalance

#9958 update AT gun desc on how to anchor
  code/modules/projectiles/guns/mounted.dm
Labels: Quality of Life

#9905 Change xeno bomb armor to usual soft armor
  code/__DEFINES/conflict.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Removal, Balance/Rebalance, Mechanic

#9963 researcher spawns with tweezers in his bag
  code/datums/jobs/job/shipside.dm
Labels: Balance/Rebalance, Quality of Life

#9916 Fix BR runtimes and map load loops
  code/__DEFINES/_subsystems.dm
  code/controllers/subsystem/modularmapping.dm
  code/game/objects/effects/spawners/modularmappingspawner.dm
  code/modules/unit_tests/map_templates.dm
  tgmc.dme
Labels: Fix, Test Merge Candidate

#9966 Fixes numerous Icarus bugs, gives Icarus its own unique areas
  _maps/map_files/Icarus_Military_Port/icarus_military_port.dmm
  code/game/area/icarus.dm
  tgmc.dme
Labels: Code Improvement, Fix, Map Edit

#9965 You only need to wait 1 minute before taking another minions/ssd mob
  code/__DEFINES/mode.dm
Labels: Balance/Rebalance

#9968 bandages heal more, but take longer to use
  code/game/objects/items/stacks/medical.dm
Labels: Balance/Rebalance

#9980 Revert "bandages heal more, but take longer to use"
  code/game/objects/items/stacks/medical.dm
Labels: Revert

#9934 Late Synthetics now look better.
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Sprites, Removal, Content Expansion

#9972 Updates LV medbay variant 2.
  _maps/modularmaps/lv624/medbaytwo.dmm
Labels: Fix, Map Edit

#9951 Give Hivemind Transfer Plasma
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
Labels: Balance/Rebalance, Mechanic

#9897 Wraith fixes
  code/__HELPERS/math.dm
  code/game/objects/structures/window.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/shuttle/mini_dropship.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix, Test Merge Candidate

#9892 TGUI preferences should save properly i guess
  code/modules/client/preferences_savefile.dm
Labels: Fix

#9953 T-25/29 changes- Same bullet between both of them, stat changes for T-25
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/obj/items/ammo.dmi
Labels: Sprites, Balance/Rebalance

#9955 tp23 sprite update
  icons/obj/items/gun.dmi
Labels: Sprites

#9987 Recoilless Rifle Quality of Life change
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
Labels: Quality of Life

#9978 Update teleporter desc
  code/game/objects/structures/teleporter.dm
Labels: Mechanic

#9992 Make the gender option more clear on what they do
  tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx
Labels: UI, Quality of Life

#9950 update xeno UI
  icons/mob/hud.dmi
Labels: Sprites, Test Merge Candidate, Mechanic

#9997 Revert "Splints work as tourniquets"
  code/game/objects/items/stacks/medical.dm
  code/modules/mob/living/blood.dm
  code/modules/organs/limbs.dm
Labels: Revert

#10001 Adds a new ALTERNATE set of antenna gear to TGMC.
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites, Mechanic

#10002 Revert "Adds a new ALTERNATE set of antenna gear to TGMC."
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites, Revert

#9996 Fix t-25 ammo packet not working
  code/modules/projectiles/magazines/misc.dm
Labels: Fix

#9993 Fix night vision scope offset
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/living.dm
Labels: Fix

#9960 Refactors energy weapon magazines to use overlays
  code/game/objects/items/power_cells.dm
  code/modules/power/cell.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/magazines/energy.dm
  icons/obj/items/ammo.dmi
  icons/obj/power.dmi
Labels: Sprites, Fix

#10013 Removes hostile mobs from Icarus
  _maps/map_files/Icarus_Military_Port/icarus_military_port.dmm
Labels: Removal, Balance/Rebalance, Map Edit

#9994 2x1 doorifying Prison (+ 2x1 maint doors for it)
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/game/objects/machinery/doors/multi_tile.dm
  icons/obj/doors/mainship/2x1maintdoor.dmi
Labels: Sprites, Balance/Rebalance, Map Edit, Mechanic

#9975 Fix ai runtime
  code/datums/components/ai.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/xeno/xeno.dm
Labels: Test Merge Candidate

#10003 Change Minerva's Req, CAS armament area, and add Briefing Area
  _maps/map_files/Minerva/TGS_Minerva.dmm
Labels: Map Edit

#9998 Remove bleeding from missing limbs
  code/modules/mob/living/blood.dm
Labels: Removal

#10005 Pillar of Spring's Remapping: Changing Req, PO, Hanger, and Medical, then adding bar and memorial
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit

#9976 Fix abilities being doubled on hunter and hivelord primo
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Fix

#9999 Remove rear attachment port in Icarus LZ2
  _maps/map_files/Icarus_Military_Port/icarus_military_port.dmm
Labels: Removal, Map Edit

#9988 Darker wisp
  icons/mob/human_face.dmi
Labels: Sprites

#9974 Makes the shipside NanoTrasenMed and MarineMed have unlimited splints
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Balance/Rebalance

#10016 fix container height
  code/game/objects/structures/cargo_container.dm
Labels: Fix

#9995 Refurbishes thunderdome
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/camera/camera.dm
  icons/obj/stationobjs.dmi
Labels: Sprites, Map Edit, Administration

#10012 Reworks TE cell sprite and overlay.
  icons/obj/items/ammo.dmi
Labels: Sprites, Quality of Life

#10022 ports cm vehicle sprites reworked
  _maps/map_files/desertdam/desertdam.dmm
  code/game/objects/structures/prop.dm
  icons/obj/structures/vehicles.dmi
Labels: Sprites, Map Edit, Mechanic

#10036 Simultaneous deployable reload fix
  code/__DEFINES/traits.dm
  code/modules/projectiles/mounted.dm
Labels: Fix

#10028 Robotic Limbs no longer get shrap
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance

#8042 Yet more Sulaco QOL
  _maps/map_files/Sulaco/Sulaco.dmm
  code/game/area/sulaco.dm
  code/game/objects/machinery/telecomms/machines/broadcaster.dm
  code/game/objects/machinery/telecomms/machines/bus.dm
  code/game/objects/machinery/telecomms/machines/hub.dm
  code/game/objects/machinery/telecomms/machines/processor.dm
  code/game/objects/machinery/telecomms/machines/receiver.dm
  code/game/objects/machinery/telecomms/machines/relay.dm
  code/game/objects/machinery/telecomms/machines/server.dm
  code/game/objects/structures/window.dm
  code/game/turfs/walls/wall_types.dm
Labels: Fix, Map Edit, Test Merge Candidate, Quality of Life

#10030 Squad Marine vendor attachment QOL
  code/__DEFINES/loadout.dm
  code/datums/loadout/loadout_helper.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Removal

#10035 No more sharpened sharpened shovel
  code/game/objects/items/tools/shovel_tools.dm
Labels: Fix

#10039 Fixes invisible windows
  icons/obj/structures/windows.dmi
Labels: Sprites, Fix

#10042 Fixes equipment vendors no longer requiring points
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Priority: High, Fix

#10033 Removes body types (Ecto, Meso, Endo)
  code/__HELPERS/global_lists.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/sanitize_values.dm
  code/_globalvars/lists/flavor_misc.dm
  code/game/objects/items.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/mob/new_player/body_type.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/organs/limb_objects.dm
  code/modules/organs/limbs.dm
  icons/mob/human_races/r_human.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx
Labels: Sprites, Removal, UI

#10017 Adds the T-100Y howitzer and rebalances the mortar, renamed mortar.
  code/game/objects/machinery/mortar.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/howitzer.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  sound/weapons/guns/fire/howitzer_fire.ogg
  sound/weapons/guns/misc/howitzer_whistle.ogg
Labels: Sprites, Sound, Code Improvement, Balance/Rebalance, Mechanic

#10047 Add two research consoles in Sulaco
  _maps/map_files/Sulaco/Sulaco.dmm
Labels: Fix, Map Edit

#10032 Plasma Cutter Change
  code/__DEFINES/objects.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/items/tools/mining_tools.dm
  code/modules/clothing/modular_armor/modular.dm
Labels: Balance/Rebalance, Test Merge Candidate

#10045 makes the AMRs scope unuseable on the move
  code/modules/projectiles/gun_attachables.dm
Labels: Balance/Rebalance

#10040 add comms to tadpole
  _maps/shuttles/minidropship.dmm
Labels: Map Edit, Mechanic

#10046 Adds 8.6x70mm ammo box / Fixes 10x26.5mm ammo box sprite
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/magazines/misc.dm
  icons/obj/items/ammo.dmi
Labels: Sprites, Code Improvement, Fix, Mechanic

#10031 Refactors gun icon/item code
  code/__DEFINES/conflict.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/smgs.dm
  icons/Marine/gun64.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Sprites, Refactor, Fix

#10058 Add a Cancel button to the hotkey "Say" input
  code/modules/mob/typing_indicator.dm
Labels: Quality of Life

#10038 Adjust layer order for mob item rendering
  code/__DEFINES/mobs.dm
Labels: Code Improvement

#10052 T-26 Slowdown remove
  code/__DEFINES/conflict.dm
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance

#10068 TAT tweaks
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance, Feature

#10070 ANFO fix
  code/modules/reagents/reactions/other.dm
Labels: Fix

#10074 fix defib fumble time
  code/game/objects/items/defibrillator.dm
Labels: Fix

#10043 Expansion of PoS: Req change 2.0, Bigger Bar, 2x1 maint doors, medbay remap, maint hall in bow, and Condor's hazard signs
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Mechanic, Content Expansion

#10071 SOM reloaded
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/jobs/job/sonsofmars.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/modular_armor/attachments/chestplates.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/under.dm
  code/modules/power/cell.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/energy.dm
  icons/Marine/gun64.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/modular/m10.dmi
  icons/mob/modular/modular_armor.dmi
  icons/mob/suit_slot.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/storage/storage.dmi
  sound/weapons/guns/fire/volkite_1.ogg
  sound/weapons/guns/fire/volkite_2.ogg
  sound/weapons/guns/fire/volkite_3.ogg
  sound/weapons/guns/fire/volkite_4.ogg
  sound/weapons/guns/interact/volkite_reload.ogg
  sound/weapons/guns/interact/volkite_unload.ogg
  sound/weapons/guns/misc/error.ogg
Labels: Sprites, Sound, Balance/Rebalance, Fix, Feature

#10083 Fixes robo heads not being reattachable
  code/modules/surgery/headreattach.dm
Labels: Fix

#10082 Fix implants being removable
  code/game/objects/items/scanners.dm
Labels: Fix

#10073 Human sprite very smoll fix
  icons/mob/human_races/r_human.dmi
Labels: Sprites, Removal

#10008 Boxing+
  code/_onclick/item_attack.dm
  code/game/objects/structures/crates_lockers/closets/fitness.dm
  code/modules/clothing/gloves/miscellaneous.dm
  icons/obj/clothing/boxing.dmi
  icons/obj/clothing/gloves.dmi
  sound/effects/knockout.ogg
Labels: Sprites, Sound, Mechanic

#10092 Headband resprite
  icons/mob/head_1.dmi
Labels: Sprites
