Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2023-12, with the labels that each got.

#14536 Fixes some minimap dnr issues
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/projectiles/gun_system.dm
Labels: Fix

#14547 removes rds compatibility with mg60
  code/modules/projectiles/guns/rifles.dm
Labels: Removal, Balance

#14576 Autoweed fix
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#14577 fixes the base yellow color
  code/__DEFINES/modular_armor.dm
Labels: Fix

#14571 Fix grammar in human examine text
  code/modules/mob/living/carbon/human/examine.dm
Labels: Fix

#14510 some shotguns get underbarreled flashlight
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance, Feature

#14581 Fix a funny widow exploit
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
Labels: Fix, In Game Exploit

#14583 Makes the two tile pod door (namely used on big red) acidable
  code/game/objects/machinery/doors/poddoor.dm
Labels: Balance

#14578 CAS ordnance travelling times are no longer affected by spaceship orbit
  code/game/objects/structures/dropship_equipment.dm
Labels: Balance

#14579 Clarifies AI Bioscan Corruption Is Affected By Ship Elevation
  code/datums/gamemodes/infestation.dm
Labels: Grammar and Formatting

#14552 Makes standard marine vendors unwrenchable
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance

#14207 the Syndicate expansion part one (allegedly)
  code/__DEFINES/attachments.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/greyscale_guns.dm
  code/__DEFINES/loadout_variants.dm
  code/__DEFINES/modular_armor.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/exoskeleton.json
  code/datums/greyscale/json_configs/hardsuit_variant.json
  code/datums/greyscale/json_configs/visors.json
  code/game/objects/items.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/arm_plates.dm
  code/modules/clothing/modular_armor/attachments/chest_plates.dm
  code/modules/clothing/modular_armor/attachments/leg_plates.dm
  code/modules/clothing/modular_armor/attachments/secondary_color.dm
  code/modules/clothing/modular_armor/attachments/visors.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/syndicate_hardsuits.dmi
  icons/mob/modular/visors.dmi
  tgmc.dme
Labels: Sprites, UI

#14512 Skill adjustments and additions
  code/__DEFINES/skills.dm
  code/_onclick/item_attack.dm
  code/datums/jobs/job/job.dm
  code/datums/skills.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun_system.dm
Labels: Balance, Stale, Feature

#14590 Fix defender being able to move dead bodies
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Fix

#14586 Mech entry fix
  code/modules/vehicles/sealed.dm
Labels: Fix

#14310 Squad transfer tablet
  code/game/objects/items/devices/squad_transfer_tablet.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/SquadTransfer.tsx
Labels: Stale, Feature, UI

#14553 Add queen egg laying back
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
Labels: Balance

#14597 Deletes some rogue commas
  code/datums/jobs/access.dm
  code/game/objects/items.dm
  code/game/objects/items/reagent_containers/food/donuts.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/structures/girders.dm
  code/modules/admin/verbs/legacy.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/head/helmet.dm
  code/modules/language/sectoid.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/surgery/eye.dm
  code/modules/surgery/generic.dm
  code/modules/vehicles/mecha/mech_bay.dm
Labels: Code Improvement

#14602 increases the range of sg153 bullets to 40 from 20
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#14604 C4 (Plastique Explosives) No Longer Require A Multitool To Disarm
  code/game/objects/items/explosives/plastique.dm
Labels: Balance

#14596 The Antenna module now improves comms in caves, loses req beacon
  code/__DEFINES/conflict.dm
  code/__DEFINES/dcs/signals.dm
  code/game/objects/items/radio/radio.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Balance

#14612 Kill get_contents
  code/modules/admin/debug_verbs.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
Labels: Code Improvement

#14607 Changes Hypo Hypervene Acronym to Hy
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Grammar and Formatting

#14606 Slightly reduces the cheese level of Wraiths
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Balance

#14595 Warlock Psycrush nerf
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Balance

#14593 warlock psyblast nerf
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Balance

#14613 Deletes unused hud defines and cyborg.dmi
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  icons/mob/screen/cyborg.dmi
Labels: Sprites, Code Improvement

#14617 Fixes spiderlings not continuing their attack
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
Labels: Fix

#14614 Orders Show Job Title of Order Sender
  code/modules/screen_alert/command_alert.dm
Labels: Feature

#14610 fixes mountbatten pink: the squeakel
  code/__DEFINES/modular_armor.dm
Labels: Fix

#14619 Add a chat reliability layer
  code/__DEFINES/chat.dm
  code/controllers/subsystem/chat.dm
  code/datums/chat_payload.dm
  code/modules/tgchat/README.md
  code/modules/tgchat/to_chat.dm
  code/modules/tgui/tgui_window.dm
  tgmc.dme
  tgui/packages/tgui-panel/chat/middleware.js
Labels: UI

#14621 Snatch now spends plasma only on success.
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Fix

#14605 Sectoids reloaded - Just probing edition
  code/__DEFINES/actions.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/keybind.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/datums/actions/ability_actions.dm
  code/datums/actions/species_actions/sectoid_action.dm
  code/datums/emergency_calls/sectoid.dm
  code/datums/jobs/job/sectoid.dm
  code/datums/keybinding/sectoid.dm
  code/datums/status_effects/sectoid.dm
  code/game/atoms.dm
  code/game/data_huds.dm
  code/game/objects/items/radio/headset.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/living_health_procs.dm
  icons/Xeno/actions.dmi
  icons/effects/64x64.dmi
  icons/mob/psionic_icons.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
Labels: Sprites, Balance, Feature, UI

#14626 Drop pod orbit adjustments
  code/game/objects/structures/droppod.dm
Labels: Balance

#14620 Time shift now rewinds fire_stacks and on_fire.
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Feature

#14630 Skirmish Rifle buff, 30->40 mag cap
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance

#14640 Fixes antenna
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Fix

#14628 Pizza doesn't net cas points anymore
  code/modules/requisitions/supply_export.dm
Labels: Removal

#14639 Rebinds unique action to C by default (instead of space)
  code/datums/keybinding/human.dm
Labels: Quality of Life

#14648 Fix wrong 515 regex
  code/__HELPERS/unsorted.dm
Labels: Code Improvement

#14646 Fix earlyadd minimap icons not showing up on minimap
  code/controllers/subsystem/minimaps.dm
Labels: Fix

#14649 Base rescue mission time tweaks
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/game/objects/machinery/computer/nt_access.dm
Labels: Balance

#14650 Campaign mission end ghostize
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/game/objects/machinery/computer/nt_access.dm
Labels: Balance

#14642 Allows ai to ping alert the baneling pod.
  code/_onclick/ai.dm
Labels: Feature

#14654 Fix a supply beacon runtime
  code/game/objects/machinery/squad_supply/supply_beacon.dm
Labels: Fix

#14655 Fix export denied personal stat
  code/datums/personal_statistics.dm
Labels: Fix

#14656 Follow up mission end QOL
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Quality of Life

#14658 Campaign BSOD fix
  tgui/packages/tgui/interfaces/CampaignMenu/index.tsx
Labels: Fix, UI

#12892 Adds a delay to throwing
  code/__DEFINES/conflict.dm
  code/_onclick/click.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/modules/mob/living/carbon/carbon.dm
Labels: Balance, Stale

#14661 Campaign combat robo tweaks
  code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
Labels: Balance

#14660 Misc gun skilltype changes
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#14659 Defensive mission walance
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  code/datums/gamemodes/campaign/missions/asat_capture.dm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/game/objects/structures/campaign_structures/misc_structures.dm
  tgmc.dme
Labels: Balance, Map Edit

#14651 Emplacements may be hopped over
  code/modules/projectiles/mounted.dm
  code/modules/projectiles/sentries.dm
Labels: Balance

#14662 Makes sticky resin unacidable
  code/game/objects/structures/xeno.dm
Labels: Fix

#14644 Deletes some garbage on big red.
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/modularmaps/big_red/bigredsouthwestetavar4.dmm
Labels: Fix, Map Edit

#14643 Deletes stacking pipes on Ice Caves.
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Map Edit

#14667 updates this stupid shrike comment
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Code Improvement

#14672 Adds packets to Target Rifle
  code/__DEFINES/loadout.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/ammo.dmi
Labels: Sprites, Feature

#14676 Adds voicelines to CAS
  code/__DEFINES/cas.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  code/modules/condor/cas_chair.dm
  code/modules/condor/cas_shuttle.dm
  sound/voice/plane_vws/ammunition_zero.ogg
  sound/voice/plane_vws/flightcomputer_hot.ogg
  sound/voice/plane_vws/low_fuel.ogg
  sound/voice/plane_vws/no_fuel.ogg
  sound/voice/plane_vws/shot_flare.ogg
  sound/voice/plane_vws/shot_missile.ogg
Labels: Sound, Feature

#14675 Removes the magnum from the crash weapons vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal, Fix

#14665 Fix items being weird with layers if equipped is overriden the wrong way
  code/modules/mob/inventory.dm
Labels: Fix

#14683 kills 4 cape styles and style jaeger
  code/__DEFINES/loadout_variants.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/cape.json
  code/datums/greyscale/json_configs/cape_highlight.json
  code/datums/greyscale/json_configs/visors.json
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/arm_plates.dm
  code/modules/clothing/modular_armor/attachments/cape.dm
  code/modules/clothing/modular_armor/attachments/chest_plates.dm
  code/modules/clothing/modular_armor/attachments/leg_plates.dm
  code/modules/clothing/modular_armor/attachments/visors.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/capes.dmi
  icons/mob/modular/capes_highlight.dmi
  icons/mob/modular/mark_one/dashe.dmi
  icons/mob/modular/mark_one/hotaru.dmi
  icons/mob/modular/mark_one/kabuto.dmi
  icons/mob/modular/mark_two/hotaru.dmi
Labels: Sprites, Removal

#14674 Fixes SG-62 reqtorio
  code/modules/reqs/supplypacks.dm
Labels: Fix

#14682 Fix emote spam when losing grasp of NODROP items
  code/modules/organs/limbs.dm
Labels: Fix

#14686 Adds an ozelomelyn hugger
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/projectiles/ammo_datums.dm
  icons/Xeno/actions.dmi
Labels: Sprites, Feature

#14684 Updates The Bottle of Docter's Delight's Description And Moves It To The Valhalla Tab
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Grammar and Formatting

#14664 Changes Layer of Rear Attach Points.
  code/game/objects/structures/dropship_equipment.dm
Labels: Quality of Life

#14637 Daedalus Prison
  _maps/_basemap.dm
  _maps/daedalusprison.json
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  code/game/area/daedalusprison.dm
  code/game/objects/structures/platforms.dm
  config/maps.txt
  tgmc.dme
Labels: Config Update, Map Edit, Feature

#14499 Remove HSG nest from canter + some canter maintenance
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
Labels: Balance, Map Edit, Quality of Life

#14482 Standardizes OB rooms on all shipmaps
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Do Not Merge, Balance, Map Edit

#14669 Campaign: drop pod refresh fixes
  _maps/map_files/Iteron/Iteron.dmm
  code/game/objects/structures/droppod.dm
Labels: Fix, Map Edit

#14261 Adds Beginner loadouts.
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/__DEFINES/equipment.dm
  code/__DEFINES/loadout.dm
  code/_globalvars/bitfields.dm
  code/datums/quick_load_beginners.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/machinery/vending/beginner_vendor.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/paperwork/beginner_tutorials.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/obj/machines/vending.dmi
  tgmc.dme
Labels: Sprites, Map Edit, Feature, Test Merge Candidate

#14258 Reverts Hyperscale 3
  code/datums/components/attachment_handler.dm
  code/datums/greyscale/_greyscale_config.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/attachments.json
  code/datums/greyscale/json_configs/attachments_64.json
  code/datums/greyscale/json_configs/gun.json
  code/datums/greyscale/json_configs/gun_fire.json
  code/datums/greyscale/json_configs/gun_hands.json
  code/datums/greyscale/json_configs/gun_mob.json
  code/datums/greyscale/json_configs/gun_revolver.json
  code/datums/greyscale/json_configs/gun_shotgun.json
  code/game/objects/items.dm
  code/game/objects/items/storage/holsters.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  icons/Marine/attachments_64.dmi
  icons/Marine/greyscale_gun/attachments.dmi
  icons/Marine/greyscale_gun/attachments_64.dmi
  icons/Marine/greyscale_gun/back.dmi
  icons/Marine/greyscale_gun/gun.dmi
  icons/Marine/greyscale_gun/gun_64.dmi
  icons/Marine/greyscale_gun/l_hand.dmi
  icons/Marine/greyscale_gun/l_hand_64.dmi
  icons/Marine/greyscale_gun/r_hand.dmi
  icons/Marine/greyscale_gun/r_hand_64.dmi
  icons/Marine/greyscale_gun/suit.dmi
  icons/Marine/marine-weapons.dmi
  tgmc.dme
Labels: Sprites, Removal, Revert, Test Merge Candidate

#14692 lets scorpion be given plasma + can now weak acid items
  code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
Labels: Feature

#14698 You don't fall over from a broken leg if buckled anymore
  code/modules/mob/living/carbon/human/life/handle_organs.dm
Labels: Fix

#14699 Yet another export fix
  code/modules/requisitions/supply_export.dm
Labels: Fix

#14700 Fixes the sg-85 ammo bin missing from req and adds it's powerpack to req
  code/modules/reqs/supplypacks.dm
Labels: Fix, Feature

#14702 Cleans up imperial guardsman ert code.
  code/datums/jobs/job/imperium.dm
  icons/mob/clothing/suits/ert_suits.dmi
  icons/obj/clothing/suits/ert_suits.dmi
Labels: Sprites, Fix

#14706 Fixes flat door icons
  code/game/objects/structures/mineral_doors.dm
Labels: Fix

#14694 Removes the delay from mantis swipe + they can be given plasma now
  code/modules/mob/living/carbon/xenomorph/castes/mantis/abilities_mantis.dm
  code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
Labels: Removal, Balance, Quality of Life

#14707 Makes FC worth as much larva points as a marine, removes unused specalist define
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
Labels: Removal, Balance

#14629 Hardsuit Loadout Colour not being saved fix
  code/__DEFINES/attachments.dm
  code/__DEFINES/loadout_variants.dm
  code/datums/components/attachment_handler.dm
  code/datums/loadout/item_representation/armor_representation.dm
  code/modules/clothing/modular_armor/attachments/arm_plates.dm
  code/modules/clothing/modular_armor/attachments/chest_plates.dm
  code/modules/clothing/modular_armor/attachments/leg_plates.dm
  code/modules/clothing/modular_armor/attachments/secondary_color.dm
  code/modules/clothing/modular_armor/jaeger.dm
Labels: Stale, Fix

#14710 Fix a ceiling define
  code/__DEFINES/__game.dm
Labels: Fix

#14711 Campaign Freelancer fix
  code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
Labels: Fix

#14709 Campaign ghostise fix
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Fix

#14704 More OB cinematics for shipside
  code/game/objects/structures/orbital_cannon.dm
Labels: Feature

#14708 Swapped Vali Claymore and Machete Sounds
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/twohanded.dm
Labels: Balance

#14701 Fixes bypassing nodrop with a click-drag
  code/game/objects/items/storage/storage.dm
Labels: Fix

#14712 Fixes health analyzer SSD display
  code/game/objects/items/scanners.dm
Labels: Fix

#14713 Mindmeld fix
  code/datums/status_effects/sectoid.dm
Labels: Fix

#14689 Prevents Hypo Injecting Synths And Combat Robots.
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Fix

#14714 Remove unneeded crash message
  code/datums/jobs/job/job.dm
Labels: Code Improvement

#14721 Fixes tgui CI issue
  tgui/packages/tgui/interfaces/ColorMatrixEditor.tsx
  tgui/packages/tgui/interfaces/MatrixMathTester.tsx
Labels: UI
