Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2023-06, with the labels that each got.

#12964 TGUI-ify the strip menu
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/equipment.dm
  code/__DEFINES/stripping.dm
  code/__HELPERS/pronouns.dm
  code/__HELPERS/sanitize_values.dm
  code/_globalvars/bitfields.dm
  code/_onclick/drag_drop.dm
  code/datums/elements/strippable.dm
  code/datums/loadout/loadout.dm
  code/game/objects/items.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/items/storage/internal.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/client/preferences_savefile.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/mob/living/carbon/carbon_stripping.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human_stripping.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_animal/friendly/parrot.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun_helpers.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/StripMenu.tsx
  tgui/packages/tgui/styles/interfaces/StripMenu.scss
  tgui/packages/tgui/styles/main.scss
Labels: Fix, Feature, Test Merge Candidate, UI

#13081 AI callout update
  code/__DEFINES/cooldowns.dm
  code/_onclick/ai.dm
  code/modules/mob/living/silicon/ai/ai.dm
  sound/machines/high_tech_confirm.ogg
Labels: Sound, Quality of Life

#13058 Fob Construction Improvements
  code/modules/mining/remote_fob/remote_fob_actions_misc.dm
  code/modules/mining/remote_fob/remote_fob_computer.dm
Labels: Quality of Life

#13127 Hvh loadout tweaks
  code/datums/quick_load_outfits.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/modular_armor/som.dm
  code/modules/clothing/modular_armor/xenonauten.dm
Labels: Balance

#13121 Fixes invisible blocking objects on both LZ's on Desparity
  _maps/map_files/desparity/desparity.dmm
Labels: Fix, Map Edit

#13129 Fixes attachments unloading on drop
  code/modules/projectiles/gun_system.dm
Labels: Fix

#13143 fixes a power fist exploit
  code/game/objects/items/weapons/misc.dm
Labels: Fix

#13140 Minor fixes and balance changes
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/modularmaps/EORG/basketball.dmm
  _maps/modularmaps/big_red/bigredmedbayvar1.dmm
  _maps/modularmaps/big_red/bigredmedbayvar2.dmm
  _maps/modularmaps/big_red/bigredmedbayvar3.dmm
  _maps/modularmaps/big_red/bigredmedbayvar4.dmm
  _maps/modularmaps/big_red/bigredmedbayvar5.dmm
  _maps/modularmaps/big_red/bigredmedbayvar7.dmm
  code/game/area/mainship.dm
  code/game/turfs/floor_ground.dm
  code/modules/mob/living/silicon/ai/ai.dm
  sound/machines/high_tech_confirm.ogg
Labels: Sound, Balance, Fix, Map Edit

#13135 Fix variants
  code/datums/jobs/job/job.dm
Labels: Fix, Test Merge Candidate

#13131 Makes deployables a component
  code/datums/components/deployable_item.dm
  code/game/objects/items/storage/dispenser.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/machinery/floodlight.dm
  code/game/objects/machinery/minelayer.dm
  code/game/objects/machinery/mortar.dm
  code/game/objects/structures/teleporter.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/vehicles/unmanned/deployable_vehicles.dm
  tgmc.dme
Labels: Code Improvement, Fix

#13126 Psylance vs mech tweak
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#13133 More type proc ref that was missed
  code/datums/keybinding/carbon.dm
  code/datums/keybinding/mob.dm
Labels: Code Improvement

#13109 Removes AMR bullet slowdown and laser penetration bonus
  code/__DEFINES/conflict.dm
  code/modules/projectiles/projectile.dm
Labels: Removal, Balance

#13141 Fixes hive threat reward
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#12893 Acid refactor + Acid buff against flares
  code/__DEFINES/xeno.dm
  code/game/atoms.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/objs.dm
  code/game/objects/structures.dm
  code/game/turfs/closed.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  code/game/turfs/walls/r_wall.dm
  code/game/turfs/walls/resin.dm
  code/game/turfs/walls/wall_types.dm
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/projectiles/projectile.dm
Labels: Balance, Refactor, Test Merge Candidate

#13132 gun appearance flags
  code/modules/projectiles/gun_system.dm
Labels: Fix, Test Merge Candidate

#13154 Fixes power packs not disconnecting on drop
  code/modules/projectiles/gun_system.dm
Labels: Fix

#13153 Fixes blinds permazooming you
  code/game/objects/items.dm
Labels: Fix

#13162 Fixes GL54 razor nade name in req
  code/modules/reqs/supplypacks.dm
Labels: Fix

#13151 Prevents alamo crashing from deleting mobs and AI nodes
  code/game/turfs/turf.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Balance, Fix

#13160 Makes the back slot pref actually work
  code/__DEFINES/loadout.dm
  code/__DEFINES/preferences.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Fix, Quality of Life

#13150 Misc clothing fixes
  icons/obj/clothing/suits/ert_suits.dmi
  icons/obj/clothing/uniforms/uniforms.dmi
Labels: Sprites, Fix

#13166 Boomvest fix2
  code/datums/jobs/job/clf.dm
  code/game/objects/items/explosives/bombvest.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#13165 Murders `text()`
  code/__HELPERS/text.dm
  code/__HELPERS/type2type.dm
  code/game/objects/effects/manifest.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/items/implants/implantcase.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/air_alarm.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/camera/tracking.dm
  code/game/objects/machinery/computer/medical.dm
  code/game/objects/machinery/computer/security.dm
  code/game/objects/machinery/computer/skills.dm
  code/game/objects/machinery/computer/station_alert.dm
  code/game/objects/machinery/fire_alarm.dm
  code/game/objects/machinery/igniter.dm
  code/game/objects/machinery/sleeper.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/fireaxe.dm
  code/modules/buildmode/submodes/boom.dm
  code/modules/instruments/songs/editor.dm
Labels: Code Improvement

#13152 Gives the Sulaco Medbay a map table and a shower.
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Map Edit, Feature

#13175 move Theseus' ship armaments
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit, Feature

#13182 Fixes hard armor getter proc
  code/modules/projectiles/projectile.dm
Labels: Fix

#13179 Fix gear preferences not showing the right slots
  tgui/packages/tgui/interfaces/PlayerPreferences/GearCustomisation.tsx
Labels: Fix, UI

#13169 Adds missing sprites for las pouch, and allows tesla rifle to use las pouch.
  code/modules/projectiles/guns/energy.dm
  icons/Marine/gun64.dmi
Labels: Sprites, Balance

#12995 Laser rework
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/status_effects.dm
  code/datums/quick_load_outfits.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/xeno_buffs.dm
  code/game/objects/effects/effect.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/codex/entries/guns_codex.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/rifles.dm
  icons/Marine/gun64.dmi
  icons/mob/radial.dmi
  icons/mob/screen_alert.dmi
  icons/obj/items/projectiles.dmi
  sound/weapons/guns/fire/laser_charge_up.ogg
Labels: Sprites, Sound, Code Improvement, Balance, Feature

#13194 Fixes poly TTS runtime
  code/modules/mob/living/say.dm
Labels: Fix

#13198 Fix some runtiming balloon alerts
  code/datums/status_effects/debuffs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix

#13200 Jungle walls are now unacidable.
  code/game/turfs/closed.dm
Labels: Fix

#13186 Early synth health stats differentation
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance

#13199 Fixes drone link double del
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
Labels: Fix

#13196 Fixes a hugger timer runtime
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#13195 Fixes reloading runtiming if you try to load a non magazine into a gun
  code/modules/projectiles/gun_system.dm
Labels: Fix

#13181 Adds a flag that determines if you can toggle auto unloading on a gun
  code/__DEFINES/conflict.dm
  code/_globalvars/bitfields.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#13222 Deletes the last of old legacy nanoui code
  code/__DEFINES/machines.dm
  code/modules/hydroponics/seed_machines.dm
  nano/templates/TemplatesGuide.txt
  nano/templates/accounts_terminal.tmpl
  nano/templates/botany_editor.tmpl
  nano/templates/botany_isolator.tmpl
  nano/templates/dropship_weapons_console.tmpl
  nano/templates/identification_computer.tmpl
  nano/templates/layout_basic.tmpl
  nano/templates/layout_default.tmpl
  nano/templates/layout_default_header.tmpl
  nano/templates/podlauncher.tmpl
  nano/templates/port_gen.tmpl
  nano/templates/transfer_valve.tmpl
Labels: Removal, Code Improvement

#13213 laser carbine sunder fix
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#13209 Makes deconstructing xeno structures as a xeno faster
  code/game/turfs/walls/resin.dm
Labels: Balance

#13219 Fixes hive tracker no client runtime
  code/_onclick/hud/screen_objects/screen_objects.dm
Labels: Fix

#13218 Fixes warrior punch invalid param runtime
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Fix

#13216 Fixes clamp dropship attach point runtime
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#13212 Rooba adv proc call
  code/modules/admin/holder.dm
Labels: Fix

#13136 Minimap improvement
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/modularmaps/EORG/basketball.dmm
  _maps/modularmaps/big_red/bigredcaveswvar1.dmm
  _maps/modularmaps/big_red/bigredcaveswvar2.dmm
  _maps/modularmaps/big_red/bigredcaveswvar3.dmm
  _maps/modularmaps/big_red/bigredcaveswvar4.dmm
  _maps/modularmaps/big_red/bigredcaveswvar5.dmm
  _maps/modularmaps/big_red/bigredlz2var1.dmm
  _maps/modularmaps/big_red/bigredlz2var2.dmm
  _maps/modularmaps/big_red/bigrednorthlambdavar1.dmm
  _maps/modularmaps/big_red/bigrednorthlambdavar2.dmm
  _maps/modularmaps/big_red/bigrednorthlambdavar3.dmm
  _maps/modularmaps/big_red/bigrednorthlambdavar4.dmm
  _maps/modularmaps/big_red/bigrednorthlambdavar5.dmm
  _maps/modularmaps/big_red/bigrednorthlambdavar6.dmm
  _maps/modularmaps/big_red/bigredsecornervar1.dmm
  _maps/modularmaps/big_red/bigredsecornervar2.dmm
  _maps/modularmaps/big_red/bigredsecornervar3.dmm
  _maps/modularmaps/big_red/bigredsecornervar4.dmm
  _maps/modularmaps/big_red/bigredsecornervar5.dmm
  _maps/modularmaps/big_red/bigredsecornervar6.dmm
  _maps/modularmaps/big_red/bigredsecornervar7.dmm
  _maps/modularmaps/big_red/bigredsouthwestetavar1.dmm
  _maps/modularmaps/big_red/bigredsouthwestetavar2.dmm
  _maps/modularmaps/big_red/bigredsouthwestetavar3.dmm
  _maps/modularmaps/big_red/bigredsouthwestetavar4.dmm
  _maps/modularmaps/big_red/bigredsouthwestetavar5.dmm
  code/__DEFINES/minimap.dm
  code/game/turfs/closed.dm
Labels: Map Edit, Quality of Life

#13106 Silo scaling
  code/controllers/subsystem/silo.dm
Labels: Balance, Stale, Test Merge Candidate

#13215 Fixes crew monitor signal runtime
  code/game/objects/machinery/computer/crew.dm
Labels: Fix

#13210 hunter AP fix
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Fix

#13225 Vali can load from pills
  code/datums/components/chem_booster.dm
  code/datums/components/harvester.dm
  code/game/objects/items/reagent_containers/pill.dm
Labels: Balance

#13223 King is a real ruler now + shrike can send hive message
  code/__DEFINES/is_helpers.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Feature

#13211 fire/lava funny damage fix
  code/game/turfs/liquid_turfs.dm
  code/modules/mob/living/living_defense.dm
Labels: Fix

#13228 Refactor nuke to use timers
  code/game/objects/effects/countdown.dm
  code/game/objects/machinery/nuclearbomb.dm
  tgui/packages/tgui/interfaces/NuclearBomb.tsx
Labels: Refactor, UI

#13234 Adds a codex entry for the blink drive
  code/game/objects/items/blink_drive.dm
Labels: Quality of Life

#12434 Portable reagent dispenser
  code/datums/components/deployable_item.dm
  code/game/objects/machinery/deployable.dm
  code/game/objects/machinery/portable_reagent_tank.dm
  code/game/objects/machinery/vending/vending_types.dm
  icons/mob/clothing/back.dmi
  icons/obj/items/chemistry.dmi
  tgmc.dme
Labels: Sprites, Config Update, Stale, Fix, Feature

#13237 Fixes resin hole chain stun
  code/modules/xenomorph/xeno_structures.dm
Labels: Balance

#13231 More service headgear
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/head/misc.dm
  icons/mob/clothing/headwear/head_0.dmi
  icons/obj/clothing/headwear/hats.dmi
Labels: Sprites, Feature

#13236 Make hivemind core hive status trackable
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Feature

#13238 add spaceacillin autoinjector to marinemed
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance, Feature

#13241 Fixes a shield bug
  code/datums/components/shield.dm
Labels: Fix

#13246 Fixes medical item overlays not appearing when vended into storage
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/storage/firstaid.dm
Labels: Fix

#13244 Plasma pistol doesn't keep a "round" in chamber
  code/modules/projectiles/guns/pistols.dm
Labels: Fix

#13202 Adds gas rounds to MLRS
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/machinery/mortar.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/mortar.dmi
Labels: Sprites, Feature

#13232 pepperball gun now has a coaxial water cannon
  code/modules/projectiles/guns/specialist.dm
  icons/Marine/marine-weapons.dmi
Labels: Sprites, Feature

#13185 Genghis incendiary charge
  code/__DEFINES/loadout.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/turfs/walls/resin.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/det.dmi
  icons/obj/items/assemblies.dmi
Labels: Sprites, Fix, Feature

#13252 illumination flares visual update
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  icons/effects/64x64.dmi
  icons/effects/effects.dmi
Labels: Sprites, Feature

#13147 Marine light medical belt
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/clothing/belts.dmi
Labels: Sprites, Feature

#13256 Adds Russian Red autoinjectors to Marinemed Vendor
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#13260 Resin doors are destroyed in 1 second
  code/game/objects/structures/xeno.dm
Labels: Fix

#13220 fixed turf armour
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#13249 Fixes platform runtime
  code/game/objects/structures/platforms.dm
Labels: Fix

#13250 Fixes `get_limb` getting a limb passed
  code/game/objects/items.dm
Labels: Fix

#13265 give acid rain a siren warning like sand storm
  code/datums/weather/weather_types/acid_rain.dm
Labels: Feature

#13267 Fixes weather not working for non humans + micro optimizations
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
Labels: Fix

#13173 Quickbuild Rework
  _maps/bigred_v2.json
  _maps/gelida_iv.json
  _maps/ice_colony_v2.json
  _maps/icy_caves.json
  _maps/lv624.json
  _maps/magmoor_digsite_iv.json
  _maps/orion_outpost.json
  _maps/prison_station_fop.json
  _maps/research_outpost.json
  code/__DEFINES/foam.dm
  code/controllers/subsystem/processing/resinshaping.dm
  code/datums/map_config.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/walls/resin.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance, Map Edit, Test Merge Candidate

#13269 adds a dot to 7.62x39 and 5.56 ammo boxes
  code/modules/projectiles/magazines/misc.dm
Labels: Grammar and Formatting

#13274 remove easy plat miner in Gelida IV
  _maps/map_files/gelida_iv/gelida_iv.dmm
Labels: Removal, Balance, Map Edit

#13203 Fix King roar reliability
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Fix

#13279 fix deployable exploits
  code/modules/projectiles/mounted.dm
Labels: Fix

#13280 Fix human armour checks
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/damage_procs.dm
Labels: Fix

#13277 Misc visual fixes
  code/modules/projectiles/ammo_datums.dm
  icons/mob/items_lefthand_1.dmi
  icons/obj/items/projectiles.dmi
Labels: Sprites, Fix

#13284 Fixes weather messages
  code/datums/weather/weather.dm
Labels: Fix

#13239 Adds jumping
  code/__DEFINES/colors.dm
  code/__DEFINES/dcs/signals.dm
  code/datums/elements/footstep.dm
  code/datums/elements/jump.dm
  code/datums/elements/windowshutter.dm
  code/datums/keybinding/living.dm
  code/game/objects/structures/platforms.dm
  code/game/sound.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/projectiles/projectile.dm
  sound/effects/bounce_1.ogg
  sound/effects/bounce_2.ogg
  sound/effects/bounce_3.ogg
  sound/effects/bounce_4.ogg
  tgmc.dme
Labels: Sound, Priority: High, Feature, RED LABEL

#13264 Less wacky footstep overrides
  code/__DEFINES/dcs/signals.dm
  code/datums/elements/footstep.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/structures/lattice.dm
  code/game/turfs/open.dm
Labels: Code Improvement

#13283 Adds Medium General Pouch to White Clothing Vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#13285 Buff defiler's tentacle by decreasing plasma cost
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Labels: Balance

#13281 remove smoke effect from mini rocket impacts
  code/game/objects/structures/dropship_ammo.dm
Labels: Removal

#13270 Fixes debris runtime
  code/datums/elements/debris.dm
Labels: Fix

#13254 Warlock shield transparency port from RU
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Feature

#13253 Robot hud port from RUTGMC
  code/game/data_huds.dm
  icons/mob/hud.dmi
Labels: Sprites, Removal, Feature

#13271 Non humans don't fit in autodoc anymore
  code/game/objects/machinery/autodoc.dm
Labels: Fix

#13263 hitscan lasers now produce light
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/tracer.dm
Labels: Fix, Feature, Test Merge Candidate

#13290 Defiler code fix
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Labels: Code Improvement, Refactor

#13295 No mind burst larva auto burrow
  code/modules/mob/living/carbon/xenomorph/embryo.dm
Labels: Feature

#13286 allows for more than 2 squads when Pillar of Spring is the ship map
  _maps/pillar_of_spring.json
Labels: Balance, Map Edit

#13291 allows for more than 2 squads when theseus is the ship map
  _maps/theseus.json
Labels: Balance, Map Edit

#13293 More weather fixes
  code/datums/looping_sounds/weather_sounds.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/acid_rain.dm
Labels: Fix

#13296 Fix squeak toys not squeaking when jumped on w/ new turf jump ended signal
  code/__DEFINES/dcs/signals.dm
  code/datums/components/squeak.dm
  code/datums/elements/jump.dm
Labels: Feature

#13297 Fixes MLRS Rockets being unavailable
  code/modules/reqs/supplypacks.dm
Labels: Fix

#13301 Fixes targetting breaking when another module inserted
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#13292 Mousedrop_T children call parent
  code/_onclick/drag_drop.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/pipe/pipe_dispenser.dm
  code/game/objects/machinery/sleeper.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/morgue.dm
  code/modules/mob/mob.dm
  code/modules/recycling/disposal.dm
Labels: Code Improvement

#13255 Hide active icon port from RU
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  icons/mob/actions.dmi
Labels: Sprites, Feature

#13302 Fixes objects and turfs frequently not using damage or armour flags
  code/_onclick/item_attack.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/displaycase.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/lamarr_cage.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/plants.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/liquid_turfs.dm
  code/game/turfs/walls/resin.dm
  code/game/turfs/walls/wall_types.dm
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/recycling/disposal.dm
  code/modules/vehicles/_vehicle.dm
  code/modules/vehicles/mecha/combat/savannah_ivanov.dm
  code/modules/vehicles/mecha/equipment/tools/mining_tools.dm
  code/modules/vehicles/mecha/mech_melee_attack.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
  code/modules/xenomorph/xeno_structures.dm
Labels: Fix

#13307 removes engine in minerva OB room
  _maps/map_files/Minerva/TGS_Minerva.dmm
Labels: Removal, Fix, Map Edit

#13316 Fixes a mounted gun runtime
  code/modules/projectiles/mounted.dm
Labels: Fix

#13315 Fixes a tweezer runtime
  code/datums/elements/shrapnel_removal.dm
Labels: Fix

#13314 Fixes a ssmonitor runtime
  code/controllers/subsystem/monitor.dm
Labels: Fix

#13311 Fix space dealing inconsistent damage
  code/game/turfs/space.dm
Labels: Fix

#13309 revert new combat and bayonet knife and machette
  icons/mob/inhands/weapons/melee_left.dmi
  icons/mob/inhands/weapons/melee_right.dmi
  icons/obj/items/weapons.dmi
Labels: Sprites, Revert

#13306 Resting via bind as a xeno now respects the use flags of the rest action
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#13146 Breadhunts CIC rework take 3 (I am not letting this flag fall)
  code/datums/jobs/squads.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/machinery/overwatch.dm
  icons/UI_Icons/map_blips.dmi
  icons/mob/radial.dmi
Labels: Sprites, Quality of Life

#13310 evolution without client
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Feature

#13313 xeno ex_act sanity
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/status_procs.dm
Labels: Code Improvement, Fix

#13299 Jump fix
  code/datums/elements/jump.dm
Labels: Fix

#13170 More immersive caves
  code/game/objects/items/radio/radio.dm
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/objects/machinery/telecomms/broadcasting.dm
  code/game/objects/machinery/telecomms/machines/processor.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Balance

#13282 Changes Russian Red Autoinjector Mix
  code/game/objects/items/reagent_containers/autoinjectors.dm
Labels: Balance

#13327 Sticky spit now spits thin sticky resin again
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#13275 The Vendor's Rising Consciousness and spelling fix
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/projectiles/guns/pistols.dm
Labels: Feature

#13323 Adding fingerless gloves
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/gloves/marine_gloves.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Sprites, Feature

#13321 Smart minigun now has reduced windup/slowdown
  code/modules/projectiles/guns/specialist.dm
Labels: Balance

#13330 Fix a fire overlay runtime
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Fix

#13324 MLRS Box QOL
  code/game/objects/machinery/mortar.dm
Labels: Quality of Life

#13332 Thin sticky resin doesn't refund build points
  code/game/objects/structures/xeno.dm
Labels: Fix

#13331 Fixes defiler being able to change reagent mid gas emission
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Labels: Fix

#13288 Refactors floor code
  code/__DEFINES/objects.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/tiles/light.dm
  code/game/objects/items/stacks/tiles/plasteel.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/turfs/floor.dm
  code/game/turfs/floor_ground.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/plating.dm
  code/game/turfs/turf.dm
  code/modules/admin/smites/bsa.dm
  code/modules/mob/inventory.dm
  code/modules/power/lighting.dm
  code/modules/recycling/disposal.dm
  tgmc.dme
Labels: Refactor

#13341 fixes a small jump visual bug
  code/datums/elements/jump.dm
Labels: Fix

#13340 Marine boots have noslip again
  code/modules/clothing/shoes/marine_shoes.dm
Labels: Fix

#13344 Add 5 colors, the Squad Colors, to modular armor for Hyperscale and alphabetize color list
  code/__DEFINES/modular_armor.dm
Labels: Code Improvement, Feature

#13349 Explosive Vest description update in regards to riot shields
  code/game/objects/items/explosives/bombvest.dm
Labels: Fix

#13346 Fixes an intoxication status effect runtime
  code/datums/status_effects/debuffs.dm
Labels: Fix

#13329 Misc balloon alert fixes
  code/game/objects/items/frames/alarms.dm
  code/game/objects/items/frames/frame.dm
  code/game/objects/items/frames/light_fixtures.dm
  code/game/objects/machinery/camera/camera_assembly.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/turfs/walls/walls.dm
Labels: Fix, Quality of Life

#13348 Fixes ghost rail flashlight
  code/modules/projectiles/gun_attachables.dm
Labels: Fix

#13258 Pillar of Spring Summer 2023 Remodel
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Map Edit

#13354 Fixes more type definitions in params
  code/game/objects/items/embedding.dm
  code/modules/projectiles/gun_attachables.dm
Labels: Code Improvement

#13353 Fixes new character slots being uneditable (minus species)
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#13172 adds outfits for robot shipside roles
  code/datums/jobs/job/shipside.dm
Labels: Fix

#13347 new/list => list()
  code/__HELPERS/spatial_info.dm
  code/game/objects/items/reagent_containers/food/snacks/grown.dm
  code/game/objects/items/taperecorder.dm
  code/game/objects/machinery/computer/security.dm
  code/game/objects/machinery/computer/skills.dm
  code/modules/mob/inventory.dm
  code/modules/reagents/holder.dm
  code/modules/reagents/reactions.dm
  code/modules/reagents/reagents/other.dm
Labels: Code Improvement

#13358 The alamo doesn't get locked as it is taking off if manually hijacked
  code/modules/shuttle/marine_dropship.dm
Labels: Balance, Fix

#13361 SOM General Storage Grammar
  code/modules/clothing/modular_armor/attachments/storage.dm
Labels: Grammar and Formatting

#13365 Gives non speech channels first letter uppercase + automatic dot
  code/modules/mob/living/say.dm
Labels: Feature

#13350 Fixes insta repairing cades if they were low hp enough
  code/game/objects/structures/barricade.dm
Labels: Balance

#13366 fix deployable aim mode bugs
  code/modules/projectiles/gun_helpers.dm
Labels: Fix

#13364 flooring fixes
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/floor_types.dm
Labels: Fix

#13368 fix siren playing in normal rain
  code/datums/weather/weather_types/acid_rain.dm
Labels: Fix

#13334 Smart Minions by default
  code/__DEFINES/xeno.dm
  code/datums/actions/observer_action.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Balance

#13305 cooler cooler explosions now using particles
  code/__DEFINES/is_helpers.dm
  code/controllers/subsystem/explosions.dm
  code/game/objects/effects/effect_system/effects_explosion.dm
  code/game/objects/effects/temporary_visuals/explosions.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/modules/admin/fun_verbs.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  code/modules/power/batteryrack.dm
  code/modules/power/cell.dm
  code/modules/power/port_gen.dm
  code/modules/power/smes_construction.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammunition.dm
  code/modules/reagents/reactions/other.dm
  icons/effects/96x157.dmi
  icons/effects/96x96.dmi
  icons/effects/explosion.dmi
  tgmc.dme
Labels: Sprites, Removal, Code Improvement, Feature

#13362 Adds missing dependency to TTS docker
  tools/tts/tts/Dockerfile
Labels: Tools, Fix

#13325 fix smart pipe mapping helper runtiming
  code/modules/atmospherics/machinery/pipes/manifold.dm
  code/modules/mapping/mapping_helpers.dm
Labels: Fix

#13370 Fixes admin Rank and Equipment bugs
  code/datums/jobs/job/job.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix, Administration

#13360 Impact Hud lingers longer
  code/game/objects/machinery/mortar.dm
Labels: Feature
