Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2023-02, with the labels that each got.

#12050 annihilate extra tcomm in Sulaco w/ dorm changes
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Fix, Map Edit, Feature

#12052 Replaces flat ice walls with a 3/4ths compliant version
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/shuttles/minidropship.dmm
  code/__DEFINES/smoothing.dm
  code/game/area/icecolony.dm
  code/game/turfs/closed.dm
  icons/turf/walls/bluefrostwall.dmi
  icons/turf/walls/darkfrostwall.dmi
  icons/turf/walls/frostwall.dmi
Labels: Sprites, Map Edit

#12045 King Death Cry
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  sound/voice/alien_king_died.ogg
Labels: Sound

#12047 fix camo fatigues half uniform not showing
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/uniform_0.dmi
Labels: Sprites, Fix

#12055 P-14 desc no longer lies to you about mag size
  code/modules/projectiles/guns/pistols.dm
Labels: Grammar and Formatting

#12053 Sensor tower update
  code/game/objects/structures/sensor_tower.dm
Labels: Code Improvement, Fix

#12021 Fixes some harddel issues
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/atom_hud.dm
Labels: Code Improvement

#12016 king death timer fix
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#11917 Xeno Ex_act fix
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Balance

#11954 New map, Oscar Outpost [MDB Ignore]
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar2.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar3.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar4.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar2.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar3.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar4.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar5.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar6.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar7.dmm
  _maps/oscar_outpost.json
  code/__DEFINES/__game.dm
  code/datums/gamemodes/combat_patrol.dm
  code/datums/gamemodes/game_mode.dm
  code/datums/gamemodes/sensor_capture.dm
  code/datums/gamemodes/zombie_crash.dm
  code/game/area/oscaroutpost.dm
  code/game/objects/effects/decals/turfdecals/markings.dm
  code/game/objects/effects/spawners/modularmappingspawner.dm
  code/game/objects/effects/spawners/random.dm
  code/game/objects/machinery/floodlight.dm
  code/game/objects/structures/platforms.dm
  code/game/objects/structures/prop.dm
  code/modules/mapping/modular_mapping.dm
  code/modules/projectiles/guns/mounted.dm
  config/maps.txt
  icons/Marine/mainship_props96.dmi
  icons/Marine/marine-hmg.dmi
  icons/effects/landmarks_static.dmi
  icons/obj/structures/platforms.dmi
  icons/turf/decals.dmi
  tgmc.dme
Labels: Sprites, Config Update, Map Edit, Feature, Test Merge Candidate

#11786 Camouflage marines
  _maps/desertdam.json
  code/__DEFINES/loadout.dm
  code/__DEFINES/maps.dm
  code/__DEFINES/objects.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/special_forces.dm
  code/datums/loadout/loadout_manager.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items/loot_box.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/m10.dmi
  icons/mob/modular/modular_armor.dmi
Labels: Sprites, Map Edit, Feature

#12017 Sprites marine job-specific satchels, adds functionality
  code/__DEFINES/loadout.dm
  code/_globalvars/lists/objects.dm
  code/game/objects/items/storage/backpack.dm
  icons/obj/items/storage/storage.dmi
Labels: Sprites, Feature

#11937 Clean Up Action Icons
  code/datums/actions/action.dm
  code/datums/actions/observer_action.dm
  code/datums/actions/xeno_action.dm
  code/datums/components/suit_autodoc.dm
  code/game/objects/machinery/overwatch.dm
  icons/Marine/marine-weapons.dmi
  icons/mob/actions.dmi
Labels: Sprites, Test Merge Candidate

#11721 Xeno buff of the year (Pre-shutter mazing ability)
  code/__DEFINES/action.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mode.dm
  code/__DEFINES/xeno.dm
  code/__HELPERS/game.dm
  code/controllers/subsystem/processing/resinshaping.dm
  code/datums/gamemodes/distress.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/walls/resin.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  tgmc.dme
Labels: Balance, Feature, Requires Testing

#12076 Fix xeno bomb checks
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Fix

#12071 Heavy Minigun and Dual AC are now not-hardpoint only (and necessary emplaced gun price changes)
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  code/game/objects/structures/dropship_equipment.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-hmg.dmi
Labels: Sprites, Balance, Map Edit, Feature

#12063 spiderlings now get coated in resin jelly too :)
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
Labels: Balance

#12061 Fix vent crawl
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
Labels: Fix

#12084 new main menu ui
  code/_onclick/hud/new_player.dm
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  icons/UI_Icons/lobby_button.dmi
  icons/UI_Icons/lobbytext.dmi
Labels: Sprites

#12081 Deployable ex_act fix
  code/game/objects/machinery/deployable.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/sentries.dm
Labels: Balance, Fix

#12087 Fixes vatborn having way too much slowdown
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#12089 Remove Mosin from Icy Cave
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Removal, Map Edit

#12039 Ports carrier visible huggers from CM part 2
  code/modules/mob/living/carbon/xenomorph/castes/carrier/carrier.dm
  icons/Xeno/2x2_Xenos.dmi
Labels: Sprites, Feature

#11993 New cosmetic robot types
  code/__HELPERS/global_lists.dm
  code/datums/jobs/job/terragov.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/holsters.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/glasses/meson.dm
  code/modules/clothing/glasses/night.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/new_player/preferences_setup.dm
  icons/mob/human_races/r_robot_alpharii.dmi
  icons/mob/human_races/r_robot_bravada.dmi
  icons/mob/human_races/r_robot_charlit.dmi
  icons/mob/human_races/r_robot_deltad.dmi
  icons/mob/species/robot/glasses_alpharii.dmi
  icons/mob/species/robot/glasses_bravada.dmi
  icons/mob/species/robot/glasses_charlit.dmi
  icons/mob/species/robot/glasses_deltad.dmi
  tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx
Labels: Sprites, Feature, UI

#12091 Unjanks rav fire interation
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/projectiles/guns/flamer.dm
Labels: Balance

#12101 remove supply manifest
  code/modules/reqs/supply.dm
Labels: Removal

#12085 Marine boots recolor + additions
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/shoes/marine_shoes.dm
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Sprites, Feature

#12096 Improvements to fireturf code
  code/modules/projectiles/guns/flamer.dm
Labels: Balance

#12100 Warlock shield control change
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Quality of Life

#12098 Removes vending delay from marine vendors
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Removal, Quality of Life

#12099 HvH tweaks
  code/datums/jobs/job/sonsofmars.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/items/blink_drive.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Code Improvement, Balance

#12072 New TAT ammo, and three AGLS changes
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-atgun.dmi
Labels: Sprites, Balance, Fix, Feature

#12110 Only humans spin when stop drop and rolling
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
Labels: Fix

#11999 Spatial grid port
  code/__DEFINES/_radio.dm
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/say.dm
  code/__DEFINES/spatial_gridmap.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/_lists.dm
  code/__HELPERS/game.dm
  code/__HELPERS/spatial_info.dm
  code/_onclick/hud/parallax.dm
  code/controllers/subsystem/parallax.dm
  code/controllers/subsystem/spatial_gridmap.dm
  code/datums/datum.dm
  code/datums/holocall.dm
  code/datums/wires/radio.dm
  code/game/atoms_movable.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/radio/intercom.dm
  code/game/objects/items/radio/radio.dm
  code/game/objects/machinery/hologram.dm
  code/game/objects/machinery/telecomms/broadcasting.dm
  code/game/objects/machinery/telecomms/machines/broadcaster.dm
  code/game/objects/machinery/telecomms/machines/bus.dm
  code/game/objects/machinery/telecomms/machines/hub.dm
  code/game/objects/machinery/telecomms/machines/processor.dm
  code/game/objects/machinery/telecomms/machines/receiver.dm
  code/game/objects/machinery/telecomms/machines/relay.dm
  code/game/objects/machinery/telecomms/machines/server.dm
  code/game/objects/machinery/telecomms/telecomunications.dm
  code/game/say.dm
  code/game/sound.dm
  code/modules/client/client_procs.dm
  code/modules/mapping/reader.dm
  code/modules/mapping/space_management/zlevel_manager.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob.dm
  tgmc.dme
Labels: Code Improvement, Test Merge Candidate, Requires Testing

#12066 MG-60 reduction
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance

#12067 Nerfs throwing knives
  code/game/objects/items/weapons/blades.dm
Labels: Balance

#12111 MG-42 now has T-12 burst fire and tac sensor+BFA
  code/modules/projectiles/guns/rifles.dm
Labels: Balance

#12104 Makes thrown objects actually make sound when they hit something living.
  code/game/objects/items.dm
Labels: Feature

#12083 AGS Improvements and WP ammo
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-hmg.dmi
Labels: Sprites, Balance, Feature, Quality of Life

#12117 WarNerd rouny sprites
  icons/Xeno/2x2_Xenos.dmi
Labels: Sprites

#12105 Larva, health, plasma, etc hud minor resprite
  icons/mob/hud.dmi
Labels: Sprites

#12115 Actual oxycodone OD
  code/modules/reagents/reagents/medical.dm
Labels: Balance

#12119 Buffs power fist a little
  code/game/objects/items/weapons/misc.dm
Labels: Balance

#12120 Powerfist sprite update
  code/game/objects/items/weapons/misc.dm
  icons/obj/items/weapons.dmi
  tgmc.dme
Labels: Sprites

#12075 New proc do_refill allows you to tactical reload pill bottles and flare pouches
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/storage.dm
Labels: Feature

#12132 Fix AGLS req oversight
  code/modules/reqs/supplypacks.dm
Labels: Fix

#12125 Gasmask action icon and internals code cleaning
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  icons/mob/screen/generic.dmi
Labels: Sprites, Removal

#12124 Nerfs the bible
  code/game/objects/items/storage/bible.dm
Labels: Balance

#12009 Adds a new Marine gun- The Magnum
  code/__DEFINES/calibers.dm
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
  sound/weapons/guns/fire/t76.ogg
  sound/weapons/guns/fire/t76_start.ogg
Labels: Sprites, Sound, Feature

#12123 Adds a light on the pillar of spring where the vendors are.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#12136 Rownin and flak vest fix
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/modular_armor.dmi
Labels: Sprites, Fix

#12112 Reqtorio Expansion V 1.3
  code/modules/factory/howtopaper.dm
  code/modules/factory/parts.dm
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature

#12135 Fix Plasma OB detonating in OB room
  code/game/objects/structures/orbital_cannon.dm
Labels: Fix

#12127 AMR fixes
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#12143 Fix MLRS reqtorio
  code/modules/factory/parts.dm
Labels: Fix

#12148 SOM HE and incendiary grenades
  code/datums/jobs/job/sonsofmars.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/pouch.dm
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/grenade.dmi
Labels: Sprites, Feature, Quality of Life

#12144 Reduce Stun grenade detonation time
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Balance

#12146 Spray nozzle nerf
  code/modules/projectiles/gun_attachables.dm
Labels: Balance

#12145 VX-12 resprite
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/magazines/energy.dm
  icons/Marine/gun64.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites

#12121 Mortar/Howitzer shell speed nerf, howitzer cooloff nerf, arty bullet color change to yellow
  code/game/objects/machinery/mortar.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#12128 Engineers can no longer buy teleporters
  code/__DEFINES/loadout.dm
Labels: Balance

#12141 Adds the Carlford Armory Union C-1 Garand.
  code/__DEFINES/calibers.dm
  code/controllers/subsystem/persistence.dm
  code/datums/jobs/job/clf.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_64.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  sound/weapons/guns/fire/garand.ogg
  sound/weapons/guns/interact/garand_ping.ogg
Labels: Sprites, Sound, Feature

#12058 Nerfs Shields melee/acid resistances and shield melee coverage overall
  code/game/objects/items/weapons/shields.dm
Labels: Removal, Balance, Test Merge Candidate

#12118 Redoes robot healing a little
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  code/__DEFINES/loadout.dm
  code/__DEFINES/traits.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/tools/soldering_tool.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/power/cable.dm
  code/modules/projectiles/guns/flamer.dm
  tgmc.dme
Labels: Removal, Balance, Map Edit

#12150 Fixes Reqtorio formatting
  code/modules/factory/parts.dm
Labels: Fix

#12153 Remove mosin from Research Outpost
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
Labels: Removal, Map Edit

#12158 Fix bottle stuns
  code/game/objects/items/reagent_containers/food/drinks/bottle.dm
Labels: Balance, Fix

#12156 Reduces bonus time for capturing a sensor tower
  code/__DEFINES/mode.dm
Labels: Balance

#12161 TL buff
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance

#12134 Makes pill packets great again!
  code/__DEFINES/colors.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/items/trash.dm
  icons/obj/items/chemistry.dmi
  icons/obj/items/trash.dmi
Labels: Sprites, Balance

#12164 Brings node.bat to what TG has, to fix several jukebuild problems
  dependencies.sh
  tools/bootstrap/node.bat
  tools/bootstrap/node_.ps1
Labels: Code Improvement, Tools

#12166 Fixes the mutiple rogue pixels carriers wound overlays had.
  icons/Xeno/wound_overlays.dmi
Labels: Sprites

#12175 Deletes balloon alert from taking out a pill
  code/game/objects/items/storage/firstaid.dm
Labels: Removal

#12107 Refactors the xeno evolution backend.
  code/__DEFINES/mobs.dm
  code/__HELPERS/global_lists.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  tgui/packages/tgui/interfaces/HiveEvolveScreen.tsx
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Code Improvement, Refactor, Test Merge Candidate, UI

#12171 Increases passive regeneration on kitted limbs
  code/modules/mob/living/carbon/human/life/handle_organs.dm
  code/modules/organs/limbs.dm
Labels: Balance

#12182 Mosin scope sprite fix
  icons/Marine/marine-weapons.dmi
Labels: Sprites, Fix

#12183 Pill packet sprites V2
  code/__DEFINES/colors.dm
  icons/obj/items/chemistry.dmi
Labels: Sprites

#12029 Adds the Artemis helmet module, that protects from eye blur.
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/loadout.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/datums/components/blur_protection.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/codex/entries/clothing_codex.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/modular/modular_armor_modules.dmi
  tgmc.dme
Labels: Sprites, Sound, Stale, Feature, UI

#12122 Adds maintenance activation to robots
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/status_procs.dm
Labels: Fix, Feature, Test Merge Candidate

#12187 Fixes xenos being unable to evolve to t4 from t1 due to missing t2 slots
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#12179 Reduces cable coil material cost
  code/modules/power/cable.dm
Labels: Balance

#12149 New DualAC sprite and ammo + tweaks
  code/game/sound.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-ac.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  sound/weapons/guns/fire/autocannon_1.ogg
  sound/weapons/guns/fire/autocannon_2.ogg
  sound/weapons/guns/fire/autocannon_3.ogg
  sound/weapons/guns/fire/autocannon_fire.ogg
Labels: Sprites, Removal, Sound, Feature

#12130 Buffs shoulder holster webbing
  code/modules/clothing/modular_armor/attachments/uniform.dm
Labels: Balance

#12192 Resprites crematorium with TG sprites
  icons/obj/stationobjs.dmi
Labels: Sprites

#12170 Skill locks chemistry
  code/modules/reagents/machinery/chem_dispenser.dm
  code/modules/reagents/machinery/chem_master.dm
Labels: Balance

#12178 (Hopefully) fixes Admin Observers not appearing on staffwho and being unable to use MSAY
  code/modules/admin/holder.dm
Labels: Fix, Administration

#12198 Adds a roller bed to the Synth Essential Set.
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Feature

#12204 ERT Shoulder holster empty slots.
  code/modules/clothing/modular_armor/attachments/uniform.dm
Labels: Feature

#12206 armor code cleanup
  code/__DEFINES/conflict.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/robot_visors.json
  code/datums/greyscale/json_configs/visors.json
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/attachments/visors.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/modular_armor/som.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  icons/mob/modular/jaeger_armor.dmi
  icons/mob/modular/jaeger_helmets.dmi
  icons/mob/modular/m10.dmi
  icons/mob/modular/modular_armor.dmi
  icons/mob/modular/robot_armor.dmi
  icons/mob/modular/robot_helmets.dmi
  icons/mob/modular/som_armor.dmi
  icons/mob/modular/som_helmets.dmi
  icons/mob/modular/xenonauten_armor.dmi
  icons/mob/modular/xenonauten_helmets.dmi
Labels: Sprites, Code Improvement

#12165 Refactors gamemode code, in particular relating to silos
  code/__DEFINES/mode.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/monitor.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/civil_war.dm
  code/datums/gamemodes/combat_patrol.dm
  code/datums/gamemodes/distress.dm
  code/datums/gamemodes/infestation.dm
  code/datums/gamemodes/nuclear_war.dm
  code/datums/gamemodes/offduty.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/xenomorph/xeno_structures.dm
  tgmc.dme
Labels: Code Improvement, Refactor, Test Merge Candidate

#12189 cooler combat sound effects
  code/__DEFINES/conflict.dm
  code/_globalvars/bitfields.dm
  code/controllers/subsystem/explosions.dm
  code/game/objects/items/radio/headset.dm
  code/game/sound.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/mecha/combat/savannah_ivanov.dm
  sound/bullets/bullet_miss1.ogg
  sound/bullets/bullet_miss2.ogg
  sound/bullets/bullet_miss3.ogg
  sound/bullets/bullet_miss4.ogg
  sound/bullets/bullet_ricochet1.ogg
  sound/bullets/bullet_ricochet2.ogg
  sound/bullets/bullet_ricochet3.ogg
  sound/bullets/bullet_ricochet4.ogg
  sound/bullets/bullet_ricochet5.ogg
  sound/bullets/bullet_ricochet6.ogg
  sound/bullets/bullet_ricochet7.ogg
  sound/bullets/bullet_ricochet8.ogg
  sound/effects/explosion1.ogg
  sound/effects/explosion2.ogg
  sound/effects/explosion3.ogg
  sound/effects/explosion4.ogg
  sound/effects/explosion5.ogg
  sound/effects/explosion6.ogg
  sound/effects/explosion_far1.ogg
  sound/effects/explosion_far2.ogg
  sound/effects/explosion_far3.ogg
  sound/effects/explosion_far4.ogg
  sound/effects/explosion_far5.ogg
  sound/effects/explosion_large1.ogg
  sound/effects/explosion_large2.ogg
  sound/effects/explosion_large3.ogg
  sound/effects/explosion_large4.ogg
  sound/effects/explosion_large5.ogg
  sound/effects/explosion_large6.ogg
  sound/effects/explosion_med1.ogg
  sound/effects/explosion_med2.ogg
  sound/effects/explosion_med3.ogg
  sound/effects/explosion_med4.ogg
  sound/effects/explosion_med5.ogg
  sound/effects/explosion_med6.ogg
  sound/effects/explosion_micro1.ogg
  sound/effects/explosion_micro2.ogg
  sound/effects/explosion_micro3.ogg
  sound/effects/explosion_small1.ogg
  sound/effects/explosion_small2.ogg
  sound/effects/explosion_small3.ogg
  sound/effects/explosion_small4.ogg
  sound/effects/explosion_smallfar1.ogg
  sound/effects/explosion_smallfar2.ogg
  sound/effects/explosion_smallfar3.ogg
  sound/effects/explosion_smallfar4.ogg
Labels: Removal, Sound, Feature

#12162 Adds the V-34 carbine for SOM and some MPI changes
  code/datums/quick_load_outfits.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/gun.dmi
Labels: Sprites, Feature

#12210 Fixes Caste death timers not working
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#12174 Adds ICC, a new hostile ERT, and a minor SoM blurb change.
  code/__DEFINES/_radio.dm
  code/__DEFINES/factions.dm
  code/datums/emergency_calls/icc.dm
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/icc.dm
  code/datums/skills.dm
  code/game/communications.dm
  code/game/objects/items/radio/encryptionkey.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-pouches.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/belt.dmi
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head_1.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/mask.dmi
  icons/mob/suit_1.dmi
  icons/mob/suit_slot.dmi
  icons/mob/uniform_0.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/cm_hats.dmi
  icons/obj/clothing/cm_suits.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/storage/storage.dmi
  tgmc.dme
Labels: Sprites, Feature, Grammar and Formatting

#12221 Portable vendor fix
  code/game/objects/items/portable_vendor.dm
Labels: Fix

#12224 Loadout fixes
  code/datums/loadout/item_representation/_item_representation.dm
  code/datums/loadout/item_representation/armor_representation.dm
Labels: Fix

#12176 New Mecha melee weapon- Sunbeam particle piercer
  code/modules/projectiles/ammo_datums.dm
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  icons/mecha/mech_gun_overlays.dmi
  icons/mecha/mecha_equipment_64x32.dmi
  icons/obj/items/projectiles.dmi
Labels: Sprites, Feature

#12126 Nuke tgui port
  code/game/objects/machinery/nuclearbomb.dm
  tgui/packages/tgui/interfaces/NuclearBomb.tsx
Labels: Stale, Feature, UI, Quality of Life

#12163 Buffs Carrier Panic drop Ability while still mainly retaining the nature of the nerf before it
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Balance

#12225 Fixes a dispenser bug
  code/datums/elements/deployable_item.dm
Labels: Fix

#12216 PMC updates
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar2.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar3.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar5.dmm
  code/datums/jobs/job/deathsquad.dm
  code/datums/jobs/job/freelancers.dm
  code/datums/jobs/job/mercenaries.dm
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/special_forces.dm
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Balance, Map Edit

#12215 Spiderlings will also rest when widow does
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
  icons/Xeno/Effects.dmi
Labels: Sprites, Quality of Life

#12218 Updated SADAR sprites
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  icons/Marine/gun64.dmi
  icons/mob/ammoHUD.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_64.dmi
  icons/mob/items_suit_slot_64.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/projectiles.dmi
Labels: Sprites, Quality of Life

#12226 No more Build-a-Sentry magnum
  code/modules/projectiles/guns/revolvers.dm
Labels: Sound, Balance

#12207 New combat robot self maint sound
  code/datums/status_effects/debuffs.dm
  sound/effects/robotrepair.ogg
  sound/effects/robotrepair2.ogg
Labels: Sound

#12227 Xeno evolution fixes
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#12231 Fix some quick equip bugs
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/storage.dm
Labels: Fix

#12232 Revert an unintended sound change
  code/datums/status_effects/debuffs.dm
Labels: Fix, Revert

#12155 More fire cleanup and rav fire act actually working edition
  code/__DEFINES/cooldowns.dm
  code/game/atoms.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/guns/flamer.dm
Labels: Stale, Fix

#12201 Adds style headgear (and 2 masks)
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/modular_armor/style_line.dm
  icons/mob/modular/style_hats.dmi
  icons/mob/modular/style_hats_mob.dmi
Labels: Sprites, Feature

#12219 Specifies that time shift doesnt save you from death or from crit
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Quality of Life

#12222 Cleans up jetpack code
  code/game/objects/items/jetpack.dm
Labels: Fix, Test Merge Candidate

#12236 SOM nades fit in grenade launchers
  code/modules/projectiles/guns/grenade_launchers.dm
Labels: Fix

#12238 Adds a missing loadout vendor next to the clone vat on minerva
  _maps/map_files/Minerva/TGS_Minerva.dmm
Labels: Map Edit, Feature

#12168 healing kit refactor
  code/_onclick/item_attack.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/stacks/medical.dm
  code/modules/organs/limbs.dm
Labels: Balance, Refactor, Fix, Quality of Life

#12247 Fixes robots being able to spawn in HvH
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/civil_war.dm
  code/datums/gamemodes/combat_patrol.dm
  code/datums/jobs/job/terragov.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#12244 Minor smoothing and map fixes
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/modularmaps/big_red/bigredsecornervar6.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar2.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar3.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar5.dmm
  _maps/shuttles/minidropship.dmm
  code/game/objects/structures/window.dm
  code/game/turfs/closed.dm
  code/game/turfs/floor_ground.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Balance, Fix, Map Edit

#12237 Fixes prae primo giving the person it was used on the PASSMOB flag
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
Labels: Fix

#12243 RPG tweaks
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#12229 Adds a prompt for evolving to hivemind
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Quality of Life

#12239 Adds bumpslash to esword
  code/game/objects/items/weapons/energy.dm
Labels: Quality of Life

#12184 MP-19 belt buff/resprite.
  code/game/objects/items/storage/holsters.dm
  icons/obj/clothing/belts.dmi
Labels: Sprites, Balance

#12255 Removes 2 stupid procs
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/mob_helpers.dm
  code/modules/surgery/surgery.dm
Labels: Code Improvement

#12254 Monkeys can now wield two-handed weapons
  code/game/objects/items/weapons/twohanded.dm
Labels: Quality of Life

#12252 Cocoons are no longer meltable
  code/game/objects/items/cocoon.dm
Labels: Fix

#12251 Fix hivestatus blessings button
  code/datums/actions/action.dm
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Fix, UI, Quality of Life

#12250 Fix a tile mover todo
  code/_globalvars/bitfields.dm
Labels: Code Improvement

#12249 Moves devolve action into hive UI
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Fix, UI, Quality of Life

#12257 bullet_act now calls parent
  code/game/objects/structures/stool_bed_chair_nest/janicart.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/multitile/cm_armored.dm
Labels: Fix
