Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2023-01, with the labels that each got.

#11798 underbarreled flashlights
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  icons/Marine/marine-weapons.dmi
Labels: Sprites, Feature

#11789 harnesses and harness type stuff have 6 light range
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance

#11831 Bioprinter can print biotic limbs
  code/__DEFINES/mobs.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/machinery/bioprinter.dm
  code/modules/organs/limbs.dm
  code/modules/surgery/robolimbs.dm
Labels: Feature

#11841 mooc fix
  code/modules/tgui_input/say_modal/speech.dm
Labels: Fix

#11651 Marine Vendor QOL
  code/__DEFINES/loadout.dm
  code/game/objects/items.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/clothing/modular_armor/modular.dm
Labels: Quality of Life

#11836 Adds descriptions to xeno ability tooltips
  code/datums/actions/xeno_action.dm
  code/modules/codex/entries/mobs_codex.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
Labels: Quality of Life

#11822 SL demotion/promotion fix
  code/datums/jobs/squads.dm
Labels: Fix

#11821 Mech can't be Plasmacut
  code/modules/vehicles/mecha/_mecha.dm
Labels: Fix

#11812 Warlock QOL changes
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Quality of Life

#11828 Vending visual retouch & cleanup
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  icons/obj/machines/vending.dmi
Labels: Sprites, Removal, Fix, Feature, Grammar and Formatting

#11740 Improves engi teleporters slightly
  code/game/objects/structures/teleporter.dm
Labels: Quality of Life

#11845 feat: use vis flag to determine direction
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Code Improvement, Refactor

#11853 Fix long range soldering and cabling
  code/game/objects/items/tools/soldering_tool.dm
  code/modules/power/cable.dm
Labels: Fix

#11850 Fixes storage getting stuck in mobs
  code/game/objects/items/storage/storage.dm
Labels: Fix

#11851 Slows down cryo fracture healing
  code/modules/reagents/reagents/medical.dm
Labels: Balance

#11843 damage_mult applies to sunder
  code/modules/projectiles/gun_system.dm
Labels: Balance

#11855 Add vending animation to marinemed and lasgun charger
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/machines/vending.dmi
Labels: Sprites

#11848 Secrete resin refactor
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Code Improvement, Refactor, Grammar and Formatting

#11591 Xeno Drag Changes
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Balance, Feature

#11870 Remove suicide vest in Magmoor's mosque
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Map Edit

#11862 New striped fatigues
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/uniform_0.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Feature

#11860 Reverts gunsprites back to the old set
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/items_righthand_64.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/gun.dmi
Labels: Sprites, Revert

#11868 Warlock lance fix
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Fix

#11835 Pillar of Spring 2023 Remodeling Part 1: Medbay Edition
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Feature, Test Merge Candidate

#11784 You now spin while stop drop rolling.
  code/modules/mob/living/living_defense.dm
Labels: Stale, Quality of Life

#11869 Vending additions part 2
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending_types.dm
  icons/obj/machines/vending.dmi
Labels: Sprites, Fix, Feature

#11876 Adjust factorio pizza selling to inflation
  code/modules/requisitions/supply_export.dm
Labels: Fix

#11882 Mech weapons dont detach on destruction
  code/modules/vehicles/mecha/equipment/mecha_equipment.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Fix

#11866 HvH spawn protection
  code/game/objects/structures/patrol_points.dm
Labels: Balance

#11800 Grenade launcher tweak
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/modules/projectiles/guns/grenade_launchers.dm
Labels: Balance

#11811 HvH E-shields
  code/datums/quick_load_outfits.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/modular.dm
Labels: Balance

#11813 Sentinel nade tweak
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
Labels: Balance

#11785 Primo rav fix and adjustment
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Balance, Fix

#11829 Repair refactor/QOL
  code/__DEFINES/objects.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/machinery/deployable.dm
  code/game/objects/objs.dm
  code/game/objects/structures/barricade.dm
  code/modules/vehicles/atv.dm
  code/modules/vehicles/mecha/mecha_defense.dm
  code/modules/vehicles/motorbike.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Refactor, Test Merge Candidate, Quality of Life

#11861 Adjusts the red cave wall sprites some, fixes some improper hydro trays
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/modularmaps/big_red/bigredlzvar1.dmm
  _maps/modularmaps/big_red/bigredlzvar2.dmm
  _maps/modularmaps/big_red/bigredlzvar3.dmm
  _maps/modularmaps/big_red/bigredlzvar4.dmm
  _maps/modularmaps/big_red/bigredlzvar5.dmm
  _maps/modularmaps/big_red/bigredlzvar6.dmm
  _maps/modularmaps/big_red/bigredlzvar7.dmm
  _maps/modularmaps/big_red/bigredlzvar8.dmm
  _maps/shuttles/tgs_canterbury.dmm
  icons/turf/walls/redwall.dmi
Labels: Sprites, Map Edit

#11832 Changes dylovene to tricordrazine in combat injector
  code/game/objects/items/reagent_containers/autoinjectors.dm
Labels: Balance

#11814 AMR Kit cost is now 775 from 650
  code/modules/reqs/supplypacks.dm
Labels: Balance, Stale

#11872 swaps lmg and p14 mags back to old sprites
  icons/obj/items/ammo.dmi
Labels: Sprites

#11827 Medscanner skill threshold lowered to novice. Allows SL to use medscanner without fumble.
  code/game/objects/items/scanners.dm
Labels: Balance, Stale

#11807 Adds basic manuals to squad marine vendors.
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/paperwork/paper.dm
Labels: Feature

#11844 Confirmation for return to corpse if you are in larva queue
  code/_onclick/hud/ghost.dm
Labels: Stale, Quality of Life

#11897 Db holster visual bug fix
  icons/obj/clothing/belts.dmi
Labels: Sprites, Fix

#11895 Fix morgue sprite bug
  icons/obj/stationobjs.dmi
Labels: Sprites, Fix

#11894 Hyposprays resprite
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/syringes.dm
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/syringe.dmi
  icons/obj/reagentfillings.dmi
Labels: Sprites, Code Improvement

#11899 Small chemfridge refactor
  code/game/objects/machinery/kitchen/smartfridge.dm
  tgui/packages/tgui/interfaces/SmartVend.js
Labels: Refactor, Fix, UI

#11901 Balance Fix: Shrike req points 50->500
  code/modules/requisitions/supply_export.dm
Labels: Balance, Fix

#11863 new valk sprite overlay for xenonauten
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites

#11881 Vendor QOL #2
  code/game/objects/items.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/clothing/modular_armor/modular.dm
Labels: Quality of Life

#11879 MP cant enter the mech with jetpack of his back
  code/modules/vehicles/mecha/mecha_mob_interaction.dm
Labels: Balance

#11777 Primo spitter tweaks
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Fix, Feature

#11765 King rework - revived
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/_globalvars/lists/mobs.dm
  code/_onclick/click.dm
  code/datums/keybinding/xeno.dm
  code/datums/looping_sounds/xeno_sounds.dm
  code/datums/status_effects/gun_skill.dm
  code/game/objects/effects/overlays.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/mob/living/living_defense.dm
  code/modules/organs/limbs.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/vehicles/mecha/_mecha.dm
  icons/effects/effects.dmi
  icons/mob/actions.dmi
  sound/effects/king_beam_active.ogg
  sound/effects/king_beam_charge.ogg
  sound/effects/off_guard_ability.ogg
  sound/effects/petrify_activate.ogg
  sound/effects/petrify_charge.ogg
  tgmc.dme
Labels: Sprites, Sound, Feature

#11900 PoS Medbay Fixes
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Removal, Fix, Map Edit, Feature

#11788 Mateba, General revolver changes and SAA buff.
  code/modules/projectiles/guns/revolvers.dm
Labels: Balance

#11908 boiler gibbing with its own sprites
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  icons/Xeno/2x2_Xenos.dmi
Labels: Sprites

#11904 Upgrades the minimap icons to be more consistent, clear, and visually pleasing.
  icons/UI_Icons/map_blips.dmi
Labels: Sprites

#11914 Synth hud CM port, synth damage overlay fix
  code/game/data_huds.dm
  code/modules/mob/living/carbon/human/species.dm
  icons/mob/hud.dmi
Labels: Sprites, Feature

#11909 Loadout attachment fix
  code/datums/loadout/item_representation/gun_representation.dm
Labels: Fix

#11913 Warlock observe hud fix
  code/_globalvars/lists/flavor_misc.dm
Labels: Fix

#11921 Minor ammo cleanup and walance changes
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Code Improvement, Fix

#11887 Removes Optical Imager Goggles from the game
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/night.dm
  code/modules/reqs/supplypacks.dm
Labels: Removal, Map Edit

#11877 Adds a visual effect to the Ravager's Ravage ability
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  icons/effects/200x200.dmi
Labels: Sprites, Quality of Life

#11925 new bullet projectile sprites and muzzle offset change
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
  icons/obj/items/projectiles.dmi
Labels: Sprites

#11931 Laser Pistol no longer has wielded slowdown
  code/modules/projectiles/guns/energy.dm
Labels: Balance

#11907 Combat robots can speak machine
  code/modules/language/language_holder.dm
  code/modules/mob/living/carbon/human/species.dm
Labels: Feature

#11927 CAS can no longer be launched before shutters open, or before Tadpole launches
  code/modules/shuttle/cas_plane.dm
Labels: Removal

#11923 ADD BOXING RINGS TO ALL EORD ARENA
  _maps/modularmaps/EORG/basketball.dmm
  _maps/modularmaps/EORG/cs_mansion.dmm
  _maps/modularmaps/EORG/cs_militia.dmm
  _maps/modularmaps/EORG/cs_office.dmm
  _maps/modularmaps/EORG/de_dust2.dmm
  _maps/modularmaps/EORG/de_inferno.dmm
  _maps/modularmaps/EORG/de_nuke.dmm
  _maps/modularmaps/EORG/old.dmm
  _maps/modularmaps/EORG/original.dmm
Labels: Map Edit, Feature

#11912 Pillar of Spring 2023 Expansion Part 2: kotahi edition
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  code/game/objects/items/toys/cards.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/client/preferences_gear.dm
  icons/obj/items/kotahi_cards.dmi
Labels: Sprites, Map Edit, Feature

#11926 Buffs M40 FLDP grenades and their related storage options
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/flashlight.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/projectiles/guns/grenade_launchers.dm
Labels: Balance, Feature

#11936 Removes a stray admin message from Sentinel debugging
  code/modules/reagents/reagents/toxin.dm
Labels: Removal, Fix

#11918 Sensor cap timer change
  code/__DEFINES/mode.dm
  code/datums/gamemodes/sensor_capture.dm
  code/game/objects/structures/sensor_tower.dm
Labels: Balance

#11920 Barrel charger improvement
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
Labels: Balance

#11930 Buffs Combat Floodlights
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  code/game/objects/machinery/floodlight.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance, Map Edit

#11854 Rouny takeover
  code/modules/admin/fun_verbs.dm
  code/modules/admin/holder.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  icons/Xeno/2x2_Xenos.dmi
Labels: Sprites

#11933 Replaces webbing vest sprites
  icons/mob/ties.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/ties_overlay.dmi
Labels: Sprites

#11871 SOM blink drive
  code/datums/gamemodes/combat_patrol.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/blink_drive.dm
  code/game/objects/items/weapons/energy.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/back.dmi
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/jetpack.dmi
  icons/obj/items/weapons.dmi
  sound/items/blink_empty.ogg
  sound/items/blink_recharge.ogg
  tgmc.dme
Labels: Sprites, Sound, Refactor, Feature

#11944 mech APFDS (Heavy cannon) and sniper no longer sunder
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#11924 PFC Jim Pizza joint
  code/game/objects/items/marine_gear.dm
  code/modules/factory/parts.dm
  code/modules/requisitions/supply_export.dm
Labels: Code Improvement, Feature

#11834 2023 tips update
  strings/tips/marine.txt
  strings/tips/meme.txt
  strings/tips/xeno.txt
Labels: Grammar and Formatting

#11935 All shoes now have the same armor unless specified otherwise
  code/modules/clothing/clothing.dm
  code/modules/clothing/shoes/marine_shoes.dm
Labels: Balance

#11948 Fix sensor capture timer bug
  code/datums/gamemodes/combat_patrol.dm
  code/datums/gamemodes/sensor_capture.dm
Labels: Fix

#11938 Adds the Ornamented Cap
  code/modules/clothing/head/head.dm
  icons/mob/head_1.dmi
  icons/obj/clothing/cm_hats.dmi
Labels: Sprites, Feature

#11957 Gun light fix
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
Labels: Fix

#11958 Mortar offset fix
  code/game/objects/machinery/mortar.dm
Labels: Fix

#11955 Fixes mecha tactical smoke
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Labels: Fix

#11952 Mech repair speed reduction
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Balance

#11960 New mob and object sprite for vali weapons
  icons/mob/items_lefthand_0.dmi
  icons/mob/items_righthand_0.dmi
  icons/obj/items/weapons.dmi
Labels: Sprites

#11963 PoS minor fixes
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#11959 Valhalla Update
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#11970 remove old cm actions for guns
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
Labels: Removal

#11978 Fixes pamphlet recipe of Reqtorio Razorfoam
  code/modules/factory/howtopaper.dm
Labels: Fix

#11939 Ammo HUD Update V2
  code/modules/projectiles/ammo_datums.dm
  icons/mob/ammoHUD.dmi
Labels: Sprites, Removal

#11969 HvH tweaks
  code/datums/quick_load_outfits.dm
  code/game/objects/items/loot_box.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Balance, Feature

#11934 Introduces the Style Line of equipment
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/suits/marine_armor.dm
  icons/mob/suit_1.dmi
  icons/obj/clothing/cm_suits.dmi
Labels: Sprites, Refactor, Map Edit, Feature, Test Merge Candidate

#11979 Fix reverse grip in vali sword on right hand
  icons/mob/items_righthand_0.dmi
Labels: Sprites, Fix

#11956 Brings the CSE's leadership down to a more reasonable level
  code/datums/skills.dm
Labels: Balance

#11974 TGMC Black suit
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/uniform_0.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Feature

#11973 Minor map fixes
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/modularmaps/big_red/bigredatmosvar1.dmm
  _maps/modularmaps/big_red/bigredatmosvar2.dmm
  _maps/modularmaps/big_red/bigredatmosvar3.dmm
  _maps/modularmaps/big_red/bigredatmosvar4.dmm
  _maps/modularmaps/big_red/bigredatmosvar5.dmm
  _maps/modularmaps/big_red/bigredatmosvar6.dmm
  _maps/modularmaps/lv624/southsandtemple1.dmm
Labels: Fix, Map Edit

#11991 bald hairstyles
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites

#11995 MG-42 sprite fix
  icons/mob/items_righthand_64.dmi
Labels: Sprites, Fix

#11996 Fixes Reqtorio surt module printing violins
  code/modules/factory/parts.dm
Labels: Fix

#11989 King summon fix
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Fix

#11994 HvH fixes
  code/game/objects/items/weapons/energy.dm
  code/game/objects/structures/sensor_tower.dm
Labels: Fix

#11988 add 4 floodlights to all shipside maps
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Balance, Map Edit, Feature

#11598 Adds the AGLS-37
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/loot_box.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-hmg.dmi
  icons/obj/items/grenade.dmi
  sound/weapons/guns/fire/ags.ogg
Labels: Sprites, Sound, Feature, Test Merge Candidate

#11998 Random spawner fix
  code/game/objects/effects/spawners/random.dm
Labels: Fix

#11964 SOM ert update
  code/datums/emergency_calls/sonsofmars.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/storage/holsters.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance

#11968 Melee stun chance now factor in armour
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance

#11987 Godmode fixes
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/status_procs.dm
Labels: Fix

#12006 Fixes a mounted weapon bug
  code/modules/projectiles/mounted.dm
Labels: Fix

#12007 Beanbag nerf
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#11885 GPMG/MMG Buff
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Balance

#11951 Crate changes
  code/game/objects/machinery/autolathe_datums.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Removal, Balance, Feature, Quality of Life

#11824 Adds new pain, gored, preburst and scream sounds, courtesy of The God Of Clowns.
  code/game/sound.dm
  sound/voice/human_male_gored3.ogg
  sound/voice/human_male_pain_10.ogg
  sound/voice/human_male_pain_11.ogg
  sound/voice/human_male_pain_9.ogg
  sound/voice/human_male_preburst10.ogg
  sound/voice/human_male_preburst4.ogg
  sound/voice/human_male_preburst5.ogg
  sound/voice/human_male_preburst6.ogg
  sound/voice/human_male_preburst7.ogg
  sound/voice/human_male_preburst8.ogg
  sound/voice/human_male_preburst9.ogg
  sound/voice/human_male_scream_7.ogg
Labels: Sound, Feature

#12014 King HP nerf and scaling change
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
Labels: Balance

#12022 Makes mechs (mostly assault and vanguard) substantially less tanky.
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Labels: Balance

#12013 Gun belt sprite fixes
  icons/mob/belt.dmi
  icons/obj/clothing/belts.dmi
Labels: Sprites

#12028 Kills CM icon_state varedits for good, creates a lint to guard against it
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/map_files/combat_patrol_base/combat_patrol_base.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/modularmaps/EORG/de_nuke.dmm
  _maps/modularmaps/big_red/bigredatmosvar5.dmm
  _maps/modularmaps/big_red/bigredcheckpointsouthvar3.dmm
  _maps/modularmaps/big_red/bigreddormvar1.dmm
  _maps/modularmaps/big_red/bigreddormvar2.dmm
  _maps/modularmaps/big_red/bigredlzvar8.dmm
  _maps/modularmaps/big_red/bigredmedbayvar7.dmm
  _maps/modularmaps/big_red/operation.dmm
  _maps/modularmaps/deltastation/nevaultvar1.dmm
  _maps/modularmaps/lv624/atmospherics.dmm
  _maps/shuttles/casplane.dmm
  _maps/shuttles/distress.dmm
  _maps/shuttles/distress_pmc.dmm
  _maps/shuttles/distress_ufo.dmm
  _maps/shuttles/distress_upp.dmm
  _maps/shuttles/escape_pod.dmm
  _maps/shuttles/minidropship.dmm
  _maps/shuttles/normandy.dmm
  code/game/objects/structures/cas_plane_parts.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/prop.dm
  code/game/objects/structures/som_cas_parts.dm
  code/game/turfs/closed.dm
  code/game/turfs/markings.dm
  code/game/turfs/open.dm
  icons/Marine/casship.dmi
  icons/Marine/somshipprop.dmi
  icons/turf/decals.dmi
  icons/turf/ert_shuttle.dmi
  tools/ci/check_grep.sh
Labels: Sprites, Code Improvement, Tools, Map Edit, Feature

#12032 Misspelling fix when trying to remove cloning vat beaker
  code/game/objects/machinery/cloning/cloning.dm
Labels: Fix

#12025 Sorts out synth vendor with tags and category names
  code/__DEFINES/loadout.dm
  tgui/packages/tgui/interfaces/MarineSelector.js
Labels: Code Improvement, UI, Quality of Life

#12035 Reduces surgery tool material costs
  code/game/objects/items/tools/surgery_tools.dm
Labels: Balance, Fix

#12040 Mech Rocket nerf removes heavy explosion, +1 Light explosion
  code/modules/projectiles/ammo_datums.dm
Labels: Removal, Balance

#12041 Mech Resound
  sound/mecha/LongNanoActivation.ogg
  sound/mecha/LongSyndiActivation.ogg
  sound/mecha/critdestrnano.ogg
  sound/mecha/critdestrsyndi.ogg
  sound/mecha/critnano.ogg
  sound/mecha/imag_enhnano.ogg
  sound/mecha/imag_enhsyndi.ogg
  sound/mecha/internaldmgalarm.ogg
  sound/mecha/lowpowernano.ogg
  sound/mecha/lowpowersyndi.ogg
  sound/mecha/mechdrill.ogg
  sound/mecha/mechstep.ogg
  sound/mecha/mechturn.ogg
  sound/mecha/nominalnano.ogg
  sound/mecha/nominalsyndi.ogg
  sound/mecha/weapdestrnano.ogg
  sound/mecha/weapdestrsyndi.ogg
  sound/mecha/weapons/mech_heavy_cannon.ogg
  sound/mecha/weapons/mech_laser_heavy.ogg
  sound/mecha/weapons/mech_laser_light.ogg
  sound/mecha/weapons/mech_light_cannon.ogg
  sound/mecha/weapons/mech_lmg.ogg
  sound/mecha/weapons/mech_minigun.ogg
  sound/mecha/weapons/mech_minigun_start.ogg
  sound/mecha/weapons/mech_shotgun.ogg
  sound/mecha/weapons/mech_sniper.ogg
Labels: Removal, Sound

#12046 update sprites for vali activation
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites

#12044 Ports CM defib sounds
  code/game/objects/items/defibrillator.dm
  sound/items/defib_SafetyOn.ogg
  sound/items/defib_failed.ogg
  sound/items/defib_safetyOff.ogg
  sound/items/defib_success.ogg
Labels: Sound, Feature
