Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2023-04, with the labels that each got.

#12565 Fixes carpet and catwalk breaking
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  code/game/turfs/floor_types.dm
  code/game/turfs/plating.dm
Labels: Fix, Map Edit

#12557 Fixes the 3rd person ravager endure message
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Fix

#12570 Fixed SOM vet hud icon
  icons/mob/hud.dmi
Labels: Sprites, Fix

#12575 Fixes loadout imports
  code/__DEFINES/loadout.dm
Labels: Fix

#12556 Makes the default starting boot knife the M5 survival knife
  code/modules/clothing/modular_armor/attachments/storage.dm
Labels: Balance

#12561 Adds the SOM breaching axe
  code/datums/quick_load_outfits.dm
  code/game/blood.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  icons/effects/64x64.dmi
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/weapon64_left.dmi
  icons/mob/inhands/weapons/weapon64_right.dmi
  icons/mob/suit_slot.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/items/weapons64.dmi
Labels: Sprites, Fix, Feature

#12581 Fixes the stuff the 515 regexing missed
  code/__HELPERS/qdel.dm
  code/controllers/subsystem/autofire.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/ticker.dm
  code/datums/actions/order_action.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/jobs/job/shipside.dm
  code/datums/progressbar.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/tables_racks.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/panels/note_panel.dm
  code/modules/admin/smites/bread.dm
  code/modules/admin/smites/nugget.dm
  code/modules/asset_cache/transports/asset_transport.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/balloon_alert/balloon_alert.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/orbits/spaceship.dm
  code/modules/power/power.dm
  code/modules/reqs/supply.dm
  code/modules/requisitions/fulton.dm
  code/modules/vehicles/mecha/mecha_control_console.dm
Labels: Code Improvement

#12576 Gives the nuke disk generator a TGUI interface
  code/game/objects/machinery/computer/nuke_disk_generator.dm
  tgui/packages/tgui/interfaces/NukeDiskGenerator.js
Labels: Refactor, Fix, Feature, UI

#12543 SSsilo priority tweak
  code/__DEFINES/_subsystems.dm
  code/controllers/subsystem/silo.dm
Labels: Code Improvement

#12586 The mc now keeps track of how many times a subsystem has slept in fire()
  code/controllers/master.dm
  code/controllers/subsystem.dm
Labels: Code Improvement

#12587 The mc now detects if its priority budget gets out of sync with reality and soft resets
  code/controllers/master.dm
Labels: Code Improvement

#12585 The Failsafe can now recover from an deleted MC
  code/__DEFINES/spaceman_dmm.dm
  code/_debugger.dm
  code/controllers/failsafe.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/assets.dm
  code/controllers/subsystem/garbage.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/shuttle.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/timer.dm
  code/game/world.dm
  code/modules/tgchat/to_chat.dm
  tgmc.dme
Labels: Code Improvement

#12604 updates the minimap icon
  icons/mob/actions.dmi
Labels: Sprites

#12593 Adds an admin verb to disable taking over mindless/SSD mobs
  code/_globalvars/admin.dm
  code/datums/actions/observer_action.dm
  code/modules/admin/server_verbs.dm
Labels: Fix, Feature

#12591 Nerfs the dispenser storage, can no longer hold bulky items.
  code/game/objects/items/storage/dispenser.dm
Labels: Balance

#12613 Fix stuck droppod targetting map
  code/game/objects/structures/droppod.dm
Labels: Fix

#12606 Moves germs to human from atom
  code/game/atoms.dm
  code/game/blood.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life/handle_status_effects.dm
  code/modules/reagents/reagents/other.dm
  code/modules/surgery/surgery.dm
Labels: Code Improvement

#12598 Fixes comms blackout event
  code/modules/events/ion_storm.dm
Labels: Fix

#12603 Adds large 10x26mm caseless box
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammunition.dm
Labels: Feature

#12609 Fix reverse grip on right wielding greatsword
  icons/mob/inhands/weapons/twohanded_right.dmi
Labels: Sprites, Fix

#12605 Adds self germ check
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Feature

#12553 Railgun changes
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance

#12601 Replaces "max_w_class = #" with "max_w_class = DEFINE"
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/storage/storage.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/projectiles/guns/sentries.dm
Labels: Code Improvement

#12563 Adds cryo to small Cant, adds cryo beakers to both variants
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
Labels: Balance, Map Edit, Quality of Life

#12622 Mortar sound fix
  code/game/objects/machinery/mortar.dm
Labels: Fix

#12624 Cade repair improvements
  code/game/objects/structures/barricade.dm
Labels: Balance

#12631 Sentinel spit now travels properly instead of stopping at the tile you aimed
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
Labels: Fix

#12627 Fix ICC/old SOM armor sprites
  code/modules/clothing/suits/marine_armor.dm
Labels: Fix

#12630 Fixes a behead runtime
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Fix

#12629 Adds toys and plushies to requisitions.
  code/modules/reqs/supplypacks.dm
Labels: Feature

#12619 Small fixes for large ammo boxes and MG-60
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance, Fix

#12635 Fixes CL uniform icons
  icons/obj/clothing/uniforms/uniforms.dmi
Labels: Sprites, Fix

#12640 Fixes shrike ban not working
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
Labels: Fix

#12610 Minor Big red LZ2 tweak
  _maps/modularmaps/big_red/bigredlz2var1.dmm
  _maps/modularmaps/big_red/bigredlz2var2.dmm
Labels: Balance, Map Edit

#12454 Hyposprays can draw reagent with right click.
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Feature

#12558 Adds craftable supply crates
  code/_globalvars/lists/objects.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/machinery/squad_supply/supply_packer.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  tgmc.dme
Labels: Feature, Test Merge Candidate

#12546 claymore balances
  code/game/objects/items/weapons/twohanded.dm
Labels: Balance, Stale

#12562 MREs are much more nutrient dense.
  code/game/objects/items/reagent_containers/food/snacks.dm
Labels: Do Not Merge, Balance

#12634 BAS attachment increases gun size
  code/modules/projectiles/gun_attachables.dm
Labels: Balance

#12632 Adjusts some things on drain sting, fixes do_after stacking
  code/__DEFINES/mobs.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
Labels: Balance, Fix, Quality of Life

#12650 Moves everything weight class 7 and + down to 6.
  code/game/objects/items/storage/secure.dm
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/objects/structures/dummy_mapping_objects.dm
  code/modules/projectiles/gun_system.dm
  code/modules/vehicles/multitile/hardpoints.dm
Labels: Code Improvement

#12647 Fixes people who get killed while buckled in the alamo chairs standing up even while dead
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
Labels: Fix

#12643 Adds the ak47 to the proper seasonal instead of 2 mag types
  code/controllers/subsystem/persistence.dm
Labels: Fix

#12636 Fixes psi point gen
  code/__DEFINES/misc.dm
  code/_globalvars/lists/objects.dm
  code/modules/power/groundmap_geothermal.dm
Labels: Fix

#12642 Refactors simple doors and inflatables
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  icons/obj/doors/mineral_doors.dmi
Labels: Sprites, Refactor

#12305 Roundstart runtime fixes
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#12661 Fixes psi gen, again.
  code/modules/power/groundmap_geothermal.dm
Labels: Fix

#12657 Minor code fixes
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/game/objects/structures/inflatable.dm
Labels: Code Improvement

#12655 Adds 2 AI droids to Theseus
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit, Feature

#12653 shrike can now give plasma
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
Labels: Balance, Feature

#12638 Fixes some grammar checks.
  code/game/objects/machinery/vending/loadout_vendor.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Grammar and Formatting

#12677 Rocket fix
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#12628 made deploying items make you automatically interact with them
  code/__DEFINES/preferences.dm
  code/_globalvars/bitfields.dm
  code/datums/elements/deployable_item.dm
  code/modules/client/preferences_ui.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Balance, UI, Quality of Life

#12670 xfuel back tank resprite.
  code/modules/projectiles/magazines/flamer.dm
  icons/mob/clothing/back.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites

#12675 Updates Factions
  code/__DEFINES/factions.dm
  code/datums/jobs/job/special_forces.dm
  code/game/objects/items/cards_ids.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/sentries.dm
Labels: Fix

#12685 Removes unused breaker box
  _maps/modularmaps/big_red/bigredengineeringvar1.dmm
  _maps/modularmaps/big_red/bigredengineeringvar2.dmm
  _maps/modularmaps/big_red/bigredengineeringvar3.dmm
  _maps/modularmaps/big_red/bigredengineeringvar4.dmm
  code/game/objects/effects/spawners/random.dm
  code/game/objects/structures/prop.dm
  code/modules/power/breaker_box.dm
  tgmc.dme
Labels: Removal, Code Improvement, Map Edit

#12694 Unmanned Vehicles now leave behind robot gibs when destroyed
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Feature

#12695 Swaps dexaline for isotonic in lifesaver belt
  code/game/objects/items/storage/belt.dm
Labels: Balance

#12703 Improves robot GHMME experience.
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Quality of Life

#12693 You no longer keep healthscan/defib gloves after being delimbed.
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/scanners.dm
Labels: Fix

#12688 Vali green blood gained scales off the weapon attack speed.
  code/datums/components/chem_booster.dm
  code/game/objects/items.dm
Labels: Balance

#12686 Loadouts can be reorganized.
  code/datums/loadout/loadout_manager.dm
  tgui/packages/tgui/interfaces/LoadoutManager/index.tsx
Labels: UI, Quality of Life

#12679 Integrates tables with the new smoothing system
  code/__DEFINES/icon_smoothing.dm
  code/game/objects/machinery/computer/HolodeckControl.dm
  code/game/objects/structures/tables_racks.dm
  icons/obj/smooth_objects/black_table.dmi
  icons/obj/smooth_objects/fancy_table.dmi
  icons/obj/smooth_objects/mainship_table.dmi
  icons/obj/smooth_objects/pool_table.dmi
  icons/obj/smooth_objects/prison_table.dmi
  icons/obj/smooth_objects/req_table.dmi
  icons/obj/smooth_objects/rustic_table.dmi
  icons/obj/smooth_objects/table_fabric.dmi
  icons/obj/smooth_objects/table_regular.dmi
  icons/obj/smooth_objects/table_reinforced.dmi
  icons/obj/smooth_objects/wood_table_reinforced.dmi
Labels: Sprites, Code Improvement, Fix

#12702 Acid on walls gets deleted if the wall gets deleted
  code/game/turfs/turf.dm
Labels: Fix

#12696 Corpsman vendor has QC+ and Peri+ hypos
  code/__DEFINES/loadout.dm
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Quality of Life

#12698 Flamethrower back tank resprite
  icons/mob/clothing/back.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites

#12710 Updates Pistol belt description
  code/game/objects/items/storage/belt.dm
Labels: Grammar and Formatting

#12707 Adds a verb/keybind to toggle automatic magazine ejections
  code/__DEFINES/dcs/signals.dm
  code/datums/elements/deployable_item.dm
  code/datums/keybinding/human.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
Labels: Feature

#12717 Fixes out of hand tac reloads
  code/modules/projectiles/gun_helpers.dm
Labels: Fix

#12667 Projectile stun resistance
  code/__DEFINES/dcs/signals.dm
  code/datums/components/shield.dm
  code/datums/components/stun_mitigation.dm
  code/game/objects/items.dm
  code/game/objects/items/explosives/bombvest.dm
  code/game/objects/items/weapons/energy.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/inventory.dm
  code/modules/projectiles/ammo_datums.dm
  tgmc.dme
Labels: Fix, Feature

#12691 Flare pouch is a holster now.
  _maps/map_files/LV624/LV624.dmm
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/clf.dm
  code/datums/jobs/job/imperium.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  icons/Marine/marine-pouches.dmi
Labels: Sprites, Map Edit, Quality of Life

#12732 AMR Resprite
  icons/Marine/gun64.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Fix

#12729 Adjust status displays to fit on walls
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/modularmaps/big_red/bigredlzvar1.dmm
  _maps/modularmaps/big_red/bigredlzvar2.dmm
  _maps/modularmaps/big_red/bigredlzvar3.dmm
  _maps/modularmaps/big_red/bigredlzvar4.dmm
  _maps/modularmaps/big_red/bigredlzvar5.dmm
  _maps/modularmaps/big_red/bigredlzvar6.dmm
  _maps/modularmaps/big_red/bigredlzvar7.dmm
  _maps/modularmaps/big_red/bigredlzvar8.dmm
  code/game/objects/effects/spawners/random/clothing.dm
  code/game/objects/effects/spawners/random/engineering.dm
  code/game/objects/effects/spawners/random/food_or_drink.dm
  code/game/objects/effects/spawners/random/machinery.dm
  code/game/objects/effects/spawners/random/medical.dm
  code/game/objects/effects/spawners/random/misc_item.dm
  code/game/objects/effects/spawners/random/misc_structure.dm
  code/game/objects/effects/spawners/random/weaponry.dm
  code/game/objects/machinery/status_display.dm
  code/game/objects/structures/prop.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
  icons/Marine/mainship_props.dmi
  icons/effects/landmarks_static.dmi
  icons/obj/status_display.dmi
  icons/obj/structures/closet.dmi
  icons/obj/terminals.dmi
Labels: Sprites, Fix, Map Edit

#12706 Human topic cleanup
  code/modules/mob/living/carbon/human/human.dm
Labels: Refactor, Test Merge Candidate

#12594 AR-55 is now buyable in req.. and by SLs, makes GL-54 magazines cheaper in req
  code/__DEFINES/loadout.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature, Test Merge Candidate

#12738 Sadar resprite
  icons/Marine/gun64.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_64.dmi
Labels: Sprites

#12743 Fixes the ammo box's water tank sprite.
  code/modules/projectiles/magazines/flamer.dm
  icons/obj/items/items_mini.dmi
Labels: Sprites, Feature

#12745 Adds navy sprite obj icon
  icons/obj/clothing/headwear/marine_hats.dmi
Labels: Sprites, Fix

#12678 razorwire construction option changed to a ratio of 2 metal for 1 razorwire, with 2 razorwire being made with 4 metal
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/razorwire.dm
Labels: Balance

#12637 Adds new FC Gear Selector vendor. Adds FC vendors to crash ships.
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/__DEFINES/jobs.dm
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/shipside.dm
  code/datums/loadout/loadout_helper.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Removal, Map Edit, Feature, Quality of Life

#12726 fixes only the first arty piece having a cam
  code/game/objects/machinery/mortar.dm
Labels: Fix

#12723 updates the element system from /tg/station
  code/__DEFINES/dcs/flags.dm
  code/__DEFINES/map_switch.dm
  code/controllers/subsystem/dcs.dm
  code/datums/elements/_element.dm
  code/datums/elements/attachment.dm
  code/datums/elements/connect_loc.dm
  code/datums/elements/deployable_item.dm
  code/datums/elements/egrill_element.dm
  code/datums/elements/gestures.dm
  code/datums/elements/light_blocking.dm
  code/datums/elements/limb_support.dm
  code/datums/elements/plasma_on_attack.dm
  code/datums/elements/plasma_on_attacked.dm
  code/datums/elements/riding.dm
  code/datums/elements/shrapnel_removal.dm
  code/datums/elements/special_clothing_overlay.dm
  code/datums/elements/undertile.dm
  code/datums/elements/wall_speedup.dm
  code/modules/unit_tests/bespoke_id.dm
  code/modules/unit_tests/dcs_get_id_from_elements.dm
  tgmc.dme
Labels: Code Improvement, Test Merge Candidate

#12716 Tac-reloadable guns are opaque (so when in hands)
  code/modules/projectiles/gun_system.dm
Labels: Quality of Life

#12748 Fixes broken entertainment monitors
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/modularmaps/EORG/cs_office.dmm
  _maps/modularmaps/EORG/de_dust2.dmm
Labels: Fix, Map Edit

#12736 Kills rocket spam
  code/modules/projectiles/guns/specialist.dm
Labels: Balance

#12728 Hunter no longer breaks stealth when staring at weeds.
  code/game/objects/obj_defense.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Fix

#12715 Fixes Evac cryo pod ghosting you immediately if you start getting into it.
  code/game/objects/machinery/cryopod.dm
  code/modules/shuttle/escape_pod.dm
Labels: Fix

#12750 Repeater Resprite
  icons/Marine/gun64.dmi
Labels: Sprites

#12733 Fixes the psi gen fix fix by making the math actually not stupid
  code/__DEFINES/mode.dm
  code/_globalvars/lists/objects.dm
  code/modules/power/groundmap_geothermal.dm
Labels: Fix

#12761 Clicking a UI Slot will return the item inside the slot
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/modules/projectiles/gun_system.dm
Labels: Removal, Feature

#12754 Shoulder holster can no longer carry mp19
  code/modules/clothing/modular_armor/attachments/uniform.dm
Labels: Balance

#12764 Fixes synth erroneously being marked as "cold" on both minimap and examine
  code/game/objects/items/defibrillator.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Fix

#12767 Removes the medscanner gloves from the Marinemed
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance

#12755 BFA change
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Balance, Fix

#12769 BR modular loot removal
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/modularmaps/big_red/bigredcargoareavar3.dmm
  _maps/modularmaps/big_red/bigredcargoareavar4.dmm
  _maps/modularmaps/big_red/bigredcargoareavar5.dmm
  _maps/modularmaps/big_red/bigredcargoareavar6.dmm
  _maps/modularmaps/big_red/bigredsecornervar3.dmm
  _maps/modularmaps/big_red/bigredsecornervar6.dmm
Labels: Balance, Fix, Map Edit

#12772 Removes portable atmospherics machinery's var of non existant type
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
Labels: Removal, Fix

#12773 Fixes two args having the same name in the squeak component
  code/datums/components/squeak.dm
Labels: Fix

#12742 Lowers Claymore deploy time
  code/game/objects/items/explosives/mine.dm
Labels: Removal, Balance

#12774 Removes unused mech var with nonexistant type
  code/modules/vehicles/mecha/_mecha.dm
Labels: Removal, Fix

#12765 Toolbelt and tool pouch can now hold the exact same things
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
Labels: Balance

#12771 Deletes duplicate proc def and unused var of nonexistant type on the antagonist datum
  code/modules/antagonists/_common/antag_datum.dm
Labels: Fix

#12784 Fix typo for cell charger
  code/game/objects/machinery/cell_charger.dm
Labels: Grammar and Formatting

#12730 Makes transfusion less annoying to use
  code/__DEFINES/mobs.dm
  code/__HELPERS/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
  code/modules/projectiles/gun_helpers.dm
Labels: Balance, Test Merge Candidate

#12779 Moves the button for Tcomms in Theseus
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Fix, Map Edit

#12780 Wearable shotgun boxes
  code/modules/projectiles/ammunition.dm
  icons/mob/clothing/back.dmi
Labels: Sprites, Balance, Feature

#12777 Rectifies a bunch of proc redefines
  code/_onclick/hud/fullscreen.dm
  code/_onclick/item_attack.dm
  code/datums/actions/xeno_action.dm
  code/datums/components/harvester.dm
  code/datums/datum.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/items/reagent_containers/food/condiment.dm
  code/game/objects/items/reagent_containers/food/pizzapasta.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/reagent_containers/food/snacks/grown.dm
  code/game/objects/items/reagent_containers/jerrycan.dm
  code/game/objects/items/tools/cleaning_tools.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/machinery/deployable.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/airlock_control.dm
  code/game/objects/machinery/floodlight.dm
  code/game/objects/machinery/roomba.dm
  code/game/objects/obj_defense.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/turfs/turf.dm
  code/modules/assembly/infrared.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/status_procs.dm
  code/modules/mob/logout.dm
  code/modules/mob/mob.dm
  code/modules/organs/limbs.dm
  code/modules/power/apc.dm
  code/modules/power/multiz.dm
  code/modules/power/port_gen.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/shuttle/ert.dm
  code/modules/shuttle/on_move.dm
  code/modules/tgui_input/say_modal/typing.dm
  code/modules/vehicles/mecha/working/ripley.dm
Labels: Code Improvement

#12781 Pill packet/bottle overlay updates when you refill a hypo
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Fix

#12787 Adds desc to weldingtool and medical splint
  code/game/objects/items/circuitboards/circuitboard.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/tools/maintenance_tools.dm
Labels: Grammar and Formatting

#12786 Medical Rig belt has isotonic instead of dexalin
  code/game/objects/items/storage/belt.dm
Labels: Balance

#12783 Makes Defender's Fortify Charge feel smoother to use
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Quality of Life

#12796 Re-adds the IV drip to the Canterbury
  _maps/shuttles/tgs_canterbury.dmm
Labels: Fix, Map Edit

#12795 Blessings menu action button removal
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Removal

#12794 Missing call burrow desc fix
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Fix

#12793 Remove X spits at y message
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Quality of Life

#12792 Make xenos have all abilities if spawned prior to game start
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Quality of Life

#12790 [s]Fix admin topic exploit
  code/modules/client/client_procs.dm
Labels: Security Exploit

#12788 Fixes some minor issues
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/desertdam/desertdam.dmm
  code/game/objects/items/reagent_containers/food/burgers.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/structures/tables_racks.dm
  icons/obj/smooth_objects/table_regular.dmi
Labels: Sprites, Balance, Fix, Map Edit

#12816 Fixes req railings not being invunerable and fixes mobs being able to be thrown over them
  code/game/objects/machinery/doors/railing.dm
Labels: Fix

#12804 Gloves resprite
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/generic/Admin_Level.dmm
  code/__DEFINES/loadout.dm
  code/datums/gamemodes/objective_items.dm
  code/datums/jobs/job/shipside.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/effects/spawners/random/clothing.dm
  code/game/objects/effects/spawners/random/engineering.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/under/gimmick.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Sprites, Map Edit

#12811 Makes lifesaver the recommended Synth option.
  code/__DEFINES/loadout.dm
Labels: Removal, Feature

#12814 adds feedback to healthscan RMB
  code/game/objects/items/scanners.dm
Labels: Quality of Life

#12817 Remove three miners close to landing zone in Icy Cave redux
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Map Edit

#12802 Cablecuff fix
  code/game/objects/items/stacks/stack.dm
  icons/mob/mob.dmi
Labels: Sprites, Fix

#12813 Fixes stack Destroy() runtime
  code/game/objects/items/stacks/stack.dm
Labels: Fix

#12763 Attempts to fix Chest Fling throwing through fog.
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Fix

#12805 Grill and gibber changes
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/machinery/kitchen/gibber.dm
  code/game/objects/structures/kitchen_spike.dm
  code/modules/food/recipes_microwave.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  sound/machines/grill/frying.ogg
Labels: Sound, Fix, Map Edit, Feature

#12776 Improves xeno tanks
  code/game/objects/structures/misc.dm
Labels: Feature

#12791 Rolls minion agressivity ability into rally/command
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
Labels: Balance, Quality of Life

#12584 Adds minimap drawing
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/__DEFINES/minimap.dm
  code/__HELPERS/_logging.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystem/minimaps.dm
  code/game/objects/items/devices/minimap_tablet.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  config/config.txt
  icons/UI_Icons/map_blips.dmi
  icons/UI_Icons/minimap_buttons.dmi
  icons/UI_Icons/minimap_mouse/draw_blue.dmi
  icons/UI_Icons/minimap_mouse/draw_erase.dmi
  icons/UI_Icons/minimap_mouse/draw_purple.dmi
  icons/UI_Icons/minimap_mouse/draw_red.dmi
  icons/UI_Icons/minimap_mouse/draw_yellow.dmi
  icons/UI_Icons/minimap_mouse/label.dmi
  tgmc.dme
Labels: Sprites, Config Update, Map Edit, Feature, Administration, Test Merge Candidate

#12827 carrier balloon alerts when switching huggers
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Quality of Life

#12829 Update Human Prop and Screen Alert Sprites
  _maps/map_files/combat_patrol_base/combat_patrol_base.dmm
  code/game/objects/structures/prop.dm
  icons/Marine/mainship_props.dmi
  icons/UI_Icons/screen_alert_images.dmi
Labels: Sprites, Map Edit

#12825 Big Red LZ1 Changes
  _maps/modularmaps/big_red/bigredlzvar1.dmm
  _maps/modularmaps/big_red/bigredlzvar2.dmm
  _maps/modularmaps/big_red/bigredlzvar3.dmm
  _maps/modularmaps/big_red/bigredlzvar4.dmm
  _maps/modularmaps/big_red/bigredlzvar5.dmm
  _maps/modularmaps/big_red/bigredlzvar6.dmm
  _maps/modularmaps/big_red/bigredlzvar7.dmm
Labels: Map Edit

#12832 Fixes req railings not having collision
  code/game/objects/machinery/doors/railing.dm
Labels: Fix

#12838 Readds the mini ammo box sprite for the T29/SG29 mags.
  icons/obj/items/items_mini.dmi
Labels: Sprites, Fix

#12722 Turns all gun belts into holsters.
  code/__DEFINES/equipment.dm
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/deathsquad.dm
  code/datums/jobs/job/imperium.dm
  code/datums/jobs/job/other.dm
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/jobs/job/upp.dm
  code/datums/jobs/job/upp_commando.dm
  code/datums/quick_load_outfits.dm
  code/game/atoms.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun_system.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/clothing/belts.dmi
Labels: Sprites, Stale, Refactor

#12840 Black marine gloves
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/gloves/marine_gloves.dm
  icons/obj/clothing/gloves.dmi
Labels: Sprites, Feature

#12842 Fixes inflatable door opacity
  code/game/objects/structures/inflatable.dm
Labels: Fix

#12830 droppod fix
  code/game/objects/structures/droppod.dm
Labels: Fix

#12845 Fixes tables flipping being able to move things it shouldn't
  code/game/objects/structures/tables_racks.dm
Labels: Fix

#12844 Fixes up diagonals and diagonal shuffling
  code/modules/mob/living/living.dm
Labels: Fix

#12843 Fixes the companion component runtiming upon deletion
  code/datums/components/companion.dm
Labels: Fix

#12826 Adds some new GL-54 ammo types
  code/__DEFINES/colors.dm
  code/__DEFINES/loadout.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/ammoHUD.dmi
Labels: Sprites, Feature

#12770 Quickbuild no longer triggers on left click
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#12749 Powerloader refactor
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/interaction.dm
  code/_globalvars/bitfields.dm
  code/_onclick/item_attack.dm
  code/_onclick/other_mobs.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/cas_plane_parts.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/modules/mining/satchel_ore_boxdm.dm
  code/modules/vehicles/powerloader.dm
Labels: Refactor

#12839 HvH loadout adjustments
  code/datums/quick_load_outfits.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/modular_armor/som.dm
  code/modules/clothing/modular_armor/xenonauten.dm
Labels: Balance, Quality of Life

#12720 Armour refactor part 2
  code/__DEFINES/equipment.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/datums/status_effects/xeno_buffs.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/reagent_containers/syringes.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/open.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/life/handle_fire.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/projectile.dm
Labels: Balance, Refactor, Test Merge Candidate

#12835 Shipside medvendors are now shipside
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Fix, Map Edit

#12853 Fixes quickbuild drag not working
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#12824 M45 Trailblazer
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/grenade.dmi
  icons/obj/items/storage/storage_boxes.dmi
Labels: Sprites, Feature

#12849 Allows droppods to be bought in req
  _maps/map_files/Minerva/TGS_Minerva.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Twin_Pillars/Twin_Pillars.dmm
  code/game/objects/structures/droppod.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance, Map Edit
