Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2023-10, with the labels that each got.

#14063 Quick laser swap fix
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#14062 X-Ray Laser Rifle minor rebalance
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
Labels: Removal, Balance

#14066 Updates Crest Toss' Description
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Grammar and Formatting

#14055 Removes tier-based weapon spawns from ground maps
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
Labels: Removal, Balance, Map Edit

#14070 Lawanka Changes (Version 2)
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  code/game/turfs/closed.dm
Labels: Code Improvement, Balance, Map Edit

#14069 Remove stuff that doesn't work on current MIN_COMPILER_VERSION
  byond-extools.dll
  code/__DEFINES/_tick.dm
  code/__DEFINES/misc.dm
  code/__byond_version_compat.dm
  code/game/world.dm
  dependencies.sh
  tools/tgs4_scripts/PreCompile.sh
Labels: Tools

#14067 Fixes inconsistent MG27 Magazine description
  code/modules/projectiles/magazines/mounted.dm
Labels: Fix

#14078 Fixes an issue where the TE-X Piercing Mode inflicted Microwaved
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#14074 Egg Lay Ability Description
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Grammar and Formatting

#14071 Uncraftable stunprods
  code/game/objects/items/weapons/weaponry.dm
Labels: Removal

#14065 removes AR-55 from SL vendor
  code/__DEFINES/loadout.dm
Labels: Removal, Balance

#12961 Adds puppeteer, a T2 xeno
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/traits.dm
  code/__DEFINES/xeno.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/mobs.dm
  code/controllers/subsystem/aura.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/xeno_buffs.dm
  code/game/data_huds.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/effects/overlays.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/ai/ai_behaviors/xeno/puppet.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppet/abilities_puppet.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppet/puppet.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/projectiles/ammo_datums.dm
  icons/UI_Icons/map_blips.dmi
  icons/Xeno/actions.dmi
  icons/Xeno/castes/puppet.dmi
  icons/Xeno/castes/puppeteer.dmi
  icons/effects/effects.dmi
  icons/mob/actions.dmi
  icons/mob/hud.dmi
  icons/mob/mob.dmi
  icons/mob/screen_alert.dmi
  icons/obj/items/projectiles.dmi
  tgmc.dme
Labels: Sprites, Feature, Test Merge Candidate

#14025 Adds the L-88 to ICC and its export version to req.
  code/datums/jobs/job/icc.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/gun64.dmi
  icons/mob/clothing/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Feature

#14087 adds RR injectors to valhalla
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix, Feature

#14090 Bump Python version
  dependencies.sh
  tools/bootstrap/python37._pth
  tools/bootstrap/python_.ps1
  tools/requirements.txt
Labels: Tools

#14084 Add Debug Controller verb
  code/modules/admin/debug_verbs.dm
  code/modules/admin/holder.dm
Labels: Administration

#14082 Clarifies Smart Pistol Vendor Purchase
  code/__DEFINES/loadout.dm
Labels: Grammar and Formatting

#14089 Fix some missing stack singular names
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/items/stacks/sheets/mineral.dm
Labels: Fix

#14085 Updates freelancers to 2023
  code/datums/jobs/job/freelancers.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/suits/marine_armor.dm
Labels: Balance

#14098 Changes xeno ranks to hatchling - ancient
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Grammar and Formatting

#14094 Remove gorger weed speed penalty
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
Labels: Balance

#14097 The Judge has been found guilty. (Walance)
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/revolvers.dm
Labels: Balance

#14107 Lawanka tcomms fix
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
Labels: Fix, Map Edit

#14086 Ports CTRL+SHIFT Click from TG for admins
  code/_onclick/click.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Administration

#14073 Removes BR's marshall's disk spawn from all modulars
  _maps/modularmaps/big_red/bigredlzvar1.dmm
  _maps/modularmaps/big_red/bigredlzvar2.dmm
  _maps/modularmaps/big_red/bigredlzvar3.dmm
  _maps/modularmaps/big_red/bigredlzvar4.dmm
  _maps/modularmaps/big_red/bigredlzvar5.dmm
  _maps/modularmaps/big_red/bigredlzvar6.dmm
  _maps/modularmaps/big_red/bigredlzvar7.dmm
  _maps/modularmaps/big_red/bigredlzvar8.dmm
Labels: Removal, Balance, Map Edit

#14106 Some minor fixes.
  code/_onclick/hud/ghost.dm
  code/game/objects/items/storage/belt.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/clothing/suits/wiz_robe.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Fix, Quality of Life

#14105 Vending machines now restock adjacent items.
  code/game/objects/machinery/vending/vending.dm
Labels: Feature

#13953 Adds CLF specialist to CLF ERT, and 2 guns for it.
  code/__DEFINES/calibers.dm
  code/datums/emergency_calls/clf.dm
  code/datums/jobs/job/clf.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/Marine/clf_heavyrifle.dmi
  icons/Marine/gun64.dmi
  icons/Marine/marine-weapons.dmi
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/ammo_left.dmi
  icons/mob/inhands/weapons/ammo_right.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/items_righthand_64.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  sound/weapons/guns/fire/dpm.ogg
  sound/weapons/guns/fire/ptrs.ogg
  sound/weapons/guns/interact/dpm_reload.ogg
  sound/weapons/guns/interact/dpm_unload.ogg
Labels: Sprites, Sound, Feature

#14102 Hyperscales Guns: Take 3
  code/__DEFINES/greyscale_guns.dm
  code/datums/components/attachment_handler.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/attachments.json
  code/datums/greyscale/json_configs/attachments_64.json
  code/datums/greyscale/json_configs/gun.json
  code/datums/greyscale/json_configs/gun_hands.json
  code/datums/greyscale/json_configs/gun_mob.json
  code/datums/greyscale/json_configs/gun_pistol.json
  code/datums/greyscale/json_configs/gun_revolver.json
  code/datums/greyscale/json_configs/gun_shotgun.json
  code/datums/greyscale/layer.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/holsters.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/Marine/attachments_64.dmi
  icons/Marine/greyscale_gun/attachments.dmi
  icons/Marine/greyscale_gun/attachments_64.dmi
  icons/Marine/greyscale_gun/back.dmi
  icons/Marine/greyscale_gun/gun.dmi
  icons/Marine/greyscale_gun/gun_64.dmi
  icons/Marine/greyscale_gun/l_hand.dmi
  icons/Marine/greyscale_gun/l_hand_64.dmi
  icons/Marine/greyscale_gun/r_hand.dmi
  icons/Marine/greyscale_gun/r_hand_64.dmi
  icons/Marine/greyscale_gun/suit.dmi
  tgmc.dme
Labels: Sprites, Feature, Test Merge Candidate

#14093 Ports select equipment from TG
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/datums/outfit.dm
  code/game/objects/items.dm
  code/game/objects/items/cloaking.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/admin/holder.dm
  code/modules/admin/outfit_editor.dm
  code/modules/admin/outfit_manager.dm
  code/modules/admin/outfits.dm
  code/modules/admin/verbs/selectequipment.dm
  code/modules/client/preferences.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/dummy.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/OutfitEditor.js
  tgui/packages/tgui/interfaces/OutfitManager.js
  tgui/packages/tgui/interfaces/SelectEquipment.js
Labels: Administration, UI

#14020 Adds cleanbots, refactors some Roomba behavior to be more generic
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  code/datums/gamemodes/_game_mode.dm
  code/game/objects/machinery/bots/bots.dm
  code/game/objects/machinery/bots/cleanbot.dm
  code/game/objects/machinery/bots/roomba.dm
  icons/obj/aibots.dmi
  tgmc.dme
Labels: Sprites, Map Edit, Feature

#14114 Attached gun fix
  code/modules/projectiles/gun_system.dm
Labels: Fix

#14115 SG62 hvh loadout
  code/datums/quick_load_outfits.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Feature

#14111 Restricts boiler from rooting while resting.
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Fix

#14112 Adds balloon alert for when warrior tries to grab something in agility mode.
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
Labels: Quality of Life

#14119 Halloween Present: Add Dashe armor to UNITE THE REALMS
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/visors.json
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/arm_plates.dm
  code/modules/clothing/modular_armor/attachments/chest_plates.dm
  code/modules/clothing/modular_armor/attachments/leg_plates.dm
  code/modules/clothing/modular_armor/attachments/visors.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/mark_one/dashe.dmi
  icons/mob/modular/visors.dmi
Labels: Sprites, Feature

#14118 Adjusts the amount of supply points lower tier castes gives
  code/modules/requisitions/supply_export.dm
Labels: Balance

#14125 adds the two new icc guns to valhalla
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#14120 Atomization of #14116
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/reagent_container.dm
Labels: Code Improvement, Grammar and Formatting

#14109 Pill packets can be restocked.
  code/__DEFINES/equipment.dm
  code/_globalvars/bitfields.dm
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/machinery/vending/vending.dm
Labels: Feature

#14103 Reverts TE-X Ray Rifle to its first iteration
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/energy.dm
  icons/effects/particles/generic_particles.dmi
Labels: Sprites, Balance

#14128 Overhead campaign objective timers
  code/game/objects/effects/countdown.dm
  code/game/objects/structures/campaign_structures/capture_objectives.dm
Labels: Quality of Life

#14145 More campaign asset icons
  code/_globalvars/lists/flavor_misc.dm
  code/datums/gamemodes/campaign/campaign_rewards.dm
  icons/UI_Icons/campaign_icons.dmi
  icons/UI_Icons/map_blips.dmi
  icons/mob/hud.dmi
Labels: Sprites

#14132 Teleporter blocker sprite
  code/game/objects/structures/campaign_structures/deploy_blockers.dm
  icons/obj/structures/campaign/tele_blocker.dmi
Labels: Sprites

#14134 Loadout tweaks
  code/datums/jobs/job/sons_of_mars_shipside.dm
  code/datums/quick_load_outfits.dm
Labels: Balance

#14136 Breaching axe nerf
  code/game/objects/items/weapons/twohanded.dm
Labels: Balance

#14091 Makes Prison Station a HvH only map
  code/datums/gamemodes/_game_mode.dm
Labels: Removal

#14140 Fix an exploit allowing you to make C4 instant.
  code/game/objects/items/explosives/plastique.dm
Labels: Fix, In Game Exploit

#14099 Runner changes: quality of life and refactoring
  code/__DEFINES/atom_hud.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/game/data_huds.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  icons/Xeno/actions.dmi
  icons/mob/hud.dmi
Labels: Sprites, Removal, Balance, Refactor, Fix, Feature, Grammar and Formatting, Quality of Life

#14143 firesupport bino QOL
  code/datums/fire_support.dm
  code/game/objects/items/firesupport_binoculars.dm
Labels: Quality of Life

#14139 Removes an evil operator & improves some neuro sanity.
  code/modules/reagents/reagents/toxin.dm
Labels: Removal, Code Improvement, Fix

#14127 Maptable fixes
  code/game/objects/machinery/cic_maptable.dm
Labels: Fix

#14137 Improves faction asset code
  code/datums/gamemodes/campaign/campaign_rewards.dm
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Code Improvement

#14131 HvH pod code improvements
  code/game/objects/structures/droppod.dm
Labels: Fix

#14130 Hyperscales more guns
  code/__DEFINES/greyscale_guns.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/attachments.json
  code/datums/greyscale/json_configs/gun_fire.json
  code/datums/greyscale/json_configs/gun_plasma_pistol.json
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/smgs.dm
  icons/Marine/greyscale_gun/attachments.dmi
  icons/Marine/greyscale_gun/back.dmi
  icons/Marine/greyscale_gun/gun.dmi
  icons/Marine/greyscale_gun/gun_64.dmi
  icons/Marine/greyscale_gun/l_hand.dmi
  icons/Marine/greyscale_gun/l_hand_64.dmi
  icons/Marine/greyscale_gun/r_hand.dmi
  icons/Marine/greyscale_gun/r_hand_64.dmi
  icons/Marine/greyscale_gun/suit.dmi
  icons/Marine/marine-weapons.dmi
Labels: Sprites, Feature

#14150 Delete all instances of Grid for Stack
  tgui/docs/component-reference.md
  tgui/packages/tgui/components/Grid.js
  tgui/packages/tgui/components/index.js
  tgui/packages/tgui/interfaces/PlayerPreferences/BackgroundInformation.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/GearCustomisation.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
  tgui/packages/tgui/interfaces/common/AccessList.js
Labels: Code Improvement, UI

#14108 TTS update
  code/__DEFINES/tts.dm
  code/controllers/subsystem/tts.dm
  code/game/say.dm
  code/modules/client/preferences_ui.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/mob/living/say.dm
  tools/tts/tts-api/off1.wav
  tools/tts/tts-api/off2.wav
  tools/tts/tts-api/off3.wav
  tools/tts/tts-api/off4.wav
  tools/tts/tts-api/on1.wav
  tools/tts/tts-api/on2.wav
  tools/tts/tts-api/tts-api.py
Labels: Tools, Quality of Life

#14154 Campaign RTB stun
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Quality of Life

#14163 Missing smartrifle asset
  code/datums/gamemodes/campaign/campaign_rewards.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/items/storage/belt.dm
Labels: Fix

#14162 Resin node examine change
  code/game/objects/effects/weeds.dm
Labels: Fix

#14153 Campaign strategic reserve tweak
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_rewards.dm
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Balance

#14166 Fix a missing trailing space before pod dchat announcement
  code/game/objects/structures/droppod.dm
Labels: Fix

#14159 increases sg62 target rifle bullet range
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#14147 Mech stomp
  code/modules/vehicles/mecha/_mecha.dm
Labels: Feature

#14152 Campaign status uses static data
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Code Improvement

#14173 Spellchecked some bot messages
  code/game/objects/machinery/bots/bots.dm
Labels: Grammar and Formatting

#14176 Fixes Lagun Powerpack icons. Cleans up the hyperscale .json a little
  code/datums/greyscale/_greyscale_config.dm
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/gun.json
  code/datums/greyscale/json_configs/gun_pistol.json
  code/datums/greyscale/json_configs/gun_plasma_pistol.json
  code/modules/projectiles/guns/energy.dm
  icons/Marine/greyscale_gun/gun_64.dmi
Labels: Sprites, Fix

#14149 Xeno fade in on spawn and evolution
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/new_player/new_player.dm
Labels: Feature

#14148 explosions clear smoke
  code/game/objects/effects/effect_system/smoke.dm
Labels: Balance

#14182 Fixes View Variables not opening via HrefToken
  code/modules/admin/verbs/datumvars.dm
  html/statbrowser.js
Labels: Fix

#14157 SOM background fluff info
  code/modules/mob/new_player/new_player.dm
Labels: Feature

#14158 Gives hivemind queen-level psychic cure instead of shrike-level psychic cure
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
Labels: Balance

#13969 Adds roundstart heavy weapon rotation.
  code/controllers/subsystem/persistence.dm
  code/game/objects/machinery/mortar.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Feature

#14180 Campaign UI improvements
  code/datums/gamemodes/campaign/faction_stats.dm
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignAssets.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignMissions.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignOverview.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignPurchase.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/index.tsx
Labels: Fix, UI, Quality of Life

#14183 Campaign support roles
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Iteron/Iteron.dmm
  code/__DEFINES/jobs.dm
  code/_globalvars/lists/game_modes.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sons_of_mars_shipside.dm
  code/game/objects/effects/landmarks/marine_spawns.dm
  code/game/objects/items/storage/holsters.dm
  code/modules/clothing/gloves/marine_gloves.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/clothing/belt.dmi
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/uniforms/ert_uniforms.dmi
  icons/mob/hud.dmi
  icons/mob/inhands/clothing/uniforms_left.dmi
  icons/mob/inhands/clothing/uniforms_right.dmi
  icons/mob/landmarks.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/uniforms/ert_uniforms.dmi
Labels: Sprites, Map Edit, Feature

#14184 Sprite fixes
  code/game/objects/items/blink_drive.dm
  code/modules/projectiles/magazines/energy.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/equipment/backpacks_left.dmi
  icons/mob/inhands/equipment/backpacks_right.dmi
  icons/obj/items/storage/storage.dmi
Labels: Sprites

#14188 Reduces Puppeteer's max puppets to 3
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
Labels: Balance

#14186 Sawn-off shotgun must now be wielded to fire
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance

#14190 synth has a melee damage malus
  code/datums/skills.dm
Labels: Balance

#14177 Ravager endure vali slowdown protection
  code/datums/status_effects/debuffs.dm
Labels: Balance

#14189 maptable fixes
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Iteron/Iteron.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/combat_patrol_base/combat_patrol_base.dmm
  code/game/objects/machinery/cic_maptable.dm
Labels: Code Improvement, Map Edit

#14194 Instant asset fix
  code/datums/gamemodes/campaign/campaign_rewards.dm
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Fix

#14199 Adds the cement protein bar
  code/game/objects/items/marine_gear.dm
Labels: Feature

#14198 SOM officer prefs
  tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
Labels: Fix, UI

#14196 Fixes Lasguns inhands
  code/modules/projectiles/guns/energy.dm
Labels: Fix

#14165 berry bar and pouch
  code/game/objects/effects/spawners/random/misc_item.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/trash.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  icons/Marine/marine-pouches.dmi
  icons/obj/items/food/packaged.dmi
  icons/obj/items/trash.dmi
  tgmc.dme
Labels: Sprites, Feature

#14193 Campaign asset reorg
  code/datums/gamemodes/campaign/campaign_assets.dm
  code/datums/gamemodes/campaign/campaign_rewards.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/missions/asat_capture.dm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/datums/gamemodes/campaign/missions/mech_wars.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
  code/datums/gamemodes/campaign/missions/supply_raid.dm
  code/datums/gamemodes/campaign/missions/teleporter_raid.dm
  code/datums/gamemodes/campaign/rewards/allies.dm
  code/datums/gamemodes/campaign/rewards/attrition_mods.dm
  code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
  code/datums/gamemodes/campaign/rewards/disablers.dm
  code/datums/gamemodes/campaign/rewards/drop_pods.dm
  code/datums/gamemodes/campaign/rewards/equipment.dm
  code/datums/gamemodes/campaign/rewards/fire_support.dm
  code/datums/gamemodes/campaign/rewards/mechs.dm
  code/datums/gamemodes/campaign/rewards/reserves.dm
  code/datums/gamemodes/campaign/rewards/teleporter.dm
  tgmc.dme
Labels: Code Improvement

#14208 Fixes puppeteer evolution threshold
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
Labels: Fix

#14205 Autobalance Fix
  code/controllers/subsystem/monitor.dm
Labels: Fix

#14164 Draw order UI
  code/__DEFINES/equipment.dm
  code/__DEFINES/preferences.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/carbon/human/inventory.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/DrawOrder.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/Types.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/index.tsx
Labels: Test Merge Candidate, UI, Quality of Life

#14200 Concrete cades
  _maps/map_files/Campaign maps/orion_2/orionoutpost_2.dmm
  _maps/map_files/Campaign maps/som_base/sombase.dmm
  code/game/objects/structures/barricade.dm
  icons/Marine/barricades.dmi
Labels: Sprites, Map Edit, Feature

#14215 Adds non-tad version of heavy laser
  code/modules/projectiles/guns/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-hmg.dmi
Labels: Sprites, Feature

#14210 Renames Headwear in the Loadout Pref to Surplus.
  code/modules/client/preferences_gear.dm
Labels: Grammar and Formatting

#14222 freelancer fix
  code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
Labels: Fix

#14221 Fix a unsanitized log message
  code/modules/shuttle/marine_dropship.dm
Labels: Security Exploit

#14138 Quality of life changes aswell as a few additions
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
Labels: Balance, Map Edit, Feature, Test Merge Candidate, Quality of Life

#14211 give hivemind psychic whisper
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
Labels: Feature

#14219 Fixes an incredibly minor issue with the clone vats console
  code/game/objects/machinery/cloning/cloning.dm
Labels: Fix

#14213 Rock and Stone.
  code/game/objects/items/weapons/blades.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/inhands/weapons/melee_left.dmi
  icons/mob/inhands/weapons/melee_right.dmi
  icons/obj/items/weapons.dmi
  sound/weapons/heavyhit.ogg
Labels: Sprites, Sound, Feature

#14234 Fixes some CAS oversights
  code/modules/condor/cas_chair.dm
  code/modules/condor/cas_shuttle.dm
  tgui/packages/tgui/interfaces/MarineCasship.tsx
Labels: Fix, UI

#14240 Fix boiler being able to ventcrawl
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
Labels: Fix

#14203 Mission walance
  code/__DEFINES/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/missions/destroy_mission.dm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/datums/gamemodes/campaign/missions/loot_capture.dm
  code/datums/gamemodes/campaign/missions/mech_wars.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
  code/datums/gamemodes/campaign/missions/supply_raid.dm
  code/datums/gamemodes/campaign/rewards/attrition_mods.dm
  code/datums/gamemodes/campaign/rewards/reserves.dm
  code/game/objects/structures/teleporter_array.dm
Labels: Balance

#14239 Ensure saved gear is in gear_datums when loading prefs
  code/modules/client/preferences_savefile.dm
Labels: Fix

#14237 Fix x8 DRPG crate containing only one DRPG
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
Labels: Fix

#14232 SLs may now buy megaphones
  code/__DEFINES/loadout.dm
Labels: Feature

#14218 Adds KTLD sight sunglasses
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/night.dm
  icons/mob/clothing/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Sprites, Feature

#14187 Table fixes.
  code/game/objects/effects/spawners/random/misc_structure.dm
  code/game/objects/items/frames/table_rack.dm
  code/game/objects/structures/tables_racks.dm
Labels: Fix

#14235 Adds protein-bar belt and pouch
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/Marine/marine-pouches.dmi
  icons/obj/clothing/belts.dmi
Labels: Sprites, Feature

#14192 throw bounce change
  code/game/atoms_movable.dm
  code/game/objects/obj_defense.dm
  code/game/turfs/closed.dm
  code/modules/mob/living/living_defense.dm
Labels: Fix, Test Merge Candidate

#13924 Tweaks widow to be more playable.
  code/__DEFINES/dcs/signals.dm
  code/datums/components/jump.dm
  code/datums/components/riding/riding_mob.dm
  code/datums/gamemodes/_game_mode.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/widow.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/mob.dm
Labels: Fix, Feature, Quality of Life

#14104 ghost runechat
  code/modules/mob/say.dm
Labels: Feature

#13858 Gives gnomes a (rare) chance of moving when not observed
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/modularmaps/EORG/basketball.dmm
  code/__DEFINES/is_helpers.dm
  code/_globalvars/lists/objects.dm
  code/game/objects/effects/spawners/random/misc_item.dm
  code/game/objects/items/toys/toys.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  icons/effects/random/misc.dmi
  icons/obj/items/toy.dmi
  sound/voice/gnomelaugh.ogg
Labels: Sprites, Sound, Map Edit, Feature

#14244 Baneling can now watch other xenos while in pod
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm
Labels: Quality of Life

#14246 Evolution overlay runtime error fix
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#14223 Adds a rouny plushie to Pillar of Spring
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Feature

#14224 Adds a rouny plushie to Sulaco
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Map Edit, Feature

#14225 Adds a rouny plushie to Arachne
  _maps/map_files/Arachne/TGS_Arachne.dmm
Labels: Map Edit, Feature

#14250 Mounted gun req and seasonal fix
  code/controllers/subsystem/persistence.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/reqs/supplypacks.dm
Labels: Fix

#14083 Bandana no longer hides facial hair
  code/modules/clothing/masks/breath.dm
Labels: Removal, Stale

#14266 Moly tweak
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Balance

#14257 Emissive stuff
  code/__DEFINES/colors.dm
  code/__DEFINES/lighting.dm
  code/__HELPERS/lighting.dm
  code/game/atoms_movable.dm
  code/game/objects/effects/misc.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items.dm
  code/game/objects/items/blink_drive.dm
  code/game/objects/items/jetpack.dm
  code/game/objects/items/radio/intercom.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/items/weapons/energy.dm
  code/game/objects/machinery/air_alarm.dm
  code/game/objects/machinery/fire_alarm.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/power/apc.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/energy.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/mask.dmi
  icons/mob/inhands/equipment/backpacks_left.dmi
  icons/mob/inhands/equipment/backpacks_right.dmi
  icons/mob/inhands/weapons/melee_left.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/items_righthand_64.dmi
  icons/mob/suit_slot.dmi
  icons/obj/machines/air_alarm.dmi
  icons/obj/machines/apc.dmi
  icons/obj/machines/fire_alarm.dmi
  icons/obj/machines/radio.dmi
  icons/obj/wallframes.dmi
Labels: Sprites, Feature

#14249 Fix xenos resin spitting on space tiles
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#14270 hugger sprite fix
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#14233 Expands on random disks by adding disk sets
  _maps/bigred_v2.json
  _maps/deltastation.json
  _maps/desparity.json
  _maps/gelida_iv.json
  _maps/ice_colony_v2.json
  _maps/icy_caves.json
  _maps/lawanka.json
  _maps/lv624.json
  _maps/magmoor_digsite_iv.json
  _maps/orion_outpost.json
  _maps/prison_station_fop.json
  _maps/research_outpost.json
  _maps/slumbridge.json
  _maps/vapor_processing.json
  code/datums/gamemodes/_game_mode.dm
  code/datums/map_config.dm
  code/game/objects/machinery/computer/nuke_disk_generator.dm
Labels: Code Improvement, Map Edit

#14251 pistol knife buff
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/pistols.dm
  icons/obj/items/ammo.dmi
  icons/obj/items/weapons.dmi
Labels: Sprites, Balance

#14284 Fixes an issue with headwear visor behavior
  code/modules/clothing/modular_armor/modular.dm
Labels: Fix

#14285 baneling overwatch 2
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
Labels: Fix

#14280 Fix a reference to tgstation's issue tracker in tgui
  tgui/public/tgui.html
Labels: UI

#14279 fixed wrong overwatch minimap
  code/controllers/subsystem/minimaps.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/overwatch.dm
Labels: Fix

#14273 More campaign mission stuff
  code/__DEFINES/campaign.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/factions.dm
  code/__DEFINES/mobs.dm
  code/_globalvars/lists/flavor_misc.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/missions/airbase_raid.dm
  code/datums/gamemodes/campaign/missions/asat_capture.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/datums/gamemodes/campaign/missions/comm_uplink.dm
  code/datums/gamemodes/campaign/missions/destroy_mission.dm
  code/datums/gamemodes/campaign/missions/final_mission.dm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/datums/gamemodes/campaign/missions/loot_capture.dm
  code/datums/gamemodes/campaign/missions/mech_wars.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
  code/datums/gamemodes/campaign/missions/raiding_base.dm
  code/datums/gamemodes/campaign/missions/spearhead_assault.dm
  code/datums/gamemodes/campaign/missions/supply_raid.dm
  code/datums/gamemodes/campaign/missions/teleporter_raid.dm
  code/datums/gamemodes/campaign/rewards/attrition_mods.dm
  code/datums/gamemodes/campaign/rewards/reserves.dm
  code/game/objects/machinery/computer/nt_access.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/structures/campaign_props.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  code/game/objects/structures/prop.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
  code/modules/screen_alert/misc_alert.dm
  icons/UI_Icons/campaign_icons.dmi
  icons/UI_Icons/screen_alert_images.dmi
  icons/obj/structures/campaign/tall_structures.dmi
  sound/effects/airhiss.ogg
  tgmc.dme
  tgui/packages/tgui/interfaces/NtAccessTerminal.js
Labels: Sprites, Sound, Code Improvement, UI

#14276 Alkysine now heals ear damage
  code/modules/reagents/reagents/medical.dm
Labels: Balance

#14288 Bricks the brick
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/misc.dm
Labels: Balance

#14294 No more ultimate instinct from defender charge
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
Labels: Fix

#14292 Jump and stun fix
  code/datums/components/jump.dm
  code/datums/status_effects/debuffs.dm
Labels: Fix

#14291 Map table fix
  code/game/objects/machinery/cic_maptable.dm
Labels: Fix

#14277 Fixes razorwires from producing infinite barbed wires.
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/items/stacks/rods.dm
Labels: Balance, Fix

#14287 adds cameras to campaign ship maps
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Iteron/Iteron.dmm
Labels: Fix, Map Edit

#14295 Sentry IFF fix
  code/modules/projectiles/projectile.dm
Labels: Fix

#14293 Adjust imialky hypo
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Balance

#14307 Ports meowsynth and spaceman synthesizer sounds
  code/modules/instruments/instrument_data/fun.dm
  sound/runtime/instruments/synthesis_samples/meowsynth/LICENSE.txt
  sound/runtime/instruments/synthesis_samples/meowsynth/c2.ogg
  sound/runtime/instruments/synthesis_samples/meowsynth/c3.ogg
  sound/runtime/instruments/synthesis_samples/meowsynth/c4.ogg
  sound/runtime/instruments/synthesis_samples/meowsynth/c5.ogg
  sound/runtime/instruments/synthesis_samples/meowsynth/c6.ogg
  sound/runtime/instruments/synthesis_samples/spaceman/LICENSE.txt
  sound/runtime/instruments/synthesis_samples/spaceman/c2.ogg
  sound/runtime/instruments/synthesis_samples/spaceman/c3.ogg
  sound/runtime/instruments/synthesis_samples/spaceman/c4.ogg
  sound/runtime/instruments/synthesis_samples/spaceman/c5.ogg
Labels: Sound

#14272 Vendor emissives
  code/game/objects/machinery/vending/loadout_vendor.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/prop.dm
  icons/obj/machines/computer.dmi
  icons/obj/machines/vending.dmi
Labels: Sprites, Feature

#14092 Replaces the Tad Heavy RR with the Mounted Flak Gun
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar4.dmm
  code/__DEFINES/calibers.dm
  code/game/objects/structures/dropship_equipment.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/projectiles/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-fkgun.dmi
  icons/Marine/marine-hmg.dmi
  icons/mob/ammoHUD.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/projectiles.dmi
Labels: Sprites, Removal, Map Edit, Feature

#13946 Adds custom squads
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/__DEFINES/_radio.dm
  code/datums/jobs/squads.dm
  code/game/objects/items/radio/encryptionkey.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/squad_manager.dm
  code/game/objects/machinery/squad_selector.dm
  code/game/objects/machinery/telecomms/telecomunications.dm
  code/game/say.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/SquadManager.tsx
  tgui/packages/tgui/interfaces/SquadSelector.tsx
Labels: Map Edit, Feature, Administration, Test Merge Candidate, UI

#14281 Attempts to split overwatch cams between factions
  code/__DEFINES/objects.dm
  code/controllers/subsystem/minimaps.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/computer/camera_console.dm
  code/game/objects/machinery/overwatch.dm
  code/game/turfs/turf.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/ai/freelook/cameranet.dm
  code/modules/mob/living/silicon/ai/freelook/chunk.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/shuttle/on_move.dm
Labels: Feature, Test Merge Candidate, Requires Testing

#14269 Crusher toss fix
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Fix

#14297 Creates CEILING_OBSTRUCTED, a middle ground between caves and not caves, and applies it to Lawanka Outpost's Engineering.
  code/__DEFINES/__game.dm
  code/__HELPERS/lighting.dm
  code/_onclick/ai.dm
  code/game/area/lawankaoutpost.dm
  code/game/objects/items/binoculars.dm
  code/game/objects/machinery/mortar.dm
  code/game/turfs/turf.dm
  code/modules/requisitions/fulton.dm
  code/modules/shuttle/navigation_computer.dm
Labels: Balance, Feature, Test Merge Candidate

#14322 Updates Desc Of Radio Backpack
  code/modules/reqs/supply.dm
Labels: Grammar and Formatting

#14243 Hyperscale gloves 2.0
  code/datums/greyscale/json_configs/marine_uniform.json
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/gloves/marine_gloves.dm
  icons/mob/modular/marine_uniform.dmi
Labels: Sprites, Test Merge Candidate

#14142 Examine tweaks - complete xeno examine, armor information
  code/modules/mob/living/carbon/human/examine.dm
Labels: Code Improvement, Feature, Test Merge Candidate

#14321 hide in status fix
  code/_globalvars/lists/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Fix
