Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2023-11, with the labels that each got.

#14353 Changes some of the Hot Drinks Sprites
  icons/obj/items/drinks.dmi
Labels: Sprites

#14347 Moves props on admin level
  _maps/map_files/generic/Admin_Level.dmm
Labels: Fix, Map Edit

#14349 MG-27 no longer accepts suppressors
  code/modules/projectiles/guns/mounted.dm
Labels: Balance

#14342 Deletes unused define
  code/__DEFINES/__game.dm
Labels: Code Improvement

#14341 No more BIG RED Crash
  code/datums/gamemodes/crash.dm
Labels: Balance

#14334 Adds push resistance to warlock while channeling Psychic Shield
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Balance

#14356 drop pod computer fix
  icons/obj/machines/computer.dmi
Labels: Sprites

#14331 Power monitor sprite
  code/modules/power/power_monitor.dm
Labels: Fix

#14355 Syringe Case Valhalla NTMED
  code/game/objects/machinery/vending/vending_types.dm
Labels: Feature

#14327 Fixes slouch hat not having on mob sprite.
  code/modules/clothing/head/head.dm
Labels: Fix

#14335 Medical emissives
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/orion_2/orionoutpost_2.dmm
  _maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm
  _maps/map_files/Campaign maps/som_base/sombase.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Iteron/Iteron.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/big_red/bigredmedbayvar1.dmm
  _maps/modularmaps/big_red/bigredmedbayvar2.dmm
  _maps/modularmaps/big_red/bigredmedbayvar3.dmm
  _maps/modularmaps/big_red/bigredmedbayvar4.dmm
  _maps/modularmaps/big_red/bigredmedbayvar5.dmm
  _maps/modularmaps/big_red/bigredmedbayvar6.dmm
  _maps/modularmaps/big_red/bigredmedbayvar7.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
  _maps/modularmaps/lv624/medbayone.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar2.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar3.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar4.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar2.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar3.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar4.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar5.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/machinery/adv_med.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/cloning/cloning.dm
  code/game/objects/machinery/computer/crew.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/sleeper.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  icons/obj/machines/cloning.dmi
  icons/obj/machines/cryogenics.dmi
  icons/obj/machines/cryogenics2.dmi
Labels: Sprites, Map Edit

#14323 Makes Vali require 1u of Synap instead of 3u.
  code/datums/components/chem_booster.dm
Labels: Balance

#14262 Larva Queue: Now while playing Minions
  code/__DEFINES/dcs/signals.dm
  code/_onclick/hud/ghost.dm
  code/datums/actions/observer_action.dm
  code/datums/components/larva_queue.dm
  code/datums/gamemodes/_game_mode.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  tgmc.dme
Labels: Feature, Test Merge Candidate

#14217 A harvester weapon with Kelotane applies some sunder.
  code/datums/components/harvester.dm
Labels: Balance, Stale

#14352 Adds respawn charge indicator to the baneling explode ability
  code/__DEFINES/action.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Code Improvement, Feature

#14247 New hivelord primo and xeno flowers as primo for all builders
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/xenomorph/xeno_structures.dm
  icons/Xeno/actions.dmi
  icons/obj/items/projectiles.dmi
Labels: Sprites, Balance, Feature, Test Merge Candidate

#14366 Xeno visual improvements
  code/datums/components/overlay_lighting.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living_defense.dm
  icons/Xeno/castes/baneling.dmi
  icons/Xeno/castes/beetle.dmi
  icons/Xeno/castes/behemoth.dmi
  icons/Xeno/castes/boiler.dmi
  icons/Xeno/castes/bull.dmi
  icons/Xeno/castes/carrier.dmi
  icons/Xeno/castes/crusher.dmi
  icons/Xeno/castes/defender.dmi
  icons/Xeno/castes/defiler.dmi
  icons/Xeno/castes/drone.dmi
  icons/Xeno/castes/gorger.dmi
  icons/Xeno/castes/hivelord.dmi
  icons/Xeno/castes/hivemind.dmi
  icons/Xeno/castes/hunter.dmi
  icons/Xeno/castes/king.dmi
  icons/Xeno/castes/larva.dmi
  icons/Xeno/castes/mantis.dmi
  icons/Xeno/castes/praetorian.dmi
  icons/Xeno/castes/puppet.dmi
  icons/Xeno/castes/puppeteer.dmi
  icons/Xeno/castes/queen.dmi
  icons/Xeno/castes/ravager.dmi
  icons/Xeno/castes/runner.dmi
  icons/Xeno/castes/scorpion.dmi
  icons/Xeno/castes/sentinel.dmi
  icons/Xeno/castes/shrike.dmi
  icons/Xeno/castes/spitter.dmi
  icons/Xeno/castes/warlock.dmi
  icons/Xeno/castes/warrior.dmi
  icons/Xeno/castes/widow.dmi
  icons/Xeno/castes/wraith.dmi
Labels: Sprites

#14363 Fixes throw impact not respecting speed
  code/game/atoms_movable.dm
Labels: Fix

#14364 Runners are once again subject to Pointblank shots (PBs)
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Fix

#14263 Icy cave balance changes
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Balance, Stale, Map Edit

#14344 Deletes stacking pipes on Arachne.
  _maps/map_files/Arachne/TGS_Arachne.dmm
Labels: Fix, Map Edit

#14343 Deletes stacking pipes on Prison Station.
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Fix, Map Edit

#14340 Deletes stacking pipes on Magmoor.
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Fix, Map Edit

#14346 Deletes stacking pipes on Iteron.
  _maps/map_files/Iteron/Iteron.dmm
Labels: Fix, Map Edit

#14339 Deletes stacking pipes on Sulaco.
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Fix, Map Edit

#14338 Deletes stacking pipes from Theseus.
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Fix, Map Edit

#14337 Deletes stacking pipes on Ice Colony.
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Fix, Map Edit

#14336 Deletes stacking pipes on Pillar of Spring.
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#14298 Adds Library disk to Big Red, hardsets ETA disk.
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/modularmaps/big_red/bigredlibraryvar1.dmm
  _maps/modularmaps/big_red/bigredlibraryvar2.dmm
  _maps/modularmaps/big_red/bigredlibraryvar3.dmm
Labels: Balance, Map Edit, Feature, Test Merge Candidate

#14373 Xeno fire fix
  code/modules/mob/living/living_defense.dm
Labels: Fix, Test Merge Candidate

#14361 Wall hit changes
  code/modules/mob/living/living_defense.dm
Labels: Fix

#14358 campaign computers and props
  _maps/map_files/Campaign maps/som_base/sombase.dmm
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  code/game/objects/machinery/cic_maptable.dm
  code/game/objects/machinery/computer/som_computer.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/structures/campaign_props.dm
  code/game/objects/structures/landing_signs.dm
  code/game/objects/structures/rocks.dm
  code/modules/power/lighting.dm
  icons/Marine/mainship_props96.dmi
  icons/obj/flora/crystals.dmi
  icons/obj/landing_signs.dmi
  icons/obj/machines/artillery.dmi
  icons/obj/machines/computer.dmi
  icons/obj/structures/campaign/tall_structures.dmi
  tgmc.dme
Labels: Sprites, Map Edit

#14369 Very quick speed pass
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
Labels: Fix

#14368 Amends missing changes in Runner stuff, fixes an issue with Evasion's HUD indicator
  code/__DEFINES/action.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Balance, Fix, Feature

#14314 Adds 3 bottles to NT Med.
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/items/reagent_containers/glass/bottle.dm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Map Edit, Feature

#14372 Better larva queue removal handling
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#14374 Nymph Support Minion
  code/__DEFINES/xeno.dm
  code/modules/ai/presets/xeno_presets.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/nymph/castedatum_nymph.dm
  code/modules/mob/living/carbon/xenomorph/castes/nymph/nymph.dm
  icons/Xeno/castes/nymph.dmi
  tgmc.dme
Labels: Sprites, Feature

#14362 realistic window impacts
  code/game/objects/structures/window.dm
Labels: Balance

#14151 Locks LV to HvH votes only. Sets the default maps to Debugdalus and Vapor Processing
  code/datums/gamemodes/_game_mode.dm
  code/datums/map_config.dm
  config/maps.txt
Labels: Config Update, Removal, Code Improvement

#14380 Fix some broken emissives
  code/game/objects/machinery/cic_maptable.dm
  code/game/objects/machinery/squad_selector.dm
  code/modules/vehicles/mecha/mech_bay.dm
Labels: Fix

#14379 Rocket Sledgehammer Fix
  code/game/objects/items/weapons/twohanded.dm
Labels: Fix

#14371 Removes Harvester Blade From Surplus Clothing Vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal, Code Improvement

#13713 Spiderling ai improvements
  code/__DEFINES/dcs/signals.dm
  code/datums/components/riding/riding_mob.dm
  code/game/buckling.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/widow.dm
  icons/Xeno/Effects.dmi
Labels: Sprites, Fix, Feature

#14396 Fix recoil not working properly with a scope
  code/modules/mob/mob_helpers.dm
Labels: Fix

#14398 Remove useless uses of updateUsrDialog
  code/game/objects/items/portable_vendor.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/vending.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/reagents/machinery/chem_dispenser.dm
Labels: Fix

#14391 Fix runtime in spatial agent shortcut
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#14392 Fix adding slots in job slots panel
  code/__DEFINES/jobs.dm
  code/datums/jobs/job/fallen.dm
Labels: Fix

#14382 Stops banelings from exploding if it's before shutters and they don't have a pod
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
Labels: Quality of Life

#14296 Adds a fumble to baseline pill bottles.
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/items/chemistry.dmi
Labels: Sprites, Feature, Grammar and Formatting

#14402 Fixes LV being voteable on Crash
  code/datums/gamemodes/crash.dm
Labels: Fix

#14404 Cryo directions
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Iteron/Iteron.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  icons/obj/machines/cloning.dmi
  icons/obj/machines/cryogenics2.dmi
Labels: Sprites, Fix, Map Edit

#14401 If you have a stronger acid, you can now click on weaker acid directly to upgrade it.
  code/game/objects/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix, Feature

#14405 Fix: Banelings will no longer bring sticky nades back to their pod upon dying
  code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
Labels: Fix

#14397 Fixes pouches looking empty on spawn while they aren't.
  code/game/objects/items/storage/pouch.dm
Labels: Fix

#14155 Increases resin wall bullet armor
  code/game/turfs/walls/resin.dm
Labels: Balance, Test Merge Candidate

#14308 Ports the CM Canister pouch
  code/game/objects/items/storage/reagent_pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/Marine/marine-pouches.dmi
  tgmc.dme
Labels: Sprites, Feature

#14395 flare throw fix
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Fix

#14370 Makes hiveminds sprite dependent on the type of weed theyre on + new hivemind sprites
  code/game/objects/effects/weeds.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  icons/Xeno/castes/hivemind.dmi
Labels: Sprites, Fix, Feature

#14418 Makes eating pills more fluid
  code/_onclick/click.dm
  code/game/objects/items/reagent_containers/pill.dm
Labels: Balance, Feature

#14411 Fix Defiler inject egg range
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Labels: Fix

#14426 Removes random CIC blast door on smallbury
  _maps/shuttles/tgs_canterbury.dmm
Labels: Removal, Fix, Map Edit

#14421 Filter Supply Beacon Drop Locations if its in the Air
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/objects/machinery/squad_supply/supply_console.dm
Labels: Fix, Quality of Life

#14406 Campaign: Mission parameters
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/game/objects/structures/campaign_structures/deploy_blockers.dm
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignOverview.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/index.tsx
Labels: UI, Quality of Life

#14394 Knockback replacements
  code/__DEFINES/mobs.dm
  code/game/atoms_movable.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Feature

#14423 Adjust reagent pouch ratio
  code/game/objects/items/storage/reagent_pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance, Feature

#14407 Campaign asset fixes
  code/__DEFINES/campaign.dm
  code/__DEFINES/dcs/signals.dm
  code/datums/gamemodes/campaign/campaign_assets.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/rewards/disablers.dm
Labels: Fix, Quality of Life

#14410 Restore rouny runner skin
  icons/Xeno/castes/runner.dmi
Labels: Sprites, Fix

#14420 Cleans up shrike vortex code + fixes it throwing decals around
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Code Improvement, Fix

#14430 Attempts to fix an issue with larva queue
  code/datums/gamemodes/infestation.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#14416 Atomization #14403 Vali harvester sprites
  code/__DEFINES/dcs/signals.dm
  code/datums/components/harvester.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/harvester.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/codex/codex_atom.dm
  icons/mob/inhands/weapons/melee_left.dmi
  icons/mob/inhands/weapons/melee_right.dmi
  icons/mob/inhands/weapons/twohanded_left.dmi
  icons/mob/inhands/weapons/twohanded_right.dmi
  icons/mob/inhands/weapons/vali_left.dmi
  icons/mob/inhands/weapons/vali_right.dmi
  icons/obj/items/vali.dmi
  icons/obj/items/weapons.dmi
  tgmc.dme
Labels: Sprites, Code Improvement

#14400 Removes Big Red's Modular LZ's
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/modularmaps/big_red/bigredlz2var1.dmm
  _maps/modularmaps/big_red/bigredlz2var2.dmm
  _maps/modularmaps/big_red/bigredlzvar1.dmm
  _maps/modularmaps/big_red/bigredlzvar2.dmm
  _maps/modularmaps/big_red/bigredlzvar3.dmm
  _maps/modularmaps/big_red/bigredlzvar4.dmm
  _maps/modularmaps/big_red/bigredlzvar5.dmm
  _maps/modularmaps/big_red/bigredlzvar6.dmm
  _maps/modularmaps/big_red/bigredlzvar7.dmm
  _maps/modularmaps/big_red/bigredlzvar8.dmm
  code/game/objects/effects/spawners/modularmappingspawner.dm
  code/modules/mapping/modular_mapping.dm
Labels: Removal, Map Edit

#14429 Fix orders not being shown in chat
  code/modules/screen_alert/command_alert.dm
Labels: Fix

#14409 Adds base pill bottles to light medical belt
  code/game/objects/items/storage/belt.dm
Labels: Balance

#14408 remove miniscope on recoilless rocket
  code/modules/projectiles/guns/specialist.dm
Labels: Removal

#14433 Fixes a runtime related to AI movement
  code/modules/ai/ai_behaviors/ai_behavior.dm
Labels: Fix

#14434 Fixes an issue with the Runner HUD not updating properly when cancelled
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Fix

#14436 this language purports to only use floats but then doesn't (spiderling runtime fix)
  code/__HELPERS/math.dm
  code/datums/datacore.dm
  code/game/objects/items.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/structures/prop.dm
  code/modules/hydroponics/hydro_tools.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/shuttle/on_move.dm
  code/modules/vehicles/multitile/cm_armored.dm
Labels: Fix

#14431 FK-88 no longer has windup.
  code/modules/projectiles/guns/mounted.dm
Labels: Balance

#14443 Fix SDMM lints
  code/_globalvars/lists/mobs.dm
  code/controllers/master.dm
  code/controllers/subsystem/server_maint.dm
  code/datums/emergency_calls/sons_of_mars_breachers.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/turfs/floor_ground.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppet/abilities_puppet.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#14432 You can now toggle auto aim mode while trying to wield a gun
  code/modules/projectiles/gun_helpers.dm
Labels: Quality of Life

#14447 Fixes Icy Caves APCs
  _maps/map_files/icy_caves/icy_caves.dmm
Labels: Fix, Map Edit

#14449 Ports TG Deathsquad sprites
  icons/mob/clothing/back.dmi
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/headwear/ert_headwear.dmi
  icons/mob/clothing/suits/ert_suits.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/headwear/ert_headwear.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits/ert_suits.dmi
  icons/obj/items/storage/storage.dmi
Labels: Sprites

#14450 chore: add flags_area to bitfields
  code/_globalvars/bitfields.dm
Labels: Administration

#14367 Refuel flamerbag from welding kits
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/tools/maintenance_tools.dm
Labels: Balance, Feature

#14441 emissive droppods
  code/game/objects/structures/droppod.dm
  icons/obj/structures/droppod.dmi
Labels: Sprites

#14460 Decap respawn fix
  code/modules/organs/limb_objects.dm
Labels: Fix

#14365 adds unguided sadar and sg 62 reqtorio
  code/modules/factory/parts.dm
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature

#14459 Chems color defines
  code/__DEFINES/colors.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Code Improvement

#14464 Heavy laser has additional firemodes
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar4.dmm
  code/game/objects/structures/dropship_equipment.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-hmg.dmi
Labels: Sprites, Map Edit, Feature

#14474 Fix pre-game xeno runtimes
  code/game/objects/structures/xeno.dm
  code/game/turfs/walls/resin.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Fix

#14475 Fix custom squad members not showing in manifest
  code/datums/datacore.dm
Labels: Fix

#14458 Refactor NODROP into TRAIT_NODROP
  code/__DEFINES/equipment.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/datums/components/chem_booster.dm
  code/datums/components/deployable_item.dm
  code/datums/elements/strappable.dm
  code/datums/elements/strippable.dm
  code/game/objects/items.dm
  code/game/objects/items/embedding.dm
  code/game/objects/items/storage/internal.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/items/weapons/misc.dm
  code/game/objects/machinery/cryopod.dm
  code/modules/clothing/glasses/night.dm
  code/modules/clothing/gloves/color.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/clothing/under/under.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/carbon_stripping.dm
  code/modules/mob/living/carbon/give.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/vehicles/multitile/tank.dm
Labels: Refactor

#14439 Small map blip update
  icons/UI_Icons/map_blips.dmi
Labels: Sprites

#14469 Allows sticky grenades to be applied to self from your hand
  code/game/objects/items/explosives/grenades/marines.dm
Labels: Balance, Quality of Life

#14481 Reduces xeno rank playtime requirements
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Quality of Life

#14351 Emissive Cameras
  code/game/objects/machinery/camera/camera.dm
  code/modules/mob/living/silicon/ai/ai.dm
  icons/obj/machines/monitors.dmi
Labels: Sprites, Stale

#14461 Russian Red Nerf
  code/modules/reagents/reagents/medical.dm
Labels: Balance

#14492 Revert "Adds a fumble to baseline pill bottles."
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/obj/items/chemistry.dmi
Labels: Sprites, Revert

#14478 Sets reagent pouch draw_mode to default on
  code/game/objects/items/storage/reagent_pouch.dm
Labels: Quality of Life

#14487 Gives Behemoth its own unique map icon instead of sharing the Crusher's
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  icons/UI_Icons/map_blips.dmi
Labels: Sprites

#14494 Pill bottles for all
  code/game/objects/items/storage/pill_packets.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance

#14490 Hugger fix
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#14485 Fixes pouches not updating icon on spawn.
  code/game/objects/items/storage/pouch.dm
Labels: Fix

#14438 Heavy jetpack
  code/__DEFINES/dcs/signals.dm
  code/datums/components/stun_mitigation.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/items/jetpack.dm
Labels: Code Improvement, Feature, Quality of Life

#14440 Campaign fixes
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/game/objects/machinery/computer/nt_access.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/hunter.dm
Labels: Fix, Quality of Life

#14506 Fix lascarbine spread pointblanks shooting past the target
  code/modules/projectiles/projectile.dm
Labels: Fix

#14503 Cocoon doesn't try to process after it releases its victim
  code/game/objects/items/cocoon.dm
Labels: Fix

#14502 TTS mask runtime fix
  code/modules/mob/living/say.dm
Labels: Fix

#14501 Fix SSresinshaping and ping not returning their stat panel entry
  code/controllers/subsystem/ping.dm
  code/controllers/subsystem/processing/resinshaping.dm
Labels: Fix

#14500 Fixes the lobby button runtimes
  code/_onclick/hud/new_player.dm
  code/_onclick/hud/screen_objects/menu_text_objects.dm
Labels: Fix

#14498 Kills portaflashes for real this time
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
Labels: Balance, Map Edit

#14468 Max health code improvements
  code/game/data_huds.dm
  code/game/objects/items/scanners.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/sleeper.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/living_health_procs.dm
  tgui/packages/tgui/interfaces/MedScanner.js
Labels: Code Improvement, UI

#14509 stalemate adjustment
  code/controllers/subsystem/monitor.dm
Labels: Balance

#14514 Emissive acidwells
  code/modules/xenomorph/xeno_structures.dm
  icons/Xeno/acid_pool.dmi
Labels: Sprites

#14513 init sig register stuff
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
Labels: Code Improvement

#14508 Completely re-organizes the Slumbridge area file.
  _maps/map_files/slumbridge/slumbridge.dmm
  code/game/area/slumbridge.dm
Labels: Code Improvement, Fix, Map Edit

#14454 Gets rid of vali spear
  code/game/objects/items/weapons/harvester.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/vali_left.dmi
  icons/mob/inhands/weapons/vali_right.dmi
  icons/obj/items/vali.dmi
Labels: Sprites, Removal

#14445 Teleblock changes
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  code/__DEFINES/dcs/signals.dm
  code/game/objects/effects/tele_blocker.dm
  code/game/objects/items/blink_drive.dm
  code/game/turfs/space.dm
  code/game/turfs/turf.dm
  tgmc.dme
Labels: Fix, Map Edit

#14523 Crash railgun removal
  code/__DEFINES/mode.dm
  code/datums/gamemodes/crash.dm
  code/game/objects/items/binoculars.dm
Labels: Balance

#14534 Fix AI runtimes
  code/controllers/subsystem/minimaps.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#14533 Fix a bunch of spiderling runtimes
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
Labels: Fix

#14532 Fixes a quickbuild bug
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#14535 Renames these two artillery piece ammunition packs in req
  code/modules/reqs/supplypacks.dm
Labels: Fix

#14525 Reduces roundstart grenades from 600->200
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance

#14526 Makes most grenade boxes cheaper.
  code/modules/reqs/supplypacks.dm
Labels: Balance

#14521 Removes the context menu toggle
  code/modules/client/client_defines.dm
  code/modules/client/preferences_toggles.dm
Labels: Removal

#14529 Embed fix
  code/game/objects/items/embedding.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#14545 Fix tadpole being able to land on disks
  code/game/objects/machinery/computer/nuke_disk_generator.dm
Labels: Fix

#14544 Fix some computer emissives
  code/game/objects/machinery/computer/general_air_control.dm
  code/game/objects/machinery/teleporter.dm
Labels: Fix

#14546 Actually adds the Coffee sprites i intended to in the first place
  icons/obj/items/drinks.dmi
Labels: Sprites, Fix

#14462 Russian Red is no longer commonly accessible
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Balance, Stale

#13807 edits armor color names and organization; adds two new armor colors
  code/__DEFINES/modular_armor.dm
  code/datums/gamemodes/campaign/missions/mech_wars.dm
Labels: Fix, Feature

#14563 adds more stuff to valhalla
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Feature

#14559 Fixes valhalla loadout vendor not working in hvh
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#14403 Adjusts harvester chemicals
  code/datums/components/harvester.dm
  code/game/objects/items/weapons/harvester.dm
  icons/mob/inhands/weapons/vali_left.dmi
  icons/mob/inhands/weapons/vali_right.dmi
  icons/obj/items/vali.dmi
Labels: Sprites, Code Improvement, Balance, Feature

#14567 Valhalla Area Compression
  _maps/map_files/generic/Admin_Level.dmm
  code/game/area/valhallastation.dm
Labels: Code Improvement, Map Edit

#14557 re-orders persimmon palette
  code/__DEFINES/modular_armor.dm
Labels: Fix

#14549 Increased chance to gib humans with explosions
  code/__DEFINES/mobs.dm
Labels: Balance

#14555 Ports CM's landing and taking off dropship sounds
  sound/effects/engine_landing.ogg
  sound/effects/engine_startup.ogg
Labels: Sound

#14570 Autoweed exploit fix
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix, In Game Exploit

#14562 Euclide range on projectile stuns
  code/modules/projectiles/ammo_datums.dm
Labels: Balance
