Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2024-01, with the labels that each got.

#14718 Wheelchair refactor
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/lv624/medbayone.dmm
  code/datums/components/riding/riding.dm
  code/datums/components/riding/riding_vehicle.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/modules/vehicles/ridden.dm
  code/modules/vehicles/wheelchair.dm
  tgmc.dme
Labels: Code Improvement, Balance, Refactor, Map Edit

#14733 Fixes injections when targeting non-carbon targets
  code/game/objects/items/reagent_containers/hypospray.dm
Labels: Fix

#14732 Renames The Rear Attach Point
  code/game/objects/structures/dropship_equipment.dm
Labels: Grammar and Formatting

#14731 Xenos/Weeds can no longer hide under Rear Attach Points
  code/game/objects/structures/dropship_equipment.dm
Labels: Balance

#14724 Fix CI deprecation warns
  .github/workflows/ci_suite.yml
Labels: GitHub

#14720 Replaces babel with swc
  tgui/.swcrc
  tgui/babel.config.js
  tgui/jest.config.js
  tgui/package.json
  tgui/webpack.config.js
  tgui/yarn.lock
Labels: UI

#14735 Attack_ai for maptable.
  code/game/objects/machinery/cic_maptable.dm
Labels: Quality of Life

#14717 Unrelenting force fix
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Fix

#14719 Storage exploit fix
  code/modules/clothing/modular_armor/attachments/storage.dm
Labels: Fix

#14715 Campaign overview action button
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/modules/mob/dead/observer/login.dm
  icons/mob/actions.dmi
Labels: Sprites, Quality of Life

#14743 VV topic fix
  code/modules/admin/view_variables/topic.dm
Labels: Fix

#14726 Magmoor canterbury crash site effect fix.
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Fix, Map Edit

#14705 Adds Marine Food Vendors to all ship requisition areas + makes sure all ships have cig vendors
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/shuttles/tgs_bigbury.dmm
Labels: Map Edit, Feature

#14729 Arachne shutters improvements.
  _maps/map_files/Arachne/TGS_Arachne.dmm
Labels: Map Edit, Feature

#14727 Sulaco cleanup.
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  code/game/objects/machinery/doors/poddoor.dm
Labels: Fix, Map Edit

#14742 Add larva embryo to Valhalla's vendor
  code/game/objects/machinery/vending/vending_types.dm
Labels: Quality of Life

#14741 Makes Chameleon Badge, Cape, Kama, and Reflective Belt Easier to Equip
  code/modules/clothing/modular_armor/attachments/cape.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Quality of Life

#14752 Stops a funny admin issue
  code/modules/admin/view_variables/admin_delete.dm
Labels: Administration

#14746 Backend improvement to campaign overview UI
  code/_globalvars/lists/flavor_misc.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/modules/asset_cache/asset_list_items.dm
  icons/UI_Icons/campaign/asset_icons.dmi
  icons/UI_Icons/campaign/mission_icons.dmi
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignAssets.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignMissions.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignOverview.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignPurchase.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/index.tsx
Labels: Sprites, Code Improvement, UI

#14753 Lowercasify "Vars"
  code/__DEFINES/admin.dm
  code/modules/admin/view_variables/debug_variables.dm
Labels: Code Improvement

#14750 move osay and view tags
  code/modules/admin/admin_verbs.dm
  code/modules/admin/tag.dm
Labels: Administration

#14749 Fix/improve some signal examine stuff
  code/datums/components/chem_booster.dm
  code/datums/components/harvester.dm
  code/datums/components/rotation.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Code Improvement, Fix

#14685 AMR lase slows down again on hit, flak slowdown removed.
  code/__DEFINES/conflict.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
Labels: Balance

#14677 AI QOL stuffs (bounty)
  code/controllers/subsystem/minimaps.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/hologram.dm
  code/game/sound.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/README.md
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  tgmc.dme
Labels: Quality of Life

#14757 Hud icon and overlays cleanup
  code/_onclick/hud/ai.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/parallax.dm
  code/_onclick/hud/picture_in_picture.dm
  code/_onclick/hud/radial.dm
  code/_onclick/hud/rendering/plane_master.dm
  code/_onclick/hud/rendering/render_plate.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/_onclick/hud/screen_objects/text_objects.dm
  code/_onclick/hud/xeno/hivemind.dm
  code/_onclick/hud/xeno/larva.dm
  code/_onclick/hud/xeno/xeno.dm
  code/controllers/subsystem/minimaps.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items/storage/storage.dm
  code/modules/buildmode/buildmode.dm
  code/modules/buildmode/buttons.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/living/living_verbs.dm
  code/modules/mob/living/silicon/ai/multicam.dm
  code/modules/mob/mob_movement.dm
  code/modules/screen_alert/misc_alert.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
  code/modules/vehicles/mecha/mecha_ui.dm
Labels: Refactor, Test Merge Candidate

#14736 Removes Tangle grenades from Marine access.
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
Labels: Removal, Balance

#14695 Laser pouch can no longer be used as a magazine for Lasguns or Tesla guns.
  code/modules/projectiles/guns/energy.dm
Labels: Balance

#14759 Ravager and Gorger are now pepperball immune
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#14764 Tweaks health in status tab.
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Quality of Life

#14738 CAS Munitions Revamp, Addition of Bombs.
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/__DEFINES/dropship_equipment.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  icons/Marine/mainship_props.dmi
  icons/Marine/mainship_props64.dmi
  icons/effects/lases.dmi
  sound/voice/plane_vws/shot_bomb.ogg
Labels: Sprites, Sound, Balance, Map Edit, Feature

#14770 Removes the HE GL54 nades from req
  code/modules/reqs/supplypacks.dm
Labels: Removal

#14768 Fixes various strip related bugs (+ an extra runtime)
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon_helpers.dm
  code/modules/mob/living/carbon/carbon_stripping.dm
Labels: Fix

#14773 CQC skill tweaks
  code/__DEFINES/skills.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Balance

#14760 Fix glass being able to be merged into any other glass type
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/big_red/bigredengineeringvar1.dmm
  _maps/modularmaps/big_red/bigredengineeringvar2.dmm
  _maps/modularmaps/big_red/bigredengineeringvar3.dmm
  _maps/modularmaps/big_red/bigredengineeringvar4.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
  _maps/modularmaps/lv624/robotics.dmm
  _maps/shuttles/big_ert.dmm
  _maps/shuttles/tgs_bigbury.dmm
  code/game/objects/effects/spawners/random/engineering.dm
  code/game/objects/items/shards.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/structures/window.dm
  code/modules/codex/entries/stacks_codex.dm
  code/modules/reqs/supplypacks.dm
Labels: Fix, Map Edit

#14778 Possibly fixes some situations that would incorrectly DNR you.
  code/modules/mob/living/carbon/human/life.dm
Labels: Fix

#14697 Adds the retired veteran ERT (bounty)
  code/__DEFINES/_radio.dm
  code/__DEFINES/traits.dm
  code/datums/components/mounted_gun.dm
  code/datums/components/riding/riding_vehicle.dm
  code/datums/emergency_calls/retired.dm
  code/datums/jobs/job/retired.dm
  code/game/objects/items/radio/encryptionkey.dm
  code/game/objects/items/radio/headset.dm
  code/modules/organs/limbs.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/vehicles/_vehicle.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/wheelchair.dm
  tgmc.dme
Labels: Feature

#14781 CAS Icon fixes
  code/game/objects/structures/dropship_ammo.dm
  icons/Marine/mainship_props.dmi
Labels: Sprites, Fix

#14744 removes the shutters on this one big red office variant
  _maps/modularmaps/big_red/bigredofficevar4.dmm
  code/modules/mapping/modular_mapping.dm
Labels: Removal, Map Edit

#14786 Spatial agent glasses have all huds now
  code/datums/jobs/job/other.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
Labels: Quality of Life

#14787 Removes hatchling rank, adds prime
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Removal, Grammar and Formatting

#14791 Throw bounce improvements
  code/__HELPERS/unsorted.dm
  code/game/atoms_movable.dm
Labels: Fix

#14792 Daedalus Changes (#1)
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  code/game/area/daedalusprison.dm
  code/game/turfs/closed.dm
  config/maps.txt
Labels: Config Update, Balance, Map Edit, Grammar and Formatting

#14794 Harvester bicard fix
  code/datums/components/harvester.dm
Labels: Balance, Fix

#14624 New Gorger Primordial Ability: Oppose
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/xeno_buffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
Labels: Removal, Feature

#14795 Defiler egg injecting qol + bugfix
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
Labels: Fix, Quality of Life

#14796 Action visual fix
  code/datums/actions/ability_actions.dm
Labels: Fix

#14623 Splits psy points into tactical and strategic points
  code/__DEFINES/xeno.dm
  code/controllers/subsystem/points.dm
  code/datums/gamemodes/nuclear_war.dm
  code/game/objects/items/cocoon.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/power/groundmap_geothermal.dm
  tgui/packages/tgui/interfaces/BlessingMenu.tsx
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Feature, UI

#14799 Fixes balloon alert for king's primo laser use attempts before shutters are open.
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Fix

#14775 Melee special attacks
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/keybind.dm
  code/__DEFINES/traits.dm
  code/datums/actions/ability_actions.dm
  code/datums/actions/weapon_actions.dm
  code/datums/components/stun_mitigation.dm
  code/datums/keybinding/weapons.dm
  code/game/objects/items/blink_drive.dm
  code/game/objects/items/jetpack.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/twohanded.dm
  icons/mob/actions.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
Labels: Sprites, Balance, UI

#14797 Research Outpost is no longer votable if the gamemode is Nuclear War.
  code/__DEFINES/__game.dm
  code/datums/gamemodes/_game_mode.dm
Labels: Removal

#14803 Removes trange()
  code/__HELPERS/game.dm
Labels: Removal

#14804 Changes The Minion Spawner To Require Tactical Points Instead of Strategic Points
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Balance

#14808 Adds a "Smartguns/IFF" to the valhalla vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Quality of Life

#14809 Fixes some busted stairs in EORG maps
  _maps/modularmaps/EORG/cs_mansion.dmm
  _maps/modularmaps/EORG/cs_militia.dmm
  _maps/modularmaps/EORG/cs_office.dmm
  _maps/modularmaps/EORG/de_inferno.dmm
  _maps/modularmaps/EORG/de_nuke.dmm
Labels: Fix, Map Edit

#14810 Remove the non-smart pistol bundle from sg
  code/__DEFINES/loadout.dm
Labels: Removal

#14811 Fix hud thing I forgor
  code/modules/clothing/glasses/hud.dm
Labels: Fix

#14813 AMR fix
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#14812 APC punch fix
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Fix

#14802 Visible cooldown timer
  code/__DEFINES/action.dm
  code/datums/actions/ability_actions.dm
  code/game/objects/effects/countdown.dm
Labels: Quality of Life

#14776 Refactor toggle for activatable items
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/keybind.dm
  code/datums/actions/ability_actions.dm
  code/datums/actions/action.dm
  code/datums/actions/item_toggles.dm
  code/datums/keybinding/item_toggles.dm
  code/game/objects/items/blink_drive.dm
  code/game/objects/items/jetpack.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
Labels: Sprites, Code Improvement, UI, Quality of Life

#14789 Campaign: New loadout system and perk system
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Iteron/Iteron.dmm
  code/__DEFINES/assert.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/equipment.dm
  code/__HELPERS/traits.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/game_modes.dm
  code/datums/actions/ability_actions.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/individual_stats.dm
  code/datums/gamemodes/campaign/loadout_items.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/belt.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/ears.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/feet.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/gloves.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/head.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/uniform.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/ears.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/eyes.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/feet.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/gloves.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/head.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/mask.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/uniform.dm
  code/datums/gamemodes/campaign/outfit_holder.dm
  code/datums/gamemodes/campaign/perks.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sons_of_mars_shipside.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/clothing/modular_armor/som.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/projectiles/guns/rifles.dm
  icons/UI_Icons/campaign/loadout_item_icons.dmi
  icons/UI_Icons/campaign/perk_icons.dmi
  icons/mob/actions.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/IndividualStats/IndividualLoadouts.tsx
  tgui/packages/tgui/interfaces/IndividualStats/IndividualPerks.tsx
  tgui/packages/tgui/interfaces/IndividualStats/index.tsx
Labels: Sprites, Map Edit, Feature, UI

#14653 Adds Plasma Guns MJP EDITION (Cannon/Rifle)
  code/__DEFINES/conflict.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/codex/entries/guns_codex.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/plasma.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/marine-plasmaguns.dmi
  icons/Marine/marine-weapons.dmi
  icons/effects/overheat.dmi
  icons/mob/clothing/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/radial.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/items_mini.dmi
  icons/obj/items/projectiles.dmi
  icons/obj/items/storage/storage.dmi
  sound/weapons/guns/fire/plasma_fire_blast.ogg
  sound/weapons/guns/fire/plasma_fire_fast.ogg
  sound/weapons/guns/fire/plasma_fire_heavy.ogg
  sound/weapons/guns/fire/plasma_fire_med.ogg
  sound/weapons/guns/interact/gun_overheat.ogg
  sound/weapons/guns/interact/plasma_reload_1.ogg
  sound/weapons/guns/interact/plasma_reload_2.ogg
  sound/weapons/guns/interact/plasma_reload_3.ogg
  sound/weapons/guns/interact/plasma_unload_1.ogg
  sound/weapons/guns/interact/plasma_unload_2.ogg
  sound/weapons/guns/interact/plasma_unload_3.ogg
  tgmc.dme
Labels: Sprites, Sound, Feature

#14798 Kills BR's indoor APC's that controlled outside areas, splits up LZ 2 engi into two areas.
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/modularmaps/big_red/bigredengineeringvar1.dmm
  _maps/modularmaps/big_red/bigredengineeringvar2.dmm
  _maps/modularmaps/big_red/bigredengineeringvar3.dmm
  _maps/modularmaps/big_red/bigredengineeringvar4.dmm
  _maps/modularmaps/big_red/bigredofficevar1.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
  _maps/modularmaps/big_red/bigredofficevar3.dmm
  code/game/area/bigred.dm
Labels: Balance, Map Edit

#14818 Readds and unshitcodes bulletholes
  code/__DEFINES/misc.dm
  code/game/turfs/walls/walls.dm
  code/modules/projectiles/projectile.dm
  icons/effects/bulletholes.dmi
Labels: Sprites, Code Improvement

#14779 Adds Acid pools
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/xenomorph/acid_pools.dm
  icons/UI_Icons/buyable_icons.dmi
  icons/Xeno/3x3building.dmi
  tgmc.dme
Labels: Sprites, Feature

#14819 Xenos can now select a tunnel from the minimap instead of a list
  code/__HELPERS/ai.dm
  code/modules/xenomorph/tunnel.dm
Labels: Quality of Life

#14815 Evasion no longer lets you slash marines
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
Labels: Balance

#14774 Deletes the longtad
  _maps/shuttles/minidropship_combat_tad.dmm
  code/datums/shuttles.dm
Labels: Balance, Map Edit

#14820 Campaign: Various small tweaks loadout/perk tweaks
  code/datums/actions/ability_actions.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/individual_stats.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm
  code/datums/gamemodes/campaign/missions/asat_capture.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
  code/datums/gamemodes/campaign/missions/phoron_capture.dm
  code/datums/gamemodes/campaign/missions/supply_raid.dm
  code/datums/gamemodes/campaign/perks.dm
  tgui/packages/tgui/interfaces/IndividualStats/IndividualLoadouts.tsx
Labels: Balance, UI

#14825 Campaign loadout defaults
  code/datums/gamemodes/campaign/loadout_items.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/belt.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/ears.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/feet.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/gloves.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/head.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/uniform.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/ears.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/eyes.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/feet.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/gloves.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/head.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/mask.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/uniform.dm
Labels: Quality of Life

#14830 BR campaign landmarks
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Fix, Map Edit

#14822 Bunch of weird runtimes that broke one round then never happened again
  code/__HELPERS/logging/attack.dm
  code/__HELPERS/mobs.dm
  code/game/objects/machinery/telecomms/broadcasting.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
Labels: Fix, Test Merge Candidate

#14826 Fix flamer back tank disconnecting with magharness
  code/datums/components/reequip.dm
  code/modules/projectiles/gun_system.dm
Labels: Removal, Fix

#14828 Action fixes
  code/datums/actions/ability_actions.dm
  code/datums/actions/action.dm
  code/datums/actions/item_action.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/modular_armor/attachments.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/projectiles/gun_attachables.dm
Labels: Code Improvement, Fix

#14670 Nerfs scout rifle sunder, buffs penetration
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#14817 Adds resin gargoyles
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/xenomorph/resin_gargoyle.dm
  icons/UI_Icons/buyable_icons.dmi
  icons/UI_Icons/map_blips.dmi
  icons/Xeno/2x2building.dmi
  tgmc.dme
Labels: Sprites, Feature

#14835 Plasma guns no longer spawn in crash, valhalla
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#14836 MarineMed pill bottles can now be restocked in the vendor.
  code/game/objects/items/storage/firstaid.dm
Labels: Quality of Life

#14838 Defibbing a dead marine turns on their camera.
  code/game/objects/items/defibrillator.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Quality of Life

#14827 Adds a prompt to the reload admins verb
  code/modules/admin/server_verbs.dm
Labels: Administration

#14832 Reduces The Cost Of The Minion Spawner
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Balance

#14837 Hopefully actually fixes the AMR
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#14844 SOM light armour fix
  code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
Labels: Fix

#14840 Ghost verb fix
  code/__DEFINES/dcs/signals.dm
  code/controllers/subsystem/ticker.dm
  code/modules/mob/dead/observer/login.dm
Labels: Fix

#14846 porting health analyzer from Paradise
  icons/obj/device.dmi
Labels: Sprites

#14748 2024 tips update
  strings/tips/marine.txt
  strings/tips/meme.txt
  strings/tips/xeno.txt
Labels: Grammar and Formatting

#14845 Auto job tab select for campaign
  code/datums/gamemodes/campaign/individual_stats.dm
  tgui/packages/tgui/interfaces/IndividualStats/IndividualLoadouts.tsx
  tgui/packages/tgui/interfaces/IndividualStats/IndividualPerks.tsx
  tgui/packages/tgui/interfaces/IndividualStats/index.tsx
Labels: UI, Quality of Life

#14841 actually working defaults for campaign
  code/datums/gamemodes/campaign/outfit_holder.dm
Labels: Fix

#14851 Wait 10s in TGS build for ESBuild to exit
  tools/build/build.js
Labels: Tools

#14783 More mapping helpers, unrestricted sides for door access, flickering lights and more
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/door.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/power/lighting.dm
  icons/effects/mapping_helpers.dmi
  icons/obj/doors/overlays.dmi
  icons/obj/lighting.dmi
  sound/effects/lightbuzzloop6.ogg
  sound/effects/lightfizz.ogg
  sound/effects/lightfizz2.ogg
  sound/effects/lightfizz3.ogg
  sound/effects/lightfizz4.ogg
  sound/effects/lightfizz5.ogg
  sound/effects/lightfizz6.ogg
Labels: Sprites, Sound, Feature

#14847 fix east facing mob sprite for sg-62
  icons/mob/items_righthand_1.dmi
Labels: Sprites, Fix

#14762 Interceptor and Special Response ERT redesign
  code/__DEFINES/loadout_variants.dm
  code/datums/jobs/job/special_forces.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/suits/ert_suits.dmi
  icons/mob/clothing/suits/marine_armor.dmi
  icons/mob/clothing/uniforms/ert_uniforms.dmi
Labels: Sprites, Removal, Feature

#14839 Xenos once again block marines diagonally
  code/modules/mob/living/living.dm
Labels: Balance

#14842 Removes Vgrip off SG
  code/modules/projectiles/guns/rifles.dm
Labels: Removal, Balance

#14852 Radiopack and AI drone beacon don't work in deep caves anymore
  code/modules/reqs/supply.dm
  code/modules/vehicles/unmanned/unmanned_droid.dm
Labels: Balance

#14849 Widens the hive status tgui window
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: UI, Quality of Life

#14747 Click Code cleanup
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/dcs/signals/signals_click.dm
  code/_onclick/ai.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/_onclick/observer.dm
  code/datums/components/attachment_handler.dm
  code/datums/components/deployable_item.dm
  code/datums/components/rotation.dm
  code/datums/elements/strappable.dm
  code/datums/keybinding/carbon.dm
  code/datums/keybinding/mob.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/items/reagent_containers/reagent_container.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/projectiles/gun_attachables.dm
  tgmc.dme
Labels: Refactor

#14866 Fix acid pool wrong flags
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Fix

#14859 Fixes the ghost bob animation
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#14848 adds 3 helmet cosmetics
  code/game/objects/items/misc.dm
  code/game/objects/items/toys/cards.dm
  code/modules/client/preferences_gear.dm
  icons/mob/modular/modular_helmet_storage.dmi
  icons/obj/items/items.dmi
  tgmc.dme
Labels: Sprites, Feature

#14861 Fixes Xenomorph pounce bypassing shields & improves it a bit.
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#14862 Gives DBs a 0.7 damage multiplier
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance

#14863 Fixes magharness keeping the item in your suit slot after you take the suit off
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Fix

#14880 Fixes certain click interactions
  code/__DEFINES/dcs/signals.dm
  code/_onclick/click.dm
  code/datums/keybinding/carbon.dm
  code/datums/keybinding/mob.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/structures.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  strings/tips/marine.txt
Labels: Fix

#14879 Ghost bob fix 2
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#14877 Removes Russian Red from standard access in HvX
  code/__DEFINES/loadout.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal

#14882 suitlights to crasher armor
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/clothing/suits/marine_armor.dm
Labels: Feature

#14891 Show statpanel scroll bar only when needed
  html/statbrowser.css
Labels: Fix

#14890 Toggle Weather Sound verb has correct message
  code/modules/client/preferences_toggles.dm
Labels: Fix

#14892 Fix Toggle Ambience verb and delete CHANNEL_AMBIENT
  code/__DEFINES/sound.dm
  code/modules/client/preferences_toggles.dm
Labels: Fix

#14887 fixes puppeteers blessing radial menu icons
  icons/mob/actions.dmi
Labels: Sprites, Fix

#14900 Removes flak vest
  code/game/objects/machinery/vending/marine_vending.dm
  icons/mob/modular/xenonauten.dmi
Labels: Sprites, Removal

#14898 Xenomorph resting rework
  code/__DEFINES/mobs.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/keybinding/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_verbs.dm
Labels: Balance

#14896 Fix spitslash on right click
  code/_onclick/click.dm
Labels: Fix

#14906 The Great Unification of Modules
  code/modules/clothing/modular_armor/attachments/modules.dm
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites

#14857 Nanites purge healing meds but can't be purged (+ a buff to their healing)
  code/game/objects/items/reagent_containers/autoinjectors.dm
  code/modules/reagents/reactions/medical.dm
  code/modules/reagents/reagents/medical.dm
Labels: Balance

#14888 Even more DNR (& defib) fixes.
  code/game/data_huds.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/radio/headset.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Fix

#14872 remove TL-172 Defensive Shield from crash and nuclear war
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance

#14901 crasher with flak stats
  code/modules/clothing/modular_armor/xenonauten.dm
Labels: Feature

#14911 Gives all xenos with acid strong acid during prep
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance, Test Merge Candidate

#14856 Makes beacons a component
  code/__DEFINES/equipment.dm
  code/__DEFINES/loadout.dm
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/controllers/subsystem/minimaps.dm
  code/datums/components/beacon.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/reqs/supply.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/unmanned/unmanned_droid.dm
  tgmc.dme
Labels: Refactor

#14860 Bigred atmos pipes fix.
  _maps/modularmaps/big_red/bigredatmosvar2.dmm
  _maps/modularmaps/big_red/bigredatmosvar3.dmm
  _maps/modularmaps/big_red/bigredatmosvar5.dmm
Labels: Fix, Map Edit

#14907 Magmoor Disk Sets
  _maps/magmoor_digsite_iv.json
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Balance, Map Edit

#14843 New ICC Guard kit, new MG, New heavy armor.
  code/datums/jobs/job/icc.dm
  code/game/objects/items/storage/holsters.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/rifles.dm
  icons/Marine/gun64.dmi
  icons/mob/clothing/back.dmi
  icons/mob/clothing/headwear/ert_headwear.dmi
  icons/mob/clothing/suits/ert_suits.dmi
  icons/mob/items_lefthand_64.dmi
  icons/mob/items_righthand_64.dmi
  icons/obj/clothing/headwear/ert_headwear.dmi
  icons/obj/clothing/suits/ert_suits.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/storage/storage.dmi
Labels: Sprites, Feature

#14909 Evolution Changes
  code/_globalvars/lists/mobs.dm
  code/modules/codex/entries/mobs_codex.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance

#14886 MBX can't be one handed
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance

#14897 Reverts all recent click changes
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/dcs/signals/signals_click.dm
  code/_onclick/ai.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/_onclick/observer.dm
  code/datums/components/attachment_handler.dm
  code/datums/components/deployable_item.dm
  code/datums/components/rotation.dm
  code/datums/elements/strappable.dm
  code/datums/keybinding/carbon.dm
  code/datums/keybinding/mob.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/reagent_containers/reagent_container.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/structures.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/projectiles/gun_attachables.dm
  strings/tips/marine.txt
  tgmc.dme
Labels: Removal, Revert, Test Merge Candidate

#14913 ASL order fix
  code/modules/screen_alert/command_alert.dm
Labels: Balance

#14934 Fix autobalance, miniguns and sadar
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#14850 chat style changes
  code/__DEFINES/chat_filter.dm
  code/__DEFINES/span.dm
  code/__HELPERS/announce.dm
  code/controllers/master.dm
  code/controllers/subsystem/mapping.dm
  code/datums/gamemodes/hvh.dm
  code/datums/gamemodes/infestation.dm
  code/datums/jobs/job/job.dm
  code/game/objects/machinery/computer/intel_computer.dm
  code/modules/admin/fun_verbs.dm
  code/modules/client/client_procs.dm
  code/modules/events/intel_computer.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/orbits/spaceship.dm
  code/modules/screen_alert/command_alert.dm
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
  tgui/packages/tgui-say/styles/colors.scss
Labels: Feature, UI

#14925 Kill most RR in campaign
  code/datums/gamemodes/campaign/loadout_items/SOM/head.dm
Labels: Balance

#14924 Perk additions
  code/_globalvars/lists/flavor_misc.dm
  code/datums/gamemodes/campaign/individual_stats.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm
  code/datums/gamemodes/campaign/outfit_holder.dm
  code/datums/gamemodes/campaign/perks.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/som.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  icons/UI_Icons/campaign/perk_icons.dmi
Labels: Sprites, Balance

#14922 gives specops medic a med skill
  code/datums/jobs/job/special_forces.dm
Labels: Feature

#14920 Reduce SOM bullet armour
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/som.dm
Labels: Balance, Fix

#14915 Campaign autobalance
  code/__DEFINES/campaign.dm
  code/datums/gamemodes/campaign.dm
Labels: Balance

#14916 Campaign VP target reduced to 7
  code/__DEFINES/campaign.dm
Labels: Balance

#14930 Evolution change hot fix
  code/_globalvars/lists/mobs.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix, Test Merge Candidate

#14918 Campaign weapon x tweaks
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Balance

#14923 More campaign loadouts
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Feature

#14858 Adds marine Heavy SMG
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/smgs.dm
  icons/Marine/gun64.dmi
  icons/mob/clothing/back.dmi
  icons/mob/items_lefthand_1.dmi
  icons/mob/items_righthand_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/items_mini.dmi
  sound/weapons/guns/fire/skorpevo.ogg
Labels: Sprites, Sound, Feature

#14937 Ports Energy Sword Sprites
  icons/mob/inhands/weapons/melee_left.dmi
  icons/mob/inhands/weapons/melee_right.dmi
  icons/mob/inhands/weapons/twohanded_left.dmi
  icons/mob/inhands/weapons/twohanded_right.dmi
  icons/obj/items/weapons.dmi
Labels: Sprites

#14917 Xeno AP
  code/_onclick/xeno.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/game/objects/effects/misc.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/flashlight.dm
  code/game/objects/items/reagent_containers/food/cans.dm
  code/game/objects/items/reagent_containers/food/drinks/bottle.dm
  code/game/objects/items/reagent_containers/food/drinks/drinkingglass.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/machinery/computer/HolodeckControl.dm
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/machinery/nuclearbomb.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/ladders.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/open.dm
  code/game/turfs/walls/resin.dm
  code/game/turfs/walls/walls.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_scrubber.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/living/simple_animal/friendly/parrot.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/power/apc/apc_attack.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/power/lighting.dm
  code/modules/shuttle/escape_pod.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/vehicles/multitile/cm_armored.dm
  code/modules/xenomorph/acidwell.dm
  code/modules/xenomorph/jellypod.dm
  code/modules/xenomorph/pherotower.dm
  code/modules/xenomorph/trap.dm
  code/modules/xenomorph/tunnel.dm
  code/modules/xenomorph/xenoplant.dm
Labels: Balance

#14970 Small volkite nerf
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#14969 Radiation nerf
  code/datums/fire_support.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#14971 V-34 speed reduction
  code/modules/projectiles/guns/rifles.dm
Labels: Balance

#14972 Various campaign item points tweaks
  code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
Labels: Balance

#14955 Mech war tower fix
  code/game/objects/structures/campaign_structures/capture_objectives.dm
Labels: Fix

#14943 Hud fix
  code/game/atoms/_atom.dm
Labels: Fix

#14968 campaign loadout fixes
  code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/head.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm
  code/datums/gamemodes/campaign/perks.dm
  code/modules/clothing/modular_armor/som.dm
  code/modules/clothing/modular_armor/xenonauten.dm
Labels: Fix

#14967 Fix campaign BSOD
  code/datums/gamemodes/campaign/missions/airbase_raid.dm
  code/datums/gamemodes/campaign/missions/supply_raid.dm
Labels: Fix
