Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2024-04, with the labels that each got.

#15534 Fixes posters
  code/game/objects/effects/decals/contraband.dm
Labels: Fix

#15539 hotfix for PoS req and tc
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#15463 Warding nerf
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Balance

#15475 Welding repair amount scale off engi skill
  code/game/objects/objs.dm
Labels: Balance

#15488 Reworks Grenade req pricing and reqtorio pricing and yield. Actually adds cloak nade refill to req.
  code/game/objects/items/storage/boxes.dm
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance, Feature

#15491 gives SOs powerloader and engineer skills (so, buff)
  code/datums/skills.dm
Labels: Balance

#15492 lowers CSE leadership by 1 level
  code/datums/skills.dm
Labels: Balance

#15494 Buffs the bulletproof vest to be actually good at stopping bullets
  code/modules/clothing/suits/armor.dm
Labels: Balance

#15504 gives CSE engineering + construction 5, renames skill levels
  code/__DEFINES/skills.dm
  code/datums/skills.dm
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/machinery/computer/computer.dm
  code/modules/power/fusion_engine.dm
Labels: Balance

#15521 ACs can no longer use mech console
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
Labels: Fix

#15518 buffs to veteran ERT and specops ERT skills
  code/datums/jobs/job/retired.dm
  code/datums/jobs/job/special_forces.dm
  code/datums/skills.dm
Labels: Balance

#15522 Some more campaign loadouts
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/field_commander.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/squad_leader.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/standard.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/veteran.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/corpsman.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/field_commander.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/marine.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/smartgunner.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/squad_leader.dm
  code/datums/gamemodes/campaign/perks.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/magazines/flamer.dm
  icons/UI_Icons/campaign/loadout_item_icons.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Fix, Feature

#15531 Campaign mech colours
  code/datums/gamemodes/campaign/missions/mech_wars.dm
  code/datums/gamemodes/campaign/rewards/mechs.dm
Labels: Quality of Life

#15477 Removes dark frost wall cuttable subtype
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  code/game/turfs/closed.dm
Labels: Removal, Do Not Merge, Balance, Map Edit

#15527 Deployment desc update
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/patrol_points.dm
Labels: Quality of Life

#15545 Raiding base fixes
  _maps/map_files/Campaign maps/som_raid_base/som_raiding_base.dmm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/missions/raiding_base.dm
  code/game/area/campaign_maps/som_raiding_base.dm
  icons/obj/structures/stairs.dmi
Labels: Sprites, Fix, Map Edit

#15538 Ghost runtime fix
  code/datums/gamemodes/campaign/faction_stats.dm
  code/modules/mob/mob.dm
Labels: Code Improvement

#15466 Examining Stasis Bodybag now show DNR timer and Defib status (DNR or Almost departed)
  code/game/objects/items/bodybag.dm
Labels: Quality of Life

#15513 Conveyor fix
  code/modules/recycling/conveyor2.dm
Labels: Fix

#15460 Activating supply beacons makes the supply console do a noise
  code/__DEFINES/dcs/signals.dm
  code/datums/components/beacon.dm
  code/game/objects/machinery/squad_supply/supply_console.dm
Labels: Quality of Life

#15546 Campaign mission timer pause
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/traits.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/datums/gamemodes/campaign/missions/raiding_base.dm
  code/game/objects/machinery/computer/nt_access.dm
Labels: Balance

#15551 Make all reagents scannable by default
  code/modules/reagents/reagents.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reagents/reagents/other.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Quality of Life

#15530 adds paramedic labcoat
  code/modules/clothing/suits/labcoat.dm
Labels: Feature

#15575 Update index.tsx
  tgui/packages/tgui/interfaces/Orbit/index.tsx
Labels: Fix, UI

#15557 Red light alert light path fixing and Various icon fixes
  code/datums/marine_main_ship.dm
  code/modules/power/lighting.dm
  code/modules/shuttle/escape_pod.dm
  icons/obj/clothing/glasses.dmi
  icons/obj/lighting.dmi
  icons/obj/stationobjs.dmi
Labels: Sprites, Fix

#15561 Revert "Warding nerf"
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Revert

#15582 Adds new night vision goggles to valhalla vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#15516 Makes the radial menu for all medicine fit all limbs.
  code/_onclick/hud/radial.dm
  code/modules/radial/radial_body_select.dm
Labels: Quality of Life

#15558 Fix infinite reflect
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#15565 Campaign UI colour tweaks
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignAssets.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignMissions.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/CampaignPurchase.tsx
  tgui/packages/tgui/interfaces/CampaignMenu/index.tsx
  tgui/packages/tgui/interfaces/IndividualStats/IndividualLoadouts.tsx
  tgui/packages/tgui/interfaces/IndividualStats/IndividualPerks.tsx
Labels: UI, Quality of Life

#15574 Changed faction comparison docs into multiple tables, added more sections
  docs/faction-design.md
Labels: Code Improvement

#15553 HvH reduced smoke duration and file reorg
  code/game/objects/items/explosives/grenades/explosive_grenades.dm
  code/game/objects/items/explosives/grenades/flares.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/incendiary_grenades.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/explosives/grenades/phosphorus_grenades.dm
  code/game/objects/items/explosives/grenades/rad_grenade.dm
  code/game/objects/items/explosives/grenades/smoke_grenades.dm
  code/game/objects/items/explosives/grenades/sticky_grenades.dm
  code/game/objects/items/explosives/grenades/training_grenade.dm
  icons/obj/items/grenade.dmi
  tgmc.dme
Labels: Sprites, Balance

#15533 Simplifies MT - Ares (Multitank tile) reloading. Refactors some tank code.
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
Labels: Code Improvement, Balance, Refactor

#15566 AI can use evasion
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Feature

#15567 Nymphs and non-minion AI will no longer be suicidal
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/xeno/xeno.dm
  code/modules/ai/presets/xeno_presets.dm
Labels: Feature

#15548 Gelida IV caves can be plasmacut one tile wider
  _maps/map_files/gelida_iv/gelida_iv.dmm
Labels: Balance, Map Edit

#15528 Add extra clone bays to Theseus medical
  _maps/map_files/Theseus/TGS_Theseus.dmm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
Labels: Map Edit, Feature

#15583 Fixes Nade box storage.
  code/game/objects/items/storage/boxes.dm
Labels: Fix

#15588 update smartgunner's job description
  code/datums/jobs/job/marines.dm
Labels: Fix

#15529 Synth vendor edits
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Quality of Life

#15570 Prevents stacking pamphlets
  code/game/objects/items/pamphlets.dm
Labels: Fix

#15505 Tank vendor
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/shuttles/vehicle_supply.dmm
  code/__DEFINES/shuttles.dm
  code/__DEFINES/vehicles.dm
  code/datums/shuttles.dm
  code/game/area/areas/shuttles.dm
  code/game/objects/machinery/gear.dm
  code/modules/reqs/supply.dm
  code/modules/shuttle/shuttle_rotate.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/apc.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/armored/medium_apc.dm
  code/modules/vehicles/armored/small_apc.dm
  code/modules/vehicles/armored/tank_fabricator.dm
  tgui/packages/tgui/interfaces/VehicleSupply.tsx
Labels: Map Edit, Feature, UI

#15509 Enables Assault Crewmen
  code/__DEFINES/jobs.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
Labels: Feature

#15563 Silo calc fix
  code/controllers/subsystem/silo.dm
Labels: Fix, Test Merge Candidate

#15568 LTA-AP spread decrease
  code/modules/vehicles/armored/armored_weapons.dm
Labels: Balance

#15562 Lowers king's phero power from 6 to 4.5
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
Labels: Balance

#15584 Fixes the missing icon for the generic rocket launcher rocket and M30 box magazine
  code/modules/projectiles/magazines/sentries.dm
  code/modules/projectiles/magazines/specialist.dm
Labels: Fix

#15552 More loadout stuff
  code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/squad_leader.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/standard.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/veteran.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm
  code/game/objects/items/explosives/grenades/smoke_grenades.dm
  icons/mob/inhands/weapons/grenades_left.dmi
  icons/mob/inhands/weapons/grenades_right.dmi
  icons/obj/items/grenade.dmi
Labels: Sprites, Balance

#15569 Gives assault crewmen loader pamphlets
  code/datums/jobs/job/shipside.dm
Labels: Feature

#15579 Dirt fix
  code/game/objects/items/tools/shovel_tools.dm
  code/game/turfs/floor_ground.dm
Labels: Fix

#15597 Move the daedalus lz north 1 tile and make space for tank south
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
Labels: Fix, Map Edit

#15604 Removes space locker from theseus
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Removal, Fix, Map Edit

#15608 Add more materials to debugabus + add more glass to the ships
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
Labels: Map Edit, Feature

#15499 Port floor lights from polaris
  code/modules/power/lighting.dm
  icons/obj/lighting.dmi
Labels: Sprites, Feature

#15591 Campaign portrait updates
  icons/UI_Icons/screen_alert_images.dmi
Labels: Sprites

#15502 AT-36 ammo price increase and amount decrease
  code/modules/reqs/supplypacks.dm
Labels: Balance, Fix

#15487 Makes basic med pills and their chem bottles infinite in med vendor and makes analyzers infinite too.
  code/game/objects/machinery/vending/vending_types.dm
Labels: Balance

#15559 Increases AMR flak ammo sunder.
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#15578 Raid base map tweaks
  _maps/map_files/Campaign maps/som_raid_base/som_raiding_base.dmm
  code/game/area/campaign_maps/som_raiding_base.dm
Labels: Balance, Map Edit

#15587 Campaign tweaks
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/datums/gamemodes/campaign/rewards/disablers.dm
  code/datums/gamemodes/campaign/rewards/reserves.dm
  code/datums/gamemodes/campaign/rewards/teleporter.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/structures/patrol_points.dm
  code/game/objects/structures/teleporter_array.dm
  icons/effects/campaign_effects.dmi
  icons/effects/effects.dmi
Labels: Sprites, Balance, Fix, Map Edit, Quality of Life

#15605 Deploy point rework and fluff update
  code/__DEFINES/dcs/signals.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/missions/asat_capture.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/datums/gamemodes/campaign/missions/mech_wars.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
  code/datums/gamemodes/campaign/missions/phoron_capture.dm
  code/datums/gamemodes/campaign/missions/raiding_base.dm
  code/datums/gamemodes/campaign/missions/supply_raid.dm
  code/datums/gamemodes/combat_patrol.dm
  code/datums/gamemodes/hvh.dm
  code/datums/gamemodes/sensor_capture.dm
  code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/structures/patrol_points.dm
  tgmc.dme
Labels: Code Improvement, Feature

#15598 Fixes the overwatch jump camera button not working for the AI + small fixes
  code/game/objects/machinery/hologram.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/admin/server_verbs.dm
Labels: Code Improvement, Fix, Administration

#15580 Mjolnir, a new armor
  code/datums/greyscale/greyscale_configs.dm
  code/datums/greyscale/json_configs/visors.json
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/arm_plates.dm
  code/modules/clothing/modular_armor/attachments/chest_plates.dm
  code/modules/clothing/modular_armor/attachments/leg_plates.dm
  code/modules/clothing/modular_armor/attachments/visors.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/mark_one.dm
  code/modules/clothing/modular_armor/modular.dm
  icons/mob/modular/mark_one/mjolnir.dmi
  icons/mob/modular/mark_two/mjolnir_open.dmi
  icons/mob/modular/visors.dmi
Labels: Sprites, Feature

#15581 Gun skill tweak
  code/modules/projectiles/gun_system.dm
Labels: Balance

#15617 Tad can't land indoors
  code/modules/shuttle/navigation_computer.dm
Labels: Balance

#15616 Mirage changes
  code/__DEFINES/dcs/signals.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Balance, Fix

#15618 Bemo exploit fix
  code/__DEFINES/dcs/signals.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Fix, In Game Exploit

#15622 Fixes clamp bleeders surgery step
  code/modules/mob/living/blood.dm
  code/modules/surgery/generic.dm
Labels: Fix

#15614 Updates Captain loadout. Adds red Captain cloak variant to Captain's locker.
  code/datums/jobs/job/shipside.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
Labels: Removal, Feature

#15611 Several small fixes and improvements
  code/game/objects/effects/overlays.dm
  code/game/objects/items/autopsy_scanner.dm
  code/game/objects/items/binoculars.dm
  code/game/objects/items/tools/misc_tools.dm
  code/game/objects/machinery/overwatch.dm
  code/game/turfs/floor_ground.dm
  code/modules/mob/living/silicon/ai/ai_notifications.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
  icons/mob/AI.dmi
  icons/obj/items/paper.dmi
  icons/obj/items/surgery_tools.dmi
Labels: Sprites, Code Improvement, Fix, Quality of Life

#15599 Clarify body scans in the medHud + Minor fixes
  code/modules/client/preferences_toggles.dm
  code/modules/mob/living/carbon/human/examine.dm
  strings/tips/xeno.txt
Labels: Code Improvement, Grammar and Formatting, Quality of Life

#15590 Removes puppeteer orders ability and scout order, makes attack and recall orders normal abilitys
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/xeno.dm
  code/datums/keybinding/xeno.dm
  code/modules/ai/ai_behaviors/xeno/puppet.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
Labels: Removal, Quality of Life

#15621 Campaign home map edits
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Iteron/Iteron.dmm
  code/game/area/mainship.dm
Labels: Map Edit, Quality of Life

#15577 Light fixture code update
  code/__DEFINES/dcs/signals.dm
  code/datums/marine_main_ship.dm
  code/game/atoms/_atom.dm
  code/game/objects/items/tools/flame_tools.dm
  code/modules/power/light_bulbs.dm
  code/modules/power/lighting.dm
  code/modules/power/lighting_frame.dm
  icons/obj/lighting.dmi
  tgmc.dme
Labels: Sprites, Code Improvement, Fix

#15609 Storage opening QOL
  code/game/objects/items/storage/storage.dm
Labels: Quality of Life

#15620 some announcement qol
  code/__DEFINES/factions.dm
  code/game/objects/structures/orbital_cannon.dm
  code/modules/screen_alert/command_alert.dm
Labels: Grammar and Formatting, Quality of Life

#15613 Makes lascarbine spread stats more in line with combat shotgun buckshot's
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#15592 Increases RG 220 wield delay
  code/modules/projectiles/guns/specialist.dm
Labels: Balance

#15629 Buffs wraith's melee damage, from 20 to 23
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Labels: Balance

#15585 Makes synthetics scannable
  code/modules/mob/living/carbon/human/species_types/synthetics.dm
Labels: Balance

#15631 Bemo typo fix
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Fix, Test Merge Candidate

#15633 Xeno turret fix
  code/modules/projectiles/projectile.dm
Labels: Fix

#15636 Campaign: Improved constitution perk unlocks Tyr/Lorica for all jobs
  code/datums/gamemodes/campaign/loadout_items/SOM/head.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/head.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm
  code/datums/gamemodes/campaign/perks.dm
Labels: Balance

#15625 Arachne QOL Changes
  _maps/map_files/Arachne/TGS_Arachne.dmm
  code/game/area/mainship.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/poddoor.dm
Labels: Map Edit, Quality of Life

#15624 Fire_act consolidation
  code/__DEFINES/objects.dm
  code/datums/components/harvester.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/effects/decals/Cleanable/fuel.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/effects/effect_system/particle_effects.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/explosives/grenades/flares.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/training_grenade.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/machinery/fire_alarm.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/mine_structures.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/stool_bed_chair_nest/xeno_nest.dm
  code/game/objects/structures/window.dm
  code/game/objects/structures/xeno.dm
  code/game/shuttle_engines.dm
  code/game/turfs/floor.dm
  code/game/turfs/floor_ground.dm
  code/game/turfs/floor_types.dm
  code/game/turfs/open_ground.dm
  code/game/turfs/plating.dm
  code/game/turfs/snow.dm
  code/game/turfs/walls/r_wall.dm
  code/game/turfs/walls/resin.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
  code/modules/hydroponics/vines.dm
  code/modules/lighting/lighting_mask/lighting_mask.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
  code/modules/mob/living/carbon/xenomorph/egg.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/living_defense.dm
  code/modules/power/lighting.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/vehicles/mecha/mecha_defense.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
  code/modules/xenomorph/_xeno_structure.dm
  code/modules/xenomorph/acidwell.dm
  code/modules/xenomorph/trap.dm
  code/modules/xenomorph/xeno_turret.dm
Labels: Code Improvement

#15641 fix rogue pixel on mjolnir
  icons/mob/modular/mark_one/mjolnir.dmi
Labels: Sprites, Fix

#15512 Acid smoke now checks for Acid protection instead of bio protection.
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
Labels: Code Improvement, Balance

#15650 Light fix
  code/modules/power/lighting.dm
Labels: Fix

#15642 splits up ammo_datums.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammo_types/ags_ammo.dm
  code/modules/projectiles/ammo_types/energy_ammo.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/mech_ammo.dm
  code/modules/projectiles/ammo_types/microrail_ammo.dm
  code/modules/projectiles/ammo_types/miscellaneous_ammo.dm
  code/modules/projectiles/ammo_types/mortar_ammo.dm
  code/modules/projectiles/ammo_types/pistol_ammo.dm
  code/modules/projectiles/ammo_types/revolver_ammo.dm
  code/modules/projectiles/ammo_types/rifle_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/projectiles/ammo_types/shotgun_ammo.dm
  code/modules/projectiles/ammo_types/smartgun_ammo.dm
  code/modules/projectiles/ammo_types/smg_ammo.dm
  code/modules/projectiles/ammo_types/sniper_ammo.dm
  code/modules/projectiles/ammo_types/turret_ammo.dm
  code/modules/projectiles/ammo_types/tx54_ammo.dm
  code/modules/projectiles/ammo_types/volkite_ammo.dm
  code/modules/projectiles/ammo_types/xenos/energy_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/gas_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/huggers_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/puppeteer_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/widow_xenoammo.dm
  tgmc.dme
Labels: Refactor

#15628 Adds alternate Scout Rifle magazines to reqtorio.
  code/modules/factory/parts.dm
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature

#15635 Allow ghosts to examine miners
  code/game/objects/machinery/miner.dm
Labels: Feature

#15632 Adds a delay when loading magazines from ammo packets
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/magazines/misc.dm
Labels: Balance

#15490 autodoc code comments on __skills.dm define
  code/__DEFINES/skills.dm
Labels: Quality of Life

#15643 Several small cosmetic changes to debugabus + pos
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/shuttles/alamo.dmm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/doors/shutters.dm
Labels: Fix, Map Edit, Quality of Life

#15646 Change FK-88 HE shell description to be less confusing
  code/modules/projectiles/magazines/mounted.dm
Labels: Fix

#15657 Hotfix for acid prot.
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/living.dm
Labels: Fix

#15653 BR is now an actual desert for map variants
  _maps/bigred_v2.json
Labels: Fix, Map Edit

#15655 Removes dead tank code & fixes weapon overlays for non turreted tanks
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/apc.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/armored/medium_tank.dm
  icons/obj/armored/3x3/tank_secondary_gun.dmi
Labels: Sprites, Removal

#15656 Adds APC and Transport Crewmen to the game
  _maps/interiors/apc_medical.dmm
  _maps/interiors/apc_transport.dmm
  code/__DEFINES/access.dm
  code/datums/gamemodes/nuclear_war.dm
  code/datums/interior/_interior.dm
  code/datums/interior/interior_apc.dm
  code/datums/interior/interior_tank.dm
  code/datums/interior/map_templates.dm
  code/modules/reqs/supply.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/apc.dm
  code/modules/vehicles/armored/armored_modules.dm
  code/modules/vehicles/armored/interiors/ammo_rack.dm
  code/modules/vehicles/armored/interiors/chairs.dm
  icons/mob/clothing/headwear/marine_helmets.dmi
  icons/mob/clothing/suits/marine_armor.dmi
  icons/mob/clothing/uniforms/marine_uniforms.dmi
  icons/obj/armored/3x3/apc.dmi
  icons/obj/armored/3x3/apc_interior.dmi
  icons/obj/armored/hardpoint_modules.dmi
  icons/obj/clothing/headwear/marine_helmets.dmi
  icons/obj/clothing/suits/marine_armor.dmi
  icons/obj/clothing/uniforms/marine_uniforms.dmi
  tgmc.dme
Labels: Sprites, Map Edit, Feature

#15668 Stalemate removal
  code/controllers/subsystem/monitor.dm
  code/controllers/subsystem/silo.dm
Labels: Removal

#15669 Robot, non-modular jaegar and xenonauten use armor defines
  code/__DEFINES/conflict.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/xenonauten.dm
Labels: Code Improvement

#15654 Tank treads move fix
  icons/obj/armored/3x3/tank.dmi
Labels: Sprites, Fix

#15658 Fix the accept button for interactive emotes
  code/_onclick/hud/interactive_emotes.dm
Labels: Fix

#15670 Tactical binocular and fuel tank admin logging
  code/game/objects/items/binoculars.dm
  code/game/objects/structures/reagent_dispensers.dm
Labels: Administration, Logging

#15660 Fix other order exploit
  code/modules/screen_alert/command_alert.dm
Labels: Fix

#15648 Fire scream nerf
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
Labels: Quality of Life

#15649 Sandevistan and implant code improvements/fixes
  code/__DEFINES/dcs/helpers.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/implants.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/keybind.dm
  code/__HELPERS/mobs.dm
  code/datums/components/_component.dm
  code/datums/components/after_image.dm
  code/datums/components/jump.dm
  code/datums/elements/shrapnel_removal.dm
  code/datums/keybinding/cyberware.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/implants/implant_chem.dm
  code/game/objects/items/implants/implant_cloak.dm
  code/game/objects/items/implants/implant_neurostim.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/implants/sandevistan.dm
  code/game/objects/items/scanners.dm
  code/game/objects/items/weapons/swords.dm
  code/game/objects/machinery/autodoc.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/mob/mob_helpers.dm
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
  icons/obj/items/implants.dmi
  sound/effects/spinal_implant_off.ogg
  sound/effects/spinal_implant_on.ogg
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
Labels: Sprites, Sound, Code Improvement, Fix, UI

#15459 gives job vendors tag sets for item categories; reorganizes so alike items are grouped together
  code/__DEFINES/loadout.dm
  tgui/packages/tgui/interfaces/MarineSelector.jsx
Labels: Stale, Feature, UI

#15652 Valhalla xenos are of the xeno faction
  code/datums/jobs/job/fallen.dm
Labels: Fix, Test Merge Candidate

#15673 Gives the APC and Tank a horn
  code/__DEFINES/cooldowns.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/armored_actions.dm
  icons/mob/actions/actions_vehicle.dmi
  sound/vehicles/horns/armored_horn.ogg
Labels: Sprites, Sound, Feature

#15678 Jump mod implant
  code/__DEFINES/dcs/signals.dm
  code/datums/components/jump.dm
  code/datums/keybinding/living.dm
  code/game/objects/items/implants/implanter.dm
  code/game/objects/items/implants/jump_mod.dm
  code/modules/admin/fun_verbs.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/living.dm
  tgmc.dme
Labels: Feature

#15675 Perk icon display
  code/datums/gamemodes/campaign/individual_stats.dm
  code/datums/gamemodes/campaign/perks.dm
  icons/UI_Icons/campaign/perk_icons.dmi
  icons/effects/perk_unlock.dmi
  sound/effects/perk_unlock.ogg
Labels: Sprites, Sound, Quality of Life

#15683 Fixes linters failing because of a BR modular
  code/game/area/bigred.dm
Labels: Fix

#15689 vendor UI fix
  tgui/packages/tgui/interfaces/MarineSelector.jsx
Labels: Fix, UI

#15677 Adds working TG crafting
  code/__DEFINES/construction.dm
  code/__DEFINES/crafting.dm
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_mouse.dm
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_x_act.dm
  code/__DEFINES/dcs/signals/signals_reagent.dm
  code/__DEFINES/equipment.dm
  code/__DEFINES/food.dm
  code/__DEFINES/hud.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/obj_flags.dm
  code/__DEFINES/unit_tests.dm
  code/__HELPERS/cmp.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/turfs.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/crafting.dm
  code/_globalvars/lists/objects.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/components/crafting/_recipes.dm
  code/datums/components/crafting/crafting.dm
  code/datums/mind.dm
  code/game/atoms/_atom.dm
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/stack_recipe.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/game/objects/objs.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/windoor_assembly.dm
  code/game/objects/structures/window.dm
  code/modules/asset_cache/assets/crafting.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/reactions.dm
  code/modules/reagents/reagents.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/focus_only_tests.dm
  code/modules/unit_tests/unit_test.dm
  icons/obj/doors/door_assembly2x1.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/PersonalCrafting.tsx
Labels: Sprites, Feature, UI

#15662 Adds back ar-55 to leader vendors
  code/__DEFINES/loadout.dm
Labels: Balance

#15685 makes fc ghmme autoinjector pouch standard; fixes 15665
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Fix

#15674 Cleaned up fire sprites
  icons/effects/fire.dmi
Labels: Sprites

#15612 Bring back banelings as minions
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/xeno.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/ai/presets/xeno_presets.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm
  tgmc.dme
Labels: Feature, Test Merge Candidate

#15687 adds soap to allowed items in medical rig belt
  code/datums/storage/subtypes/belt.dm
Labels: Balance

#15564 Expands Valhalla With A Vehicle Area, Adds Assault Vehicle Category to Valhalla Req Vendor
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Map Edit, Feature

#15688 Make keybind for vehicle honk
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/human.dm
  code/modules/vehicles/armored/armored_actions.dm
Labels: Feature, Quality of Life

#15692 Makes sandevistans a round statistic to show at round end
  code/datums/gamemodes/_game_mode.dm
  code/datums/round_statistics.dm
  code/game/objects/items/implants/sandevistan.dm
Labels: Quality of Life

#15695 Re-organize our reagent files to match TG organization.
  code/modules/reagents/chemistry/colors.dm
  code/modules/reagents/chemistry/holder/holder.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/chemistry/machinery/pandemic.dm
  code/modules/reagents/chemistry/machinery/reagentgrinder.dm
  code/modules/reagents/chemistry/reactions.dm
  code/modules/reagents/chemistry/readme.md
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/cloning.dm
  code/modules/reagents/chemistry/reagents/drinks/alcohol.dm
  code/modules/reagents/chemistry/reagents/drinks/drink.dm
  code/modules/reagents/chemistry/reagents/food.dm
  code/modules/reagents/chemistry/reagents/medical.dm
  code/modules/reagents/chemistry/reagents/other.dm
  code/modules/reagents/chemistry/reagents/toxin.dm
  code/modules/reagents/chemistry/recipes/food_drink.dm
  code/modules/reagents/chemistry/recipes/medical.dm
  code/modules/reagents/chemistry/recipes/other.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/autoinjectors.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/reagents/reagent_containers/dropper.dm
  code/modules/reagents/reagent_containers/food.dm
  code/modules/reagents/reagent_containers/food/burgers.dm
  code/modules/reagents/reagent_containers/food/cans.dm
  code/modules/reagents/reagent_containers/food/condiment.dm
  code/modules/reagents/reagent_containers/food/donuts.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/food/drinks/bottle.dm
  code/modules/reagents/reagent_containers/food/drinks/drinkingglass.dm
  code/modules/reagents/reagent_containers/food/frozen.dm
  code/modules/reagents/reagent_containers/food/mexican.dm
  code/modules/reagents/reagent_containers/food/piecake.dm
  code/modules/reagents/reagent_containers/food/pizzapasta.dm
  code/modules/reagents/reagent_containers/food/sandwich.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/reagents/reagent_containers/food/soupsalad.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/jerrycan.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  tgmc.dme
Labels: Code Improvement

#15571 Adds contextual tutorials
  SQL/database_changelog.txt
  SQL/tgmc-schema.sql
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/colors.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/fonts.dm
  code/__DEFINES/hud.dm
  code/__DEFINES/layers.dm
  code/__DEFINES/matrices.dm
  code/__DEFINES/text.dm
  code/__HELPERS/screen_objs.dm
  code/__HELPERS/view.dm
  code/_onclick/human.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/tutorials.dm
  code/game/objects/items.dm
  code/modules/client/client_procs.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/living.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/tutorials/_tutorial.dm
  code/modules/tutorials/tutorial_instruction.dm
  code/modules/tutorials/tutorials/drop.dm
  code/modules/tutorials/tutorials/switch_hands.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/tutorial_sanity.dm
  config/config.txt
  interface/fonts/Grand9K_Pixel.ttf
  interface/fonts/Pixellari.ttf
  interface/fonts/SpessFont.ttf
  interface/fonts/TinyUnicode.ttf
  interface/fonts/VCR_OSD_Mono.ttf
  interface/fonts/fonts_datum.dm
  interface/fonts/grand_9k.dm
  interface/fonts/license.txt
  interface/fonts/pixellari.dm
  interface/fonts/spess_font.dm
  interface/fonts/tiny_unicode.dm
  interface/fonts/vcr_osd_mono.dm
  tgmc.dme
Labels: Config Update, Feature, SQL

#15706 [Code bounty] Clicking a magazine to tac reload instead of drag
  code/modules/projectiles/gun_helpers.dm
Labels: Quality of Life

#15705 Xeno fire overlay fix
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Fix

#15704 Sentry deployer offset
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#15702 Organ clang fix
  code/modules/organs/organ_objects.dm
Labels: Fix

#15699 vehicle fixes
  code/game/atoms/atom_movable.dm
  code/modules/vehicles/_hitbox.dm
Labels: Fix

#15637 select_reagent() loads new reagent
  code/datums/components/harvester.dm
Labels: Quality of Life

#15712 Add ar-55 to FC vendor
  code/__DEFINES/loadout.dm
Labels: Feature

#15707 Small Pillar of Spring fixes: Spring Edition
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  icons/mob/landmarks.dmi
Labels: Sprites, Map Edit, Quality of Life

#15701 fix crafting ignoring most checks
  code/__DEFINES/crafting.dm
  code/datums/components/crafting/_recipes.dm
  code/datums/components/crafting/crafting.dm
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/stack_recipe.dm
  code/game/objects/structures/barricade.dm
Labels: Fix

#15437 Makes it possible to attack resin doors on help intent
  code/__DEFINES/obj_flags.dm
  code/_onclick/item_attack.dm
  code/game/objects/structures/mineral_doors.dm
Labels: Do Not Merge, Quality of Life

#15717 Shifts tank/apc damage sprite thresholds
  code/modules/vehicles/armored/__armored.dm
Labels: Quality of Life

#15718 Vendor fixes
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
  icons/obj/machines/vending.dmi
Labels: Sprites, Fix

#15714 Announcement/Send Order QoLs (& Alamo takeoff alarm)
  code/__HELPERS/announce.dm
  code/datums/gamemodes/infestation.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/squads.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/events/intel_computer.dm
  code/modules/orbits/spaceship.dm
  code/modules/screen_alert/_screen_alert.dm
  code/modules/screen_alert/command_alert.dm
  sound/AI/ares_online.ogg
  sound/misc/airraid.ogg
  sound/misc/ds_signalled_alarm.ogg
  sound/misc/notice3.ogg
  tgui/packages/tgui/interfaces/MarineDropship.jsx
Labels: Sound, Balance, Feature, UI, Quality of Life

#15730 APC defensive fix
  code/modules/vehicles/armored/apc.dm
Labels: Balance

#15725 Fixes APC having no invisible comm relay
  _maps/interiors/apc_medical.dmm
  _maps/interiors/apc_transport.dmm
Labels: Fix, Map Edit

#15724 Fixes loader phamplets not spawning/size
  code/game/objects/items/pamphlets.dm
Labels: Fix

#15723 Fixes APC having insane ram damage
  code/modules/vehicles/armored/apc.dm
Labels: Balance

#15722 Fixes removed pragma
  tools/ci/od_lints.dm
Labels: Tools, Fix

#15686 buffs autoinjector storage mod by adding 2 more slots
  code/datums/storage/subtypes/internal.dm
Labels: Balance

#15709 Evolution tower nerf
  code/modules/xenomorph/xenotowers.dm
Labels: Balance

#15713 Restores original order for defiler chems
  code/__DEFINES/xeno.dm
Labels: Quality of Life

#15732 Fix powerpacks double reloading
  code/__DEFINES/is_helpers.dm
  code/game/objects/items/weapons/misc.dm
  code/modules/projectiles/gun_helpers.dm
Labels: Fix

#15728 Light tube fix
  icons/obj/lighting.dmi
Labels: Sprites, Fix

#15736 Adds beanbag slug to valhalla vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#15733 Vehicle entry QOL
  code/datums/interior/interior_tank.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/medium_tank.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/mecha_mob_interaction.dm
  code/modules/vehicles/sealed.dm
Labels: Quality of Life
