Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2024-08, with the labels that each got.

#16435 renames an inauspiciously named emoji
  icons/misc/emoji.dmi
Labels: Sprites, Grammar and Formatting

#16425 Airburst fix
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammo_types/ags_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/projectiles/ammo_types/tx54_ammo.dm
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
Labels: Fix

#16423 Deletes projectile lag
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/obj_defense.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/simple_animal/friendly/parrot.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/atv.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Quality of Life

#16424 Fullscreen overlay code improvement
  code/_onclick/hud/fullscreen.dm
Labels: Code Improvement

#16433 Fixes an invisible window frame
  code/game/objects/structures/window_frame.dm
Labels: Fix

#16385 TSX MedScanner, and theme rework
  code/game/objects/items/scanners/health_analyzer.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_ui.dm
  tgui/packages/tgui/index.tsx
  tgui/packages/tgui/interfaces/MedScanner.jsx
  tgui/packages/tgui/interfaces/MedScanner.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
  tgui/packages/tgui/styles/themes/ntos_healthy.scss
  tgui/packages/tgui/styles/themes/ntos_rusty.scss
Labels: Feature, Grammar and Formatting, UI

#16403 Xenos can now place acid instantly during prep phase
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance

#16402 Action code fixes/improvements
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/overwatch.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/actions/action.dm
  code/datums/actions/innate.dm
  code/datums/actions/item_action.dm
  code/datums/actions/item_toggles.dm
  code/datums/actions/order_action.dm
  code/datums/actions/skill.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/squads.dm
  code/datums/outfit.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/machinery/computer/communications.dm
  code/game/objects/machinery/overwatch.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/projectiles/gun_attachables/foldable.dm
  code/modules/projectiles/gun_attachables/muzzle.dm
  code/modules/projectiles/gun_attachables/rail.dm
  code/modules/projectiles/gun_system.dm
  code/modules/screen_alert/command_alert.dm
Labels: Fix, Requires Testing

#16422 V-31 AP sprite tweak
  icons/obj/items/ammo/rifle.dmi
Labels: Sprites

#16426 Fixes looped power on Pillar of Spring
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#16436 fullscreen fixes
  code/_onclick/hud/fullscreen.dm
Labels: Fix

#16437 barricade decon fix
  code/game/objects/structures/barricade.dm
Labels: Fix

#16415 Resin silos give minions the correct hive number
  code/modules/xenomorph/silo.dm
  code/modules/xenomorph/spawner.dm
Labels: Fix

#16434 Campaign - Shuffle team button
  code/datums/gamemodes/campaign.dm
  code/modules/admin/panels/Campaign_panel.dm
  tgui/packages/tgui/interfaces/CampaignAdminPanel.tsx
Labels: Administration, UI

#16343 Flags
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Iteron/Iteron.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/mobs.dm
  code/controllers/subsystem/aura.dm
  code/datums/components/deployable_item.dm
  code/datums/personal_statistics.dm
  code/game/data_huds.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/items/ashtray.dm
  code/game/objects/items/plantable_flags.dm
  code/game/objects/machinery.dm
  code/game/objects/machinery/camera/camera_assembly.dm
  code/game/objects/machinery/deployable.dm
  code/game/objects/machinery/fax.dm
  code/game/objects/machinery/portable_reagent_tank.dm
  code/game/objects/obj_defense.dm
  code/game/objects/objs.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/lamarr_cage.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/other/meter.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/life/handle_status_effects.dm
  code/modules/mob/living/carbon/shock.dm
  code/modules/mob/living/living.dm
  code/modules/power/cable.dm
  code/modules/power/pipecleaners.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/sentries.dm
  code/modules/vehicles/train.dm
  code/modules/vehicles/unmanned/deployable_vehicles.dm
  code/modules/xenomorph/acidwell.dm
  code/modules/xenomorph/tunnel.dm
  icons/mob/hud/aura.dmi
  icons/mob/inhands/items/large_flag_left.dmi
  icons/mob/inhands/items/large_flag_right.dmi
  icons/obj/items/flags/plantable_flag.dmi
  icons/obj/items/flags/plantable_flag_large.dmi
  sound/items/plantable_flag/flag_raised.ogg
Labels: Sprites, Sound, Map Edit, Feature

#16444 AI behavior fix
  code/modules/ai/ai_behaviors/ai_behavior.dm
Labels: Fix

#16447 Kit fix
  code/game/objects/items/stacks/medical.dm
Labels: Fix

#16452 Xeno attack fixes
  code/__DEFINES/dcs/signals/signals.dm
  code/datums/components/riding/riding_mob.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
Labels: Fix

#16445 AI glide fix
  code/modules/ai/ai_behaviors/ai_behavior.dm
Labels: Fix

#16457 Fixes evil goat (and hostile/retaliate animals proccing Retaliate() when hit while dead)
  code/modules/mob/living/simple_animal/hostile/retaliate.dm
Labels: Fix

#16450 Adds ERP
  code/__DEFINES/_radio.dm
  code/__DEFINES/factions.dm
  code/datums/emergency_calls/erp.dm
  code/datums/jobs/job/erp.dm
  code/datums/skills.dm
  code/game/objects/items/explosives/grenades/explosive_grenades.dm
  code/game/objects/items/radio/encryptionkey.dm
  code/game/objects/items/radio/headset.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/modular_armor/attachments/uniform.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  icons/UI_Icons/map_blips.dmi
  icons/mob/inhands/guns/special_left_1.dmi
  icons/mob/inhands/guns/special_right_1.dmi
  icons/obj/items/food/piecake.dmi
  icons/obj/items/guns/special64.dmi
  tgmc.dme
Labels: Sprites, Feature

#16442 Xeno viscontent fix
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Quality of Life

#16428 Introduce a reqtorio valhalla vendor
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Map Edit, Feature

#16451 Removes podlocks on outward facing tadpole windows
  _maps/shuttles/minidropship_outrider.dmm
  _maps/shuttles/minidropship_umbilical.dmm
Labels: Removal, Balance, Map Edit

#16461 Fixes geotherm gens/SMES on LV-759
  _maps/map_files/LV759/LV759.dmm
Labels: Fix, Map Edit

#16462 Fixes Arachne body scanner & sleeper consoles
  _maps/map_files/Arachne/TGS_Arachne.dmm
Labels: Fix, Map Edit

#16378 SL minimap icons + latejoining SLs no longer take over SL status
  code/datums/jobs/job/marines.dm
  code/datums/jobs/squads.dm
  code/game/data_huds.dm
  code/game/objects/items/radio/headset.dm
  icons/UI_Icons/map_blips.dmi
  icons/mob/hud/job.dmi
Labels: Sprites, Feature, Quality of Life

#16463 Adds unboxer to valhalla reqtorio vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#16470 Campaign autobal timing fix
  code/datums/gamemodes/campaign.dm
Labels: Fix

#16468 Increases the cost of HPR/SVD to 300.
  code/modules/reqs/supplypacks.dm
Labels: Balance

#16439 Detpack QOL
  code/game/objects/items/radio/detpack.dm
Labels: Stale, Quality of Life

#16443 Screen warnings for fire/hunger/temp/O2/etc use `throw_alert`
  code/__DEFINES/alerts.dm
  code/__DEFINES/hud.dm
  code/_onclick/hud/alerts.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/carbon_status_procs.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/life/handle_environment.dm
  code/modules/mob/living/carbon/human/life/handle_regular_hud_updates.dm
  code/modules/mob/living/carbon/human/species_types/combat_robots.dm
  code/modules/mob/living/carbon/human/species_types/synthetics.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/tooltip/tooltip.dm
  code/modules/tooltip/tooltip.html
  icons/mob/screen_alert.dmi
Labels: Sprites, Refactor, Fix

#16448 airlock shock fix
  code/game/objects/machinery/doors/airlock.dm
Labels: Stale, Fix

#16476 Coilgun bind fix
  code/modules/vehicles/armored/som_armored_weapons.dm
Labels: Fix

#16475 Sentry density fix
  code/modules/projectiles/sentries.dm
Labels: Fix

#16474 Tank coilgun tweaks
  code/modules/projectiles/ammo_types/rocket_ammo.dm
Labels: Balance

#16473 Campaign SG shotgun access
  code/_globalvars/lists/flavor_misc.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm
  icons/UI_Icons/campaign/loadout_item_icons.dmi
Labels: Sprites, Balance

#16469 Removes smoothing from retractable railings
  code/game/objects/machinery/doors/railing.dm
Labels: Removal, Fix

#16467 Escape pod button fix
  tgui/packages/tgui/interfaces/EscapePod.jsx
Labels: Fix, UI

#16472 Sentry tank fix
  code/modules/projectiles/gun_attachables/rail.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/sentries.dm
Labels: Fix

#16481 Some misc hugger code cleanup
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/mob/living/living_defense.dm
Labels: Code Improvement

#16480 Fixes ghosts being able to make huggers jump out of bags
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#16466 Xenos can no longer damage their own doors
  code/game/objects/structures/xeno.dm
Labels: Fix

#16455 Crest defence buff
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Balance

#16484 AGLS frag fix
  code/modules/projectiles/ammo_types/ags_ammo.dm
Labels: Fix

#16487 Updates the pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub

#16479 Increases the price of SG factory refills
  code/modules/reqs/supplypacks.dm
Labels: Balance

#16485 Suppressor makes bullets less visible
  code/modules/projectiles/projectile.dm
Labels: Feature

#16398 Gives survivors more stuff (and other survivor things)
  code/datums/jobs/job/survivor.dm
  code/datums/skills.dm
  code/datums/storage/subtypes/belt.dm
  code/game/objects/items/tools/kitchen_tools.dm
  code/game/objects/items/weapons/batons.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/clothing/head/head.dm
  code/modules/clothing/spacesuits/rig.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  icons/mob/clothing/headwear/head_0.dmi
  icons/mob/clothing/suits/suit_0.dmi
  icons/mob/inhands/weapons/twohanded_left.dmi
  icons/mob/inhands/weapons/twohanded_right.dmi
  icons/mob/suit_slot.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits/suits.dmi
  icons/obj/items/weapons/twohanded.dmi
Labels: Sprites, Balance, Feature

#16496 Adds missing arrow to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: GitHub

#16492 Tank space fix
  code/modules/vehicles/_hitbox.dm
Labels: Fix

#16498 Fire fixes and code improvement
  code/game/objects/structures/razorwire.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
  code/modules/vehicles/armored/_multitile.dm
Labels: Code Improvement, Fix
