Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2024-07, with the labels that each got.

#16206 TE Powerpack Charge Overlay
  code/modules/projectiles/magazines/energy.dm
  icons/obj/items/ammo/powerpack.dmi
Labels: Sprites

#16207 Fixes inability to create custom squads on sulaco
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Fix, Map Edit

#16209 Fixes webmap
  code/controllers/configuration/entries/general.dm
  interface/interface.dm
Labels: Config Update, Fix

#16201 Fixes doubled-up windows on Outrider
  _maps/shuttles/minidropship_outrider.dmm
Labels: Fix, Map Edit

#16221 LV-759 Clean Up And Balance
  _maps/map_files/LV759/LV759.dmm
  code/game/objects/structures/hybrisa_props.dm
Labels: Balance, Map Edit

#16225 Fixes strain swapping not being instant
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
Labels: Code Improvement, Fix

#16213 Makes large req export histories more readable and less laggy
  code/modules/reqs/supply.dm
  tgui/packages/tgui/interfaces/Cargo.jsx
Labels: UI, Quality of Life

#16214 Campaign DNR fix
  code/datums/gamemodes/campaign.dm
Labels: Fix

#16212 Adds a Valhalla surgery area, modifies the marine spawner xeno button.
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/buttons.dm
Labels: Code Improvement, Map Edit, Feature

#16219 Fixes powerpack worn icon states.
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/specialist.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/ammo_left.dmi
  icons/mob/inhands/weapons/ammo_right.dmi
  icons/obj/items/ammo/powerpack.dmi
Labels: Sprites, Fix

#16227 Adds a sprite for active radiopack
  code/modules/reqs/supply.dm
  icons/obj/items/storage/backpack.dmi
Labels: Sprites, Code Improvement

#16001 Boiler Tweaks
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/projectiles/ammo_types/xenos/gas_xenoammo.dm
Labels: Balance, Stale, Requires Testing

#16191 Engi storage holds miner upgrades
  code/datums/storage/subtypes/internal.dm
Labels: Balance

#16122 Shrike & Hivemind Heals no longer cancels on target movement
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Balance

#16218 Adds visual clarity to kutjevo and riptide windows
  icons/obj/smooth_objects/kutjevo_window_frame.dmi
  icons/obj/smooth_objects/wood_window_frame.dmi
Labels: Sprites

#16200 APC/Tank pathing to Tadpole on Arachne and Theseus
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Fix, Map Edit

#16239 Fixes webmap even if there are spaces in the map name
  interface/interface.dm
Labels: Fix

#16235 Further declutters the export history
  code/modules/reqs/supply.dm
Labels: Quality of Life

#16203 Adds height
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/datums/datum.dm
  code/game/atoms/_atom.dm
  code/game/atoms/atom_movable.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  icons/effects/cut.dmi
Labels: Sprites, Code Improvement

#16233 CLF gets faster suicide vest detonate time
  code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
  code/datums/jobs/job/clf.dm
  code/game/objects/items/explosives/bombvest.dm
Labels: Balance

#16126 Combined Arms mission
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Iteron/Iteron.dmm
  code/__DEFINES/factions.dm
  code/_globalvars/lists/objects.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/missions/mech_wars.dm
  code/datums/gamemodes/campaign/rewards/mechs.dm
  code/game/objects/effects/landmarks/gamemode/campaign_vehicle_spawners.dm
  code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
  code/game/objects/structures/patrol_points.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/som_tank.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/sealed.dm
  icons/effects/campaign_effects.dmi
  icons/effects/landmarks_static.dmi
  tgmc.dme
Labels: Sprites, Map Edit, Feature

#16252 Filter fix
  code/game/atoms/atom_movable.dm
  code/modules/admin/view_variables/filterrific.dm
Labels: Code Improvement

#16243 Window fix
  code/game/objects/structures/window.dm
Labels: Fix

#16232 Shutter fix
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/doors/shutters.dm
  icons/obj/doors/mainship/blastdoors_shutters.dmi
  icons/obj/structures/prop/urban/urbanshutters.dmi
Labels: Sprites, Fix

#16231 LV prop cleanup
  _maps/map_files/LV759/LV759.dmm
  code/game/objects/structures/concrete_planter.dm
  code/game/objects/structures/hybrisa_props.dm
  code/game/objects/structures/large_vehicle_props.dm
  code/game/objects/structures/rocks.dm
  code/game/objects/structures/vehicle_props.dm
  icons/obj/structures/prop/concrete_planter.dmi
  icons/obj/structures/prop/urban/64x64_urbanrandomprops.dmi
  tgmc.dme
Labels: Sprites, Code Improvement, Map Edit

#16241 Truck fix
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/Campaign maps/orion_2/orionoutpost_2.dmm
  _maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm
  _maps/map_files/Campaign maps/som_base/sombase.dmm
  _maps/map_files/Campaign maps/som_raid_base/som_raiding_base.dmm
  _maps/map_files/Campaign maps/tgmc_raid_base/tgmc_raiding_base.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/map_files/riptide/riptide.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/jungle_outpost/joutpostscrates3.dmm
  _maps/modularmaps/jungle_outpost/joutpostscrates4.dmm
  code/game/objects/structures/prop.dm
Labels: Fix, Map Edit

#16244 Removes headsets and ASRS tablets from spawning in Valhalla
  code/game/objects/machinery/buttons.dm
Labels: Removal, Fix

#16264 Expand admin level bounds
  _maps/map_files/generic/Admin_Level.dmm
Labels: Fix, Map Edit

#16256 Dead var death
  code/game/objects/machinery/buttons.dm
Labels: Removal

#16260 Deletes unused icons in `icons/mob/screen/generic.dmi`. Deletes `icons/mob/screen/generic_old.dmi`
  icons/mob/screen/generic.dmi
  icons/mob/screen/generic_old.dmi
Labels: Sprites

#16247 Fixes error icon on blank shotgun shells
  icons/obj/items/ammo/box.dmi
  icons/obj/items/ammo/handful.dmi
  icons/obj/items/ammo/shotgun.dmi
Labels: Sprites, Fix

#16270 Evo sanity checks
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Code Improvement

#16262 Fueltank runtime
  code/game/objects/structures/reagent_dispensers.dm
Labels: Fix

#16265 Tank fixes
  code/modules/vehicles/armored/__armored.dm
  icons/obj/armored/3x4/som_ammo_rack.dmi
Labels: Sprites, Fix

#16245 Optimizes and declutters the requests panel
  code/modules/reqs/supply.dm
  tgui/packages/tgui/interfaces/Cargo.jsx
Labels: Code Improvement, Fix, UI, Quality of Life

#16267 Breech loaded tank magazines
  code/datums/storage/subtypes/tank.dm
  code/game/objects/effects/landmarks/gamemode/campaign_vehicle_spawners.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/armored/interiors/breech.dm
  code/modules/vehicles/armored/som_armored_weapons.dm
  icons/obj/items/ammo/tank.dmi
Labels: Sprites, Feature

#16210 Baselighting fixes/improvements
  code/datums/gamemodes/hvh.dm
  code/game/turfs/turf.dm
  code/modules/lighting/lighting_area.dm
  code/modules/mapping/map_template.dm
Labels: Code Improvement, Test Merge Candidate

#16165 Off-hand shooting
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/mounted.dm
Labels: Feature

#16249 Fixes AI double spawning
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Fix

#16254 Adds SOM tank and it's weapons to Valhalla, adds a mech computer to the vehicle area
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Map Edit, Feature

#16255 Fixes Bravo, Charlie, and Delta squad chat on sulaco
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Fix, Map Edit

#16248 Removes area where marines get trapped podding in on Big Red
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Removal, Balance, Map Edit

#16272 Fixes surgery privacy shutters on pos
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#16263 HvH Deploy point changes
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/Campaign maps/orion_2/orionoutpost_2.dmm
  _maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm
  _maps/map_files/Campaign maps/som_base/sombase.dmm
  _maps/map_files/Campaign maps/som_raid_base/som_raiding_base.dmm
  _maps/map_files/Campaign maps/tgmc_raid_base/tgmc_raiding_base.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Iteron/Iteron.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/LV759/LV759.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/combat_patrol_base/combat_patrol_base.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/map_files/kutjevo/kutjevo.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/map_files/riptide/riptide.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/big_red/bigredcaveswvar1.dmm
  _maps/modularmaps/big_red/bigredcaveswvar2.dmm
  _maps/modularmaps/big_red/bigredcaveswvar3.dmm
  _maps/modularmaps/big_red/bigredcaveswvar4.dmm
  _maps/modularmaps/big_red/bigredcaveswvar5.dmm
  _maps/modularmaps/big_red/bigredsecornervar1.dmm
  _maps/modularmaps/big_red/bigredsecornervar2.dmm
  _maps/modularmaps/big_red/bigredsecornervar3.dmm
  _maps/modularmaps/big_red/bigredsecornervar4.dmm
  _maps/modularmaps/big_red/bigredsecornervar5.dmm
  _maps/modularmaps/big_red/bigredsecornervar6.dmm
  _maps/modularmaps/big_red/bigredsecornervar7.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar2.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar3.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar4.dmm
  code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
  code/game/objects/structures/patrol_points.dm
  icons/UI_Icons/map_blips.dmi
  icons/UI_Icons/map_blips_large.dmi
Labels: Sprites, Map Edit, Feature

#16236 Adds human target practice to Valhalla
  _maps/map_files/generic/Admin_Level.dmm
Labels: Map Edit, Feature

#16275 Adds :trol: emoji
  icons/misc/emoji.dmi
Labels: Sprites, Feature

#16197 Space extinguishes fire
  code/datums/status_effects/debuffs.dm
Labels: Balance

#16279 LTAAP tank in campaign
  _maps/map_files/Iteron/Iteron.dmm
  code/game/objects/effects/landmarks/gamemode/campaign_vehicle_spawners.dm
Labels: Map Edit, Feature

#16222 Corspman can now suture without fumbling
  code/modules/surgery/generic.dm
  code/modules/surgery/surgery.dm
Labels: Code Improvement, Balance

#16271 Gives supply beacons on the minimap the req background colour and a red tip
  icons/UI_Icons/map_blips.dmi
Labels: Sprites, Quality of Life

#16291 Fixes requesting console screen width
  tgui/packages/tgui/interfaces/Cargo.jsx
Labels: Fix, UI

#16294 Gives Isotonic autoinjector a tag
  code/modules/reagents/reagent_containers/autoinjectors.dm
Labels: Quality of Life

#16296 Tracks and rewards healing, repairing, and tanks killed in campaign
  code/datums/personal_statistics.dm
  code/game/objects/obj_defense.dm
  code/game/turfs/walls/walls.dm
  code/modules/vehicles/armored/__armored.dm
Labels: Feature

#16293 Fixes supply tgui bluescreen
  code/modules/reqs/supply.dm
Labels: Fix

#16301 Afterimage actual fix
  code/datums/components/after_image.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
Labels: Fix

#16295 Records kitting
  code/game/objects/items/stacks/medical.dm
Labels: Quality of Life

#16305 Ram fixes
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/vehicle_collision.dm
Labels: Fix

#16306 Patrol mission point changes
  code/datums/gamemodes/campaign/missions/mech_wars.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
Labels: Balance

#16278 C4 ex_act tweak
  code/game/objects/items/explosives/plastique.dm
Labels: Balance

#16285 Direct load fix for tanks
  code/modules/vehicles/armored/__armored.dm
Labels: Fix

#16287 Desant z fix
  code/modules/vehicles/_hitbox.dm
Labels: Fix

#16253 SSD takeover now loads your active character slot
  code/datums/actions/observer_action.dm
  code/datums/gamemodes/_game_mode.dm
Labels: Quality of Life

#16215 xenos can now fully evo pre-shutters
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  tgui/packages/tgui/interfaces/HiveEvolveScreen.tsx
Labels: Balance, UI

#16240 Adds a keybind for canceling landslide
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Feature

#16286 mecha cannon change
  code/modules/projectiles/ammo_types/heavy_ammo.dm
Labels: Balance

#16300 Fixes the reagent scanner's blank icon sprite
  code/game/objects/items/scanners/reagent_scanner.dm
Labels: Fix

#16310 Fixes the technician backpack's error sprite
  icons/obj/items/storage/backholster.dmi
  icons/obj/items/storage/backpack.dmi
Labels: Sprites, Fix

#16277 Sombase map fixes
  _maps/map_files/Campaign maps/som_base/sombase.dmm
Labels: Fix, Map Edit

#16303 Campaign reward table additions
  code/_globalvars/lists/game_modes.dm
  code/game/objects/items/implants/implanter.dm
Labels: Feature

#16307 Campaign vehicle scaling
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/missions/asat_capture.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/datums/gamemodes/campaign/missions/raiding_base.dm
Labels: Balance

#16313 mapper icon fix
  code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
Labels: Code Improvement

#16298 Lets you empty sandbags
  code/game/objects/items/stacks/sandbags.dm
Labels: Feature

#16257 Tguifies server verbs.
  code/modules/admin/server_verbs.dm
Labels: Do Not Merge, Administration

#16322 Removes nutriment from zoom pills
  code/modules/reagents/reagent_containers/pill.dm
Labels: Removal, Balance

#16319 SSD takeover fixes
  code/datums/actions/observer_action.dm
  code/modules/mob/mob_transformation_simple.dm
Labels: Fix

#16316 Queen, Boiler, and Bull can now use their long range vision while resting
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Quality of Life

#16325 Fixes the empty mortar bag icon sprite
  icons/obj/items/storage/backholster.dmi
Labels: Sprites, Fix

#16318 SOM fuel bag
  code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/engineer.dm
  code/game/objects/items/storage/backpack.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/equipment/backpacks_left.dmi
  icons/mob/inhands/equipment/backpacks_right.dmi
  icons/obj/items/storage/backpack.dmi
Labels: Sprites, Balance

#16321 Fixes synthetic isntruments being offkey
  code/modules/instruments/songs/play_synthesized.dm
Labels: Fix

#16330 Random event cleanup
  code/modules/events/hive_threat.dm
  code/modules/events/intel_computer.dm
  code/modules/events/ion_storm.dm
  code/modules/events/stock_uptick.dm
  code/modules/events/supply_drop.dm
Labels: Fix

#16320 DMR no longer has minimum range accuracy, has mildly higher penetration.
  code/modules/projectiles/ammo_types/rifle_ammo.dm
Labels: Balance

#16331 Campaign loadout fixes and improvements
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/engineer.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/medic.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
  code/datums/gamemodes/campaign/perks.dm
Labels: Balance

#16314 Adds tracking for runner snatches
  code/datums/gamemodes/_game_mode.dm
  code/datums/personal_statistics.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Feature

#16259 Adds civil war loadouts
  code/datums/quick_load_civil_war.dm
  code/datums/quick_load_outfits.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/machinery/vending/civil_war_vendor.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/projectiles/ammunition.dm
  tgmc.dme
Labels: Feature

#16281 Updated FK-88 Ammo Refill Prices
  code/modules/reqs/supplypacks.dm
Labels: Balance

#16284 Adjust price of Mortar Smoke/Flare refills
  code/modules/reqs/supplypacks.dm
Labels: Balance

#16290 Adds SG-62 ammo bins to reqtorio
  code/modules/factory/parts.dm
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature

#16268 Fumo Revival
  code/game/objects/items/toys/toys.dm
  code/game/objects/machinery/computer/arcade.dm
  icons/obj/items/toy.dmi
Labels: Sprites, Feature

#16333 Defender can use regenerate skin while resting
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
Labels: Quality of Life

#16329 Adds more intel computers to magmoor
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Map Edit, Feature

#16336 Deletes some useless powerloader code
  code/modules/vehicles/powerloader.dm
Labels: Code Improvement

#16179 Duffelbag tweaks
  code/datums/storage/storage.dm
  code/game/objects/items/storage/backpack.dm
Labels: Balance

#16315 Brings the medic medkit pouch in line with the advanced autoinjector pouch
  code/__DEFINES/loadout.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sons_of_mars_shipside.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Balance

#16326 Boiler: Acid shroud + extra boiler balance
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/projectiles/ammo_types/xenos/gas_xenoammo.dm
  icons/Xeno/actions/boiler.dmi
Labels: Sprites, Balance, Feature

#16335 Updates the TGMC Campaign tank's description
  code/modules/vehicles/armored/_multitile.dm
Labels: Grammar and Formatting

#16341 Fixes stalagmites
  code/game/objects/structures/rocks.dm
  icons/obj/flora/rock_large.dmi
  icons/obj/flora/rocks2.dmi
  icons/obj/structures/boulder_small.dmi
  icons/obj/structures/prop/urban/urbanrandomprops.dmi
  icons/obj/structures/prop/urban_vehicles/64x64_hybrisa_vehicles_smalltrucks.dmi
Labels: Sprites, Fix

#16347 Less misleading jump stamina message
  code/datums/components/jump.dm
Labels: Fix

#16346 515.1640 compatibility fixes
  code/datums/components/_component.dm
  code/datums/greyscale/_greyscale_config.dm
  code/modules/admin/topic.dm
  code/modules/admin/view_variables/debug_variables.dm
  code/modules/paperwork/paper_bundle.dm
Labels: Code Improvement

#16342 Adds Rangefinder Binos to Req
  code/modules/reqs/supplypacks.dm
Labels: Feature

#16327 Flash powder removal
  code/modules/reagents/chemistry/recipes/other.dm
Labels: Removal

#16339 Campaign plasma gun cost changes
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/corpsman.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/engineer.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/field_commander.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/marine.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/squad_leader.dm
  code/datums/gamemodes/campaign/perks.dm
Labels: Balance

#16251 Kwik-e-quip now checks if you already vended things from GHMME
  code/__DEFINES/jobs.dm
  code/game/objects/items/cards_ids.dm
  code/game/objects/machinery/vending/quick_vendor.dm
Labels: Stale, Fix

#16349 NT base rescue telegib fix
  code/game/objects/effects/tele_blocker.dm
Labels: Fix

#16351 fixes powerloader being unrepairable
  code/modules/vehicles/powerloader.dm
Labels: Fix

#16348 NT pod change
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  icons/obj/structures/campaign/campaign_big.dmi
Labels: Sprites, Fix

#16344 Adds :clueless: emoji
  icons/misc/emoji.dmi
Labels: Sprites, Feature

#16340 Campaign admin panel QOL - Nonforced autobalance
  code/modules/admin/panels/Campaign_panel.dm
  tgui/packages/tgui/interfaces/CampaignAdminPanel.tsx
Labels: Administration, UI

#16334 Adds campaign TGMC tank to Valhalla
  code/game/objects/machinery/buttons.dm
Labels: Feature

#16154 Adds Retrograde Sentinel Strain
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/sentinel.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  icons/Xeno/castes/sentinel.dmi
Labels: Sprites, Feature

#16350 Recalibers SMG45 into .41 AE and adds packets to marine vendor
  code/__DEFINES/calibers.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/smgs.dm
  icons/obj/items/ammo/packet.dmi
Labels: Sprites, Quality of Life

#16352 Fixes LR-73 ammo box overlay
  code/game/objects/items/storage/boxes.dm
Labels: Fix

#16353 Fixes duplicating sunglasses
  code/modules/clothing/glasses/glasses.dm
Labels: Fix

#16355 Clonevat power fix + autodoc
  code/game/objects/machinery/cloning/cloning.dm
Labels: Fix

#16354 Acid shroud fixes and QoL
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Fix, Test Merge Candidate, Quality of Life

#16366 fix crash instaevo
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
Labels: Fix

#16367 Adds squad colour defines + other colour changes
  code/__DEFINES/colors.dm
  code/_onclick/hud/parallax.dm
  code/datums/actions/species_actions/sectoid_action.dm
  code/datums/jobs/squads.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/machinery/hologram.dm
  code/game/objects/machinery/pipe/construction.dm
  code/game/turfs/walls/resin.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/unary_devices/heat_exchanger.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/he_pipes.dm
  code/modules/atmospherics/machinery/pipes/pipes.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/simple_animal/friendly/corgi.dm
  code/modules/power/pipecleaners.dm
Labels: Code Improvement, Grammar and Formatting

#16373 Destructable vehicles
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/Campaign maps/orion_2/orionoutpost_2.dmm
  _maps/map_files/Campaign maps/som_base/sombase.dmm
  _maps/map_files/Campaign maps/som_raid_base/som_raiding_base.dmm
  _maps/map_files/Campaign maps/tgmc_raid_base/tgmc_raiding_base.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV759/LV759.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/kutjevo/kutjevo.dmm
  _maps/map_files/riptide/riptide.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  code/game/objects/structures/prop.dm
  icons/obj/vehicles/64x64.dmi
Labels: Sprites, Map Edit, Quality of Life

#16383 fixes ERROR on Req Operations Vendor with a basic open panel sprite
  icons/obj/machines/vending.dmi
Labels: Sprites, Fix

#16375 Reinforced table parts give two metal
  code/game/objects/items/frames/table_rack.dm
Labels: Fix

#16376 Clarifies armor stat panel entry
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Quality of Life

#16372 Adds more tactical binoculars mode overlays
  code/game/objects/items/binoculars.dm
  code/game/objects/items/firesupport_binoculars.dm
  icons/obj/items/binoculars.dmi
Labels: Sprites

#16359 Organ defines, get_organ_slot, remove_organ_slot
  code/__DEFINES/DNA.dm
  code/datums/gamemodes/objective.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/scanners/health_analyzer.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/flasher.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/life/handle_organs.dm
  code/modules/mob/living/carbon/human/species_types/zombies.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/drinks/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/medical.dm
  code/modules/surgery/brainrepair.dm
  code/modules/surgery/eye.dm
  tgmc.dme
Labels: Code Improvement

#16387 Tele asset fix
  code/datums/gamemodes/campaign/rewards/teleporter.dm
Labels: Fix

#16389 Death fixes
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
Labels: Balance

#16386 Campaign medical asset change
  code/datums/gamemodes/campaign/rewards/equipment.dm
Labels: Balance

#16384 Emp changes
  code/game/objects/items/blink_drive.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/doors/windowdoor.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/vehicles/armored/__armored.dm
Labels: Balance

#16380 V-31 scatter adjustment
  code/modules/projectiles/guns/rifles.dm
Labels: Balance

#16374 Asset disabler fix
  code/datums/gamemodes/campaign/rewards/disablers.dm
Labels: Fix

#16368 Tank throw fix
  code/modules/vehicles/_hitbox.dm
Labels: Fix

#16371 Fixes jaeger mk1 helmet duplicating in the armor vendor
  code/modules/clothing/modular_armor/mark_one.dm
Labels: Fix

#16377 Adds extra checks to settings old bodies as undefibbable
  code/_onclick/hud/alerts.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#16392 area flag fix
  code/game/area/patricks_rest.dm
Labels: Fix

#16364 CIC messages/ship announcements have the same cooldown as HUD orders (and more character limits)
  code/game/objects/machinery/computer/communications.dm
  code/game/objects/machinery/overwatch.dm
Labels: Balance

#16393 Combat patrol fixes
  code/datums/gamemodes/hvh.dm
  code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
Labels: Fix

#16395 Raid base edits
  _maps/map_files/Campaign maps/som_raid_base/som_raiding_base.dmm
  _maps/map_files/Campaign maps/tgmc_raid_base/tgmc_raiding_base.dmm
  code/datums/gamemodes/campaign/missions/raiding_base.dm
Labels: Balance, Map Edit

#16365 Neuraline shows up on med scan now
  code/modules/reagents/chemistry/reagents/medical.dm
Labels: Quality of Life

#16317 plasma SMG tweaks
  code/modules/projectiles/ammo_types/energy_ammo.dm
  code/modules/projectiles/guns/plasma.dm
Labels: Balance, Stale

#16302 Gives Kelotane Vali 5 fire stack (also use better proc)
  code/datums/components/harvester.dm
Labels: Balance, Stale

#16391 acid code cleanup
  code/__DEFINES/atom.dm
  code/__DEFINES/dcs/signals/signals.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/aliens.dm
  code/game/objects/items.dm
  code/game/objects/machinery/deployable.dm
  code/game/objects/objs.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/handrail.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/projectiles/mounted.dm
  tgmc.dme
Labels: Code Improvement

#16399 Fixes snow minigun powerpack icon
  code/modules/projectiles/magazines/specialist.dm
  icons/obj/items/ammo/powerpack.dmi
Labels: Sprites, Fix

#16379 Heat rocket scatter
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Balance, Stale

#16282 Adds rappel to tadpole (again)
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/__DEFINES/skills.dm
  code/datums/gamemodes/campaign/perks.dm
  code/datums/skills.dm
  code/game/objects/items/pamphlets.dm
  code/game/objects/structures/rappel_system.dm
  code/modules/projectiles/gun_attachables/attachable.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/reqs/supplypacks.dm
  code/modules/shuttle/mini_dropship.dm
  icons/UI_Icons/map_blips.dmi
  icons/obj/structures/prop/mainship.dmi
  tgmc.dme
Labels: Sprites, Map Edit, Feature

#16407 Rounified version of queen
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  icons/Xeno/castes/queen.dmi
Labels: Sprites, Feature

#16408 Adds a queen plushie
  code/game/objects/items/toys/toys.dm
  code/game/objects/machinery/computer/arcade.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/inhands/items/toys_left.dmi
  icons/mob/inhands/items/toys_right.dmi
  icons/obj/items/toy.dmi
  sound/items/wee.ogg
Labels: Sprites, Sound, Feature

#16414 Req points from xenos statistics
  code/datums/gamemodes/_game_mode.dm
  code/datums/round_statistics.dm
  code/modules/requisitions/supply_export.dm
Labels: Feature

#16417 Vehicle interior door allows non-mobs to exit
  code/datums/interior/interior_tank.dm
  code/modules/vehicles/armored/__armored.dm
Labels: Feature

#16406 Patrol point fix (for campaign)
  code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
Labels: Fix

#16400 Timeshift bugfix
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#16390 Droppod location now has warning overlay
  code/game/objects/effects/overlays.dm
  code/game/objects/structures/droppod.dm
  icons/effects/lases.dmi
Labels: Sprites, Balance

#16360 All harvesters load up reagents on afterattack
  code/datums/components/harvester.dm
  code/game/objects/items/weapons/harvester.dm
Labels: Quality of Life
