Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2024-03, with the labels that each got.

#15100 Some recipes which use 1u of Lemoline now add to the final volume
  code/modules/reagents/reactions/medical.dm
Labels: Balance

#15136 Adds a mortar bag to basic mortar kit
  code/game/objects/machinery/mortar.dm
Labels: Balance

#15186 Adds the Critical sructure and ignore weed removal tag on Gargoyle.
  code/modules/xenomorph/resin_gargoyle.dm
Labels: Balance

#15191 Doubles the Damage of Genghis Charge flames but halves it's total burn time. (rounded up)
  code/game/objects/items/explosives/plastique.dm
Labels: Balance

#15213 Increases crusher sunder multiplier
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Labels: Balance

#15217 Reqtorio expansion V 1.6
  code/modules/factory/howtopaper.dm
  code/modules/factory/parts.dm
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance, Feature

#15231 Changes "View Hive" lobby button to "View Hive Leaders"
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/modules/mob/new_player/new_player.dm
Labels: Grammar and Formatting

#15220 Adds HEFA nades to Valhalla.
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal, Feature

#15215 Mecha keybinds
  tgui/packages/tgui/interfaces/PlayerPreferences/KeybindSettings.tsx
Labels: UI, Quality of Life

#15209 Xeno charge fixes
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/abilities_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#15106 Removes High-Tier Xenomorph Research Samples
  code/game/objects/effects/landmarks/excavation_site_spawner.dm
  code/game/objects/machinery/research.dm
Labels: Removal, Fix

#15235 Directional attack adjacency sanity
  code/datums/elements/directional_attack.dm
Labels: Priority: High, Fix

#15225 Fixes near-infinite loop with primordial crusher ability
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Priority: High, Fix

#15224 Sound runtime
  code/modules/projectiles/gun_system.dm
Labels: Fix

#15230 Adds antigas nades to crash vendor
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance

#15237 Disables directional attacks for mobs of the same faction as you
  code/datums/elements/directional_attack.dm
Labels: Quality of Life

#15233 Fixes vehicle shooting speed
  code/modules/vehicles/armored/armored_weapons.dm
Labels: Fix

#15236 Fixes some unintended retired ert things
  code/datums/emergency_calls/retired.dm
  code/datums/jobs/job/retired.dm
  code/modules/projectiles/gun_system.dm
Labels: Fix

#15226 Crusher fix
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Fix

#15247 Fix blessing menu typo
  tgui/packages/tgui/interfaces/BlessingMenu.tsx
Labels: Grammar and Formatting, UI

#15241 Tank balance changes
  code/modules/projectiles/ammo_datums.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/ammo_magazine.dm
Labels: Balance

#15242 Fixes tank reload not updating UI
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/interiors/breech.dm
Labels: Fix

#15243 Tank periscope buff
  code/modules/vehicles/armored/interiors/periscope.dm
Labels: Feature

#15228 Moves orion silo one tile
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
Labels: Fix, Map Edit

#15175 Changes Fire-safety Locker Layer, Changes It's Position On Standard Tad
  _maps/shuttles/minidropship_standard.dmm
  code/game/objects/structures/crates_lockers/walllocker.dm
Labels: Map Edit, Quality of Life

#15055 TG colored plainchat
  tgui/packages/tgui-panel/styles/components/Chat.scss
  tgui/packages/tgui-panel/themes.ts
Labels: Feature, Test Merge Candidate, UI

#15080 Synthetic critical condition changes
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance, Stale

#15232 Adds armored vehicle jobs
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/__DEFINES/skills.dm
  code/datums/gamemodes/extended.dm
  code/datums/gamemodes/nuclear_war.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/datums/skills.dm
  code/game/objects/effects/landmarks/marine_spawns.dm
  code/game/objects/items/pamphlets.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/under/marine_uniform.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/apc.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/armored/interiors/chairs.dm
  code/modules/vehicles/armored/medium_apc.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
  icons/UI_Icons/map_blips.dmi
  icons/UI_Icons/map_blips_large.dmi
  icons/mob/clothing/headwear/marine_helmets.dmi
  icons/mob/clothing/suits/marine_armor.dmi
  icons/mob/clothing/uniforms/marine_uniforms.dmi
  icons/mob/hud.dmi
  icons/mob/landmarks.dmi
  icons/obj/clothing/headwear/marine_helmets.dmi
  icons/obj/clothing/suits/marine_armor.dmi
  icons/obj/clothing/uniforms/marine_uniforms.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
Labels: Sprites, Feature, UI

#15183 Resprites 571, adds 2 new sentry types.
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/sentries.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/sentry.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Feature

#15279 Revert "Resprites 571, adds 2 new sentry types."
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/sentries.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/sentry.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Revert

#15223 Action runtimes
  code/_globalvars/lists/mobs.dm
  code/datums/actions/ability_actions.dm
  code/datums/actions/action.dm
  code/datums/actions/species_actions/sectoid_action.dm
  code/datums/status_effects/sectoid.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Fix

#15246 Refactor defib gloves
  code/__DEFINES/loadout.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/gloves.dm
  code/datums/quick_load_beginners.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/storage/backpack.dm
  icons/obj/clothing/gloves.dmi
Labels: Sprites, Code Improvement, Refactor

#15260 Loadout changes
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/uniform.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/uniform.dm
  code/game/objects/items/storage/pouch.dm
  code/modules/clothing/modular_armor/som.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Balance

#15266 fixes a missing category in gear preferences
  tgui/packages/tgui/interfaces/PlayerPreferences/GearCustomisation.tsx
Labels: Fix, UI

#15250 Shield perk fix
  code/datums/gamemodes/campaign/perks.dm
Labels: Fix

#15249 Alamo can no longer be captured mid-transit
  code/modules/shuttle/marine_dropship.dm
  code/modules/tgui/states/alamo.dm
  tgui/packages/tgui/interfaces/MarineDropship.jsx
Labels: Fix, UI

#15273 Gregor portraits for campaign
  code/datums/fire_support.dm
  code/datums/gamemodes/campaign/rewards/allies.dm
  code/datums/gamemodes/campaign/rewards/drop_pods.dm
  code/datums/gamemodes/campaign/rewards/fire_support.dm
  code/datums/gamemodes/campaign/rewards/teleporter.dm
  code/modules/screen_alert/misc_alert.dm
  icons/UI_Icons/screen_alert_images.dmi
Labels: Sprites

#15271 Fixes mag harness for belt guns
  code/modules/projectiles/gun_attachables.dm
Labels: Fix

#15274 Squad management fix
  code/datums/jobs/job/marines.dm
Labels: Fix

#14984 Add 2 night vision goggle sets
  code/__DEFINES/traits.dm
  code/_onclick/click.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/machinery/cell_charger.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/mark_one.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/power/cell.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/clothing/eyes.dmi
  icons/mob/modular/modular_armor_modules.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/power.dmi
  sound/items/scan_pulse.wav
Labels: Sprites, Sound, Balance, Stale, Refactor, Feature

#15289 Clean up some more xeno code
  code/__DEFINES/mobs.dm
  code/game/data_huds.dm
  code/modules/admin/fun_verbs.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
Labels: Code Improvement

#15277 Focus aura no longer gives you firerate bonuses in aim mode.
  code/modules/projectiles/gun_system.dm
Labels: Balance

#15278 Admin pod fixes
  code/game/objects/structures/supplypod.dm
  code/modules/admin/verbs/centcom_podlauncher.dm
Labels: Fix

#15275 rwalls have 3k hp again, even slightly higher bullet/las armor
  code/game/turfs/walls/r_wall.dm
Labels: Balance

#15276 rds now gives aim speed mult instead of fire delay
  code/modules/projectiles/gun_attachables.dm
Labels: Balance

#15091 Tad can no longer perform instant transmission
  code/modules/shuttle/mini_dropship.dm
Labels: Stale, Fix

#15282 Increases warrior slash damage
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
Labels: Balance

#15270 Trying to disassemble some deployables is a balloon alert instead of to_chat
  code/game/objects/machinery/deployable.dm
  code/game/objects/structures/barricade.dm
  code/modules/projectiles/sentries.dm
  code/modules/vehicles/unmanned/deployable_vehicles.dm
Labels: Fix

#15257 Code improvement for akimbo scatter
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
Labels: Code Improvement

#15240 Baneling Removal
  code/__DEFINES/action.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/__DEFINES/xeno.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/mobs.dm
  code/_onclick/ai.dm
  code/datums/keybinding/xeno.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  tgmc.dme
Labels: Removal

#15293 Restores the illusion of choice regarding special resin walls(Fixes not being able to select any other type)
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#15290 Sound tank fixes
  code/game/sound.dm
Labels: Fix

#15229 Each time you upgrade a grab, you have to resist one more time to escape. (HVH PR)
  code/modules/mob/mob_grab.dm
Labels: Balance

#15227 Punchstun and shovestun no longer care about armor and always stuns for 4 seconds now. (HVH PR)
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Balance

#15288 Cleanup some scout cloak and related code
  code/game/objects/items/loot_box.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/reqs/supplypacks.dm
Labels: Code Improvement

#15298 Fixes typo in bulwark description
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Grammar and Formatting

#15295 Hold order rounding fix
  code/modules/mob/living/carbon/human/species.dm
Labels: Fix

#15299 swaps research rig belt dexalin for isotonic
  code/game/objects/items/storage/belt.dm
Labels: Balance

#15281 Lowers warlock HP
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
Labels: Balance

#15302 Remove old type from map
  _maps/map_files/Campaign maps/som_base/sombase.dmm
Labels: Removal, Map Edit

#15286 Rest is no longer a verb
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_verbs.dm
Labels: Removal

#15313 Adds tank LTA-AP minigun
  _maps/map_files/Campaign maps/orion_2/orionoutpost_2.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  code/modules/projectiles/ammo_datums.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/armored/interiors/ammo_rack.dm
  code/modules/vehicles/armored/interiors/breech.dm
  icons/obj/armored/3x3/tank_gun.dmi
  icons/obj/armored/hardpoint_modules.dmi
  icons/obj/items/ammo.dmi
Labels: Sprites, Map Edit, Feature

#15312 (Mostly) fixes tank minimaps
  code/controllers/subsystem/minimaps.dm
  code/datums/interior/_interior.dm
  code/datums/interior/interior_tank.dm
Labels: Feature

#15311 Stops non tank users from touching tank
  code/modules/vehicles/armored/__armored.dm
Labels: Feature

#15310 Fixes kotahi shuffling
  code/game/objects/items/toys/cards.dm
Labels: Code Improvement, Fix

#15212 Projectile code cleanup
  code/__DEFINES/conflict.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/obj_flags.dm
  code/_globalvars/bitfields.dm
  code/modules/codex/entries/ammunition_codex.dm
  code/modules/codex/entries/magazine_codex.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/projectile.dm
Labels: Code Improvement, Fix

#15303 Adds AMR alternative ammo, TL flak ammo and cleaner nades to valhalla.
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#15320 Proper updating for xeno health/plasma side buttons
  code/__DEFINES/xeno.dm
  code/_onclick/hud/hud.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Quality of Life

#15317 Gives cluster OB 1 more tile of devastation
  code/game/objects/structures/orbital_cannon.dm
Labels: Balance

#15283 adjusted values of larmor and vlarmor
  code/__DEFINES/conflict.dm
Labels: Balance

#15305 More projectile fixes/improvements
  code/controllers/subsystem/autofire.dm
  code/game/objects/items/explosives/grenades/bullet_grenade.dm
  code/game/objects/machinery/mortar.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
  code/modules/xenomorph/xeno_turret.dm
Labels: Code Improvement, Fix

#15307 Explosion throw changes
  code/__DEFINES/move_force.dm
  code/controllers/subsystem/explosions.dm
  code/game/objects/items.dm
  code/modules/vehicles/mecha/_mecha.dm
Labels: Balance

#15306 Mech stagger
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Balance

#15338 Fix bemo throw
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Fix

#15256 Preweeds Magmoor
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Stale, Map Edit

#15255 fix: sulaco cas bay parity
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Stale, Map Edit

#15252 fix: map parity ai droid changes
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Stale, Map Edit

#15251 fix: map parity changes
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Stale, Map Edit

#15334 valhalla area compression the sequel
  _maps/map_files/generic/Admin_Level.dmm
Labels: Map Edit

#15261 Campaign base map tweaks
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Iteron/Iteron.dmm
Labels: Map Edit, Quality of Life

#15327 Give laspistol and serpenta full auto
  code/modules/projectiles/guns/energy.dm
Labels: Balance

#15314 Less RNG in flame_radius, incen OB buff
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/modules/admin/fun_verbs.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#15337 Allow the AI to interact with the nuke again
  code/game/objects/machinery/nuclearbomb.dm
Labels: Fix

#15341 Restores pre-root boiler dig mechanic
  code/datums/actions/action.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Balance

#15349 Fix the ICC MG name and caliber
  code/game/objects/items/storage/holsters.dm
  code/modules/projectiles/magazines/rifles.dm
Labels: Fix

#15348 Add animations for Trench Gun, M412LI, and Minimi
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/obj/items/guns/machineguns64.dmi
  icons/obj/items/guns/shotguns64.dmi
Labels: Sprites

#15328 removes ipc head variants from the hairstyle dmi
  icons/mob/human_face.dmi
Labels: Sprites, Removal

#15326 Water is now recognizable by medical scanners
  code/modules/reagents/reagents/other.dm
Labels: Fix

#15323 Synthetic overheating damage tweak + cool effects
  code/modules/mob/living/carbon/human/species.dm
Labels: Balance, Feature

#15222 add acid well to drones
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
Labels: Balance, Stale

#15322 Removes the shoulder mount.
  code/game/objects/machinery/research.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Removal

#15268 adds antigas grenade pouches to FC and SL vendors
  code/__DEFINES/loadout.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/pouch.dm
Labels: Feature

#15353 edits beginner loadout tutorials + updates some of the loadouts
  code/datums/quick_load_beginners.dm
  code/modules/paperwork/beginner_tutorials.dm
Labels: Fix

#14615 Revamps the Alamo with doublewide seats and enchanced player visibility
  _maps/shuttles/alamo.dmm
  code/game/objects/machinery/computer/dropship_weapons.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/turfs/closed.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  code/modules/shuttle/marine_dropship.dm
  icons/obj/objects.dmi
  icons/turf/dropship.dmi
  icons/turf/shuttle.dmi
Labels: Sprites, Stale, Fix, Map Edit, Feature, Test Merge Candidate

#15377 theseus edits
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit, Quality of Life

#15374 resprites mimir worn sprite
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites

#15373 Portrait fixes
  code/datums/fire_support.dm
Labels: Fix

#15376 style hats now mask hair
  code/modules/clothing/modular_armor/style_line.dm
Labels: Quality of Life

#15344 Consistant SOM medic supplies
  code/datums/gamemodes/campaign/loadout_items/SOM/head.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm
Labels: Balance

#15343 Campaign loadout popup
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Quality of Life

#15357 Queen screech fix
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Fix

#15342 Petrify gib fix
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Fix

#15366 Democratises say tech
  strings/tips/meta.txt
Labels: Feature

#15333 Kill some obj vars
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/scanners.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/machinery/constructable_frame.dm
  code/game/objects/objs.dm
  code/game/objects/structures/window.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/power/batteryrack.dm
  code/modules/power/cell.dm
  code/modules/power/smes_construction.dm
Labels: Code Improvement

#15347 Campaign auto respawn window
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/rewards/reserves.dm
Labels: Quality of Life

#15316 Minimap layers
  code/__DEFINES/layers.dm
  code/datums/components/beacon.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/devices/minimap_tablet.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/computer/nt_access.dm
  code/game/objects/machinery/computer/nuke_disk_generator.dm
  code/game/objects/machinery/nuclearbomb.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/structures/campaign_structures/campaign_structure.dm
  code/game/objects/structures/campaign_structures/capture_objectives.dm
  code/game/objects/structures/campaign_structures/deploy_blockers.dm
  code/game/objects/structures/sensor_tower.dm
  code/game/objects/structures/teleporter.dm
  code/modules/events/intel_computer.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/xenomorph/pherotower.dm
  code/modules/xenomorph/resin_gargoyle.dm
  code/modules/xenomorph/silo.dm
  code/modules/xenomorph/spawner.dm
  code/modules/xenomorph/tunnel.dm
Labels: Quality of Life

#15339 Campaign mission tweaks
  code/datums/gamemodes/campaign/missions/asat_capture.dm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/datums/gamemodes/campaign/missions/mech_wars.dm
Labels: Balance

#15369 fire support bino tweaks
  code/game/objects/items/firesupport_binoculars.dm
Labels: Balance

#15370 Facehuggers actually prioritize the nearest marine
  code/__DEFINES/_math.dm
  code/controllers/subsystem/advanced_pathfinding.dm
  code/controllers/subsystem/weeds.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/items/devices/minimap_tablet.dm
  code/game/objects/machinery/mortar.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#15238 GL-81 now fits attachments
  code/modules/projectiles/guns/grenade_launchers.dm
Labels: Balance, Stale

#15384 Fixes caste passive plasma regen limits not applying under certain circumstances
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Fix

#15383 Add medivac bed description, fix typo, remove an useless verb
  code/datums/gamemodes/campaign/loadout_items/_TGMC/gloves.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Code Improvement, Grammar and Formatting, Quality of Life

#15381 Fixes campaign mortar acid smoke
  code/datums/fire_support.dm
Labels: Fix

#15379 Visible antigas
  code/game/objects/effects/effect_system/smoke.dm
Labels: Quality of Life

#15389 Fixes some factory oopsies nobody has bothered to fix
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
Labels: Fix, Grammar and Formatting

#15385 Flak gun fixes
  code/controllers/subsystem/persistence.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
Labels: Fix

#15386 Arachne Vehicle Bay Expansion
  _maps/map_files/Arachne/TGS_Arachne.dmm
Labels: Removal, Map Edit, Feature

#15340 Projectile fixes
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/_hitbox.dm
Labels: Fix

#15401 Base rescue tweaks
  code/datums/gamemodes/campaign/campaign_assets.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
Labels: Balance

#15400 Campaign game timer tweaks
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/datums/gamemodes/campaign/missions/mech_wars.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
Labels: Balance

#15399 Supply raid objective tweak
  code/datums/gamemodes/campaign/missions/supply_raid.dm
Labels: Balance

#15410 Rename the flak gun in the req interface
  code/modules/reqs/supplypacks.dm
Labels: Quality of Life

#15409 Nukes all references to the M56D
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/loot_box.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/prop.dm
  code/modules/codex/entries/guns_codex.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  icons/Marine/tank_propew.dmi
  icons/Marine/tank_propns.dmi
Labels: Sprites, Code Improvement

#15408 Fixes unlimited Igunana ammo reloads
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Fix

#15394 Add the evac timer to the AI status tab
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Quality of Life

#15391 Fix huggers for REAL
  code/__DEFINES/_math.dm
  code/__HELPERS/math.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#15402 Campaign loot table fix
  code/_globalvars/lists/game_modes.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
Labels: Fix

#15419 Mech explosion resistance reduction
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Labels: Balance

#15424 Minor volkite tweaks
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#15416 Melee special attack adjustments
  code/__DEFINES/dcs/signals.dm
  code/datums/actions/weapon_actions.dm
  code/datums/keybinding/weapons.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/twohanded.dm
Labels: Balance

#15350 Cleans up species.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species.dm
  code/modules/mob/living/carbon/human/zombie.dm
Labels: Code Improvement

#15367 Roomba tries to restock elligible items
  code/__DEFINES/vending.dm
  code/game/objects/machinery/bots/roomba.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending.dm
  tgmc.dme
Labels: Quality of Life

#15420 Campaign timing adjustments
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/missions/asat_capture.dm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
Labels: Balance, Quality of Life

#15398 Campaign tower fix
  _maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/structures/campaign_structures/capture_objectives.dm
Labels: Fix, Map Edit

#15397 Removes multiple intel computers in same areas on Gelida IV
  _maps/map_files/gelida_iv/gelida_iv.dmm
Labels: Removal, Map Edit

#15412 Sword lunge fix
  code/game/objects/items/weapons/blades.dm
Labels: Fix

#15430 Add the ASRS supply tablet to req
  code/datums/jobs/job/shipside.dm
  code/modules/reqs/supplypacks.dm
Labels: Quality of Life

#15425 Fixed some typo and Clarify some ammo with the same caliber
  code/__DEFINES/loadout.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/specialist.dm
Labels: Grammar and Formatting

#15404 Sentry fix and code improvements
  code/modules/projectiles/sentries.dm
Labels: Fix, Test Merge Candidate

#15421 Mech actuator overload hotkey
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/mecha.dm
  code/modules/vehicles/mecha/combat/gygax.dm
Labels: Quality of Life

#15435 Gun codex shows relevant weapon skill
  code/modules/codex/entries/guns_codex.dm
Labels: Quality of Life

#15422 Mech UI size fix
  tgui/packages/tgui/interfaces/Mecha/index.tsx
Labels: Fix, UI

#15414 Job point fix
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/hvh.dm
  code/datums/jobs/job/job.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: Balance, Fix

#15392 Add a button for the AI to open the req console directly.
  code/__DEFINES/hud.dm
  code/_onclick/hud/ai.dm
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Quality of Life

#15382 Add the FCDR vendor
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Map Edit, Feature

#15368 Improves the hypersleep console
  code/_globalvars/lists/objects.dm
  code/game/objects/items.dm
  code/game/objects/machinery/cryopod.dm
Labels: Stale, Quality of Life

#15331 adds storage to some base suits
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/EORG/cs_office.dmm
  _maps/modularmaps/lv624/auxbotany.dmm
  _maps/shuttles/minidropship_food.dmm
  code/__DEFINES/loadout.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/effects/landmarks/itemspawner.dm
  code/game/objects/effects/spawners/random/clothing.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/game/objects/structures/coathanger.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/wiz_robe.dm
  tgui/packages/tgui/interfaces/MarineSelector.jsx
Labels: Balance, Map Edit, UI

#15440 Tank balance changes #1
  code/modules/projectiles/ammo_datums.dm
  code/modules/vehicles/armored/_multitile.dm
Labels: Balance

#15438 Fixes caste swapping/regressing while zoomed in causing your vision to get stuck forward
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#15418 Minor lava refactor
  code/game/atoms/_atom.dm
  code/game/objects/obj_defense.dm
  code/game/turfs/liquid_turfs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Balance, Refactor
