Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2024-06, with the labels that each got.

#15929 Fixes a disposal pipe on Sulaco
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Fix, Map Edit

#15948 Adds a layer of forcefields around xeno valhalla
  _maps/map_files/generic/Admin_Level.dmm
Labels: Fix, Map Edit

#15952 splits up scanners.dm + probably the last health analyzer patch
  code/game/objects/items/scanners/gas_analyzer.dm
  code/game/objects/items/scanners/health_analyzer.dm
  code/game/objects/items/scanners/mass_spectrometer.dm
  code/game/objects/items/scanners/reagent_scanner.dm
  code/game/objects/items/scanners/terahertz_scanner.dm
  tgmc.dme
Labels: Fix

#15954 Deletes Marine lockers.dmi
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  icons/Marine/Marine_Lockers.dmi
  icons/obj/structures/closet.dmi
Labels: Sprites

#15955 Repaths Marine props icons.
  code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/machinery/cic_maptable.dm
  code/game/objects/structures/campaign_props.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/prop.dm
  code/game/objects/structures/som_cas_parts.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  icons/obj/structures/prop/apc.dmi
  icons/obj/structures/prop/broken_apc.dmi
  icons/obj/structures/prop/dropship.dmi
  icons/obj/structures/prop/mainship.dmi
  icons/obj/structures/prop/mainship_64.dmi
  icons/obj/structures/prop/mainship_96.dmi
  icons/obj/structures/prop/mech.dmi
  icons/obj/structures/prop/somship.dmi
  icons/obj/structures/prop/tank_horizontal.dmi
  icons/obj/structures/prop/tank_vertical.dmi
Labels: Sprites

#15956 Reorganizes barricades.dmi
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/machinery/line_nexter.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/campaign_structures/misc_structures.dm
  code/game/objects/structures/razorwire.dm
  icons/Marine/barricades.dmi
  icons/Marine/structures.dmi
  icons/obj/structures/barbedwire.dmi
  icons/obj/structures/barricades/barbedwire.dmi
  icons/obj/structures/barricades/concrete.dmi
  icons/obj/structures/barricades/folding.dmi
  icons/obj/structures/barricades/metal.dmi
  icons/obj/structures/barricades/misc.dmi
  icons/obj/structures/barricades/plasteel.dmi
  icons/obj/structures/barricades/sandbags.dmi
  icons/obj/structures/barricades/upgrades.dmi
Labels: Sprites

#15959 Repaths `Pouch.dmi`
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/reagent_pouch.dm
  icons/Marine/marine-pouches.dmi
  icons/obj/clothing/pouches.dmi
Labels: Sprites

#15957 Reorganizes Weapons.dmi
  code/datums/components/harvester.dm
  code/datums/elements/riding.dm
  code/game/objects/items/implants/implant_items.dm
  code/game/objects/items/tools/hydro_tools.dm
  code/game/objects/items/tools/mining_tools.dm
  code/game/objects/items/toys/toy_weapons.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/weapons/batons.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/energy.dm
  code/game/objects/items/weapons/harvester.dm
  code/game/objects/items/weapons/holo_weapons.dm
  code/game/objects/items/weapons/misc.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/swords.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/items/weapons/weapon.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/projectiles/guns/pistols.dm
  icons/Marine/spear.dmi
  icons/obj/items/harvest.dmi
  icons/obj/items/tools.dmi
  icons/obj/items/toy.dmi
  icons/obj/items/vali.dmi
  icons/obj/items/weapons.dmi
  icons/obj/items/weapons/64x64.dmi
  icons/obj/items/weapons/batons.dmi
  icons/obj/items/weapons/energy.dmi
  icons/obj/items/weapons/knives.dmi
  icons/obj/items/weapons/misc.dmi
  icons/obj/items/weapons/shield.dmi
  icons/obj/items/weapons/swords.dmi
  icons/obj/items/weapons/throwing.dmi
  icons/obj/items/weapons/twohanded.dmi
  icons/obj/items/weapons/vali.dmi
  icons/obj/items/weapons64.dmi
  icons/obj/mining.dmi
  tgmc.dme
Labels: Sprites

#15964 Hypos no longer open pill bottles
  code/datums/storage/subtypes/pill_bottle.dm
Labels: Quality of Life

#15970 Deletes 128.dmi
  icons/Marine/128.dmi
Labels: Sprites

#15972 Repaths `Fusion_eng.dmi`
  code/game/objects/machinery/fuelcell_recycler.dm
  code/modules/power/fusion_engine.dm
  icons/obj/machines/fusion_engine.dmi
Labels: Sprites

#15969 Repaths `Teleporter.dmi`
  code/game/objects/structures/teleporter.dm
  code/game/objects/structures/teleporter_array.dm
  icons/obj/structures/teleporter.dmi
Labels: Sprites

#15978 Readds forcefields to Riptide
  _maps/map_files/riptide/riptide.dmm
Labels: Fix, Map Edit

#15979 Pyrogen can be given plasma
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
Labels: Fix

#15974 Marine-items.dmi reorg.
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/machinery/minelayer.dm
  icons/Marine/marine-items.dmi
  icons/effects/blips.dmi
  icons/effects/orders.dmi
  icons/mob/screen/arrows.dmi
  icons/obj/items/grenade.dmi
  icons/obj/items/mines.dmi
  icons/obj/stack_objects.dmi
Labels: Sprites

#15973 Deletes `code/modules/mob/living/silicon/decoy/decoy.dm` and `icons/Marine/ai.dmi`
  code/_onclick/adjacent.dm
  code/modules/mob/living/silicon/decoy/decoy.dm
  icons/Marine/ai.dmi
  tgmc.dme
Labels: Sprites

#15971 Deletes junglewall.dmi
  icons/Marine/junglewall.dmi
Labels: Sprites

#15967 fixes health analyzer revivable threshold (for the final time)
  code/game/objects/items/scanners/health_analyzer.dm
Labels: Fix

#15963 Replaces CQC name with UNARMED
  code/__DEFINES/skills.dm
  code/__DEFINES/traits.dm
  code/datums/gamemodes/campaign/perks.dm
  code/datums/skills.dm
  code/game/objects/items/pamphlets.dm
  code/game/objects/objs.dm
  code/game/objects/structures/benchpress.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/window.dm
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/mob_grab.dm
Labels: Code Improvement

#15953 adds faction corpses
  code/game/objects/effects/landmarks/corpsespawner.dm
Labels: Feature

#15983 smg-25 holster nerf
  code/game/objects/items/storage/holsters.dm
Labels: Fix

#15976 Prevent deployable shields on the tad and alamo
  code/datums/components/deployable_item.dm
  code/game/objects/items/weapons/shields.dm
Labels: Fix

#15981 Alamo doors unlock on hijacking the console
  code/modules/shuttle/marine_dropship.dm
Labels: Fix

#15867 Railgun nerf
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance

#15985 Fix stacks in backpacks breaking
  code/datums/storage/storage.dm
  code/datums/storage/subtypes/bag.dm
  code/datums/storage/subtypes/box.dm
  code/datums/storage/subtypes/holster.dm
  code/datums/storage/subtypes/internal.dm
  code/datums/storage/subtypes/pill_bottle.dm
  code/datums/storage/subtypes/wallet.dm
Labels: Fix

#15986 Repaths and reorgs `Remotefob.dmi`
  code/modules/remote_fob/actions_misc.dm
  code/modules/remote_fob/computer.dm
  code/modules/remote_fob/drone.dm
  icons/Marine/remotefob.dmi
  icons/mob/actions.dmi
  icons/obj/machines/fob.dmi
  tgmc.dme
Labels: Sprites

#15988 Reorgs `Marine-navigation.dmi`
  code/game/objects/items/binoculars.dm
  code/game/objects/items/devices/minimap_tablet.dm
  code/game/objects/items/devices/squad_transfer_tablet.dm
  code/game/objects/items/devices/tablets.dm
  code/game/objects/items/firesupport_binoculars.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/items/pinpointer.dm
  code/game/objects/items/whistle.dm
  code/game/objects/machinery/squad_supply/supply_beacon.dm
  code/game/objects/structures/campaign_structures/orbital_beacons.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/reqs/supply.dm
  code/modules/shuttle/shuttle.dm
  icons/Marine/marine-navigation.dmi
  icons/obj/items/beacon.dmi
  icons/obj/items/binoculars.dmi
  icons/obj/items/items.dmi
  icons/obj/items/pinpointer.dmi
Labels: Sprites

#15996 Hugger throw fix
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#15982 Fixes an attachment component bug
  code/datums/components/attachment_handler.dm
Labels: Fix

#15995 Remove Big Red's cave miners near LZ2
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/modularmaps/big_red/bigredsweastcornervar1.dmm
  _maps/modularmaps/big_red/bigredsweastcornervar2.dmm
  _maps/modularmaps/big_red/bigredsweastcornervar3.dmm
  _maps/modularmaps/big_red/bigredsweastcornervar4.dmm
  _maps/modularmaps/big_red/bigredsweastcornervar5.dmm
Labels: Removal, Balance, Map Edit

#15993 Reorgs `marine-weapons.dmi`
  code/game/objects/items/motion_detector.dm
  code/modules/projectiles/gun_attachables/attachable.dm
  code/modules/projectiles/gun_attachables/flamer.dm
  code/modules/projectiles/gun_attachables/foldable.dm
  code/modules/projectiles/gun_attachables/muzzle.dm
  code/modules/projectiles/gun_attachables/rail.dm
  code/modules/projectiles/gun_attachables/scope.dm
  code/modules/projectiles/gun_attachables/stock.dm
  code/modules/projectiles/gun_attachables/underbarrel.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  icons/Marine/attachments_64.dmi
  icons/Marine/marine-weapons.dmi
  icons/obj/items/guns/attachments/flamer.dmi
  icons/obj/items/guns/attachments/gun.dmi
  icons/obj/items/guns/attachments/muzzle.dmi
  icons/obj/items/guns/attachments/rail.dmi
  icons/obj/items/guns/attachments/scope.dmi
  icons/obj/items/guns/attachments/scope_64.dmi
  icons/obj/items/guns/attachments/stock.dmi
  icons/obj/items/guns/attachments/stock_64.dmi
  icons/obj/items/guns/attachments/underbarrel.dmi
Labels: Sprites

#15990 Repaths `Cas.dmi`
  code/game/objects/structures/cas_plane_parts.dm
  code/game/objects/structures/dropship_equipment.dm
  code/modules/condor/cas_chair.dm
  code/modules/condor/cas_shuttle.dm
  icons/Marine/cas_plane_engines.dmi
  icons/Marine/casship.dmi
  icons/obj/structures/cas_cockpit.dmi
  icons/turf/cas.dmi
Labels: Sprites

#15913 Kill gas mask sound pref
  code/__DEFINES/preferences.dm
  code/_globalvars/bitfields.dm
  code/modules/client/preferences_toggles.dm
  code/modules/clothing/masks/gasmask.dm
Labels: Removal, Stale

#15997 Surgery table fix
  code/game/objects/machinery/OpTable.dm
Labels: Fix

#16000 Deconstructing upgraded metal cade refunds full cost
  code/game/objects/structures/barricade.dm
Labels: Fix

#16007 Trying to undeploy mortar refunds any chambered items
  code/game/objects/machinery/mortar.dm
Labels: Fix

#15886 Makes OBs cost the same (solid fuel-wise)
  code/datums/marine_main_ship.dm
  code/game/objects/structures/orbital_cannon.dm
Labels: Balance, Test Merge Candidate

#15984 Fix cursed vehicle to vehicle movement
  code/modules/vehicles/_hitbox.dm
Labels: Fix

#15989 Knockback improvement
  code/game/atoms/atom_movable.dm
  code/game/objects/items/jetpack.dm
  code/game/objects/items/weapons/swords.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Fix

#16025 Pyrogen Fire Charge description correction
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
Labels: Grammar and Formatting

#16013 Nerfs bookcases
  code/game/objects/structures/bookcase.dm
Labels: Balance

#16024 Adds shading to Pyrogens dead sprite
  icons/Xeno/castes/pyrogen.dmi
Labels: Sprites

#16022 Tank AOE damage stuff
  code/modules/vehicles/_hitbox.dm
  code/modules/vehicles/armored/_multitile.dm
Labels: Balance

#16029 Increases surt fire resistance to 45
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Balance

#15999 Show larva position on button
  code/__DEFINES/span.dm
  code/datums/components/larva_queue.dm
Labels: Quality of Life

#16023 Deletes duplicate mech files.
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/big_red/bigredofficevar1.dmm
  _maps/modularmaps/big_red/bigredsecornervar6.dmm
  _maps/modularmaps/lv624/newcavevar2.dmm
  code/game/mecha/mech_bay.dm
  code/game/mecha/mecha_parts.dm
  code/game/mecha/mecha_wreckage.dm
  code/modules/vehicles/mecha/mech_bay.dm
  code/modules/vehicles/mecha/mecha_parts.dm
  code/modules/vehicles/mecha/mecha_wreckage.dm
  tgmc.dme
Labels: Map Edit

#16014 Pyrogen Buffs and damage type rework
  code/__DEFINES/mobs.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
Labels: Balance

#16036 Slight nerfs to the TX11
  code/modules/projectiles/ammo_types/rifle_ammo.dm
Labels: Balance

#16041 Kills `Marine` icons folder.
  code/game/objects/machinery/mortar.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  code/modules/projectiles/gun_attachables/rail.dm
  code/modules/projectiles/gun_attachables/stock.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/projectiles/sentries.dm
  icons/Marine/clf_heavyrifle.dmi
  icons/Marine/howitzer.dmi
  icons/Marine/marine-ac.dmi
  icons/Marine/marine-atgun.dmi
  icons/Marine/marine-fkgun.dmi
  icons/Marine/marine-hmg.dmi
  icons/Marine/marine-mmg.dmi
  icons/Marine/mortar.dmi
  icons/Marine/sentry.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/guns/attachments/stock.dmi
  icons/obj/machines/deployable/agls.dmi
  icons/obj/machines/deployable/at36.dmi
  icons/obj/machines/deployable/atr22.dmi
  icons/obj/machines/deployable/clf_heavyrifle.dmi
  icons/obj/machines/deployable/fk88.dmi
  icons/obj/machines/deployable/heavy_laser.dmi
  icons/obj/machines/deployable/heavy_smartgun.dmi
  icons/obj/machines/deployable/howitzer.dmi
  icons/obj/machines/deployable/mg08.dmi
  icons/obj/machines/deployable/minigun.dmi
  icons/obj/machines/deployable/mortar.dmi
  icons/obj/machines/deployable/mounted_machinegun.dmi
  icons/obj/machines/deployable/sentry/build_a_sentry.dmi
  icons/obj/machines/deployable/sentry/cope.dmi
  icons/obj/machines/deployable/sentry/flamer.dmi
  icons/obj/machines/deployable/sentry/laser.dmi
  icons/obj/machines/deployable/sentry/mini.dmi
  icons/obj/machines/deployable/sentry/sentry.dmi
  icons/obj/machines/deployable/sentry/shotgun.dmi
  icons/obj/machines/deployable/sentry/sniper.dmi
  icons/obj/structures/crates.dmi
  sound/weapons/guns/fire/agls.ogg
Labels: Sprites, Sound, Fix

#16018 Fix hugger bounce for real
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Fix

#16021 Hit scan fix
  code/modules/projectiles/projectile.dm
Labels: Fix

#16040 Fixes behemoth's earth pillar and AoE attacks not damaging vehicles outside of the middle
  code/__DEFINES/is_helpers.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Fix

#16033 fix cell + delete cell.dm
  code/__DEFINES/dcs/signals.dm
  code/game/objects/items.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/machinery/cell_charger.dm
  code/game/objects/machinery/recharger.dm
  code/modules/power/cell.dm
  code/modules/power/power.dm
  code/modules/projectiles/gun_system.dm
  tgmc.dme
Labels: Code Improvement, Fix

#16045 Vehicle loading fixes
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/apc.dm
Labels: Fix

#16031 Vehicle ammohud fix
  code/modules/vehicles/armored/__armored.dm
Labels: Fix

#16043 Makes Evade cancel timer 0.3 seconds instead of 1 second
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Balance

#16044 Reduce AMR's on-hit slowdown
  code/__DEFINES/conflict.dm
Labels: Balance

#16026 Removes an egregious object fling trap in Slumbridge
  _maps/map_files/slumbridge/slumbridge.dmm
Labels: Removal, Fix, Map Edit

#16027 Riptide: Makes the destroyable jungle walls count as being on outdoor tiles (you can now talk in ob'd zones)
  _maps/map_files/riptide/riptide.dmm
Labels: Map Edit, Quality of Life

#15936 Vali Spear: The Return
  code/game/objects/items/weapons/harvester.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/vali_left.dmi
  icons/mob/inhands/weapons/vali_right.dmi
  icons/obj/items/weapons/vali.dmi
Labels: Sprites, Stale, Feature, Test Merge Candidate

#16058 Xenos can now see research digsites.
  code/controllers/subsystem/minimaps.dm
Labels: Balance

#16049 Mostly buffs xenos across the board, nerfs speed
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
Labels: Balance, Test Merge Candidate, Requires Testing

#16066 Fixes t27 mag sprite.
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/mounted.dm
  icons/obj/items/ammo.dmi
Labels: Sprites, Fix

#16054 Make King Roar's armored vehicle damage depend on how much is hit
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Balance

#16052 Increase crusher charge damage against tanks
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Balance

#16070 Fix pyrogen's fireball AoE checking the wrong armor type
  code/modules/projectiles/ammo_types/xenos/pyrogen_xenoammo.dm
Labels: Fix

#15932 Spiderlings can now attack uncouncious marines
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
Labels: Feature

#15894 Submerging refactor
  code/__DEFINES/atom_movable.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/traits.dm
  code/datums/components/submerge_mod.dm
  code/datums/elements/accelerate_on_cross.dm
  code/datums/elements/submerge.dm
  code/game/atoms/_atom.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/items.dm
  code/game/objects/structures/flora.dm
  code/game/turfs/liquid_turfs.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/living_movement.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
  code/modules/vehicles/__vehicle.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/mecha_movement.dm
  icons/turf/alpha_128.dmi
  tgmc.dme
Labels: Sprites, Refactor, Fix, Feature

#16071 Fixes melting fire on the ground dealing the wrong damage type
  code/modules/projectiles/guns/_shared_ammo_objects.dm
Labels: Fix

#16061 Xeno jump cd buff
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Balance

#16060 Fix bino exploit
  code/game/objects/items/binoculars.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Fix

#16056 projectile fixes and cleanup
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammo_types/ags_ammo.dm
  code/modules/projectiles/ammo_types/energy_ammo.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/mech_ammo.dm
  code/modules/projectiles/ammo_types/microrail_ammo.dm
  code/modules/projectiles/ammo_types/miscellaneous_ammo.dm
  code/modules/projectiles/ammo_types/mortar_ammo.dm
  code/modules/projectiles/ammo_types/pistol_ammo.dm
  code/modules/projectiles/ammo_types/revolver_ammo.dm
  code/modules/projectiles/ammo_types/rifle_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/projectiles/ammo_types/shotgun_ammo.dm
  code/modules/projectiles/ammo_types/smartgun_ammo.dm
  code/modules/projectiles/ammo_types/smg_ammo.dm
  code/modules/projectiles/ammo_types/sniper_ammo.dm
  code/modules/projectiles/ammo_types/turret_ammo.dm
  code/modules/projectiles/ammo_types/tx54_ammo.dm
  code/modules/projectiles/ammo_types/volkite_ammo.dm
  code/modules/projectiles/ammo_types/xenos/energy_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/gas_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/huggers_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/pyrogen_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
  code/modules/projectiles/ammo_types/xenos/widow_xenoammo.dm
Labels: Fix

#16079 Nosubmerge trait
  code/__DEFINES/traits.dm
  code/datums/components/jump.dm
  code/datums/components/submerge_mod.dm
  code/datums/elements/submerge.dm
  code/game/atoms/atom_movable.dm
  code/game/turfs/liquid_turfs.dm
  code/modules/vehicles/_hitbox.dm
Labels: Fix

#16072 Medical items now apply to yourself if you use them in-hand
  code/game/objects/items/stacks/medical.dm
  code/modules/reagents/reagent_containers.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Quality of Life

#15926 Defibrillator refactor, NPCs/disconnected players rework
  code/__DEFINES/defibrillator.dm
  code/_onclick/hud/alerts.dm
  code/game/data_huds.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/scanners/health_analyzer.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/clothing/gloves/defibrillator_gloves.dm
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/logout.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living_helpers.dm
  code/modules/mob/mob_helpers.dm
  icons/mob/hud/human.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/items/defibrillator.dmi
  sound/items/defib_release.ogg
  tgmc.dme
Labels: Sprites, Sound, Refactor, Feature, Grammar and Formatting, Quality of Life

#15845 Ineligible(nuclear) detonation sites, blacklists nuke from being activated at LZs, enclosed areas & areas with the area_flag "CANNOT_NUKE"
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/__DEFINES/area.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/objects.dm
  code/game/area/area.dm
  code/game/area/bigred.dm
  code/game/area/daedalusprison.dm
  code/game/area/deltastation.dm
  code/game/area/gelida_iv.dm
  code/game/area/icecolony.dm
  code/game/area/icy_caves.dm
  code/game/area/lawankaoutpost.dm
  code/game/area/lv624.dm
  code/game/area/magmoor_digsite.dm
  code/game/area/orion_outpost.dm
  code/game/area/oscaroutpost.dm
  code/game/area/research_outpost.dm
  code/game/area/riptide.dm
  code/game/area/slumbridge.dm
  code/game/area/whiskeyoutpost.dm
  code/game/objects/machinery/nuclearbomb.dm
  code/modules/mapping/mapping_helpers.dm
  tgui/packages/tgui/interfaces/NuclearBomb.tsx
Labels: Code Improvement, Do Not Merge, Balance, Map Edit, UI

#16074 Pass flag changes
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/rocks.dm
Labels: Balance

#15951 WALANCE - WIDOW BUFF - Spider can now web (maze)- Complete
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/castedatum_spiderling.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
Labels: Feature, Test Merge Candidate, Requires Testing

#16095 Fixes Boiler Direct Hits
  code/modules/projectiles/ammo_types/xenos/gas_xenoammo.dm
Labels: Fix

#16094 Allows Marines to shoot through mech using IFF
  code/modules/vehicles/mecha/combat/combat.dm
Labels: Balance

#16091 Warlock Crush Hits more of the Tank now
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Balance

#16101 Changes some bad/inaccurate var names in xeno abilities
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Code Improvement

#16089 Adjusts King's Laser Against APC/Tank
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Balance

#16084 Reorganizes `Storage.dmi`
  code/game/objects/items/loot_box.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/items/portable_vendor.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/items/storage/marine_boxes.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/storage/storage.dm
  code/game/objects/items/storage/wallets.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/detectivework/evidence.dm
  code/modules/mining/money_bag.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/recycling/sortingmachinery.dm
  icons/obj/clothing/belts.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/storage/backholster.dmi
  icons/obj/items/storage/backpack.dmi
  icons/obj/items/storage/bag.dmi
  icons/obj/items/storage/box.dmi
  icons/obj/items/storage/briefcase.dmi
  icons/obj/items/storage/firstaid.dmi
  icons/obj/items/storage/holster.dmi
  icons/obj/items/storage/marine_box.dmi
  icons/obj/items/storage/misc.dmi
  icons/obj/items/storage/storage.dmi
  icons/obj/items/storage/storage_48.dmi
  icons/obj/items/storage/storage_boxes.dmi
  icons/obj/items/storage/vialbox.dmi
  icons/obj/items/storage/wallet.dmi
  icons/obj/janitor.dmi
  icons/obj/mining.dmi
  icons/obj/structures/crates.dmi
  icons/obj/structures/structures.dmi
Labels: Sprites, Code Improvement

#16088 Xeno Acid Smoke Deals Damage to APC/Tank Based on HItbox
  code/modules/vehicles/_hitbox.dm
Labels: Balance

#16068 Light interior fix
  code/game/turfs/turf.dm
  code/modules/mapping/map_template.dm
Labels: Fix

#16086 Valhalla Vehicle Area Update
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Map Edit, Feature, Quality of Life

#16102 status effect fix
  code/datums/status_effects/debuffs.dm
Labels: Fix

#16099 Submerge fix
  code/datums/elements/submerge.dm
Labels: Fix

#16103 Transparency fixes
  code/game/objects/machinery/deployable.dm
  code/game/objects/structures/campaign_structures/campaign_structure.dm
  code/game/objects/structures/campaign_structures/deploy_blockers.dm
  code/modules/vehicles/__vehicle.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/sealed.dm
Labels: Quality of Life

#16093 Forced campaign autobalance option
  code/datums/gamemodes/campaign.dm
Labels: Administration

#16092 Binoc fix 2
  code/game/objects/items/binoculars.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
Labels: Fix, Test Merge Candidate

#16020 Fixes the weather pref
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/modules/client/preferences_savefile.dm
Labels: Stale, Fix

#16090 Buffs the tank Chaingun
  code/modules/projectiles/ammo_types/heavy_ammo.dm
Labels: Balance, Test Merge Candidate, Requires Testing

#16112 Tank fixes for mines and sentry
  code/__HELPERS/ai.dm
  code/game/objects/items/explosives/mine.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/sentries.dm
Labels: Fix

#16110 Couple campaign fixes
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Fix

#16116 Accidental mars sand changes
  code/game/turfs/floor_ground.dm
Labels: Fix

#16115 Adds vehicle modules to valhalla
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#16117 remove large metal stacks in Kutjevo
  _maps/map_files/kutjevo/kutjevo.dmm
Labels: Removal, Map Edit

#16077 Allows toggling of xeno ranks + xeno rank fixes
  code/game/data_huds.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Fix, Feature, UI

#16124 Fixes mashing confirm on the dropship selector bugging the Tad out
  code/game/objects/machinery/computer/dropship_picker.dm
Labels: Fix, In Game Exploit

#16055 moves signals.dm + signals_keybindings.dm
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  tgmc.dme
Labels: Code Improvement, Stale

#16128 fix draw order not saving
  code/modules/client/preferences_savefile.dm
Labels: Fix

#16098 Brings Some Soul Back For Modules
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites

#16123 Forced devolve works again
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#16105 Adds spray secondary flamer for tank
  code/datums/storage/subtypes/tank.dm
  code/modules/projectiles/ammo_types/miscellaneous_ammo.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/armored_weapons.dm
  icons/obj/armored/3x3/tank_gun.dmi
  icons/obj/armored/3x3/tank_interior.dmi
  icons/obj/armored/hardpoint_modules.dmi
  icons/obj/items/ammo.dmi
  icons/obj/items/projectiles.dmi
Labels: Sprites, Fix, Feature

#16121 Allow attackself unzoom
  code/game/objects/items/binoculars.dm
Labels: Fix

#16131 facepaint no longer opens pill bottles
  code/_onclick/item_attack.dm
  code/game/objects/items.dm
  code/game/objects/items/storage/firstaid.dm
Labels: Fix

#16064 Name correctly shows in xeno ruler arisen announcement
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#16120 Nosubmerge crash fix
  code/game/atoms/atom_movable.dm
Labels: Code Improvement

#16132 Fix tank not rendering in some cases
  code/modules/vehicles/armored/_multitile.dm
Labels: Fix

#16129 fixes VSD (again)
  code/datums/gamemodes/campaign/rewards/allies.dm
  code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
  code/datums/jobs/job/vsd.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Fix

#16125 Removes the ability to attack with weapons while prone
  code/_onclick/item_attack.dm
Labels: Removal, Fix

#16133 Adds instructions for how to use hyposprays
  code/modules/reagents/reagent_containers/autoinjectors.dm
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Feature

#16145 Fixes tank aiming at darkness trying to shoot across zlevels
  code/modules/projectiles/gun_helpers.dm
  code/modules/vehicles/armored/__armored.dm
Labels: Fix

#16146 Probably fixes secondary tank weapon overlays duplicating
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/armored_weapons.dm
Labels: Fix

#16144 Reset tank ui on new purchase
  code/modules/reqs/supply.dm
Labels: Fix

#16083 Adds duffelbags + sprites
  code/datums/storage/storage.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/machinery/vending/marine_vending.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/equipment/backpacks_left.dmi
  icons/mob/inhands/equipment/backpacks_right.dmi
  icons/obj/items/storage/duffelbag.dmi
Labels: Sprites, Feature

#16160 suddendly
  code/game/objects/machinery/squad_supply/supply_console.dm
Labels: Grammar and Formatting

#16158 Corrects incorrect tip about larvas and stasis
  strings/tips/marine.txt
Labels: Fix

#16157 Tracks gorger heals
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
Labels: Feature

#16156 Syringes can change their injection amount
  code/modules/reagents/reagent_containers/syringes.dm
Labels: Quality of Life

#16150 Runtime fix on storing mobs in tanks
  code/modules/vehicles/armored/__armored.dm
Labels: Fix

#16161 Adds SMG-45 boxes
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
Labels: Feature

#16075 Ravage now hits more of the APC and Tank
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Balance

#16017 Hover bike
  code/datums/components/riding/riding_vehicle.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/volkite_ammo.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/vehicles/hover_bike.dm
  code/modules/vehicles/ridden.dm
  code/modules/vehicles/vehicle_attachments/vehicle_modules.dm
  code/modules/vehicles/vehicle_attachments/weapon_attachments.dm
  icons/obj/vehicles/hover_bike.dmi
  icons/obj/vehicles/vehicle_weapons.dmi
  tgmc.dme
Labels: Sprites, Feature

#16151 Lighting update
  code/datums/mutable_appearance.dm
  code/modules/lighting/lighting_static/static_lighting_corner.dm
  code/modules/lighting/lighting_static/static_lighting_object.dm
  code/modules/lighting/lighting_static/static_lighting_setup.dm
  code/modules/lighting/lighting_static/static_lighting_source.dm
  code/modules/lighting/lighting_static/static_lighting_turf.dm
  code/modules/mapping/space_management/space_level.dm
Labels: Code Improvement

#16175 Xeno name fix
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Fix

#16184 Daedalus Changes (#3)
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  code/game/area/daedalusprison.dm
Labels: Balance, Map Edit

#16176 Fixes being able to get 2 shots out of 1 shell in Tank
  code/modules/vehicles/armored/armored_weapons.dm
Labels: Fix

#16168 Fireball's AoE now applies fire stacks
  code/modules/projectiles/ammo_types/xenos/pyrogen_xenoammo.dm
Labels: Balance

#16194 Moves sound preferences from `Preferences` tab to `Game Preferences`
  code/modules/client/preferences_toggles.dm
  code/modules/client/preferences_ui.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: UI, Quality of Life

#16140 Reorgs `Ammo.dmi`
  code/datums/greyscale/greyscale_configs.dm
  code/game/objects/items/rcd.dm
  code/game/objects/machinery/mortar.dm
  code/modules/projectiles/ammo_types/shotgun_ammo.dm
  code/modules/projectiles/ammo_types/sniper_ammo.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/magazines/energy.dm
  code/modules/projectiles/magazines/flamer.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/mounted.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/sentries.dm
  code/modules/projectiles/magazines/shotguns.dm
  code/modules/projectiles/magazines/smgs.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/projectiles/magazines/unmanned_vehicle.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  icons/obj/items/ammo.dmi
  icons/obj/items/ammo/artillery.dmi
  icons/obj/items/ammo/box.dmi
  icons/obj/items/ammo/energy.dmi
  icons/obj/items/ammo/flamer.dmi
  icons/obj/items/ammo/greyscale.dmi
  icons/obj/items/ammo/handful.dmi
  icons/obj/items/ammo/machinegun.dmi
  icons/obj/items/ammo/misc.dmi
  icons/obj/items/ammo/packet.dmi
  icons/obj/items/ammo/pistol.dmi
  icons/obj/items/ammo/powerpack.dmi
  icons/obj/items/ammo/revolver.dmi
  icons/obj/items/ammo/rifle.dmi
  icons/obj/items/ammo/rocket.dmi
  icons/obj/items/ammo/sentry.dmi
  icons/obj/items/ammo/shotgun.dmi
  icons/obj/items/ammo/sniper.dmi
  icons/obj/items/ammo/submachinegun.dmi
  icons/obj/items/ammo/tank.dmi
  icons/obj/items/tools.dmi
Labels: Sprites, Code Improvement

#16134 insane ravager buff
  icons/Xeno/castes/ravager.dmi
Labels: Sprites

#16169 Adds new Tadpole - Outrider Transport
  _maps/shuttles/minidropship_outrider.dmm
  code/datums/shuttles.dm
  code/game/objects/machinery/computer/dropship_picker.dm
  icons/UI_Icons/dropshippicker/_outrider.png
Labels: Sprites, Map Edit, Feature

#16190 Readd xenonauten specific module sprites
  code/modules/clothing/modular_armor/attachments/modules.dm
  icons/mob/modular/modular_armor_modules.dmi
Labels: Sprites

#16181 Campaign loadout changes
  code/_globalvars/lists/flavor_misc.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/belt.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/field_commander.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/standard.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/veteran.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/field_commander.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/marine.dm
  code/datums/gamemodes/campaign/perks.dm
  code/game/objects/items/storage/holsters.dm
  icons/UI_Icons/campaign/loadout_item_icons.dmi
Labels: Sprites

#16097 Tank balance
  code/__DEFINES/calibers.dm
  code/__DEFINES/conflict.dm
  code/__DEFINES/vehicles.dm
  code/datums/storage/subtypes/tank.dm
  code/game/objects/items/pamphlets.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammo_types/ags_ammo.dm
  code/modules/projectiles/ammo_types/energy_ammo.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/microrail_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/projectiles/ammo_types/tx54_ammo.dm
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
  code/modules/projectiles/projectile.dm
  code/modules/reqs/supply.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/_hitbox.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/apc.dm
  code/modules/vehicles/armored/armored_modules.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/armored/som_armored_weapons.dm
  code/modules/vehicles/armored/som_tank.dm
  code/modules/vehicles/sealed.dm
  icons/obj/armored/3x3/tank_interior.dmi
  icons/obj/items/ammo/tank.dmi
  icons/obj/items/projectiles.dmi
Labels: Sprites, Code Improvement, Balance

#16173 Vehicle explosion effect
  code/modules/vehicles/armored/__armored.dm
Labels: Feature

#16182 Bike gun fix
  code/modules/vehicles/vehicle_attachments/weapon_attachments.dm
Labels: Fix

#16196 Fixes being unable to draw from storages within a duffelbag.
  code/_onclick/adjacent.dm
  code/game/objects/items/storage/backpack.dm
Labels: Code Improvement, Fix

#16180 baselight fix
  code/modules/lighting/lighting_static/static_lighting_object.dm
Labels: Fix, Test Merge Candidate

#16178 Admin panel for campaign
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/modules/admin/holder.dm
  code/modules/admin/panels/Campaign_panel.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/CampaignAdminPanel.tsx
Labels: UI

#16114 Desant fix
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/xeno.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
Labels: Stale, Fix

#16189 Lying offset fix
  code/__DEFINES/mobs.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/mob/living/carbon/update_icons.dm
Labels: Fix

#16192 Disallows AI railgun to target FOB
  code/_onclick/ai.dm
Labels: Balance

#16198 Fix after image mouse opacity
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
Labels: Fix

#16153 Lighting error fix
  code/controllers/subsystem/lighting.dm
  code/modules/mapping/map_template.dm
Labels: Code Improvement

#16087 More chat style updates - new announcement colors, admin announcement changes, and more
  code/__DEFINES/chat.dm
  code/__DEFINES/span.dm
  code/__HELPERS/announce.dm
  code/__HELPERS/ooc_announcement.dm
  code/controllers/subsystem/ticker.dm
  code/datums/elements/shrapnel_removal.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/combat_patrol.dm
  code/datums/gamemodes/hvh.dm
  code/datums/gamemodes/infestation.dm
  code/game/atoms/_atom.dm
  code/game/objects/items.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/modules/admin/fun_verbs.dm
  code/modules/client/client_procs.dm
  code/modules/instruments/songs/editor.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/reagents/reagent_containers/pill.dm
  code/modules/screen_alert/command_alert.dm
  sound/misc/adm_announce.ogg
  sound/misc/bloop.ogg
  tgmc.dme
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
Labels: Sound, Feature, UI

#16199 Fixes squad radio for non squad members
  code/datums/jobs/squads.dm
Labels: Fix
