Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2024-10, with the labels that each got.

#16612 Fixes Bigbury buttons
  _maps/shuttles/tgs_bigbury.dmm
Labels: Fix, Map Edit

#16579 Undoes the chemistry lock, chem is open for everyone (also oxy is no longer a free refill from vendors)
  code/game/objects/machinery/doors/airlock_types.dm
  code/modules/reagents/chemistry/machinery/chem_dispenser.dm
  code/modules/reagents/chemistry/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/autoinjectors.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
Labels: Balance

#16546 Hyposprays/Autoinjectors now have 2 second injection delay on non-same faction injectees
  code/modules/reagents/reagent_containers/hypospray.dm
Labels: Balance

#16615 Removes Bomb Vest from Marine Vendors
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal, Balance

#16609 Minor runner evasion description update
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Grammar and Formatting

#16489 Increases devastation damage by 100 against xenos
  code/modules/mob/living/carbon/xenomorph/damage_procs.dm
Labels: Balance, Stale

#16576 Improves Rappel
  code/game/objects/structures/rappel_system.dm
Labels: Balance

#16602 Nuke log
  code/game/objects/machinery/nuclearbomb.dm
Labels: Code Improvement

#16621 Tyr HvH buff
  code/datums/components/_component.dm
  code/datums/components/companion.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance

#16619 Secondary projectile changes
  code/modules/projectiles/ammo_types/ags_ammo.dm
  code/modules/projectiles/ammo_types/microrail_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/projectiles/ammo_types/tx54_ammo.dm
Labels: Balance

#16617 HvH melee stun changes
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance

#16616 Campaign engineer buff
  code/__DEFINES/traits.dm
  code/datums/gamemodes/campaign/perks.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/barricade.dm
Labels: Balance

#16607 fix shrike healing & crit healing and properly addresses regen delays
  code/modules/mob/living/carbon/xenomorph/life.dm
Labels: Fix, Feature

#16625 bed/chair offset fixes
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/vehicles/armored/interiors/chairs.dm
Labels: Fix

#16567 Firenado fixes/improvements
  code/__HELPERS/type2type.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
Labels: Code Improvement, Fix

#16618 Removes barriers around Delta Station's supermatter
  _maps/map_files/deltastation/deltastation.dmm
Labels: Removal, Balance, Map Edit

#16620 Hunter stat adjustment
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Balance

#16623 Buffs Special Resin Walls
  code/game/turfs/walls/resin.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Balance

#16622 Survivening: More survivor content
  code/datums/jobs/job/survivor.dm
  code/game/objects/items/tools/hydro_tools.dm
  code/game/objects/items/tools/surgery_tools.dm
  code/modules/admin/verbs/selectequipment.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/reagents/chemistry/reagents/other.dm
Labels: Balance, Feature, Administration

#16532 Primordial Queens Support Screeches
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/xeno_buffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  icons/Xeno/actions/queen.dmi
  sound/voice/alien/queen_frenzy_screech.ogg
  sound/voice/alien/queen_heal_screech.ogg
  sound/voice/alien/queen_plasma_screech.ogg
Labels: Sprites, Sound, Feature

#16613 Make clients_by_z work
  code/__DEFINES/dcs/signals/signals.dm
  code/game/atoms/atom_movable.dm
  code/modules/lighting/emissive_blocker.dm
  code/modules/mob/dead/dead.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/logout.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
  code/modules/mob/mob.dm
  code/modules/shuttle/on_move.dm
Labels: Code Improvement, Stale

#16646 Suit fixes
  code/datums/components/shield.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/suits/marine_armor.dm
  icons/mob/modular/tdf_armor.dmi
  icons/mob/modular/tdf_helmets.dmi
Labels: Sprites, Code Improvement, Fix

#16581 TE powerbackpack
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/magazines/energy.dm
  icons/mob/clothing/back.dmi
  icons/obj/items/ammo/powerpack.dmi
Labels: Sprites, Feature

#16659 Removes a Chigusa intel computer, Chigusa plat miner removals and movals
  _maps/map_files/desertdam/desertdam.dmm
Labels: Removal, Balance, Map Edit

#16660 Wraith's Timeshift Cancels on Z-Level Change
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#16658 Having 100% Fire Armor Gives You Actual Fire Immunity
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
Labels: Fix

#16670 fixes handcuffs breaking resist when you are un-handcuffed
  code/modules/mob/living/carbon/inventory.dm
Labels: Fix

#16672 FC and Synth loadout vendor tabs + their respective essential kits work with loadout vendors
  code/__DEFINES/loadout.dm
  tgui/packages/tgui/interfaces/LoadoutManager/index.tsx
Labels: UI, Quality of Life

#16645 Adds the UV-T Skink scouting drone
  code/__DEFINES/loadout.dm
  code/game/objects/items/radio/detpack.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/__vehicle.dm
  code/modules/vehicles/unmanned/deployable_vehicles.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
  code/modules/vehicles/unmanned/unmanned_vehicle_remote.dm
  code/modules/xenomorph/resin_gargoyle.dm
  icons/obj/unmanned_vehicles.dmi
Labels: Sprites

#16666 Makes grenades peak
  code/game/objects/items/explosives/grenades/grenade.dm
Labels: Feature

#16671 Deletes a duplicate hairstyle
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites, Fix

#16572 Lower xeno ratio
  code/__DEFINES/jobs.dm
  code/__DEFINES/mode.dm
  code/controllers/subsystem/silo.dm
Labels: Balance, Stale, Test Merge Candidate

#16677 Mech EMP buffs
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/mecha_defense.dm
Labels: Balance

#16676 minigun powerpack fixes
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/specialist.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/weapons/ammo_left.dmi
  icons/mob/inhands/weapons/ammo_right.dmi
Labels: Sprites

#16673 Tank icon update
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/som_tank.dm
  icons/UI_Icons/map_blips_large.dmi
Labels: Sprites, Quality of Life

#16679 Sentry deploy fix
  code/game/objects/structures/dropship_equipment.dm
Labels: Fix

#16596 Chainsaw & Chainsword update and Add chainsaw to req
  code/datums/components/dripping.dm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/inhands/weapons/melee_left.dmi
  icons/mob/inhands/weapons/melee_right.dmi
  sound/weapons/chainsaw_simpson.ogg
  sound/weapons/chainsawstart.ogg
Labels: Sprites, Sound, Balance, Feature

#16665 Plant Weeds Dynamically Shows Ability Cost
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix, Quality of Life

#16611 Playsound improvements
  code/controllers/subsystem/explosions.dm
  code/game/sound.dm
Labels: Code Improvement, Fix, Quality of Life

#16667 Sentry fix
  code/modules/projectiles/sentries.dm
Labels: Fix

#16652 Gives king sledge inmunity
  code/game/objects/items/weapons/twohanded.dm
Labels: Balance

#16661 Equip fix
  code/modules/mob/mob.dm
Labels: Fix, Test Merge Candidate

#16597 Adds the ICC LVRT 'Fallow' vehicle.
  _maps/interiors/icc_recontank.dmm
  code/__DEFINES/calibers.dm
  code/datums/interior/interior_icc_recontank.dm
  code/datums/interior/map_templates.dm
  code/datums/storage/subtypes/tank.dm
  code/game/objects/machinery/buttons.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/icc_armored_weapons.dm
  code/modules/vehicles/armored/icc_recontank.dm
  code/modules/vehicles/armored/interiors/ammo_rack.dm
  code/modules/vehicles/armored/interiors/breech.dm
  icons/obj/armored/2x2/icc_lvrt.dmi
  icons/obj/armored/2x2/icc_lvrt_damage.dmi
  icons/obj/armored/2x2/icc_lvrt_gun.dmi
  icons/obj/armored/3x3/tank_gun.dmi
  icons/obj/armored/hardpoint_modules.dmi
  icons/obj/items/ammo/tank.dmi
  tgmc.dme
Labels: Sprites, Map Edit, Feature

#16684 Chainsaw fix
  code/game/objects/items/weapons/twohanded.dm
Labels: Fix

#16683 Remove tunnel naming
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Removal

#16693 Naming a tunnel no longer leaks your ckey
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Fix

#16689 boot knives for special factions
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  code/datums/jobs/job/mercenaries.dm
  code/datums/jobs/job/pmc.dm
  code/datums/jobs/job/special_forces.dm
  code/datums/jobs/job/vsd.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/shoes/miscellaneous.dm
  icons/mob/clothing/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Sprites, Map Edit

#16681 Xeno Fruit Effects on Death & New Power Fruit Death Effect
  code/__DEFINES/conflict.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/xenomorph/xenoplant.dm
Labels: Removal, Feature

#16515 Bluesummers Wreck Site [NEW MAP]
  _maps/_basemap.dm
  _maps/bluesummers.json
  _maps/map_files/Bluesummers/bluesummers.dmm
  code/__DEFINES/__game.dm
  code/datums/gamemodes/crash.dm
  code/game/area/bluesummers.dm
  code/game/objects/effects/decals/Cleanable/misc.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/effects/spawners/random/machinery.dm
  code/game/objects/items/misc.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/machinery/cryopod.dm
  code/game/objects/machinery/doors/multi_tile.dm
  code/game/objects/machinery/science.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/prop.dm
  code/game/turfs/open.dm
  code/modules/paperwork/paper.dm
  code/modules/power/lighting.dm
  config/maps.txt
  icons/obj/machines/cryogenics2.dmi
  icons/obj/pipes/disposal.dmi
  icons/obj/smooth_objects/ship_window_frame.dmi
  icons/turf/cave.dmi
  icons/turf/cave_drought.dmi
  tgmc.dme
Labels: Sprites, Config Update, Map Edit

#16588 Gorger Rebalances & Visual Effects
  code/__DEFINES/mobs.dm
  code/datums/status_effects/xeno_buffs.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
  icons/effects/96x96.dmi
Labels: Sprites, Balance, Feature, Grammar and Formatting, Quality of Life

#16695 Sentry exploit fix
  code/modules/projectiles/sentries.dm
Labels: Fix

#16690 Melee mech fix
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
Labels: Fix

#16685 Nade message fix
  code/datums/personal_statistics.dm
  code/game/objects/items/explosives/grenades/grenade.dm
Labels: Fix

#16655 Xenomorphs can walk to ignore portals
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Balance

#16697 Changes Xeno to Marine ratio back to 2.46
  code/__DEFINES/jobs.dm
Labels: Balance

#16710 keyloop microopt
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/mob_movement.dm
Labels: Code Improvement

#16708 Gib code improvements
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/decals/Cleanable/robots.dm
  code/game/objects/effects/spawners/gibspawner.dm
  code/modules/recycling/disposal.dm
Labels: Code Improvement

#16707 Fixes crusher "anihilate" typo
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Grammar and Formatting

#16704 Adds Plasma SMG description
  code/modules/projectiles/guns/plasma.dm
Labels: Grammar and Formatting

#16700 Fixes skinks equipping C4 as a weapon
  code/game/objects/items/radio/detpack.dm
  code/modules/vehicles/unmanned/deployable_vehicles.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Fix, Test Merge Candidate

#16709 Signal improvements
  code/datums/signals.dm
Labels: Code Improvement

#16705 Standard webbing can't hold powerpacks/powerbackpacks anymore
  code/datums/storage/subtypes/internal.dm
Labels: Balance

#16718 Fix light break helper complaining about already broken lights
  code/modules/mapping/mapping_helpers.dm
Labels: Fix

#16692 Chestbursting can now happen in EORD/Deathmatch
  code/modules/mob/living/carbon/xenomorph/embryo.dm
Labels: Stale, Feature

#16542 Dancer Praetorian Strain
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/praetorian.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  icons/Xeno/actions/praetorian.dmi
  icons/Xeno/castes/praetorian.dmi
Labels: Sprites, Feature

#16713 Updates roboticist survivor loadout
  code/datums/jobs/job/survivor.dm
Labels: Balance

#16719 Adds xeno spawnpoints to vapor processing
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
Labels: Fix, Map Edit
