Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2024-11, with the labels that each got.

#16712 Moves crash landing spots on Research Outpost
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
Labels: Balance, Map Edit

#16706 Bluesummers v1.1 patch
  _maps/map_files/Bluesummers/bluesummers.dmm
Labels: Balance, Map Edit

#16696 Increases rocket sledge price
  code/modules/reqs/supplypacks.dm
Labels: Balance

#16721 SH-34 secondary fix
  code/datums/gamemodes/campaign/loadout_items/_TGMC/secondaries.dm
Labels: Fix

#16714 Smart pistol Rework. Everyone can now use it.
  code/__DEFINES/loadout.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/inhands/guns/pistols_left_1.dmi
  icons/mob/inhands/guns/pistols_right_1.dmi
  icons/obj/items/ammo/pistol.dmi
  icons/obj/items/guns/pistols.dmi
  icons/obj/items/guns/pistols64.dmi
  icons/obj/items/storage/holster.dmi
Labels: Sprites, Balance

#16726 Razorwire icon fix
  code/game/objects/structures/razorwire.dm
Labels: Fix

#16716 widow can emmit pheromones
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
Labels: Balance, Stale

#16715 Puppeters puppets can have pheros
  code/modules/mob/living/carbon/xenomorph/castes/puppet/puppet.dm
Labels: Balance, Stale

#16587 Buffs Barricades
  code/game/objects/structures/barricade.dm
Labels: Balance, Stale, Test Merge Candidate, Requires Testing

#16727 Combat shotgun resprite
  code/modules/projectiles/guns/shotguns.dm
  icons/mob/clothing/back.dmi
  icons/mob/inhands/guns/shotguns_left_1.dmi
  icons/mob/inhands/guns/shotguns_right_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/guns/attachments/stock.dmi
  icons/obj/items/guns/machineguns64.dmi
  icons/obj/items/guns/shotguns64.dmi
Labels: Sprites

#16600 Temporary hotfix for stripmenu equipping
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Do Not Merge, Stale, Test Merge Candidate

#16734 Fixes godmode puppet bug
  code/datums/status_effects/xeno_buffs.dm
Labels: Fix

#16728 MMG repallete
  icons/mob/clothing/back.dmi
  icons/mob/inhands/guns/machineguns_left_1.dmi
  icons/mob/inhands/guns/machineguns_right_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/guns/attachments/stock.dmi
  icons/obj/machines/deployable/mounted_machinegun.dmi
Labels: Sprites

#16740 Resprites Plasma Pistol
  code/modules/projectiles/guns/pistols.dm
  icons/obj/items/ammo/pistol.dmi
  icons/obj/items/guns/energy.dmi
  icons/obj/items/storage/holster.dmi
Labels: Sprites

#16743 Changes Powerloader Speed & Fixes Powerloader Skill
  code/__DEFINES/skills.dm
  code/modules/vehicles/powerloader.dm
Labels: Balance, Fix

#16742 FOB Construction Drone's Barbed Wiring Costs 1 instead of 2
  code/modules/remote_fob/actions_misc.dm
Labels: Fix

#16720 New praetorian primo: Slime Grenade
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
Labels: Balance, Test Merge Candidate

#16729 Merges Join game and ready up lobby buttons
  code/_onclick/hud/screen_objects/menu_text_objects.dm
Labels: Quality of Life

#16744 BR bookcase density fix 2
  _maps/modularmaps/big_red/bigredlibraryvar2.dmm
  _maps/modularmaps/big_red/bigredlibraryvar3.dmm
Labels: Fix, Map Edit

#16741 Hunter stealth damage threshold
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Balance

#16748 Railgun repallete
  icons/mob/clothing/back.dmi
  icons/mob/inhands/guns/special_left_1.dmi
  icons/mob/inhands/guns/special_right_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/guns/special64.dmi
Labels: Sprites

#16754 Raises silo scaling to 2x
  code/datums/gamemodes/nuclear_war.dm
Labels: Balance

#16756 Recoilless Rifle edit and repallete
  icons/mob/clothing/back.dmi
  icons/mob/inhands/guns/special_left_1.dmi
  icons/mob/inhands/guns/special_right_1.dmi
  icons/mob/suit_slot.dmi
  icons/obj/items/guns/machineguns64.dmi
  icons/obj/items/guns/special64.dmi
  icons/obj/items/storage/backholster.dmi
Labels: Sprites

#16757 Removes confirmation for toggle_sleep verb
  code/modules/admin/admin_verbs.dm
Labels: Removal, Administration

#16751 Direct Hits from Tesla Ball no longer drains from the Plasmadrain Immune
  code/modules/projectiles/ammo_types/energy_ammo.dm
Labels: Fix

#16753 Fixes inaccessible buttons on canterbury and bigbury
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
Labels: Fix, Map Edit

#16763 Wraith Portals are Lava Immune
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#16768 Fixes hunter being able to break the tad console from stealth
  code/modules/shuttle/mini_dropship.dm
Labels: Balance, Fix
