Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2024-05, with the labels that each got.

#15747 apc minimap
  code/modules/vehicles/armored/apc.dm
  icons/UI_Icons/map_blips_large.dmi
Labels: Sprites, Feature

#15748 Creates a new type of rock wall for Magmoor
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  code/game/turfs/closed.dm
  code/game/turfs/open.dm
  icons/turf/walls/lava_wall.dmi
Labels: Sprites, Fix, Map Edit, Feature

#15777 Fixes missing alamo consoles on Lawanka and Daedalus
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
Labels: Fix, Map Edit

#15750 Adds a garage to southwest Ice Colony
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  code/game/area/icecolony.dm
Labels: Map Edit, Feature

#15778 Increases QB for Gelida
  _maps/gelida_iv.json
Labels: Balance, Map Edit

#15771 Fix mob hit sound
  code/modules/mob/living/living_defense.dm
Labels: Fix

#15715 Misc proc cleanup
  code/__DEFINES/mobs.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/items/defibrillator.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/embryo.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
Labels: Code Improvement

#15767 New prop vehicles
  code/game/objects/structures/prop.dm
  icons/obj/structures/vehicles.dmi
  icons/obj/vehicles/64x64.dmi
  icons/obj/vehicles/large_truck.dmi
Labels: Sprites

#15776 Shipside rank overhaul
  code/datums/jobs/access.dm
  code/datums/jobs/job/shipside.dm
Labels: Grammar and Formatting

#15766 Psycrush and psyblast multitile walance changes
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/projectiles/ammo_types/xenos/energy_xenoammo.dm
Labels: Balance

#15772 Closet exploit
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix, In Game Exploit

#15769 Full ranks show up in command annoucements
  code/game/objects/machinery/computer/communications.dm
  code/modules/screen_alert/command_alert.dm
Labels: Feature

#15694 Removes minimum pop from Transport Crewmen
  code/datums/gamemodes/nuclear_war.dm
  code/datums/jobs/job/shipside.dm
Labels: Removal, Balance, Test Merge Candidate

#15693 Removes the ability to build cades on tadpoles, adds a new mapping helper and flag
  _maps/shuttles/minidropship_big.dmm
  _maps/shuttles/minidropship_factorio.dmm
  _maps/shuttles/minidropship_food.dmm
  _maps/shuttles/minidropship_mobile_bar.dmm
  _maps/shuttles/minidropship_standard.dmm
  _maps/shuttles/minidropship_umbilical.dmm
  code/__DEFINES/area.dm
  code/_globalvars/bitfields.dm
  code/datums/components/crafting/crafting.dm
  code/game/area/areas/shuttles.dm
  code/game/objects/effects/effect_system/foam.dm
  code/game/objects/items/quickdeploy_cade.dm
  code/game/objects/items/stacks/barbed_wire.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/barricade.dm
  code/modules/mapping/mapping_helpers.dm
Labels: Removal, Balance, Map Edit, Feature

#15775 Yet more campaign loadout icons
  code/_globalvars/lists/flavor_misc.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/belt.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/engineer.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/field_commander.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/medic.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/squad_leader.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/standard.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/veteran.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/corpsman.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/engineer.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/field_commander.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/marine.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/smartgunner.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/squad_leader.dm
  icons/UI_Icons/campaign/loadout_item_icons.dmi
Labels: Sprites

#15786 Removes walking grenades
  code/game/objects/items/explosives/grenades/grenade.dm
Labels: Removal, Code Improvement

#15788 Truck fix
  code/game/objects/structures/prop.dm
Labels: Fix

#15780 Proper storage fix
  code/datums/storage/storage.dm
Labels: Fix

#15784 Perk unlock animation tweak
  code/datums/gamemodes/campaign/perks.dm
  icons/effects/perk_unlock.dmi
Labels: Sprites

#15793 Runtime fixes
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/jobs/squads.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/items/motion_detector.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/weapon.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/teleporter_array.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/sentries.dm
  code/modules/vehicles/mecha/mecha_mob_interaction.dm
Labels: Code Improvement

#15773 EMP stuff
  code/__DEFINES/combat.dm
  code/__DEFINES/mecha.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm
  code/game/objects/empulse.dm
  code/game/objects/items/explosives/grenades/emgrenade.dm
  code/game/objects/items/flash.dm
  code/game/objects/items/implants/implant_neurostim.dm
  code/game/objects/items/portable_vendor.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/machinery/cell_charger.dm
  code/game/objects/machinery/computer/arcade.dm
  code/game/objects/machinery/computer/computer.dm
  code/game/objects/machinery/computer/medical.dm
  code/game/objects/machinery/computer/security.dm
  code/game/objects/machinery/computer/skills.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/fire_alarm.dm
  code/game/objects/machinery/flasher.dm
  code/game/objects/machinery/igniter.dm
  code/game/objects/machinery/lightswitch.dm
  code/game/objects/machinery/recharger.dm
  code/game/objects/machinery/sleeper.dm
  code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
  code/game/objects/structures/crates_lockers/secure_crates.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/glasses/thermal.dm
  code/modules/mob/living/brain/life.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/organs/limbs.dm
  code/modules/organs/organ_internal.dm
  code/modules/power/apc/apc.dm
  code/modules/power/cell.dm
  code/modules/power/smes.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/sentries.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/mecha_defense.dm
  icons/obj/device.dmi
  sound/magic/lightningshock.ogg
Labels: Sprites, Sound, Code Improvement, Balance, Feature

#15755 tank resprite
  code/datums/interior/interior_tank.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/armored_modules.dm
  icons/obj/armored/3x3/apc.dmi
  icons/obj/armored/3x3/tank.dmi
  icons/obj/armored/3x3/tank_damage.dmi
  icons/obj/armored/3x3/tank_gun.dmi
  icons/obj/armored/hardpoint_modules.dmi
Labels: Sprites

#15774 Campaign map colours
  code/__DEFINES/objects.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/missions/airbase_raid.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/datums/gamemodes/campaign/missions/mech_wars.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
  code/datums/gamemodes/campaign/missions/supply_raid.dm
  code/game/objects/items.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/mark_one.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/modular_armor/xenonauten.dm
Labels: Quality of Life

#15779 Fixes a few crafting interactions
  code/__DEFINES/is_helpers.dm
  code/datums/components/crafting/crafting.dm
  code/game/objects/items/stacks/sandbags.dm
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/stack_recipe.dm
  code/game/turfs/liquid_turfs.dm
  code/game/turfs/space.dm
Labels: Fix

#15792 Fixes stray areas on Gelida IV
  _maps/map_files/gelida_iv/gelida_iv.dmm
Labels: Fix, Map Edit

#15781 Orion Outpost Changes
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  code/game/objects/structures/prop.dm
Labels: Balance, Map Edit

#15791 Magmoor tweaks
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  code/game/area/magmoor_digsite.dm
Labels: Fix, Map Edit, Feature

#15801 Tad can land on lavaland tiles
  code/modules/shuttle/navigation_computer.dm
Labels: Fix

#15797 Lazy weed test fix
  code/modules/unit_tests/weed_spread.dm
Labels: Fix, Unit Tests

#15802 Implement more uses of PopulateContents()
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/closets/fitness.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/l3closet.dm
  code/game/objects/structures/crates_lockers/closets/secure/bar.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Code Improvement

#15676 Stacks of newly crafted items merge to existing stacks in user hands
  code/game/objects/items/stacks/stack.dm
Labels: Feature

#15813 Fixes reagent exploit
  code/modules/reagents/chemistry/holder/holder.dm
Labels: Fix, In Game Exploit

#15804 update pilot visuals
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sons_of_mars_shipside.dm
  code/game/objects/structures/crates_lockers/closets/secure/cm_closets.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/marine_armor.dm
  icons/mob/clothing/headwear/marine_helmets.dmi
  icons/mob/clothing/suits/marine_armor.dmi
  icons/mob/clothing/uniforms/marine_uniforms.dmi
  icons/obj/clothing/headwear/marine_helmets.dmi
  icons/obj/clothing/suits/marine_armor.dmi
  icons/obj/clothing/uniforms/marine_uniforms.dmi
Labels: Sprites, Feature

#15817 Fixes transport crewman and assault crewman orbit menu icons
  code/_globalvars/lists/flavor_misc.dm
Labels: Fix

#15803 Campaign loadout fixes
  code/datums/gamemodes/campaign/loadout_items/SOM/head.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage/medic.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/head.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/pockets.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm
  code/datums/gamemodes/campaign/perks.dm
  code/modules/clothing/modular_armor/som.dm
  code/modules/clothing/modular_armor/xenonauten.dm
Labels: Fix

#15819 Xeno building fixes
  code/modules/xenomorph/acid_pools.dm
  code/modules/xenomorph/resin_gargoyle.dm
  icons/UI_Icons/map_blips.dmi
Labels: Sprites, Balance, Fix

#15798 fixed emoji todo + emoji unit test
  code/modules/asset_cache/asset_list_items.dm
  code/modules/emoji/emoji_parse.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/verify_emoji_names.dm
  icons/misc/emoji.dmi
Labels: Sprites, Code Improvement, Unit Tests

#15809 adds proc/wash()
  code/__DEFINES/colors.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/misc.dm
  code/game/atoms/_atom.dm
  code/game/blood.dm
  code/game/objects/effects/decals/cleanable.dm
  code/game/objects/items/tools/cleaning_tools.dm
  code/game/objects/structures/watercloset.dm
  code/game/turfs/turf.dm
  code/modules/reagents/chemistry/reagents/other.dm
Labels: Code Improvement

#15814 Minimap code fix
  code/controllers/subsystem/minimaps.dm
Labels: Fix

#15826 Roomba no longer permanently curses storages that get vacuumed
  code/game/objects/machinery/cryopod.dm
Labels: Fix

#15821 Removes Slumbridge's CAS prop, replaces with tank AND fixes lava prison tiles
  _maps/map_files/slumbridge/slumbridge.dmm
Labels: Removal, Fix, Map Edit

#15828 Campaign end of mission/game messaging
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/combat_patrol.dm
  code/datums/gamemodes/extended.dm
  code/datums/gamemodes/infestation.dm
Labels: Quality of Life

#15795 Observers can jump to locations using their minimap
  code/controllers/subsystem/minimaps.dm
Labels: Quality of Life

#15833 Xenos can slash dense plants
  code/game/objects/structures/flora.dm
Labels: Quality of Life

#15834 Basketball hoops can be slashed
  code/game/objects/items/toys/toys.dm
Labels: Quality of Life

#15835 Adds some reagent signals
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/dcs/signals/signals_reagent.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/chemistry/holder/holder.dm
Labels: Code Improvement

#15841 turns clean_mob into clean_blood()
  code/datums/weather/weather_types/acid_rain.dm
  code/game/atoms/_atom.dm
  code/game/blood.dm
  code/game/turfs/liquid_turfs.dm
Labels: Code Improvement

#15827 fixes proper args in playsound_local()
  code/controllers/subsystem/explosions.dm
  code/controllers/subsystem/tts.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/instruments/songs/play_legacy.dm
  code/modules/instruments/songs/play_synthesized.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
Labels: Fix

#15829 Reduces Behemoth's Ability Damage Against Vehicles
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Balance

#15853 Jerrycans show correct amount of fuel when examined
  code/modules/reagents/reagent_containers/jerrycan.dm
Labels: Fix

#15852 Alamo build fix
  code/__HELPERS/game.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Fix

#15831 Campaign corpsman fix
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage/corpsman.dm
Labels: Fix

#15820 Attrition fix
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Fix

#15837 SL enabled rapid reserves
  code/datums/gamemodes/campaign/rewards/reserves.dm
Labels: Balance

#15647 Health analyzer update
  code/__DEFINES/defibrillator.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/scanners.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/MedScanner.jsx
Labels: Feature, UI

#15858 Xenos no longer can use abilities in dense & opaque objs
  code/__DEFINES/actions.dm
  code/_globalvars/bitfields.dm
  code/datums/actions/ability_actions.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#15862 Allows AI to be dragged when unanchored
  code/modules/mob/living/silicon/ai/ai.dm
Labels: Balance

#15861 Allows AI to get coords from weeds
  code/_onclick/ai.dm
Labels: Fix

#15855 Runtime fixes
  code/controllers/subsystem/minimaps.dm
  code/game/objects/structures/droppod.dm
  code/modules/condor/cas_shuttle.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/xenomorph/tunnel.dm
Labels: Code Improvement

#15838 Auto attrition selection
  code/__DEFINES/campaign.dm
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Quality of Life

#15864 Click catcher fix
  code/datums/atom_hud.dm
  code/modules/client/client_procs.dm
Labels: Fix

#15863 Retired ERT adjustments
  code/datums/emergency_calls/retired.dm
  code/datums/jobs/job/retired.dm
Labels: Balance

#15866 Pref sound fix
  code/datums/storage/storage.dm
  code/datums/storage/subtypes/bag.dm
  code/datums/storage/subtypes/box.dm
  code/datums/storage/subtypes/holster.dm
  code/datums/storage/subtypes/internal.dm
  code/datums/storage/subtypes/pill_bottle.dm
  code/datums/storage/subtypes/wallet.dm
Labels: Fix

#15870 Charile typo to Charlie
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/under/marine_uniform.dm
Labels: Grammar and Formatting

#15868 Xeno leader death timer fix
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#15815 Tank adjustments
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
Labels: Balance

#15847 New voicelines for donning and doffing Valkyrie and B18
  code/datums/components/suit_autodoc.dm
  sound/voice/b18_activate.ogg
  sound/voice/b18_deactivate.ogg
Labels: Sound

#15887 fix destroyable forcefield
  _maps/map_files/riptide/riptide.dmm
  code/game/objects/effects/misc.dm
Labels: Fix, Map Edit

#15873 Fills in some packet descriptions
  code/modules/projectiles/magazines/misc.dm
Labels: Grammar and Formatting

#15876 Fixes overwatch being unable to select targets to OB
  code/game/objects/machinery/overwatch.dm
Labels: Fix

#15883 Map fixes
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Campaign maps/orion_2/orionoutpost_2.dmm
  _maps/map_files/Campaign maps/som_base/sombase.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/modularmaps/EORG/original.dmm
  _maps/shuttles/alamo.dmm
Labels: Fix, Map Edit

#15878 Attrition fix 2
  code/datums/gamemodes/campaign.dm
Labels: Fix

#15875 stagger gun code adjustment
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/projectile.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Balance, Fix

#15891 Adds logging to LZ Containment Shutters
  code/game/objects/machinery/buttons.dm
Labels: Administration, Logging

#15880 adds thermal tarps to valhalla
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#15842 Removes evo fade in for xenos
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Removal

#15872 Clarifies that Behemoth rolling ram deals no damage
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Quality of Life

#15882 call wash() instead of clean_blood()
  code/game/objects/items/tools/cleaning_tools.dm
  code/game/objects/machinery/bots/cleanbot.dm
  code/game/objects/machinery/suit_storage_unit.dm
  code/game/objects/machinery/washing_machine.dm
  code/game/objects/structures/watercloset.dm
  code/modules/detectivework/footprints_and_rag.dm
Labels: Code Improvement

#15892 See Through sprite opacity QOL change
  code/datums/components/seethrough_mob.dm
Labels: Quality of Life

#15896 Ravager Rage Screenshake no longer effects the ravager
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Balance

#15871 Fixes bar signs
  code/game/objects/structures/barsign.dm
  code/game/objects/structures/signs.dm
Labels: Fix

#15825 Scaling loadouts for campaign
  code/__DEFINES/campaign.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
Labels: Balance, Feature

#15810 Tele COPE
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/fire_support.dm
  code/datums/fire_support.dm
  code/datums/fire_support/drop_pod.dm
  code/datums/fire_support/fire_support.dm
  code/datums/fire_support/gun_run.dm
  code/datums/fire_support/missile.dm
  code/datums/fire_support/mortar.dm
  code/datums/fire_support/rockets.dm
  code/datums/fire_support/teleport.dm
  code/datums/gamemodes/campaign/rewards/teleporter.dm
  code/game/objects/items/firesupport_binoculars.dm
  code/game/objects/machinery/mortar.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/teleporter_array.dm
  tgmc.dme
Labels: Feature

#15830 Adds a vehicle spawner to xeno valhalla
  _maps/map_files/generic/Admin_Level.dmm
  code/game/objects/effects/landmarks/landmarks.dm
  code/game/objects/machinery/buttons.dm
Labels: Map Edit, Feature

#15888 Deletes unused hostile simple animals.
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/riptide/riptide.dmm
  code/__DEFINES/is_helpers.dm
  code/game/objects/effects/spiders.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/simple_animal/hostile/alien.dm
  code/modules/mob/living/simple_animal/hostile/carp.dm
  code/modules/mob/living/simple_animal/hostile/constructs.dm
  code/modules/mob/living/simple_animal/hostile/faithless.dm
  code/modules/mob/living/simple_animal/hostile/giant_spider.dm
  code/modules/mob/living/simple_animal/hostile/hivebot.dm
  code/modules/mob/living/simple_animal/hostile/mimic.dm
  code/modules/mob/living/simple_animal/hostile/pirate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate.dm
  code/modules/mob/living/simple_animal/hostile/retaliate/clown.dm
  code/modules/mob/living/simple_animal/hostile/russian.dm
  code/modules/mob/living/simple_animal/hostile/shade.dm
  code/modules/mob/living/simple_animal/hostile/syndicate.dm
  code/modules/mob/living/simple_animal/hostile/tree.dm
  code/modules/tgui/states/notcontained.dm
  icons/effects/effects.dmi
  icons/mob/animal.dmi
  icons/mob/ghost.dmi
  icons/mob/hivebot.dmi
  icons/mob/landmarks.dmi
  icons/mob/mob.dmi
  icons/mob/simple_human.dmi
  icons/obj/flora/pinetrees.dmi
  tgmc.dme
Labels: Sprites, Removal, Map Edit

#15682 Smooth move update
  code/__DEFINES/mobs.dm
  code/__DEFINES/movement.dm
  code/__HELPERS/spatial_info.dm
  code/controllers/subsystem/time_track.dm
  code/datums/components/riding/riding.dm
  code/datums/components/riding/riding_mob.dm
  code/datums/components/riding/riding_vehicle.dm
  code/game/atoms/atom_movable.dm
  code/game/buckling.dm
  code/game/objects/effects/effect_system/particle_effects.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/structures/door_assembly.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/admin/smites/puzzle.dm
  code/modules/ai/ai_behaviors/xeno/xeno_illusion.dm
  code/modules/mob/camera/imaginary_friend.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/mob/mob_movement.dm
  code/modules/mob/mob_movespeed.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/vehicles/__vehicle.dm
  code/modules/vehicles/_hitbox.dm
  code/modules/vehicles/cargo_train.dm
  code/modules/vehicles/powerloader.dm
  code/modules/vehicles/train.dm
Labels: Fix, Test Merge Candidate

#15832 Lava and fire jumping
  code/modules/mob/living/living_defense.dm
Labels: Balance

#15901 Adds a bitfield menu for xeno_flags
  code/_globalvars/bitfields.dm
Labels: Code Improvement

#15859 Slumbridge wellness check
  _maps/map_files/slumbridge/slumbridge.dmm
  code/game/objects/structures/platforms.dm
Labels: Balance, Fix, Map Edit, Quality of Life

#15918 Tank Desant projectile fix
  code/modules/projectiles/projectile.dm
Labels: Fix

#15921 Lava hotfix
  code/modules/mob/living/living_defense.dm
Labels: Fix

#15914 Adds (harmless) rain on Desparity and Lawanka
  _maps/desparity.json
  _maps/lawanka.json
Labels: Map Edit, Feature

#15917 Fixes bug preventing tangle mortar shells from being ordered
  code/modules/reqs/supplypacks.dm
Labels: Fix

#15902 Removes an extra plat miner from big red – west Eta
  _maps/modularmaps/big_red/bigredsouthwestetavar5.dmm
Labels: Removal, Balance, Map Edit

#15893 Fix bluetooth tactical reload
  code/modules/projectiles/gun_helpers.dm
Labels: Fix

#15890 Minor Boiler QOL changes
  code/__DEFINES/action.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  icons/Xeno/actions.dmi
  icons/Xeno/actions_boiler_glob.dmi
Labels: Sprites, Quality of Life

#15923 Sorts hud.dmi into it's own folder.
  code/__DEFINES/mobs.dm
  code/datums/components/chem_booster.dm
  code/game/atoms/_atom.dm
  code/game/data_huds.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppet/puppet.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/xenomorph/tunnel.dm
  icons/Xeno/actions.dmi
  icons/mob/hud.dmi
  icons/mob/hud/aura.dmi
  icons/mob/hud/human.dmi
  icons/mob/hud/human_health.dmi
  icons/mob/hud/infected.dmi
  icons/mob/hud/intoxicated.dmi
  icons/mob/hud/job.dmi
  icons/mob/hud/xeno.dmi
  icons/mob/hud/xeno_health.dmi
Labels: Sprites

#15924 Adds a ton of digsites to Riptide, Magmoor, and Lawanka
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/riptide/riptide.dmm
Labels: Map Edit, Feature

#15925 Tank collision fixes
  code/modules/vehicles/_hitbox.dm
  code/modules/vehicles/armored/__armored.dm
Labels: Fix

#15927 Renames chestburster prefs
  code/__DEFINES/preferences.dm
Labels: Grammar and Formatting

#15783 Adds the CPC (Clone Personnel Carrier) module
  _maps/interiors/apc_cloner.dmm
  code/datums/interior/interior_apc.dm
  code/datums/interior/map_templates.dm
  code/game/objects/machinery/cloning/cloning.dm
  code/game/objects/machinery/kitchen/gibber.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/apc.dm
  code/modules/vehicles/armored/armored_modules.dm
  icons/obj/armored/3x3/apc.dmi
  icons/obj/machines/cryogenics.dmi
Labels: Sprites, Map Edit, Feature, Test Merge Candidate

#15920 Catwalk Improvements
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/riptide/riptide.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  code/__DEFINES/ai.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/objects.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/lattice.dm
  code/game/turfs/liquid_turfs.dm
  code/game/turfs/open.dm
  code/game/turfs/turf.dm
  icons/turf/floors/lava.dmi
Labels: Sprites, Code Improvement, Map Edit, Feature

#15737 Mini Bull rework and buff
  code/modules/mob/living/carbon/xenomorph/castes/bull/abilities_bull.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Balance, Fix, Grammar and Formatting, Test Merge Candidate

#15916 Reduces Puppet Damage
  code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm
Labels: Balance

#15922 Makes the hypos in the NTMed default to being empty
  code/game/objects/machinery/vending/vending_types.dm
Labels: Quality of Life

#15919 Makes tad repairable and adds circuit board to req
  code/game/objects/items/circuitboards/circuitboard.dm
  code/game/objects/machinery/computer/computer.dm
  code/modules/reqs/supplypacks.dm
  code/modules/shuttle/mini_dropship.dm
  icons/obj/items/circuitboards.dmi
Labels: Sprites, Feature

#15930 Robot beginner loadouts
  code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
  code/datums/outfit.dm
  code/datums/quick_load_beginners.dm
  code/datums/quick_load_robots.dm
  code/game/objects/machinery/vending/beginner_vendor.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/under/marine_uniform.dm
  tgmc.dme
Labels: Feature

#15903 Som ERT breacher skills
  code/datums/emergency_calls/sons_of_mars_breachers.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/sons_of_mars_ert.dm
  code/datums/skills.dm
Labels: Balance

#15626 adds in Pyrogen Xenomorph Caste
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/status_effects.dm
  code/__DEFINES/traits.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_globalvars/lists/mobs.dm
  code/controllers/subsystem/explosions.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/items.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/tools/flame_tools.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammo_types/miscellaneous_ammo.dm
  code/modules/projectiles/ammo_types/xenos/pyrogen_xenoammo.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/reagents/chemistry/reagents/other.dm
  code/modules/xenomorph/acidwell.dm
  icons/UI_Icons/map_blips.dmi
  icons/Xeno/actions.dmi
  icons/Xeno/castes/pyrogen.dmi
  icons/Xeno/pyrogen.dmi
  icons/effects/64x64.dmi
  icons/effects/beam.dmi
  icons/effects/fire.dmi
  icons/mob/OnFire.dmi
  icons/obj/items/projectiles.dmi
  sound/effects/fireball.ogg
  sound/effects/firebeam.ogg
  sound/effects/prepare.ogg
  sound/effects/wind.ogg
  tgmc.dme
Labels: Sprites, Sound, Feature

#15941 Chem Exploit fix
  code/__DEFINES/dcs/signals/signals_reagent.dm
  code/modules/reagents/chemistry/holder/holder.dm
Labels: Fix

#15942 Prevents Crusher from crest tossing vehicles
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
Labels: Balance

#15940 Fixes vsd (redoing pr)
  code/datums/emergency_calls/vsd.dm
  code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
  code/datums/jobs/job/vsd.dm
  icons/UI_Icons/campaign/asset_icons.dmi
  icons/UI_Icons/map_blips.dmi
  icons/mob/clothing/back.dmi
  icons/mob/hud/job.dmi
  icons/mob/suit_slot.dmi
  icons/obj/clothing/belts.dmi
Labels: Sprites, Fix

#15874 Health analyzer patch: tooltips and other stuff
  code/__DEFINES/mobs.dm
  code/__DEFINES/synthetic.dm
  code/game/objects/items/scanners.dm
  code/modules/mob/living/carbon/human/species_types/synthetics.dm
  code/modules/mob/living/living_defines.dm
  code/modules/organs/organ_internal.dm
  code/modules/reagents/chemistry/reagents/medical.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/MedScanner.jsx
Labels: Fix, Feature, UI

#15947 Cat's cannot be picked up from range anymore
  code/_onclick/drag_drop.dm
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Fix

#15790 Adds strains framework
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/unit_tests/xeno_logical_scaling.dm
Labels: Feature

#15944 Adds brake function to roller beds
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Balance
