Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2024-02, with the labels that each got.

#14932 adds some tx54 grenades to valhalla vendors
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#14926 You can no longer go over blood limit, or below 0 blood
  code/game/objects/items/implants/implant_chem.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/modules/admin/smites/bloodless.dm
  code/modules/mob/living/blood.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_health_procs.dm
  code/modules/organs/wound.dm
  code/modules/reagents/reagents/alcohol.dm
  code/modules/reagents/reagents/food.dm
  code/modules/reagents/reagents/medical.dm
  code/modules/reagents/reagents/toxin.dm
Labels: Fix

#14800 Arachne Symmetry Fix and CAS Bay Adjustment
  _maps/map_files/Arachne/TGS_Arachne.dmm
Labels: Map Edit, Quality of Life

#14976 ASAT tweak
  code/datums/gamemodes/campaign/missions/asat_capture.dm
Labels: Balance

#14980 Fixes invisible cryopods on Magmoor.
  code/game/objects/structures/misc.dm
Labels: Fix

#14899 Runner evasion can be cancelled early
  code/__DEFINES/cooldowns.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
Labels: Balance, Quality of Life

#14938 Caste Swap
  code/__DEFINES/traits.dm
  code/_globalvars/misc.dm
  code/modules/mob/living/carbon/xenomorph/evo_datum.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Code Improvement, Balance

#14991 Removes jumping
  code/modules/mob/living/carbon/human/emote.dm
Labels: Removal, Cringe

#14989 Motion sensor fix again
  code/game/objects/items/motion_detector.dm
  code/modules/projectiles/gun_system.dm
Labels: Fix

#14994 Adjust psylance stagger
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#14912 Evolution tower buff
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/xenomorph/xenotowers.dm
Labels: Balance, Test Merge Candidate

#14997 Recoil fixes
  code/modules/projectiles/guns/specialist.dm
Labels: Fix

#14990 Fix middle click pref for humans
  code/_onclick/click.dm
Labels: Fix

#14992 Fix b18 gloves
  code/modules/clothing/gloves/marine_gloves.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: Sprites, Fix

#14834 Recoilless and Flak cannon seasonal
  code/controllers/subsystem/persistence.dm
Labels: Feature, Test Merge Candidate

#14988 delete specialclick
  code/__DEFINES/dcs/signals.dm
  code/datums/keybinding/carbon.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/effects/weeds.dm
  code/game/objects/structures.dm
  strings/tips/marine.txt
Labels: Removal

#15000 Some fullscreen overlay fixes (this fixes the vali necro overlay)
  code/_onclick/hud/fullscreen.dm
Labels: Code Improvement, Fix

#14945 Halves Psychic Drain's plasma cost
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance

#15001 Adds proc attack_self_alternate()
  code/__DEFINES/dcs/signals.dm
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
Labels: Code Improvement

#14960 Revert "Fix flamer back tank disconnecting with magharness"
  code/datums/components/reequip.dm
  code/modules/projectiles/gun_system.dm
Labels: Revert, Test Merge Candidate

#15014 ASL rally arrows fix
  code/datums/actions/order_action.dm
Labels: Fix

#15017 Attrition fix
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Fix

#15011 Mine alpha fix
  code/game/objects/items/explosives/mine.dm
Labels: Fix

#15009 ASAT mission fixes
  code/datums/gamemodes/campaign/missions/asat_capture.dm
  code/game/objects/structures/campaign_structures/capture_objectives.dm
Labels: Fix

#15016 SG-162 high impact and heavy impact now apply their CC for 1 second instead of 1 decisecond.
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#15007 Campaign autobalance tweaks
  code/__DEFINES/campaign.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
Labels: Balance

#14998 Campaign individual performance rewards
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/individual_stats.dm
  code/datums/jobs/job/job.dm
  code/datums/personal_statistics.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/structures/campaign_structures/capture_objectives.dm
  code/game/objects/structures/campaign_structures/deploy_blockers.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/projectile.dm
Labels: Balance

#14927 removes xeno probing
  code/game/objects/items/tools/research_tools.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/requisitions/supply_export.dm
  icons/obj/items/implants.dmi
Labels: Sprites, Removal, Balance, Feature

#15019 Adds Baneling to Admin Player Panel
  code/modules/admin/panels/player_panel.dm
Labels: Feature

#15021 makes sure extra_checks all use proc_ref
  code/game/objects/machinery/computer/buildandrepair.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/atmospherics/machinery/components/unary_devices/vent_pump.dm
  code/modules/power/fusion_engine.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/recycling/disposal-construction.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
  code/modules/shuttle/navigation_computer.dm
  code/modules/vehicles/multitile/cm_armored.dm
Labels: Code Improvement

#15023 Tfoot OB inaccuracy penalty
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/structures/orbital_cannon.dm
Labels: Balance

#15025 Fix smartgun loadouts
  code/__DEFINES/loadout.dm
Labels: Fix

#15024 Delta level clarification
  code/game/objects/machinery/computer/communications.dm
Labels: Quality of Life

#15027 Changes gargoyle's alert sound
  code/modules/xenomorph/resin_gargoyle.dm
Labels: Quality of Life

#15026 Fix some toggle visuals
  code/datums/actions/item_action.dm
  code/game/objects/items.dm
  code/game/objects/items/blink_drive.dm
  code/game/objects/items/implants/implant.dm
  code/game/objects/items/jetpack.dm
  code/game/objects/items/motion_detector.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/projectiles/gun_attachables.dm
  code/modules/projectiles/gun_helpers.dm
Labels: Quality of Life

#15004 Transport Officer
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/shuttles/minidropship_factorio.dmm
  _maps/shuttles/minidropship_food.dmm
  _maps/shuttles/minidropship_mobile_bar.dmm
  _maps/shuttles/minidropship_standard.dmm
  _maps/shuttles/minidropship_umbilical.dmm
  code/__DEFINES/access.dm
  code/__DEFINES/jobs.dm
  code/datums/gamemodes/extended.dm
  code/datums/gamemodes/nuclear_war.dm
  code/datums/jobs/access.dm
  code/datums/jobs/job/fallen.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/squads.dm
  code/datums/skills.dm
  code/game/objects/effects/landmarks/marine_spawns.dm
  code/game/objects/items/devices/tablets.dm
  code/modules/shuttle/mini_dropship.dm
  icons/UI_Icons/map_blips.dmi
  icons/mob/hud.dmi
  icons/mob/landmarks.dmi
  tgui/packages/tgui/interfaces/PlayerPreferences/JobPreferences.tsx
Labels: Sprites, Do Not Merge, Balance, Map Edit, Feature, Do Not TM, UI

#14939 Add interactive emotes
  code/_onclick/hud/hud.dm
  code/_onclick/hud/interactive_emotes.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
  code/modules/mob/mob_defines.dm
  tgmc.dme
Labels: Feature

#15010 Base rescue mission tweaks
  code/datums/gamemodes/campaign/missions/base_rescue.dm
Labels: Balance

#14996 Stagger doesn't stack in duration anymore
  code/modules/projectiles/ammo_datums.dm
Labels: Do Not Merge, Balance

#15032 chicken protein bars no longer runtime when you eat a different type of protein bar
  code/game/objects/items/marine_gear.dm
Labels: Fix

#15030 Beacon Auto update when changing Z-level instead of turning off
  code/datums/components/beacon.dm
  code/game/objects/machinery/squad_supply/supply_console.dm
Labels: Quality of Life

#15031 Long and spread nozzle are gone from acquisition.
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal, Balance

#15038 Capture exploit fix
  code/modules/shuttle/marine_dropship.dm
Labels: Fix

#15039 Caste swap / regress exploit fix
  code/modules/mob/living/carbon/xenomorph/evolution.dm
Labels: Fix

#15040 Rappel effect+
  code/__DEFINES/dcs/signals.dm
  code/datums/elements/footstep.dm
  code/game/objects/effects/temporary_visuals/explosions.dm
  code/game/objects/structures/patrol_points.dm
Labels: Feature

#15037 Increases expert timelock to 25 hours
  code/__DEFINES/jobs.dm
Labels: Administration

#14855 Re-PR Lewd's Behemoth changes
  code/__DEFINES/dcs/signals.dm
  code/datums/actions/ability_actions.dm
  code/datums/actions/xeno_action.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  icons/effects/effects.dmi
  sound/effects/behemoth/seismic_fracture_landing.ogg
Labels: Sprites, Sound, Balance, Stale, Refactor, Fix, Feature, Grammar and Formatting, Test Merge Candidate

#14914 port TG surgery tool sprites
  icons/mob/inhands/equipment/surgery_left.dmi
  icons/mob/inhands/equipment/surgery_right.dmi
  icons/obj/items/surgery_tools.dmi
Labels: Sprites

#15033 Fixes big red medbay variant 4 and 5 pipes.
  _maps/modularmaps/big_red/bigredmedbayvar4.dmm
  _maps/modularmaps/big_red/bigredmedbayvar5.dmm
Labels: Fix, Map Edit

#14987 Shifts SG prep door on Cantabury so they may leave without breaking glass
  _maps/shuttles/tgs_canterbury.dmm
Labels: Stale, Fix, Map Edit

#14957 Fancy announcements (again)
  code/__DEFINES/span.dm
  code/__HELPERS/announce.dm
  code/controllers/subsystem/evacuation.dm
  code/controllers/subsystem/mapping.dm
  code/datums/emergency_calls/emergency_call.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/hvh.dm
  code/datums/gamemodes/infestation.dm
  code/datums/marine_main_ship.dm
  code/game/objects/machinery/computer/communications.dm
  code/game/objects/machinery/self_destruct.dm
  code/game/objects/structures/orbital_cannon.dm
  code/modules/admin/fun_verbs.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/screen_alert/command_alert.dm
  code/modules/shuttle/marine_dropship.dm
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
Labels: Code Improvement, Feature, Administration, UI

#15054 Human v Human melee tweaks and fixes
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/mob_grab.dm
Labels: Balance, Fix

#15048 All AMR ammo costs the same.
  code/modules/reqs/supplypacks.dm
Labels: Balance

#15047 Adds MLRS Incendiary and Cloak rockets
  code/game/objects/machinery/mortar.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/reqs/supplypacks.dm
  icons/Marine/mortar.dmi
Labels: Sprites, Feature

#15050 Arachne Medbay Disposals Fix
  _maps/map_files/Arachne/TGS_Arachne.dmm
Labels: Fix, Map Edit

#15043 Xeno Alamo TGUI
  code/modules/shuttle/marine_dropship.dm
  code/modules/tgui/states/alamo.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/MarineDropship.jsx
Labels: Refactor, UI

#15045 Reqtorio Expansion V 1.4
  code/modules/factory/howtopaper.dm
  code/modules/factory/parts.dm
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature, Grammar and Formatting

#15049 King summon interruptible
  code/modules/admin/topic.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Administration

#15053 Rename razorburn_smol to razorburn_small
  code/__DEFINES/loadout.dm
  code/datums/quick_load_beginners.dm
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/factory/parts.dm
  code/modules/projectiles/guns/grenade_launchers.dm
Labels: Code Improvement

#15035 Reorganizes gun64.dmi and gun.dmi into folders and smaller files.
  code/game/objects/items/weapons/twohanded.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/plasma.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/guns/specialist.dm
  icons/Marine/gun64.dmi
  icons/Marine/spear.dmi
  icons/obj/items/gun.dmi
  icons/obj/items/guns/energy.dmi
  icons/obj/items/guns/energy64.dmi
  icons/obj/items/guns/machineguns.dmi
  icons/obj/items/guns/machineguns64.dmi
  icons/obj/items/guns/marksman.dmi
  icons/obj/items/guns/marksman64.dmi
  icons/obj/items/guns/pistols.dmi
  icons/obj/items/guns/pistols64.dmi
  icons/obj/items/guns/plasma64.dmi
  icons/obj/items/guns/rifles.dmi
  icons/obj/items/guns/rifles64.dmi
  icons/obj/items/guns/shotguns.dmi
  icons/obj/items/guns/shotguns64.dmi
  icons/obj/items/guns/special.dmi
  icons/obj/items/guns/special64.dmi
  icons/obj/items/guns/submachineguns.dmi
  icons/obj/items/guns/submachineguns64.dmi
Labels: Sprites

#15056 Fixes xenos with non-standard wound handling not showing wounds in special states.
  code/modules/mob/living/carbon/xenomorph/castes/baneling/baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
Labels: Fix

#15065 Minor jump tweaks
  code/__DEFINES/layers.dm
  code/datums/components/jump.dm
  code/game/objects/structures/campaign_props.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
Labels: Fix

#15066 Multi tile connect loc
  code/datums/elements/connect_loc.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/machinery/cic_maptable.dm
Labels: Code Improvement

#15070 Sentinel nade is now transparent
  code/game/objects/effects/effect_system/smoke.dm
Labels: Balance

#15069 Xeno respawn timer changes
  code/modules/mob/living/carbon/xenomorph/death.dm
Labels: Balance

#15046 Reqtorio expansion V 1.5
  code/modules/factory/howtopaper.dm
  code/modules/factory/parts.dm
  code/modules/factory/unboxer.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature

#15081 Moves inter-round caches to cache/. Deletes tmp/ between rounds
  .gitignore
  code/controllers/subsystem/server_maint.dm
  code/modules/asset_cache/asset_list.dm
  config/config.txt
Labels: Config Update

#15079 Adds a number of missing items to valhalla
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#15083 Fix martini belt sprite typo
  code/game/objects/items/storage/belt.dm
Labels: Fix

#15060 Fixes all instances of "Bicardine" in the code, plus some redundant code.
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  code/datums/jobs/job/icc.dm
  code/game/objects/effects/spawners/random/food_or_drink.dm
  code/game/objects/effects/spawners/random/misc_item.dm
  code/game/objects/items/reagent_containers/food/snacks.dm
  code/game/objects/items/tools/flame_tools.dm
  code/game/objects/items/trash.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/paperwork/beginner_tutorials.dm
Labels: Map Edit, Grammar and Formatting

#15062 Adds "bullet grenades" and the lasburster grenade
  code/game/objects/items/explosives/grenades/bullet_grenade.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/projectile.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/ammoHUD.dmi
  icons/mob/inhands/weapons/grenades_left.dmi
  icons/mob/inhands/weapons/grenades_right.dmi
  icons/obj/items/grenade.dmi
  icons/obj/items/items_mini.dmi
  icons/obj/items/storage/storage_boxes.dmi
  sound/weapons/burst_phaser2.ogg
  tgmc.dme
Labels: Sprites, Sound, Code Improvement, Feature

#15067 Adds a cooldown to re-resting
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Quality of Life

#15084 Fix martini belt not being clickable
  code/game/objects/items/storage/belt.dm
Labels: Fix

#14975 SMG-45 HP->Squashhead, new sound
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/smgs.dm
  icons/obj/items/ammo.dmi
  icons/obj/items/guns/submachineguns64.dmi
  sound/weapons/guns/fire/skorpevo.ogg
Labels: Sprites, Removal, Sound, Feature

#15097 Campaign autowalance fix
  code/datums/gamemodes/campaign.dm
Labels: Fix

#15098 Fix destroy mission win condition
  code/datums/gamemodes/campaign/missions/destroy_mission.dm
Labels: Fix

#15102 Adds some adjacency sanity to some xeno abilities
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Fix

#15099 Yet more throw fixes
  code/game/atoms/atom_movable.dm
  code/modules/mob/living/living.dm
Labels: Fix

#15087 Fix an exploit with tac sensor being active permanently
  code/game/objects/items/motion_detector.dm
Labels: Fix

#15109 Campaign weapon description updates
  code/datums/gamemodes/campaign/loadout_items/SOM/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/belt.dm
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/back_slot.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm
Labels: Quality of Life

#15072 Adds the M40-AG "Anti Gas" Grenade
  code/__DEFINES/conflict.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/game/objects/items/explosives/grenades/marines.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/ammoHUD.dmi
  icons/mob/inhands/weapons/grenades_left.dmi
  icons/mob/inhands/weapons/grenades_right.dmi
  icons/obj/items/grenade.dmi
  icons/obj/items/items_mini.dmi
  icons/obj/items/storage/storage_boxes.dmi
Labels: Sprites, Feature

#15116 Hopefully fixes Transport Officer icon not showing in orbit menu
  code/_globalvars/lists/flavor_misc.dm
Labels: Fix

#15112 merge xenomorph and human overlay layers together
  code/__DEFINES/conflict.dm
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Code Improvement

#15111 AT mine tweaks
  code/game/objects/items/explosives/mine.dm
Labels: Balance

#15107 Fix job-exclusive loadouts in Valhalla.
  code/__DEFINES/loadout.dm
  code/datums/loadout/loadout_helper.dm
Labels: Fix

#15105 Fixes Martini belt erroring when it is full
  code/__DEFINES/atmospherics.dm
  code/game/objects/items/storage/storage.dm
  code/modules/projectiles/gun_attachables.dm
  icons/obj/clothing/belts.dmi
Labels: Sprites, Fix

#15110 FK-88 buff, and some housecleaning
  code/modules/projectiles/ammo_datums.dm
  code/modules/reqs/supplypacks.dm
Labels: Balance

#15113 Shield code improvements
  code/__DEFINES/combat.dm
  code/datums/components/shield.dm
  code/game/objects/items/weapons/energy.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/twohanded.dm
Labels: Code Improvement, Fix

#15076 Fix xenos not being able to hijack/cap
  code/modules/shuttle/marine_dropship.dm
Labels: Fix, Test Merge Candidate, Requires Testing, UI

#14993 Converts Autoinjectors + Hyposprays into TGUI
  code/__DEFINES/interaction.dm
  code/_onclick/item_attack.dm
  code/game/objects/items/reagent_containers/hypospray.dm
  code/game/objects/items/reagent_containers/reagent_container.dm
  tgui/packages/tgui/interfaces/Hypospray.tsx
Labels: Refactor, Test Merge Candidate, UI

#15118 Fix req stats formatting
  code/datums/gamemodes/_game_mode.dm
Labels: Fix

#15119 Campaign light armor prereq fixes
  code/datums/gamemodes/campaign/loadout_items/SOM/suit_storage.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit_storage.dm
Labels: Fix

#15121 Fix sanity fix
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Fix

#15104 Removes Duplicate Bomb Placements on Arachne
  _maps/map_files/Arachne/TGS_Arachne.dmm
Labels: Removal, Fix, Map Edit

#15082 Gives ice colony 2100 QB from 1600
  _maps/ice_colony_v2.json
Labels: Balance, Map Edit

#15101 Preweeds Gelida IV and adds a tunnel
  _maps/map_files/gelida_iv/gelida_iv.dmm
Labels: Balance, Map Edit

#15092 External reinforced walls for magmoor lz1 buildings
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
Labels: Balance, Map Edit

#15127 The ship AI can no longer hijack/capture the Alamo
  code/modules/shuttle/marine_dropship.dm
  tgui/packages/tgui/interfaces/MarineDropship.jsx
Labels: Fix, UI

#15124 Xeno spit is unstaggerable
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance

#15052 Even more Behemoth balancing and fixes
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
Labels: Code Improvement, Balance, Fix

#15059 Increases BR QB to 2300 from 1800
  _maps/bigred_v2.json
Labels: Balance, Map Edit, Test Merge Candidate

#15096 Make Engineer Skill Affect Groundside Gens Repair Time
  code/modules/power/groundmap_geothermal.dm
Labels: Balance

#15120 Removes the first aid kit from medic/SL vendor and medic spawn
  code/__DEFINES/loadout.dm
Labels: Removal

#15129 client/New() actually deals with the nulls in the global client list instead of letting them stay
  code/modules/client/client_procs.dm
Labels: Fix

#15130 Fixes custom squad tablets
  code/game/objects/items/devices/tablets.dm
Labels: Fix

#15131 Fix Main console not being able to overwatch custom squads
  code/game/objects/machinery/overwatch.dm
Labels: Fix

#15132 Fix getting headsets while in a custom squad
  code/game/objects/items/radio/headset.dm
  icons/obj/items/radio.dmi
Labels: Sprites, Fix

#15133 Fixes non-custom squad members being unable to talk on custom squad comms
  code/datums/jobs/squads.dm
Labels: Fix

#15042 Interactive emote fixes
  code/_onclick/click.dm
  code/_onclick/hud/interactive_emotes.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/xenoattacks.dm
Labels: Stale, Fix

#15123 Hunter Buff
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
Labels: Balance

#15090 Removes and moves Ice Colony phoron miners
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
Labels: Removal, Balance, Map Edit

#15150 Stamina skill fix
  code/__DEFINES/skills.dm
Labels: Fix

#15149 Perk item upgrade fix
  code/datums/gamemodes/campaign/individual_stats.dm
  code/datums/gamemodes/campaign/outfit_holder.dm
Labels: Fix

#15125 More Xeno abilities useable while resting.
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
Labels: Balance

#14942 Warrior changes - minor reworks and rebalancing
  code/__DEFINES/action.dm
  code/__DEFINES/actions.dm
  code/__DEFINES/mobs.dm
  code/_globalvars/bitfields.dm
  code/datums/actions/ability_actions.dm
  code/datums/actions/xeno_action.dm
  code/game/atoms/atom_movable.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  icons/Xeno/actions.dmi
  icons/effects/64x64.dmi
  icons/effects/96x96.dmi
  icons/effects/effects.dmi
Labels: Sprites

#15153 reinforced wall change
  code/game/turfs/walls/r_wall.dm
Labels: Balance, Test Merge Candidate

#15089 Directional attacks 2, probably better implementation edition
  code/__DEFINES/preferences.dm
  code/_globalvars/bitfields.dm
  code/_onclick/click.dm
  code/datums/elements/directional_attack.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/living.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Feature, Test Merge Candidate, UI

#15164 end of mission tele fix
  code/datums/gamemodes/campaign/faction_stats.dm
Labels: Fix

#15165 ASAT desc fix
  code/datums/gamemodes/campaign/missions/asat_capture.dm
Labels: Fix

#15163 Interactive emotes converted to using a keybinding
  code/__DEFINES/dcs/signals.dm
  code/_onclick/click.dm
  code/_onclick/hud/interactive_emotes.dm
  code/datums/keybinding/mob.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Code Improvement

#15152 Adds message for recipient when a ticket is (un)marked, closed, or tiered.
  code/modules/admin/verbs/adminhelp.dm
Labels: Administration

#15143 Fix robotic cradle sprite
  code/game/objects/machinery/robotic_cradle.dm
Labels: Fix

#15135 Adds HEFA grenades
  code/game/objects/items/explosives/grenades/bullet_grenade.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/reqs/supplypacks.dm
  icons/mob/inhands/weapons/grenades_left.dmi
  icons/mob/inhands/weapons/grenades_right.dmi
  icons/obj/items/grenade.dmi
  icons/obj/items/items_mini.dmi
  icons/obj/items/storage/storage_boxes.dmi
Labels: Sprites, Balance, Feature

#15167 Xeno plasma code optimisation and bug fix
  code/game/data_huds.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_health_procs.dm
Labels: Code Improvement, Fix, Quality of Life

#15085 Conveyor code improvement
  code/modules/recycling/conveyor2.dm
  icons/obj/recycling.dmi
Labels: Sprites, Code Improvement

#15173 Adds barricade mapping helpers
  code/modules/mapping/mapping_helpers.dm
  icons/effects/mapping_helpers.dmi
Labels: Sprites, Feature

#15161 ERT Shuttles Have Plasteel Cades By Their Doors
  _maps/shuttles/distress.dmm
  _maps/shuttles/distress_pmc.dmm
  _maps/shuttles/distress_ufo.dmm
  _maps/shuttles/distress_upp.dmm
Labels: Balance, Map Edit

#15148 Daedalus Changes (#2)
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/snow.dm
Labels: Balance, Fix, Map Edit

#15178 Minor mech iff code improvement
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Code Improvement

#15190 Larva fix
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix, In Game Exploit

#15185 Campaign credit tweaks
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/individual_stats.dm
Labels: Balance

#15182 fix plasma hud sticking on death
  code/modules/mob/living/carbon/xenomorph/death.dm
Labels: Fix

#15184 Autocannon wall true damage buff
  code/modules/projectiles/ammo_datums.dm
Labels: Balance

#15180 Replaces some unneeded cases of `span_boldannounce` to `span_danger`.
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/datums/weather/weather_types/sand_storm.dm
  code/datums/weather/weather_types/snow_storm.dm
  code/modules/reagents/reagents.dm
Labels: Code Improvement

#15174 Changes Tadpole's Med Dispenser Layer
  code/game/objects/machinery/vending/vending_types.dm
Labels: Quality of Life

#15172 Remove melee embed chance
  code/modules/mob/living/carbon/human/human_defense.dm
Labels: Balance

#15177 AI VOX announcement
  code/__HELPERS/announce.dm
  code/modules/mob/living/silicon/ai/say.dm
Labels: Feature

#15188 More perk tweaks
  code/__DEFINES/colors.dm
  code/datums/gamemodes/campaign/perks.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/mob/living/carbon/shock.dm
Labels: Balance

#15198 Fixes larva spawns probably
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#15170 Boiler Root Removal
  code/__DEFINES/actions.dm
  code/__DEFINES/dcs/signals.dm
  code/_globalvars/bitfields.dm
  code/datums/actions/xeno_action.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
Labels: Balance

#15144 Sunder multiplier
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance

#15166 Adds a accuracy malus to Puppeteer and Widow minions
  code/__DEFINES/combat.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/castedatum_spiderling.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/xenoaccuracy.dm
Labels: Balance

#15195 [NO GBP] Observers and AI itself can read VOX announcement too
  code/modules/mob/living/silicon/ai/say.dm
Labels: Code Improvement, GBP: No Update

#15201 Larva fix for real
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Fix

#15208 Conveyor fix
  code/modules/recycling/conveyor2.dm
Labels: Fix

#15207 add emp signal
  code/__DEFINES/dcs/signals.dm
  code/game/atoms/_atom.dm
Labels: Code Improvement

#15206 Fixes landmark resin walls
  code/datums/gamemodes/infestation.dm
Labels: Fix

#15199 Portrait additions
  code/datums/gamemodes/campaign/campaign_assets.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/campaign/rewards/allies.dm
  code/datums/gamemodes/campaign/rewards/equipment.dm
  code/modules/screen_alert/misc_alert.dm
  icons/UI_Icons/screen_alert_images.dmi
Labels: Sprites

#15204 Fixes tactical reserve asset
  code/datums/gamemodes/campaign/rewards/reserves.dm
Labels: Fix

#15203 Fix sectoid gun sprite
  code/modules/projectiles/guns/rifles.dm
  icons/obj/items/guns/energy.dmi
  icons/obj/items/guns/energy64.dmi
  icons/obj/items/guns/machineguns.dmi
  icons/obj/items/guns/machineguns64.dmi
  icons/obj/items/guns/marksman.dmi
  icons/obj/items/guns/marksman64.dmi
  icons/obj/items/guns/pistols.dmi
  icons/obj/items/guns/pistols64.dmi
  icons/obj/items/guns/plasma64.dmi
  icons/obj/items/guns/rifles.dmi
  icons/obj/items/guns/rifles64.dmi
  icons/obj/items/guns/shotguns.dmi
  icons/obj/items/guns/shotguns64.dmi
  icons/obj/items/guns/special.dmi
  icons/obj/items/guns/special64.dmi
  icons/obj/items/guns/submachineguns.dmi
  icons/obj/items/guns/submachineguns64.dmi
Labels: Sprites, Fix
