Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2025-04, with the labels that each got.

#17444 Acid cost affected by dissolvability, cast delay buffed against flares
  code/game/objects/items/explosives/grenades/flares.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Balance

#17300 Xeno Template Building
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/nymph/castedatum_nymph.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/patterns.dm
  icons/Xeno/patterns.dmi
  tgmc.dme
Labels: Feature, Test Merge Candidate

#17590 Melting fire fixes/walance
  code/modules/projectiles/guns/_shared_ammo_objects.dm
Labels: Balance, Fix

#17582 Mech repairpacks make you vulnerable while using them
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
  code/modules/vehicles/mecha/mecha_actions.dm
Labels: Balance

#17583 Spatial grid update
  code/__DEFINES/spatial_gridmap.dm
  code/__HELPERS/_lists.dm
  code/controllers/subsystem/spatial_gridmap.dm
  code/game/atoms/atom_movable.dm
  code/modules/mob/login.dm
  code/modules/spatial_grid/cell_tracker.dm
  tgmc.dme
Labels: Refactor, Fix

#17584 Fix remaining Zs that should set baseturfs (last pr I swear)
  _maps/arachne.json
  _maps/combat_patrol_base.json
  _maps/debugdalus.json
  _maps/iteron.json
  _maps/multiz_debug.json
  _maps/pillar_of_spring.json
  _maps/sulaco.json
  code/__DEFINES/maps.dm
Labels: Fix, Map Edit

#17585 Fix warped invis-emissive interactions
  code/__DEFINES/dcs/signals/signals.dm
  code/__HELPERS/filters.dm
  code/game/atoms/atom_appearance.dm
  code/modules/vehicles/mecha/mecha_actions.dm
Labels: Fix

#17588 Fixes mech being diagonal (again)
  code/game/atoms/atom_movable.dm
  code/modules/vehicles/mecha/mecha_movement.dm
Labels: Fix

#17589 Mech relimb slashes will relay to torso when limb is destroyed
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Labels: Fix

#17565 Som tank interior layering fix
  code/datums/interior/interior_tank.dm
  code/modules/vehicles/armored/interiors/ammo_rack.dm
Labels: Fix

#17566 Parallax performance & visual improvements
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/sight.dm
  code/_onclick/hud/parallax.dm
  code/_onclick/hud/parallax/parallax.dm
  code/_onclick/hud/parallax/random_layer.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/controllers/subsystem/parallax.dm
  code/game/atoms/_atom.dm
  code/game/objects/items/devices/minimap_tablet.dm
  code/game/objects/machinery/cic_maptable.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/living/silicon/ai/multicam.dm
  code/modules/vehicles/__vehicle.dm
  code/modules/vehicles/mecha/_mecha.dm
  tgmc.dme
Labels: Refactor

#17572 Fixes directionalburst(canister) hitting solid objects if it spawns inside them (tank hitbox)
  code/modules/projectiles/ammo_datums.dm
Labels: Fix

#17574 Crash always has at least two xenos
  code/datums/gamemodes/crash.dm
Labels: Balance

#17593 Fixes toggle seethrough offsetting your sprite on 516
  code/datums/components/seethrough_mob.dm
Labels: Fix

#17594 fix 516 tgui say focusing
  tgui/packages/tgui-say/516/TguiSay.tsx
  tgui/packages/tgui-say/516/helpers.ts
  tgui/packages/tgui-say/516/styles/main.scss
Labels: Fix, UI

#17595 mech/mobs/doors emissive fix
  code/game/objects/machinery/doors/door.dm
  code/modules/mob/living/carbon/carbon_defines.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Labels: Fix

#17596 Fixes being able to magdump mech rockets
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Fix

#17597 stub new mouse buttons
  code/__DEFINES/_click.dm
  code/_onclick/click.dm
Labels: Fix

#17598 Fix backhand passing wrong blame mob arg
  code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
Labels: Fix

#17600 Conq obliteration multiz fix and it targets vehicles now
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_conqueror.dm
Labels: Balance, Fix

#17601 More tgui bumping
  code/controllers/configuration/entries/general.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui/tgui_window.dm
  config/config.txt
  tgui/packages/tgui-panel/index.tsx
  tgui/packages/tgui/App.tsx
  tgui/packages/tgui/Icons.tsx
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/drag.ts
  tgui/packages/tgui/icons.ts
  tgui/packages/tgui/index.tsx
  tgui/packages/tgui/layouts/TitleBar.tsx
  tgui/packages/tgui/layouts/Window.tsx
  tgui/packages/tgui/renderer.ts
  tgui/packages/tgui/routes.tsx
  tgui/packages/tgui/styles/layouts/TitleBar.scss
  tgui/packages/tgui/styles/layouts/Window.scss
  tools/build/build.js
Labels: Config Update, Code Improvement

#17602 Change client version warnings to be config like tg
  code/controllers/configuration/entries/general.dm
  code/modules/client/client_procs.dm
  config/config.txt
Labels: Config Update

#17530 Multiz minimap support
  code/controllers/subsystem/minimap/minimap_action_subtypes.dm
  code/controllers/subsystem/minimap/minimaps.dm
  code/game/objects/machinery/cic_maptable.dm
  tgmc.dme
Labels: Feature

#17550 Walking on top of doors on the above z doesnt make you fall
  code/_globalvars/bitfields.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/doors/door.dm
  code/game/objects/machinery/doors/firedoor.dm
Labels: Fix

#17603 Respawn time on crash is now 15 minutes
  code/datums/gamemodes/crash.dm
Labels: Balance

#17459 LTB Canister Ricochet and Rework
  code/modules/projectiles/ammo_types/tx54_ammo.dm
Labels: Balance

#17599 Screech_act refactor
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph_defense.dm
  code/modules/mob/living/living_defense.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/sealed.dm
Labels: Refactor, Fix

#17607 Improves the mech builder UI yet again
  tgui/packages/tgui/interfaces/MechVendor/MechAssembly.tsx
  tgui/packages/tgui/interfaces/MechVendor/MechWeapons.tsx
  tgui/packages/tgui/interfaces/MechVendor/index.tsx
Labels: Fix, UI, Quality of Life

#17606 Fixes mech and tank not handling windups correctly
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Fix

#17604 Mech dash no longer lets you go over things
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Labels: Balance

#17605 Fix mech boosting weapon overlays not updating
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_core.dm
Labels: Fix

#17618 Adds ping display to Who verb
  code/game/verbs/who.dm
Labels: Feature

#17627 Adds mech shared cooldown weapon groups
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/mecha.dm
  code/modules/vehicles/mecha/equipment/mecha_equipment.dm
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  code/modules/vehicles/mecha/mecha_actions.dm
Labels: Balance, Fix

#17626 Viewing a players playtime is now R_ADMIN and R_MENTOR
  code/modules/admin/topic.dm
Labels: Administration

#17624 Admin check hive status works again
  code/modules/admin/fun_verbs.dm
Labels: Fix

#17623 Fix admin announcement only allowing one character
  code/modules/admin/fun_verbs.dm
Labels: Fix

#17621 Vehicle zmovement fixes
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/sealed.dm
Labels: Fix

#17620 Fixes tesla rifle not working
  code/datums/beam.dm
Labels: Fix

#17610 Sass cleanup, fix scrolling breaking for the chat sometimes, tguicore update
  tgui/packages/tgui-bench/package.json
  tgui/packages/tgui-panel/chat/renderer.jsx
  tgui/packages/tgui-panel/package.json
  tgui/packages/tgui-panel/panelFocus.ts
  tgui/packages/tgui-say/package.json
  tgui/packages/tgui/package.json
  tgui/packages/tgui/styles/functions.scss
  tgui/packages/tgui/styles/interfaces/Mecha.scss
  tgui/packages/tgui/styles/interfaces/NuclearBomb.scss
  tgui/packages/tgui/styles/layouts/Window.scss
  tgui/yarn.lock
Labels: Fix, UI

#17613 minimap hotfix?
  code/controllers/subsystem/minimap/minimaps.dm
Labels: Fix

#17614 Baloon alert optimization
  code/modules/balloon_alert/balloon_alert.dm
Labels: Code Improvement

#17630 Spatial agents can now speak xeno
  code/datums/jobs/job/other.dm
  code/modules/admin/debug_verbs.dm
Labels: Quality of Life

#17631 Deshittifys looking P2
  code/datums/keybinding/living.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
Labels: Refactor

#17632 Winget sdql fix
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
Labels: Administration

#17633 Dont crash the chat if we fail to play an admin sound
  tgui/packages/tgui-panel/audio/player.tsx
Labels: Fix, UI

#17635 Fix radio colors
  tgui/packages/tgui-say/515/constants.ts
  tgui/packages/tgui-say/516/constants.ts
Labels: Fix, UI

#17634 DPI fixes for 516
  code/datums/browser.dm
  code/modules/admin/panels/permission_panel.dm
  code/modules/admin/view_variables/view_variables.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/mob.dm
  code/modules/tgui/tgui.dm
  code/modules/tgui_input/say_modal/modal.dm
  code/modules/tgui_panel/external.dm
  interface/skin.dmf
  tgui/packages/tgui-panel/index.tsx
  tgui/packages/tgui-panel/settings/SettingsGeneral.tsx
  tgui/packages/tgui-panel/settings/middleware.ts
  tgui/packages/tgui-panel/settings/scaling.ts
  tgui/packages/tgui-panel/themes.ts
  tgui/packages/tgui-say/515/TguiSay.tsx
  tgui/packages/tgui-say/516/TguiSay.tsx
  tgui/packages/tgui-say/516/helpers.ts
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/drag.ts
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
  tgui/packages/tgui/layouts/Window.tsx
  tgui/packages/tgui/styles/functions.scss
  tgui/packages/tgui/styles/layouts/TitleBar.scss
  tgui/packages/tgui/styles/main.scss
Labels: Fix, Quality of Life

#17619 Removes second gen on Daedalus
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
Labels: Removal, Map Edit

#17644 Added check for attempt_restock() feedback
  code/game/objects/machinery/vending/vending.dm
Labels: Fix

#17650 Divides all mech flamer ammo numbers by 5
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
Labels: Balance

#17475 Xenos can no longer pull resin cocoons
  code/game/objects/items/cocoon.dm
Labels: Balance

#17560 Makes movement canonical
  code/__DEFINES/movement_info.dm
  code/__DEFINES/traits.dm
  code/datums/interior/_interior.dm
  code/game/atoms/atom_movable.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/movement_order_sanity.dm
  tgmc.dme
Labels: Stale, Refactor

#17428 Special walls are now free and part of secrete resin
  code/__DEFINES/turfs.dm
  code/__DEFINES/xeno.dm
  code/__HELPERS/game.dm
  code/game/turfs/walls/resin.dm
  code/game/turfs/walls/walls.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Feature

#17548 Fixes welding inhand
  code/modules/clothing/head/misc_special.dm
  icons/mob/inhands/clothing/hats_left.dmi
  icons/mob/inhands/clothing/hats_right.dmi
  icons/mob/inhands/clothing/masks_left.dmi
  icons/mob/inhands/clothing/masks_right.dmi
Labels: Code Improvement, Refactor, Fix

#17647 Unrestricts overwatch tablets.
  code/game/objects/items/devices/tablets.dm
Labels: Removal

#17656 PDA Audio Logs
  code/__DEFINES/cooldowns.dm
  code/game/objects/items/pda.dm
  icons/obj/items/pda.dmi
  tgmc.dme
Labels: Feature

#17648 Moved SAA speedloaders from base type to subtype
  code/controllers/subsystem/persistence/_persistence.dm
  code/game/objects/items/storage/holsters.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/magazines/revolvers.dm
  code/modules/reqs/supplypacks/imports_packs.dm
Labels: Fix

#17651 If larva queue is more than 2 people it will show how long it is in the tgui "are you sure" popup when you try to observe
  code/modules/mob/new_player/new_player.dm
Labels: Quality of Life

#17653 Cap cloak gun cooldown CD after uncloaking to 1 second, and treat the fire cooldown as half of it's reality
  code/modules/vehicles/mecha/mecha_actions.dm
Labels: Balance

#17652 Stat panel is only scrollable if needed
  html/statbrowser.css
Labels: Quality of Life

#17649 Permanently reenables mechs
  code/datums/jobs/job/shipside.dm
Labels: Balance, Feature, Quality of Life

#17660 Fix global narrate only allowing one character
  code/modules/admin/fun_verbs.dm
Labels: Fix

#17661 Fixes applying corruption to bluespace gen
  code/modules/power/groundmap_geothermal.dm
Labels: Fix

#17665 Increases the Warrior's wall impact and punch damage
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
Labels: Balance

#17668 Changed name/desc of SAA R-44 speedloaders
  code/modules/projectiles/magazines/revolvers.dm
Labels: Fix

#17669 Fixes mech spawning
  code/datums/jobs/job/shipside.dm
Labels: Fix

#17673 Light medical rig can now hold hyposprays
  code/datums/storage/subtypes/belt.dm
Labels: Balance

#17662 Bump attacking is now a game preference rather than an action
  code/datums/actions/bump_attack_toggle.dm
  code/datums/components/bump_attack.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Code Improvement

#17666 Dangerous weather will now play a screen alert warning
  code/__DEFINES/text.dm
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/datums/weather/weather_types/sand_storm.dm
  code/modules/screen_alert/misc_alert.dm
Labels: Quality of Life

#17667 Pointing in held objects will now actually show what is being pointed at above your head
  code/__DEFINES/mobs.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob.dm
  icons/effects/effects.dmi
Labels: Quality of Life

#17676 Crushers charging mech legs will instead target chest if legs have no hp
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Balance

#17677 Fix mech/tank being able to use equipment while stunned
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Fix

#17678 Fix mechs being destroyed while not facing south and without an occupant making overlays layer wrong
  code/modules/vehicles/mecha/combat/greyscale/greyscale_core.dm
Labels: Fix

#17680 Fixes multiz preference not looping properly + elaborates what it does better
  code/modules/client/preferences_ui.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Fix, Quality of Life

#17682 Fixes random smoothing define being set wrong
  code/__DEFINES/icon_smoothing.dm
Labels: Fix

#17657 VV update
  code/__DEFINES/bitfields.dm
  code/_globalvars/bitfields.dm
  code/modules/admin/view_variables/debug_variable_appearance.dm
  code/modules/admin/view_variables/debug_variables.dm
  code/modules/admin/view_variables/view_variables.dm
  tgmc.dme
Labels: Code Improvement, Administration

#17670 Nerfs Conqueror's Endurance ability
  code/game/objects/items/weapons/twohanded.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_conqueror.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/vehicles/__vehicle.dm
Labels: Balance

#17674 Small Sulaco + Arachne fixes
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Fix, Map Edit

#17655 Use pixel z for falling from sky effects
  code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
  code/modules/xenomorph/maw.dm
Labels: Code Improvement

#17691 Adds mapload to every Initialize (again) and converts some New()s to Initialize()
  code/_onclick/hud/interactive_emotes.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/game/objects/items/firesupport_binoculars.dm
  code/game/objects/items/trash.dm
  code/game/objects/machinery/doors/airlock.dm
  code/game/objects/machinery/floodlight.dm
  code/game/objects/machinery/portable_reagent_tank.dm
  code/game/objects/structures/rappel_system.dm
  code/game/turfs/closed.dm
  code/game/turfs/plating.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/ai/presets/xeno_presets.dm
  code/modules/atmospherics/machinery/pipes/heat_exchange/manifold4w.dm
  code/modules/atmospherics/machinery/pipes/layermanifold.dm
  code/modules/buildmode/buttons.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/shuttle/marine_dropship.dm
Labels: Code Improvement

#17695 You can no longer put tanks, apcs and mechs into closets
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Fix

#17694 Droppods will no longer randomly appear near the LZ sometimes
  code/game/objects/structures/droppod.dm
  code/modules/mapping/space_management/space_reservation.dm
Labels: Fix

#17696 Mech builder deployment improvements
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
  tgui/packages/tgui/interfaces/MechVendor/MechAssembly.tsx
  tgui/packages/tgui/interfaces/MechVendor/data.ts
Labels: Quality of Life

#17700 Round end screen fix
  code/__DEFINES/client.dm
  code/datums/browser.dm
  tgmc.dme
Labels: Fix

#17708 enabling nuke sends message to admins
  code/game/objects/machinery/nuclearbomb.dm
Labels: Administration

#17709 Set xeno buffs shows current autoballance
  code/modules/admin/admin_verbs.dm
Labels: Administration

#17705 Request music verb
  code/__DEFINES/admin.dm
  code/__DEFINES/cooldowns.dm
  code/__DEFINES/logging.dm
  code/__HELPERS/logging/game.dm
  code/controllers/configuration/entries/general.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/panels/ban_panel.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/request_internet_sound.dm
  code/modules/logging/categories/log_category_game.dm
  config/config.txt
  tgmc.dme
Labels: Feature

#17704 Stacking debuff adjustment
  code/datums/status_effects/debuffs.dm
  code/modules/projectiles/projectile.dm
Labels: Fix

#17697 Mech has 300 instead of 500 hp as originally intended
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Labels: Balance

#17688 Refactors photographs
  code/__DEFINES/time.dm
  code/__HELPERS/matrices.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/entries/general.dm
  code/game/world.dm
  code/modules/paperwork/photography.dm
  config/config.txt
  icons/blanks/32x32.dmi
  icons/blanks/96x96.dmi
  icons/blanks/blank_title.png
Labels: Refactor, Fix, Administration, Quality of Life

#17478 Fire now falls down Zlevels
  code/modules/projectiles/guns/_shared_ammo_objects.dm
Labels: Fix

#17726 Fixes mentors being able to use admin stuff (request music verb)
  code/modules/admin/verbs/request_internet_sound.dm
Labels: Fix

#17675 Adds mouse over holograms for xeno's place pattern
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_x_act.dm
  code/__DEFINES/icon_smoothing.dm
  code/__DEFINES/xeno.dm
  code/__HELPERS/visual_effects.dm
  code/controllers/subsystem/mouse_entered.dm
  code/datums/actions/ability_actions.dm
  code/game/atoms/mouse_entered.dm
  code/game/objects/effects/misc.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/patterns.dm
  html/changelogs/archive/2025-04.yml
  tgmc.dme
Labels: Feature

#17719 More TAD logging
  code/game/objects/machinery/computer/dropship_picker.dm
Labels: Administration, Logging

#17723 Moves turrets on urbantower tad to the sides
  _maps/shuttles/minidropship_urbantower.dmm
Labels: Balance, Map Edit

#17724 Gives synth soap
  code/game/objects/machinery/vending/new_marine_vendors.dm
Labels: Balance

#17725 Vehicles are no longer capable of phasing accross spacetime
  code/modules/vehicles/cars/car.dm
  code/modules/vehicles/mecha/mecha_movement.dm
Labels: Fix, In Game Exploit

#17698 Add forum link verb
  code/controllers/configuration/entries/general.dm
  code/game/verbs/ooc.dm
  config/config.txt
Labels: Config Update, Feature

#17728 Tiering mhelp to ahelp gives admins a noise
  code/modules/admin/verbs/adminhelp.dm
Labels: Administration

#17711 Buildmode modernization
  code/__DEFINES/misc.dm
  code/__DEFINES/span.dm
  code/__HELPERS/duplicating.dm
  code/__HELPERS/qdel.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/misc.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/centcom_podlauncher.dm
  code/modules/buildmode/BUILDMODE.md
  code/modules/buildmode/bm_mode.dm
  code/modules/buildmode/buildmode.dm
  code/modules/buildmode/buttons.dm
  code/modules/buildmode/effects/line.dm
  code/modules/buildmode/submodes/advanced.dm
  code/modules/buildmode/submodes/area_edit.dm
  code/modules/buildmode/submodes/basic.dm
  code/modules/buildmode/submodes/boom.dm
  code/modules/buildmode/submodes/copy.dm
  code/modules/buildmode/submodes/delete.dm
  code/modules/buildmode/submodes/fill.dm
  code/modules/buildmode/submodes/loadout.dm
  code/modules/buildmode/submodes/smite.dm
  code/modules/buildmode/submodes/throwing.dm
  code/modules/buildmode/submodes/variable_edit.dm
  code/modules/unit_tests/create_and_destroy.dm
  icons/misc/buildmode.dmi
  icons/turf/areas.dmi
  tgmc.dme
Labels: Fix, Feature, Quality of Life

#17578 MedScanner.tsx refactor and faster health analyzers
  code/__DEFINES/mobs.dm
  code/game/objects/items/scanners/health_analyzer.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/organs/limbs.dm
  code/modules/organs/organ_internal.dm
  tgui/packages/tgui/interfaces/MedScanner.tsx
  tgui/packages/tgui/interfaces/MedScanner/MedBoxedTag.tsx
  tgui/packages/tgui/interfaces/MedScanner/MedConditional.tsx
  tgui/packages/tgui/interfaces/MedScanner/MedCounter.tsx
  tgui/packages/tgui/interfaces/MedScanner/MedDamageType.tsx
  tgui/packages/tgui/interfaces/MedScanner/constants.ts
  tgui/packages/tgui/interfaces/MedScanner/data.ts
  tgui/packages/tgui/interfaces/MedScanner/helpers.ts
  tgui/packages/tgui/interfaces/MedScanner/index.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Refactor, Test Merge Candidate, Quality of Life

#17681 Weather now uses overlays instead of setting area icons
  code/datums/weather/weather.dm
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/sand_storm.dm
  code/datums/weather/weather_types/snow_storm.dm
  icons/effects/glow_weather.dmi
Labels: Refactor, Fix, Quality of Life

#17699 Fixes oddities in world/Reboot()
  code/game/world.dm
Labels: Code Improvement, Test Merge Candidate, Quality of Life

#17732 516 is required for compile and tests
  .github/alternate_byond_versions.txt
  .github/max_required_byond_client.txt
  code/__byond_version_compat.dm
  code/_globalvars/bitfields.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/rendering/plane_master_group.dm
  code/_onclick/hud/rendering/render_plate.dm
  code/modules/admin/view_variables/debug_variable_appearance.dm
  dependencies.sh
Labels: Code Improvement, GitHub

#17741 Renames internet sound to internet music
  code/modules/admin/verbs/request_internet_sound.dm
Labels: Grammar and Formatting

#17742 Fix wrong req timers
  code/modules/factory/machines.dm
Labels: Fix

#17690 Admins now see how many lobby players there and and how many are afk
  code/game/verbs/who.dm
Labels: Administration

#17743 Fire alarm brightness fix
  code/game/area/area.dm
Labels: Fix

#17734 mentors can subtle message again
  code/modules/admin/fun_verbs.dm
Labels: Fix

#17693 Look up/down track the thing you're inside
  code/modules/mob/living/living.dm
  code/modules/unit_tests/create_and_destroy.dm
Labels: Fix

#17737 Tesla turret nerfs
  code/game/objects/machinery/tesla_turret.dm
  code/modules/reqs/supplypacks/engineering_packs.dm
Labels: Balance

#17746 Fixes build mode explosion mode
  code/modules/buildmode/submodes/boom.dm
Labels: Fix

#17747 fix sg62 inhands
  icons/mob/inhands/guns/marksman_left_1.dmi
  icons/mob/inhands/guns/marksman_right_1.dmi
Labels: Sprites, Fix

#17750 Fixes the SO cap worn icon
  icons/mob/clothing/headwear/marine_hats.dmi
Labels: Sprites, Fix

#17718 Removes extra martin from sulaco
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Removal, Fix, Map Edit

#17663 Crash T3 Slots Scaling Increased + Hivelord Pop Reduction + Caste Swap Timer Reduction
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/crash.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance

#17752 Dragon Breath only works while awake
  code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
Labels: Fix

#17753 Recasting Dragon Breaths ends it early
  code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
Labels: Quality of Life

#17760 Jellypod landmarks now actually work
  code/game/objects/effects/landmarks/landmarks.dm
Labels: Fix

#17769 Adds gib logging
  code/modules/mob/death.dm
Labels: Administration, Logging

#17770 Clean up of martina shitcode
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  code/modules/mob/living/simple_animal/friendly/cat.dm
Labels: Refactor, Map Edit

#17766 Attack hand alternate on guns no longer toggles safety
  code/modules/projectiles/gun_helpers.dm
Labels: Removal

#17756 Fix Byondui crash
  code/_onclick/hud/rendering/plane_master_group.dm
  code/_onclick/hud/rendering/render_plate.dm
Labels: Fix

#17765 Fix crusher instakilling mechs
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Fix

#17758 Reset button for adjustable pane splitters
  tgui/packages/tgui-panel/settings/SettingsGeneral.tsx
  tgui/packages/tgui-panel/settings/scaling.ts
Labels: UI, Quality of Life

#17755 Guide commment remove will no longer steal edits
  tools/pull_request_hooks/removeGuideComments.js
Labels: Removal, Tools

#17754 Status bar dpi scaling
  interface/skin.dmf
  tgui/packages/tgui-panel/settings/scaling.ts
Labels: Quality of Life

#17731 Adds rhe mech overboost module
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/keybinding/mecha.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
  code/modules/vehicles/mecha/mecha_actions.dm
  sound/mecha/overboost_chargeup.ogg
Labels: Feature

#17776 Tiering the ticket Unmarks it
  code/modules/admin/verbs/adminhelp.dm
Labels: Administration

#17702 Ammoboxparity3
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/explosives/grenades/sticky_grenades.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/structures/crates_lockers/largecrate_supplies.dm
  code/modules/projectiles/magazines/flamer.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/pistols.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/projectiles/magazines/shotguns.dm
  code/modules/projectiles/magazines/smgs.dm
  icons/obj/items/items_mini.dmi
  icons/obj/items/storage/storage_boxes.dmi
Labels: Fix

#17780 Fix guide comments remover
  tools/pull_request_hooks/removeGuideComments.js
Labels: Removal, Tools

#17778 Fix AI goal nodes
  code/controllers/subsystem/advanced_pathfinding.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
  code/modules/ai/ai_behaviors/xeno/puppet.dm
  code/modules/ai/ai_behaviors/xeno/xeno.dm
  code/modules/ai/ai_node.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
Labels: Fix

#17791 Adds soap to loadouts
  code/__DEFINES/loadout.dm
Labels: Fix
