Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2025-01, with the labels that each got.

#16848 Shield bash
  code/__DEFINES/combat.dm
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/keybinding/weapons.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/swords.dm
  code/game/objects/items/weapons/twohanded.dm
  icons/mob/actions.dmi
Labels: Sprites, Feature

#16850 Fixes ICC Leader and adds gear to ICC loadouts
  code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
  code/datums/jobs/job/icc.dm
Labels: Balance, Stale, Fix

#16504 Metnal Mining Operation (REVIVAL)
  _maps/_basemap.dm
  _maps/map_files/Metnal_Operation/Metnal_Operation.dmm
  _maps/metnal.json
  code/__DEFINES/atmospherics.dm
  code/game/area/metnal.dm
  code/game/objects/metnal_objects.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  config/maps.txt
  icons/obj/metnal_objects.dmi
  icons/obj/smooth_objects/prison_window_frame.dmi
  tgmc.dme
Labels: Sprites, Config Update, Map Edit, Feature

#16863 Prison Station: Freedom
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/crash.dm
Labels: Map Edit, Feature

#16860 For real real radio TTS fix (real edition)
  code/controllers/subsystem/tts.dm
  code/game/objects/machinery/telecomms/broadcasting.dm
Labels: Fix

#16854 Merges SL and FC prep rooms
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit, Feature

#16861 Adds an off-by-default config option to optionally disable TTS audio on whispered speech
  code/controllers/configuration/entries/game_options.dm
  code/game/say.dm
  code/modules/mob/living/say.dm
  config/config.txt
Labels: Config Update

#16873 Pillar of Spring maint fix
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#16877 Campaign: Esword secondary fix
  code/datums/gamemodes/campaign/loadout_items/SOM/secondaries.dm
Labels: Fix

#16883 Fix OD lint compile
  .github/workflows/ci_suite.yml
Labels: GitHub

#16869 New tank secondaries: TOW and Micromissile pod
  code/__DEFINES/calibers.dm
  code/datums/storage/subtypes/tank.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/armored_weapons.dm
  icons/obj/armored/3x3/tank_gun.dmi
  icons/obj/armored/3x3/tank_interior.dmi
  icons/obj/armored/hardpoint_modules.dmi
  icons/obj/items/ammo/tank.dmi
Labels: Feature

#16866 Announcement/overwatch/hivemind/hive message TTS
  code/__DEFINES/tts.dm
  code/controllers/subsystem/tts.dm
  code/datums/jobs/squads.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/telecomms/broadcasting.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/say.dm
  code/modules/mob/living/say.dm
  code/modules/screen_alert/command_alert.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Feature, UI

#16879 Fixes map errors on Pillar of Spring + map table adjustment
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Removal, Fix, Map Edit

#16876 Campaign map fixes
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/Campaign maps/som_base/sombase.dmm
  _maps/map_files/Campaign maps/tgmc_raid_base/tgmc_raiding_base.dmm
Labels: Fix, Map Edit

#16874 Adds a few tunnel sites to prison station
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
Labels: Balance, Map Edit

#16880 Flings now respect move_force
  code/modules/mob/living/carbon/xenomorph/castes/crusher/abilities_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
Labels: Balance, Fix

#16664 Adds bloodthirster Rav strain
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  icons/Xeno/64x64_Xeno_overlays.dmi
  icons/Xeno/actions/ravager.dmi
  icons/Xeno/castes/ravager.dmi
Labels: Sprites, Feature

#16725 Adds new marine race: Prototype Supersoldier
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/species.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/datums/actions/species_actions/prototype_supersoldier_action.dm
  code/datums/components/stamina_behavior.dm
  code/datums/jobs/job/terragov.dm
  code/datums/keybinding/human.dm
  code/datums/namepool.dm
  code/datums/status_effects/gun_skill.dm
  code/game/objects/effects/decals/rune.dm
  code/game/objects/effects/misc.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/tools/cleaning_tools.dm
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/human_status_procs.dm
  code/modules/mob/living/carbon/human/species_types/humans.dm
  code/modules/mob/living/carbon/human/species_types/prototype_supersoldier.dm
  code/modules/mob/living/carbon/human/species_types/synthetics.dm
  code/modules/mob/living/carbon/human/species_types/vatborns.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/actions.dmi
  strings/names/female_synth.txt
  strings/names/prototype_supersoldier.txt
  tgmc.dme
  tgui/packages/tgui/interfaces/SupersoldierStims.tsx
Labels: Sprites, Feature, UI

#16888 Homing tank secondary pod nerf
  code/modules/projectiles/ammo_types/rocket_ammo.dm
Labels: Balance, Test Merge Candidate

#16885 Enable more OD pragmas
  tools/ci/od_lints.dm
Labels: Tools

#16890 Tank Chaingun has IFF again
  code/modules/projectiles/ammo_types/heavy_ammo.dm
Labels: Balance

#16900 Fixes xeno dragging crit humans doing brute damage
  code/modules/mob/living/living_health_procs.dm
Labels: Fix

#16894 decapitalizes full faction announcement titles for consistency
  code/modules/screen_alert/command_alert.dm
Labels: Fix

#16882 Mugshot announcements
  code/datums/components/attachment_handler.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/structures/orbital_cannon.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
  code/modules/screen_alert/_screen_alert.dm
  code/modules/screen_alert/command_alert.dm
  code/modules/screen_alert/misc_alert.dm
  icons/UI_Icons/screen_alert_images.dmi
  icons/effects/alphacolors.dmi
Labels: Sprites, Feature

#16892 Adds Soda Dispenser to Valhalla.
  _maps/map_files/generic/Admin_Level.dmm
Labels: Map Edit, Feature

#16908 Ear removal service
  icons/mob/human_races/r_human.dmi
  icons/mob/human_races/r_moth.dmi
  icons/mob/human_races/r_synthetic.dmi
  icons/mob/human_races/r_vatborn.dmi
  icons/mob/human_races/r_vatgrown.dmi
Labels: Sprites

#16906 Nerf ltaap
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/vehicles/armored/armored_weapons.dm
Labels: Balance

#16907 Nerf micro missiles again
  code/modules/vehicles/armored/armored_weapons.dm
Labels: Balance, Test Merge Candidate

#16910 Forcedropped objects with attachments lose their actions correctly
  code/modules/clothing/modular_armor/attachments.dm
Labels: Fix, In Game Exploit

#16916 New vsd komandir portrait sprite
  icons/UI_Icons/screen_alert_images.dmi
Labels: Sprites

#16913 Fixes wraiths being able to delete people using banish
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
Labels: Fix

#16909 Renames the RR's factory refills to be in line with the single shell purchase options
  code/modules/reqs/supplypacks.dm
Labels: Grammar and Formatting

#16897 V-35 handling nerfs
  code/modules/projectiles/guns/rifles.dm
Labels: Balance

#16843 Adds a new Boiler Strain: Sizzler
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/movespeed_modification.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/ai/presets/xeno_presets.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
  icons/Xeno/actions/boiler.dmi
  icons/Xeno/castes/boiler.dmi
Labels: Sprites, Feature, Test Merge Candidate

#16914 Adding almost all xenomorphs gib animation (very cool!)
  icons/Xeno/castes/beetle.dmi
  icons/Xeno/castes/bull.dmi
  icons/Xeno/castes/carrier.dmi
  icons/Xeno/castes/crusher.dmi
  icons/Xeno/castes/defender.dmi
  icons/Xeno/castes/defiler.dmi
  icons/Xeno/castes/drone.dmi
  icons/Xeno/castes/gorger.dmi
  icons/Xeno/castes/hivelord.dmi
  icons/Xeno/castes/mantis.dmi
  icons/Xeno/castes/nymph.dmi
  icons/Xeno/castes/praetorian.dmi
  icons/Xeno/castes/queen.dmi
  icons/Xeno/castes/ravager.dmi
  icons/Xeno/castes/runner.dmi
  icons/Xeno/castes/scorpion.dmi
  icons/Xeno/castes/sentinel.dmi
  icons/Xeno/castes/shrike.dmi
  icons/Xeno/castes/spitter.dmi
  icons/Xeno/castes/warlock.dmi
  icons/Xeno/castes/warrior.dmi
Labels: Sprites

#16899 Adds Shrapnel drill to HvX
  code/__DEFINES/loadout.dm
Labels: Balance

#16925 fix VV "Jump To"
  code/game/atoms/_atom.dm
Labels: Administration

#16926 fix admin VV "Set Species"
  code/modules/mob/living/carbon/human/human.dm
Labels: Administration

#16921 Crew monitor fix
  code/game/objects/machinery/computer/crew.dm
Labels: Fix

#16924 General psi structure grammar/spelling/wording
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
  code/modules/xenomorph/maw.dm
Labels: Grammar and Formatting

#16893 Makes all Prison Station metal ceilings into glass ceilings (and another PoS fix)
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  code/game/area/prison.dm
Labels: Balance, Fix, Map Edit

#16920 APC can now use all tank secondaries
  code/modules/vehicles/armored/apc.dm
  icons/obj/armored/3x3/apc.dmi
Labels: Sprites, Balance

#16931 Adds .41 AE and squash head ammo packets back to the valhalla and crash venders
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Fix

#16935 Jetpack exploit fix
  code/game/objects/items/jetpack.dm
Labels: Fix, In Game Exploit

#16918 Disables Wraith
  code/_globalvars/lists/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
Labels: Removal

#16936 Adds big tails and twin drills hairstyles
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
Labels: Sprites, Feature

#16944 Fixes being able to tear up empty space
  code/game/turfs/floor.dm
Labels: Fix

#16942 Fix mech explosion being on del
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Labels: Fix

#16940 Minion Maw ammo
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/modules/ai/ai_behaviors/xeno/xeno.dm
  code/modules/xenomorph/maw.dm
  icons/mob/radial.dmi
  sound/effects/thoomp.ogg
Labels: Sprites, Sound, Feature

#16878 Adds loki and thor armor modules
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/loadout.dm
  code/datums/keybinding/human.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/combat_robot.dm
  code/modules/clothing/modular_armor/jaeger.dm
  code/modules/clothing/modular_armor/modular.dm
  code/modules/clothing/modular_armor/style_line.dm
  code/modules/clothing/modular_armor/tdf.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/projectiles/gun_system.dm
  icons/mob/modular/modular_armor_modules.dmi
  sound/items/armorlock.ogg
Labels: Sprites, Sound, Fix, Feature, Test Merge Candidate

#16929 Vali healing changes
  code/datums/components/chem_booster.dm
Labels: Balance, Test Merge Candidate

#16947 Drones can now use (slightly) more abilities while mounted
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/abilities_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
Labels: Balance

#16933 Ports tg Block Movement keybind
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/keybinding/mob.dm
  code/game/atoms/atom_movable.dm
  code/modules/client/client_defines.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/mob/living/living_movement.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/remote_fob/computer.dm
Labels: Quality of Life

#16938 Regular webbing storage fix and adds comments to storage.dm
  code/datums/storage/storage.dm
  code/datums/storage/subtypes/internal.dm
Labels: Removal, Balance

#16943 Fixes dchat runechat only showing for the owner
  code/__HELPERS/mobs.dm
  code/modules/mob/say.dm
Labels: Fix

#16927 Gibbing Particles and Sound
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/silicon/death.dm
  sound/effects/gib.ogg
Labels: Sound, Feature, Test Merge Candidate

#16895 Finish unfinished sentries
  code/__DEFINES/calibers.dm
  code/modules/projectiles/ammo_types/energy_ammo.dm
  code/modules/projectiles/ammo_types/miscellaneous_ammo.dm
  code/modules/projectiles/guns/sentries.dm
  code/modules/projectiles/magazines/sentries.dm
  code/modules/reqs/supplypacks.dm
Labels: Feature, Test Merge Candidate

#16952 Carrier ability pronoun correction + term standardization
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Grammar and Formatting

#16858 moves crash site on research outpost
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
Labels: Removal, Balance, Map Edit

#16956 Crusher nerfs
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
Labels: Balance

#16934 Adds 5 more intel computers to big red + fixes an apc
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/modularmaps/big_red/bigredengineeringvar1.dmm
  _maps/modularmaps/big_red/bigredengineeringvar2.dmm
  _maps/modularmaps/big_red/bigredengineeringvar3.dmm
  _maps/modularmaps/big_red/bigredengineeringvar4.dmm
  _maps/modularmaps/big_red/bigredetavar1.dmm
  _maps/modularmaps/big_red/bigredetavar2.dmm
  _maps/modularmaps/big_red/bigredetavar3.dmm
  _maps/modularmaps/big_red/bigredetavar4.dmm
  _maps/modularmaps/big_red/bigredetavar5.dmm
  _maps/modularmaps/big_red/bigredofficevar1.dmm
  _maps/modularmaps/big_red/bigredofficevar2.dmm
  _maps/modularmaps/big_red/bigredofficevar3.dmm
Labels: Fix, Map Edit, Feature

#16964 Buffs to Sentinel/Retrogade Sentinel stats across the board
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
Labels: Balance

#16965 Block Movement keybind now lets you rotate binoculars and scopes again
  code/modules/mob/living/living_movement.dm
Labels: Fix

#16962 Human bump attacks respect friendly human factions
  code/datums/components/bump_attack.dm
Labels: Fix

#16957 Tank gib godemode check
  code/modules/projectiles/ammo_types/rocket_ammo.dm
Labels: Fix

#16968 fixes Carrier ability pronoun correction + term standardization
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
Labels: Fix, Grammar and Formatting

#16971 Adds bloodthirster to global list of all xeno types
  code/_globalvars/lists/mobs.dm
Labels: Fix

#16954 Requisitions general grammar and stylistic changes
  code/modules/factory/unboxer.dm
  code/modules/projectiles/gun_attachables/rail.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/projectiles/magazines/flamer.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/armored/ammo_magazine.dm
Labels: Grammar and Formatting

#16955 Particle Effects Adjustments
  code/__DEFINES/particles.dm
  code/controllers/subsystem/explosions.dm
  code/datums/elements/debris.dm
  code/game/atoms/_atom.dm
  code/game/objects/effects/temporary_visuals/explosions.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/bookcase.dm
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/mineral_doors.dm
  code/game/objects/structures/rocks.dm
  code/game/objects/structures/supports.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/window.dm
  code/game/shuttle_engines.dm
  code/game/turfs/closed.dm
  code/game/turfs/walls/resin.dm
  code/game/turfs/walls/wall_types.dm
  code/game/turfs/walls/walls.dm
  code/modules/projectiles/ammo_types/shotgun_ammo.dm
  code/modules/projectiles/ammunition.dm
  code/modules/shuttle/marine_dropship.dm
  icons/effects/64x64.dmi
  icons/effects/particles/generic_particles.dmi
Labels: Sprites, Code Improvement, Quality of Life

#16974 Fixes laser sentry IFF
  code/modules/projectiles/guns/sentries.dm
Labels: Fix

#16975 Fixes observer minimap teleporting
  code/controllers/subsystem/minimaps.dm
Labels: Fix

#16988 Adds Marine Rank to ID Card
  code/game/objects/items/cards_ids.dm
Labels: Feature

#16992 Fixes timestamps
  code/__HELPERS/time.dm
Labels: Priority: High, Fix

#16985 Deathmark fixes
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Fix

#16976 Razor entangle changes
  code/__DEFINES/objects.dm
  code/game/objects/structures/razorwire.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
Labels: Balance

#16990 Downgrades the Acid Jaws' build check ceiling level (???)
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Fix

#16941 Mech skill
  code/__DEFINES/skills.dm
  code/datums/skills.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
Labels: Fix

#16901 New tank req weapon: BFG 9500
  code/__DEFINES/calibers.dm
  code/datums/beam.dm
  code/datums/storage/subtypes/tank.dm
  code/modules/projectiles/ammo_types/energy_ammo.dm
  code/modules/reqs/supply.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/armored_weapons.dm
  icons/effects/beam.dmi
  icons/obj/armored/3x3/tank_gun.dmi
  icons/obj/armored/3x3/tank_interior.dmi
  icons/obj/armored/hardpoint_modules.dmi
  icons/obj/items/ammo/tank.dmi
  icons/obj/items/projectiles.dmi
  sound/weapons/guns/fire/tank_bfg.ogg
  sound/weapons/guns/misc/bfg_fly.ogg
Labels: Sprites, Sound, Fix, Feature, Test Merge Candidate, Quality of Life

#16996 A few fixes to laser carbine
  code/modules/projectiles/ammo_types/energy_ammo.dm
  code/modules/projectiles/guns/energy.dm
Labels: Fix, Grammar and Formatting

#16977 Adds new beginner engi loadouts + fixes beginner tutorial typos
  code/datums/outfits/quick_load_beginners.dm
  code/game/objects/machinery/vending/beginner_vendor.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/paperwork/beginner_tutorials.dm
  code/modules/paperwork/paper.dm
  code/modules/projectiles/guns/shotguns.dm
Labels: Fix, Grammar and Formatting, Quality of Life

#16981 You can no longer see ghost runetext when you can't see the ghost
  code/__HELPERS/mobs.dm
Labels: Fix

#16999 Loadout fix
  code/datums/loadout/loadout_seller.dm
Labels: Fix, In Game Exploit

#17005 fix tdf glob mob sprite
  icons/mob/clothing/hands.dmi
Labels: Sprites, Fix

#17010 Buffs primo maturation
  code/__DEFINES/mobs.dm
Labels: Balance
