Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2025-07, with the labels that each got.

#18034 Rebalances VSD guns in a few ways.
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Balance

#18036 Adds new pepe emotes: 4chan edition
  icons/misc/emoji.dmi
Labels: Sprites, Feature

#18037 More roundend stats for xenos.
  code/datums/actions/ability_actions.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/personal_statistics.dm
  code/datums/round_statistics.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
Labels: Feature

#18045 bike rev no longer reduces max fuel capacity
  code/modules/vehicles/motorbike.dm
Labels: Fix

#18011 Reduce TE-9001 heavy laser emplacement cost
  code/modules/reqs/supplypacks.dm
Labels: Balance

#18057 Plane fixes
  code/__DEFINES/layers.dm
  code/game/objects/structures/misc.dm
  code/game/objects/structures/xeno.dm
  code/modules/atmospherics/machinery/components/components_base.dm
  code/modules/power/lighting.dm
  code/modules/shuttle/shuttle.dm
  code/modules/xenomorph/acidwell.dm
Labels: Fix

#18068 Pyro charge CD fix
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
Labels: Balance

#18070 Fixes howi and mortar guis displaying NaN for latitude offset
  tgui/packages/tgui/interfaces/Mortar.jsx
Labels: Fix, UI

#18051 Fixed Warrior throw bug
  code/modules/mob/mob_grab.dm
Labels: Fix

#18061 Desant throw changes
  code/modules/vehicles/_hitbox.dm
Labels: Balance

#17979 Weather changes
  code/datums/weather/weather_types/sand_storm.dm
  code/datums/weather/weather_types/snow_storm.dm
Labels: Balance, Test Merge Candidate

#18050 bike revving now no longer removes fuel to negatives
  code/modules/vehicles/motorbike.dm
Labels: Removal

#18038 Minion cade fix
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
Labels: Balance

#18058 Priority candidates for hive leadership now need the appropriate flag to become rulers
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Code Improvement

#18052 Mutations Framework, Atomized
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/mode.dm
  code/__DEFINES/mutations.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/controllers/subsystem/points.dm
  code/datums/gamemodes/nuclear_war.dm
  code/game/objects/items/cocoon.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/mutation_datum.dm
  code/modules/mob/living/carbon/xenomorph/mutation_upgrade.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/xenomorph/mutations.dm
  icons/UI_Icons/buyable_icons.dmi
  icons/UI_Icons/map_blips.dmi
  icons/Xeno/1x1building.dmi
  icons/mob/screen_alert.dmi
  tgmc.dme
  tgui/packages/tgui/interfaces/HiveStatus.tsx
  tgui/packages/tgui/interfaces/MutationSelector.tsx
Labels: Code Improvement, Feature, Quality of Life

#17972 Pulsearmor
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/elements/egrill_element.dm
  code/datums/keybinding/mecha.dm
  code/game/objects/obj_defense.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
  code/modules/vehicles/mecha/mecha_actions.dm
Labels: Feature

#18087 Mutation Alert Bugfix
  code/modules/mob/living/carbon/xenomorph/mutation_upgrade.dm
Labels: Fix

#18094 Compact hive display now shows primodial tiers
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Feature, UI

#18092 heayvlaser
  code/modules/reqs/supplypacks/weapons_packs.dm
Labels: Grammar and Formatting

#18027 Increased price of tanglefoot minirockets from 200 to 400 points.
  code/game/objects/structures/dropship_ammo.dm
Labels: Balance

#18064 Mech/Tank Reduces Evo Requirement for Queen
  code/__DEFINES/mode.dm
  code/datums/gamemodes/nuclear_war.dm
  code/datums/jobs/job/shipside.dm
Labels: Balance

#18069 Less nades on crash
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Balance

#18073 Less BFG wall pierce
  code/modules/projectiles/ammo_types/energy_ammo.dm
Labels: Balance

#18075 Reduce Double Barrel recoil
  code/modules/projectiles/guns/shotguns.dm
Labels: Balance

#18035 Adds medical overwatch to canter and big bury
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
Labels: Map Edit, Feature

#18097 Add in jawdrop and broken heart and wilted rose emoji
  icons/misc/emoji.dmi
Labels: Sprites, Feature

#18096 fix light mech rockets
  code/modules/projectiles/ammo_types/mech_ammo.dm
Labels: Fix

#18098 Fix caste swap timer showing the wrong time
  code/__DEFINES/mobs.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/crash.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#17896 Dragon / King Population Locks
  code/datums/gamemodes/_game_mode.dm
  code/modules/mob/living/carbon/xenomorph/castes/dragon/castedatum_dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance, Feature, Test Merge Candidate

#18019 Fix Quick Vendor blacklisting vendor usage
  code/game/objects/machinery/vending/quick_vendor.dm
Labels: Fix

#18081 Removeable las sniper scope.
  code/modules/projectiles/gun_attachables/scope.dm
  code/modules/projectiles/guns/energy.dm
  icons/obj/items/guns/attachments/scope.dmi
  icons/obj/items/guns/energy64.dmi
Labels: Removal, Balance

#18082 Acid Spray/Puddles Changes & Resin Facehugger Fix
  code/game/objects/effects/aliens.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
  code/modules/xenomorph/maw.dm
  code/modules/xenomorph/trap.dm
Labels: Code Improvement, Balance, Fix

#18099 Mutations: Melter
  code/__DEFINES/is_helpers.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/mutations_melter.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  tgmc.dme
Labels: Feature

#18108 Mutations: Globadier
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/mutations_globadier.dm
  tgmc.dme
Labels: Feature

#18123 ACTUALLY fixes zstairs
  code/game/objects/structures/stairs.dm
Labels: Fix

#18113 Mutation Bugfixes
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/mutations_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/mutations_melter.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/abilities_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/mutations_retrograde.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/mutations_sentinel.dm
Labels: Fix

#18114 King Evolution Requirement fix
  code/datums/gamemodes/infestation.dm
  code/datums/gamemodes/nuclear_war.dm
Labels: Fix

#18119 Mutations: Hivelord
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/mutations_hivelord.dm
  tgmc.dme
Labels: Feature

#18120 Mutations: Carrier
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/abilities_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/mutations_carrier.dm
  code/modules/mob/living/carbon/xenomorph/egg.dm
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
  tgmc.dme
Labels: Feature

#18117 Mutations: Pyrogen
  code/__DEFINES/dcs/signals/signals.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/mutations_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/pyrogen.dm
  tgmc.dme
Labels: Feature

#18115 Adds roofs from Mojave Sun + Smoothing Fixes
  code/__DEFINES/footsteps.dm
  code/__DEFINES/icon_smoothing.dm
  code/game/turfs/floor.dm
  code/game/turfs/open.dm
  code/game/turfs/roof_types.dm
  code/game/turfs/walls/walls.dm
  icons/turf/roofs/roof_asphalt.dmi
  icons/turf/roofs/roof_asphalt_noborder.dmi
  icons/turf/roofs/roof_metal.dmi
  icons/turf/roofs/roof_rusty.dmi
  icons/turf/roofs/roof_sheet.dmi
  icons/turf/roofs/roof_sheet_noborder.dmi
  icons/turf/roofs/roof_wood.dmi
  sound/effects/footstep/roof1.ogg
  sound/effects/footstep/roof2.ogg
  sound/effects/footstep/roof3.ogg
  sound/effects/footstep/roof4.ogg
  tgmc.dme
Labels: Fix, Feature

#18121 Mutations: Bull
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/mutations_bull.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  tgmc.dme
Labels: Fix, Feature

#18066 Mutations: Runner
  code/__DEFINES/dcs/signals/signals.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/mutations_runner.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/living.dm
  tgmc.dme
Labels: Feature

#18111 Cleans up duplicate var definitions
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/gamemodes/campaign/perks.dm
  code/datums/outfits/icc.dm
  code/datums/outfits/special_forces.dm
  code/game/area/icecolony.dm
  code/game/objects/effects/decals/Cleanable/tracks.dm
  code/game/objects/effects/landmarks/corpsespawner.dm
  code/game/objects/effects/spawners/random/machinery.dm
  code/game/objects/items/multitool.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/kitchen_tray.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/tables_racks.dm
  code/game/turfs/walls/r_wall.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/spacesuits/syndi.dm
  code/modules/hydroponics/grown_inedible.dm
  code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/projectiles/ammo_types/microrail_ammo.dm
  code/modules/projectiles/ammo_types/xenos/widow_xenoammo.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/plasma.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/reagents/chemistry/reagents/drinks/alcohol_reagents.dm
  code/modules/reagents/chemistry/reagents/medical.dm
  code/modules/reagents/reagent_containers/food/pizzapasta.dm
  code/modules/reagents/reagent_containers/food/snacks/grown.dm
  code/modules/vehicles/armored/small_apc.dm
Labels: Code Improvement, Grammar and Formatting

#18134 Xenomorph Structures & Mutations for Valhalla/Admeme
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/mutation_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/xenomorph/_xeno_structure.dm
Labels: Quality of Life

#18106 Resin Door can only take brute/burn damage
  code/game/objects/structures/xeno.dm
Labels: Balance

#18126 Mutations: Behemoth
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/mutations_behemoth.dm
  tgmc.dme
Labels: Feature

#18143 Mutations: Ravager
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/mutations_ravager.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  tgmc.dme
Labels: Feature

#18144 Spray Acid Line Fix
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
Labels: Fix

#18132 Campaign: Antigas secondary kit
  code/datums/gamemodes/campaign/loadout_items/secondary_types.dm
Labels: Balance

#18131 Campaign smartgunner shield fix
  code/datums/gamemodes/campaign/loadout_items/_TGMC/suit.dm
Labels: Fix

#18127 Mutations: Boiler
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/mutations_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  tgmc.dme
Labels: Feature

#18146 Spray Acid Cone bypasses carbon acid cooldown
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Fix

#18012 Foam and smoke microdose removal
  code/modules/reagents/chemistry/reagents/medical.dm
Labels: Balance

#18124 Job description fixes
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
Labels: Fix

#18093 Add a button to toggle tadpole shutters within the tadpole console
  _maps/shuttles/minidropship_big.dmm
  _maps/shuttles/minidropship_factorio.dmm
  _maps/shuttles/minidropship_food.dmm
  _maps/shuttles/minidropship_mobile_bar.dmm
  _maps/shuttles/minidropship_outrider.dmm
  _maps/shuttles/minidropship_panopticon.dmm
  _maps/shuttles/minidropship_standard.dmm
  _maps/shuttles/minidropship_umbilical.dmm
  _maps/shuttles/minidropship_urbantower.dmm
  code/__DEFINES/dcs/signals/signals.dm
  code/game/objects/machinery/door_control.dm
  code/modules/shuttle/mini_dropship.dm
  tgui/packages/tgui/interfaces/Minidropship.tsx
Labels: Map Edit, Quality of Life

#18155 Fire support mission tweaks
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/patricks_rest/patricks_rest.dmm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/game/objects/structures/campaign_structures/misc_structures.dm
Labels: Balance, Map Edit

#18133 Mutations: Defiler
  code/__DEFINES/dcs/signals/signals.dm
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/abilities_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/mutations_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/mutations_retrograde.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  tgmc.dme
Labels: Feature

#18118 Mutations: Hunter
  code/modules/ai/ai_behaviors/xeno/xeno_illusion.dm
  code/modules/mob/illusion.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/mutations_hunter.dm
  tgmc.dme
Labels: Feature

#18151 Mutations: Widow
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/mutations_widow.dm
  tgmc.dme
Labels: Feature

#18165 Adds a mech weapons vendor to valhalla
  _maps/map_files/generic/Admin_Level.dmm
Labels: Map Edit, Feature

#18162 Various Mutation Bugfixes
  code/game/objects/effects/effect_system/smoke.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/mutations_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Balance, Fix

#18163 Mutations: Bloodthirster
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/mutations_bloodthirster.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/mutations_ravager.dm
  tgmc.dme
Labels: Feature, Grammar and Formatting

#18159 Removed some unneeded overlay stuff
  code/game/objects/structures/campaign_props.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  icons/obj/structures/campaign/campaign_64.dmi
  icons/obj/structures/campaign/campaign_big.dmi
  icons/obj/structures/train.dmi
Labels: Removal, Code Improvement

#18158 Walkover additions
  code/game/objects/structures/campaign_props.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  code/game/objects/structures/prop.dm
Labels: Quality of Life

#18161 Mutations: Puppeteer
  code/__DEFINES/status_effects.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/abilities_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/mutations_puppeteer.dm
  tgmc.dme
Labels: Feature

#18172 Mutations: King
  code/_globalvars/lists/objects.dm
  code/game/objects/items/explosives/grenades/flares.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/mutations_king.dm
  tgmc.dme
Labels: Fix, Feature

#18137 Fixes boilers being unable to fire up/down zlevels
  code/modules/mob/living/carbon/xenomorph/castes/boiler/abilities_boiler.dm
Labels: Fix

#18164 Campaign loadout black list/white list fixes
  code/datums/gamemodes/campaign/loadout_items/SOM/belt.dm
  code/datums/gamemodes/campaign/loadout_items/_TGMC/belt.dm
Labels: Quality of Life
