Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2025-03, with the labels that each got.

#17191 SG-153 (SG-62 Underbarrel) 12.7mm Ammo Bin for SG vendor/Requsitions/Factory
  code/__DEFINES/loadout.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/factory/parts.dm
  code/modules/factory/unboxer.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/rifles.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/items/ammo/packet.dmi
Labels: Balance, Fix, Feature

#17074 Swaps hugger xortar and acid XOBs
  code/modules/xenomorph/maw.dm
Labels: Balance

#17235 Fixes glasses/goggles being able to be toggled
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/night.dm
Labels: Fix

#17236 Adds mech dash cooldown
  code/__DEFINES/cooldowns.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Labels: Balance

#17246 Fix drop pods not centering screen text
  code/__DEFINES/text.dm
  code/game/objects/structures/droppod.dm
Labels: Fix

#17247 remove redundant mysql server
  .github/workflows/run_integration_tests.yml
Labels: Removal, GitHub

#17251 Delete the extra follow verbs
  code/modules/mob/dead/observer/observer.dm
Labels: Removal

#17252 Remove from tank has a confirmation popup
  code/modules/admin/admin_verbs.dm
Labels: Removal, Administration

#17255 Neutral faction mobs can no longer be hive targets
  code/modules/events/hive_threat.dm
Labels: Fix

#17253 Adds mechs to valhalla vehicle spawner button
  code/game/objects/machinery/buttons.dm
Labels: Feature

#17254 Mousing over clickable UI elements and wall mounted machinery now turns your cursor into a pointer
  code/_onclick/hud/ai.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/_onclick/hud/xeno/xeno.dm
  code/game/objects/machinery/door_control.dm
  code/game/objects/machinery/fire_alarm.dm
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/buildmode/buttons.dm
  code/modules/power/apc/apc.dm
Labels: Quality of Life

#17221 Facehuggers can no longer land on vehicles
  code/modules/mob/living/carbon/xenomorph/facehuggers.dm
Labels: Balance

#17249 Nerfs mech power
  code/game/objects/items/power_cells.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
  code/modules/vehicles/mecha/mecha_movement.dm
Labels: Balance

#17226 Removes the weird spaces at the beginnings of some messages
  code/datums/elements/scalping.dm
  code/game/objects/items.dm
  code/game/objects/items/books/book.dm
  code/game/objects/items/circuitboards/machine.dm
  code/game/objects/items/implants/implant_chem.dm
  code/game/objects/items/implants/implant_cloak.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/tools/policetape.dm
  code/game/objects/items/toys/toy_weapons.dm
  code/game/objects/items/toys/toys.dm
  code/game/objects/items/weapons/batons.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/machinery/autodoc.dm
  code/game/objects/machinery/fire_alarm.dm
  code/game/objects/machinery/flasher.dm
  code/game/objects/machinery/igniter.dm
  code/game/objects/machinery/kitchen/gibber.dm
  code/game/objects/machinery/kitchen/microwave.dm
  code/game/objects/machinery/kitchen/processor.dm
  code/game/objects/machinery/pipe/pipe_dispenser.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/kitchen_spike.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
  code/game/objects/structures/watercloset.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/ties.dm
  code/modules/detectivework/footprints_and_rag.dm
  code/modules/hydroponics/hydro_tools.dm
  code/modules/hydroponics/hydro_tray.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/paperwork/paper.dm
  code/modules/power/smes.dm
  code/modules/projectiles/mounted.dm
  code/modules/reagents/reagent_containers/borghydro.dm
  code/modules/reagents/reagent_containers/food/piecake.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  code/modules/surgery/implant.dm
  code/modules/vehicles/unmanned/unmanned_droid.dm
Labels: Removal, Fix

#17263 Adds a counter for sources of runtimes in runtime viewer
  code/modules/error_handler/error_viewer.dm
Labels: Feature

#17264 Fixes chat subsystem resend blackbox runtime
  code/controllers/subsystem/chat.dm
Labels: Fix

#17265 Fixes tank runtimes
  code/game/objects/items.dm
  code/modules/vehicles/armored/armored_weapons.dm
Labels: Fix

#17266 Mentors can no longer use the dsay verb
  code/modules/admin/admin_verbs.dm
Labels: Administration

#17267 Blocks admin keybinding usage by people without holders
  code/datums/keybinding/admin.dm
Labels: Administration

#17269 Perms change actually sends over assets and doesn't runtime
  code/modules/admin/panels/permission_panel.dm
Labels: Administration

#17271 Adresses `remove_from_storage` calling itself in most cases
  code/datums/storage/storage.dm
Labels: Removal, Fix

#17260 Discord commit bot new look
  .github/workflows/discord_pr_announce.yml
Labels: GitHub

#17257 Updates debugdalus, nodes some maps
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Campaign maps/jungle_outpost/jungle_outpost.dmm
  _maps/map_files/Campaign maps/som_base/sombase.dmm
  _maps/map_files/Campaign maps/som_raid_base/som_raiding_base.dmm
  _maps/map_files/Campaign maps/tgmc_raid_base/tgmc_raiding_base.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/desertdam/desertdam.dmm
  _maps/modularmaps/jungle_outpost/joutpostengi1.dmm
  _maps/modularmaps/jungle_outpost/joutpostengi2.dmm
  _maps/modularmaps/jungle_outpost/joutpostengi3.dmm
  _maps/modularmaps/jungle_outpost/joutposthydro1.dmm
  _maps/modularmaps/jungle_outpost/joutposthydro2.dmm
  _maps/modularmaps/jungle_outpost/joutposthydro3.dmm
  _maps/modularmaps/jungle_outpost/joutpostmedbay1.dmm
  _maps/modularmaps/jungle_outpost/joutpostmedbay2.dmm
  _maps/modularmaps/jungle_outpost/joutpostmedbay3.dmm
  _maps/modularmaps/jungle_outpost/joutpostscrates1.dmm
  _maps/modularmaps/jungle_outpost/joutpostscrates2.dmm
  _maps/modularmaps/jungle_outpost/joutpostscrates3.dmm
  _maps/modularmaps/jungle_outpost/joutpostscrates4.dmm
  _maps/modularmaps/jungle_outpost/joutpostwtower1.dmm
  _maps/modularmaps/jungle_outpost/joutpostwtower2.dmm
  _maps/modularmaps/jungle_outpost/joutpostwtower4.dmm
  _maps/shuttles/distress.dmm
  _maps/shuttles/distress_pmc.dmm
  _maps/shuttles/distress_ufo.dmm
  _maps/shuttles/distress_upp.dmm
Labels: Map Edit

#17270 Fix valhalla button runtime
  code/game/objects/machinery/buttons.dm
Labels: Fix

#17273 Disable cid randomizer checking on localhost + copy over default admin_ranks.txt from config repo
  code/modules/client/client_procs.dm
  config/admin_ranks.txt
Labels: Quality of Life

#17274 Allows maintainers to view player panel
  code/modules/admin/panels/player_panel.dm
  code/modules/admin/topic.dm
Labels: Administration

#17278 Tank faction setting
  code/modules/vehicles/armored/interiors/chairs.dm
Labels: Fix

#17275 Nuclear War: Silo emits Pheromones
  code/modules/xenomorph/silo.dm
Labels: Balance

#17238 Hud icon for AI mobs
  code/__DEFINES/dcs/signals/signals.dm
  code/datums/components/ai.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/hud/human.dmi
Labels: Quality of Life

#17276 Health updates after taking melting fire damage
  code/modules/projectiles/guns/_shared_ammo_objects.dm
Labels: Fix, Cookie

#17279 Sorted the OOC tab. Added Communication and Fix subheaders.
  code/game/verbs/ooc.dm
  code/modules/tgui_panel/external.dm
Labels: Quality of Life

#17220 Baton Pass Buff
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  icons/effects/96x96.dmi
Labels: Balance, Feature

#17199 Gives supply beacons the supply ordering interface
  code/game/objects/machinery/squad_supply/supply_beacon.dm
Labels: Stale, Feature

#17280 Fix a decap runtime
  code/modules/mob/inventory.dm
  code/modules/organs/limbs.dm
Labels: Fix

#17281 Fixes a storage runtime
  code/datums/storage/storage.dm
Labels: Fix

#17282 Prevent people joining valhalla before round has started
  code/modules/mob/dead/observer/observer.dm
Labels: Code Improvement

#17283 Fix seethrough runtime and improve relog experience with it
  code/datums/components/seethrough_mob.dm
Labels: Fix, Logging

#17212 Discord commands updates
  SQL/database_changelog.md
  SQL/tgmc-schema.sql
  code/__DEFINES/_subsystems.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/subsystem/discord.dm
  code/modules/admin/verbs/chat_commands.dm
  code/modules/discord/accountlink.dm
  code/modules/discord/discord_embed.dm
  code/modules/discord/discord_link_record.dm
  code/modules/discord/tgs_commands.dm
  code/modules/discord/toggle_notify.dm
  config/config.txt
  strings/1000_most_common.txt
  tgmc.dme
Labels: Feature, Administration, SQL

#17272 AI medical stuff
  code/__DEFINES/ai.dm
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/managed_inventory.dm
  code/game/objects/items/weapons/energy.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/human_mobs/hazard_avoidance.dm
  code/modules/ai/ai_behaviors/human_mobs/heal_procs.dm
  code/modules/ai/ai_behaviors/human_mobs/healing.dm
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
  code/modules/ai/ai_behaviors/human_mobs/self_heal.dm
  code/modules/ai/ai_behaviors/human_mobs/weapon_module.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/tgui_input/say_modal/typing.dm
  tgmc.dme
Labels: Feature

#17293 Overwatch fix
  code/game/objects/machinery/overwatch/military.dm
Labels: Fix

#17190 Managed passflags
  code/__DEFINES/campaign.dm
  code/__DEFINES/traits.dm
  code/_onclick/click.dm
  code/datums/components/jump.dm
  code/game/atoms/atom_movable.dm
  code/game/atoms/atom_movable/pass_flags.dm
  code/game/objects/items/jetpack.dm
  code/game/objects/objs.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/init_signals.dm
  code/modules/mob/living/living.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/hover_bike.dm
  tgmc.dme
Labels: Refactor, Fix

#17289 Line improvements
  code/__HELPERS/math.dm
Labels: Fix

#17222 Xeno turret fix
  code/__HELPERS/unsorted.dm
  code/modules/xenomorph/xeno_turret.dm
Labels: Fix, Test Merge Candidate

#17284 Improve some xeno helpers and fix strains allow bypass of maximum_active_caste
  code/_globalvars/lists/mobs.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Fix

#17299 More AI hazard detection
  code/game/objects/effects/aliens.dm
  code/game/objects/effects/overlays.dm
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/shuttle/ripple.dm
Labels: Feature

#17301 Monkey business
  code/modules/mob/living/carbon/human/human_species.dm
Labels: Feature

#17291 Adds new MAPPING_DIRECTIONAL_HELPERS from tg
  code/__DEFINES/__game.dm
  code/__DEFINES/directional.dm
  code/__DEFINES/machines.dm
  code/__DEFINES/misc.dm
  code/game/objects/machinery/fire_alarm.dm
  tgmc.dme
Labels: Code Improvement

#17295 Fixes failed mech dashes still using power
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Labels: Fix

#17296 You can no longer rearm mech weapons while firing
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Balance

#17297 Mech repair retargets itself to the chest now when a limb is repaired
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Labels: Quality of Life

#17304 Fixes monkey sprites being really small
  icons/mob/human_races/r_monkey.dmi
Labels: Sprites, Fix

#17306 AI and melee weapon attack delay fixes
  code/_onclick/item_attack.dm
  code/game/objects/items/weapons/twohanded.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
  code/modules/reagents/reagent_containers/jerrycan.dm
Labels: Fix

#17305 Better AI obstacle handling
  code/__DEFINES/ai.dm
  code/game/objects/structures/barricade.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
  code/modules/projectiles/sentries.dm
Labels: Feature, Quality of Life

#17307 AI weapon equip fix
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
Labels: Fix

#17303 AI Retreat improvements
  code/datums/elements/shrapnel_removal.dm
  code/modules/ai/ai_behaviors/human_mobs/heal_procs.dm
  code/modules/ai/ai_behaviors/human_mobs/healing.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
Labels: Code Improvement

#17310 NPC wrangling
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
Labels: Quality of Life

#17312 Ssmappping update
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/dcs/signals/signals_lazy_templates.dm
  code/__DEFINES/flags_turf.dm
  code/__DEFINES/lazy_templates.dm
  code/__DEFINES/mapping.dm
  code/__DEFINES/maps.dm
  code/__DEFINES/multiz.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/lazy_templates.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/mapping.dm
  code/controllers/subsystem/mapping.dm
  code/controllers/subsystem/shuttle.dm
  code/datums/armor.dm
  code/datums/datum.dm
  code/datums/interior/_interior.dm
  code/datums/lazy_template.dm
  code/datums/map_config.dm
  code/game/atoms/_atom.dm
  code/game/objects/structures/droppod.dm
  code/game/turfs/floor.dm
  code/game/turfs/space.dm
  code/game/turfs/space/transit.dm
  code/game/turfs/turf.dm
  code/game/world.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/fun_verbs.dm
  code/modules/lighting/lighting_static/static_lighting_source.dm
  code/modules/mapping/cordon.dm
  code/modules/mapping/map_template.dm
  code/modules/mapping/preloader.dm
  code/modules/mapping/reader.dm
  code/modules/mapping/space_management/multiz_helpers.dm
  code/modules/mapping/space_management/space_level.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/mapping/space_management/traits.dm
  code/modules/mapping/space_management/zlevel_manager.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/paperwork/photography.dm
  code/modules/power/multiz.dm
  tgmc.dme
Labels: Code Improvement, Fix, Feature

#17315 Fix for engineers standard loadout
  code/datums/outfits/quick_load_beginners.dm
Labels: Fix

#17322 Actual AI wield fix
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
Labels: Fix

#17058 Melter: A Strain for Runner
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/abilities_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/runner.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  icons/Xeno/castes/runner.dmi
Labels: Feature

#17324 SOM tank offset fix
  code/modules/vehicles/_hitbox.dm
Labels: Fix

#17325 ajacent
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
Labels: Grammar and Formatting

#17292 Refactor proximity monitors and use them for xeno structure proximity alerts
  code/datums/components/connect_containers.dm
  code/datums/components/connect_range.dm
  code/datums/proximity_monitor/field.dm
  code/datums/proximity_monitor/proximity_monitor.dm
  code/game/atoms/_atom.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/effects/proximity.dm
  code/modules/assembly/proximity.dm
  code/modules/unit_tests/create_and_destroy.dm
  code/modules/xenomorph/_xeno_structure.dm
  code/modules/xenomorph/silo.dm
  tgmc.dme
Labels: Refactor

#17313 Remove hardcode groundside noparallax and split it out into a Z trait
  _maps/bigred_v2.json
  _maps/bluesummers.json
  _maps/daedalusprison.json
  _maps/desertdam.json
  _maps/desparity.json
  _maps/gelida_iv.json
  _maps/ice_colony_v2.json
  _maps/icy_caves.json
  _maps/kutjevo.json
  _maps/lavaoutpost.json
  _maps/lawanka.json
  _maps/lv624.json
  _maps/lv759.json
  _maps/magmoor_digsite_iv.json
  _maps/metnal.json
  _maps/orion_outpost.json
  _maps/oscar_outpost.json
  _maps/prison_station_fop.json
  _maps/research_outpost.json
  _maps/riptide.json
  _maps/vapor_processing.json
  _maps/whiskey_outpost_v2.json
  code/__DEFINES/maps.dm
  code/_onclick/hud/parallax.dm
  code/modules/mob/mob.dm
Labels: Removal, Fix, Map Edit

#17314 MultiZ Cables can't be destroyed
  code/modules/power/multiz.dm
Labels: Balance

#17320 Fix some layering
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/flora.dm
Labels: Fix

#17326 MultiZ Movement and openspaces
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/movement.dm
  code/__DEFINES/obj_flags.dm
  code/__DEFINES/traits.dm
  code/__DEFINES/turfs.dm
  code/datums/components/riding/riding.dm
  code/datums/components/riding/riding_mob.dm
  code/datums/components/riding/riding_vehicle.dm
  code/datums/elements/turf_transparency.dm
  code/game/atoms/_atom.dm
  code/game/atoms/atom_movable.dm
  code/game/buckling.dm
  code/game/objects/effects/temporary_visuals/temporary_visual.dm
  code/game/objects/structures/droppod.dm
  code/game/turfs/open.dm
  code/game/turfs/open/openspace.dm
  code/game/turfs/turf.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob.dm
  code/modules/unit_tests/create_and_destroy.dm
  code/modules/unit_tests/focus_only_tests.dm
  icons/effects/64x64.dmi
  icons/turf/floors.dmi
  tgmc.dme
Labels: Code Improvement, Fix, Feature

#17328 Certain HUDs will now appear over game world objects
  code/__DEFINES/atom_hud.dm
  code/_onclick/hud/rendering/plane_masters/plane_master_subtypes.dm
  code/game/atoms/_atom.dm
Labels: Quality of Life

#17319 Adds FOV
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/fov.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/traits.dm
  code/_onclick/hud/hud.dm
  code/datums/components/clothing_fov_visor.dm
  code/datums/components/fov_handler.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/living_fov.dm
  code/modules/mob/living/login.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/mob.dm
  icons/effects/fov/field_of_view.dmi
  icons/effects/fov/fov_effects.dmi
  tgmc.dme
Labels: Code Improvement

#17342 Warlock Psyblast goes over objects if right next to it
  code/modules/projectiles/ammo_types/xenos/energy_xenoammo.dm
Labels: Fix

#17333 Fixes pod launcher not always working
  code/modules/admin/verbs/centcom_podlauncher.dm
Labels: Fix

#17346 Glass floors are seethough
  code/game/turfs/iron_floor.dm
Labels: Feature

#17345 Adds multiz stairs
  code/_globalvars/lists/objects.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/structures/stairs.dm
  tgmc.dme
Labels: Feature

#17349 remove var relating to old bombvest filter
  code/game/objects/items/explosives/bombvest.dm
Labels: Removal

#17350 Queen visual warping shriek wave
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Quality of Life

#17351 mech legs now slow increasingly based on hp instead of when destroyed
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Labels: Balance

#17352 Fixes bad casting in tank desants
  code/modules/vehicles/_hitbox.dm
Labels: Fix

#17334 CAS crosshairs
  code/game/objects/structures/dropship_ammo.dm
  code/modules/condor/cas_chair.dm
  code/modules/condor/cas_shuttle.dm
  icons/UI_Icons/cas_crosshairs/banshee.dmi
  icons/UI_Icons/cas_crosshairs/dandelion.dmi
  icons/UI_Icons/cas_crosshairs/fatty.dmi
  icons/UI_Icons/cas_crosshairs/gun.dmi
  icons/UI_Icons/cas_crosshairs/gun_hv.dmi
  icons/UI_Icons/cas_crosshairs/keeper.dmi
  icons/UI_Icons/cas_crosshairs/laser.dmi
  icons/UI_Icons/cas_crosshairs/mighty.dmi
  icons/UI_Icons/cas_crosshairs/moab.dmi
  icons/UI_Icons/cas_crosshairs/monarch.dmi
  icons/UI_Icons/cas_crosshairs/napalm.dmi
  icons/UI_Icons/cas_crosshairs/poppies.dmi
  icons/UI_Icons/cas_crosshairs/rocket.dmi
  icons/UI_Icons/cas_crosshairs/rocket_flare.dmi
  icons/UI_Icons/cas_crosshairs/rocket_incend.dmi
  icons/UI_Icons/cas_crosshairs/rocket_smoke.dmi
  icons/UI_Icons/cas_crosshairs/rocket_tangle.dmi
  icons/UI_Icons/cas_crosshairs/swansong.dmi
  icons/UI_Icons/cas_crosshairs/tiny.dmi
  icons/UI_Icons/cas_crosshairs/widowmaker.dmi
Labels: Sprites, Test Merge Candidate, Quality of Life

#17344 droid and turret faction checks
  code/__HELPERS/ai.dm
Labels: Fix

#17332 Fixes baseturf issues
  _maps/bigred_v2.json
  _maps/bluesummers.json
  _maps/corsat.json
  _maps/daedalusprison.json
  _maps/deltastation.json
  _maps/desertdam.json
  _maps/desparity.json
  _maps/gelida_iv.json
  _maps/ice_colony_v2.json
  _maps/icy_caves.json
  _maps/kutjevo.json
  _maps/lavaoutpost.json
  _maps/lawanka.json
  _maps/lv624.json
  _maps/lv759.json
  _maps/magmoor_digsite_iv.json
  _maps/metnal.json
  _maps/orion_outpost.json
  _maps/oscar_outpost.json
  _maps/prison_station_fop.json
  _maps/research_outpost.json
  _maps/riptide.json
  _maps/slumbridge.json
  _maps/vapor_processing.json
  _maps/whiskey_outpost_v2.json
  code/datums/elements/turf_transparency.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/missions/airbase_raid.dm
  code/datums/gamemodes/campaign/missions/asat_capture.dm
  code/datums/gamemodes/campaign/missions/base_rescue.dm
  code/datums/gamemodes/campaign/missions/fire_support_raid.dm
  code/datums/gamemodes/campaign/missions/mech_wars.dm
  code/datums/gamemodes/campaign/missions/patrol_mission.dm
  code/datums/gamemodes/campaign/missions/phoron_capture.dm
  code/datums/gamemodes/campaign/missions/raiding_base.dm
  code/datums/gamemodes/campaign/missions/supply_raid.dm
  code/datums/gamemodes/campaign/missions/teleporter_raid.dm
  code/game/turfs/turf.dm
  code/modules/mapping/map_template.dm
  code/modules/mapping/modular_mapping.dm
Labels: Fix, Map Edit, Test Merge Candidate

#17340 Foam submerge
  code/game/objects/effects/effect_system/foam.dm
Labels: Feature

#17347 Adds multiz ladders and sorta ladder refactor
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/modularmaps/EORG/cs_militia.dmm
  code/__DEFINES/dcs/signals/signals_ladder.dm
  code/__DEFINES/flags.dm
  code/__DEFINES/traits.dm
  code/game/objects/structures/ladders.dm
  icons/obj/structures/structures.dmi
  tgmc.dme
Labels: Refactor, Map Edit, Feature, Quality of Life

#17311 NPC defib
  code/__DEFINES/defibrillator.dm
  code/datums/components/ai.dm
  code/datums/managed_inventory.dm
  code/game/objects/items/defibrillator.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/human_mobs/heal_procs.dm
  code/modules/ai/ai_behaviors/human_mobs/healing.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
Labels: Fix, Feature, Test Merge Candidate

#17288 Fire lighting fix
  code/modules/projectiles/guns/_shared_ammo_objects.dm
Labels: Feature, Test Merge Candidate

#17355 Hivelord: Recovery Pylon
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/hivelord.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/xenomorph/recovery_pylon.dm
  icons/UI_Icons/map_blips.dmi
  icons/Xeno/2x2building.dmi
  icons/Xeno/actions/construction.dmi
  tgmc.dme
Labels: Fix, Feature

#17202 adds Tank Autocannon
  code/datums/storage/subtypes/tank.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/reqs/supplypacks/vehicles_packs.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/armored_weapons.dm
  icons/obj/armored/3x3/tank_gun.dmi
  icons/obj/armored/hardpoint_modules.dmi
  icons/obj/items/ammo/tank.dmi
Labels: Feature, Test Merge Candidate, Requires Testing

#17357 Blood Splatter on Melee
  code/_onclick/item_attack.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
Labels: Code Improvement, Feature

#17359 Fix new player hud runtime
  code/_onclick/hud/hud.dm
  code/_onclick/hud/new_player.dm
  code/_onclick/hud/screen_objects/menu_text_objects.dm
Labels: Fix

#17356 NPC general process stuff
  code/datums/managed_inventory.dm
  code/datums/outfits/npc_marines.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/reagents/reagent_containers/food/snacks.dm
  tgmc.dme
Labels: Code Improvement, Feature

#17230 Tier 4 Caste: Dragon
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/dragon/castedatum_dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/dragon/dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/projectile.dm
  icons/UI_Icons/map_blips.dmi
  icons/Xeno/300x300.dmi
  icons/Xeno/32x64.dmi
  icons/Xeno/64x64.dmi
  icons/Xeno/96x144.dmi
  icons/Xeno/actions/dragon.dmi
  icons/Xeno/castes/dragon.dmi
  icons/effects/128x128.dmi
  icons/effects/effects.dmi
  icons/mob/hud/xeno_health.dmi
  sound/effects/alien/dragon/backhand_hit.ogg
  sound/effects/alien/dragon/crytogensis_impact.ogg
  sound/effects/alien/dragon/dragonbreath_start.ogg
  sound/effects/alien/dragon/flying_flight.ogg
  sound/effects/alien/dragon/flying_landing.ogg
  sound/effects/alien/dragon/flying_progress.ogg
  sound/effects/alien/dragon/lightning_impact.ogg
  sound/effects/alien/dragon/tailswipe_hit.ogg
  sound/effects/alien/dragon/void_explosion.ogg
  tgmc.dme
Labels: Code Improvement, Feature

#17348 Adds multiz movement/looking verbs, keybind and attaches it to mousescroll
  code/__DEFINES/conflict.dm
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/_onclick/living.dm
  code/_onclick/observer.dm
  code/datums/keybinding/living.dm
  code/datums/keybinding/movement.dm
  code/modules/mob/camera/camera.dm
  code/modules/mob/dead/observer/observer_movement.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/silicon/ai/ai_verbs.dm
  code/modules/mob/mob_movement.dm
  tgmc.dme
Labels: Feature, Quality of Life

#17369 Splits greyscale can attach and can vend flags
  code/__DEFINES/mecha.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
Labels: Fix

#17370 Ghosts see mech hud now as part of squad hud
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Fix

#17374 Adds SSsound caching
  code/__DEFINES/rust_g.dm
  code/controllers/subsystem/sounds.dm
Labels: Code Improvement

#17375 Playsound will now scream under certain conditions
  code/__DEFINES/sound.dm
  code/game/objects/items/storage/storage.dm
  code/game/sound.dm
  code/modules/projectiles/guns/grenade_launchers.dm
Labels: Code Improvement

#17376 Mech turns are now silent
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Labels: Quality of Life

#17378 Fix untoggleable glasses turning themselves off on init
  code/modules/clothing/glasses/glasses.dm
Labels: Fix

#17337 Better explosion logging & directional explosions
  code/controllers/subsystem/explosions.dm
  code/controllers/subsystem/ticker.dm
  code/datums/components/remote_control.dm
  code/datums/fire_support/gun_run.dm
  code/datums/fire_support/missile.dm
  code/datums/fire_support/mortar.dm
  code/datums/fire_support/rockets.dm
  code/datums/gamemodes/campaign/missions/raiding_base.dm
  code/game/objects/items/explosives/bombvest.dm
  code/game/objects/items/explosives/grenades/bullet_grenade.dm
  code/game/objects/items/explosives/grenades/explosive_grenades.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/mine.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/items/radio/detpack.dm
  code/game/objects/items/tools/maintenance_tools.dm
  code/game/objects/machinery/bots/roomba.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/dropship_ammo.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/reagent_dispensers.dm
  code/game/objects/structures/supplypod.dm
  code/game/objects/structures/vehicle_props.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/smites/bsa.dm
  code/modules/buildmode/submodes/boom.dm
  code/modules/power/batteryrack.dm
  code/modules/power/lighting.dm
  code/modules/power/port_gen.dm
  code/modules/power/smes.dm
  code/modules/power/smes_construction.dm
  code/modules/projectiles/ammo_types/energy_ammo.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/mech_ammo.dm
  code/modules/projectiles/ammo_types/mortar_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/projectiles/ammo_types/shotgun_ammo.dm
  code/modules/projectiles/ammo_types/tx54_ammo.dm
  code/modules/projectiles/ammunition.dm
  code/modules/projectiles/sentries.dm
  code/modules/reagents/chemistry/recipes/other.dm
  code/modules/shuttle/gamemodes/crash.dm
  code/modules/vehicles/armored/som_armored_weapons.dm
  code/modules/vehicles/atv.dm
  code/modules/vehicles/cars/car.dm
  code/modules/vehicles/hover_bike.dm
  code/modules/vehicles/motorbike.dm
Labels: Code Improvement, Administration, Test Merge Candidate, Logging

#17366 Bayonet fixes
  _maps/map_files/Bluesummers/bluesummers.dmm
  _maps/map_files/Campaign maps/tgmc_raid_base/tgmc_raiding_base.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  code/datums/managed_inventory.dm
  code/datums/storage/subtypes/belt.dm
  code/datums/storage/subtypes/internal.dm
  code/game/objects/effects/spawners/random/weaponry.dm
  code/game/objects/items/gift_wrappaper.dm
  code/game/objects/items/storage/pouch.dm
  code/game/objects/items/weapons/blades.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/clothing/modular_armor/xenonauten.dm
  code/modules/clothing/shoes/marine_shoes.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/marine_armor.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/gimmick.dm
  code/modules/projectiles/gun_attachables/muzzle.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/mounted.dm
  code/modules/projectiles/guns/pistols.dm
  code/modules/projectiles/guns/plasma.dm
  code/modules/projectiles/guns/revolvers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
Labels: Code Improvement, Fix, Map Edit

#17384 NPC death checks for chems
  code/modules/reagents/chemistry/reagents.dm
Labels: Fix

#17380 NPC gun usage fixes
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
  code/modules/ai/ai_behaviors/human_mobs/weapon_module.dm
Labels: Fix, Feature

#17383 NPC defib markers
  code/datums/components/ai.dm
  code/game/data_huds.dm
  code/game/objects/items/radio/headset.dm
Labels: Fix

#17381 NPC item storage
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
  code/modules/ai/ai_behaviors/human_mobs/weapon_module.dm
Labels: Feature

#17367 Adds extra sentries to valhalla
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature, Grammar and Formatting

#17327 Metnal bugfix and other changes
  _maps/map_files/Metnal_Operation/Metnal_Operation.dmm
Labels: Fix, Map Edit

#17389 Increases Melter's Health & Armor
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
Labels: Balance

#17360 Minions sell for 10 points instead of 50
  code/modules/requisitions/supply_export.dm
Labels: Balance

#17390 Fix SOMEBODY merging a broken autocannon PR without interior sounds or ammo rack sprites and with two different ammo types that shoot the same bullet
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/armored/icc_armored_weapons.dm
  icons/obj/armored/3x3/tank_interior.dmi
  sound/vehicles/weapons/tank_autocannon_interior_fire_1.ogg
  sound/vehicles/weapons/tank_autocannon_interior_fire_2.ogg
  sound/vehicles/weapons/tank_autocannon_reload.ogg
Labels: Fix

#17391 Fixes floors layering incorrectly
  code/game/objects/structures/prop.dm
  code/game/turfs/open.dm
Labels: Fix

#17392 Fix acid layering under what its on top of sometimes
  code/game/objects/effects/aliens.dm
Labels: Fix

#17393 Fixes silo alerts alerting on friendlies
  code/modules/xenomorph/_xeno_structure.dm
Labels: Fix

#17365 Revert "Removes the cap of the derringer in the vendor"
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Removal

#17394 Mech overload automatically disables on running out of power
  code/modules/vehicles/mecha/mecha_movement.dm
Labels: Quality of Life

#17396 Fixes wonkiness with non-self camera perspectives
  code/game/objects/items/gift_wrappaper.dm
  code/game/objects/machinery/computer/camera_advanced.dm
  code/game/objects/machinery/computer/camera_console.dm
  code/game/objects/machinery/kitchen/gibber.dm
  code/game/objects/structures/rappel_system.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  code/modules/client/client_procs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/ai/freelook/eye.dm
  code/modules/mob/mob.dm
  code/modules/recycling/disposal.dm
Labels: Fix

#17398 Fixes slow mo shriekwaves
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Fix

#17402 Dragon Passflags
  code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
  code/modules/projectiles/ammo_datums.dm
Labels: Code Improvement

#17377 Double xeno maw impact time
  code/modules/xenomorph/maw.dm
Labels: Balance

#17372 Crusher charges always target legs
  code/__DEFINES/is_helpers.dm
  code/modules/mob/living/carbon/xenomorph/charge_crush.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
Labels: Balance

#17198 [BOUNTY] Gorger drain abilities now steal Greenblood
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/mobs.dm
  code/datums/components/chem_booster.dm
  code/datums/status_effects/xeno_buffs.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/abilities_gorger.dm
Labels: Balance, Stale

#17405 Dragon Movement Speed Nerfs / Dragon Breath Armor Reduction
  code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/dragon/castedatum_dragon.dm
Labels: Balance

#17404 Some 516 and UI fixes
  code/__DEFINES/html_assistant.dm
  code/__HELPERS/stat_tracking.dm
  code/_onclick/hud/map_popups.dm
  code/datums/chatmessage.dm
  code/datums/mind.dm
  code/game/objects/items/books/book.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/structures/noticeboard.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/debug_verbs.dm
  code/modules/admin/tag.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/admin/verbs/legacy.dm
  code/modules/mob/new_player/poll.dm
  code/modules/paperwork/clipboard.dm
  code/modules/paperwork/filingcabinet.dm
  code/modules/paperwork/folders.dm
  code/modules/paperwork/paper.dm
  code/modules/paperwork/photography.dm
  tgmc.dme
  tgui/global.d.ts
  tgui/packages/tgui-panel/audio/player.js
  tgui/packages/tgui-panel/audio/player.tsx
  tgui/packages/tgui-panel/chat/renderer.jsx
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/public/tgui.html
Labels: Fix

#17408 Seamless Blood Decals
  code/game/objects/effects/decals/Cleanable/humans.dm
Labels: Feature

#17335 Gun Crosshairs
  code/game/objects/items/weapons/blades.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/grenade_launchers.dm
  code/modules/projectiles/guns/rifles.dm
  code/modules/projectiles/guns/shotguns.dm
  code/modules/projectiles/guns/specialist.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
  icons/UI_Icons/gun_crosshairs/explosive.dmi
  icons/UI_Icons/gun_crosshairs/rifle.dmi
  icons/UI_Icons/gun_crosshairs/shotgun.dmi
  icons/UI_Icons/gun_crosshairs/sniper.dmi
Labels: Sprites, Feature, Test Merge Candidate

#17406 Campaign mech nerfs
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Labels: Balance

#17382 Adds a multi-z debug map
  _maps/map_files/multiz_debug/multiz_debug.dmm
  _maps/multiz_debug.json
  code/game/area/mainship.dm
  code/game/objects/machinery/camera/camera.dm
  code/game/objects/structures/ladders.dm
  code/modules/transport/elevator/elev_controller.dm
  code/modules/transport/elevator/elev_panel.dm
  code/modules/transport/transport_module.dm
  config/shipmaps.txt
  icons/obj/machines/buttons.dmi
  icons/obj/machines/elevatorpanel.dmi
  tgui/packages/tgui/interfaces/ElevatorPanel.tsx
Labels: Map Edit, Feature

#17422 NPC gun equip fix
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
Labels: Fix

#17423 Some autocannon nerfs
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/vehicles/armored/ammo_magazine.dm
  code/modules/vehicles/armored/armored_weapons.dm
Labels: Balance

#17400 Revert "Ghosts see mech hud now as part of squad hud"
  code/modules/mob/dead/observer/login.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Test Merge Candidate

#17432 NPC Undefibbable check
  code/modules/ai/ai_behaviors/human_mobs/healing.dm
Labels: Fix

#17429 glorp
  icons/misc/emoji.dmi
Labels: Sprites

#17415 More Dragon Nerfs
  code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/dragon/castedatum_dragon.dm
Labels: Balance

#17433 Fix NPC item storing
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
Labels: Fix

#17434 NPC buckle improvements
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
  code/modules/vehicles/__vehicle.dm
Labels: Quality of Life

#17416 No zapping Incorporeal/Godmode stuff
  code/datums/beam.dm
Labels: Fix

#17412 Fixes death timers for T4 strains
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Fix

#17115 Reworks tadpole weapon attachments
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  code/__DEFINES/cooldowns.dm
  code/game/objects/items/explosives/grenades/smoke_grenades.dm
  code/game/objects/machinery/dropship_part_fabricator.dm
  code/game/objects/structures/dropship_equipment.dm
  icons/obj/items/grenade.dmi
  icons/obj/machines/drone_fab.dmi
  icons/obj/structures/prop/mainship.dmi
  sound/machines/dropship_fabricator.ogg
Labels: Removal, Map Edit, Feature, Test Merge Candidate

#17245 Generator mist
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  code/datums/gamemodes/infestation.dm
  code/modules/power/groundmap_geothermal.dm
Labels: Fix, Map Edit, Feature, Test Merge Candidate

#17435 Does the important z blockers and some random ones i felt like doing
  code/game/objects/structures/bookcase.dm
  code/game/objects/structures/campaign_structures/capture_objectives.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  code/game/objects/structures/cargo_container.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/razorwire.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/tables_racks.dm
  code/game/objects/structures/tank_dispenser.dm
  code/game/objects/structures/window.dm
Labels: Code Improvement

#17437 Open space is unweedable
  code/game/turfs/turf.dm
Labels: Fix

#17438 The tram no longer launches you through the windshield at mach 3
  code/modules/transport/transport_module.dm
Labels: Fix

#17439 Fix shriek sleeping
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Fix

#17440 Fix moved not updating planes properly
  code/game/atoms/atom_movable.dm
  code/modules/mob/living/living.dm
  code/modules/xenomorph/recovery_pylon.dm
Labels: Fix

#17441 Probably fix xeno wounds not layering properly in multiz
  code/modules/mob/living/carbon/xenomorph/update_icons.dm
Labels: Fix

#17447 fix vents layering under the floor
  code/__DEFINES/layers.dm
  code/modules/atmospherics/machinery/components/components_base.dm
Labels: Fix

#17446 Traps will layer lower
  code/modules/xenomorph/trap.dm
Labels: Fix

#17442 McXonalds Drive Thru Resin Jelly (All xenos can pickup jelly)
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/dragon/castedatum_dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/nymph/castedatum_nymph.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
Labels: Balance

#17424 Weak explosions no longer destroy weeds
  code/game/objects/effects/weeds.dm
Labels: Balance

#17353 If you toggle off EOR sounds it actually works
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/infestation.dm
Labels: Fix

#17379 Maw limit
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Balance

#17450 NPC checks for instant revive trait
  code/modules/ai/ai_behaviors/human_mobs/heal_procs.dm
Labels: Fix
