Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2025-02, with the labels that each got.

#16970 Jumping mobs now make any mobs buckled to them jump
  code/datums/components/jump.dm
Labels: Feature, Test Merge Candidate, Requires Testing

#16984 Adds death on crit trait (supersoldiers stim and robot fix)
  code/__DEFINES/traits.dm
  code/datums/actions/species_actions/prototype_supersoldier_action.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/human/species_types/combat_robots.dm
  code/modules/mob/living/carbon/human/species_types/prototype_supersoldier.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/mob_verbs.dm
Labels: Code Improvement, Fix, Feature

#17023 Fix "Toggle Seethrough" toggle being lost when gaining primo
  code/datums/components/seethrough_mob.dm
Labels: Fix

#17029 Hive screen no longer shows strains
  code/_globalvars/lists/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
  code/modules/mob/living/carbon/xenomorph/castes/nymph/castedatum_nymph.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppet/castedatum_puppet.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/castedatum_spiderling.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Fix, Quality of Life

#17026 Armour module style touchups
  code/datums/gamemodes/campaign/loadout_items/SOM/head.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/attachments/storage.dm
  code/modules/reqs/supplypacks.dm
Labels: Grammar and Formatting

#17024 Fixes some modular armor descriptions inaccurately stating the amount of protection provided
  code/modules/clothing/modular_armor/attachments/arm_plates.dm
  code/modules/clothing/modular_armor/attachments/chest_plates.dm
  code/modules/clothing/modular_armor/attachments/leg_plates.dm
Labels: Fix, Grammar and Formatting

#17008 Vendors now vend the item into your selected hand
  code/modules/mob/mob.dm
Labels: Quality of Life

#16966 Warlock no longer immobilized during Psyblast
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
Labels: Balance

#16982 fix jaw stat tracking
  code/modules/xenomorph/maw.dm
Labels: Stale, Fix

#17003 Fix outfits missing their holster contents
  code/datums/outfits/quick_load_outfits.dm
  code/datums/outfits/som_ert.dm
Labels: Fix

#17040 disposable nerf
  code/modules/projectiles/ammo_types/rocket_ammo.dm
Labels: Balance

#16912 Oppressor: A Strain for Praetorian
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/movespeed_modification.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/praetorian.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  icons/Xeno/Effects.dmi
  icons/Xeno/actions/praetorian.dmi
  icons/Xeno/castes/praetorian.dmi
Labels: Sprites, Feature, Test Merge Candidate, Requires Testing

#17036 Fix several DB issues
  SQL/database_changelog.md
  SQL/tgmc-schema.sql
  code/__DEFINES/_subsystems.dm
  code/datums/jobs/job/special_forces.dm
  code/datums/jobs/job/survivor.dm
Labels: Fix, Administration

#17045 fireteam fixes
  code/__DEFINES/jobs.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Fix

#17035 Adds assault crewman to Valhalla jobs
  code/datums/jobs/job/fallen.dm
  code/datums/outfits/shipside.dm
Labels: Feature

#17030 Ghosts can view reagents on examine like corpsmen
  code/game/atoms/atom_examine.dm
  code/game/objects/items/explosives/grenades/chem_grenade.dm
  code/game/objects/items/storage/reagent_pouch.dm
Labels: Feature

#17027 Fire and liquid turf jump/throw interaction fixes
  code/game/atoms/atom_movable.dm
  code/game/turfs/liquid_turfs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
Labels: Fix, Test Merge Candidate

#17044 Overwatch cleanup
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/Fort_Phobos/Fort_Phobos.dmm
  _maps/map_files/Iteron/Iteron.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/debugdalus/tgs_debugdalus.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  code/__DEFINES/jobs.dm
  code/datums/actions/orders.dm
  code/game/objects/machinery/overwatch.dm
  code/game/objects/machinery/overwatch/_overwatch.dm
  code/game/objects/machinery/overwatch/military.dm
  code/game/objects/machinery/overwatch/types.dm
  tgmc.dme
Labels: Code Improvement, Balance

#16951 Hivemind Gets Ability to Use Acid Jaws/Maws
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/xenomorph/maw.dm
Labels: Balance, Feature

#17061 Removes shoulder fire from the game
  code/modules/projectiles/projectile.dm
Labels: Balance

#16902 Revamp/maintenance pass on of mostly non-tgui UI
  code/__DEFINES/_helpers.dm
  code/__DEFINES/colors.dm
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/text.dm
  code/_onclick/hud/screen_objects/menu_text_objects.dm
  code/_onclick/hud/screen_objects/text_objects.dm
  code/datums/chatmessage.dm
  code/datums/fire_support/fire_support.dm
  code/datums/gamemodes/campaign.dm
  code/datums/gamemodes/campaign/campaign_mission.dm
  code/datums/gamemodes/campaign/faction_stats.dm
  code/datums/gamemodes/combat_patrol.dm
  code/datums/gamemodes/hvh.dm
  code/datums/jobs/squads.dm
  code/datums/keybinding/client.dm
  code/datums/view.dm
  code/game/objects/effects/countdown.dm
  code/game/objects/machinery/overwatch/military.dm
  code/game/objects/machinery/status_display.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/orbital_cannon.dm
  code/game/objects/structures/sensor_tower.dm
  code/game/verbs/ooc.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_toggles.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/mob.dm
  code/modules/screen_alert/command_alert.dm
  code/modules/shuttle/gamemodes/crash.dm
  code/modules/shuttle/marine_dropship.dm
  code/modules/tgui_panel/external.dm
  interface/fonts/easvhs.dm
  interface/fonts/easvhs.ttf
  interface/fonts/f25_bank.dm
  interface/fonts/f25_bank.ttf
  interface/fonts/license.txt
  interface/skin.dmf
  tgmc.dme
  tgui/.eslintignore
  tgui/packages/tgui-panel/index.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Code Improvement, Fix, Feature, Requires Testing, UI, Quality of Life

#17065 Makes the platforms on gelida non dense
  _maps/map_files/gelida_iv/gelida_iv.dmm
Labels: Map Edit, Quality of Life

#17000 Beam visual fix
  code/datums/beam.dm
Labels: Fix

#17072 Allows fireman carried people to be laid on surgery tables
  code/datums/elements/riding.dm
  code/game/objects/machinery/OpTable.dm
Labels: Quality of Life

#17063 OB sound fix
  code/game/objects/structures/orbital_cannon.dm
Labels: Fix

#17070 Allows combat robots to wear mimir
  code/modules/clothing/modular_armor/combat_robot.dm
Labels: Balance

#17038 TAD launch no longer end xeno prep phase / only landing does
  _maps/map_files/kutjevo/kutjevo.dmm
  code/__DEFINES/dcs/signals/signals.dm
  code/controllers/subsystem/processing/resinshaping.dm
  code/game/area/kutjevo.dm
  code/game/objects/structures/rappel_system.dm
  code/modules/mob/living/carbon/xenomorph/abilities.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/shuttle/mini_dropship.dm
Labels: Balance, Fix

#17057 Laser Rifle and MG lose rail scope
  code/modules/projectiles/guns/energy.dm
Labels: Balance

#17084 New Lobby Art from Astolfo!
  icons/misc/lobby_art/macxeno.dmi
Labels: Sprites

#17068 Buff standard tad cockpit/window health
  code/modules/shuttle/marine_dropship.dm
Labels: Balance

#17091 Laser sentry range fix
  code/modules/projectiles/guns/sentries.dm
Labels: Fix

#17090 Fix Ravager charge issue
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
Labels: Fix

#17093 Detpack signal fix
  code/game/objects/items/radio/detpack.dm
Labels: Fix

#17094 Overwatch grammar fix
  code/game/objects/machinery/overwatch/military.dm
Labels: Grammar and Formatting

#17080 Adds electrical insulation to Officer Gloves.
  code/modules/clothing/gloves/marine_gloves.dm
Labels: Balance

#17078 Allows squad leaders to take a radiopack as a backpack option
  code/__DEFINES/loadout.dm
Labels: Balance

#17105 Add public address config option
  code/controllers/configuration/entries/general.dm
  code/datums/world_topic.dm
  code/modules/admin/verbs/chat_commands.dm
Labels: Config Update

#17101 Ports tg action for pinging non-org codeowners
  .github/workflows/codeowner_reviews.yml
Labels: GitHub

#17099 Remove deprecated config option
  code/controllers/configuration/entries/game_options.dm
  config/config.txt
Labels: Config Update, Removal

#16953 Adds Globadier, a new spitter strain
  code/__DEFINES/action.dm
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__HELPERS/ai.dm
  code/_globalvars/lists/mobs.dm
  code/datums/keybinding/xeno.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/explosives/grenades/incendiary_grenades.dm
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/spitter.dm
  code/modules/mob/living/carbon/xenomorph/xenoupgrade.dm
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
  code/modules/projectiles/guns/flamer.dm
  icons/Xeno/actions/spitter.dmi
  icons/Xeno/castes/spitter.dmi
  icons/obj/items/mines.dmi
  icons/obj/items/projectiles.dmi
  sound/effects/kaboom.ogg
Labels: Sprites, Feature

#17028 Dancer Overhaul & Buff
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/status_effects.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/xeno_buffs.dm
  code/game/data_huds.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  icons/Xeno/actions/praetorian.dmi
  icons/effects/128x128.dmi
  icons/effects/96x96.dmi
  icons/mob/hud/human.dmi
Labels: Sprites, Balance, Feature

#17081 Makes the stun type names consistent code wise
  code/__DEFINES/mobs.dm
  code/datums/components/stun_mitigation.dm
  code/game/objects/items/defibrillator.dm
  code/game/objects/items/explosives/grenades/flashbang.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/carbon/human/species_types/synthetics.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/abilities_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/ammo_datums.dm
  code/modules/projectiles/ammo_types/energy_ammo.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/mech_ammo.dm
  code/modules/projectiles/ammo_types/revolver_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/projectiles/ammo_types/shotgun_ammo.dm
  code/modules/projectiles/ammo_types/smartgun_ammo.dm
  code/modules/projectiles/ammo_types/xenos/widow_xenoammo.dm
  code/modules/reagents/chemistry/reagents/food.dm
  code/modules/reagents/chemistry/reagents/other.dm
  code/modules/reagents/chemistry/reagents/toxin.dm
  code/modules/reagents/reagent_containers/cups/bottle.dm
Labels: Code Improvement, Test Merge Candidate

#17096 Everyone except spatial agents can only spawn mechs once
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/traits.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
Labels: Balance, Fix

#17031 Updating PoS medbay
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Map Edit, Feature, Test Merge Candidate

#17122 No more ????? in item examine
  code/__HELPERS/unsorted.dm
Labels: Grammar and Formatting

#17117 Stagger fixes
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
Labels: Fix

#17118 Increases command message length to 200 characters from 120 and 100
  code/game/objects/machinery/overwatch/_overwatch.dm
  code/modules/screen_alert/command_alert.dm
Labels: Grammar and Formatting

#17113 Mech explosion fix
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Labels: Fix

#17079 Adds *trick emote, allowing you to do_trick() (revolver trick) on items.
  code/__DEFINES/emote.dm
  code/datums/emotes.dm
  code/game/objects/items/weapons/blades.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/projectiles/guns/revolvers.dm
Labels: Feature

#17121 Change keybind names to the actual strains, rather than the parent caste
  code/datums/keybinding/xeno.dm
Labels: Quality of Life

#17127 Adds standard deck of cards to marine vendor/customization
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/client/preferences_gear.dm
Labels: Feature

#17125 Mech skill fix
  code/datums/skills.dm
Labels: Fix

#17098 Mech movement fixes and changes
  code/__DEFINES/dcs/signals/signals.dm
  code/modules/keybindings/bindings_atom.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/mecha_mob_interaction.dm
  code/modules/vehicles/mecha/mecha_movement.dm
Labels: Balance, Fix

#17097 removes mech directional armor
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Labels: Removal, Balance

#16983 Tank driver periscope fix
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/armored_actions.dm
  code/modules/vehicles/armored/interiors/chairs.dm
  code/modules/vehicles/armored/interiors/periscope.dm
  code/modules/vehicles/armored/som_tank.dm
Labels: Balance, Fix, In Game Exploit

#17109 Remove all references to tgs3
  .dockerignore
  code/__DEFINES/tgs.config.dm
  code/controllers/subsystem/ticker.dm
  code/modules/admin/server_verbs.dm
  tools/tgs4_scripts/PreCompile.bat
Labels: Removal

#17108 teleport verb menu is tgui now
  code/modules/mob/dead/observer/observer.dm
Labels: Quality of Life

#17128 Behemoth no longer has heavy footstep sounds.
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/behemoth.dm
Labels: Balance

#17129 XOB and xortar fire now alerts ghosts like marine OBs do
  code/modules/xenomorph/maw.dm
Labels: Quality of Life

#17111 Various Detpack QoL
  code/game/objects/items/radio/detpack.dm
  code/modules/assembly/signaler.dm
Labels: Balance, Quality of Life

#17124 Area by z dup fix
  code/game/area/area.dm
Labels: Code Improvement

#17123 Critical rock change
  code/game/objects/structures/rocks.dm
Labels: Quality of Life

#17133 Another lobby art from Zaha!
  icons/misc/lobby_art/zahabromance.dmi
Labels: Sprites

#17119 Adds a delay to tank firing after turning its turret
  code/modules/vehicles/armored/__armored.dm
Labels: Balance

#17135 notify_ghosts now only flashes the window for stuff related to round re-entry
  code/game/objects/machinery/cloning/cloning.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/living.dm
  code/modules/mob/mob_helpers.dm
Labels: Refactor, Quality of Life

#17059 Buffs standard SMGs overall
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/misc.dm
  code/modules/projectiles/magazines/smgs.dm
Labels: Balance

#17130 Nerfs laser sentry range by 1 tile
  code/modules/projectiles/guns/sentries.dm
Labels: Balance

#17145 Default climb delay change
  code/game/objects/structures.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/platforms.dm
Labels: Balance

#17144 let medical rig hold tweezers and ESR-12
  code/datums/storage/subtypes/belt.dm
Labels: Balance

#17149 Removes Russian Red from ground maps
  _maps/map_files/desertdam/desertdam.dmm
  _maps/map_files/riptide/riptide.dmm
  _maps/modularmaps/corsatdome/corsatdomeicecolony.dmm
Labels: Removal, Balance, Map Edit

#17137 Smart target rifle changes
  code/modules/projectiles/ammo_types/smartgun_ammo.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Balance

#17095 Crates falling from the sky now instead of teleporting
  code/game/objects/machinery/squad_supply/supply_console.dm
  icons/effects/32x64.dmi
  icons/effects/64x64.dmi
Labels: Quality of Life

#17126 Reworks breach/demolition modes for detpack
  code/game/objects/items/radio/detpack.dm
Labels: Balance

#17154 Auto Capitalize mugshot announcements
  code/game/objects/machinery/overwatch/military.dm
  code/modules/screen_alert/command_alert.dm
Labels: Quality of Life

#17066 Pyrogen Rework
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/mobs.dm
  code/datums/keybinding/xeno.dm
  code/datums/status_effects/debuffs.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/projectiles/ammo_types/xenos/pyrogen_xenoammo.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
  icons/Xeno/actions/pyrogen.dmi
Labels: Sprites, Balance, Fix, Feature

#17156 Ezdb
  .github/guides/EZDB.md
  .gitignore
  CONTRIBUTING.md
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/dbconfig.dm
  code/controllers/subsystem/dbcore.dm
  tools/ezdb/__main__.py
  tools/ezdb/ezdb.bat
  tools/ezdb/ezdb/__init__.py
  tools/ezdb/ezdb/changes.py
  tools/ezdb/ezdb/config.py
  tools/ezdb/ezdb/mysql.py
  tools/ezdb/ezdb/paths.py
  tools/ezdb/steps/__init__.py
  tools/ezdb/steps/download_mariadb.py
  tools/ezdb/steps/install_database.py
  tools/ezdb/steps/install_initial_schema.py
  tools/ezdb/steps/step.py
  tools/ezdb/steps/update_schema.py
  tools/requirements.txt
Labels: Code Improvement, GitHub

#17157 Fix undeleted query in tutorial code
  code/controllers/subsystem/tutorials.dm
Labels: Removal, Fix

#17158 Optimizes icon exists, and makes a bunch of iconstates situations use it
  code/__HELPERS/icons.dm
  code/_onclick/hud/parallax.dm
  code/datums/greyscale/layer.dm
  code/modules/asset_cache/assets/crafting.dm
  code/modules/mob/living/silicon/ai/death.dm
Labels: Code Improvement

#17049 Add 2 new cade types
  _maps/map_files/Arachne/TGS_Arachne.dmm
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Campaign maps/nt_base/nt_base.dmm
  _maps/map_files/Campaign maps/orion_2/orionoutpost_2.dmm
  _maps/map_files/Campaign maps/som_base/sombase.dmm
  _maps/map_files/Campaign maps/tgmc_raid_base/tgmc_raiding_base.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/LV759/LV759.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Metnal_Operation/Metnal_Operation.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/kutjevo/kutjevo.dmm
  _maps/map_files/lavaoutpost/LavaOutpost.dmm
  _maps/map_files/oscar_outpost/oscar_outpost.dmm
  _maps/map_files/riptide/riptide.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/big_red/bigredetavar5.dmm
  _maps/modularmaps/big_red/bigredmedbayvar6.dmm
  _maps/modularmaps/lv624/newcavevar11.dmm
  _maps/modularmaps/lv624/robotics.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar2.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar3.dmm
  _maps/modularmaps/oscaroutpost/oscarnorthvar4.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar1.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar2.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar3.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar4.dmm
  _maps/modularmaps/oscaroutpost/oscarsouthvar5.dmm
  _maps/shuttles/distress.dmm
  _maps/shuttles/distress_pmc.dmm
  _maps/shuttles/distress_ufo.dmm
  _maps/shuttles/distress_upp.dmm
  _maps/shuttles/minidropship_mobile_bar.dmm
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/datums/components/remote_control.dm
  code/game/objects/items/quickdeploy_cade.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/campaign_structures/misc_structures.dm
  code/modules/mapping/mapping_helpers.dm
  code/modules/remote_fob/actions_misc.dm
  code/modules/vehicles/armored/vehicle_collision.dm
  icons/obj/structures/barricades/metal.dmi
  icons/obj/structures/barricades/plasteel.dmi
Labels: Map Edit, Feature, Test Merge Candidate

#17161 Mech has night vision
  code/modules/mob/living/carbon/carbon.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Labels: Balance

#17162 Non-HvH mechs now spin to fire
  code/__DEFINES/mecha.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Balance

#17100 Addressing some tesla turret complaints
  code/__DEFINES/loadout.dm
  code/datums/components/deployable_item.dm
  code/datums/status_effects/debuffs.dm
  code/game/objects/machinery/tesla_turret.dm
  code/game/objects/objs.dm
  code/modules/reqs/supplypacks.dm
  icons/obj/machines/deployable/sentry/tesla.dmi
Labels: Balance, Fix, Feature, Administration, In Game Exploit

#17163 forgot one of the ghost notifications
  code/modules/mob/mob_helpers.dm
Labels: Fix

#16723 Adds a status effect to try to mitigate sniper stacking
  code/__DEFINES/conflict.dm
  code/__DEFINES/status_effects.dm
  code/_globalvars/bitfields.dm
  code/datums/status_effects/debuffs.dm
  code/datums/status_effects/status_effect.dm
  code/modules/mob/living/status_procs.dm
  code/modules/projectiles/ammo_types/ags_ammo.dm
  code/modules/projectiles/ammo_types/energy_ammo.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/mech_ammo.dm
  code/modules/projectiles/ammo_types/rifle_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
  code/modules/projectiles/ammo_types/sniper_ammo.dm
  code/modules/projectiles/ammo_types/tx54_ammo.dm
  code/modules/projectiles/ammo_types/xenos/energy_xenoammo.dm
  code/modules/projectiles/projectile.dm
Labels: Balance

#17150 Kills cringe reagent healing
  code/modules/reagents/chemistry/reagents/drinks/drink_reagents.dm
  code/modules/reagents/chemistry/reagents/food.dm
Labels: Balance

#17169 Spear fix
  code/_onclick/click.dm
Labels: Fix

#17177 Detpack fix
  code/game/objects/items/radio/detpack.dm
Labels: Fix

#17174 Storage datum fixes
  code/datums/storage/storage.dm
  code/datums/storage/subtypes/internal.dm
  code/game/objects/items/storage/holsters.dm
Labels: Fix

#17152 Rehydrating Marine Guns (Hydrocannon attachment)
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Feature

#17178 Req consoles now display a supply pack's notes
  code/controllers/subsystem/points.dm
  tgui/packages/tgui/interfaces/Cargo.jsx
Labels: Quality of Life

#17179 Adjusts chemmaster skill requirement
  code/modules/reagents/chemistry/machinery/chem_master.dm
Labels: Fix

#17104 Sticky quick equip slots.
  code/__DEFINES/equipment.dm
  code/game/objects/items.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Stale, Quality of Life

#17180 Removes lisp from tracker shell order
  code/modules/reqs/supplypacks.dm
Labels: Removal, Grammar and Formatting

#17165 Starting weeds are now majority sticky.
  code/__DEFINES/xeno.dm
Labels: Balance, Test Merge Candidate, Quality of Life

#17185 Reverts the SG-62 buffs
  code/modules/projectiles/ammo_types/smartgun_ammo.dm
  code/modules/projectiles/guns/rifles.dm
Labels: Balance

#17173 ANOTHER Zaha lobby art
  icons/misc/lobby_art/absolutewowza.dmi
Labels: Sprites

#17167 Adds a mech limb damage system
  code/__DEFINES/dcs/signals/signals.dm
  code/game/objects/obj_defense.dm
  code/game/objects/objs.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Balance

#17009 Guts bad parts of wraith
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Whiskey_Outpost/Whiskey_Outpost_v2.dmm
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/obj_flags.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/bitfields.dm
  code/datums/keybinding/xeno.dm
  code/datums/round_statistics.dm
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/game/objects/objs.dm
  code/game/objects/structures/rappel_system.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/abilities_wraith.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/xenomorph/tunnel.dm
Labels: Removal, Map Edit

#17184 Traverse line proc
  code/__HELPERS/math.dm
  code/__HELPERS/unsorted.dm
  code/datums/fire_support/gun_run.dm
  code/game/objects/structures/dropship_ammo.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/abilities_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/abilities_spitter.dm
  code/modules/mob/living/simple_animal/hostile/hostile.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/projectiles/sentries.dm
  code/modules/vehicles/armored/som_armored_weapons.dm
  code/modules/xenomorph/xeno_turret.dm
Labels: Code Improvement

#17171 Faction var at AM level
  code/game/atoms/atom_movable.dm
  code/game/objects/effects/landmarks/gamemode/campaign_reward_spawns.dm
  code/game/objects/effects/landmarks/gamemode/campaign_vehicle_spawners.dm
  code/game/objects/effects/landmarks/gamemode/hvh_deploy_points.dm
  code/game/objects/items/firesupport_binoculars.dm
  code/game/objects/items/marine_gear.dm
  code/game/objects/items/plantable_flags.dm
  code/game/objects/items/radio/headset.dm
  code/game/objects/machinery/computer/crew.dm
  code/game/objects/machinery/computer/intel_computer.dm
  code/game/objects/machinery/computer/marines_consoles.dm
  code/game/objects/machinery/doors/poddoor.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/machinery/overwatch/_overwatch.dm
  code/game/objects/machinery/squad_supply/supply_console.dm
  code/game/objects/machinery/squad_supply/supply_pads.dm
  code/game/objects/machinery/vending/loadout_vendor.dm
  code/game/objects/machinery/vending/new_marine_vendors.dm
  code/game/objects/machinery/vending/quick_vendor.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/campaign_structures/deploy_blockers.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  code/game/objects/structures/sensor_tower.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/teleporter_array.dm
  code/modules/mob/mob_defines.dm
  code/modules/reqs/supply.dm
  code/modules/vehicles/sealed.dm
  code/modules/vehicles/unmanned/unmanned_vehicle.dm
Labels: Code Improvement

#17043 Enhanced Mentor OOC Listening
  code/game/verbs/ooc.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Administration

#17196 [s] Valhalla drains no longer add burrowed larva points to the actual hive
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Fix

#17160 APC changes
  code/modules/vehicles/armored/apc.dm
Labels: Balance, Test Merge Candidate

#17182 Mech can now be shuffled by xenos
  code/game/verbs/ooc.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
Labels: Balance

#17183 Mech movement rework
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/gygax.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Labels: Balance, Fix

#17197 Combat robot corpsman beginner loadouts now spawn with medevac beacons
  code/datums/outfits/quick_load_robots.dm
  code/modules/paperwork/beginner_tutorials.dm
Labels: Fix

#17146 Tank Soundscape V2
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/looping_sounds/tank.dm
  code/game/sound.dm
  code/modules/vehicles/_hitbox.dm
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/armored_actions.dm
  code/modules/vehicles/armored/armored_weapons.dm
  code/modules/vehicles/armored/icc_armored_weapons.dm
  code/modules/vehicles/armored/som_armored_weapons.dm
  code/modules/vehicles/armored/som_tank.dm
  sound/vehicles/hover_tank/hover_1.ogg
  sound/vehicles/hover_tank/hover_2.ogg
  sound/vehicles/hover_tank/hover_3.ogg
  sound/vehicles/hover_tank/hover_4.ogg
  sound/vehicles/hover_tank/hover_interior_1.ogg
  sound/vehicles/hover_tank/hover_interior_2.ogg
  sound/vehicles/hover_tank/hover_interior_3.ogg
  sound/vehicles/hover_tank/hover_interior_4.ogg
  sound/vehicles/hover_tank/idle_1.ogg
  sound/vehicles/hover_tank/idle_interior_1.ogg
  sound/vehicles/hover_tank/idle_interior_2.ogg
  sound/vehicles/looping/engine_rev_1.ogg
  sound/vehicles/looping/engine_rev_2.ogg
  sound/vehicles/looping/tank_eng_idle_1.ogg
  sound/vehicles/looping/tank_eng_idle_2.ogg
  sound/vehicles/looping/tank_eng_idle_3.ogg
  sound/vehicles/looping/tank_eng_idle_4.ogg
  sound/vehicles/looping/tank_eng_interior_idle_1.ogg
  sound/vehicles/looping/tank_eng_interior_idle_2.ogg
  sound/vehicles/looping/tank_eng_interior_loop_1.ogg
  sound/vehicles/looping/tank_eng_interior_loop_2.ogg
  sound/vehicles/looping/tank_eng_interior_loop_3.ogg
  sound/vehicles/looping/tank_eng_interior_start.ogg
  sound/vehicles/looping/tank_eng_interior_stop.ogg
  sound/vehicles/looping/tank_eng_start.ogg
  sound/vehicles/looping/tank_eng_stop.ogg
  sound/vehicles/looping/tanks_eng_interior_start.ogg
  sound/vehicles/looping/tanks_eng_interior_stop.ogg
  sound/vehicles/looping/tanks_eng_start.ogg
  sound/vehicles/tankswivel.ogg
  sound/vehicles/turret_swivel_interior.ogg
  sound/vehicles/weapons/coilgun_fire_interior.ogg
  sound/vehicles/weapons/ltb_fire_interior.ogg
  sound/vehicles/weapons/mlrs_fire.ogg
  sound/vehicles/weapons/mlrs_interior.ogg
  sound/vehicles/weapons/particle_fire_interior.ogg
  sound/vehicles/weapons/volkite_fire_interior.ogg
  tgmc.dme
Labels: Quality of Life

#17187 Added subheaders Toggles and Follow to spectators.
  code/modules/mob/dead/observer/observer.dm
Labels: Quality of Life

#17148 Security level refactor, also GLOB.marine_main_ship is dead
  code/__DEFINES/__game.dm
  code/__DEFINES/_subsystems.dm
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/security_level.dm
  code/__HELPERS/announce.dm
  code/_globalvars/bitfields.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_onclick/ai.dm
  code/controllers/subsystem/evacuation.dm
  code/controllers/subsystem/security_level.dm
  code/datums/marine_main_ship.dm
  code/datums/world_topic.dm
  code/game/objects/effects/misc.dm
  code/game/objects/items/binoculars.dm
  code/game/objects/machinery/computer/communications.dm
  code/game/objects/machinery/doors/shutters.dm
  code/game/objects/machinery/fire_alarm.dm
  code/game/objects/machinery/overwatch/military.dm
  code/game/objects/machinery/status_display.dm
  code/game/objects/structures/orbital_cannon.dm
  code/modules/admin/fun_verbs.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/power/lighting.dm
  code/modules/security_levels/keycard_authentication.dm
  code/modules/security_levels/security_level_datums.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/security_levels.dm
  tgmc.dme
Labels: Refactor

#17192 Mech Energy, repair packs and weight mechanics
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/datums/keybinding/mecha.dm
  code/game/objects/items/power_cells.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/reqs/supplypacks.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_constructor.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
  code/modules/vehicles/mecha/equipment/mecha_equipment.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
  code/modules/vehicles/mecha/equipment/tools/other_tools.dm
  code/modules/vehicles/mecha/mecha_actions.dm
  code/modules/vehicles/mecha/mecha_defense.dm
  tgui/packages/tgui/interfaces/MechVendor/data.ts
  tgui/packages/tgui/interfaces/MechVendor/index.tsx
Labels: Feature

#17134 fixes scorpion autofire getting stuck shooting
  code/modules/mob/living/carbon/xenomorph/abilities.dm
Labels: Stale, Fix

#17189 Mech jump
  code/__DEFINES/mecha.dm
  code/datums/components/jump.dm
  code/modules/vehicles/__vehicle.dm
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/gygax.dm
  code/modules/vehicles/mecha/combat/savannah_ivanov.dm
  code/modules/vehicles/mecha/mecha_movement.dm
Labels: Feature

#17206 Does mech balance numbers
  code/game/objects/items/power_cells.dm
  code/modules/projectiles/ammo_types/mech_ammo.dm
  code/modules/projectiles/ammo_types/miscellaneous_ammo.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
  code/modules/vehicles/mecha/equipment/weapons/greyscale_weapons.dm
Labels: Balance

#17215 New armor lock effect icon
  code/modules/clothing/modular_armor/attachments/modules.dm
  icons/effects/effects.dmi
Labels: Sprites

#17213 Increases Tank and APC bio armor to 100. (Increases tank hard bio armour by 20)
  code/modules/vehicles/armored/_multitile.dm
  code/modules/vehicles/armored/apc.dm
Labels: Balance

#17143 Additional buttons to ghost hud
  code/__DEFINES/hud.dm
  code/_onclick/hud/ghost.dm
  icons/mob/screen_ghost.dmi
Labels: Stale, Feature

#17214 Minor clean-up of xeno vars
  code/__DEFINES/combat.dm
  code/modules/mob/living/carbon/xenomorph/attack_alien.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/king.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/warrior.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
  code/modules/mob/living/simple_animal/simple_animal.dm
Labels: Code Improvement

#17208 Fix engine turn off sounds
  code/modules/vehicles/armored/__armored.dm
  sound/vehicles/looping/tanks_eng_interior_start.ogg
  sound/vehicles/looping/tanks_eng_interior_stop.ogg
  sound/vehicles/looping/tanks_eng_start.ogg
Labels: Fix

#17209 Fix admin smite logs
  code/modules/admin/admin_verbs.dm
Labels: Fix, Logging

#17210 Fix admin shuttle stuff
  code/controllers/subsystem/shuttle.dm
  code/modules/admin/verbs/map_template.dm
  tgui/packages/tgui/interfaces/ShuttleManipulator.jsx
Labels: Fix

#17211 Adds !tgs seasonals
  code/modules/admin/verbs/chat_commands.dm
Labels: Feature

#17216 Readds discord PR announcer
  .github/workflows/discord_pr_announce.yml
Labels: Code Improvement, GitHub

#17217 Minor improvement to mech weight bar
  tgui/packages/tgui/interfaces/MechVendor/index.tsx
Labels: Fix, UI

#17219 New MC profiling and debugging tools
  code/__DEFINES/MC.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/modules/unit_tests/subsystem_init.dm
  tgui/packages/tgui/interfaces/ControllerOverview/OverviewSection.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/SubsystemDialog.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/SubsystemRow.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/SubsystemViews.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/contants.ts
  tgui/packages/tgui/interfaces/ControllerOverview/filters.ts
  tgui/packages/tgui/interfaces/ControllerOverview/index.tsx
  tgui/packages/tgui/interfaces/ControllerOverview/types.ts
Labels: Code Improvement, Administration

#17218 Add edge debug tools
  code/modules/admin/debug_verbs.dm
Labels: Administration

#17205 Fixes some mech spin-firing stuff
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Fix

#17229 Fix mech sprint numbers
  code/modules/vehicles/mecha/_mecha.dm
  code/modules/vehicles/mecha/combat/greyscale/greyscale_limbs.dm
  code/modules/vehicles/mecha/combat/gygax.dm
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Labels: Fix

#17186 Human mob AI
  code/__DEFINES/ai.dm
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/mobs.dm
  code/__HELPERS/ai.dm
  code/controllers/subsystem/advanced_pathfinding.dm
  code/datums/actions/order_action.dm
  code/datums/actions/orders.dm
  code/datums/actions/weapon_actions.dm
  code/datums/components/ai.dm
  code/datums/components/jump.dm
  code/datums/elements/strappable.dm
  code/datums/managed_inventory.dm
  code/datums/storage/storage.dm
  code/game/objects/items.dm
  code/game/objects/items/blink_drive.dm
  code/game/objects/items/explosives/bombvest.dm
  code/game/objects/items/explosives/grenades/grenade.dm
  code/game/objects/items/jetpack.dm
  code/game/objects/items/stacks/medical.dm
  code/game/objects/items/weapons/energy.dm
  code/game/objects/items/weapons/harvester.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/swords.dm
  code/game/objects/items/weapons/twohanded.dm
  code/game/objects/items/weapons/weapon.dm
  code/modules/admin/fun_verbs.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/human_mobs/grenades.dm
  code/modules/ai/ai_behaviors/human_mobs/hazard_avoidance.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
  code/modules/ai/ai_behaviors/human_mobs/self_heal.dm
  code/modules/ai/ai_behaviors/human_mobs/weapon_module.dm
  code/modules/ai/ai_behaviors/xeno/puppet.dm
  code/modules/ai/ai_behaviors/xeno/xeno.dm
  code/modules/ai/ai_behaviors/xeno/xeno_illusion.dm
  code/modules/ai/ai_node.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
  code/modules/mob/mob.dm
  code/modules/projectiles/gun_attachables/muzzle.dm
  code/modules/projectiles/gun_helpers.dm
  code/modules/projectiles/gun_system.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
  code/modules/projectiles/guns/flamer.dm
  code/modules/vehicles/unmanned/unmanned_droid.dm
  tgmc.dme
Labels: Code Improvement, Feature, Requires Testing

#16889 Thermo-Bluespace Generator (groundside gens rework)
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Bluesummers/bluesummers.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/LV759/LV759.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Metnal_Operation/Metnal_Operation.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/corsat/corsat.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/map_files/kutjevo/kutjevo.dmm
  _maps/map_files/lavaoutpost/LavaOutpost.dmm
  _maps/map_files/riptide/riptide.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/big_red/bigredengineeringvar1.dmm
  _maps/modularmaps/big_red/bigredengineeringvar2.dmm
  _maps/modularmaps/big_red/bigredengineeringvar3.dmm
  _maps/modularmaps/big_red/bigredengineeringvar4.dmm
  code/__DEFINES/dcs/signals/signals.dm
  code/controllers/subsystem/evacuation.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/area/icecolony.dm
  code/game/area/prison.dm
  code/game/objects/machinery/computer/nuke_disk_generator.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/power/lighting.dm
  icons/UI_Icons/map_blips.dmi
  icons/obj/machines/tbg.dmi
  sound/machines/generator/tbg_alarm.ogg
  sound/machines/generator/tbg_mid1.ogg
  sound/machines/generator/tbg_mid2.ogg
  sound/machines/generator/tbg_mid3.ogg
  sound/machines/generator/tbg_mid4.ogg
  sound/machines/generator/tbg_mid5.ogg
  sound/machines/generator/tbg_winddown.ogg
  sound/machines/generator/tbg_windup.ogg
  tgui/packages/tgui/interfaces/NukeDiskGenerator.jsx
Labels: Sprites, Sound, Map Edit, Feature, UI

#17034 Re-educates marines on safe dietary practices.
  code/modules/reagents/reagent_containers/food/snacks.dm
Labels: Stale, Fix, Feature

#17224 Mech booster numbers change
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Labels: Balance

#17103 Clickdrag toggle keybind
  code/__DEFINES/dcs/signals/signals_keybindings.dm
  code/__DEFINES/preferences.dm
  code/_globalvars/bitfields.dm
  code/_onclick/drag_drop.dm
  code/datums/keybinding/mob.dm
  code/modules/client/preferences_ui.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/GameSettings.tsx
Labels: Stale, Feature

#17048 2025 tip update!
  strings/tips/marine.txt
  strings/tips/meme.txt
  strings/tips/xeno.txt
Labels: Grammar and Formatting

#17223 Fix reload admins
  code/modules/admin/server_verbs.dm
Labels: Fix

#17227 Fix mech sprint icon
  code/modules/vehicles/mecha/combat/gygax.dm
Labels: Fix

#17232 mech take fire damage
  code/modules/vehicles/mecha/combat/greyscale/greyscale.dm
Labels: Balance

#17234 Fixes not all mech items respecting arms being blown off
  code/modules/vehicles/mecha/equipment/mecha_equipment.dm
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Fix

#17237 Fix get mob not working on cryod mobs
  code/modules/admin/admin_verbs.dm
Labels: Fix

#17241 Remove melee core speed boost
  code/modules/vehicles/mecha/equipment/tools/greyscale_tools.dm
Labels: Removal, Balance

#17242 Mech can now reload on the move
  code/modules/vehicles/mecha/equipment/weapons/weapons.dm
Labels: Balance

#17243 Add reload-config admin verb
  code/controllers/configuration/configuration.dm
  code/modules/admin/server_verbs.dm
Labels: Administration

#17225 Prevents hijacking the alamo when its already shipside
  code/modules/shuttle/marine_dropship.dm
Labels: Fix
