Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2025-08, with the labels that each got.

#18076 Removes bluespace generator
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
  _maps/map_files/Bluesummers/bluesummers.dmm
  _maps/map_files/DaedalusPrison/DaedalusPrison.dmm
  _maps/map_files/Ice_Colony_v2/Ice_Colony_v2.dmm
  _maps/map_files/LV624/LV624.dmm
  _maps/map_files/LV759/LV759.dmm
  _maps/map_files/Lawanka_Outpost/LawankaOutpost.dmm
  _maps/map_files/Magmoor_Digsite_IV/Magmoor_Digsite_IV.dmm
  _maps/map_files/Metnal_Operation/Metnal_Operation.dmm
  _maps/map_files/Orion_Military_Outpost/orionoutpost.dmm
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  _maps/map_files/Research_Outpost/Research_Outpost.dmm
  _maps/map_files/corsat/corsat.dmm
  _maps/map_files/deltastation/deltastation.dmm
  _maps/map_files/desparity/desparity.dmm
  _maps/map_files/fiorina/fiorina.dmm
  _maps/map_files/gelida_iv/gelida_iv.dmm
  _maps/map_files/generic/Admin_Level.dmm
  _maps/map_files/icy_caves/icy_caves.dmm
  _maps/map_files/kutjevo/kutjevo.dmm
  _maps/map_files/lavaoutpost/LavaOutpost.dmm
  _maps/map_files/riptide/riptide.dmm
  _maps/map_files/slumbridge/slumbridge.dmm
  _maps/modularmaps/big_red/bigredatmosvar1.dmm
  _maps/modularmaps/big_red/bigredatmosvar2.dmm
  _maps/modularmaps/big_red/bigredatmosvar3.dmm
  _maps/modularmaps/big_red/bigredatmosvar4.dmm
  _maps/modularmaps/big_red/bigredatmosvar5.dmm
  _maps/modularmaps/big_red/bigredatmosvar6.dmm
  code/__DEFINES/dcs/signals/signals.dm
  code/controllers/subsystem/evacuation.dm
  code/datums/gamemodes/infestation.dm
  code/datums/looping_sounds/machinery_sounds.dm
  code/game/area/icecolony.dm
  code/game/objects/machinery/computer/nuke_disk_generator.dm
  code/modules/power/groundmap_geothermal.dm
  code/modules/power/lighting.dm
  icons/UI_Icons/map_blips.dmi
  icons/obj/machines/tbg.dmi
  sound/machines/generator/tbg_alarm.ogg
  sound/machines/generator/tbg_mid1.ogg
  sound/machines/generator/tbg_mid2.ogg
  sound/machines/generator/tbg_mid3.ogg
  sound/machines/generator/tbg_mid4.ogg
  sound/machines/generator/tbg_mid5.ogg
  sound/machines/generator/tbg_winddown.ogg
  sound/machines/generator/tbg_windup.ogg
  tgui/packages/tgui/interfaces/NukeDiskGenerator.tsx
Labels: Removal, Map Edit

#18169 Mutations: Shrike
  code/game/atoms/_atom.dm
  code/game/objects/structures/window.dm
  code/game/turfs/closed.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_conqueror.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/abilities_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/mutations_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/mob/living/carbon/xenomorph/xenoprocs.dm
  code/modules/mob/living/living_defense.dm
  tgmc.dme
Labels: Feature

#18168 Mutations: Oppressor
  code/__DEFINES/movespeed_modification.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/mutations_oppressor.dm
  tgmc.dme
Labels: Feature

#18180 Destroy mission tweaks
  code/datums/gamemodes/campaign/missions/destroy_mission.dm
Labels: Balance

#18167 Campaign Loadout UI fix
  tgui/packages/tgui/interfaces/IndividualStats/index.tsx
Labels: Fix, UI

#18182 Moved around two vendors (and the shower) in canter medical
  _maps/shuttles/tgs_canterbury.dmm
Labels: Map Edit, Quality of Life

#18148 Add automated loadout vendors in specialist and leader rooms on sulaco
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
Labels: Map Edit, Feature

#18183 Canter medvendors rearrange (UPDATE - re added light fixture)
  _maps/shuttles/tgs_canterbury.dmm
Labels: Fix, Map Edit

#18187 Fixes vapor processing area
  _maps/map_files/Vapor_Processing/Vapor_Processing.dmm
Labels: Fix, Map Edit

#18198 Vent crawling logging
  code/_onclick/ventcrawl.dm
  code/modules/atmospherics/machinery/atmosmachinery.dm
Labels: Administration, Logging

#18184 Removes xeno respawn timer
  code/__DEFINES/mode.dm
  code/_globalvars/misc.dm
  code/datums/actions/observer_action.dm
  code/datums/gamemodes/_game_mode.dm
  code/datums/gamemodes/crash.dm
  code/datums/gamemodes/extended.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/xenomorph/death.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
Labels: Removal, Balance

#18207 Slight conqueror rebalance
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_conqueror.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
Labels: Balance

#18209 Fixes Mutation Typos
  code/modules/mob/living/carbon/xenomorph/castes/boiler/mutations_sizzler.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/mutations_conqueror.dm
Labels: Grammar and Formatting

#18090 Adds a new lowpop map: Blue Moon
  _maps/_basemap.dm
  _maps/bluemoon.json
  _maps/map_files/Blue_Moon/bluemoon.dmm
  code/game/area/bluemoon.dm
  code/game/objects/structures/landing_signs.dm
  config/maps.txt
  icons/obj/landing_signs.dmi
  tgmc.dme
Labels: Map Edit, Feature

#18215 Recipes not appearing fix
  code/game/objects/items/stacks/sheets/glass.dm
  code/game/objects/items/stacks/sheets/mineral.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
Labels: Fix

#18219 Acid cade fix
  code/game/objects/structures/barricade.dm
Labels: Fix

#18221 Fixes infinitely stacking barricade armor upgrades
  code/game/objects/structures/barricade.dm
Labels: Fix

#18217 removes the ability to build MAW
  code/modules/mob/living/carbon/xenomorph/hive_upgrades.dm
Labels: Removal, Balance

#18222 Moves nuke building a little closer to center of the map on Blue Moon
  _maps/map_files/Blue_Moon/bluemoon.dmm
Labels: Balance, Map Edit
