Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2025-05, with the labels that each got.

#17777 Adds mech pods on sulaco and theseus
  _maps/map_files/Sulaco/TGS_Sulaco.dmm
  _maps/map_files/Theseus/TGS_Theseus.dmm
Labels: Map Edit, Feature

#17721 Small POS Fix
  _maps/map_files/Pillar_of_Spring/TGS_Pillar_of_Spring.dmm
Labels: Fix, Map Edit

#17716 Moves bsg on big red further into engineering
  _maps/map_files/BigRed_v2/BigRed_v2.dmm
Labels: Balance, Map Edit

#17628 Tadpole Panoptical Model
  _maps/shuttles/minidropship_panopticon.dmm
  code/datums/shuttles.dm
  code/game/objects/machinery/computer/dropship_picker.dm
  icons/UI_Icons/dropshippicker/_panopticon.png
Labels: Map Edit, Feature

#17775 Adds proccall build mode mode
  code/modules/buildmode/submodes/proccall.dm
  icons/misc/buildmode.dmi
  tgmc.dme
Labels: Administration

#17793 Stacking debuff adjustment adjustment
  code/datums/status_effects/debuffs.dm
Labels: Fix

#17795 Heavy projectile feedback
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/ammo_types/rocket_ammo.dm
Labels: Quality of Life

#17787 Cleans out some todos
  code/__DEFINES/flags.dm
  code/__DEFINES/fonts.dm
  code/__HELPERS/game.dm
  code/_onclick/hud/screen_objects/screen_objects.dm
  code/datums/greyscale/config_types/new_mech.dm
  code/datums/mind.dm
  code/game/atoms/_atom.dm
  code/game/objects/items.dm
  code/game/turfs/walls/wall_types.dm
  code/modules/mob/living/carbon/xenomorph/evolution.dm
  code/modules/transport/tram/tram_doors.dm
Labels: Fix

#17794 Catwalk destruction now on Disarm intent [MDB Ignore]
  code/game/objects/structures/lattice.dm
Labels: Quality of Life

#17790 Griddles can now be jumped on like tables
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
Labels: Feature

#17672 Engi/Corp/SG vendor get construction pouch w/ materials included
  code/__DEFINES/loadout.dm
Labels: Balance, Fix

#17805 Lockers can now be unlocked with right click
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Feature

#17802 Bloodless smite fix
  code/modules/admin/smites/bloodless.dm
Labels: Administration

#17801 Robo Ac's/Ro's now get their job items
  code/datums/jobs/job/shipside.dm
  code/datums/outfits/shipside.dm
Labels: Fix

#17804 APCs can now be right clicked to unlock
  code/modules/power/apc/apc_attack.dm
Labels: Feature

#17761 No more allocating multiple leaders in a squad
  code/datums/jobs/squads.dm
Labels: Feature

#17803 Adds PP to VV
  code/modules/mob/mob.dm
Labels: Administration

#17744 Datumized health scans + advice and refactored analyzer gloves
  code/__DEFINES/health_scan.dm
  code/__DEFINES/loadout.dm
  code/__HELPERS/cmp.dm
  code/datums/components/chem_booster.dm
  code/datums/components/suit_autodoc.dm
  code/datums/health_scan/_advice.dm
  code/datums/health_scan/advice/chem_mix_warnings.dm
  code/datums/health_scan/advice/crit_condition.dm
  code/datums/health_scan/advice/damage_types.dm
  code/datums/health_scan/advice/implanted_embryo.dm
  code/datums/health_scan/advice/limb_warnings.dm
  code/datums/health_scan/advice/revival_tips.dm
  code/datums/health_scan/advice/special_max_health.dm
  code/datums/health_scan/advice/species_notes.dm
  code/datums/health_scan/advice/traumatic_shock.dm
  code/datums/health_scan/health_scan.dm
  code/datums/outfits/quick_load_beginners.dm
  code/game/objects/items/scanners/health_analyzer.dm
  code/game/objects/machinery/vending/marine_vending.dm
  code/modules/clothing/gloves/analyzer_gloves.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/living/carbon/human/human.dm
  tgmc.dme
Labels: Refactor, Test Merge Candidate

#17796 xeno turret targetting fix
  code/modules/xenomorph/xeno_turret.dm
Labels: Fix

#17789 Disposal units can now be emptied with right click.
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
Labels: Feature

#17738 chess analysis emoji
  icons/misc/emoji.dmi
Labels: Sprites, Feature

#17799 Contributing.md update
  CONTRIBUTING.md
Labels: GitHub

#17646 Objective Based Requisitions Points Gain.
  code/datums/gamemodes/_game_mode.dm
  code/datums/round_statistics.dm
  code/game/objects/machinery/computer/nuke_disk_generator.dm
  code/modules/requisitions/fulton.dm
  code/modules/requisitions/supply_export.dm
Labels: Balance, Feature, Test Merge Candidate, Requires Testing

#17521 Crash Vendor Points Resurrected.
  code/game/objects/machinery/computer/nuke_disk_generator.dm
Labels: Feature, Test Merge Candidate

#17772 Lays foundation for Reagent Priority in health analyzers chemical contents list
  code/__DEFINES/reagents.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/food.dm
  code/modules/reagents/chemistry/reagents/medical.dm
  code/modules/reagents/chemistry/reagents/other.dm
  code/modules/reagents/chemistry/reagents/toxin.dm
  code/modules/reagents/chemistry/recipes/other.dm
  tgui/packages/tgui/interfaces/MedScanner/data.ts
  tgui/packages/tgui/interfaces/MedScanner/index.tsx
Labels: Fix, Quality of Life

#17800 Removes extra hardppoint on pan tad model
  _maps/shuttles/minidropship_panopticon.dmm
  code/datums/shuttles.dm
  icons/UI_Icons/dropshippicker/_panopticon.png
Labels: Removal, Balance, Map Edit

#17773 Fixes holes (that let you go out of bounds) on meridian riptide
  _maps/map_files/riptide/riptide.dmm
Labels: Fix, Map Edit

#17781 Better fullscreen mode
  code/modules/client/client_procs.dm
Labels: Code Improvement

#17783 Remove some unused storage code
  code/datums/storage/storage.dm
  code/datums/storage/subtypes/bag.dm
Labels: Removal

#17785 Remove the old conflicts action
  .github/workflows/conflicts.yml
Labels: Removal, GitHub

#17798 Splits gender preference into gender and physique
  code/__DEFINES/preferences.dm
  code/_globalvars/lists/flavor_misc.dm
  code/_onclick/hud/human.dm
  code/datums/emergency_calls/retired.dm
  code/game/objects/structures/mirror.dm
  code/modules/admin/fun_verbs.dm
  code/modules/admin/topic.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  code/modules/client/preferences_ui.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/mob_transformation_simple.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/new_player/preferences_setup.dm
  code/modules/organs/limb_objects.dm
  code/modules/organs/limbs.dm
  tgui/packages/tgui/interfaces/PlayerPreferences/CharacterCustomization.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/GearCustomisation.tsx
  tgui/packages/tgui/interfaces/PlayerPreferences/Types.ts
Labels: Refactor, Fix

#17817 Hunter stealth attack consistancy
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
Labels: Balance

#17813 resisting low stacks of melting fire correctly paralyzes you
  code/datums/status_effects/debuffs.dm
Labels: Fix

#17819 Right click attack with harvesters call their proc
  code/datums/components/harvester.dm
Labels: Fix

#17786 Xeno flag -> trait conversions
  code/__DEFINES/mobs.dm
  code/__DEFINES/traits.dm
  code/_globalvars/bitfields.dm
  code/game/objects/effects/acid_hole.dm
  code/game/objects/machinery/miner.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/walls/walls.dm
  code/modules/codex/entries/mobs_codex.dm
  code/modules/mob/living/carbon/xenomorph/castes/baneling/castedatum_baneling.dm
  code/modules/mob/living/carbon/xenomorph/castes/beetle/castedatum_beetle.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/boiler/castedatum_boiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/carrier/castedatum_carrier.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/castedatum_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/dragon/castedatum_dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/castedatum_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/larva/castedatum_larva.dm
  code/modules/mob/living/carbon/xenomorph/castes/mantis/castedatum_mantis.dm
  code/modules/mob/living/carbon/xenomorph/castes/nymph/castedatum_nymph.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/puppeteer/castedatum_puppeteer.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/scorpion/castedatum_scorpion.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warlock/castedatum_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Code Improvement

#17784 Atom icon size caching
  code/__HELPERS/icons.dm
  code/__HELPERS/unsorted.dm
  code/datums/status_effects/status_effect.dm
  code/game/atoms/atom_movable.dm
  code/game/data_huds.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob_helpers.dm
Labels: Code Improvement

#17782 Refactor more playsound code
  code/datums/interior/_interior.dm
  code/game/sound.dm
Labels: Code Improvement, Refactor

#17826 Adds r76 scope to Valhalla
  code/game/objects/machinery/vending/marine_vending.dm
Labels: Feature

#17827 Melting fire self extinguish bugfix
  code/modules/mob/living/carbon/human/human_attackhand.dm
Labels: Fix

#17812 instant evacuation launch begone
  code/__DEFINES/mode.dm
  code/modules/shuttle/escape_pod.dm
Labels: Balance, Feature

#17824 Supersoldier throwing farther stim
  code/datums/actions/species_actions/prototype_supersoldier_action.dm
Labels: Feature

#17830 Surt nerf
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/clothing/modular_armor/som.dm
Labels: Balance

#17831 Xeno fire patting
  code/__DEFINES/dcs/signals/signals.dm
  code/_onclick/xeno.dm
  code/modules/projectiles/guns/_shared_ammo_objects.dm
Labels: Balance

#17810 Admins can change their ASAY colors
  code/__DEFINES/colors.dm
  code/controllers/configuration/entries/general.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/preferences_verbs.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_savefile.dm
  config/config.txt
Labels: Config Update, Administration

#17774 Warrior/warlock mech damage nerf
  code/modules/mob/living/carbon/xenomorph/castes/warlock/abilities_warlock.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/abilities_warrior.dm
  code/modules/projectiles/ammo_types/xenos/energy_xenoammo.dm
Labels: Balance

#17823 Randomize the name of taken SSD mobs
  code/__DEFINES/preferences.dm
  code/_globalvars/bitfields.dm
  code/datums/actions/observer_action.dm
  code/modules/client/preferences_ui.dm
Labels: Feature

#17615 NanoAmmo for Vehicles
  _maps/interiors/apc_cloner.dmm
  _maps/interiors/apc_medical.dmm
  _maps/interiors/apc_transport.dmm
  _maps/shuttles/minidropship_big.dmm
  _maps/shuttles/minidropship_factorio.dmm
  _maps/shuttles/minidropship_food.dmm
  _maps/shuttles/minidropship_mobile_bar.dmm
  _maps/shuttles/minidropship_outrider.dmm
  _maps/shuttles/minidropship_panopticon.dmm
  _maps/shuttles/minidropship_standard.dmm
  _maps/shuttles/minidropship_umbilical.dmm
  _maps/shuttles/minidropship_urbantower.dmm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/machinery/vending/vending_types.dm
  icons/obj/machines/vending.dmi
Labels: Map Edit, Feature

#17833 Apc's first turn off lighting then equipment
  code/modules/power/apc/apc.dm
Labels: Quality of Life

#17836 Fix drones unable to receive queen plasma
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
Labels: Fix

#17853 fix ci
  tools/ci/download_byond.sh
  tools/ci/install_byond.sh
Labels: Tools

#17846 Randomised magazine ejection offsets
  code/modules/projectiles/gun_system.dm
Labels: Feature

#17842 Buff dragon's grabbed variations by halfing the delay and nerfing the damage
  code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
Labels: Balance

#17840 Fix miners saying mineral value instead of ammount
  code/game/objects/machinery/miner.dm
Labels: Fix

#17825 Assault armor no longer uses power unless it activates
  code/modules/vehicles/mecha/mecha_actions.dm
Labels: Fix

#17854 Makes reason window in ban panel bigger
  html/browser/banpanel.css
Labels: Administration

#17857 Fix href view vv exploit for mentors
  code/modules/admin/verbs/datumvars.dm
  code/modules/admin/view_variables/topic.dm
Labels: Fix, Security Exploit

#17856 tweaks veh collision and makes it target legs on mech
  code/modules/vehicles/armored/__armored.dm
  code/modules/vehicles/armored/vehicle_collision.dm
Labels: Balance

#17855 Fixes tad preview while moving not working
  code/modules/shuttle/navigation_computer.dm
Labels: Fix

#17835 Prison areas changes
  _maps/map_files/Prison_Station_FOP/Prison_Station_FOP.dmm
  code/game/area/prison.dm
Labels: Balance, Map Edit

#17861 Fixes xeno keybindings
  code/datums/keybinding/xeno.dm
Labels: Fix

#17865 All xenos can pick up jelly now
  code/__DEFINES/traits.dm
  code/game/objects/structures/xeno.dm
  code/modules/mob/living/carbon/xenomorph/castes/behemoth/castedatum_behemoth.dm
  code/modules/mob/living/carbon/xenomorph/castes/bull/castedatum_bull.dm
  code/modules/mob/living/carbon/xenomorph/castes/crusher/castedatum_crusher.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/dragon/castedatum_dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/drone/castedatum_drone.dm
  code/modules/mob/living/carbon/xenomorph/castes/gorger/castedatum_gorger.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/castedatum_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/castedatum_hunter.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/nymph/castedatum_nymph.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/runner/castedatum_runner.dm
  code/modules/mob/living/carbon/xenomorph/castes/sentinel/castedatum_sentinel.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/spitter/castedatum_spitter.dm
  code/modules/mob/living/carbon/xenomorph/castes/warrior/castedatum_warrior.dm
  code/modules/mob/living/carbon/xenomorph/castes/wraith/castedatum_wraith.dm
  code/modules/mob/living/carbon/xenomorph/xeno_defines.dm
Labels: Balance

#17878 Fix directional attacks hitting corpses
  code/datums/elements/directional_attack.dm
Labels: Fix

#17877 SSD Widow burrowed fix
  code/modules/mob/living/carbon/xenomorph/castes/widow/abilities_widow.dm
Labels: Fix

#17863 Solid plasteel cades give correct material refund
  code/game/objects/structures/barricade.dm
Labels: Fix

#17851 Adds View latest ticket verb - allowing players to see their latest ticket
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/client/client_procs.dm
Labels: Code Improvement, Feature, Test Merge Candidate

#17867 TSX escape pod
  tgui/packages/tgui/interfaces/EscapePod.tsx
Labels: Code Improvement, UI

#17866 TSXifies cryo
  code/modules/atmospherics/machinery/components/unary_devices/cryo.dm
  tgui/packages/tgui/interfaces/CargoRequest.tsx
  tgui/packages/tgui/interfaces/Cryo.jsx
  tgui/packages/tgui/interfaces/Cryo.tsx
Labels: Code Improvement

#17869 TSXify SMES
  code/modules/power/smes.dm
  tgui/packages/tgui/interfaces/Smes.tsx
Labels: Code Improvement

#17870 TSXify Cas
  code/game/objects/machinery/computer/dropship_weapons.dm
  code/game/objects/structures/dropship_equipment.dm
  tgui/packages/tgui/interfaces/CAS.tsx
Labels: Code Improvement

#17871 TSXify portable vendor
  tgui/packages/tgui/interfaces/PortableVendor.tsx
Labels: Code Improvement, UI

#17872 TSXifies nukedisk generators
  code/game/objects/machinery/computer/nuke_disk_generator.dm
  tgui/packages/tgui/interfaces/NukeDiskGenerator.tsx
Labels: Code Improvement, Fix

#17873 TSX tadpole
  tgui/packages/tgui/interfaces/Minidropship.jsx
  tgui/packages/tgui/interfaces/Minidropship.tsx
Labels: Code Improvement, UI

#17868 CAS plane UI housekeeping
  tgui/packages/tgui/interfaces/MarineCasship.tsx
Labels: Code Improvement, UI

#17712 Makes sizzler's opaque gas transparent, increases damage on spit and bomblets
  code/modules/projectiles/ammo_types/xenos/spits_xenoammo.dm
Labels: Balance, Requires Testing

#17608 Multi z shooting mechanics
  code/__DEFINES/movement.dm
  code/modules/projectiles/projectile.dm
Labels: Feature

#17852 Fixes throw stim still being targetted
  code/datums/actions/species_actions/prototype_supersoldier_action.dm
Labels: Quality of Life

#17885 Don't run CI on pushed commits (while keeping pull requests)
  .github/workflows/ci_suite.yml
Labels: GitHub

#17881 Untied vehicle_collision from sound timer
  code/modules/vehicles/armored/__armored.dm
Labels: Fix

#17879 Adds ai nodes to the thunderdome
  _maps/map_files/generic/Admin_Level.dmm
Labels: Map Edit, Administration

#17883 Offhand icon layers under other hud objects
  code/datums/elements/riding.dm
  code/game/objects/items/weapons/twohanded.dm
Labels: Quality of Life

#17886 Health analyzer: fixes Tramadol advice popping out in nanite users
  code/datums/health_scan/advice/traumatic_shock.dm
Labels: Fix

#17876 Fixes indestructible cades exploit
  code/game/objects/structures/barricade.dm
Labels: Fix, In Game Exploit

#17821 Chat styling rework (2025 edition)
  code/__DEFINES/announce.dm
  code/__DEFINES/chat.dm
  code/__DEFINES/span.dm
  code/__HELPERS/announce.dm
  code/_onclick/hud/alerts.dm
  code/controllers/subsystem/job.dm
  code/controllers/subsystem/persistence/_persistence.dm
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  code/datums/gamemodes/campaign/rewards/campaign_asset_jobs.dm
  code/datums/helper_datums/getrev.dm
  code/datums/jobs/job/job.dm
  code/datums/jobs/job/marines.dm
  code/datums/jobs/job/shipside.dm
  code/datums/jobs/job/sons_of_mars_shipside.dm
  code/datums/jobs/job/sonsofmars.dm
  code/datums/jobs/job/survivor.dm
  code/datums/jobs/job/terragov.dm
  code/datums/jobs/job/xenomorph.dm
  code/game/atoms/atom_examine.dm
  code/game/objects/machinery/computer/nt_access.dm
  code/game/objects/objs.dm
  code/game/verbs/ooc.dm
  code/modules/admin/fun_verbs.dm
  code/modules/buildmode/submodes/advanced.dm
  code/modules/buildmode/submodes/area_edit.dm
  code/modules/buildmode/submodes/basic.dm
  code/modules/buildmode/submodes/boom.dm
  code/modules/buildmode/submodes/copy.dm
  code/modules/buildmode/submodes/delete.dm
  code/modules/buildmode/submodes/fill.dm
  code/modules/buildmode/submodes/loadout.dm
  code/modules/buildmode/submodes/proccall.dm
  code/modules/buildmode/submodes/smite.dm
  code/modules/buildmode/submodes/throwing.dm
  code/modules/buildmode/submodes/variable_edit.dm
  code/modules/mob/examine.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_attackhand.dm
  code/modules/mob/living/silicon/ai/examine.dm
  code/modules/mob/mob_verbs.dm
  tgmc.dme
  tgui/packages/tgui-panel/styles/tgchat/chat-dark.scss
  tgui/packages/tgui-panel/styles/tgchat/chat-light.scss
  tgui/packages/tgui-say/styles/colors.scss
Labels: Refactor, Test Merge Candidate

#17888 Fix untargetted projectiles runtime
  code/modules/projectiles/projectile.dm
Labels: Fix

#17894 Headset for spatial agents
  code/datums/outfits/misc.dm
  code/game/objects/items/radio/encryptionkey.dm
  code/game/objects/items/radio/headset.dm
Labels: Administration

#17890 Protein shakes and Leporazine are now in vendors
  code/game/objects/machinery/vending/vending_types.dm
  code/modules/reagents/reagent_containers/food/drinks.dm
  code/modules/reagents/reagent_containers/glass/bottle.dm
Labels: Quality of Life

#17900 RTSlike camera jump binding for AI
  code/__DEFINES/dcs/signals/signals.dm
  code/modules/keybindings/bindings_client.dm
  code/modules/keybindings/setup.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/mob.dm
Labels: Feature

#17889 Builder npc
  code/__DEFINES/ai.dm
  code/datums/outfits/npc_marines.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/ai/ai_behaviors/human_mobs/engineering.dm
  code/modules/ai/ai_behaviors/human_mobs/healing.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
  tgmc.dme
Labels: Feature

#17887 Remove codeowner review action
  .github/CODEOWNERS
  .github/workflows/codeowner_reviews.yml
Labels: Removal, GitHub

#17875 Heavily refactors the cargo UI
  code/controllers/subsystem/points.dm
  code/modules/asset_cache/assets/cargo.dm
  code/modules/reqs/supply.dm
  code/modules/reqs/supplypacks.dm
  tgmc.dme
  tgui/packages/tgui/interfaces/Cargo.jsx
  tgui/packages/tgui/interfaces/Cargo/Category.tsx
  tgui/packages/tgui/interfaces/Cargo/Menu.tsx
  tgui/packages/tgui/interfaces/Cargo/Pack.tsx
  tgui/packages/tgui/interfaces/Cargo/StaticMenus.tsx
  tgui/packages/tgui/interfaces/Cargo/constants.ts
  tgui/packages/tgui/interfaces/Cargo/helpers.ts
  tgui/packages/tgui/interfaces/Cargo/index.tsx
  tgui/packages/tgui/interfaces/Cargo/types.ts
Labels: Code Improvement, Refactor, Quality of Life

#17788 Brings back some of the april fools emotes as ghost emotes
  code/modules/mob/dead/observer/emote.dm
  code/modules/mob/mob.dm
  icons/misc/observer_emotes.dmi
  tgmc.dme
Labels: Feature, Test Merge Candidate

#17905 Missing NPC hazards
  code/modules/mob/living/carbon/xenomorph/castes/dragon/abilities_dragon.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
Labels: Feature

#17895 Hive ruler adjustment
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/xenomorph/castes/defiler/castedatum_defiler.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/castedatum_king.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/castedatum_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/abilities_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/queen/castedatum_queen.dm
  code/modules/mob/living/carbon/xenomorph/castes/shrike/castedatum_shrike.dm
  code/modules/mob/living/carbon/xenomorph/castes/widow/castedatum_widow.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  tgui/packages/tgui/interfaces/HiveStatus.tsx
Labels: Code Improvement, Refactor, Quality of Life

#17906 NPC movement improvements
  code/__DEFINES/ai.dm
  code/__DEFINES/dcs/signals/signals.dm
  code/__DEFINES/is_helpers.dm
  code/game/atoms/atom_movable.dm
  code/game/objects/items/stacks/rods.dm
  code/game/turfs/liquid_turfs.dm
  code/game/turfs/turf.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/ai/ai_behaviors/human_mobs/hazard_avoidance.dm
Labels: Fix, Quality of Life

#17915 NPC resist fixes
  code/datums/status_effects/debuffs.dm
  code/modules/ai/ai_behaviors/human_mobs/healing.dm
  code/modules/mob/living/living_defense.dm
Labels: Fix

#17914 Friendly obstacle avoidance improvement for NPCs
  code/__DEFINES/ai.dm
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
  code/modules/ai/ai_behaviors/human_mobs/human_mob.dm
Labels: Fix

#17916 Barricade material defines
  code/__DEFINES/structures.dm
  code/game/objects/items/stacks/sheets/sheet_types.dm
  code/game/objects/structures/barricade.dm
Labels: Balance

#17837 Removes intelligence computer and mech weapons from riptide ship in caves
  _maps/map_files/riptide/riptide.dmm
Labels: Removal, Map Edit

#17908 Break up arty file & mlrs is no longer a howitzer child
  code/__DEFINES/artillery.dm
  code/game/objects/machinery/artillery/boxes.dm
  code/game/objects/machinery/artillery/howitzer.dm
  code/game/objects/machinery/artillery/mlrs.dm
  code/game/objects/machinery/artillery/mortar.dm
  code/game/objects/machinery/artillery/shells.dm
  code/game/objects/machinery/mortar.dm
  tgmc.dme
Labels: Code Improvement

#17822 Nerfs easy method to instakill any full health xeno
  code/game/objects/items/explosives/grenades/bullet_grenade.dm
Labels: Balance

#17922 Monkey fixes
  code/_onclick/human.dm
  code/modules/mob/living/carbon/human/_species.dm
  code/modules/mob/living/carbon/human/species_types/monkeys.dm
Labels: Fix

#17763 Adds a cooldown for electric wire
  code/__DEFINES/cooldowns.dm
  code/modules/power/power.dm
Labels: Balance

#17917 Increase the telegraph timer for harmful weather
  code/datums/weather/weather_types/acid_rain.dm
  code/datums/weather/weather_types/ash_storm.dm
  code/datums/weather/weather_types/sand_storm.dm
Labels: Balance

#17930 Friendly mine indicator
  code/game/alternate_appearance.dm
  code/game/objects/items/explosives/mine.dm
  icons/obj/items/mines.dmi
Labels: Feature
