Repository tgstation/TerraGov-Marine-Corps, pull requests merged in 2025-10, with the labels that each got.

#18316 Fix laser carbine inhand sprites
  icons/mob/inhands/guns/energy_right_1.dmi
Labels: Sprites, Fix

#18317 Hover animation fix
  code/modules/vehicles/armored/som_tank.dm
  code/modules/vehicles/hover_bike.dm
Labels: Fix

#18297 NPC goal unsticking
  code/__DEFINES/ai.dm
  code/controllers/subsystem/advanced_pathfinding.dm
  code/modules/ai/ai_behaviors/ai_behavior.dm
Labels: Fix

#18308 BIg campaign bike
  code/__DEFINES/traits.dm
  code/datums/components/riding/riding.dm
  code/datums/components/riding/riding_vehicle.dm
  code/modules/projectiles/ammo_types/heavy_ammo.dm
  code/modules/projectiles/magazines/specialist.dm
  code/modules/vehicles/big_bike.dm
  code/modules/vehicles/hover_bike.dm
  code/modules/vehicles/vehicle_attachments/weapon_attachments.dm
  icons/obj/vehicles/big_bike.dmi
  icons/obj/vehicles/vehicle_weapons.dmi
  tgmc.dme
Labels: Balance

#18258 C4 refactor
  code/__DEFINES/dcs/signals/signals.dm
  code/game/objects/items/explosives/genghis_charge.dm
  code/game/objects/items/explosives/plastique.dm
  code/game/objects/items/radio/detpack.dm
  code/game/objects/structures/campaign_structures/destroy_objectives.dm
  code/game/objects/structures/window.dm
  code/modules/mob/living/carbon/xenomorph/castes/king/abilities_king.dm
  tgmc.dme
Labels: Code Improvement, Refactor, Quality of Life

#18322 Balloon alert audit (part 2)
  code/game/objects/machinery/camera/camera_assembly.dm
  code/game/objects/machinery/doors/firedoor.dm
  code/game/objects/machinery/kitchen/gibber.dm
  code/game/objects/machinery/kitchen/microwave.dm
  code/game/objects/machinery/pipe/pipe_dispenser.dm
  code/game/objects/machinery/vending/vending.dm
  code/game/objects/structures/barricade.dm
  code/game/objects/structures/campaign_structures/capture_objectives.dm
  code/game/objects/structures/campaign_structures/orbital_beacons.dm
  code/game/objects/structures/droppod.dm
  code/game/objects/structures/dropship_equipment.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/ladders.dm
  code/game/objects/structures/lattice.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/watercloset.dm
  code/game/objects/structures/xeno.dm
  code/game/turfs/floor_types.dm
  code/modules/admin/fun_verbs.dm
  code/modules/ai/ai_behaviors/human_mobs/helper_procs.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/modular_armor/attachments/modules.dm
  code/modules/factory/unboxer.dm
  code/modules/food_and_drinks/kitchen_machinery/griddle.dm
  code/modules/food_and_drinks/kitchen_machinery/grill.dm
  code/modules/mob/living/carbon/carbon_stripping.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/species_types/combat_robots.dm
  code/modules/mob/living/carbon/human/zombie.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivelord/abilities_hivelord.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/abilities_hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hivemind/hivemind.dm
  code/modules/mob/living/carbon/xenomorph/castes/hunter/abilities_hunter.dm
  code/modules/mob/living/carbon/xenomorph/hive_datum.dm
  code/modules/mob/living/carbon/xenomorph/life.dm
  code/modules/mob/living/carbon/xenomorph/saddles.dm
  code/modules/mob/living/carbon/xenomorph/xenomorph.dm
Labels: Grammar and Formatting

#18325 NPC escort fix
  code/modules/ai/ai_behaviors/ai_behavior.dm
  code/modules/mob/living/carbon/xenomorph/castes/spiderling/spiderling.dm
Labels: Fix

#18268 More Ravager Mutations
  code/__DEFINES/dcs/signals/signals.dm
  code/modules/mob/living/carbon/xenomorph/castes/defender/abilities_defender.dm
  code/modules/mob/living/carbon/xenomorph/castes/praetorian/abilities_praetorian.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/abilities_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/castedatum_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/mutations_ravager.dm
  code/modules/mob/living/carbon/xenomorph/castes/ravager/ravager.dm
  code/modules/mob/living/carbon/xenomorph/xeno_helpers.dm
  code/modules/mob/living/living_defense.dm
Labels: Balance, Fix, Feature

#18330 Shrap trait fix
  code/datums/elements/shrapnel_removal.dm
Labels: Fix

#18327 Crash autodoc is now 2 times faster
  _maps/shuttles/tgs_bigbury.dmm
  _maps/shuttles/tgs_canterbury.dmm
  code/game/objects/machinery/autodoc.dm
Labels: Balance, Map Edit

#18314 Remove SH-410 from normal play
  code/game/objects/machinery/vending/marine_vending.dm
  code/game/objects/machinery/vending/vending_types.dm
Labels: Removal, Balance

#18312 MP-19 ammo nerf
  code/modules/projectiles/guns/smgs.dm
  code/modules/projectiles/magazines/smgs.dm
Labels: Balance

#18298 E-pistol nerf with less stupid this time
  code/modules/projectiles/guns/energy.dm
Labels: Balance

#18255 Rebalances pyrogen plasma
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/abilities_pyrogen.dm
  code/modules/mob/living/carbon/xenomorph/castes/pyrogen/castedatum_pyrogen.dm
Labels: Balance

#18336 tgui-core update
  tgui/packages/tgui-bench/package.json
  tgui/packages/tgui-dev-server/package.json
  tgui/packages/tgui-panel/package.json
  tgui/packages/tgui-panel/settings/SettingsGeneral.tsx
  tgui/packages/tgui-say/package.json
  tgui/packages/tgui-setup/package.json
  tgui/packages/tgui/interfaces/ColorMatrixEditor.tsx
  tgui/packages/tgui/interfaces/MedScanner/index.tsx
  tgui/packages/tgui/interfaces/ParticleEdit/EntriesBasic.tsx
  tgui/packages/tgui/interfaces/PlaneMasterDebug.tsx
  tgui/packages/tgui/interfaces/Smes.tsx
  tgui/packages/tgui/package.json
  tgui/packages/tgui/stories/Input.stories.tsx
  tgui/yarn.lock
Labels: Code Improvement, Fix, UI
